### ISSUE TITLE
[runtimes] Port corrected tint black shader

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1003]
See https://github.com/EsotericSoftware/spine-runtimes/issues/992

Thanks @ivanpopelyshev 

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-sfml (does not support tint black)
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua
- [x] spine-love (does not support tint black)
- [x] spine-corona (does not support tint black)

**Comment by ivanpopelyshev** [comment]
Three patterns for you!

Simple version

![gray_alpha](https://user-images.githubusercontent.com/695831/30813464-2ee9710c-a216-11e7-98a2-e03e76f0734b.png)

All grayscale and alpha, 256x256

![pattern256](https://user-images.githubusercontent.com/695831/30813445-211079f4-a216-11e7-98f7-45afd41810f6.png)

All grayscale and alpha, [1024x1024](https://user-images.githubusercontent.com/695831/30813456-27bbc61e-a216-11e7-8200-a1b545b89b0b.png)

**Comment by ivanpopelyshev** [comment]
There's no double-tint in canvas so you can just cross it :)
