### ISSUE TITLE
[LibGDX Runtime] SkeletonAttachments Incorrectly Flipped

### ISSUE THREAD

**Issue by byron-conroy** [EsotericSoftware/spine-runtimes#1005]
I have attached a SkeletonAttachment to another skeleton and there appear to be some issues with regards to flipping. All the following screenshots are flipping along the X Axis only.

Both Main skeleton and the attachment not flipped.
![default](https://user-images.githubusercontent.com/9834063/30901882-c92add54-a3ac-11e7-9f9c-853d9525bd05.png)

Main skeleton flipped and the attachment not flipped.
![flipxnoattachment](https://user-images.githubusercontent.com/9834063/30901892-d15570f2-a3ac-11e7-9856-2242bdc0b69c.png)

Both Main skeleton and the attachment flipped.
![flipx](https://user-images.githubusercontent.com/9834063/30901900-d606521a-a3ac-11e7-9d2c-c6247086f75a.png)

**Comment by badlogic** [comment]
Thanks for reporting. I've fixed up SkeletonAttachment to behave like it should, but that required a breaking change.

Skeletons that are attached to another skeleton via a `SkeletonAttachment` now need to be updated via an alternative `Skeleton#updateWorldTransform(Bone)` method. The bone passed to this method is the bone of the parent skeleton to which the child skeleton is attached via the `SkeletonAttachment`.

You can find an updated example here https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-libgdx/spine-libgdx-tests/src/com/esotericsoftware/spine/SkeletonAttachmentTest.java#L99
