### ISSUE TITLE
Skeleton binary backward compatibility

### ISSUE THREAD

**Issue by piotrros** [EsotericSoftware/spine-runtimes#1006]
I'm struggling with some binary skeletons. 

Graphic designer updated Spine to the latest version and created several new models (for a new game). I couldn't open them (app crashed) in my app so I did runtimes update. 

Now they're working just fine, but the old ones (saved in older Spine version) don't work anymore. 

My app (on the old model) is crashing on this line (929):

`spSlotData* slotData = spSlotData_create(i, slotName, boneData);`

in SkeletonBinary.c.

As I've found out slotName is NULL, but even after fixing this (when is null replace with empty string) there are a lot more and this is going forever.

I'm using cocos2d-x btw.

So, the most intuitive solution is to re-export the old models with the latest Spine. But **some** old models don't open:

https://imgur.com/a/nd64R

(yes, we've sent a report)

So, we're stuck.
The only option, for now, is to rollback to the old Spine and remake from scratch models made in the latest version.

**Comment by pharan** [comment]
The problem to solve here is why your old project won't open in the latest Spine.
Compatibility is handled on the project/editor level, and the recommendation is always to keep your editor and runtime versions in sync.

This is especially important when using skeleton binary as that is more likely to change with the introduction of new features.

**Comment by badlogic** [comment]
Sorry for the troubles. Here's some more in-depth information on what you can do http://esotericsoftware.com/forum/Spine-editor-and-runtime-version-management-6534

You need to find out what version your old and new models use, then decide on a version all of them need to be converted to. It appears you already decided on converting the old models to the latest format. Please send the project files for the old models that crash Spine to contact@esotericsoftware.com so we can help you recover them. One quick fix would be to export them to JSON in the old Spine editor version, then import that JSON into the latest Spine editor version.
