### ISSUE TITLE
Error After using JsonRollback tool.

### ISSUE THREAD

**Issue by MMVL123** [EsotericSoftware/spine-runtimes#1007]
My 3.2.01 Json can't completely be loaded to Unity.And I try to use JsonRollback tool.
But……
ArgumentException: The requested value 'skinnedmesh' was not found.
System.Enum.Parse (System.Type enumType, System.String value, Boolean ignoreCase) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Enum.cs:692)
Spine.Unity.Editor.SpineEditorUtilities.GetRequiredAtlasRegions (System.String skeletonDataPath) (at Assets/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs:889)

JsonRollback tool.：http://zh.esotericsoftware.com/forum/Spine-editor-and-runtime-version-management-6534

spine-runtimes3.6 can‘t load complete Output Json file.

I’ve tried to changing Json like“skinnedmesh”,“weightedmesh”“weights”……The Console of Unity is also like this……Could you give me the Spine Json format of  “spine-runtimes 3.6”?

**Comment by badlogic** [comment]
The JsonRollback tool can't update your JSON from 3.2.01 to the latest version. You can find the latest version of the JSON format here http://esotericsoftware.com/spine-json-format

As I said in the other issue, please import your old JSON into the latest Spine editor, then export it again. This way you'll get the latest JSON format. If importing the old JSON into the latest Spine editor does not work, let us know.

Also, could you please post usage problems on the forums esotericsoftware.com/forum/? We try to use the issue tracker only for bug reports.

**Comment by MMVL123** [comment]
Thank you，and I‘m sorry .Please close this issue...

**Comment by badlogic** [comment]
Don't be sorry! We'd love to help as best as we can. Let me know how importing into the editor and reexporting works out for you.
