### ISSUE TITLE
[libgdx] Wrong alpha since v3.6.39

### ISSUE THREAD

**Issue by fechy** [EsotericSoftware/spine-runtimes#1008]
Since v3.6.39, the alphas are wrong, see:
https://gyazo.com/754b05ea887ec09240731d7a4fba8d8d

On the left side is the version before 3.6.39:
Notice the "wave" below the bird and over the button that it correctly transitions from full seen to invisible. 
On the right side is the new version:
Notice that the "wave" goes to a dark color instead of just disappear.

Tried the newest snapshot build and is the same result. 

I've tried different export options from Spine, different rendering on Libgdx and png compression but no good result.

Any thought of what might be?

**Comment by badlogic** [comment]
@fechy there was a bug in the renderer, I just commited a fix. Could you get the latest revision from the master repo and give that a try?

**Comment by fechy** [comment]
@badlogic indeed it works with the latest revision from the repo. 

Looking forward for the new build.
Thanks

**Comment by NathanSweet** [comment]
2 minute response time and fix, on a Saturday no less, WTG @badlogic! o/

**Comment by badlogic** [comment]
Actually fixed before issue submission.
