### ISSUE TITLE
[cocos2dx] TankExample will crash with latest cocos2d-x codes

### ISSUE THREAD

**Issue by minggo** [EsotericSoftware/spine-runtimes#1031]
I am updating cocos2d-x's Spine runtime to 3.6.39, and found the `TankExample` will crash on Mac. I haven't tested on other platforms. `BatchingExample`, `GoblinsExample`, `RaptorExample` and `SpinebodyExample` work correctly. 

I used cocos2d-x with the [commit](https://github.com/cocos2d/cocos2d-x/commit/b53eb252005ee92773f6cd9f66191cf99ad2320a), which is the latest codes.

Edit: my environment:

- macOS: 10.13
- Xcode: 8.3.3

Edit: works on linux, Windows, Android, iOS simulator.

**Comment by minggo** [comment]
TankExample works on iOS simulator.

**Comment by minggo** [comment]
And it works on Windows, linux and Android too. Only crash on macOS, the crash screen is 

<img width="922" alt="screen shot 2017-11-01 at 2 44 21 pm" src="https://user-images.githubusercontent.com/488203/32263105-37d38ec8-bf13-11e7-84fd-8abc94784487.png">

Steps to reproduce it:

* clone [cocos2d-x](https://github.com/cocos2d/cocos2d-x) and update submodules
* merge [the PR](https://github.com/cocos2d/cocos2d-x/pull/18427)
* run `download-deps.py` to download 3rd party libraries
* open `build/cocos2d_tests.xcodeproj`
* select `cpp-tests Mac` and run
* click `43: Node: Spine` and click back icon
* then it will crash

**Comment by badlogic** [comment]
Thanks for reporting, I'll take a look asap.

**Comment by badlogic** [comment]
I've updated our sample to cocos2d-x 3.16, the last official release. I can not reproduce the crash of the tank example on any platform.

My guess is, that the tank.json file you ship in cocos2d-x is exported from an older Spine version, and thus incompatible with the loader. You can find the latest exports here https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/examples

**Comment by badlogic** [comment]
Also, you MUST include our copyright notices in your repo if you copy our code and assets! As stated before, we'd prefer if you didn't include Spine in the cocos2d-x repository, as it confuses users and the runtime included in the cocos2d-x repo is usually outdated.

**Comment by minggo** [comment]
@badlogic thanks to fix it.

The copyright notices is here: https://github.com/cocos2d/cocos2d-x/blob/v3/licenses/LICENSE_spine.txt

If cocos2d-x doesn't include spine runtime, then it is hard to generate lua/js binding codes.

**Comment by badlogic** [comment]
@minggo thanks, but the license file only covers the code. It does not cover the sample skeletons you also have in your repository. Each of these has its own license file. Sorry for the extra work, but please add those license.txt files as well.

I understand the issue with the lua/js bindings. However, as it stands, even your latest update already misses some essential bug fixes.

**Comment by minggo** [comment]
tank.json is replaced with tank-pro.json which is shift in spine runtime 3.6.39. I think you should enable `Address Sanitizer` to catch the crash like this:

* Producet -> Scheme -> Edit Scheme
* Diagnostics -> Addres Sanitizer

It will catch invalid pointer access ASAP.

Sorry, i will add the license of sample skeletons ASAP.

**Comment by minggo** [comment]
@badlogic sorry, should  i add all the licenses under [this folder](https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/examples)? Or is there a license for all  sample skeletons?

Thanks.

**Comment by badlogic** [comment]
@minggo it seems all the skeletons you include are ours, so including this single license file in the spine resources folder in your tests is sufficient https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/examples/tank/license.txt

I found the bug that makes loading crash on macOS thanks to address sanitizer! Thanks for the hint, see this commit for the fix https://github.com/EsotericSoftware/spine-runtimes/commit/361378b2750841955e0643d66594abe46d81e90d

**Comment by minggo** [comment]
@badlogic thanks to fix it.

I updated spine runtime license and added resource license in https://github.com/cocos2d/cocos2d-x/pull/18438.
