### ISSUE TITLE
[cocos2dx] Premultiplied alpha

### ISSUE THREAD

**Issue by tiagomartines11** [EsotericSoftware/spine-runtimes#1033]
Using the latest cocos2dx and spine-runtimes 3.6.39, I cannot use PMA (or forcefully not use it) properly.

I followed the guidelines from #809 and I tried both proposed solutions.
Solution 2 renders my animation properly, but I cannot give up PMA on my project globally. 
Solution 1 does not work and I can't figure out why. I see black shadows on the edges of my assets where they should subtly fade out instead.

**Comment by badlogic** [comment]
By latest, are you talking about the cocos2d-x 3.16 release, or the latest commit from their master branch? I'm afraid this is more of an issue with cocos2d-x than with Spine itself. I'm not sure what we can do on our end to fix this.

**Comment by badlogic** [comment]
I dug a bit deeper, and it appears PMA is still supposed to work as before in cocos2d-x. Could you please check if this method is executed for your images? https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/CCImage.cpp#L2452. This will be called for solution 1 to make all the loaded images PMA.

SkeletonRenderer has a field `_premultipliedAlpha` which you can set via `setOpacityModifyRGB`. If set to true, then PMA blend modes are set in OpenGL. The default is true. You'll need that for solution 1 to work.

**Comment by tiagomartines11** [comment]
Thank you very much for looking into this. After a lot of tinkering, I found a strange solution! 
The original PMA output from Spine produces odd artifacts when leaving `CC_ENABLE_PREMULTIPLIED_ALPHA` on and using `setOpacityModifyRGB(true)`.
But after losslessly compressing this PNG file with ImageOptim, it started rendering properly. I believe the indexing process that happens during compression might have changed the way cocos loads the texture. 
While this solves my issue, please let me know if you would like to debug this further. I can email you the assets for investigation.

**Comment by badlogic** [comment]
That is an interesting find. I'd like to get to the bottom of this, please
send me your assets, contact@esotericsoftware.com

**Comment by fred1024** [comment]
We had some troubles with our premultiplied alpha assets ... so i tried this and it seems to work.. could you confirm it is ok ?

with opacityModifyRGB(true)

`
const char* TWO_COLOR_TINT_PMA_FRAGMENT_SHADER = STRINGIFY(
\n#ifdef GL_ES\n
precision highp float;
\n#endif\n
                                                           
varying vec4 v_light;   // a pma value (as skeletonRenderer opacityModifyRgb() must be true to work properly with pma)
varying vec4 v_dark;    // a non-pma value (dark alpha should be one anyway)
varying vec2 v_texCoord;
                                                           
void main() {
    vec4 texColor = texture2D(CC_Texture0, v_texCoord);     // input PMA texture

    float alpha = texColor.a * v_light.a;   // new alpha will be texture alpha * light.alpha

    gl_FragColor.a = alpha;
    
    float q = ((( texColor.a - 1.0 ) * v_dark.a) + 1.0);
    
    gl_FragColor.rgb = clamp((q * texColor.a - texColor.rgb) * v_dark.rgb * v_light.a + (texColor.rgb * v_light.rgb), 0.0, 1.0);
}
);
`
