### ISSUE TITLE
[Runtimes | libgdx] Bounding box attachments from skins aren't showing up as attached when skin is changed

### ISSUE THREAD

**Issue by heschlie** [EsotericSoftware/spine-runtimes#1039]
I'm not 100% sure if this is by design or not so apologies if this is expected behavior. We have a Bounding Box Attachment (bba) which is tied to a skin. when we switch to that skin in game the bba doesn't seem to transfer over and get attached to the proper slot. Which means when we call `SkeletonBounds.polygon()` on it we get `null` back and future operations cause an NPE.

I'm currently working around it by attaching that bba every time we start that animation:

```java
spine.skeleton.setSkin("sword");
bba = (BoundingBoxAttachment)spine.skeleton.getAttachment("sword", "sword");
spine.skeleton.findSlot("sword").setAttachment(bba);
```

While not a huge annoyance it seems to me this should work without the above juggle.

**Comment by badlogic** [comment]
`Skeleton.setSkin` only sets attachments if a corresponding attachment was set in the old skin. Assuming your bounding box attachment is in the new skin and not in the old skin, you have to call `Skeleton.setSlotsToSetupPose` as per the `Skeleton.setSkin` Javadocs.

I'm closing this out for now if you don't mind but will of course re-open if that doesn't fix the issue.

**Comment by heschlie** [comment]
@badlogic thanks for the quick reply, that did indeed fix it.
