### ISSUE TITLE
Can i use it for commercial without any purchasing?

### ISSUE THREAD

**Issue by Gamzic** [EsotericSoftware/spine-runtimes#1040]
Can i use runtime in my games for commercial without buing spine pro? If not, then please ask me, is the Essential Licence enough to develop commercial games using only your rintimes? Thank you)

**Comment by badlogic** [comment]
You need a Spine license to use the Spine runtimes. If you make more than $500,000USD in annual revenue, you must license Spine Enterprise, otherwise Spine Professional or Spine Essential are fine.
