### ISSUE TITLE
[UE4] Generation of huge infinite number of File in DerivedDataCache

### ISSUE THREAD

**Issue by AndreaDev237** [EsotericSoftware/spine-runtimes#1041]
Hello,
I notice a problem with SpineSkeletonRender Component 
When an actor has SpineSkeleton Render + SpineSkeletonAnimation component with Atlas and data set the engine generate infinite files called "PHYSX_[alphanumeric string]PHYSXPC_[more text].udd" inside the Folder DerivedDataCache of engine.

I notice that because on my SSD of 1TB the folder contains 27 milions of this file and a total size of 600gb

Another similar Problem is reported here on AnswerHub related to unreal procedural mesh component: https://answers.unrealengine.com/questions/669057/proceduralmeshcomponent-creating-files-to-derivedd.html
After read this i see your plugin use RuntimeMeshComponent similar to unreal mesh procedural component.

This issue can potentialy harm SSD(major) / HDD life for the number of Write on disks.

I found the only possible fix for now is to unset SpineSkeletonAnimation Data and Atlas and set at begin play on the game, in this way the Engine not generate any files during play test.
Change params / settings on SpineSkeletonRender component not fix the problem. 

i made some Screenshot to
![image](https://user-images.githubusercontent.com/2900985/33226578-a09b3218-d191-11e7-8c98-6ca734b4511a.png)
![image](https://user-images.githubusercontent.com/2900985/33226588-c8c5a048-d191-11e7-865c-4eff59f01385.png)

Screenshot made after 20-30 second each other.
i hope you can find and fix this problem because is silent and i notice that after 4 months of use.

PS: i'm still analyze problem and code, if i will find something useful i report here immediately.
Thanks again!

**Comment by badlogic** [comment]
Thanks for reporting. That is an extremely nasty issue. I'll try to figure out what writes all these files. Given the file names, it appears that the physics integration is at fault.

**Comment by badlogic** [comment]
See http://esotericsoftware.com/forum/UE4-Performance-problem-example-project-current-branch-9482

**Comment by badlogic** [comment]
I've unsuccesfully tried to come up with a solution to this. Sadly, there is none. It seems the collision mesh API of UE4 simply can't be bend to not generate those derrived files. I've now disabled collision mesh generation in the `SpineSkeletonRendererComponent`.

The better solution to this issue is to create a collision shape yourself and attach it to the default scene root.
