### ISSUE TITLE
TwoColorPolygonBatch should implement Batch

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1043]
See http://esotericsoftware.com/forum/Slot-getDarkColor-Tint-Black-9628

**Comment by piotr-j** [comment]
Ive figured ill take a look at this, might need it in the future. Ive encountered one problem, Sprites. Since its kinda pointless without adding support for dark for other stuff, sprites verts no longer match. Also, another freaking batch...  any ideas for what, if anything, to do anout that?

**Comment by badlogic** [comment]
Welp, no way around just manually transfering Sprite vertices to the batch
buffer, setting the dark color of each vertex to 0 :/
