### ISSUE TITLE
[ue4] Add UMG support

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1047]
Once this is implemented, use it in the assets editor, see https://github.com/EsotericSoftware/spine-runtimes/issues/1291

**Comment by sumday** [comment]
How about this issue now?

**Comment by Rainfarer** [comment]
Are there any news regarding this one?

**Comment by motifgames** [comment]
We are waiting this feature 1 year. I want to know release schedule or roadmap. It is VERY IMPORTANT about Our Team and Project.

**Comment by GitHub-NetFly** [comment]
There is no progress yet?

**Comment by GitHub-NetFly** [comment]
Is this problem reopened? I'm still working on the problem that the Basic renderer can't render mesh..Once there is a result... I will continue to discuss it with you here.

**Comment by GitHub-NetFly** [comment]
In communication with Epic engineers, I have made some progress on this matter, the effect is as follows:
![1](https://user-images.githubusercontent.com/6991952/54423124-e2384000-474a-11e9-86df-fb9558c70a52.png)

![2](https://user-images.githubusercontent.com/6991952/54423133-e6fcf400-474a-11e9-9e06-bc3e6c0aef79.png)


There are probably two problems. 1. The MaterialDomain used on the UI should use UserInterface, which may result in a UI version. All Blend types need to recreate a UI material version.
![334575-materialdomain](https://user-images.githubusercontent.com/6991952/54325163-c09c6300-463b-11e9-99ae-72541d94570e.png)

2. The coordinates of the vertices Y and Z need to be interchanged. In addition, the approach I take here is that Y takes a negative value.
![334576-vertadd](https://user-images.githubusercontent.com/6991952/54325195-e6296c80-463b-11e9-836a-6777faba875e.png)

Then re-map the vertices to the corresponding position according to the size to be drawn.
![334577-remapvert](https://user-images.githubusercontent.com/6991952/54325214-03f6d180-463c-11e9-9b71-0233d201fc00.png)

Related code：
[code](https://drive.google.com/open?id=1yFlW-E5njpMU5Afq-Yw3ReWK_j2EyUnH)

The code is for functional reference only and is not recommended for formal production use. It is not optimized and organized.

The principle of this rendering is to perform 2D skeletal animation in Spine's library, then get the position of the new vertices on each Slot, and then use these vertices to generate ProceduralMesh for rendering, one Slot corresponds to a Section. For Slate, it is to follow the MeshWidget approach, update the Mesh vertex data, and then draw the faces of these vertices in the OnPaint process..

**Comment by badlogic** [comment]
@GitHub-NetFly I think I've fixed all issues now. You can find the latest updates in the 3.8-beta branch. Please let me know if you run into any other issues. Otherwise I'll close this out.

**Comment by GitHub-NetFly** [comment]
> @GitHub-NetFly I think I've fixed all issues now. You can find the latest updates in the 3.8-beta branch. Please let me know if you run into any other issues. Otherwise I'll close this out.

@badlogic  Thank you very much, through the test, the problems I have encountered before have been solved very well, I agree to close this Issue. If there are other problems, I will continue to follow up.

**Comment by badlogic** [comment]
Closing this out. Thanks for your help!
