### ISSUE TITLE
[Unity]Every Frame have GC when Using SkeletonAnimator

### ISSUE THREAD

**Issue by lsc1414** [EsotericSoftware/spine-runtimes#1050]
![image](https://user-images.githubusercontent.com/5005412/34143130-1fe55c32-e4c6-11e7-82bf-9469ac5594af.png)

**Comment by pharan** [comment]
What Unity version?

**Comment by lsc1414** [comment]
5.6.3f1

**Comment by pharan** [comment]
There was fortunately already an optimization in place. It accidentally didn't encompass 5.6, where it should have.

The fix will be applied soon. Thanks for reporting!
