### ISSUE TITLE
[Unity] SkeletonAnimation.Initialize should not set animation

### ISSUE THREAD

**Issue by MichalBerlinger** [EsotericSoftware/spine-runtimes#1052]
When switching skeleton data asset and using SkeletonAnimation.Initialize(true) you might run into an issue, that new skeletonData animations don't have current _animationName, and you can't set new AnimationName before Initialization because those ways it is not available either.

Steps to reproduce:
1) Create SkeletonAnimation with one asset
2) In runtime, use script to update this SkeletonAnimation with new data:
`skeletonAnimation.ClearState();
skeletonAnimation.skeletonDataAsset = newSkeletonDataAsset;
skeletonAnimation.Initialize(true);`
3) if new asset do not share the same animation as original asset there will be error on AnimationState.cs line 446 called from SkeletonAnimation line 153

So my two options how to fix that:
1) SkeletonAnimation line 153: don't set the animation and let it do the user manually after initialization
2) Add new optional parameter animationName that will assign local _animationName to new value before starting the animation.

Without this, I am not able to switch data assets that don't share same animation name.

**Comment by pharan** [comment]
Setting the initial animation according to what's serialized is for skeletons that don't have code. Sometimes skeletons are just there for visuals and you shouldn't need to add an extra component for it.

That it will throw an exception if the _animationName is incorrect was a problem even if you weren't switching out the skeletonDataAsset, so we're handling that either way:
https://github.com/EsotericSoftware/spine-runtimes/commit/613b098b53ce4d8e604fd40c46958a1c8796cfda
https://github.com/EsotericSoftware/spine-runtimes/commit/5be75c9f6df3d9c10583a1a1fd740e30fadf9c2a

Note that switching out the skeletonDataAsset makes you pay the setup/initialization performance cost again. In some cases, it makes more sense to just have extra GameObjects per skeletonDataAsset you need to use.

**Comment by MichalBerlinger** [comment]
So I downloaded the latest version from repository, and it works now. Thanks for the fix!
