### ISSUE TITLE
[UE4] "The following modules are missing ..."

### ISSUE THREAD

**Issue by yeti25660** [EsotericSoftware/spine-runtimes#1054]
Hello,

I have problem to launch my level without error.
Despite I was following all instruction in http://esotericsoftware.com/spine-ue4 I've always trouble.

![image](https://user-images.githubusercontent.com/8846054/34320126-9ce6a7b6-e7f2-11e7-9170-29eace6a1525.png)

And when I click on yes,

![image](https://user-images.githubusercontent.com/8846054/34320131-f1d57c70-e7f2-11e7-87f5-387a3972edae.png)

![image](https://user-images.githubusercontent.com/8846054/34320132-f5fd1fb0-e7f2-11e7-9663-3e7d81bd142f.png)

I use 4.16.3 version

![image](https://user-images.githubusercontent.com/8846054/34320153-87a9af64-e7f3-11e7-9603-f601008951b3.png)

**Comment by badlogic** [comment]
Could you show me the build log?

**Comment by badlogic** [comment]
@yeti25660 I'll re-open once you provide me with the requested information.
