### ISSUE TITLE
[threejs] MeshBasicMaterial not support vec4 for color attribute

### ISSUE THREAD

**Issue by robotcity** [EsotericSoftware/spine-runtimes#1066]
I encountered the wrong animation, I had to write my own shader:
`
let SpineMaterial = new THREE.ShaderMaterial( {
        uniforms: {
            map    : {type: 't',  value: null },
        },
        vertexShader: [
            'attribute vec4 color;',
            'varying vec2 vUv;',
            'varying vec4 vColor;',
            'void main() {',
                'vUv = uv;', 
                'vColor = color;',
                'gl_Position = projectionMatrix*modelViewMatrix*vec4(position,1.0);',
            '}'].join(''),
        fragmentShader: [
            'uniform sampler2D map;',
            'varying vec2 vUv;',
            'varying vec4 vColor;',
            'void main(void) {',
                'gl_FragColor = texture2D(map, vUv)*vColor;',
		    '}'].join(''),
		side         : THREE.DoubleSide,
		transparent  : true,
	});
`
and replaced in SkeletonMesh.ts (58):
`
let material = this.material = SpineMaterial.clone();
`
and in (135): 
`
mat.uniforms.map.value = texture.texture;
`
then everything worked.

**Comment by badlogic** [comment]
Could you show us how to reproduce the issue?

**Comment by robotcity** [comment]
in spine there is an example - powerup with the animation "bounce", in threejs the stars are not correct.

**Comment by badlogic** [comment]
Thank you, we'll investigate.
