### ISSUE TITLE
[Unity] Skeleton Utility Bones lag slightly behind what's being rendered

### ISSUE THREAD

**Issue by fonograph** [EsotericSoftware/spine-runtimes#1071]
To reproduce:

* Download 3.6 Spine runtime examples.
* Create new project, and drag in dragon_SkeletonData from the Examples/Spine folder as a Skeleton Animation.
* Set animation to flying and turn on looping.
* Add SkeletonUtility component.
* Spawn Hierarchy (Follow).
* In the hierarchy, go down to tail6 and select so you can see the transform gizmo in the scene view.
* Play the scene, and step through it frame by frame.
* You will see the transform gizmo lag slightly behind where the tip of the tail appears to be. This is most noticeable at the apex of the tail's movement, when it starts moving down (see the attached screenshot).

If I change Update() SkeletonAnimation.cs to do _UpdateLocal() _after_ skeleton.UpdateWorldTransform(), the problem is resolved with no evident side effects. (See the second screenshot -- same frame in the animation, but everything is where it should be.) However, the Spine runtime logic is pretty deep and I'm no expert.

![Incorrect Skeleton Utility Bone transform](https://user-images.githubusercontent.com/4312895/35592879-5e37c7d6-05dc-11e8-8901-3c84338e1ad2.png)

![After switching the order of operations](https://user-images.githubusercontent.com/4312895/35592911-75474a00-05dc-11e8-9e21-78c012770da9.png)

**Comment by pharan** [comment]
Thanks for the detailed steps.
We'll take a look at it.

The order of UpdateLocal, UpdateWorld and UpdateComplete events are specific to their sequence relative to AnimationState.Apply and Skeleton.UpdateWorldTransform. So reordering isn't quite the solution.

But you're right that SkeletonUtility uses those events. More likely, SkeletonUtility needs to perform its follow operation on a different event based on certain conditions.

**Comment by pharan** [comment]
I found the problem.
If you didn't use constraints for the target bones, the fix is straightforward.
Otherwise, there's an extra user checkbox to be added, and fix to be tested.

**Comment by pharan** [comment]
The fixes are committed. It'll be included in the next unitypackage update. Thanks again for reporting!

**Comment by fonograph** [comment]
@pharan np, thanks for the quick fix!
