### ISSUE TITLE
[AS3/Starling] Event string, int & float values are missing

### ISSUE THREAD

**Issue by neuronix** [EsotericSoftware/spine-runtimes#1074]
Hi,

The event parameters are always set to the default values:
event.data.stringValue = ""
event.data.intValue = 0
event.data.floatValue = 0

JSON export is correct as you can see below

```
                      "events": [{
				"time": 0,
				"name": "sound_fire"
			}, {
				"time": 0.1667,
				"name": "1",
				"string": "fire"
			}, {
				"time": 0.1667,
				"name": "sound",
				"string": "fire"
			}, {
				"time": 0.1667,
				"name": "sound_fire",
				"string": "fire"
			}, {
				"time": 0.3333,
				"name": "1",
				"int": 5,
				"string": "fire"
			},
```

But as you can see in the test app log:

"onEvent:", track, event.data.name, event.data.stringValue, event.data.intValue, event.data.floatValue

gives:
onEvent: 0 sound_fire  0 0
onEvent: 0 1  0 0
onEvent: 0 sound  0 0
onEvent: 0 sound_fire  0 0
onEvent: 0 1  0 0
onEvent: 0 sound  0 0
onEvent: 0 sound_fire  0 0
onEvent: 0 1  0 0
onEvent: 0 sound  0 0
onEvent: 0 sound_fire  0 0
onEvent: 0 1  0 0

Meanwhile, using the name as a hack.

Kind regards

**Comment by badlogic** [comment]
`event.data` is the setup pose event data, not the data keyed in the animation. Use this `event.intValue`, `event.floatValue`, `event.stringValue`. 

```
skeleton.state.onEvent.add(function(entry : TrackEntry, event : Event) : void {
   trace(entry.trackIndex + " event: " + entry.animation.name + ", " + event.data.name + ": " + event.intValue + ", " + event.floatValue + ", " + event.stringValue);
});
```

You can see it working as intended in `SpineboyExample`.

**Comment by neuronix** [comment]
Thank you for the clarification and sorry for the confusion! :)
