### ISSUE TITLE
[AS3/Starling] Potential performance optimization for batching

### ISSUE THREAD

**Issue by neuronix** [EsotericSoftware/spine-runtimes#1080]
Hi guys!

We have found a potential optimization in SkeletonSprite.as, by adding an if to

Line 213 Before
`painter.state.blendMode = blendModes[slot.data.blendMode.ordinal];`

Line 213 After
`if (mesh.color) painter.state.blendMode = blendModes[slot.data.blendMode.ordinal];`

This has improved batching and largely reduced draw calls in our animations since our artist often hides items with opacity as it's apparently easier to animate and said items often have different blendmodes.

Could this cause any issue I'm unaware of?

Kind regards,

Nx

**Comment by badlogic** [comment]
That kind of works, but will fall apart if `mesh.color` is != 0, which I assume can be the case quite a bit, i.e. rgb are set to some value, but alpha is set to 0.

It is better to check the alpha component for 0, then skip rendering of that attachment/slot all together. E.g. in line 160 (3.7-beta branch, but can be applied in 3.6 branch as well):

```
a = slot.color.a * attachmentColor.a; // as before
if (a == 0) {
   clipper.clipEndWithSlot(slot);
   continue;
}
```

**Comment by neuronix** [comment]
Thanks @badlogic  ! We have tested the proposed fix and it works like a charm! :)

**Comment by badlogic** [comment]
Cool :) No need to close the issue, I gotta add this to the source as well.
