### ISSUE TITLE
[AS3/Starling] Add support for whitespace trimming in atlases

### ISSUE THREAD

**Issue by neuronix** [EsotericSoftware/spine-runtimes#1081]
Hi guys,

We have a series of animations we'd like to batch in a big atlas for performance. The issue we have is that if we enabled whitespace trimming in the atlas, the animations no longer work. Is there a way to enable this? Is there plan for handling trimming? How hard would it be to implement it?

I gave a quick look at the 3.7 beta branch and unless I'm mistaken I didn't see any related changes. 

Thanks :)

**Comment by badlogic** [comment]
That's actually not quite trivial and I currently don't have the resources to implement it in the short term I'm afraid. But let's keep this issue open and I'll try to get to it when I find some spare time.

**Comment by badlogic** [comment]
Wait, I'm an idiot. Stripping should work in Starling. Can you send me an example that breaks? You can share confidential assets via contact@esotericsoftware.com (Please reference this issue in your email).

**Comment by PierrotLL** [comment]
Hi badlogic, I work with neuronix :)

I took as example the goblins in spine-starling-example.
I re-packed the atlas with TexturePacker using params "--trim-mode Trim --enable-rotation --padding 2"
You can download the resulting atlas here : https://gist.github.com/PierrotLL/c0193352d8368afd55110fa8b218b836
As you can see (using the spine-starling-example project), the eye-blinking animation is broken.

If I pack the atlas with params "--trim-mode None --disable-rotation", the animation works fine.

Thanks a lot for your reactivity :)

**Comment by PierrotLL** [comment]
I noticed that MeshAttachment.regionOffsetX/Y is set but never used.

**Comment by badlogic** [comment]
Finally had some time to look into this. Turns out we don't support white-space trimming for meshes at the moment. This is as much a runtime problem as it is an editor problem. We have an issue for this on the editor tracker, closing this down.
