### ISSUE TITLE
[ue4] Update to 4.19

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1091]
We need to wait for RuntimeMeshComponent to work with 4.19. Seems to be a major change. https://github.com/Koderz/RuntimeMeshComponent/issues/87

**Comment by supersaiyansubtlety** [comment]
Will an older release of the runtimes work with the current versions of Unreal Engine and Visual Studio 2017 in the mean time?

**Comment by NuclearCookie** [comment]
No, spine is broken with UE4.19
If you want spine, use UE4.18 or lower..

**Comment by supersaiyansubtlety** [comment]
Will I have to use the next to most recent version of spine runtimes, 3.6.32, with UE4.18?

**Comment by NuclearCookie** [comment]
From the readme in spine-runtimes/spine-eu4:
https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-ue4

> Spine version
> spine-ue4 works with data exported from Spine 3.6.xx.

**Comment by badlogic** [comment]
I've replaced the dependency on RuntimeMeshComponent with the UE4 built-in ProceduralMeshComponent. The runtime is now compatible with 4.19, see the 3.7-beta-ue4-cpp branch. **NOTE**: that branch also contains a rather big change in that the underlying Spine runtime is now C++ based! If you are in production, you may want to make sure you test this in a separate project.

**Comment by NuclearCookie** [comment]
Hey @badlogic the RMC has been updated to support 4.19
Are you planning on using it again, or are you sticking with PMC?

**Comment by badlogic** [comment]
@NuclearCookie good question. Given our recent experience with RMC, I'm unsure if we should take the gamble again and include it. While PMC does not support two color tinting, it is at least supported by Epic, so we can be somewhat sure it will continue working in the future. RMC has proven to be a bit unstable when it comes to supporting the latest Unreal versions (not a knock on the author, it's a spare time project of his after all).

**Comment by NuclearCookie** [comment]
From the documentation of RMC: 
> The RMC is also nearly 100% compatible with the ProceduralMeshComponent, while adding many features above what the PMC offers.

Would it be possible to easily allow both? For example like this:
```
#if USE_RMC
RuntimeMeshComponent MeshComponent;
#else
ProceduralMeshComponent MeshComponent;
#endif
```

This way, there's a good fallback if this happens again in the future, but while it works, we can benefit from the reduced memory footprint and improved performance of RMC :)

**Comment by badlogic** [comment]
It's not quite that easy. We need to have separate Materials depending on what component we use. Also `SpineSkeletonRendererComponent` derives from PMC so it itself is a scene component. Finally, RMC would have to be added to the build either by default, or by manual user action, which can be a bit of a quagmire as well.

I think the best option is to have to components, one using PMC, one RMC. There will be some minor code duplication (which can be factored out into a set of shared functions).

I'm also not quite sure if the reduced memory and improved performance benefits of RMC are real. At least on the memory side, PMC in 4.18+ doesn't look any worse than RMC.

Think the above makes sense? If so, could you open an issue for it?

**Comment by NuclearCookie** [comment]
It makes sense!

If you don't see any reason for switching back to RMC, I won't make an issue about it. 
We'll do some performance testing with the new version soon.

Thanks for the detailed reply!
