### ISSUE TITLE
Values intValue, floatValue and stringValue are parsed directly in the event, instead of in event.data

### ISSUE THREAD

**Issue by Friksel** [EsotericSoftware/spine-runtimes#1100]
Hi there, I'm using the pixi-spine runtime and just found some strange behaviour in the event-object according to the event data ( pixijs/pixi-spine#237). Looking at these official runtimes as a reference the same thing seems to happen in these ts-runtimes too. So I therefore post the issue here as well:

Both the `event`-object as well as the `eventData` object do have the values `intValue`, `floatValue` and `stringValue` inside. Like seen here:
https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-ts/core/src/Event.ts
https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-ts/core/src/EventData.ts
But in Spine editor only one set of these three values can be set. 

So this is how each event-object looks like in the ts-runtime (same as pixi-spine runtime):
![event](https://user-images.githubusercontent.com/3089978/38670517-4a024bc4-3e49-11e8-89f6-9b9a805c6892.JPG)
And this is the data-object within:
![eventdata](https://user-images.githubusercontent.com/3089978/38670519-4b8f2e30-3e49-11e8-9560-93cb4046b063.JPG)

But I would expect to find all custom values (and the event name) inside the `event.data` object, not directly in the `event`-object. Or else; all data values (including the event-name) directly inside the `event`-object itself, having no data-object at all.

This looks wrong to me since we're having redundant data in each event that will never be set to actual data and therefor never used. But I might be missing something here?

**Comment by badlogic** [comment]
It's not wrong. `EventData` contains the default values for the event in the setup pose. When you add an animation to a skeleton, and key an event, you can set values of these properties specifically for this key of the event, which can deviate from the default values.

**Comment by Friksel** [comment]
Ah I see. That's actually very clever and useful. Thanks!
