### ISSUE TITLE
[spine-ts] incorrect canvas size when using spine-widget

### ISSUE THREAD

**Issue by Shiu** [EsotericSoftware/spine-runtimes#1101]
Canvas size is much larger than the actual skeleton size. 
See http://www.fainted.dk/playtest/plays.html

Attached project was created with Spine 3.7.15-beta
[plays.zip](https://github.com/EsotericSoftware/spine-runtimes/files/1907947/plays.zip)

**Comment by erikari** [comment]
I see in your code that you set the canvas to be that size.
```
.plays {
    width: 1000px;
    height: 1000px;

}
```
What do you expect to happen? The skeleton to scale up?

Documentation says:

> data-scale: optional, the scaling factor to apply when loading the .json file. Defaults to 1 if omitted. Irrelevant if data-fit-to-canvas is true.

> data-fit-to-canvas: optional, whether to fit the animation to the canvas size or not. Defaults to true if omitted, in which case data-scale, data-x and data-y are irrelevant. This setting calculates the setup pose bounding box using the specified skin to center and scale the animation on the canvas.

So I guess the skeleton should be bigger since you set a specific size for the canvas?

**Comment by Shiu** [comment]
expected is the skeleton should fit inside the canvas since data-fit-to-canvas is true. Bounds might not be calculated correctly. 

FWIW, setting manual scale does not give the desired result either.

**Comment by Shiu** [comment]
The issue was caused by a scale key being set on the root bone. Root bone was hidden, so the key didn't show up in dopesheet. Removing the key, fixes the issue

Can close issue if this is the expected behavior.
