### ISSUE TITLE
[Starling] newRegionAttachment's UV doesn't display correctly

### ISSUE THREAD

**Issue by jimmymjing** [EsotericSoftware/spine-runtimes#1107]
Hello,
I'm using Starling framework. After upgrading to the latest SDK, the RegionAttachment's UV doesn't display  subtexture correctly if the texture atlas allowing 90 degrees rotation. I'm using TexturePacker (CodeAndWeb) to generate atlas.

**Comment by badlogic** [comment]
Could you please provide me with a sample project to reproduce the issue?

**Comment by badlogic** [comment]
@jimmymjing I'm closing this out. Please submit a new issue if you have a reproduction case for us.

**Comment by jimmymjing** [comment]
Hello, I will make some time this weekend and submit a sample project. I'm sorry. Actually just package textures using texturepacker(codeNweb ) with rotation enabled will duplicate the issue, but I will submit a sample soon.
