### ISSUE TITLE
[ts] Extra tabs

### ISSUE THREAD

**Issue by ivanpopelyshev** [EsotericSoftware/spine-runtimes#1108]
https://github.com/EsotericSoftware/spine-runtimes/blob/3.7-beta/spine-ts/core/src/PathConstraint.ts#L93
https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-ts/core/src/PathConstraint.ts#L93

**Comment by badlogic** [comment]
God damn it, I told my editor to remove whitespace :D Cheers, fix is incoming along with internal changes to PathConstraint, see https://github.com/EsotericSoftware/spine-runtimes/issues/1109
