### ISSUE TITLE
[unity] Empty preview window when selecting SkeletonData

### ISSUE THREAD

**Issue by Rennan24** [EsotericSoftware/spine-runtimes#1110]
Upon upgrading to Unity 2018.1.0f2 I noticed that when I select a SkeletonData asset and look in the preview window the skeleton does not show up, It was working fine when I was using it 2017.3.0f3 but for some reason it broke in the new version.

This is what it looks like in 2017.3.0f3
---
![unity_2018-05-04_16-56-59](https://user-images.githubusercontent.com/20914286/39657464-e9a6cefa-4fbc-11e8-9c19-b6518ccbd620.png)

This is what it looks like in 2018.1.0f2
---
![unity_2018-05-04_16-56-45](https://user-images.githubusercontent.com/20914286/39657481-07236ccc-4fbd-11e8-9df6-1249e49c1a28.png)

**Comment by pharan** [comment]
Thanks for reporting. We'll check it out.

**Comment by pharan** [comment]
Seems a bit hairy to track down. No ETA for now.

**Comment by Rennan24** [comment]
Oh dang I see, well at least it gave me an excuse to upgrade in order to see if that would fix it lol. Glad to see some of the new features like the AnimationReferenceAsset and EventDataReferenceAsset, good work on those! 😄

**Comment by pharan** [comment]
It's behaving strangely. I'm beginning to wonder if it's a bug in Unity 2018.1, but I haven't seen other reports of it yet.

**Comment by wittydoma** [comment]
2017.4.2f2
Empty preview,too.

**Comment by pharan** [comment]
Thanks for reporting! That helps

**Comment by pharan** [comment]
If anyone has any idea what changed with preview tools in Unity 2017.4 and 2018.1, do let us know! This bug is kind of weird.

**Comment by GarlicDipping** [comment]
Hi, I've struggled with this problem in my own tool too, and found out that spine's SkeletonData Inspector has the same problem.

It seems like Unity changed `PreviewRenderUtility` class a bit, so you must call 

`previewRenderUtility.AddSingleGO(GameObject)`

for a gameobject to be previewed.

I've tested it out by adding

`previewRenderUtility.AddSingleGO(previewGameObject);`

in spine-unity's `SkeletonDataAssetInspector.cs`'s line 773(at `SkeletonInspectorPreview.Initialize()` function), and it seems like the preview renders well.

**Comment by pharan** [comment]
Thanks, @GarlicDipping !! That's a huge help. I'll try to apply this change this week.

I guess PreviewRenderUtility wasn't a well-documented class to begin with.

**Comment by Rennan24** [comment]
Nice catch @GarlicDipping, a lot of the Unity Editor GUI stuff tends to be pretty bad with documentation, hopefully their new UIElements will have better documentation though!

**Comment by GarlicDipping** [comment]
Glad it helped guys 😄 I really hope unity to give more attention to the Editor GUI stuffs, too...

**Comment by pharan** [comment]
@GarlicDipping Might be interesting.
We were handling the SkeletonAnimation component having to be manually updated by calling `Update` and `LateUpdate`.

But it seems like in 2017.4 and 2018.1, the MonoBehaviors added via `AddSingleGo` has its `Update` method being called by the editor, but not `LateUpdate`

So animations were playing weirdly fast, but just removing all manual calls made it so it wouldn't move.
