### ISSUE TITLE
[AnimationState] Complete event with a looping zero-duration animation. Doesn't fire.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#1112]
AnimationState fires the Complete event under the following conditions:
https://github.com/EsotericSoftware/spine-runtimes/blob/5919e0bea3db561e761a05ac6ca4a787d992be39/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/AnimationState.java#L389-L392

Here's a couple of weird things about it when the Animation duration is zero:
1. `entry.trackTime % duration` will become `entry.trackTime % 0` by default.
`(n % 0)` is `NaN` in .NET. Not sure what this does in other languages.
2. This means Complete never fires when the zero-duration animation is played in a loop.

I'm not sure what good behavior should be, or if this should be left alone.

On a related note, the current the current code also means that if an animation looped more than once in one frame, Complete is only fired once instead of the number of times it was looped within that frame.

I guess that's acceptable, until people have crazy-low framerates with crazy-short animations and hooked up important game logic that counts per animation loop. 

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

**Comment by badlogic** [comment]
What's the use case for animation duration being zero?

**Comment by pharan** [comment]
Julen said:
> For example:
> Our door has 5 animations, two of them are zero-duration (opened/closed) the others are opening, closing and beeing knocked.

Nate suggests the event should fire every frame.
Should the condition look like this?
```java
if (entry.loop ? (duration == 0) || (trackLastWrapped > entry.trackTime % duration)
 	: (animationTime >= animationEnd && entry.animationLast < animationEnd))
```

**Comment by NathanSweet** [comment]
Yeah, that looks OK. The ternary operator has gotten complex enough I think it's time to separate it out:
```
// Queue complete if completed a loop iteration or the animation.
boolean complete;
if (entry.loop)
	complete = duration == 0 || trackLastWrapped > entry.trackTime % duration;
else
	complete = animationTime >= animationEnd && entry.animationLast < animationEnd;
if (complete) queue.complete(entry);
```
This seems OK to do for all the runtimes.

**Comment by badlogic** [comment]
@pharan I'm implementing it in the reference implementation and modified this issue to reflect the status of the port for all runtimes. Please do it in 3.6, then we merge it into 3.7-beta.
