### ISSUE TITLE
Unable to build after adding Spine plugin for Unreal Engine

### ISSUE THREAD

**Issue by supersaiyansubtlety** [EsotericSoftware/spine-runtimes#1116]
Hello, 
I'm trying to get started making a 2D game using unreal engine 4 and spine. I've followed the instruction to the best of my abilities [here](http://esotericsoftware.com/spine-ue4#Using-the-SpineUE4-Runtime) and viewed the example [here](https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-ue4/Source/SpineUE4/SpineUE4.Build.cs#L9)
When I try to start the Unreal Project it says the build failed and I should try rebuilding in Visual Studio. When I try building in Visual Studio, I get multiple errors like 
```
'FLocalVertexFactory': no appropriate default constructor available
```
and 
```
'FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility': method with override specifier 'override' did not override and base class methods" and a couple like "'ObjectInitializer': undeclared identifier
```
My attempts to find the problem with google led me to search in this github project for "super(FObjectInitializer)" and found that some had a lowercase "o". I tried changing this but still received errors. I've tried with both visual studio 2017 and 2015 (I made a separate project to test in 2015 because it didn't have the new build tools). 
The relevant changes I made to my project's folder structure based on the UE4 docs are: 
MyProject/Plugins/SpinePlugin 
and 
MyProject/Plugins/RuntimeMeshComponentPlugin
and 
MyProject/Plugins/SpinePlugin/Source/SpinePlugin/Public/spine-c
I also made the changes outlined [here](https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-ue4/Source/SpineUE4/SpineUE4.Build.cs#L9) in my MyProject.Build.cs

Any help would be greatly appreciated.

**Comment by badlogic** [comment]
Sorry for the troubles. This is an issue with our `RuntimeMeshComponent` dependency, see https://github.com/EsotericSoftware/spine-runtimes/issues/1091. We are waiting on a fix from the maintainer. Please follow issue #1091.
