### ISSUE TITLE
[c] spAnimationState_apply optimization

### ISSUE THREAD

**Issue by ievgenmukhin** [EsotericSoftware/spine-runtimes#1117]
https://github.com/EsotericSoftware/spine-runtimes/blob/d11ebfededd3ae285227f6cd1f93d3370dc80ff7/spine-c/spine-c/src/spine/Skin.c#L74

spAttachment* spSkin_getAttachment (const spSkin* self, int slotIndex, const char* name) which is called for each timeline in spAnimationState_apply consumes most of CPU time during animation state applying, especially for spine files with large amount of images. We have spine file with ~1000 images for pre-rendered animations, some of them used in more than one bone, resulting in ~8K entries in _spSkin. With such file we have very low framerate on older hardware.

Adding hashtable to _spSkin for fast Entry lookup gives us ~40x performance gain on such large spine animations.

**Comment by badlogic** [comment]
Ay, `spSkin_getAttachment` performs a linear search through the slot/name entries. Replacing that with a map definitely gives a good speed up. If you have made this change already, we are happy to merge a pull request. Otherwise I'll look into fixing it up asap.

**Comment by ievgenmukhin** [comment]
Hi, I have implemented this as temporary fix using 3rd party code from public domain for string hashing (murmur hash), so I'm not sure if it can be merged to your code base. I can update my fix with string hashing which is good for you, and create pull request if you want.

**Comment by badlogic** [comment]
Murmur should be fine license wise. Happy to merge your PR!

**Comment by ievgenmukhin** [comment]
Did you have a chance to check my PR? https://github.com/EsotericSoftware/spine-runtimes/pull/1118

**Comment by badlogic** [comment]
I've commented on your PR! Sorry for the delay. Let's continue tracking this in the PR, closing this out.
