### ISSUE TITLE
[ts] Events keep firing during mix-out

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1119]
See http://esotericsoftware.com/forum/TS-Multiple-events-fired-10395

**Comment by NathanSweet** [comment]
Fix ready for porting: 2a7fd54224e53d73ae303bed480bdac10bacd838

**Comment by badlogic** [comment]
Ported to all runtimes.

**Comment by smaren** [comment]
@badlogic I see you have closed this issue, it has however not been fixed for the 3.6 branch (at least for the TS version)

**Comment by badlogic** [comment]
I backported the changes to all 3.6 runtimes.
