### ISSUE TITLE
[libgdx]TwoColorPolygonBatch vertex format differs from other Batches

### ISSUE THREAD

**Issue by piotr-j** [EsotericSoftware/spine-runtimes#1121]
Looks like i didnt quite get it right in #1057, missed one corner case. Drawing text. BitmapFontCache uses `TwoColorPolygonBatch#draw (Texture texture, float[] vertices, int offset, int count)` and if theres more then 1 character it breaks the batch. Current solution cant be easily extended. Perhaps a flag for automatic conversion enabled by default?

Something like this might do the trick https://gist.github.com/piotr-j/669d77fc9b385d12a9a40c7258bc8b58

**Comment by badlogic** [comment]
I'm a little slow today, could you tell me how this is breaking the batch with BitmapFontCache?

**Comment by piotr-j** [comment]
BitmapFontCache passes in vertices for a bunch of glyphs at once, but it doesnt know about additional float thats required for dark color. That makes it fail to render properly and all further draw calls until batch ends.

**Comment by NathanSweet** [comment]
Does it make sense to render text using a TwoColorPolygonBatch? It's not just BitmapFontCache, it's any code that assumes the vertex data is the same as SpriteBatch.

**Comment by piotr-j** [comment]
While its clearly not needed, it makes it easier when you have one batch for everything. And the two color part is useful for gui, tho its somewhat out of scope for spine.

**Comment by NathanSweet** [comment]
I guess if we decide to do it, the most reasonable way is to have `draw (Texture texture, float[] vertices, int offset, int count)` accept the standard SpriteBatch format and do a copy, then we'd have a separate TwoColorPolygonBatch-specific method for the two color format.
