### ISSUE TITLE
memory not freed on ios

### ISSUE THREAD

**Issue by ShuraLiu** [EsotericSoftware/spine-runtimes#1131]
i use spine 3.51 with cocos2d-x on iOS. I tested the spine API, but found the memory does not freed correctly. the code i used as below:

spAtlas* atlas = spAtlas_createFromFile(atlasFile.c_str(), 0);
spAttachmentLoader* attachmentLoader = SUPER(Cocos2dAttachmentLoader_create(atlas));
spSkeletonBinary* binary = spSkeletonBinary_createWithLoader(attachmentLoader);
spSkeletonData* skeletonData = spSkeletonBinary_readSkeletonDataFile(binary, binaryFile.c_str());
spSkeletonBinary_dispose(binary);
spSkeletonData_dispose(skeletonData);
spAtlas_dispose(atlas);
spAttachmentLoader_dispose(attachmentLoader);

the memory after called spSkeletonData_dispose is larger than code before spSkeletonBinary_readSkeletonDataFile, i checked the memory leak with Xcode, with nothing founded.

i did the test with different files, but the same result. i'm so confused with it.

update:
this is one of my tests, the spine file is large, this character has many animations.
code like this:
![wx20180702-125931](https://user-images.githubusercontent.com/5306624/42146148-8373f77e-7df8-11e8-8cde-861e12625538.png)
before all:
![wx20180702-130059](https://user-images.githubusercontent.com/5306624/42146156-94942952-7df8-11e8-9c50-15a0027f93b4.png)
before spSkeletonBinary_readSkeletonDataFile:
![wx20180702-130656](https://user-images.githubusercontent.com/5306624/42146184-d46e562e-7df8-11e8-827f-5be062b3c30f.png)
before spSkeletonData_dispose:
![wx20180702-130228](https://user-images.githubusercontent.com/5306624/42146194-e7782e8e-7df8-11e8-8265-915de32d9683.png)
after spSkeletonData_dispose:
![wx20180702-130245](https://user-images.githubusercontent.com/5306624/42146200-f39fab6a-7df8-11e8-9282-caac1af4be68.png)
after all:
![wx20180702-130308](https://user-images.githubusercontent.com/5306624/42146206-fda3dcda-7df8-11e8-8bc3-94cbc017db3e.png)

i'm not sure if there is sth wrong with my usage or it is a real bug, please help me.

**Comment by badlogic** [comment]
spine-cococs2dx has a two singleton instances, [`SkeletonTwoColorBatch`](https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-cocos2dx/src/spine/SkeletonTwoColorBatch.h#L102) and [`Skeleton`](https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-cocos2dx/src/spine/SkeletonBatch.h#L42) that are alive during your entire application's life-time. These use some memory which amounts roughly to what you see. You can explicitely destroy them via the `destroyInstance` methods, but it's unlikely you need to. As I said, they are live for the whole of the program and will be re-used.

**Comment by ShuraLiu** [comment]
get it, thanks!
