### ISSUE TITLE
[UE4] Compile error on Beta-Cpp 3.7 branch (UE4.20)

### ISSUE THREAD

**Issue by GloryOfNight** [EsotericSoftware/spine-runtimes#1134]
fbe0692c4c9db27facf981221582dc485e6dbb6e - commit where I getting error
Project & Engine ver. 4.20 Preview 5 
Commit line in
Plugins\SpinePlugin\Source\SpinePlugin\SpinePlugin.Build.cs
has been changed to:
`//Definitions.Add("SPINE_UE4");
// In Unreal 4.20+, comment the above line, uncomment the below line
PublicDefinitions.Add("SPINE_UE4");`

Also used latest RuntimeMeshComponent from [Koderz rep](https://github.com/Koderz/RuntimeMeshComponent)

All build log from UE builder
[BombaNino.log](https://github.com/EsotericSoftware/spine-runtimes/files/2162602/BombaNino.log)

Do you have any compiling commit of SpineRuntime for UE 4.20 project?
Thanks.

**Comment by badlogic** [comment]
Did you change the `SpinePlugin.Build.cs` file as it says in the comment? The spine-ue4 runtime based on spine-cpp does not use the `RuntimeMeshComponent` anymore, please remove it as a dependency from all your build scripts. Please also remove the `spine-c` folder, and replace it with the `spine-cpp` folder from `spine-cpp/spine-cpp`.

**Comment by GloryOfNight** [comment]
Hi! Thanks for answer, I did as you say and all work fine, editor compiled plugin. 
But I has the second error, when starting build on Android, there a error that broke UBT:
`UATHelper: Packaging (Android (ETC1)):     D:/GitHub/BombaNino/Plugins/SpinePlugin/Source/SpinePlugin/Public/SpineSkeletonDataAsset.h(34,10):  fatal error: 'spine/spine.h' file not found` 
Log file, errors & warnings from 205 to 326 line
Fatal error: 323 line
[UBT-BombaNino-Android-Shipping_3.txt](https://github.com/EsotericSoftware/spine-runtimes/files/2163376/UBT-BombaNino-Android-Shipping_3.txt)
