### ISSUE TITLE
Spine 3.6.39 cocos2dx runtime can not play  low version animation(3.5.35)

### ISSUE THREAD

**Issue by liuyi** [EsotericSoftware/spine-runtimes#1136]
Is this a bug? or just don't support this version?
I just want upgrade spine runtime to 3.6.39 ( from 3.5.35 ）。
But when I done, got error when play spine animation(These animations can play very well on cocos2dx3.15.1 with spine 3.5.35).
see my screenshot at below:
![image](https://user-images.githubusercontent.com/848803/42321430-808c8144-808b-11e8-9182-d015a3f08680.png)
![image](https://user-images.githubusercontent.com/848803/42321435-830145d6-808b-11e8-8649-7fad2a5c169e.png)
![image](https://user-images.githubusercontent.com/848803/42321440-84da7936-808b-11e8-9da8-81ae0f24435d.png)

**Comment by badlogic** [comment]
Yes, the binary format is only stable within major versions, e.g. you can't load a binary skeleton exported from the Spine Editor version 3.5 with the Spine Runtimes version 3.6.

Please export from the version of the editor that matches the runtime. You can read more information about versioning here http://esotericsoftware.com/forum/Spine-editor-and-runtime-version-management-6534
