### ISSUE TITLE
[JS] Skin change bug.

### ISSUE THREAD

**Issue by yuriilychak** [EsotericSoftware/spine-runtimes#1139]
Hello. I use cocos2d-js and have problem with skin change. The problem is when you have empty skin placeholder in one skin, and this placeholder not empty in other skin, after skin change placeholder dont clear and attachment from old skin don't remove.
I fix it by rewriting the method setSkin to:
```
Skeleton.prototype.setSkin = function (newSkin) {
	if (newSkin != null) {
                var slots = this.slots;
                var slotCount = slots.length;
                var i, slot, name, attachment;

		for (i = 0; i < slotCount; ++i) {
			slot = slots[i];
			name = slot.data.attachmentName;

			if (name != null) {
                        	if (this.skin != null) {
                            		attachment = this.skin.getAttachment(i, name);
                                  	if (attachment) {
                                        	slot.attachment = null;
                                  	}
                        	}
				attachment = newSkin.getAttachment(i, name);
				if (attachment) {
					slot.setAttachment(attachment);
				}
			}
		}
	}
	this.skin = newSkin;
};
```
But I don't know is I correctly clear slot by `slot.attachment = null;`, or I need to do something else?

**Comment by badlogic** [comment]
Do you know if cocos2d-js is using our Spine runtime (spine-ts)? If that's the case, please refer to this section in the runtime guide http://esotericsoftware.com/spine-runtime-skins#Skin-changes. If you do not want to retain the old attachments that are missing in the newly set skin, call `skeleton.setSlotsToSetupPose()`
