### ISSUE TITLE
[runtimes] Port latest reference implementation changes in 3.7 branch

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1142]
See these commits:

Skeleton flipX/Y becomes scale.
https://github.com/EsotericSoftware/spine-runtimes/commit/d9a6b9151bdce0654cb263accfb0366a0a91d08b

Stretchy IK
https://github.com/EsotericSoftware/spine-runtimes/commit/a62e4466dd5d26235bd71159108fa00be7526f30
https://github.com/EsotericSoftware/spine-runtimes/commit/ae2f77112024dea53f3e5c2d9f28afed5f0fc252

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

**Comment by pharan** [comment]
flipX/flipY
csharp: https://github.com/EsotericSoftware/spine-runtimes/commit/0f7c01c469c9b2f67c40ef843b90bb0559a312bb
unity: https://github.com/EsotericSoftware/spine-runtimes/commit/d336712ccc7e2b7bd52dc0aa763389577e11a1be

**Comment by pharan** [comment]
Unity stuff:
https://github.com/EsotericSoftware/spine-runtimes/commit/3d52f1a7e2e3a69ee01640972e27745d38b68b29

**Comment by vegard** [comment]
My apologies if this is not the right place, but commit 5aab588928f780ea1fc5c3ba8ccc02e0ed5c13c1 references this issue and it seems to mix up X and Y for me, i.e. when I do ->setScaleX(-1) then it flips vertically and with ->setScaleY(-1) it flips horizontally. Could be a problem on my end, though...

**Comment by badlogic** [comment]
@vegard What engine are you using? What runtime (spine-c or spine-cpp)? Are you using y-down or y-up? Do you habe a reproduction sample for me?

**Comment by vegard** [comment]
spine-cpp commit 8ab455fc (branch `3.7-beta-cpp`) with basically the `drawSkeleton()` implementation from http://esotericsoftware.com/spine-cpp#Implementing-Rendering. Everything looks fine except I unexpectedly have to use `->setScaleY(-1)` to flip horizontally. I don't call `setYDown()` anywhere in my code, so it should be using the default value of `false`.
