### ISSUE TITLE
[UE4] Texture Streaming delay(Ver 4.18)

### ISSUE THREAD

**Issue by Hiryua** [EsotericSoftware/spine-runtimes#1143]
hi. I using unreal with spine

but I have one error and will ask.

This happens in 2D spine  animation.

![1](https://user-images.githubusercontent.com/41192548/42692254-0c83c3c8-86e6-11e8-9463-cff587e1b747.png)
![2](https://user-images.githubusercontent.com/41192548/42692258-10237cb2-86e6-11e8-88ba-152a1e2501bd.png)

The streaming delays only appear in Blueprint with Spine

Increasing the Texture Streamming pool size  is useless

**Comment by badlogic** [comment]
This is nothing related to Spine, but simply how UE4 deals with textures by default. Please see this as a starting point https://answers.unrealengine.com/questions/395848/texture-streaming-1.html. Then please look into the documentation of texture streaming in UE4 https://answers.unrealengine.com/questions/395848/texture-streaming-1.html.
