### ISSUE TITLE
Please specify config.json or config.jsonContent     at SpineWidget.validateConfig

### ISSUE THREAD

**Issue by spreatics** [EsotericSoftware/spine-runtimes#1144]
I know this question may be so easy. but I can't find solution so far...(googled more than 1 hour)

when I try to test my first HTML5 spine widget with json, atlas I get error message form chrome browser as below.

Please specify config.json or config.jsonContent at SpineWidget.validateConfig

my code is as simple as below..please help......

 `<div class="spine-widget" data-jason="my url" data-atlas="my url" data-animation="test"></div>`

p.s : yes, of course I bought valid license and I made jqeury and spine-widget.js included in my source.

**Comment by badlogic** [comment]
It's `data-json`, we've also replied on the forum!

**Comment by spreatics** [comment]
yes....you are right hundred times....and I agree that I was a fool....thanks a lot....T.T
