### ISSUE TITLE
[Cocos2d-x] EXC_BAD_ACCESS Crash in event queue drain

### ISSUE THREAD

**Issue by ForestRingGames** [EsotericSoftware/spine-runtimes#1147]
When switching scenes we had a crash today in the even queue drain function. It seemed to be rather random, we couldn't reproduce it in a stable way. - though it happened two times on two different days.

See the attached screenshot for the stacktrace and line of crash.

How could this happen? Can this error be triggered by using completion listeners or track completion listeners in a wrong way?

<img width="2672" alt="bildschirmfoto 2018-07-18 um 08 18 37" src="https://user-images.githubusercontent.com/21338444/42865664-a2463800-8a6a-11e8-9dc0-f8642183a52b.png">

**Comment by badlogic** [comment]
I'm afraid that's impossible to tell from the screenshot. What part of that statement is giving you the error? The listener? How do you construct the listener? Does it close over a thing that could be dead at this point?

**Comment by ForestRingGames** [comment]
@badlogic I just found the issue, it turns out it was my fault. The stack trace here was not complete unfortunately, which lead to the conclusion that it crashes in spine. But it in face crashed in my own code. 
I removed a SkeletonRenderer from its parent as a result of a listener of that SkeletonRenderer. Apparently spine doesn't like that ;)

I found the issue with Address Sanitizer.

**Comment by badlogic** [comment]
Great you found the issue. If you smoke something a listener requires, then things explode.
