### ISSUE TITLE
spVertexAttachment_computeWorldVertices() with stride > 2

### ISSUE THREAD

**Issue by mysterycoconut** [EsotericSoftware/spine-runtimes#1148]
While implementing usage of the spine-c runtime with my own code I kept getting less vertices than expected when rendering meshes. Found out the issue was I was passing 4 as `stride` to spVertexAttachment_computeWorldVertices() (necessary for how my data is structured), and that was not handled well by the current implementation.

My fix was to add `count *= stride*0.5f;` after `count += offset;`.

**Comment by badlogic** [comment]
What's your vertex layout look like?

**Comment by mysterycoconut** [comment]
I just have position, uv, and color packed like this into an array:
```
struct shaderVertexInfo {
	float x;
	float y;
	unsigned short u;
	unsigned short v;
	uint32_t color;
};
```
So the stride between two elements of the array is not 2 32-bit floats, but 4.
