### ISSUE TITLE
Error with Unity 2018.2.1

### ISSUE THREAD

**Issue by mistergreen** [EsotericSoftware/spine-runtimes#1151]
FYI. These errors prevent Unity project from compiling

> Assets/spine-unity/Asset Types/Editor/SkeletonDataAssetInspector.cs(628,28): error CS1540: Cannot access protected member `UnityEngine.Texture.Texture()' via a qualifier of type `UnityEngine.Texture'. The qualifier must be of type `Spine.Unity.Editor.SkeletonInspectorPreview' or derived from it

> Assets/spine-unity/Asset Types/Editor/SkeletonDataAssetInspector.cs(628,28): error CS0122: `UnityEngine.Texture.Texture()' is inaccessible due to its protection level

**Comment by pharan** [comment]
Are you using the latest runtime?
People have reported this before while using an older version and we fixed it several months ago.

The current 3.6 and 3.7-beta have been checked against Unity 5.6 and up to 2018.2.

**Comment by mistergreen** [comment]
I was mistaken on the Unity version, it's Unity 2018.2.1, the latest stable build.

I haven't updated the runtime maybe in 8 months.
I checked on the runtime version

> This Spine-Unity runtime works with data exported from Spine Editor version: 3.6.xx

It's not crucial for me as there were other errors with the migration so I reverted back to Unity 2017.3.
