### ISSUE TITLE
Error building Spine-UE4 3.7-beta-cpp on Windows

### ISSUE THREAD

**Issue by RisingSunStudios** [EsotericSoftware/spine-runtimes#1153]
Hi all, trying to build this plugin for UE4.20 and not having any luck. Followed instructions in the readme but it is failing to build. Looks like the errors are from the RuntimeMesh library. Any help?

Here is the output:

`
1>------ Rebuild All started: Project: UE4, Configuration: BuiltWithUnrealBuildTool Win32 ------
2>------ Rebuild All started: Project: SpineTest2, Configuration: Development_Editor x64 ------
2>Cleaning SpineTest2Editor Binaries...
2>Creating makefile for SpineTest2Editor (no existing makefile)
2>Performing full C++ include scan (no include cache file)
2>Using Visual Studio 2017 14.14.26428 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428) and Windows 10.0.17134.0 SDK (C:\Program Files (x86)\Windows Kits\10).
2>Parsing headers for SpineTest2Editor
2>  Running UnrealHeaderTool "D:\Projects\Unreal\Projects\SpineTest2\SpineTest2.uproject" "D:\Projects\Unreal\Projects\SpineTest2\Intermediate\Build\Win64\SpineTest2Editor\Development\SpineTest2Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
2>Reflection code generated for SpineTest2Editor in 13.205659 seconds
2>Building 70 actions with 6 processes...
2>  PCLaunch.rc
2>  Attachment.c
2>  IkConstraintData.c
2>  Json.c
2>  IkConstraint.c
2>  EventData.c
2>  extension.c
2>  Event.c
2>  Color.c
2>  ClippingAttachment.c
2>  BoundingBoxAttachment.c
2>  BoneData.c
2>  Array.c
2>  MeshAttachment.c
2>  Bone.c
2>  Atlas.c
2>  PathAttachment.c
2>  AtlasAttachmentLoader.c
2>  AttachmentLoader.c
2>  RegionAttachment.c
2>  PathConstraintData.c
2>  VertexEffect.c
2>  VertexAttachment.c
2>  TransformConstraintData.c
2>  Triangulator.c
2>  TransformConstraint.c
2>  Slot.c
2>  SlotData.c
2>  PathConstraint.c
2>  SkeletonData.c
2>  Skin.c
2>  SkeletonClipping.c
2>  SkeletonBounds.c
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\INCLUDE\limits.h(80): error C4668: '__STDC_WANT_SECURE_LIB__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>  SkeletonBinary.c
2>  Skeleton.c
2>  AnimationStateData.c
2>  PointAttachment.c
2>  SkeletonJson.c
2>  PCLaunch.rc
2>  PCLaunch.rc
2>  PCLaunch.rc
2>  PCLaunch.rc
2>  Animation.c
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\INCLUDE\limits.h(80): error C4668: '__STDC_WANT_SECURE_LIB__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>  AnimationState.c
2>  SharedPCH.UnrealEd.cpp
2>  SharedPCH.Engine.NonOptimized.cpp
2>  SharedPCH.Engine.cpp
2>  Module.RuntimeMeshComponent.gen.cpp
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): error C3668: 'FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility': method with override specifier 'override' did not override any base class methods
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): warning C4263: 'uint64 FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *) const': member function does not override any base class virtual member function
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(187): warning C4264: 'uint64 FVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *,const void *) const': no override available for virtual member function from base 'FVertexFactory'; function is hidden
2>  D:\Projects\Unreal\UE_4.20\Engine\Source\Runtime\ShaderCore\Public\VertexFactory.h(427): note: see declaration of 'FVertexFactory::GetStaticBatchElementVisibility'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\SceneInterface.h(19): note: see declaration of 'FVertexFactory'
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(156): error C2512: 'FLocalVertexFactory': no appropriate default constructor available
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\LocalVertexFactory.h(30): note: see declaration of 'FLocalVertexFactory'
2>  SpineTest2Character.cpp
2>  SpineTest2.cpp
2>  SpineTest2.init.gen.cpp
2>  SpineTest2Character.gen.cpp
2>  SpineTest2GameMode.gen.cpp
2>  Module.SpinePlugin.gen.cpp
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): error C3668: 'FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility': method with override specifier 'override' did not override any base class methods
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): warning C4263: 'uint64 FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *) const': member function does not override any base class virtual member function
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(187): warning C4264: 'uint64 FVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *,const void *) const': no override available for virtual member function from base 'FVertexFactory'; function is hidden
2>  D:\Projects\Unreal\UE_4.20\Engine\Source\Runtime\ShaderCore\Public\VertexFactory.h(427): note: see declaration of 'FVertexFactory::GetStaticBatchElementVisibility'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\SceneInterface.h(19): note: see declaration of 'FVertexFactory'
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(156): error C2512: 'FLocalVertexFactory': no appropriate default constructor available
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\LocalVertexFactory.h(30): note: see declaration of 'FLocalVertexFactory'
2>  SpineTest2GameMode.cpp
2>  UE4Editor-SpineTest2.lib
2>     Creating library D:\Projects\Unreal\Projects\SpineTest2\Intermediate\Build\Win64\UE4Editor\Development\SpineTest2\UE4Editor-SpineTest2.lib and object D:\Projects\Unreal\Projects\SpineTest2\Intermediate\Build\Win64\UE4Editor\Development\SpineTest2\UE4Editor-SpineTest2.exp
2>  UE4Editor-SpineTest2.dll
2>     Creating library D:\Projects\Unreal\Projects\SpineTest2\Intermediate\Build\Win64\UE4Editor\Development\SpineTest2\UE4Editor-SpineTest2.suppressed.lib and object D:\Projects\Unreal\Projects\SpineTest2\Intermediate\Build\Win64\UE4Editor\Development\SpineTest2\UE4Editor-SpineTest2.suppressed.exp
2>  Module.SpinePlugin.cpp
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): error C3668: 'FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility': method with override specifier 'override' did not override any base class methods
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): warning C4263: 'uint64 FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *) const': member function does not override any base class virtual member function
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(187): warning C4264: 'uint64 FVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *,const void *) const': no override available for virtual member function from base 'FVertexFactory'; function is hidden
2>  D:\Projects\Unreal\UE_4.20\Engine\Source\Runtime\ShaderCore\Public\VertexFactory.h(427): note: see declaration of 'FVertexFactory::GetStaticBatchElementVisibility'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\SceneInterface.h(19): note: see declaration of 'FVertexFactory'
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(156): error C2512: 'FLocalVertexFactory': no appropriate default constructor available
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\LocalVertexFactory.h(30): note: see declaration of 'FLocalVertexFactory'
2>  Module.RuntimeMeshComponentEditor.cpp
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): error C3668: 'FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility': method with override specifier 'override' did not override any base class methods
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): warning C4263: 'uint64 FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *) const': member function does not override any base class virtual member function
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(187): warning C4264: 'uint64 FVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *,const void *) const': no override available for virtual member function from base 'FVertexFactory'; function is hidden
2>  D:\Projects\Unreal\UE_4.20\Engine\Source\Runtime\ShaderCore\Public\VertexFactory.h(427): note: see declaration of 'FVertexFactory::GetStaticBatchElementVisibility'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\SceneInterface.h(19): note: see declaration of 'FVertexFactory'
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(156): error C2512: 'FLocalVertexFactory': no appropriate default constructor available
2>  D:\Projects\Unreal\UE_4.20\Engine\Source\Runtime\Engine\Public\LocalVertexFactory.h(30): note: see declaration of 'FLocalVertexFactory'
2>  Module.SpineEditorPlugin.gen.cpp
2>  Module.SpineEditorPlugin.cpp
2>  UE4Editor-SpineEditorPlugin.lib
2>     Creating library D:\Projects\Unreal\Projects\SpineTest2\Plugins\SpinePlugin\Intermediate\Build\Win64\UE4Editor\Development\SpineEditorPlugin\UE4Editor-SpineEditorPlugin.lib and object D:\Projects\Unreal\Projects\SpineTest2\Plugins\SpinePlugin\Intermediate\Build\Win64\UE4Editor\Development\SpineEditorPlugin\UE4Editor-SpineEditorPlugin.exp
2>  Module.RuntimeMeshComponent.cpp
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): error C3668: 'FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility': method with override specifier 'override' did not override any base class methods
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(179): warning C4263: 'uint64 FRuntimeMeshVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *) const': member function does not override any base class virtual member function
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(187): warning C4264: 'uint64 FVertexFactory::GetStaticBatchElementVisibility(const FSceneView &,const FMeshBatch *,const void *) const': no override available for virtual member function from base 'FVertexFactory'; function is hidden
2>  D:\Projects\Unreal\UE_4.20\Engine\Source\Runtime\ShaderCore\Public\VertexFactory.h(427): note: see declaration of 'FVertexFactory::GetStaticBatchElementVisibility'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\SceneInterface.h(19): note: see declaration of 'FVertexFactory'
2>d:\projects\unreal\projects\spinetest2\plugins\runtimemeshcomponentplugin\source\runtimemeshcomponent\public\RuntimeMeshRendering.h(156): error C2512: 'FLocalVertexFactory': no appropriate default constructor available
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\LocalVertexFactory.h(30): note: see declaration of 'FLocalVertexFactory'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshComponent.cpp(1469): error C2259: 'FRuntimeMeshSceneProxy': cannot instantiate abstract class
2>  D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshComponent.cpp(1469): note: due to following members:
2>  D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshComponent.cpp(1469): note: 'SIZE_T FPrimitiveSceneProxy::GetTypeHash(void) const': is abstract
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\PrimitiveSceneProxy.h(132): note: see declaration of 'FPrimitiveSceneProxy::GetTypeHash'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshComponent.cpp(1781): error C4668: 'WITH_RUNTIME_PHYSICS_COOKING' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshComponent.cpp(1839): error C2039: 'ShouldAllowClientSideNavigation': is not a member of 'UNavigationSystemBase'
2>  D:\Projects\Unreal\UE_4.20\Engine\Source\Runtime\Engine\Classes\AI/NavigationSystemBase.h(197): note: see declaration of 'UNavigationSystemBase'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshComponent.cpp(1833): warning C4996: 'UNavigationSystem::ShouldUpdateNavOctreeOnComponentChange': ShouldUpdateNavOctreeOnComponentChange is deprecated. Use FNavigationSystem::WantsComponentChangeNotifies instead Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
2>  D:\Projects\Unreal\UE_4.20\Engine\Source\Runtime\Engine\Classes\AI/NavigationSystemBase.h(314): note: see declaration of 'UNavigationSystem::ShouldUpdateNavOctreeOnComponentChange'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(424): error C2039: 'PositionVertexBuffer': is not a member of 'FStaticMeshLODResources'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\ParticleHelper.h(170): note: see declaration of 'FStaticMeshLODResources'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(424): error C2039: 'VertexBuffer': is not a member of 'FStaticMeshLODResources'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\ParticleHelper.h(170): note: see declaration of 'FStaticMeshLODResources'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(424): error C2039: 'ColorVertexBuffer': is not a member of 'FStaticMeshLODResources'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\ParticleHelper.h(170): note: see declaration of 'FStaticMeshLODResources'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(424): error C2660: 'GetNewIndexForOldVertIndex': function does not take 3 arguments
2>  D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(353): note: see declaration of 'GetNewIndexForOldVertIndex'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(445): error C2039: 'PositionVertexBuffer': is not a member of 'FStaticMeshLODResources'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\ParticleHelper.h(170): note: see declaration of 'FStaticMeshLODResources'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(445): error C2039: 'VertexBuffer': is not a member of 'FStaticMeshLODResources'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\ParticleHelper.h(170): note: see declaration of 'FStaticMeshLODResources'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(445): error C2039: 'ColorVertexBuffer': is not a member of 'FStaticMeshLODResources'
2>  d:\projects\unreal\ue_4.20\engine\source\runtime\engine\public\ParticleHelper.h(170): note: see declaration of 'FStaticMeshLODResources'
2>D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(445): error C2660: 'GetNewIndexForOldVertIndex': function does not take 3 arguments
2>  D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Source\RuntimeMeshComponent\Private\RuntimeMeshLibrary.cpp(353): note: see declaration of 'GetNewIndexForOldVertIndex'
2>UnrealBuildTool : error : UBT ERROR: Failed to produce item: D:\Projects\Unreal\Projects\SpineTest2\Plugins\RuntimeMeshComponentPlugin\Intermediate\Build\Win64\UE4Editor\Development\RuntimeMeshComponent\UE4Editor-RuntimeMeshComponent.lib
2>                        (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)
2>Total build time: 118.23 seconds (Parallel executor: 0.00 seconds)
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: The command "D:\Projects\Unreal\UE_4.20\Engine\Build\BatchFiles\Rebuild.bat SpineTest2Editor Win64 Development "D:\Projects\Unreal\Projects\SpineTest2\SpineTest2.uproject" -WaitMutex -FromMsBuild" exited with code -1.
2>Done building project "SpineTest2.vcxproj" -- FAILED.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
`

**Comment by badlogic** [comment]
The 3.7-beta-cpp branch does not use the RuntimeMeshComponent anymore (same for 3.7-beta). We've switched to ProceduralMeshComponent (for various reasons).

Please remove the plugin from your project.

I also see various spine-c files referenced in your log. Please remove the `spine-c` directory from your local `SpinePlugin` and instead copy the `spine-cpp/` to the plugin directory where the `spine-c` folder was.
