### ISSUE TITLE
Spine 3.7 on custom 4.20 build

### ISSUE THREAD

**Issue by xenophont** [EsotericSoftware/spine-runtimes#1155]
Hello Badlogic,

I'm having some issues while building my project with 4.20 and 3.7 beta branch.

I modified the build.cs file
I added spine-cpp to the source folder
I eliminated all references to runtimemeshcomponent

And still I'm getting an issue, as  d:\epicgit\unrealengine_420\engine\plugins\spineplugin\source\spineplugin\public\SpineSkeletonDataAsset.h(34): fatal error C1083: Cannot open include file: 'spine/spine.h': 

I assure you the file is there. Any ideas why this is happening?

Cheers mate.

**Comment by badlogic** [comment]
Did you regenerate the Visual Studio solution? Do the files show up in the solution explorer in VS?

**Comment by xenophont** [comment]
Yes I did. The inclusive nativization option is also on. Maybe the problem comes from there?
Is the spine plugin nativizable?

Thanks for your quick response.

**Comment by xenophont** [comment]
Also, it seems as spine is looking for the files in the engine folders instead of the project source folders

**Comment by badlogic** [comment]
Hrm, I can't reproduce this locally. Any chance you could send me your project by email? Please remove the binary and intermediate folders. Email: contact@esotericsoftware.com.

**Comment by badlogic** [comment]
Oh, no, the Spine plugin can't be nativized. Please try turning that off and see if that works.

**Comment by badlogic** [comment]
Jupp, this looks pretty much the same as https://github.com/EsotericSoftware/spine-runtimes/issues/1138#issuecomment-404851282

Let me know if disabling nativization does not work for you and we can reopen this.

**Comment by xenophont** [comment]
Sadly, I cannot send a copy of the project, as it is in oficial production stage.

I made a build without nativizing, and had the same issue:
Visual studio is looking for the spine includes in the engine folder for some reason.
**I managed to fix this** by manually copying in the engine source folder (UnrealEngine_420\Engine\Source)
the following folders from Plugins\SpinePlugin\Source :
-SpineEditorPlugin
-SpinePlugin

Seems like for some reason, in UE 4.20, the includes send the compiler to look for these files in the engine source folder instead of the project plugins source folder. This never happened prior to the version change from UE 4.16.3

**With these changes, I managed to do a build without the nativizing option**.

I will try now a build with exclusive nativization.

**Comment by badlogic** [comment]
I do see warnings in UBT logs about trying to find include files in engine folders, but they never result in include files not being found (neither when building the editor, nor when packaging for a platform).

I'm not sure how your setup is different from say our spine-ue4 sample project. Without seeing your project structure and build config it is hard for me to say anything. Could you maybe modify our sample project until it results in the same behaviour you see?

**Comment by xenophont** [comment]
Sure, I will try. I will answer in this thread if I manage to reproduce it.
