### ISSUE TITLE
[UE4][4.20] BoneDriver/BoneFollower not working.

### ISSUE THREAD

**Issue by KyoKazehaya** [EsotericSoftware/spine-runtimes#1160]
Hello! 
I'm currently having a problem with the SpineBoneDriverComponent and the SpineBoneFollowerComponent in UE4 4.20.

Everytime I attempt to set an Actor as Target:

![image](https://user-images.githubusercontent.com/11358135/43952291-68b7e45a-9c8d-11e8-8150-647080fa2e9e.png)

It throws me the following Message:
![image](https://user-images.githubusercontent.com/11358135/43952324-836f0d82-9c8d-11e8-8c7a-6aba6aec4015.png)

I tried to look at the UE4 example you provided but everytime I look at the HoverController_Blueprint I can't find the bone driver anywhere.

I tried to compile the example with lower UE4 versions such as 4.19 and still that component doesn't appear anywhere.

Also, I can't find any documentation anywhere about these components and I searched everwhere.

Maybe I'm not using it properly?

**Comment by badlogic** [comment]
You can see the bone driver component in the `05-driving-bones` sample on the `HoverController_blueprint`

![https://libgdx.badlogicgames.com/uploads/20-uDR0.png](https://libgdx.badlogicgames.com/uploads/20-uDR0.png)

You can verify that the bone driver component is applied by setting a breakpoint in `SpineBoneDriverComponent`

![https://libgdx.badlogicgames.com/uploads/21-ZJLQ.png](https://libgdx.badlogicgames.com/uploads/21-ZJLQ.png)

The bone driver component in the `HoverController_blueprint` actor drives the `hoverboard`  bone of the skeleton in the `SpineboyHover` actor. This is done by taking the position of the `HoverController_blueprint` actor and applying it to the `hoverboard` bone in the `SpineboyHover` actor. The bone driver component does this in every frame.

The blueprint of the `HoverController_blueprint` actor itself doesn't modify the `SpineboyHover` actor. Instead, it modifies the `HoverController_blueprint` actor's position based on keyboard input. The bone driver component then gets called by the engine on every tick, reads the position of the `HoverController_blueprint` actor and applies it to the `hoverboard` bone.

As for the error message you are receiving, it's hard to tell what's going on. Please try to reproduce the issue withour sample project and send me the step-by-step instructions how to set up a level in the sample project that shows the problem.

**Comment by KyoKazehaya** [comment]
Hello,

Thank you for your detailed answer. Although it still doesn't work in 4.20.1. 

This are the repro steps:

1. Download beta 3.7 cpp repo.
2. Copy the spine-cpp folder  to Plugins/SpinePlugin/Sources/SpinePlugin/Public/ directory of the example project.
3. Modify SpinePlugin.Build.cs by commenting "Definitions.Add("SPINE_UE4") and uncommenting "PublicDefinitions.Add("SPINE_UE4").
4. Run .uproject and build the project.
5. Go to HoverController_Blueprint and you can see the bone driver isn't there:

![image](https://user-images.githubusercontent.com/11358135/44025779-ebee9352-9ee8-11e8-8284-162eed55e396.png)

Still the example works perfectly fine so I don't know what kind of black magic is there. Am I missing something? Maybe at the project setup step?

I uploaded the project to my GoogleDrive which you can find here (I left Binaries and Intermediate just in case): [spine-ue4.zip](https://drive.google.com/file/d/19dYZxBQv-kQfv0w7rNwq9zHAG3QW0uu6/view?usp=sharing)

Thank you lots for your time.

**Comment by badlogic** [comment]
As I said, the bone driver is a component in thr blueprint actor. Every
frame, it takes the actors position (default scene root), and applies it to
the bone of a skeleton on another actor.

The blueprint itself does not refer to the bone driver. It simpliy modifies
the blueprint actor's position based on keyboard input.

The bone driver then applies that position to the selected bone. This is
implemented in the C++ code of the bone driver.

So, what you generally do:

1) Create an actor with a skeleton
2) Create a second actor with a bone driver set to the first actor and a
bone name.
3) Modify the position of the second second actor via code or blueprint,
and the position will be applied to thr bone of the first actor.

That's it.

**Comment by KyoKazehaya** [comment]
Hello!

I deleted the previous reply because I found the problem I was having. You cannot set an actor in the blueprint itself. You can only assign it if the actor is already in the scene (by dragging and dropping the blueprint for example). If the actor isn't in the scene (for example, to be spawned later) you cannot change the Target property.

Any idea on how to change this? I think you can always create a C++ BoneDriverComponent and then on BeginPlay() find the desired object in the scene or create a bridge via another public exposed variable then bind both bone driver component target with this one.

Also, although is not a bug itself would be nice to have some documentation about the bone driver for UE4 runtime.

Thank you again.

**Comment by badlogic** [comment]
You can change the target property in your blueprint. I've modified the sample by removing the existing bone driver, adding the tag "Spineboy" to the Spineboy actor, then modifying the blueprint as follows:

![https://libgdx.badlogicgames.com/uploads/22-yun3.png](https://libgdx.badlogicgames.com/uploads/22-yun3.png)

On `BeginPlay` (any event will do), I add a bone driver component. I then fetch the currently active actors in the scene and filter them by the tag "Spineboy". I then plug that actor into the bone driver, and finally specify the bone that should be driven.

You can do the same in C++ if necessary.

**Comment by badlogic** [comment]
Oh, and about the docs: I'm in the process of updating them since we switched from spine-c to spine-cpp. I'll make sure to add proper docs for the bone drivers. The docs are quite minimal at the moment.

Thanks for all the feedback!

**Comment by KyoKazehaya** [comment]
Thank you for the snippet in blueprints! it does really help. I'll try first that approach then replicate it via C++.

Thank you for your help and your work, very appreciated. I'm sure whoever comes to this post will find it very useful as well.
