### ISSUE TITLE
[libgdx] GWT incompatible

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/spine-runtimes#1161]
VertexAttachment contains AtomicInteger. This do not supported in GWT.

**Comment by NathanSweet** [comment]
AtomicInteger is not used in the latest (`3.7-beta` branch):
https://github.com/EsotericSoftware/spine-runtimes/blob/3.7-beta/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/attachments/VertexAttachment.java#L42
