### ISSUE TITLE
Forum : Assets missing, and file unplayable in compiler continuation

### ISSUE THREAD

**Issue by oziphantom** [EsotericSoftware/spine-runtimes#1162]
So installed Cmake on my machine... 
Followed the instructions as best I could. 
The editor-support/spine doesn't exist as far as I can see in any of the groups on the libcocos2d-x
I had to fix the include paths a few times, for some reason the SDK include directory was in the Include and Exclude field
The SLN references SimpleCommand.h/cpp which doesn't seem to exist, so I delete the reference to it.
A few other tweaks here and there and now I have
4>   Creating library F:\spine-runtimes-3.6\spine-cocos2dx\example\proj.win32\Debug.win32\spine-cocos2d-x.lib and object F:\spine-runtimes-3.6\spine-cocos2dx\example\proj.win32\Debug.win32\spine-cocos2d-x.exp
4>AnimationState.obj : error LNK2019: unresolved external symbol _spIntArray_create referenced in function __spAnimationState_trackEntry
4>SkeletonJson.obj : error LNK2001: unresolved external symbol _spIntArray_create
4>AnimationState.obj : error LNK2019: unresolved external symbol _spIntArray_dispose referenced in function __spAnimationState_disposeTrackEntry
4>AnimationState.obj : error LNK2019: unresolved external symbol _spIntArray_setSize referenced in function __spTrackEntry_setTimelineData
4>AtlasAttachmentLoader.obj : error LNK2019: unresolved external symbol _spClippingAttachment_create referenced in function __spAtlasAttachmentLoader_createAttachment
4>SkeletonJson.obj : error LNK2019: unresolved external symbol _spFloatArray_create referenced in function __readVertices
4>SkeletonJson.obj : error LNK2019: unresolved external symbol _spFloatArray_add referenced in function __readVertices
4>SkeletonJson.obj : error LNK2019: unresolved external symbol _spIntArray_add referenced in function __readVertices
4>SkeletonBatch.obj : error LNK2019: unresolved external symbol _spUnsignedShortArray_create referenced in function "protected: __thiscall spine::SkeletonBatch::SkeletonBatch(void)" (??0SkeletonBatch@spine@@IAE@XZ)
4>SkeletonTwoColorBatch.obj : error LNK2001: unresolved external symbol _spUnsignedShortArray_create
4>SkeletonBatch.obj : error LNK2019: unresolved external symbol _spUnsignedShortArray_dispose referenced in function "protected: virtual __thiscall spine::SkeletonBatch::~SkeletonBatch(void)" (??1SkeletonBatch@spine@@MAE@XZ)
4>SkeletonTwoColorBatch.obj : error LNK2001: unresolved external symbol _spUnsignedShortArray_dispose
4>SkeletonBatch.obj : error LNK2019: unresolved external symbol _spUnsignedShortArray_ensureCapacity referenced in function "public: unsigned short * __thiscall spine::SkeletonBatch::allocateIndices(unsigned int)" (?allocateIndices@SkeletonBatch@spine@@QAEPAGI@Z)
4>SkeletonTwoColorBatch.obj : error LNK2001: unresolved external symbol _spUnsignedShortArray_ensureCapacity
4>SkeletonRenderer.obj : error LNK2019: unresolved external symbol _spSkeletonClipping_create referenced in function "public: virtual void __thiscall spine::SkeletonRenderer::initialize(void)" (?initialize@SkeletonRenderer@spine@@UAEXXZ)
4>SkeletonRenderer.obj : error LNK2019: unresolved external symbol _spSkeletonClipping_clipStart referenced in function "public: virtual void __thiscall spine::SkeletonRenderer::draw(class cocos2d::Renderer *,class cocos2d::Mat4 const &,unsigned int)" (?draw@SkeletonRenderer@spine@@UAEXPAVRenderer@cocos2d@@ABVMat4@4@I@Z)
4>SkeletonRenderer.obj : error LNK2019: unresolved external symbol _spSkeletonClipping_clipEnd referenced in function "public: virtual void __thiscall spine::SkeletonRenderer::draw(class cocos2d::Renderer *,class cocos2d::Mat4 const &,unsigned int)" (?draw@SkeletonRenderer@spine@@UAEXPAVRenderer@cocos2d@@ABVMat4@4@I@Z)
4>SkeletonRenderer.obj : error LNK2019: unresolved external symbol _spSkeletonClipping_clipEnd2 referenced in function "public: virtual void __thiscall spine::SkeletonRenderer::draw(class cocos2d::Renderer *,class cocos2d::Mat4 const &,unsigned int)" (?draw@SkeletonRenderer@spine@@UAEXPAVRenderer@cocos2d@@ABVMat4@4@I@Z)
4>SkeletonRenderer.obj : error LNK2019: unresolved external symbol _spSkeletonClipping_isClipping referenced in function "public: virtual void __thiscall spine::SkeletonRenderer::draw(class cocos2d::Renderer *,class cocos2d::Mat4 const &,unsigned int)" (?draw@SkeletonRenderer@spine@@UAEXPAVRenderer@cocos2d@@ABVMat4@4@I@Z)
4>SkeletonRenderer.obj : error LNK2019: unresolved external symbol _spSkeletonClipping_clipTriangles referenced in function "public: virtual void __thiscall spine::SkeletonRenderer::draw(class cocos2d::Renderer *,class cocos2d::Mat4 const &,unsigned int)" (?draw@SkeletonRenderer@spine@@UAEXPAVRenderer@cocos2d@@ABVMat4@4@I@Z)
4>SkeletonRenderer.obj : error LNK2019: unresolved external symbol _spSkeletonClipping_dispose referenced in function "public: virtual __thiscall spine::SkeletonRenderer::~SkeletonRenderer(void)" (??1SkeletonRenderer@spine@@UAE@XZ)
4>AppDelegate.obj : error LNK2019: unresolved external symbol "public: static class cocos2d::Scene * __cdecl SkeletonRendererSeparatorExample::scene(void)" (?scene@SkeletonRendererSeparatorExample@@SAPAVScene@cocos2d@@XZ) referenced in function "public: virtual bool __thiscall AppDelegate::applicationDidFinishLaunching(void)" (?applicationDidFinishLaunching@AppDelegate@@UAE_NXZ)
4>TankExample.obj : error LNK2019: unresolved external symbol "public: static class cocos2d::Scene * __cdecl CoinExample::scene(void)" (?scene@CoinExample@@SAPAVScene@cocos2d@@XZ) referenced in function "public: bool __thiscall <lambda_94ceb064e654067f38f42ee158e13021>::operator()(class cocos2d::Touch *,class cocos2d::Event *)const " (??R<lambda_94ceb064e654067f38f42ee158e13021>@@QBE_NPAVTouch@cocos2d@@PAVEvent@2@@Z)
4>F:\spine-runtimes-3.6\spine-cocos2dx\example\proj.win32\Debug.win32\spine-cocos2d-x.exe : fatal error LNK1120: 19 unresolved externals
4>Done building project "spine-cocos2d-x.vcxproj" -- FAILED.

I found they are defined in Array.h which from the C spine folder, I found and added it to the spine-cocos2d-x project, didn't fix it. Any Ideas? Does it need something in the Include search paths maybe?

**Comment by badlogic** [comment]
Did you have a CMake build/ folder before updating to the latest git commit and re-running CMake? If so, please remove that, then regenerate the VS solution via CMake GUI.

**Comment by oziphantom** [comment]
I've never installed CMake on this machine before, so latest and fresh CMake install, I've downloaded the latest version of the run-times and put them into a separate folder and HDD to the other project. This is a 100% clean build.

**Comment by badlogic** [comment]
OK, I'll try to reproduce your issue on my Windows machine. FWIW, the CMake build for cocos2dx we have only downloads cocos2dx. The Visual Studio project files are checked into git and will not be generated by CMake.

**Comment by badlogic** [comment]
Sorry, it seems there was indeed a problem in the VS2015 solution. I've fixed this in the latest commit in the 3.6 branch. I've also updated the instructions on how to compile the example project with VS2015 on Windows. Could you please give it another try?

**Comment by oziphantom** [comment]
Still waiting on full testing before I comment on my findings. They are slow.
