### ISSUE TITLE
[runtimes] Port IK & rotation changes

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1163]
See 

https://github.com/EsotericSoftware/spine-runtimes/commit/7996f2bae063c46c813192788769b0346ea98ad9
https://github.com/EsotericSoftware/spine-runtimes/commit/7df713b13f2096f1df5fe2644311402a067ffb80

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

**Comment by pharan** [comment]
Rotation fix: https://github.com/EsotericSoftware/spine-runtimes/commit/671c9210892291257be7572129a8bfb46b3353f1
csharp: https://github.com/EsotericSoftware/spine-runtimes/commit/cbd6b2617eb1161c602ce710539cf75cd06e5e83
unity: https://github.com/EsotericSoftware/spine-runtimes/commit/aef9261d401c367370bc654ee2738f5f50b91805
