### ISSUE TITLE
Doesn't work with the latest UE4.20.2

### ISSUE THREAD

**Issue by alex-kolb** [EsotericSoftware/spine-runtimes#1164]
The code doesn't compile with 4.20.2, RenderMeshComponent.cpp gives bunch of errors because of change UE4 source code (different interfaces, functons signatures etc.) Tried with 3.6 branch.

**Comment by badlogic** [comment]
Please use the 3.7-beta or 3.7-beta-cpp branch. The 3.6 branch uses RuntimeMeshComponent, which is not compatible with UE 4.20.
