### ISSUE TITLE
Spine-Unity 3.7 2018-09-06 build issues

### ISSUE THREAD

**Issue by 23doors** [EsotericSoftware/spine-runtimes#1172]
Using Unity 2018.2.6f1 latest 3.7 build causes unity to hang with 100% cpu usage when playing any example scene.

It plays for 2-3s then stops and stops responding completely. I no longer have 2018-08-25 build locally but, if I remember correctly, it worked just fine there. Tried empty project - same thing. Tried 3.6 with empty project - works normally.

**Comment by pharan** [comment]
Thanks for reporting, we're looking into the problem. There was an [AnimationState update](https://github.com/EsotericSoftware/spine-runtimes/issues/1169) and it's possibly affecting all updated runtimes, especially in cases where there's no mixing. Or possibly just spine-csharp.

**Comment by pharan** [comment]
This has been fixed and the latest unitypackage is now up, dated 2018-09-10.
Thanks again!

**Comment by 23doors** [comment]
Thanks! Everything works now!
