### ISSUE TITLE
Preview not working on Unity 2017.4.10f1

### ISSUE THREAD

**Issue by quanarmy** [EsotericSoftware/spine-runtimes#1173]
I cannot play animation preview on Unity 2017.4.10f1. I'm using spine-unity-3_6-2018-08-25 version.

**Comment by pharan** [comment]
I just tried previewing and playing animations in the skeleton preview in SkeletonDataAsset and AnimationReferenceAsset inspector previews in Unity 2017.4.10f1.

They seem to be working fine in the spine-unity 3.6 2018-08-25 release.

Is this happening for just some, or all skeleton data?

**Comment by quanarmy** [comment]
It's happening for all skeleton data.
I'm upgraded to the spine-unity 3.6 2018-08-25 from older version.

**Comment by pharan** [comment]
I can't seem to repro the problem. Is there any other details that might make your project special?

**Comment by quanarmy** [comment]
I found solution. Removing all spine from project then re-import with spine-unity 3.6 2018-08-25. It works for now!
Thanks for your support!
