### ISSUE TITLE
Unity Assembly Definition

### ISSUE THREAD

**Issue by HDANILO** [EsotericSoftware/spine-runtimes#1181]
New projects that are using Assembly Definition are having issues with Spine plugin, it has 10 editor folders that need Assembly Definitions, and it's making messy to have Spine integrated in such projects. Since spine is a plugin that is adopted early in the project, it is even more critical to have this feature on.

Here is the topic about Assembly Definitions: https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

Please adapt the current plugin to have their own Assembly Definition as an alternative to who wants to use it.

**Comment by pharan** [comment]
Hello HDANILO.
The 3.7-beta runtime already has the new folder structure and asmdef files. You can read more about it here: http://esotericsoftware.com/forum/Unity-2017-3-Assembly-Definition-Files-9270

![file](https://user-images.githubusercontent.com/1911082/46209815-78290b80-c361-11e8-9c63-b1b09435e209.png)

**Comment by HDANILO** [comment]
Thanks for the fast answer, it's a good idea to have this information easy to access, many others might come for this
