### ISSUE TITLE
[ue4] Linker error when invoking spine-cpp APIs

### ISSUE THREAD

**Issue by GryphonWorx** [EsotericSoftware/spine-runtimes#1182]
Hallo again. Thanks for all the help once more. Fabel from the forums too if that wasn't obvious :P.

Would you be up for making a quick wrapper for the spine::Animation class? From my digging it seems the only place where you store the actual animation string name and I can't for the life of me find anywhere that returns it in the Unreal classes. I'd like to be able to see the name of the animation presently playing so I can read that during runtime. I imagine the rest of the data points in the Animation class would be handy at some point as well. And of course have a UTrackInfo version of spine::trackinfo::getAnimation so we can retrieve that information.

Sorry to be asking so much, it would just be really handy to be able to use more of the nice library from UE4!

**Comment by badlogic** [comment]
I assume you want this for blueprints? The data can be easily accessed from C++.

**Comment by GryphonWorx** [comment]
In that case forgive me for now being able to find how to access it from C++. I felt I crawled through all the properties and objects you can get out of the Skeleton animator component?
My point being that the stuff you wrote to me in the forum doesn't work because trying to access anything in the AnimationState throws a linker error on compile, and the UTrackEntry has no property to access the animation, and anything involving the spine::TrackEntry also throws linker errors.

**Comment by badlogic** [comment]
OK, the linker errors are the problem we need to solve then. Could you tell me what your exact setup is (UE version, VS version, compilation target, etc.). Can you reproduce the linker errors in our example project as well? Here's a related thread, and I simply can not reproduce the issue locally with our example project, even with a completely clean setup. http://esotericsoftware.com/forum/UE4-3-7-cpp-beta-LNK2019-error-on-windows-10741

**Comment by GryphonWorx** [comment]
It's the same issue. Right now I'm not by a computer but I had the same issue yesterday in the example project. Using vs2017 and ue4.20.3. I think it's because ue4 doesn't link things that are not in the api scope, I. E. Outside the SPINEPLUGIN_API classes.

**Comment by GryphonWorx** [comment]
Also the plugin only lives in the Plugins dir of the project. No files copied into the engine source locations under program files and all compiles OK as long as I don't use anything outside the SPINEPLUGIN_API scope.

**Comment by badlogic** [comment]
Thanks, I was able to reproduce the issue. E.g. in `SpineboyCppPawn.cpp`

```
void ASpineboyCppPawn::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	USpineSkeletonAnimationComponent* animation = FindComponentByClass<USpineSkeletonAnimationComponent>();
	spine::AnimationState *state = animation->GetAnimationState();
	spine::TrackEntry *entry = state->getCurrent(0);
	if (entry) {
		GEngine->AddOnScreenDebugMessage(-1, 0.5f, FColor::Yellow, FString(entry->getAnimation()->getName().buffer()));
	}
}
```

Results in

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: class spine::String const & __cdecl spine::Animation::getName(void)" (?getName@Animation@spine@@QEAAAEBVString@2@XZ) referenced in function "public: virtual void __cdecl ASpineboyCppPawn::Tick(float)" (?Tick@ASpineboyCppPawn@@UEAAXM@Z)	SpineUE4	D:\workspaces\esotericsoftware\spine-runtimes\spine-ue4\Intermediate\ProjectFiles\SpineboyCppPawn.cpp.obj	1	
Error	LNK2019	unresolved external symbol "public: class spine::Animation * __cdecl spine::TrackEntry::getAnimation(void)" (?getAnimation@TrackEntry@spine@@QEAAPEAVAnimation@2@XZ) referenced in function "public: virtual void __cdecl ASpineboyCppPawn::Tick(float)" (?Tick@ASpineboyCppPawn@@UEAAXM@Z)	SpineUE4	D:\workspaces\esotericsoftware\spine-runtimes\spine-ue4\Intermediate\ProjectFiles\SpineboyCppPawn.cpp.obj	1	
Error	LNK2019	unresolved external symbol "public: class spine::TrackEntry * __cdecl spine::AnimationState::getCurrent(unsigned __int64)" (?getCurrent@AnimationState@spine@@QEAAPEAVTrackEntry@2@_K@Z) referenced in function "public: virtual void __cdecl ASpineboyCppPawn::Tick(float)" (?Tick@ASpineboyCppPawn@@UEAAXM@Z)	SpineUE4	D:\workspaces\esotericsoftware\spine-runtimes\spine-ue4\Intermediate\ProjectFiles\SpineboyCppPawn.cpp.obj	1	
```

I'm trying to resolve this without polluting all of spine-cpp with UE4 macros.

I've changed the issue title accordingly.

**Comment by badlogic** [comment]
I was finally able to track down all the issues involved in this. The latest commits to the 3.7-beta-cpp branch contain the fixes. You can now access all spine-cpp APIs from anywhere without linker issues. The `SpineboyCppPawn` code from above works as intended now as well.

Thanks for reporting and helping me nail this one!
