### ISSUE TITLE
spine-Unity SkeletonGraphic.Update Run time too long

### ISSUE THREAD

**Issue by fjqingyou** [EsotericSoftware/spine-runtimes#1184]
I'm Sorry!  My English very bad! so, this content body from google translate!

I using spine-Unity , but project run on ipad device, unity profiler view geting info  SkeletonGraphic.Update Run time too long.

so, In order to locate the problem, i add temp test c# code in cs file! 

//SkeletonGraphic.cs
public void UpdateMesh () {
...
if (currentInstructions.hasActiveClipping) {
    Profiler.BeginSample("meshGenerator.AddSubmesh");//Add temp test code
    meshGenerator.AddSubmesh(currentInstructions.submeshInstructions.Items[0], updateTriangles);
   Profiler.EndSample();//Add temp test code
}
....
}

//SkeletonClipping.cs
internal bool Clip (float x1, float y1, float x2, float y2, float x3, float y3, ExposedList<float> clippingArea, ExposedList<float> output) {
Profiler.BeginSample("SkeletonClipping.Clip");//Add temp test code
......
Profiler.EndSample();//Add temp test code
return clipped;
}

//rebuild and run this project
//I geting this profiler info
![qq20180929-105858](https://user-images.githubusercontent.com/31087168/46240470-85361100-c3da-11e8-8536-87e4e2c04536.png)

How should I deal with this problem?

**Comment by fjqingyou** [comment]
I read the SDK code and use it in my own cs script.

MeshGenerator meshGenerator = skeletonGraphic.MeshGenerator;
MeshGenerator.Settings settings = meshGenerator.settings;
settings.useClipping = false;//Do not use this feature
meshGenerator.settings = settings;//value type need resetting it

Although the implementation reduces the execution time of the program. Because I am not an art worker. I don’t notice any damage in animation effects.

**Comment by fjqingyou** [comment]
I haven't read all the SDK code yet, but I have a rough look at the 6-level for loop. The loop structure seems to be a bit deep. I wonder if you have any plans to optimize the algorithm? After all, the burden of such a multi-layer loop on the CPU seems to be no small.

**Comment by pharan** [comment]
Using the Clipping feature will always be expensive as you increase the number of attachments and triangles to clip. Always disable clipping when not in use, and minimize the number of attachments and triangles when in use.

If you can achieve the effect you need using Unity's shader stencils or UI masks, it will be much more performant.

**Comment by fjqingyou** [comment]
Thanks!
I need closed this issues now?

**Comment by pharan** [comment]
Thanks for letting us know.
Let us know if you have problems with the runtime!
