### ISSUE TITLE
[cpp] - Read Access Violation in AnimationState::animationsChanged()

### ISSUE THREAD

**Issue by GryphonWorx** [EsotericSoftware/spine-runtimes#1186]
Randomly when this function gets called, entry is already NULL leading to a Read Access Violation. This happens in the Spine example project if you load the 04 - Basic Controls map, hit Play and then just press Space a couple of times, then wait and the project will crash a second or two later.

Changing the current fuction:
`
void AnimationState::animationsChanged() {
	_animationsChanged = false;

	_propertyIDs.clear();

	for (size_t i = 0, n = _tracks.size(); i < n; ++i) {
		TrackEntry *entry = _tracks[i];

		while (entry->_mixingFrom != NULL)
			entry = entry->_mixingFrom;

		do {
			if (entry->_mixingTo == NULL || entry->_mixBlend != MixBlend_Add) setTimelineModes(entry);
			entry = entry->_mixingTo;
		} while (entry != NULL);
	}
}
`

To add two NULL checks here:
`
void AnimationState::animationsChanged() {
	_animationsChanged = false;

	_propertyIDs.clear();

	for (size_t i = 0, n = _tracks.size(); i < n; ++i) {
		TrackEntry *entry = _tracks[i];

		while (entry != nullptr && entry->_mixingFrom != NULL)
			entry = entry->_mixingFrom;

		while(entry != NULL)
		{
			if (entry->_mixingTo == NULL || entry->_mixBlend != MixBlend_Add) setTimelineModes(entry);
				entry = entry->_mixingTo;
		};
	}
}
`

Resolves the problem.

**Comment by badlogic** [comment]
Thanks for reporting, fixed! I went through the rest of `AnimationState` (any code touching `tracks` really) to ensure we check null entries.
