### ISSUE TITLE
[monogame]SkeletonBounds Sample not work

### ISSUE THREAD

**Issue by PommesDog** [EsotericSoftware/spine-runtimes#1191]
I used Spineboy sample Data and Monogame Sample Code
```
spineboy-ess.json
spineboy.png
spineboy.atlas
```
```
SkeletonBounds bounds = new SkeletonBounds();
protected override void Draw(GameTime gameTime) {
   .....
    bounds.Update(skeleton, true);
    MouseState mouse = Mouse.GetState();
    if (headSlot != null) {
        headSlot.G = 1;
        headSlot.B = 1;
        if (bounds.AabbContainsPoint(mouse.X, mouse.Y)) {
            BoundingBoxAttachment hit = bounds.ContainsPoint(mouse.X, mouse.Y);
            if (hit != null) {
                headSlot.G = 0;
                headSlot.B = 0;
            }
        }
    }
}
```

```
public class SkeletonBounds {
...
	public void Update (Skeleton skeleton, bool updateAabb) {
	...
		ExposedList<Slot> slots = skeleton.slots;
		int slotCount = slots.Count;
	...
		for (int i = 0; i < slotCount; i++) {
			Slot slot = slots.Items[i];
			BoundingBoxAttachment boundingBox = slot.attachment as BoundingBoxAttachment;
			if (boundingBox == null) continue;
			boundingBoxes.Add(boundingBox);
```
When I run in debug mode I noticed slot.attachment is null

I edited json and it worked

 spine-runtimes/examples/spineboy/export/spineboy-ess.json
Before
`{ "name": "head-bb", "bone": "head" },`
After
`{ "name": "head-bb", "bone": "head", "attachment": "head" },`

**Comment by pharan** [comment]
Thanks for letting us know!
Seems like the problem was just that our sample project setup pose has changed since the example code was written.

**Comment by PommesDog** [comment]
thank you pharan and badlogic
yes i think so too
need fix "head-bb" atachment setting in the "spineboy-ess.spine" and "spineboy-pro.spine"

**Comment by pharan** [comment]
That should do it:
https://github.com/EsotericSoftware/spine-runtimes/commit/61b8fcc696c689dcf952f6130f705cd04f6b7c28

**Comment by PommesDog** [comment]
I See
Thank you pharan
