### ISSUE TITLE
[cpp] assert() macro surrounding code, causes crash in release builds.

### ISSUE THREAD

**Issue by DanDanger** [EsotericSoftware/spine-runtimes#1192]
in Atlas.cpp there are many lines where assert() wraps code that needs to be executed in release builds.

eg.

line 139: assert(readTuple(&begin, end, tuple));

This causes release builds to crash.
Compiling on visual studio community edition.

**Comment by badlogic** [comment]
Thanks for reporting, fix incoming.

**Comment by badlogic** [comment]
@DanDanger I went through the entire C++ code base on a hunt for asserts in the 3.7-beta-cpp branch. None of the asserts execute code that non-asserted code paths depend on.

I've backporting the 3.7-beta-cpp changes to the 3.7-beta branch. Going forward, I would suggest you base your work off of the 3.7-beta-cpp branch, until 3.7 is released.

Thanks for reporting!
