### ISSUE TITLE
[corona] Events not firing

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1195]
http://esotericsoftware.com/forum/onEvent-not-working-properly-for-me-10864 and email

**Comment by timwickey** [comment]
This fix made some events fire - but not all. I have 4 events and only two of them trigger. 
I have confirmed this with the events in the Gunman asset pack - they do not work.
https://esotericsoftware.com/spine-asset-packs

For instance Fire_Shotgun has 4 events. Eject Casing, Fire, and two sound events. Only Eject Casing and the latter sound event trigger. ( If I move all events to at min 10 ticks away from the start then they all trigger.)

**Comment by timwickey** [comment]
This works. (all 4 trigger)
![image](https://user-images.githubusercontent.com/1440919/46966141-ddc40a00-d07a-11e8-832c-538415962efb.png)
This does not. (only last 2 trigger)
![image](https://user-images.githubusercontent.com/1440919/46966177-f6ccbb00-d07a-11e8-8a77-2f5b263880ec.png)

**Comment by badlogic** [comment]
Thanks for reporting! I'll dig into it.

**Comment by timwickey** [comment]
I appreciate it!

**Comment by timwickey** [comment]
Any luck?

**Comment by badlogic** [comment]
Sorry for the huge delay. I finally found time to work on this. I got the Gunman asset pack, exported it with default settings to .json, put the Gunman.* exported files into `spine-corona/data`, added this line to `main.lua` before line 85

```
table.insert(skeletons, loadSkeleton("Gunman.atlas", "Gunman.json", 240, 300, 0.4, "Fire_Shotgun"))
```

And it works as intended. I get all 4 events:

![https://libgdx.badlogicgames.com/uploads/qbo4KiKrVY.png](https://libgdx.badlogicgames.com/uploads/qbo4KiKrVY.png).

This is using the latest spine-lua and spine-corona runtimes from the 3.7-beta branch.

Let me know if that doesn't work for you and I'll re-open. Otherwise I suggest you switch to the 3.7-beta branch, which is compatible with exports from both 3.6 and 3.7-beta Spine.

**Comment by timwickey** [comment]
I debated opening a new issue but I thought the context was already here.

This is an issue in 3.7 but it requires setting up the weapon. I am doing the configuration in the same way as the Gunman project does for unity so I don't think it's a configuration issue. 


Using the Default Gunman assets, and the spine example main.lua

Line 84 just like you did except init with Idle
`table.insert(skeletons, loadSkeleton("Gunman.atlas", "Gunman.json", 240, 300, 0.4, "Idle"))`

Then down at the key event listener line 138 or so.
`Runtime:addEventListener("key", function(event)
    if activeSkeleton == 1 and event.phase == "down" then
        state = skeletons[activeSkeleton].state
        state:setAnimationByName(1, "Aim_Shotgun", false)  
        timer.performWithDelay( 500, function() state:setAnimationByName(1, "Fire_Shotgun", false) end )
    end
    return false
end) `

When you trigger this you will see only two events
May 22 03:18:45.764 1 event: Fire_Shotgun, Sound, 0, 0, 'Pump/Random'
May 22 03:18:45.881 1 event: Fire_Shotgun, EjectCasing, 0, 0, ''


In experimenting I put the the Fire_Shotgun on a different track than Aim and I get all 4 events.
BUT, trigger it again, and only get 2.
