### ISSUE TITLE
Bug in 3.7-beta / Animation.c / spIkConstraintTimeline_setFrame

### ISSUE THREAD

**Issue by sp-stefano-lanza** [EsotericSoftware/spine-runtimes#1197]
```spIkConstraintTimeline_setFrame``` in Animation.c has a bug. ```spIkConstraintTimeline_create``` allocates a timeline with a number of entries per frames equal to IKCONSTRAINT_ENTRIES (== 4). ```spIkConstraintTimeline_setFrame``` writes the "stretch" value to the IKCONSTRAINT_STRETCH element (== 4), thus causing an out-of-bound memory write. I believe IKCONSTRAINT_ENTRIES should be equal to 5.

**Comment by badlogic** [comment]
Thanks for reporting, this is fixed in the 3.7-beta and 3.7-beta-cpp branches.
