### ISSUE TITLE
[c] Bug with type overflow in spColor_setFromFloats

### ISSUE THREAD

**Issue by sbrednikhin** [EsotericSoftware/spine-runtimes#1200]
`spColor_setFromFloats` doesnt contain `spColor_clamp`. 
As the result using curves in editor can cause type overflow with short blinking during animating alpha to zero.
For example when using animation curve with little overflow (going higher than 100%) in animation where alpha goes from 255 to 0 in `_spColorTimeline_apply` `percent` and `a` variables will become negative and we will see "blink".

**Comment by badlogic** [comment]
Thank you for reporting, I've fixed this on the 3.6, 3.7-beta and 3.7-beta-cpp branches. The C++ runtime was not affected by this.
