### ISSUE TITLE
[ue4] Update to 4.21

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1201]

**Comment by fvmitnick** [comment]
where can i download the the plugin ?

**Comment by badlogic** [comment]
See http://esotericsoftware.com/spine-ue4. Please use the 3.7-beta-cpp branch.

**Comment by badlogic** [comment]
Closed via https://github.com/EsotericSoftware/spine-runtimes/commit/4c9ec0608384e62e153239301d02ca23c8c4eaab
