### ISSUE TITLE
[runtimes] AnimationState attachmentThreshold does not work

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#1204]
The current implementation has no effect. We want it to behave as follows:

* Use the timeline's attachment if mix percentage < attachmentThreshold, else use the setup pose attachment.
* If the mix percentage is 1, use the setup pose attachment. This should be true if attachmentThreshold is never > 1. Mix percentage is 1 when an entry will no longer be applied

Test asset can be found at:

https://drive.google.com/open?id=15P-rdfMn3bzm8vUMft4oNeCzTn9ndYkU

Ready to port:
https://github.com/EsotericSoftware/spine-runtimes/commit/b4c50035b89b989fee5ba70f2965e301f0319bdf

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

**Comment by pharan** [comment]
http://esotericsoftware.com/forum/Unity-SetAnimation-and-Attachments-mix-11036

**Comment by NathanSweet** [comment]
@pharan Can you please try out that fix and verify it's good before it's ported to all runtimes?

**Comment by pharan** [comment]
Looks good. This fixes the transition A->B where A has a key and B does not.
