### ISSUE TITLE
How do you perform multiple different animations in a spine at the same time

### ISSUE THREAD

**Issue by fanfantu** [EsotericSoftware/spine-runtimes#1206]
How to execute multiple different animations in spine at the same time? Now I have created multiple different canvas, but when the animation is executed at the same time, it will cause carton to lose frames. I want to ask how to solve this problem in a short time

**Comment by badlogic** [comment]
Could you ask this question on the forum at http://esotericsoftware.com/forum/?f=3? This issue tracker is usually reserved for issue reports and not general questions.

What Spine runtime are you using? You are speaking of canvas, so I assume you use the spine-ts widget runtime? Please include that information, along with a link to a test that shows the problem in your forum post.
