### ISSUE TITLE
[unity] Link to documentation about controlling animations is leading to Page not found

### ISSUE THREAD

**Issue by sNAtttu** [EsotericSoftware/spine-runtimes#1209]
Hello!

First of all I want to thank all of you about for the great assets in the 2D RPG bundle in the newest Humble Bundle.

I'm trying to learn how to use the spine runtimes with unity and I tried to use this link provided by your website 
![image](https://user-images.githubusercontent.com/6155769/48666911-8844a800-ead3-11e8-81de-f8f9d5172bb6.png)

However this link is leading me to the default site when page is not found 👎 If you could fix the link or provide me the correct link I would really appreciate your effort.

Screenshot from the URL (http://esotericsoftware.com/Animation.md) the link forwards me:

![image](https://user-images.githubusercontent.com/6155769/48666924-f9845b00-ead3-11e8-95a4-854f9f7a20de.png)

Thanks!
- Santeri Nousiainen

**Comment by pharan** [comment]
Thanks for reporting.
The link on the site is http://esotericsoftware.com/spine-unity-animation

The server has some caching settings (browser side) so changes may not be reflected unless you force refresh a page.
