### ISSUE TITLE
 Dynamically display the data obtained by the server. For example, the slot in the spine has the slot of the student's name, retrieve the data from the server, and update the slot.

### ISSUE THREAD

**Issue by ahao1011** [EsotericSoftware/spine-runtimes#1212]
I use spine-cocos2d-objc to implement a game that contains the student's name and avatar. I need to update the data obtained by the server to the corresponding slot. What should I do? Thank you

**Comment by badlogic** [comment]
Please ask this question on the forum at https://esotericsoftware.com/forum. We only use the issue tracker for bugs and enhancement tracking.
