### ISSUE TITLE
Cocos2d-X c++ missing mesh

### ISSUE THREAD

**Issue by oziphantom** [EsotericSoftware/spine-runtimes#1213]
Hello again, they finally got around to testing the animations or at least more of them. And this one https://www.dropbox.com/s/yt8t3sdayd7s4h9/lionBug.zip?dl=0 fails to show the rod and background net in its animation.
 I noticed that there were some updates to spine-c so I downloaded the new new 3.6 runtimes, and copied over the spine-c files. Clean rebuild, and the handle of the net, and "background" net don't show. The Foreground net ( so that the bug can be hidden ) does show. I enabled the debug options, the bones are there and working as expected, however when I enable the mesh debug, there is no mesh object for the rod or the background net showing. I've have a look at the json they are there, they are in the atlas file, in the png, I can't see any thing odd with them in the json, they are  just not rendering in the engine.

**Comment by badlogic** [comment]
@oziphantom could you please send me the Spine project? I'll re-open once I have that.

**Comment by oziphantom** [comment]
https://www.dropbox.com/s/qdaqo5ekifz9i3v/LION%20CATCHES%20SPINE.zip?dl=0

**Comment by badlogic** [comment]
Cheers! It appears there are spaces in some of the region names, e.g. "PNG/ROD ". The C runtime strips those when loading the atlas, but the spaces are retained when searching for attachments in the atlas. I'll fix this on Monday.

**Comment by badlogic** [comment]
This is now fixed int the 3.6, 3.7-beta, and 3.7-beta-cpp branches.

**Comment by rh101** [comment]
This fix has caused an issue. The code that was commented out is causing the trim method to not remove the carriage return character when it is parsing the text in the atlas file.  For instance, it's picking up the "/r" character at the end of name of the image file that is referenced in the atlas file (so "image.png" is coming out as "image.png/r").  In this case it ends up crashing down the line since it cannot find the image file to load.  This was tested on Cocos2d-x 3.17.

**Comment by badlogic** [comment]
Ah yes, this is fixed in 3.7-beta(-cpp), but I forgot to backport it, see https://github.com/EsotericSoftware/spine-runtimes/commit/08694b37b397a6bcc186c36678c1d66dc958a9ce

I'll fix this up tomorrow, thanks for the report!

**Comment by badlogic** [comment]
This is now fixed in the 3.6 branch as well.

**Comment by rh101** [comment]
Thank you
