### ISSUE TITLE
Crash with skeleton binary

### ISSUE THREAD

**Issue by rekcah1986** [EsotericSoftware/spine-runtimes#1214]
Spine: 3.6.52 Professional
Runtime: cocos2d-x 3.6
Spine Runtime: 3.6

My game crashed when load the “.skel” file, but no crash with the ".json" file.
I found the code in SkeletonBinary.c:695 (in function spSkeletonBinary_readAttachment)
```
    switch (type) {
        case SP_ATTACHMENT_REGION: {
            const char* path = readString(input);
            spAttachment* attachment;
            spRegionAttachment* region;
            if (!path) MALLOC_STR(path, name);
            attachment = spAttachmentLoader_createAttachment(self->attachmentLoader, skin, type, name, path);
            region = SUB_CAST(spRegionAttachment, attachment);
            region->path = path;
```
spAttachmentLoader_createAttachment return NULL, then the region is NULL.

Sorry for my poor English, please help me.

**Comment by rekcah1986** [comment]
The animation files: [mn.zip](https://github.com/EsotericSoftware/spine-runtimes/files/2610250/mn.zip)

**Comment by rekcah1986** [comment]
Simliar to: [Region not found in atlas error](http://zh.esotericsoftware.com/forum/Unity-Region-not-found-in-atlas-error-2317?sid=67dea7bbc875f9281fc09622f2d78cc9&p=11445&hilit=readAttachment#p11445)

**Comment by badlogic** [comment]
@rekcah1986 your .atlas file is missing the region "starout_0007".

**Comment by rekcah1986** [comment]
Can you add a function to automatically check this problem before exporting? @badlogic

**Comment by badlogic** [comment]
The editor should actually already warn you when the exported atlas does
not contain everything you need. If taht is not the case for your project,
please send us your Spine .project and image files.
