### ISSUE TITLE
[cocos2dx] Cannot display correctly mesh

### ISSUE THREAD

**Issue by ccmfeng** [EsotericSoftware/spine-runtimes#1217]
Spine: 3.6.52 Professional
Runtime: cocos2d-x 3.17
Spine Runtime: 3.6
![org](https://user-images.githubusercontent.com/6304643/49324561-2a03d480-f56b-11e8-8a3c-3a05dc02c865.png)
![bug](https://user-images.githubusercontent.com/6304643/49324562-2f611f00-f56b-11e8-99b5-62ea59018849.png)
![spine](https://user-images.githubusercontent.com/6304643/49324575-67686200-f56b-11e8-8766-c9e2f7f9583f.png)

**Comment by badlogic** [comment]
Please send me your .json/.skel/.atlas/.png files. I'll re-open once I have those.

**Comment by ccmfeng** [comment]
[spine.zip](https://github.com/EsotericSoftware/spine-runtimes/files/2648632/spine.zip)

**Comment by badlogic** [comment]
I've tried your skeleton using the latest Spine 3.7-beta runtime from this repository, playing back the animation "01A":

![https://libgdx.badlogicgames.com/uploads/kr2A3mQQ04.png](https://libgdx.badlogicgames.com/uploads/kr2A3mQQ04.png)

I've also tried using the Spine runtime from the 3.6 branch in this repository:

![https://libgdx.badlogicgames.com/uploads/zLvDYIveLG.png](https://libgdx.badlogicgames.com/uploads/zLvDYIveLG.png)

Please make sure you use the Spine Cocos2dx runtime from this repository, and not the one that is shipped with Cocos2dx itself. It is outdated and buggy.
