### ISSUE TITLE
[runtimes] Clipping code does not handle some singularities

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-runtimes#1219]
If some vertices of a triangle to be clipped overlap with vertices of the convex clipping polygon, singularities may appear. Guard against them.

Fix here: https://github.com/EsotericSoftware/spine-runtimes/commit/637db7ca9d0641a0dd29d83c81e2780d2674475c

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua 
- [x] spine-love
- [x] spine-corona

## Original report

**Description:**
After pasting the vertices of the windmill blades on the clipping, the clipping fails to show the blades texture. If the lowest vertex is moved, the blades partially cut show again.

**Repro project:**
[Download](http://www.esotericsoftware.com/files/issues/406-clipping-bug-windmill.zip)

**Repro gif:**
![gif](https://media.giphy.com/media/z2bRUAdkUGncJVvPFl/giphy.gif)

**Comment by NathanSweet** [comment]
@badlogic I created a minimal repro program, can you take a look?
http://n4te.com/x/5614-N4E4.txt

**Comment by NathanSweet** [comment]
3.7.69-beta prevents the clipping NaNs from wrecking the editor camera when opening the project, though clipping still has the bug shown in the GIF and program above.
