### ISSUE TITLE
[unity] Spine causes lag when pressing Play in Unity

### ISSUE THREAD

**Issue by revolt3r** [EsotericSoftware/spine-runtimes#1221]
https://github.com/EsotericSoftware/spine-runtimes/blob/a8ffa92cabd088bc4d996f3955b3b3af406ac7c0/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs#L49

InitializeOnLoad is not perfect, it will make editor script rerun on each "enter Play mode" or "exit Play mode".
It's recommented to initialize editor scripts if this is false: EditorApplication.isPlayingOrWillChangePlaymode

Or you could also load most of these settings lazilly.

**Comment by pharan** [comment]
We'll have the `EditorApplication.isPlayingOrWillChangePlaymode` check for now.
https://github.com/EsotericSoftware/spine-runtimes/commit/987d0741521917e12599ff6653a43f96699e4d37

We'll look into further improvements in this area, especially related to returning to edit mode.
Important to check are instances where an assembly reload happens, and what effect that has to statics and if it's ok to lose references in that case. If it gets messy, lazy instantiation may just be the way to go.
