### ISSUE TITLE
[unity] Assets sometimes error out on a fresh runtime import.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#1226]
This doesn't affect actual user productivity but it does feel a bit sloppy when it happens. It seems to have something to do with the order that asset validation and serialization occurs.

http://esotericsoftware.com/forum/Skeleton-JSON-file-not-set-error-on-project-import-11227

The part user reports is some OnValidate code in SkeletonGraphic, which probably tries to initialize the component to perform some check. Some of it may be better off moved into actual editor code.

**Comment by HaraldCsaszar** [comment]
Recently reproduced a very similar issue (should be of the same problem origin), see #1252.

**Comment by HaraldCsaszar** [comment]
Steps to reproduce (at lease produces same error message, circumstances could differ):

1. In Unity 2017.1.0f3, create an empty project.
2. Import e.g. `spine-unity-3_7-2019-01-16.unitypackage`.
3. Drag a SkeletonData object into the scene with mode `Skeleton Graphic` and save the scene under a directory outside of the imported Spine dirs.
4. Close Unity and then delete the `Spine` and `Spine Examples` dirs and also the `Library` dir.
5. Open Unity again and open scene described above (will contain missing scripts and materials, ignore those).
6. Import the same unitypackage again while the scene described above is open.
7. Reimport messages are appearing as log messages, e.g.:
```
"eyes_Atlas :: Imported with 1 material
..."
```
8. Error message will appear for SkeletonGraphic's assets:
```
Skeleton JSON file not set for SkeletonData asset..
```

Also reproduced on Unity 2017.1.0f3, imported newer unitypackage (3_7-2019-01-14) over existing project with testscene containing two SkeletonGraphic gameobjects open.
Error message:
```
"Skeleton JSON file not set for SkeletonData asset: spineboy-unity_SkeletonData
UnityEngine.Debug:LogError(Object, Object)
Spine.Unity.SkeletonDataAsset:GetSkeletonData(Boolean) (at Assets/Spine/Runtime/spine-unity/Asset Types/SkeletonDataAsset.cs:114)
Spine.Unity.SkeletonGraphic:Initialize(Boolean) (at Assets/Spine/Runtime/spine-unity/Modules/SkeletonGraphic/SkeletonGraphic.cs:238)
Spine.Unity.SkeletonGraphic:OnValidate() (at Assets/Spine/Runtime/spine-unity/Modules/SkeletonGraphic/SkeletonGraphic.cs:105)"
```

**Comment by HaraldCsaszar** [comment]
Recently discovered the problem in another context, in Unity 2018.3.0f1:
1. Delete Spine and Spine Examples dirs
2. Import unitypackage (don't close Unity or delete the Library dir)
3. The following error is displayed for every Spine skeleton asset:
```
Skeleton JSON file not set for SkeletonData asset: hero-pro_SkeletonData
UnityEngine.Debug:LogError(Object, Object)
Spine.Unity.SkeletonDataAsset:GetSkeletonData(Boolean) (at Assets/Spine/Runtime/spine-unity/Asset Types/SkeletonDataAsset.cs:114)
Spine.Unity.Editor.SkeletonInspectorPreview:Initialize(Action, SkeletonDataAsset, String) (at Assets/Spine/Editor/spine-unity/Editor/SkeletonDataAssetInspector.cs:779)
Spine.Unity.Editor.AnimationReferenceAssetEditor:HandleOnEnablePreview() (at Assets/Spine/Editor/spine-unity/Editor/AnimationReferenceAssetEditor.cs:135)
Spine.Unity.Editor.AnimationReferenceAssetEditor:OnEnable() (at Assets/Spine/Editor/spine-unity/Editor/AnimationReferenceAssetEditor.cs:61)
UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)

```
