### ISSUE TITLE
[3.7 Unity] A local or parameter named 'pathLength' 

### ISSUE THREAD

**Issue by ledvinam** [EsotericSoftware/spine-runtimes#1228]
Assets/Git/Spine/Runtime/spine-csharp/src/PathConstraint.cs(190,11): error CS0136: A local or parameter named 'pathLength' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter

**Comment by badlogic** [comment]
Thanks for reporting, fixed on the 3.7-beta and 3.7-beta-cpp branches.
