### ISSUE TITLE
Support whitespace stripped mesh texture regions

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#1232]
As of Spine 3.7.77-beta, the texture packer can do whitespace stripping for meshes. A little runtime support is needed.

For testing I modified spineboy-pro so the gun has difference amounts of whitespace on all 4 sides and made it a mesh where the upper left and bottom right corners were obvious (centered in the red balls):
![](http://n4te.com/x/5811-FkGi.png)
Test project:
http://n4te.com/x/5813-issue-1232-spineboy-project.zip
Export with whitespace stripping:
http://n4te.com/x/5847-json.zip

## Porting

Commit: 63238bfc69d449bffa6518f2c357a8204ba90bff and b12658d8adeb197a44058b38a66c92723bbf31b5

Optional: 9d77b4bf12acd11857f34f4342718f94362e3988

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua 
- [x] spine-love
- [x] spine-corona

**Comment by pharan** [comment]
Neat.
