### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by shenghaiyang** [EsotericSoftware/spine-runtimes#1234]
Will add flutter support officially?

**Comment by badlogic** [comment]
We have no short or mid term plans for Flutter support.

**Comment by raybarrera** [comment]
Any chance this will be reconsidered given the rise in popularity?

**Comment by subzero911** [comment]
+1 for Flutter support

**Comment by guopeng1994** [comment]
flutter 2.0 has came out. so any ideas now? @badlogic

**Comment by raybarrera** [comment]
Basically ceding the space to Rive without a flutter runtime.
