### ISSUE TITLE
[unity] Unity2018 SkeletonGraphic broken

### ISSUE THREAD

**Issue by Henry-T** [EsotericSoftware/spine-runtimes#1235]
Add dragon to scene as SkeletonGraphic it seems broken, but hero works.

![image](https://user-images.githubusercontent.com/4081321/50442540-4dd3f380-093a-11e9-989f-7dce30450cd0.png)

Unity3D 2018.2.1f1
Spine Runtime: 3.6 (2018-12-12)

**Comment by pharan** [comment]
Hi! This is a known limitation of SkeletonGraphic, which is a limitation of the class that it derives from (MaskableGraphic)

The UnityEngine.MaskableGraphic base class is used to integrate into some of Unity's UI systems such as group coloring and masking. MaskableGraphic can however only accept one Texture2D. Likewise, SkeletonGraphic can only use one Texture2D.

Dragon is a skeleton demoing a multi-page (multiple texture) backing atlas. This is why it specifically breaks when used with SkeletonGraphic.

You can see the documentation on it for more info: http://esotericsoftware.com/spine-unity-skeletongraphic-and-ui
