### ISSUE TITLE
[spine-c] Duplicate SP_ANIMATION_COMPLETE callback.

### ISSUE THREAD

**Issue by AntonPetrov83** [EsotericSoftware/spine-runtimes#1237]
Setting new animation after receiving `SP_ANIMATION_COMPLETE` provokes duplicate  `SP_ANIMATION_COMPLETE` sent from `_spAnimationState_applyMixingFrom()` this line:
```
if (to->mixDuration > 0) _spAnimationState_queueEvents(self, from, animationTime);
```

**Comment by badlogic** [comment]
I've tried to reproduce this using our spine-c SFML example, adding `spAnimationState_setAnimationByName(state, 0, "walk", true);` in line 58 in the completion callback. I observe no duplicate SP_ANIMATION_COMPLETE events.

Please modify our SFML example so that I can reproduce the issue.
