### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by CoalaJoe** [EsotericSoftware/spine-runtimes#1239]
I've been looking though the repository and noticed a couple of flaws or inconsistencies:
- Documentation from runtime implementations are often copy-pasted. e.g. spine-sfml/cpp says it's using spine-c.
- spine-c has the Json.c file in the includes folder instead of in the sources folder.

It is super hard for me to get started. I tried to use the spine-c and there are a lot of sp-prefixed function that are in the the code but not in the documentations. 

I hope someone can help me out.

**Comment by badlogic** [comment]
Sorry for the inconsistencies, thanks for pointing them out! I'll clean this up in the beta branch asap.

Regarding documentation, you can check out our spine-c and spine-cpp guides here:

http://esotericsoftware.com/spine-c
http://esotericsoftware.com/spine-cpp

Could we move discussion of APIs and usage to the forums? https://esotericsoftware.com/forum

**Comment by CoalaJoe** [comment]
@badlogic Sure. Thank you!
