### ISSUE TITLE
[ts][canvas] upside-down spineboy

### ISSUE THREAD

**Issue by jbloit** [EsotericSoftware/spine-runtimes#1241]
The spine boy is upside down in the canvas example, in 3.7 ([e6a5ef3]). It works fine in 3.6.

**Comment by badlogic** [comment]
Thanks for reporting. This is due to this line in the example:

https://github.com/EsotericSoftware/spine-runtimes/blob/3.7/spine-ts/canvas/example/index.html#L74

It flips the skeleton on the y-axis. Without this line, Spineboy is upright.
