### ISSUE TITLE
[unity] Mecanim animation preview windows

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1253]
Selected Mecanim animations (nested below the Controller asset in project window) do not show the respective Spine object or play back animations in the inspector preview window.

Also consider improving the playback Preview bar with the red line (non-interactive) in the SkeletonDataAsset, as reported here on the forum:
http://esotericsoftware.com/forum/preview-each-frame-of-animation-seconds-controlled-slider-14594

**Comment by Johnyfirst** [comment]
Wanted to follow up on this issue.
I've tried versions 3.8 and 4.0 beta for Unity and the issue still persists.

**Comment by HaraldCsaszar** [comment]
Thanks, we are aware of that, otherwise the ticket would have been closed instead of being put on hold. The `ready` tag does not mean ready for the end user, perhaps this was the reason for your comment.

Unfortunately Unity's Editor and Mecanim API is very prohibitive in this regard (sealed classes, use of concrete classes instead of interfaces, etc), most likely not allowing for this implementation at all.

So most likely the feasible improvement will be:
1. The "playback Preview bar with the red line (non-interactive) in the SkeletonDataAsset" mentioned above.
2. Displaying synchronized skeleton playback when scrubbing in the Animation Window, for placing Unity events.

Transition preview windows might most likely not be possible at all. Sorry. We had to put this issue on hold due to the time necessary to complete it and due to its rather low importance in comparison to other issues.

**Comment by PHANzgz** [comment]
Would love to see this implemented. Without it, it's tricky to add weapon slashes and effects.

**Comment by HaraldCsaszar** [comment]
@PHANzgz Please note that the standard way is to add events in the Spine Editor, where they can be placed precisely, and then handle these events in Unity.

**Comment by PHANzgz** [comment]
@HaraldCsaszar I see. We'll try to do the weapon slashes inside Spine, although we are not used to that workflow. Thank you.
Still, would love to see this implemented eventually.

**Comment by AnduoGames** [comment]
Heya, I found a kinda hacky but working solution to this. Through reflection, you can easily read out the time of the editor animation window. Then you just need to apply the spine animation with that time.


```cs
var time = GetAnimationWindowCurrentTime();
var animatorClip = GetCurrentAnimationClip();
// get your animation equivalent to the animator clip
animation.Apply(skeleton, 0, time, true, null, 1, Spine.MixBlend.Replace, MixDirection.In);

public static float GetAnimationWindowCurrentTime()
{
    UnityEngine.Object w = GetOpenAnimationWindow();
    if (w != null)
    {
        BindingFlags flags = BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance;
        FieldInfo animEditor = GetAnimationWindowType().GetField("m_AnimEditor", flags);

        Type animEditorType = animEditor.FieldType;
        System.Object animEditorObject = animEditor.GetValue(w);
        FieldInfo animWindowState = animEditorType.GetField("m_State", flags);
        Type windowStateType = animWindowState.FieldType;

        return (float)windowStateType.GetProperty("currentTime").GetValue(animWindowState.GetValue(animEditorObject));
    }

    return 0f;
}

public static AnimationClip GetCurrentAnimationClip()
{
    var window = GetOpenAnimationWindow();
    if (window != null)
    {
        var flags = BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance;
        var animEditorField = AnimationWindowHelper.GetAnimationWindowType().GetField("m_AnimEditor", flags);

        var animEditorType = animEditorField.FieldType;
        var animSelectionProperty = animEditorType.GetProperty("selection", flags);

        var animEditorObject = animEditorField.GetValue(window);
        var selection = animSelectionProperty.GetValue(animEditorObject);

        var animationClipField = selection.GetType().GetProperty("animationClip");

        var clip = animationClipField.GetValue(selection);

        return clip as AnimationClip;
    }

    return null;
}

public static UnityEngine.Object GetOpenAnimationWindow()
{
    UnityEngine.Object[] openAnimationWindows = Resources.FindObjectsOfTypeAll(GetAnimationWindowType());
    if (openAnimationWindows.Length > 0)
    {
        return openAnimationWindows[0];
    }
    return null;
}

public static System.Type GetAnimationWindowType()
{
    if (animationWindowType == null)
    {
        animationWindowType = System.Type.GetType("UnityEditor.AnimationWindow,UnityEditor");
    }
    return animationWindowType;
}

```

**Comment by HaraldCsaszar** [comment]
@AnduoGames Thanks for sharing your code, very much appreciated in general! Unfortunately we already had this part working, hence the comment [above](https://github.com/EsotericSoftware/spine-runtimes/issues/1253#issuecomment-790768812) mentioning that the feasible improvements will likely be limited to playing back animations from the Animation window. Very sorry that this was not clearly pointed out in the posting!

What would really be a great improvement would be if we had a way to preview transitions of the Animator (not Animation) window.

Nevertheless, this is a great reminder that we need to include the code of the old prototype in the next beta version of the spine-unity runtime, so that at least the Animation window (not Animator window) preview is played back for easier placement of manual events. Thanks for bringing this to our intention!

**Comment by HaraldCsaszar** [comment]
The `SkeletonMecanim` inspector now received a `Scene Preview` option to preview an Animation Clip for e.g. easier event placement. When enabled, the Animation Clip selected in the Animation window is previewed in the Scene and Game views. Lock the `SkeletonMecanim` Inspector window, open the Animation window and select the Animation Clip. Then in the Animation window scrub through the timeline to see the current animation frame previewed.

**Comment by HaraldCsaszar** [comment]
A new spine-unity 4.2 unitypackage is available:
https://esotericsoftware.com/spine-unity-download
