### ISSUE TITLE
[unity] SkeletonRenderSeparator for SkeletonGraphic

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1254]
Currently SkeletonRenderSeparator can be used on `SkeletonAnimation` only.
This feature could be used for e.g. partially-clipped characters in GUI-circles.

See forum: http://esotericsoftware.com/forum/Separator-with-skeletongraphics-11375

`SkeletonPartsRenderer.cs` and `SkeletonRenderSeparator.cs` need to be adapted for `SkeletonGraphic` accordingly.

**Comment by mcraiha** [comment]
Is there any timetable for this feature? We could really use this for certain UI elements.

**Comment by HaraldCsaszar** [comment]
You can expect the feature roughly estimated in the following few weeks.
Note however that urgent bugfixes will always be prioritized higher.

**Comment by HaraldCsaszar** [comment]
This feature turned out to depend on https://github.com/EsotericSoftware/spine-runtimes/issues/1592 as an implementation basis, thus it took longer. Sorry for the wait, hope you like it!
