### ISSUE TITLE
[unity] LWRP example scene and out-of-the-box support in Unity 2019

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1255]
Unity's Light Weight Render Pipeline caused problems on a user's setup with `Skeleton Lit shader`:

Forum: http://esotericsoftware.com/forum/Skeleton-Lit-shader-not-compatible-with-new-LWRP-11381

- [x] Port/rewrite incompatible shaders for LWRP
- [x] Provide LWRP example scene.
- [x] (unable to reproduce)Test existing shader for OpenGLES3.0 problem reported in comment below.
- [x] Create packaging scripts.
- [x] Release as UPM (Unity Package Manager) package.
- [x] Blog post
- [x] Release blog post (after 3.8)

**Comment by HaraldCsaszar** [comment]
Another user reports problems here on the forum:
http://esotericsoftware.com/forum/LWRP-Layer-Issues-10799

**Comment by ZhaoriGame** [comment]
Is there any progress

**Comment by HaraldCsaszar** [comment]
It was put on hold for 3.8 format changes and is now resumed.

**Comment by ZhaoriGame** [comment]
thanks, I look forward to use it soon

**Comment by HaraldCsaszar** [comment]
A user reported problems on Android with OpenGLES 3.0:
http://esotericsoftware.com/forum/LWRP-OpenGL-3-0-Android-always-renders-a-object-at-identity-12236
[edit:] Unable to reproduce the problem, asked for repro package.

**Comment by HaraldCsaszar** [comment]
A UPM package has been uploaded to the spine-unity download page:
https://esotericsoftware.com/spine-unity-download

Full documentation and blog entry will follow, for now please consult the CHANGELOG.md file for installation and usage instructions.
