### ISSUE TITLE
[monogame] iOS/Android sample

### ISSUE THREAD

**Issue by Owlzy** [EsotericSoftware/spine-runtimes#1256]
It seems from reading the source code that Android builds are not supported by MonoGame runtime.  Is this intended?  

I've got part way through implementing it, by extending Atlas.cs but am struggling to extend the SkeletonJson class.  Is this something that we should expect the runtime to support or are we expected to implement ourselves?

**Comment by badlogic** [comment]
We haven't investigated MonoGame + Spine on iOS/Android, as the only difference should be the file I/O API. I see in your [forum post](http://esotericsoftware.com/forum/MonoGame-XNA-Lacks-android-support-11401) that you figured that part out. We'll add an iOS/Android sample to our existing MonoGame sample in the future.

**Comment by badlogic** [comment]
I think we can close this, as we've resolved the issue as described in our forum posts here:

http://esotericsoftware.com/forum/MonoGame-XNA-Lacks-android-support-11401?p=51234#p51234
