### ISSUE TITLE
Unity 2018.3.4f1 error

### ISSUE THREAD

**Issue by OldOakDen** [EsotericSoftware/spine-runtimes#1272]
Hi,
I'm sorry for this request but true is that I'm graphic artist more than programmer. ;)

I extracted Spine-Unity 3.7 runtime unitypackage into Unity 2018.3.4f1 project and now I have this error in Unity:

 Assets/Spine/spine-unity/Modules/AnimationTools/AnimationTools.cs(215,6): error CS1501: No overload for method `SetFrame' takes `4' arguments

I know that this Spine-Unity runtime isn't built for this version of Unity but please exist some easy way how can I fix it please?

**Comment by HaraldCsaszar** [comment]
AnimationTools.cs file shall be deleted at user's local project, seems to be a left-over file of previously extracted unitypackages.
See forum posting here: http://esotericsoftware.com/forum/No-overload-for-method-SetFrame-11480
