### ISSUE TITLE
[cpp] SkeletonJson forgets to read images path

### ISSUE THREAD

**Issue by Pontation** [EsotericSoftware/spine-runtimes#1278]
Some of my assets use the images path in the skeleton e.g. 
```
"skeleton": {
		"hash": "rT7lqFEux8ByWJu8ww2iFIvaLnI",
		"spine": "3.7.81",
		"width": 470.72,
		"height": 731.57,
		"images": "./spine3/",
		"audio": ""
```

SkeletonJson::readSkeletonData in SkeletonJson.cpp doesn't read it and SkeletonData::_imagesPath is never assigned from what I can tell. I would expect it to be read and passed along to AttachmentLoader::newRegionAttachment and newMeshAttachment at least, so that I can look up the atlas textures with the correct path.

My current workaround is to pre-parse the entire json file to extract the image path, which is of course far from optimal, and hurts my little developer heart.

**Comment by badlogic** [comment]
@Pontation so sorry we hurt your little developer heart :( I've added parsing and storing of this non-essential data. Thanks for pointing it out!

**Comment by Pontation** [comment]
Thanks for the fix :)
