### ISSUE TITLE
[cocos2d-x]Rendering issues when the animation is created.

### ISSUE THREAD

**Issue by semgilo** [EsotericSoftware/spine-runtimes#1281]
After creating the animation, I paused the screen, the screen is as follows
![image](https://user-images.githubusercontent.com/7121873/52933975-127d0080-3390-11e9-88fe-206f55fff2d4.png)
After one frame, the picture is normal, as follows
![image](https://user-images.githubusercontent.com/7121873/52934009-34768300-3390-11e9-8ff5-4484d3e7eea0.png)
I searched the issues, but I didn't find the relevant content. If there are,please tell me, thank you.

**Comment by badlogic** [comment]
How and when do you set the scale of the skeleton? What version of the runtime are you using?

**Comment by semgilo** [comment]
Thank you for responding.
1.I set the scale on when it creating.
`static SkeletonAnimation* createWithBinaryFile (const std::string& skeletonBinaryFile, spAtlas* atlas, float scale = 1);`
2.runtime version:Spine Runtimes 3.5.35

**Comment by badlogic** [comment]
The Spine Runtimes version likely explains it. Could you update to 3.6, or maybe even 3.7? This issue has been fixed in those versions.

**Comment by semgilo** [comment]
ok,i will update and test it.

**Comment by semgilo** [comment]
@badlogic By the way, if I upgrade to 3.7, can I still use 3.6 spine exports resources?

**Comment by rh101** [comment]
If you manually call update(0) on the animation right after you create it, it will render correctly.

The way it works at the moment may actually be correct.  If the createWithBinaryFile() method called update() internally, this may cause unintended side-effects to the rendering of the next frame if any modifications need to be applied to the animation (which inherits from cocos2d::Node).

For example, this would render correctly if we are in control of when the update() is called:

```
auto animation = createWithBinaryFile(...);
animation->setScale(2.0f);
animation->setPosition(x,y);
animation->update(0);
```

Now, if the update() call happens within the spine runtime when the createWithBinaryFile() is called, it would be like this:

```
auto animation = createWithBinaryFile(...); // this calls update() somewhere in the creation process
animation->setScale(2.0f);
animation->setPosition(x,y);
```
and that may not render it correctly unless another update() occurs before the frame is drawn.

**Comment by badlogic** [comment]
hey @rh101, thanks for chiming in! What you said is actually what @semgilo should do: call `update(0)` after creating the node. This should also work in 3.5.x.

@semgilo regarding compatibility between versions: the binary format is not compatible between minor version updates, so you'd have to export. Apply @rh101 's recommendation first, that way you might be able to stay with your current runtime version.

**Comment by semgilo** [comment]
@rh101 @badlogic Thanks,it works.
