### ISSUE TITLE
[ue4]Skeleton Viewer

### ISSUE THREAD

**Issue by GitHub-NetFly** [EsotericSoftware/spine-runtimes#1291]
Because you can't see the information about Spine animation under UE4, you want to have a preview under UE4, or transplant a Skeleton Viewer to UE4..

I have made a simple preview at the moment but I have not done the rendering part of the image...
![3](https://user-images.githubusercontent.com/6991952/53778133-b17c2d80-3f36-11e9-9c7c-e3e31ba3d5c8.png)
![4](https://user-images.githubusercontent.com/6991952/53778140-b640e180-3f36-11e9-8b17-e4377ebc859c.png)

I hope that there will be a full version of Skeleton Viewer to UE4..

**Comment by badlogic** [comment]
This is cool! I can surely add the textual information you already implemented. However, previewing a skeleton .json/.skel file will also require an atlas to be specified.

**Comment by GitHub-NetFly** [comment]
I hope that there will be time to write the image preview function into the plugin, which will greatly reduce the communication cost at work.

**Comment by GitHub-NetFly** [comment]
This is cool!

**Comment by GitHub-NetFly** [comment]
[link](https://github.com/EsotericSoftware/spine-runtimes/commit/4ba46d76e88621d6f127202d9ef199d40c794e3c)

**Comment by GitHub-NetFly** [comment]
> This is cool! I can surely add the textual information you already implemented. However, previewing a skeleton .json/.skel file will also require an atlas to be specified.

[link](https://github.com/EsotericSoftware/spine-runtimes/commit/4ba46d76e88621d6f127202d9ef199d40c794e3c)   Looks like the "Event" preview is missing?


Also, I found that the editor preview feature and getting the Slots feature didn't work..

![3](https://user-images.githubusercontent.com/6991952/53928117-f41f4080-40c3-11e9-9348-eb884bab2c0f.png)

Missing code
![555](https://user-images.githubusercontent.com/6991952/53930386-0d2bef80-40cc-11e9-8324-a86a08c172f3.png)

![666](https://user-images.githubusercontent.com/6991952/53930469-53814e80-40cc-11e9-9db3-87b7c1f7fa27.png)


This is not working properly..
![2](https://user-images.githubusercontent.com/6991952/53928047-aefb0e80-40c3-11e9-8ede-a8ff109af094.png)

**Comment by GitHub-NetFly** [comment]
There is a new problem. Importing the json file engine will crash.. The engine version I am using is 4.21 source version.
![6](https://user-images.githubusercontent.com/6991952/53928646-dc48bc00-40c5-11e9-86d7-2de960f83c21.png)

![4](https://user-images.githubusercontent.com/6991952/53928655-e1a60680-40c5-11e9-819e-525fbc675ca2.png)

**Comment by GitHub-NetFly** [comment]
After testing, I found that many resources export json resource formats are different. Some json files will have strange characters.. Causes the read to fail.. Use .skel to read normally. It will not cause a crash..

**Comment by badlogic** [comment]
Thanks for testing! I'll be fixing the issues you mentioned.

**Comment by GitHub-NetFly** [comment]
> Thanks for testing! I'll be fixing the issues you mentioned.

Thank you very much for your contribution, making the spine-ue4 plugin more and more perfect.. The main problem now is that the preview of the animation doesn't work.. Other features are working fine, except for json import issues.. this is weird.. because spine export The json file, the data format is not exactly the same..

**Comment by badlogic** [comment]
I've fixed the JSON import error. Regarding the preview animation and skin not working: did you enable the `Real-time` viewport option?

![https://i.imgur.com/cJiwVHD.png](https://i.imgur.com/cJiwVHD.png)

Without this, the level view is not redrawn, so no animation can happen.

Still working on the encoding issue.

**Comment by GitHub-NetFly** [comment]
> I've fixed the JSON import error. Regarding the preview animation and skin not working: did you enable the `Real-time` viewport option?
> 
> ![https://i.imgur.com/cJiwVHD.png](https://camo.githubusercontent.com/b5e0118f60305eec050923afe5b0f67338a6c1c7/68747470733a2f2f692e696d6775722e636f6d2f634a69775648442e706e67)
> 
> Without this, the level view is not redrawn, so no animation can happen.
> 
> Still working on the encoding issue.

I think I found the problem.. your implementation is to add the Add Component in the main interface to achieve preview, and does not support preview inside the Actor. If you add a Component inside the Actor and then add it to the scene, then It will be invalid.. The effect is as follows... The Actor inside is actually empty.. sorry I didn't read the code carefully.
![1](https://user-images.githubusercontent.com/6991952/54003468-49735480-418d-11e9-99fb-af2d44cd7305.png)

I originally thought it would be a direct preview inside the Actor. Similar to adding SetAnimation to the ConstructionScript in Blueprint.
![2](https://user-images.githubusercontent.com/6991952/54003476-52fcbc80-418d-11e9-8894-37ea757e9de8.png)

![3](https://user-images.githubusercontent.com/6991952/54003480-5728da00-418d-11e9-8137-cdcfda24aa7e.png)

**Comment by GitHub-NetFly** [comment]
According to my previous functional requirements, I made a simple modification to the code, removed the Transient tag, and implemented the ability to preview the animation under the Actor. But this method has a problem, it will also be executed in the case of Runtime. It might be better to add it to the WITH_EDITORONLY_DATA macro, only for the Editor service.

![333](https://user-images.githubusercontent.com/6991952/54005518-bccc9480-4194-11e9-89e2-cd8245a04c60.png)

![123213](https://user-images.githubusercontent.com/6991952/54005594-fd2c1280-4194-11e9-8d21-61af8b5150aa.png)
