### ISSUE TITLE
[unity] Make shaders compatible with Linear Color Space

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#1301]
I found myself in a Gamma-Linear-HDR rabbit hole the past couple of days.

A forum user was previously encountering this same problem.
As it turns out, if you switch to Linear color space mode (sensibly, a recommendation if you go HDR), Unity has an undocumented requirement for shaders to tint properly: vertex colors need to be converted to linear space before they are used for tinting.

Without this correction, the colors set in the Unity Editor UI (and Spine Editor) won't match the rendered tint. They usually look noticeably more pale.

Proposed fix:

Vertex colors in vertex shader before:
```shaderlab
o.vertexColor = v.vertexColor;
```

Vertex colors in vertex shader after:
```shaderlab
#if UNITY_COLORSPACE_GAMMA
o.vertexColor = v.vertexColor;
#else
o.vertexColor = float4(GammaToLinearSpace(v.vertexColor.rgb), v.vertexColor.a);
#endif
```

I've noticed other third-party 2D assets like Ferr2D's built-in shaders were affected by this too, but Unity SpriteRenderers (?) already compensate for this somehow. The "Sprites/Default" shader code doesn't seem to have any code that does extra processing on color, but having this gamma-to-linear correction doesn't seem to negatively affect use with SpriteRenderers.

The `UNITY_COLORSPACE_GAMMA` shaderlab define can be used so that extra shaders JUST for Linear color space won't be necessary.

`GammaToLinearSpace (half3 sRGB)` is an inline method defined in Unity's built-in `UnityCG.cginc`.

As for `float4`, I'm not certain of how converting precision works in the GPU. But the shaders in spine-unity currently have float4s so that's the only reason for that in the sample.

**Comment by pharan** [comment]
Extra considerations:
1. Skeleton renderers apply PMA to the vertex colors. Would the colors still be correct when alpha is less than 1?

2. Tint black colors need to be transformed too?

Relevant code in UnityCG.cginc
https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/master/CGIncludes/UnityCG.cginc#L105-L112

**Comment by HaraldCsaszar** [comment]
Note: in order to keep PMA Vertex color logic intact and thus enable single-pass additive blend mode rendering, the best implementation could be the following:
[edit: corrected code below]
```
#if UNITY_COLORSPACE_GAMMA
o.vertexColor = v.vertexColor;
#else
o.vertexColor = gammaPMAColor.a == 0 ?
		half4(GammaToLinearSpace(gammaPMAColor.rgb), gammaPMAColor.a) :
		half4(GammaToLinearSpace(gammaPMAColor.rgb / gammaPMAColor.a) * gammaPMAColor.a, gammaPMAColor.a);
#endif
```
This is sacrificing a bit of precision through the unnecessary multiplication & division, but is superior to disabling `PMA vertex colors` and thus breaking additive batching, and making the shader more complicated by having an additional parameter `Straight Alpha Vertex Colors`, or changing `Straight Alpha Texture` to a unified `Straigh Alpha`, which breaks existing behaviour.

**Comment by HaraldCsaszar** [comment]
Above commit closes the ticket.
New 4.0-beta packages have been released and are available for download.
