### ISSUE TITLE
[Cocos2d-x]Spine not show when add to Billboard

### ISSUE THREAD

**Issue by kienvn** [EsotericSoftware/spine-runtimes#1302]
bool HelloWorld::init()
{

if ( !Scene::init() )
{
    return false;
}

auto visibleSize = Director::getInstance()->getVisibleSize();
auto origin = Director::getInstance()->getVisibleOrigin();

auto camera = Camera::createPerspective(60.0, visibleSize.width / visibleSize.height, 1.0f, 1000.f);
camera->setCameraFlag(CameraFlag::USER2);
camera->setPosition3D(Vec3(0.f, 0.f, 100.f));
camera->lookAt(Vec3(0.f, 0.f, 0.f));
addChild(camera);

auto billboard = BillBoard::create(BillBoard::Mode::VIEW_POINT_ORIENTED);
this->addChild(billboard);

SkeletonAnimation* sp = SkeletonAnimation::createWithJsonFile("fish_freeze_idle.json", "img.atlas", 1);
sp->setAnimation(0, "run", true);
sp->setCameraMask((unsigned short)CameraFlag::USER2);
billboard->addChild(sp);

return true;
}
`

This code worked on 3.4 runtime before

**Comment by badlogic** [comment]
Please modify one of the scenes in the cocos2d-x example project in this repository for me to reproduce the issue.

**Comment by kienvn** [comment]
@badlogic 
[Archive.zip](https://github.com/EsotericSoftware/spine-runtimes/files/2959715/Archive.zip)
Thanks for your interest!

**Comment by kienvn** [comment]
Hi @badlogic,
I've fixed this bug by init trianglesCommand with flags = 0, spine node will be 2D

**Comment by badlogic** [comment]
This appears to be a bug in Cocos2d-x. We simply pass along the `transformFlags` that are handed down the scene graph to `SkeletonAnimation::draw` and `SkeletonRenderer::draw`. I suggest simply extending either of the two classes for your use case and overwrite the value passed down the scene graph as you outlined.

**Comment by pandaGames** [comment]
> Hi @badlogic,
> I've fixed this bug by init trianglesCommand with flags = 0, spine node will be 2D

HI，can you post your code so I can fix it too?thx!

**Comment by dong0763** [comment]
> This appears to be a bug in Cocos2d-x. We simply pass along the `transformFlags` that are handed down the scene graph to `SkeletonAnimation::draw` and `SkeletonRenderer::draw`. I suggest simply extending either of the two classes for your use case and overwrite the value passed down the scene graph as you outlined.

Hi @badlogic ,
there is a bug that if initing trianglesCommand with flags = 0, spine will always show above of sprite3d.
