### ISSUE TITLE
[unity] Arbitrary frame animation preview in Scene

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1304]
Feature requested multiple times on the forum here: http://esotericsoftware.com/forum/Play-an-animation-on-editor-mode-11084

Currently the starting animation's first frame is displayed in the Scene window.
Provide means in e.g. the Inspector to set the preview frame to an arbitrary frame.
It shall also be considered to add `play` functionality that plays back the whole animation in the Scene window instead of showing a single static frame.

**Comment by hanthuyen8** [comment]
Hi, do you guys have any update yet?

**Comment by HaraldCsaszar** [comment]
Sorry, no update yet, this has been delayed due to many more important issues.

**Comment by FNGgames** [comment]
Hey Harald, Is this still in the backlog? Being able to set an SkeletonAnimation frame by frame in the editor would be huge for our camera / cutscene toolset. In the camera tools we have the ability to scrub a cutscene's timeline from 0-1 with all the camera moves, zooms etc intact. If we could add animation previewing to that it would be really valuable. Right now we have to guess at what the animation is doing in the scene view as we frame stuff.

**Comment by HaraldCsaszar** [comment]
@FNGgames Yes, it's still on our roadmap, otherwise the ticket would have been closed.
Regarding cutscenes and Unity Timeline, please note that there is an extension UPM package available to provide Timeline integration:
http://esotericsoftware.com/spine-unity#Timeline-Extension-UPM-Package
Also be sure to check out the tutorial video here:
https://www.youtube.com/watch?v=V2z6FZxIrb0

**Comment by HaraldCsaszar** [comment]
Related pull request for reference:
https://github.com/EsotericSoftware/spine-runtimes/pull/2351

**Comment by HaraldCsaszar** [comment]
This feature has just been implemented, see the forum thread for details:
https://ko.esotericsoftware.com/forum/d/11084-play-an-animation-on-editor-mode/16

New spine-unity 4.1 and 4.2-beta unitypackages are available for download here as usual:
https://esotericsoftware.com/spine-unity-download
