### ISSUE TITLE
[unity] SkeletonGraphic blend modes support

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1316]
As reported via email:
FMfcgxwBWSxklFKCkMvWXkzwSPRFpNNx

Blend modes (multiply, add, ..) are not currently supported on SkeletonGraphic, due to the limitation of Unity.UI.Graphic to a single material. This could be worked around by e.g. adding additional vertex attributes (an additional enum int value per vertex for "normal", "multiply", "add", etc) and processing them in the fragment shader.

**Comment by weiping-playnext** [comment]
Not sure if related. The existing shader for SkeletonGraphic can be amended to support CanvasGroup alpha setting by simply splitting the Blend Operations for the Color and Alpha Chanels.
Instead of 
`Blend One OneMinusSrcAlpha`
try
`Blend One OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha`

**Comment by HaraldCsaszar** [comment]
Also requested on this forum thread:
http://esotericsoftware.com/forum/skeletongraphic-13031
