### ISSUE TITLE
[unity] masking doesn't work for skeleton with attachments packed to several sprite atlases

### ISSUE THREAD

**Issue by maximkornilov** [EsotericSoftware/spine-runtimes#1319]
**Repro steps:**

1. Skeleton attachments are packed to several sprite atlases
2. SkeletonAnimation component is used inside Sprite Mask
3. Mask interaction for skeleton is set to "Visible Inside Mask"

**Actual**: the rendering of the skeleton is totally broken
**Expected**: skeleton is rendered correctly and masking is working

Unity Version: 2018.3.7f1
Spine runtime version:  spine-unity-3_7-2019-03-04

**Comment by HaraldCsaszar** [comment]
Could not reproduce with described setup.
Renders correctly both with a single atlas with two pages, as well as three atlases with a single page per atlas.

Please verify that there is no problem with access permissions on your side to save the generated files, and that no other scripts are interfering with the save operation.

If the problem persists, please send us a repro zip package to contact@esotericsoftware.com.
