### ISSUE TITLE
[unity] mask interaction behavior is not reverted back to none after it was set to visible "Inside/Outside" of mask

### ISSUE THREAD

**Issue by maximkornilov** [EsotericSoftware/spine-runtimes#1320]
**Repro steps:**

1. Update skeleton animation `Mask Interaction` property to `Visible Inside Mask`
2. Press the play button, check that masking is applied
3. Change your mind and update back `Mask Interaction` property to `None` default value
4. Press the play button

**Actual**: the masking is still applied

Unity Version: 2018.3.7f1
Spine runtime version:  spine-unity-3_7-2019-03-04

**Comment by HaraldCsaszar** [comment]
Could not reproduce within described setup. Tried with saving and without saving, also in Unity 2019.1, problem did not occur.

Please verify that there is no problem with access permissions on your side to save the generated files, and that no other scripts are interfering with the save operation.
