### ISSUE TITLE
[unity] Timeline not supported on Unity 2019

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1326]
As reported on the forum:
http://esotericsoftware.com/forum/Unity-2019-Runtime-11789?p=52838#p52838
http://esotericsoftware.com/forum/Unity-Timeline-after-update-to-2019-1-11819

Status:
Currently an #if branch excludes timeline features on unity 2019.

Reason:
Timeline API has changed since Unity 2018, now being a separate Unity package with some changes in interfaces / classes which prevents quick adaptation.
namespaces changed, e.g. ITimelineClipAsset no longer exists, etc.

**Comment by MichalBerlinger** [comment]
@HaraldCsaszar Hi just tried it, and after adding SpineAnimationStateTrack to Timeline I am getting this warning: "No script asset for SpineAnimationStateTrack. Check that the definition is in a file of the same name and that it compiles properly." And the script and track can't load. I have the latest version of Unity, latest Spine runtime and Timeline package support downloaded.

**Comment by MichalBerlinger** [comment]
Ok, so deleting the Library folder and reimporting the whole project fixed the issue for me. Thanks for the fix!

**Comment by HaraldCsaszar** [comment]
@Abuki Thanks for the info. This is indeed strange, under some circumstances it seems to be necessary to select the Spine folder and hit `Reimport` in order to build the Timeline script files again.

I will reopen the ticket in order to fix this additional issue.

**Comment by HaraldCsaszar** [comment]
Now triggering recompilation of the Timeline scripts automatically, so that no manual `Timeline -> Reimport` action is necessary.

**Comment by zfh2773333333** [comment]
I want to know, now, the2019.3f is support in spine?

**Comment by HaraldCsaszar** [comment]
@zfh2773333333 Yes, Unity 2019.3 is supported.
