### ISSUE TITLE
[cpp] compile error when min or max macros defined before mathutil.h

### ISSUE THREAD

**Issue by mikedmc** [EsotericSoftware/spine-runtimes#1338]
The following error is shown if min and max macros are already defined (see WinTypes.h) before spine/mathutil.h

 error C2226: syntax error : unexpected type 'T' 

fix: #undef min and max macros, define them again after finished including spine/mathutil.h

**Comment by badlogic** [comment]
Undefining `min`/`max` and redefining it after the class declaration of `MathUtils` in `MathUtils.h` is something we can't do. The undefine is not the problem the definition is. I can not assume what `min`/`max` defined in another header do in general. This must be resolved in the user code I'm afraid.
