### ISSUE TITLE
Clipping masks don't work in spine-ts

### ISSUE THREAD

**Issue by liana-p** [EsotericSoftware/spine-runtimes#1343]
Clipping masks don't seem to work in the current version of spine-ts (canvas).

The element appears unclipped when rendered.

Is this feature supposed to be implemented in spine-ts, or is there a bug?

**Comment by badlogic** [comment]
Sorry, we should communicate this better. The spine-ts canvas runtime can't technically support clipping, as that relies on mesh rendering. The canvas API doesn't have a production ready way to support this mechanism. As such, it is limited to rendering rectangular images only, which also means that clipping can not be support. I'll update the README.md accordingly.

**Comment by badlogic** [comment]
Ah, looks like it is documented. Quoting from the README, section `Spine version`:

*spine-ts Canvas does not support color tinting, mesh attachments and clipping. Only the alpha channel from tint colors is applied. Experimental support for mesh attachments can be enabled by setting `spine.canvas.SkeletonRenderer.useTriangleRendering` to true. Note that this method is slow and may lead to artifacts on some browsers.*
