### ISSUE TITLE
threejs version of spine-ts causes errors on every frame

### ISSUE THREAD

**Issue by liana-p** [EsotericSoftware/spine-runtimes#1345]
When I try to play an animation with three.js (using the example code to setup three.js and the skeleton mesh), I get this error `THREE.WebGLObjects.updateBuffer: dynamic THREE.BufferAttribute marked as needsUpdate but updateRange.count is 0, ensure you are using set methods or updating manually.` on every frame.

I've tried using specifically three.js 79 (the same as in the example, but I still get this error and not sure what could be causing it).

**Comment by badlogic** [comment]
Does this happen with our example three.js as well? If not, can you share your code and assets?

**Comment by liana-p** [comment]
I found the issue on my side, the skeleton didn't have a skin active. I had previous code in canvas that was setting the skin in the skeleton, but this code was now wrong because the SkeletonMesh creates its own skeleton.

Apparently, when a spine anim has no skin active and thus no attachments to display, it ends up causing this error

**Comment by badlogic** [comment]
Thank you for the information. I consider this a bug. I'll fix it asap!

**Comment by badlogic** [comment]
Thanks for reporting, this has been fixed in the 3.8-beta branch.
