### ISSUE TITLE
[runtimes] Port bone/constraint association with skins

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1346]
Commits:

https://github.com/EsotericSoftware/spine-runtimes/commit/6205e51752df9be7000cb479560c8ffd7b5b76eb
https://github.com/EsotericSoftware/spine-runtimes/commit/9d41645b57f8e78b01e5bede8702da71a0b68ec6
https://github.com/EsotericSoftware/spine-runtimes/commit/f0533b6093b1004d1fb9e23f325a9a7faab73369
https://github.com/EsotericSoftware/spine-runtimes/commit/705195c34855e795acd3dde6f022065eafa314e3
https://github.com/EsotericSoftware/spine-runtimes/commit/b98469ec890e58192e74d0b83f2c79dd2c6695a4

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua 
- [x] spine-love
- [x] spine-corona

**Comment by HaraldCsaszar** [comment]
[csharp] [Port of more skin API changes, commits: 659c390, 7ee57dc, b3c2170, b71970a, 42c1c4a, 70cdf2d. See](https://github.com/EsotericSoftware/spine-runtimes/commit/1d0cce37075a5a9aa02813d088890ed77901536a)

Note: commit message referenced wrong ticket, 841 instead of this one.
