### ISSUE TITLE
IMPLEMENT_MODULE() type change for UE4 runtime

### ISSUE THREAD

**Issue by antidamage** [EsotericSoftware/spine-runtimes#1349]
In Unreal Engine 4.22 the interface type ISpineEditorPlugin needs to be renamed SpineEditorPlugin.

This is a weird change to the IMPLEMENT_MODULE() functionality, but won't build without it. Uncertain if this is a breaking change for older version of UE but I suspect they'll be fine.

**Comment by badlogic** [comment]
I've fixed this a few days ago, see https://github.com/EsotericSoftware/spine-runtimes/blob/3.7/spine-ue4/Plugins/SpinePlugin/Source/SpinePlugin/Private/SpinePlugin.cpp#L40 (also in the 3.8-beta branch).

Are you still running into issues despite that? I've tested this change down to 4.20.
