### ISSUE TITLE
[lua] IK bones are not working properly

### ISSUE THREAD

**Issue by depilz** [EsotericSoftware/spine-runtimes#1356]
I'm working with the last version of the branch 3.7, I thought the previous fix for another IK issue may fix this one too, but it doesn't.

I just added my Spine animation with no changes to my Corona game, and this is the result:
<img width="108" alt="image" src="https://user-images.githubusercontent.com/5722355/57871477-66548580-77d7-11e9-82bb-40d9cabc114e.png">

Of course, the expected result was this: 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/5722355/57871520-8126fa00-77d7-11e9-95a6-f59a7dac1a4b.png">

I could fix my issue by flipping the IK bone and both arms vertically and making some adjustments on the rotation.

Sorry if I explain it badly.

**Comment by badlogic** [comment]
Could you share your assets with me? You can send them to contact@esotericsoftware
com.

**Comment by depilz** [comment]
I sent my assets and the spine setup to contact@esotericsoftware.com

**Comment by depilz** [comment]
I can "fix" the issue on the pistol animation by applying this lines after each spine enterFrame update
```
  self._skeleton:findBone("aimBoneRightHand").scaleY   = -1
  self._skeleton:findBone("aimBoneLeftHand").scaleY    = -1
  self._skeleton:findBone("bone14").scaleY             = -1
  self._skeleton:findBone("bone17").scaleY             = 1
  self._skeleton:findBone("aimBoneRightHand").rotation = 205
  self._skeleton:findBone("aimBoneLeftHand").rotation  = 290
  self._skeleton:findBone("aimBoneLeftHand").x         = 2
  self._skeleton:findBone("aimBoneLeftHand").y         = -3

  self._skeleton:updateWorldTransform()
```

**Comment by badlogic** [comment]
I tested your assets with the latest `spine-lua` and `spine-corona` runtimes from the 3.7 and 3.8-beta branches of this repository. I get the following:

![https://marioslab.io/uploads/screenshots/GALIxAXNlq.png](https://marioslab.io/uploads/screenshots/GALIxAXNlq.png)

Which appears correct. The code I used was this:

```
require("mobdebug").start()

local spine = require "spine-corona.spine"

function loadSkeleton(atlasFile, jsonFile, x, y, scale, animation, skin)
	-- to load an atlas, we need to define a function that returns
	-- a Corona paint object. This allows you to resolve images
	-- however you see fit
	local imageLoader = function (path)
		local paint = { type = "image", filename = "data/" .. path }
		return paint
	end

	-- load the atlas
	local atlas = spine.TextureAtlas.new(spine.utils.readFile("data/" .. atlasFile), imageLoader)

	-- load the JSON and create a Skeleton from it
	local json = spine.SkeletonJson.new(spine.AtlasAttachmentLoader.new(atlas))
	json.scale = scale
	local skeletonData = json:readSkeletonDataFile("data/" .. jsonFile)
	local skeleton = spine.Skeleton.new(skeletonData)
	skeleton.scaleY = -1 -- Corona's coordinate system has its y-axis point downwards
	skeleton.group.x = x
	skeleton.group.y = y

	-- Set the skin if we got one
	if skin then skeleton:setSkin(skin) end

	-- create an animation state object to apply animations to the skeleton
	local animationStateData = spine.AnimationStateData.new(skeletonData)
	animationStateData.defaultMix = 0.5
	local animationState = spine.AnimationState.new(animationStateData)

	-- set a name on the group of the skeleton so we can find it during debugging
	skeleton.group.name = jsonFile

	-- set some event callbacks
	animationState.onStart = function (entry)
		print(entry.trackIndex.." start: "..entry.animation.name)
	end
	animationState.onInterrupt = function (entry)
		print(entry.trackIndex.." interrupt: "..entry.animation.name)
	end
	animationState.onEnd = function (entry)
		print(entry.trackIndex.." end: "..entry.animation.name)
	end
	animationState.onComplete = function (entry)
		print(entry.trackIndex.." complete: "..entry.animation.name)
	end
	animationState.onDispose = function (entry)
		print(entry.trackIndex.." dispose: "..entry.animation.name)
	end
	animationState.onEvent = function (entry, event)
		print(entry.trackIndex.." event: "..entry.animation.name..", "..event.data.name..", "..event.intValue..", "..event.floatValue..", '"..(event.stringValue or "").."'" .. ", " .. event.volume .. ", " .. event.balance)
	end

	-- return the skeleton an animation state
	return { skeleton = skeleton, state = animationState }
end

local lastTime = 0
local result = loadSkeleton("David.atlas", "David.json", 240, 300, 0.4, "IdlePistol", "David")
local skeleton = result.skeleton;
local state = result.state;

state:setAnimationByName(0, "IdlePistol", true)

display.setDefault("background", 0.2, 0.2, 0.2, 1)

Runtime:addEventListener("enterFrame", function (event)
	local currentTime = event.time / 1000
	local delta = currentTime - lastTime
	lastTime = currentTime

	state:update(delta)
	state:apply(skeleton)
	skeleton:updateWorldTransform()
end)
```

Could you try updating your local copy of `spine-corona` and `spine-lua`? Please also make sure you use the correct Spine editor version to export your assets (so 3.7 or 3.8-beta respectively).

**Comment by depilz** [comment]
Can you try your code with the idleAssault animation, please?

I'm using your code and the idlePistol animation and all the one-handed weapons are working good, but I still having the issues with the two-handed weapons.

The idlePistol was giving me issues because I had code involved to fix the idleAssault, my bad, but running only your code the two-handed weapons are not working properly

**Comment by badlogic** [comment]
@depilz I'll have a look!

**Comment by badlogic** [comment]
@depilz sorry for taking so long. I've tried to reproduce the issues you were reporting. Here's what I see with my above test code, the `IdleAssault` animation, and the assets you sent me via email.

![https://marioslab.io/uploads/screenshots/k3uzp8J3d8.png](https://marioslab.io/uploads/screenshots/k3uzp8J3d8.png)

This is what it is supposed to look like based on what I see when I open your Spine project in the Spine Editor.

**Comment by depilz** [comment]
Awesome! It's fixed. Thanks :)

**Comment by depilz** [comment]
I've another question, when I go from IdlePistol to IdleToFire, the first time it plays slower than it should then it plays normal. I guess this is another issue or am I doing something wrong?

I just added this lines to your code:
```
state:setAnimationByName(0, "IdlePistol", true) -- currently in your code
timer.performWithDelay(2200, function()            -- Loop IdleToFire
  state:setAnimationByName(0, "IdleToFire", true)
end)
```

The result
![ezgif-5-3c6fe0272732](https://user-images.githubusercontent.com/5722355/58574058-1d57f480-820d-11e9-9334-a1bcfa40e041.gif)

**Comment by badlogic** [comment]
That's a side effect of the `defaultMix` set in line 31. It governs for how long two animations are mixed with each other when going from one to the other, in this case `IdlePistol` to `IdleToFire`. In my code, it's set to `0.5` seconds, which is longer than the `IdleToFire` animation time itself. That's why you see a prolonged mix between those two, while mixing between the same `IdleToFire` animation is shorter. Set the `defaultMix` to something like `0.1` and things line up properly.

**Comment by depilz** [comment]
Great! Thanks a lot! :)
