### ISSUE TITLE
Integrate cocos2d-objc into our existing project (iOS | Swift)

### ISSUE THREAD

**Issue by riyanpratamap** [EsotericSoftware/spine-runtimes#1362]
Hi @badlogic , so sorry I have a question regarding how to integrate **cocos2d-objc** in our existing project. I still have a problem integrating spine in my current project. I tried to add the sources from `spine-c/spine-c/src/spine` and `spine-cocos2d-objc/src/spine` to your project, but still produce lexical or preprocessor issue.

I have follow your instruction to run it on my emulator [here](https://github.com/EsotericSoftware/spine-runtimes/tree/3.7/spine-cocos2d-objc#ios) but i got few error. 

```
/Spine/spine-runtimes-3-2.7/spine-cocos2d-objc/cocos2d/cocos2d/CCRendererBasicTypes.m:62:12: 
error: expected method to read dictionary element not found on object of type 'id<NSCopying>'
        id src = (options[CCBlendFuncSrcColor] ?: @(GL_ONE));
```

From other [runtimes](http://esotericsoftware.com/spine-runtimes) out there, I think the only one that support one file image asset in `.png` is **cocos2d-objc**. So i'll try to implement this library.

I found your answer in [#1106 ](https://github.com/EsotericSoftware/spine-runtimes/issues/1106), but actually you are referring into **cocos2dx** installation for C++. Do you have any clue for me? Thank you.

**Comment by badlogic** [comment]
The problem is sadly in cocos2d-objc, and not in spine-cocos2d-objc, see https://github.com/cocos2d/cocos2d-objc/issues/1394

You can fix this by changing line 56 in `CCRendererBasicTypes.m` to:

```
-(id)objectForKey:(id)options
```
