### ISSUE TITLE
Cound I still find 3.3.05 version runtime somewhere?

### ISSUE THREAD

**Issue by re5e** [EsotericSoftware/spine-runtimes#1367]
I'd like to downgrade my Spine Unity runtime to 3.3.05, because a previous artist uses this version to create skeleton body without keeping .json file but only .skel files. I try to switch tags 3.3.05 but seems theres no exist.

Or is there anyway to convert a 3.3.05 version skel binary files to .json file to solve this situation? Many thanks!

**Comment by re5e** [comment]
I'd like to downgrade my Spine Unity runtime to 3.3.05, because a previous artist uses this version to create skeleton body without keeping .json file but only .skel files. I try to switch tags 3.3.05 but seems theres no exist.

Or is there anyway to convert a 3.3.05 version skel binary files to .json file to solve this situation? Many thanks!

**Comment by badlogic** [comment]
We only started tagging release in version 3.5. Going by the Spine editor changelog, 3.3.05 was released in June 2016. I would strongly recommend not using this version. If you must, the commits here should work: https://github.com/EsotericSoftware/spine-runtimes/commits/3.7?after=83b38d24b358dd95ec17d4df6363a70186d283b5+2900

As for converting a `.skel` file, that should be possible. Open the Spine editor in the latest version, click on "Spine", then click on "Import data". You can now select your `.skel` file and it will be converted to the latest Spine version, allowing you to save the project and export it to new `.json`or `.skel` files.
