### ISSUE TITLE
[unity] Totally stucks on Atlas Assets size change

### ISSUE THREAD

**Issue by theshock** [EsotericSoftware/spine-runtimes#1369]
Unity: `2018.3` or `2019.2`
Spine Runtime: `3.7` or `3.8-beta` (but works correctly in `3.6`)
On `Windows 10` and `Mac 10.14`

## Steps to Reproduce: 
1. Create new unity project
2. Import `spine-unity-3_7-2019-05-28` or `spine-unity-3_8-2019-05-28-beta`
3. Go to `Spine Examples/Spine Skeletons/spineboy-unity` in Unity Editor
4. Open `spineboy-unity_SkeletonData.asset`
5. Change `Atlas Assets` `Size` to another value and press `Enter`

## Result:
Unity stucks forever and should be killed through process manager

![UnitySpineStuck](https://user-images.githubusercontent.com/337677/58797349-79a18680-8608-11e9-81ad-74de206c1a4a.png)

**Comment by HaraldCsaszar** [comment]
Thanks for the bug report. It is tracked under this issue ticket:
https://github.com/EsotericSoftware/spine-runtimes/issues/1371
and has now been fixed.

Please download the latest unitypackages from here as usual:
http://esotericsoftware.com/spine-unity-download
