### ISSUE TITLE
[runtimes] Snapping/dipping on track 1

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1380]
As reported via email:
FMfcgxwCgzCBxHQXMGfDkpmgPhVKjVKg

Reproduction assets:
In email conversation above, 6th message from top (text "Here are the three components you requested."), 6 attached assets.

Repro steps:
Video description can be found in attached video "Spine - _Soldier_Final 6_10_2019 4_26_00 PM.mp4" in conversation, 8th message, (at message "I just changed the animation to now work on the same track as all of the other animations, _track1. [..]"). Not the video in 4th message.

**Comment by NathanSweet** [comment]
Solutions and explanation for why this happens here:
http://esotericsoftware.com/forum/Snapping-Issue-12047?p=54194#p54194
