### ISSUE TITLE
[ts] Modularize and publish to NPM

### ISSUE THREAD

**Issue by linonetwo** [EsotericSoftware/spine-runtimes#1381]
It will be much easier to manage project if all dependencies are in node_modules!

**Comment by linonetwo** [comment]
Can I generate it and release it as `@linonetwo/spine-ts-three` so I can install it via npm? Will there be any legal problem?

**Comment by badlogic** [comment]
Please do not publish the Spine runtimes to NPM. We have a package.json in the root of the repository which should allow you to build the artifacts you need. We have no intention of pushing spine-ts to NPM.

**Comment by linonetwo** [comment]
But I hope dependencies are managed by package.json and node_modules. This allows convenient version control and keeps codebase neat.

**Comment by linonetwo** [comment]
What's the reason not publishing packages to npm? Is the publishing pipeline inconvenient?

**Comment by cjke** [comment]
~Although its not identical, this will solves most use cases: `npm install EsotericSoftware/spine-runtimes` (you can install from github directly as long as it has a package.json).~ Disregard - that won't work as they aren't setup as proper modules...

A proper NPM release would be much better though, its extremely rare not to have a library/framework on NPM. Especially when you start to factor in build pipelines, etc

**Comment by badlogic** [comment]
It's happening

**Comment by NathanSweet** [comment]
It happened! http://esotericsoftware.com/blog/Spine-goes-NPM
