### ISSUE TITLE
[csharp] Y flipped in C# runtime and bone "Y down" setting is not used anywhere

### ISSUE THREAD

**Issue by aienabled** [EsotericSoftware/spine-runtimes#1386]
Hello!

I've noticed that after updating to latest C# Spine runtime version that the skeleton rendering is upside-down.

It seems the property ```static public bool yDown;``` ([source line](https://github.com/EsotericSoftware/spine-runtimes/blob/79fea3722ba59cd1bb1a6aef42138e0c3a193086/spine-csharp/src/Bone.cs#L42))
is never used in C# version unlike C++ version where it's used to properly flip the Y scale in getter ([source line](https://github.com/EsotericSoftware/spine-runtimes/blob/67f469b06d1f2ce97b43ad93c40df73c3b9c94f4/spine-cpp/spine-cpp/src/spine/Skeleton.cpp#L531)).

However, the change of the C# getter is not sufficient (as it's not actually used in code—the field `scaleY` is used instead). The Bone code requires further modifications to properly take into account the value of `yDown` static field. I've experimented with it and it seems it works properly if I change the setter (so the value is flipped when it's assigned to the `ScaleY` property) but I suppose this is not the best way to modify this.

Regards!

**Comment by badlogic** [comment]
Cheers, this should be fixed in the 3.8-beta branch!
