### ISSUE TITLE
[cpp] atlas unicode support

### ISSUE THREAD

**Issue by mikedmc** [EsotericSoftware/spine-runtimes#1390]
Can't load atlas and PNG files when game is installed in folders with Chinese characters.

The problem is that the Atlas constructors ask for the path in CHAR and then they send it over to our custom texture loader AFTER doing some text processing on it and converting it to your own String(char), acting like a proxy. Could you maybe just send the image names (no path, or relative path) to the custom texture loader (in plain char)? We'll make sure we convert it and concatenate it with the resources "root" folder? We'll initialize the custom texture loader properly.
Or even better, you could pass the path of the atlas file to the texture loader along with each image name (relative to the atlas file) and let us do the text processing to compose the full image path?

**Comment by badlogic** [comment]
I've tested this using spine-sfml-cpp on the 3.8-beta branch on macOS. The processing `Atlas` performs does not interfere with multi-byte UTF-8 sequences.

Please provide a runnable example that reproduces the issue.
