### ISSUE TITLE
[ue4] Can't compile UE4 project with latest 3.8 beta

### ISSUE THREAD

**Issue by raxi2012** [EsotericSoftware/spine-runtimes#1391]
Hi, can't build UE4 project with latest spine-runtimes beta version

![1](https://user-images.githubusercontent.com/17443915/59964706-74976f00-9504-11e9-86c3-a7fb723ec308.png)
![2](https://user-images.githubusercontent.com/17443915/59964707-74976f00-9504-11e9-958c-bcf05c2b13b1.png)
![3](https://user-images.githubusercontent.com/17443915/59964708-74976f00-9504-11e9-8223-00d4a0e49b43.png)

With debug
![4](https://user-images.githubusercontent.com/17443915/59964806-e02e0c00-9505-11e9-89ea-31ce58f04b96.png)
![5](https://user-images.githubusercontent.com/17443915/59964807-e0c6a280-9505-11e9-9d6c-d973a591df61.png)

Latest compilable version here -> [firefox send service](https://send.firefox.com/download/eed5acc2b7566f8c/#yALoNQs39TK0DGvPczisYQ), but UE crashes when I import binaries from latest beta version of Spine.

**Comment by badlogic** [comment]
Please note that the binary and json file formats have changed int he latest 3.8-beta version. You have to re-export your Spine projects. Please also make sure you copy the latest `spine-cpp` code to your Spine UE4 plugin copy.

I'm afraid your screenshots do not show the compilation errors. I'm not sure where UE4 puts the compilation logs on Linux. I'll need the compiler errors, not the errors from the build tools.

Please also try to compile the latest spine-ue4 example project from this repositories 3.8-beta branch (with the `spine-cpp` runtime from the same commit). If that works for you, then it's likely that your project setup has a problem.

**Comment by raxi2012** [comment]
This happens when I try to open a spine-ue4 (3.8 beta latest from git) project. (UE 4.22.3)
![6](https://user-images.githubusercontent.com/17443915/59982415-5b7ce400-9612-11e9-9996-40a5c88b366d.png)
![7](https://user-images.githubusercontent.com/17443915/59982708-9d0f8e00-9616-11e9-95be-a43cf46abcd8.png)

**Comment by badlogic** [comment]
Thank you for the additional data! It appears that UE4 uses stricter compiler flags on Linux. I will fix up the beta branch accordingly.

**Comment by badlogic** [comment]
This has been fixed in the 3.8-beta branch, specifically the spine-cpp runtime. Thanks for reporting!
