### ISSUE TITLE
[love2d] Vertex color scale has changed in (at least) 11.2, maybe earlier

### ISSUE THREAD

**Issue by drhayes** [EsotericSoftware/spine-runtimes#1392]
I'm working on a game in love2d.

I've been using your excellent product and recently was animating slot colors. The animated color changes were not showing up in my game.

Turns out this series of lines from [here](https://github.com/EsotericSoftware/spine-runtimes/blob/57992b6cdf01c40c08e8759341f7e940e95ce89b/spine-love/spine-love/spine.lua#L204) to [here](https://github.com/EsotericSoftware/spine-runtimes/blob/57992b6cdf01c40c08e8759341f7e940e95ce89b/spine-love/spine-love/spine.lua#L242) that multiply the color values by `255` are incorrect now. Once I removed the `* 255` from each line my color values changed as expected.

I'm by no means an expert in this, but I think this changed in version 11 of love2d: https://love2d.org/wiki/11.0

**Comment by badlogic** [comment]
Thanks for reporting! This is fixed in the 3.8-beta branch.
