### ISSUE TITLE
[unity] Changing a SkeletonAnimation non-looping animation to looping doesn't work

### ISSUE THREAD

**Issue by marcusalanen** [EsotericSoftware/spine-runtimes#1396]
For a SkeletonAnimation s, writing

s.loop = false;
s.AnimationName = "myAnimation";
s.loop = true;
s.AnimationName = "myAnimation";

doesn't result in a looping animation, since the AnimationName property just checks "if (_animationName == value)".

Of course the above code is not the problem; our real code first set the non-looping animation, and completely elsewhere wanted a looping animation of the same name.

**Comment by HaraldCsaszar** [comment]
Thanks for reporting. Issue is resolved and new unitypackages are available for download.
