### ISSUE TITLE
[unity] Support for moving/renaming sprite texture files (destructive reimport)

### ISSUE THREAD

**Issue by leonidumanskiy** [EsotericSoftware/spine-runtimes#1397]
If sprite texture file is renamed or moved to another directory, next re-import will destroy asset material and leave atlas asset in the broken state, even if nothing changed (i.e. project is being imported first time).

**Comment by leonidumanskiy** [comment]
Side notes:

This breaks different workflows. 
For example, one would want to move textures to use Unity built-in asset bundle variants:

_character_skeleton.assetbundle_:
```
/character/character_Atlas.asset
/character/character_Material.mat
/character/...
```

_character_textures.assetbundle.HD_:
```
/character_textures/hd/character.png
```

_character_textures.assetbundle.LD_:
```
/character_textures/ld/character.png

```
_character_textures.assetbundle.SD_:
```
/character_textures/sd/character.png
```

**Comment by HaraldCsaszar** [comment]
Thanks for reporting and sorry for the long delay! This has finally been fixed.
