### ISSUE TITLE
[unity] Whitespace stripping - wrong region after GetRepackedSkin in 3.7

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1399]
As reported on the forum:
http://esotericsoftware.com/forum/Texture-UV-wrong-after-using-AtlasUtilities-GetRepackedSkin-12201

Repro Unity project was uploaded in the above forum posting.

**Comment by Eyesiah** [comment]
Hello! After updating to Spine 3.8 I now have noticed that I get artifacts in the repacked skin if the spine project is exported with "rotation" set to true. So I now have to turn that off also.

**Comment by HaraldCsaszar** [comment]
Thanks for the info Eyesiah, very much appreciated.

**Comment by HaraldCsaszar** [comment]
@Eyesiah the rotation issue has just been fixed, see this issue ticket here:
https://github.com/EsotericSoftware/spine-runtimes/issues/1452

**Comment by Eyesiah** [comment]
Great, thanks for letting me know Harald! May I ask what the status of this issue is?

**Comment by HaraldCsaszar** [comment]
Unfortunately this issue it is not yet fixed, it was just revisited for quick testing whether other changes had any effect on it's status.

**Comment by HaraldCsaszar** [comment]
@Eyesiah A bugfix for this issue has now been released for the 3.8 and 3.9-beta branches.

**Comment by Eyesiah** [comment]
Fantastic, thanks!
