### ISSUE TITLE
[ue4] Crash occurs when the Atlas and SkeletonData do not match in the SpineWidget

### ISSUE THREAD

**Issue by panojune** [EsotericSoftware/spine-runtimes#1403]
I'm testing a SpineWidget with 3.8beta, Crash occurs when the Atlas and SkeletonData do not match in the SpineWidget. This is a mistake that can happen often, so I think it will need some improvement.
Thanks.

**Comment by badlogic** [comment]
Could you let me know what Unity version you are using?

**Comment by panojune** [comment]
> Could you let me know what Unity version you are using?

Yes, I'm using UE_4.21. No Unity.

**Comment by badlogic** [comment]
I've tested this using the latest 3.8-beta code. I get this if the assets don't match (e.g. spineboy data and raptor atlas):

![https://marioslab.io/uploads/screenshots/UE4Editor_KKNQ7dlHmn.png](https://marioslab.io/uploads/screenshots/UE4Editor_KKNQ7dlHmn.png)

This is working as intended. Could you please show me an error log? I'll re-open if I can reproduce it.
