### ISSUE TITLE
[unity] Support 2D Lights of Unity 2019.2

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1413]
Support for 2D Lights and the 2D Renderer (as an alternative to ForwardRenderer) pipeline (currently experimental), can be downloaded as part of the Lightweight RP package as described in the following blog post by Unity staff:

https://forum.unity.com/threads/experimental-2d-lights-and-shader-graph-support-in-lwrp.683623/

Was requested here on the Forum:
http://esotericsoftware.com/forum/2D-Lighting-in-Unity-2019-2-12306

**Comment by HaraldCsaszar** [comment]
Was also requested here on the forum:
http://esotericsoftware.com/forum/Support-for-the-new-2D-renderer-12336

**Comment by FNGgames** [comment]
Any word on this? It's been 6 months

**Comment by HaraldCsaszar** [comment]
>Any word on this? It's been 6 months

The ticket was created 4 months and 3 days ago to be precise.
(6 months from the release of the experimental package by Unity, yes. However, we can and will never base our implementation on unstable APIs.)

Nevertheless, implementation is getting closer and closer.

**Comment by FNGgames** [comment]
Thanks Harald. Sorry to sound so entitled.

**Comment by zfh2773333333** [comment]
Please hurry up, I really need this feature now.......

**Comment by zfh2773333333** [comment]
I used the shdader graph, which can implement unity 2d lighting. I don't know if it is fully compatible with the runtime. I want to know if this method is feasible?

**Comment by zfh2773333333** [comment]
我使用了2D shdader graph, 可以实现spine的2d专属灯光, 不知道是否完全兼容spine运行库. 我想知道这个方法可行吗?我是中国人,  这是机器翻译...
I used a 2D shdader graph, which can implement spine's 2d exclusive lighting. I don't know if it is fully compatible with the spine runtime. I want to know if this method is feasible? I am Chinese, this is machine translation ...

**Comment by HaraldCsaszar** [comment]
@zfh2773333333 I fear I do not understand the message above.

Please note that the implementation of URP 2D Renderer support is in progress. If you cannot wait until its completion, use the shader `Universal Render Pipeline/2D/Sprite-Lit-Default` in the meantime and switch to the official Spine shaders later.

**Comment by zfh2773333333** [comment]
![1](https://user-images.githubusercontent.com/59042125/71180866-04e51f80-22ae-11ea-9cec-cd31839f6da5.png)
![2](https://user-images.githubusercontent.com/59042125/71180867-04e51f80-22ae-11ea-8135-3804ec750214.png)
![3](https://user-images.githubusercontent.com/59042125/71180869-04e51f80-22ae-11ea-84d2-94b86c9632e5.gif)
I mean, Is this method OK?

**Comment by zfh2773333333** [comment]
thank you!

**Comment by HaraldCsaszar** [comment]
Please note that there is now an experimental first UPM package available on the download page:
http://esotericsoftware.com/spine-unity-download
