### ISSUE TITLE
[threejs] New version of ThreeJS causes missing pieces.

### ISSUE THREAD

**Issue by Heleor** [EsotericSoftware/spine-runtimes#1415]
Hello,

I'm currently exploring using Spine for a ThreeJS project which is using a relatively new version (92).  When I integrated using the demo code, I noticed missing pieces in the mesh. Doing a binary search, I narrowed it down to the demo code (currently using ThreeJS 68) also not displaying properly with ThreeJS 92.

Example: https://imgur.com/a/CDvwZSO

Reproduction steps: Check out the demo application, replace three.min.js with newer version. 

Attached a copy just in case.
[three.min.zip](https://github.com/EsotericSoftware/spine-runtimes/files/3424463/three.min.zip)

**Comment by badlogic** [comment]
i've tried our 3.8-beta branch together with the three.min.zip you attached here, as well as the latest threejs release (106), served from cloud-flare. I'm afraid I can not reproduce your issue.

![](https://marioslab.io/uploads/screenshots/6A6Wg1GDl7.png)

Happy to re-open if you can provide a reproduction example for me!

**Comment by Heleor** [comment]
I used the spine.js and example code linked below, which is still using 68 on the live site.

http://esotericsoftware.com/files/runtimes/spine-threejs/example/index.html

I could not find the newest version of the pre-build spine.js file anywhere. I will try to rebuild from source.

**Comment by badlogic** [comment]
Ah, that would explain it! That demo is super old, I'll update. Prebuilt files can be found in this repository:

https://github.com/EsotericSoftware/spine-runtimes/tree/3.7/spine-ts/build
https://github.com/EsotericSoftware/spine-runtimes/tree/3.8-beta/spine-ts/build

Note that the 3.8 release is going to happen in a few days. It might make sense to use the 3.8-beta build.

Please also make sure the Spine Editor version matches the Spine Runtimes version. For more information see: http://esotericsoftware.com/forum/Spine-editor-and-runtime-version-management-6534

**Comment by Heleor** [comment]
So is it correct to assume that spine runtimes are incompatible with assets produced with a previous version of the editor?

With the latest version and example code I have something reasonable up and running: https://imgur.com/a/C25bIf7

Some other minor issues that I ran into (on my side, but are probably useful for new people trying to get this up and running):
* Adding the mesh without ever calling 'update' on it does not actually show it in the scene.
* The base path must have a '/' at the end. 'new spine.threejs.AssetManager('/static/spine/');'
* Using 3.8 beta caused a 'no such skin: default' error which went away when using 3.7. (?)
* If you have a rig that has skins and do not choose a skin, you get a baffling 'THREE.WebGLObjects.updateBuffer: dynamic THREE.BufferAttribute marked as needsUpdate but updateRange.count is 0, ensure you are using set methods or updating manually.' exception.
* Draw order is fixed for 'front view'. If you have view the image from behind, the draw order is inverted so you see outlines. (example: https://imgur.com/a/P9Icxoy)

If any of these should be new issues I can probably create a simple repro case for each, but each of these was just a few trivial pokes at the sample code.
