### ISSUE TITLE
[ue4] Apply multiple skins via blueprints

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1416]
Currently, the blueprint API exposed by the spine-ue4 runtime only allows setting a single skin on a skeleton. To set multiple skins, the blueprint API must expose:

1. Creation of a new empty skin
2. Methods to query existing skins (this is in)
3. The C++ `Skin::addSkin()` method

Blueprint users can then create a new empty skin, add the attachments from existing skins, and set the resulting skin on the skeleton.

The problem is largely memory and life-time management of the newly created skin. UE4's GC needs a UObject for tracking, but our `spine::Skin` obviously doesn't derrive from that. We need to wrap that `spine::Skin` in a `USpineSkin`, then retain a reference to that USpineSkin in the `USpineSkeletonComponent`. All bets are off if a user sets a skin from both the blueprint via a `USpineSkin` object, and in C++ via the standard `spine::Skin`.

**Comment by undead-ooze** [comment]
Hi, are there any updates on this? Our artist is using spine for animation and we have several attachments that need to be on at once depending on the skin, this would be very helpful!
