### ISSUE TITLE
[unity] Support RootMotion at SkeletonMecanim, SkeletonAnimation and SkeletonGraphic

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1417]
Edit: split off to separate issue ticket #1716: _Normalized Times reported on this forum thread:
http://esotericsoftware.com/forum/Request-SkeletonMecanim-Normalized-Time-Control-12327_

Root Motion requested on this forum thread:
http://esotericsoftware.com/forum/implement-root-motion-in-special-way-12347

**Comment by kvfreedom** [comment]
Will SkeletonAnimation support Rootmotion?

**Comment by kvfreedom** [comment]
Will SkeletonAnimation support RootMotion?

**Comment by HaraldCsaszar** [comment]
SkeletonAnimation will receive support for root motion as well, depending on whether the solution for SkeletonMecanim is transferrable and suitable for SkeletonAnimation or not.

In the meantime, you can try out Pharan's experimental root motion component for SkeletonAnimation here:
https://github.com/pharan/spine-unity-experimental/tree/spine-rootmotion/Assets/spine-unity-experimental

**Comment by HaraldCsaszar** [comment]
Consider this when implementing root motion support:
As reported by `bladdock` on the forum, Pharan's root motion script seems to have a bug in regards to interpreting Scale or Shear Timelines as Translate timelines, since they are subclasses of it:
http://esotericsoftware.com/forum/Unity-Root-Motion-Bug-13517

**Comment by forcepusher** [comment]
RootMotion support for SkeletonMecanim is a highly awaited feature for us. Is there a way to vote on tickets ?

**Comment by tabuto74** [comment]
Need it! Should we use the old script meanwhile?

**Comment by HaraldCsaszar** [comment]
@forcepusher: In short: there is no official upvoting on ticket priorities.

One the one hand we will prioritize what we think is the most important currently missing feature,
on the other, posting here or on the forum will give us a hint whether our priorities match yours. So posting can be seen as casting your vote.

**Comment by HaraldCsaszar** [comment]
One thing I forgot in this regard though: posting "when will it be done?" which requires answers from us typically takes time away from finishing the implementation of the features we are working on. So it will effectively make it happen later than without posting, so please consider the environment before posting :).

**Comment by HaraldCsaszar** [comment]
@tabuto74 You could adapt the old script in the meantime, there is nothing that speaks against it.

**Comment by HaraldCsaszar** [comment]
We can gladly announce that root motion support has arrived for `SkeletonAnimation`, `SkeletonMecanim` and `SkeletonGraphic`. Please see the changelog for details. A new 3.8 unitypackage is available for download: http://esotericsoftware.com/spine-unity-download.

Hope you like it!

**Comment by HaraldCsaszar** [comment]
Documentation pages have been updated:
http://esotericsoftware.com/spine-unity#Enabling-Root-Motion
http://esotericsoftware.com/spine-unity#SkeletonRootMotion.

Split `NormalizedTime` part of the issue ticket off to a separate issue:
https://github.com/EsotericSoftware/spine-runtimes/issues/1716
