### ISSUE TITLE
[ue4] spine-widget problem

### ISSUE THREAD

**Issue by GloryOfNight** [EsotericSoftware/spine-runtimes#1420]
Hi!

Is spine-widget work in Widget Blueprint? I created one and tried to use, but its not rendering anything. Also I dint find any nodes try to manage stuff in it. 
Thanks!

spine-runtimes from 3.7 branch.

**Comment by badlogic** [comment]
Yes, the widget is fully functional within widget blueprints. Please make sure you are using the 3.8-beta runtime, and not the runtime from the 3.7 branch. You can find docs here: http://esotericsoftware.com/spine-ue4#Spine-widget-for-UMG-UI

We've also created a quick video tutorial: http://esotericsoftware.com/blog/Spine-UE4-UI-Integration
