### ISSUE TITLE
[UE4] Crash : memcopy at SSpineWidget.cpp line:184 is memory overwrite when PLATFORM_USES_ES2 is true

### ISSUE THREAD

**Issue by NoahXia** [EsotericSoftware/spine-runtimes#1421]
SpinePlugin\Source\SpinePlugin\Private\SSpineWidget.cpp line:184 (branch : 3.8beta)
```
memcpy(indexData, Indices.GetData(), sizeof(uint32) * Indices.Num());
```

Engine\Source\Runtime\SlateCore\Public\Rendering\RenderingCommon.h
```
#define SLATE_USE_32BIT_INDICES !PLATFORM_USES_ES2

#if SLATE_USE_32BIT_INDICES
typedef uint32 SlateIndex;
#else
typedef uint16 SlateIndex;
#endif
```

when PLATFORM_USES_ES2 is true (Android, HTML5), SlateIndex is typedef as uint16, but the memcopy use sizeof(uint32)

**Comment by badlogic** [comment]
Thanks for reporting. This is fixed in the 3.8-beta branch.
