### ISSUE TITLE
[docs] API reference links to nonexistent 'addSkin' method

### ISSUE THREAD

**Issue by Heleor** [EsotericSoftware/spine-runtimes#1422]
Location: http://esotericsoftware.com/spine-runtime-skins

Code sample:
```
Skin newSkin = new Skin("new-skin"); // 1. Create a new empty skin
newSkin.addSkin(skeletonData.findSkin("shirt/pink"); // 2. Add items
newSkin.addSkin(skeletonData.findSkin("pants/green");
newSkin.addSkin(skeletonData.findSkin("shoes/sneakers");
```

Skin API documentation: http://esotericsoftware.com/spine-api-reference#Skin

(I am using the 3.7 runtime in Three.JS)

I'm not quite sure what the correct way to do multiskinning is today. The forum thread is slightly confusing: http://esotericsoftware.com/forum/Multiple-skins-approach-10930?p=49250#p49250

**Comment by Heleor** [comment]
I *think* the following code does what I'm trying to do:

```
function mergeSkin(target, source) {
    for (let i in source.attachments) {
        for (let j in source.attachments[i]) {
            target.addAttachment(i, j, source.attachments[i][j]);
        }
    }
}

Skin newSkin = new Skin("new-skin");
mergeSkin(newSkin,skeletonData.findSkin("shirt/pink"));
mergeSkin(newSkin,skeletonData.findSkin("shirt/green"));
mergeSkin(newSkin,skeletonData.findSkin("shirt/sneakers"));
```

**Comment by badlogic** [comment]
Terribly sorry, the docs have already been updated for the impeding 3.8 release, where we added new Skin APIs to make multi-skin work easier. For 3.7, your `mergeSkin` solution is correct. For 3.8, you can simply use `Skin.addSkin()`
