### ISSUE TITLE
Having trouble with skeleton.scaleX and skeleton.scaleY (spine-ts/core)

### ISSUE THREAD

**Issue by SupremeTechnopriest** [EsotericSoftware/spine-runtimes#1426]
Hello! 

I'm attempting to flip the skeleton on my server side spine implementation (spine-ts/core only).  I've had this working in pixi-spine before, but it doesnt seem to work in spine-ts. Here is a little block.

```javascript
const loader = new spine.SkeletonJson(new AttachmentLoader())
const json = readFileSync(spineData, 'utf8')
const skeletonData = loader.readSkeletonData(json)
const animationStateData = new spine.AnimationStateData(skeletonData)
const animationState = new spine.AnimationState(animationStateData)
const skeleton = new spine.Skeleton(skeletonData)
skeletonData.fps = 1000 / this.tickRate
skeleton.scaleY = -1
// console.log(skeleton, animationState)
```

I see scaleY being set to -1 on the skeleton, but it isnt actually flipping the bones.  Im calling update like this.

```javascript
animationState.apply(skeleton)
skeleton.updateWorldTransform()
animationState.update(time.delta)
```

I've checked the modes on the bones and they all look good to me... Im out of ideas.... HALP PLEASE :)

**Comment by badlogic** [comment]
What version of spine-ts are you using?

**Comment by SupremeTechnopriest** [comment]
Latest version. Recently grabbed it off github. I think I figured it out.  The offset positions on bones arent updated when scale is flipped.  I just multiply by -1  and it works out fine.  Thanks!
