### ISSUE TITLE
Are spine-ts willing to development under ts module import & export?

### ISSUE THREAD

**Issue by taoabc** [EsotericSoftware/spine-runtimes#1430]
spine-ts is use namespace now, which will cause global variable pollution.
Development under ts module will makes module's relationship more clear, and it's convenient when I use webpack.
By use webpack/browerify together, it can output umd module or es module. It will be flexible for developer to choose.
By the way, push artifacts to npm, use jsdeliver cdn, so great.

**Comment by badlogic** [comment]
I have looked into module support a while ago. I could not find a way to support both modules and non-module deployment. Do you have a suggestion how we could do that?

**Comment by taoabc** [comment]
> I have looked into module support a while ago. I could not find a way to support both modules and non-module deployment. Do you have a suggestion how we could do that?

Develop with es module, export from webpack, set target value 'umd', is non-module output. will support both modules and non-module deployment. I can build a demo, and when I done, show it here.
