### ISSUE TITLE
Skin API degradation in C# runtime for 3.8 release

### ISSUE THREAD

**Issue by aienabled** [EsotericSoftware/spine-runtimes#1433]
Hi guys,

due to changes in https://github.com/EsotericSoftware/spine-runtimes/issues/841 I've noticed that the C# skin API is not as convenient to use and C# API performance is degraded.
When previously we could simply iterate over all the attachments (`public Dictionary<SkinEntry, Attachment> Attachments `) now there is a non-generic `public OrderedDictionary Attachments` so in order to iterate over it we have to cast to SkinEntry manually or use awful `GetAttachments` method which is simply creating a new list instance and adding all the dictionary entries there. This is leading to a lot of unnecessary allocations and GC load...

Please consider writing your own implementation for generic version of `OrderedDictionary` or using an open-source alternatives. Usage of non-generic collection in that particular case is pushing us back to ages of C# 1.0 in terms of performance and API usability.

Regards!

**Comment by HaraldCsaszar** [comment]
Hi aienabled,
Thanks for the issue report, you are absolutely right. We are going to replace the OrderedDictionary with a generic one.
Cheers!
