### ISSUE TITLE
[iOS] File asset not found

### ISSUE THREAD

**Issue by riyanpratamap** [EsotericSoftware/spine-runtimes#1434]
Hi, i am using asset that come from server. I locate the downloaded asset at default sandbox folder, and try to use it when initiate the `CCScene` but i got error that the asset cannot be found.

```
- (id)initWithSkeletonFile:(NSString *)skeleton andAtlas:(NSString *)atlas scale:(double)scale {
    self = [super init];
    if (!self) return nil;
    
    skeletonNode = [SkeletonAnimation skeletonWithFile:skeleton atlasFile:atlas scale:scale];
    
    CGSize windowSize = [[CCDirector sharedDirector] viewSize];
    [skeletonNode setPosition:ccp(windowSize.width / 2, 24)];
    [self addChild:skeletonNode];
    
    self.userInteractionEnabled = YES;
    self.contentSize = windowSize;
    
    return self;
}
```

I checked my sandbox folder, and the files already there. Is there any ideas? Thank you.

**Comment by badlogic** [comment]
spine-cocos2d-objc uses this method from cocos2d to read files:

https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-cocos2d-objc/src/spine/spine-cocos2d-objc.m#L46

Your code should work. Maybe the paths you supply are incorrect. In any case, this is not an issue with the Spine runtime from what I can tell.
