### ISSUE TITLE
[ue4] Masses of errors, as always

### ISSUE THREAD

**Issue by antidamage** [EsotericSoftware/spine-runtimes#1438]
I don't mean to sound ungrateful but can whoever is maintaining the UE4 build start testing their code please? In the last two years I've managed to get a checkout without bugs exactly once. Some of these bugs are from 3.7. We can do better. I'm not great with pull requests but I'll try to fix some of these.

    SpinePlugin\Private\SpineSkeletonDataAsset.cpp(235): warning C4458: declaration of 'skeletonData' hides class member
      SpinePlugin\Public\SpineSkeletonDataAsset.h(95): note: see declaration of 'USpineSkeletonDataAsset::skeletonData'
    SpinePlugin\Private\SpineSkeletonRendererComponent.cpp(221): error C2039: 'isActive': is not a member of 'spine::Bone'
      SpinePlugin\Public\spine-cpp\include\spine/TransformConstraint.h(41): note: see declaration of 'spine::Bone'
    SpinePlugin\Private\SSpineWidget.cpp(243): error C2039: 'isActive': is not a member of 'spine::Bone'
      SpinePlugin\Public\spine-cpp\include\spine/TransformConstraint.h(41): note: see declaration of 'spine::Bone'
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(38): error C2653: 'ConstraintData': is not a class or namespace name
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(38): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(38): error C2550: 'ConstraintData': constructor initializer lists are only allowed on constructor definitions
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(39): error C4508: 'ConstraintData': function should return a value; 'void' return type assumed
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(41): error C2653: 'ConstraintData': is not a class or namespace name
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(41): error C2523: '<Unknown>::~ConstraintData': destructor tag mismatch
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(41): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(42): error C4508: 'ConstraintData': function should return a value; 'void' return type assumed
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(44): error C2653: 'ConstraintData': is not a class or namespace name
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(45): error C2065: '_name': undeclared identifier
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(48): error C2653: 'ConstraintData': is not a class or namespace name
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(49): error C2065: '_order': undeclared identifier
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(52): error C2653: 'ConstraintData': is not a class or namespace name
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(53): error C2065: '_order': undeclared identifier
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(56): error C2653: 'ConstraintData': is not a class or namespace name
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(57): error C2065: '_skinRequired': undeclared identifier
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(60): error C2653: 'ConstraintData': is not a class or namespace name
    SpinePlugin\Public\spine-cpp\src\spine\ConstraintData.cpp(61): error C2065: '_skinRequired': undeclared identifier

**Comment by badlogic** [comment]
I have a clean checkout of the 3.8 branch and the 3.9-beta branch. I copied the latest `spine-cpp` over to the plugin dir of the example project. There are neither errors nor warnings when building the project in Visual Studio 2017.

Please tell me what your setup is, what branch you use, etc.

Looking at your error log, it appears you are using the 3.8(-beta) branch of the spine-ue4 runtime, and either an old spine-cpp from the 3.8(-beta) branch, or spine-cpp from the 3.7 branch. These do not go together.

**Comment by antidamage** [comment]
Excellent, I'll try mixing in the 3.9-beta spine-cpp, thanks.

I'm using the 3.8 branch alternately with the spine-cpp file that was already in the ue4 plugin, or with the spine-cpp in the main tree. Each spine-cpp folder has its own set of errors, include requirements not met, functions used but not defined, etc. The folder from the main tree had slightly less issues.

I am _not_ running the 3.8-beta or an old cpp folder. 100% positive. (Edit: I'm not positive at all...)

**Comment by badlogic** [comment]
Please don't mix things like that. If you use the 3.8 branch, get the files for both spine-cpp and spine-ue4 from there. Don't use left over files from days past and old branches. Don't mix in files from a different branch. All files must come from the same branch and commit. Nothing else is guaranteed to work together.

**Comment by antidamage** [comment]
Wasn't that what you just suggested I do? 3.8 does not function in its current state.

I know what happened in the first case. I had copied the 3.8-beta spine-cpp folder into the UE4 plugin folder before copying it out originally. Even with a hard reset and a clean it didn't remove it, so it persisted when I changed branches and updated and I thought it came with the new branch. So in the first instance it was the 3.8-beta spine-cpp folder.

However, as I mentioned I tried the root spine-cpp folder from the 3.8 branch in pristine condition and it's also a mess. This is the one I started trying to fix last night. Mostly it was a hodge-podge of includes not working. If the 3.9-beta spine-cpp is working without issue then it should be noted somewhere. Either that or backport it to 3.8 as the current release.

**Comment by badlogic** [comment]
My point is that 3.8 works in it's current state. The same is true for 3.9-beta branch. I'm trying to understand why your setup fails to compile.

**Comment by antidamage** [comment]
It looks like I'm just a retard. You were right, there were some stray files from the 3.8-beta present each time. When I wiped the lot and started from scratch it was fine, as you said. For whatever reason git status wasn't reporting any changes in the checked out copy, but there they were.

**Comment by badlogic** [comment]
No worries, happens to me as well. Other fun causes: switching branches without updating the VS project files or cleaning out the build artifacts. Glad it works for you now!
