### ISSUE TITLE
[iOS] Add multiple combined skin in skeleton

### ISSUE THREAD

**Issue by riyanpratamap** [EsotericSoftware/spine-runtimes#1439]
Hi, I want to add some combined multiple skin in my spine-cocos2d-objc project. Is that possible? I've read an added feature here #841 but I couldn't find how to use in spine-cocos2d-objc. Any help would be appreciated. Thank you!

**Comment by badlogic** [comment]
Yes, this is possible! You can use the spine-c API in spine-cocos2d-objc to combine multiple skins easily. See https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-sfml/c/example/main.cpp#L513

**Comment by MountMaster** [comment]
I get an error `Implicit declaration of function 'spSkin_addSkin' is invalid in C99` when I call `spSkin_addSkin` function. Is there any header that should be imported first?
