### ISSUE TITLE
[Runtimes] Error reading skeleton json file when create skeleton data

### ISSUE THREAD

**Issue by riyanpratamap** [EsotericSoftware/spine-runtimes#1441]
Hi, 

After update to 3.8, when I want to create a `SkeletonAnimation`, it always give me an error at `SkeletonJson.c` line 939.

This is the line I ended up
`for (attachmentsMap = Json_getItem(skinMap, "attachments")->child; attachmentsMap; attachmentsMap = attachmentsMap->next) {`

And this is how I create my skeleton node.
`skeletonNode = [SkeletonAnimation skeletonWithFile:skeleton atlasFile:atlas scale:scale];`

Anyway, I am using spine version 3.7.94. From what I have discovered, there's a difference about json skeleton from 3.8 and 3.7. In each `skin` node, there is an `attachments`. So my question is, how to support skeleton from previous spine version when I need the 3.8 runtime feature like `spSkin_addSkin`?

Is there any ideas? Thank you in advance

**Comment by badlogic** [comment]
Spine Editor and Runtimes versions must match I'm afraid. You either have to use the 3.7 runtime or update to the 3.8 editor and re-export. See also http://esotericsoftware.com/forum/Spine-editor-and-runtime-version-management-6534
