### ISSUE TITLE
[iOS] Create SkeletonAnimation from spSkeleton object

### ISSUE THREAD

**Issue by riyanpratamap** [EsotericSoftware/spine-runtimes#1443]
Hi.

In the spine runtimes 3.8 version (spine-c), there is functionality to add multiple skin by creating custom skin then adding one by one.

```
spSkeletonData* skeletonData = spSkeletonJson_readSkeletonDataFile(myJson, skeletonStr);

spSkin* skin = spSkin_create("default");
spSkin_addSkin(skin, spSkeletonData_findSkin(skeletonData, "face"));
spSkin_addSkin(skin, spSkeletonData_findSkin(skeletonData, "bottom_short"));
```

After that, I need to implement its skin into my skeleton
```
spSkeleton* drawable = spSkeleton_create(skeletonData);
spSkeleton_setSkin(drawable, skin);
spSkeleton_setSlotsToSetupPose(drawable);
```

But after that, I need to assign my `skeletonNode` like the [example](https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-cocos2d-objc/example/GoblinsExample.m#L45) said.

My `skeletonNode` is a `SkeletonAnimation`, and there is no initializer that require `spSkeleton` as an input param. I can assign my `skeletonNode` with this
```skeletonNode = [SkeletonAnimation skeletonWithData:skeletonData ownsSkeletonData:TRUE];```

But it didn't show my new custom skin that I've created.

Any ideas? Thank you!

**Comment by badlogic** [comment]
You also posted on the forum, let's discuss it there (and future questions regarding API usage). The tracker is used to keep track of bugs :)
