### ISSUE TITLE
[cocos2dx] Broken culling when using 2d projection

### ISSUE THREAD

**Issue by daniele-rapagnani** [EsotericSoftware/spine-runtimes#1445]
On version 3.8 of the cocos2dx runtimes animations are displayed incorrectly when using `Director::getInstance()->setProjection(Projection::_2D)`.

This is due to the [culling function](https://github.com/EsotericSoftware/spine-runtimes/blob/f98afcebfe0b6e5e21e576635c2aee90ee09f1cb/spine-cocos2dx/src/spine/SkeletonRenderer.cpp#L1009) expecting a 3d projection matrix in the incoming transform while you only get the identity matrix when using 2d projection.

**Comment by badlogic** [comment]
Thanks for reporting. This is now fixed in both the 3.8 and 3.9-beta branch. It should also work with custom projections.
