### ISSUE TITLE
[Unity] SpineExamples FootSoldier SkeletonDataAsset Slots, Click "Show Attachments" Button,  occur Error

### ISSUE THREAD

**Issue by 825126369** [EsotericSoftware/spine-runtimes#1453]
NullReferenceException: Object reference not set to an instance of an object
Spine.Unity.Editor.SkeletonDataAssetInspector.DrawSlotList () (at Assets/Spine/Editor/spine-unity/Editor/Asset Types/SkeletonDataAssetInspector.cs:501)
Spine.Unity.Editor.SkeletonDataAssetInspector.OnInspectorGUI () (at Assets/Spine/Editor/spine-unity/Editor/Asset Types/SkeletonDataAssetInspector.cs:224)
UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1625)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by HaraldCsaszar** [comment]
Thank you for reporting! Very much appreciated.

**Comment by HaraldCsaszar** [comment]
Problem was that not every skeleton has a default skin any longer (previous commit removed empty default skins). Some code relied on `skeletonData.DefaultSkin` always being non-null.
