### ISSUE TITLE
[runtimes] HasTimeline consumes a lot of CPU

### ISSUE THREAD

**Issue by quaerere** [EsotericSoftware/spine-runtimes#1462]
`AnimationState#hasTimeline()` loops over all timelines in an animation. It is used inside a loop in `AnimationState#computeHold()` that itself iterates through all timelines in the current entry's animation. This can result in O(n^2) in the worst case. Since `Animation` is supposed to be immutable (it's not because of `Animation#getTimelines()`), we can create store the timeline ids in a set for O(1) lookup instead.

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua 
- [x] spine-love
- [x] spine-corona

---
![image](https://user-images.githubusercontent.com/7693562/63420568-84b2c880-c439-11e9-88aa-e8fdc63117a1.png)

On some machines For example on honor 7x animation change  invoke HasTimeline Too much CPU

I think it is caused by the PropertyId  virtual function overrid implement

After a large quantity, it consumes cpu very much

thx

**Comment by NathanSweet** [comment]
`HasTimeline` is only called from `AnimationsChanged`, which only happens when the animations the AnimationState is applying have changed (a new animation is added or an animation will not longer be applied). Since it doesn't happen every frame, it's unlikely to be a performance problem.

**Comment by quaerere** [comment]
But if I use the spine to do that kind of jumping game, this problem will occur.

I modified the implementation of the propertyid

like
![image](https://user-images.githubusercontent.com/7693562/63633993-604a2c80-c683-11e9-9ed5-39d8cf7fabb6.png)

Determine performance improvement at runtime



But I think the data structure should be modified. It is a HastTime should be an o(1) and should not be looped to find

**Comment by NathanSweet** [comment]
In your code you forgot to return `propertyId` from the `PropertyId` getter.

I highly doubt HasTimeline is a bottleneck at all. Profilers often show the wrong thing as taking a lot of time. How many timelines are in your animation? Around 100-300 is common. Looping 300 times only when an animation changes should not be a bottleneck. Even in a jumping game, an animation changes maybe 10 times per second, maximum. The virtual function lookup when calling `getPropertyId` will not be slow. Calculating the property ID will not be slow. It is very likely your CPU is being used elsewhere. Animation `binarySearch` is most likely, as that needs to be called for every timeline, every frame.

**Comment by quaerere** [comment]
![image](https://user-images.githubusercontent.com/7693562/63634377-1e6fb500-c688-11e9-9944-80d764ecabad.png)
![image](https://user-images.githubusercontent.com/7693562/63634378-23346900-c688-11e9-9d8e-c52222d55e71.png)


Suppose an animation contains timeline 240


But this loop should be (240-x)*240

 
Not just Looping 240 times

**Comment by quaerere** [comment]
this loop should ben (240-x)*n*240

**Comment by NathanSweet** [comment]
That is true. It may be worth Animation keeping a set of property IDs.

**Comment by badlogic** [comment]
LibGDX lacks implementation in 3.8 branch. The list of IDs needs to be rebuild when timelines of an animation are modified manually.

Modifications of animation timelines on the fly while those animations are being referenced by track entries are impossible to handle (and will break other things). We ignore this case.

Instead, we document `Animation#getTimelines()` to say that modification of the returned timelines must be followed by calling the new method `Animation#setTimelines()`.
