### ISSUE TITLE
[unity] Issue with Skeleton Utility and skinned bones

### ISSUE THREAD

**Issue by TowerCrow** [EsotericSoftware/spine-runtimes#1464]
Info: http://esotericsoftware.com/forum/Issues-with-Skeleton-Utility-in-Unity-and-skinned-bones-12575

[Edit:] Reproduction zip package received via email: FMfcgxwDqnqjzTzrlFQptzqhDzBMcHhP

**Comment by HaraldCsaszar** [comment]
We are sorry for the trouble, thanks for reporting!

**Comment by HaraldCsaszar** [comment]
@TowerCrow Unfortunately we could not reproduce the issue. Could you please send us a minimal reproduction Unity project as a zip package that still shows the error? You can send it to contact@esotericsoftware.com.

**Comment by TowerCrow** [comment]
@HaraldCsaszar If you don't mind that the project is... ehem... very adult in nature then I can send it over.

**Comment by TowerCrow** [comment]
@HaraldCsaszar Email sent with the Unity project included in a zip file.

**Comment by HaraldCsaszar** [comment]
@TowerCrow Thanks very much!

**Comment by HaraldCsaszar** [comment]
The issue has now been resolved.

Updated unitypackages can be download here as usual:
http://esotericsoftware.com/spine-unity-download
