### ISSUE TITLE
[three.js] Flickering animation

### ISSUE THREAD

**Issue by PolinaLiolia** [EsotericSoftware/spine-runtimes#1472]
I'm using spine animation in my Three.js project and getting a strange flickering effect (see video here https://polina-liolia.tinytake.com/tt/MzczMDc2MF8xMTM1NDY3Ng)

runtime: spine-threejs
spine version: 3.7.93

**Comment by badlogic** [comment]
Thank you for the report. This can have many causes. I'm afraid it's not possible to tell why this happens just from the video. Could you create a simple example that let's me reproduce the issue locally? A HTML file including JavaScript to load and render the flickering skeleton, plus the skeleton data would suffice.

**Comment by PolinaLiolia** [comment]
Thank you for a quick response. 
I have already solved this issue, it was a depthWrite problem, so, I'm closing this thread.

If someone else faces this problem, here is a solution:

mySpineObject.batches.forEach(batch => {
            batch.material.depthWrite = false;
        });
