### ISSUE TITLE
[unity] Skin created by GetRepackedSkin doesn't maintain bones

### ISSUE THREAD

**Issue by Eyesiah** [EsotericSoftware/spine-runtimes#1474]
If a skin with bones is passed in to `AtlasUtilities.GetRepackedSkin`, the returned skin has an empty bones array.

I believe this also is the case for the skin Constraints also.

Simply copying over the bones myself afterwards appears to work in my case. However the two Lists are readonly, so I had to make changes to the plugin to allow this.

**Comment by HaraldCsaszar** [comment]
Thanks for reporting. Issue is fixed and updated unitypackages have been uploaded.

**Comment by Eyesiah** [comment]
Thanks Harald!
I notice though that you didn't add constraints to the new skin, is that also perhaps necessary?

**Comment by HaraldCsaszar** [comment]
Thanks for pointing that out Eyesiah, you are absolutely right! I updated the section once more and uploaded new unitypackages.
