### ISSUE TITLE
[spine-ts] spine-canvas scale incorrectlly when size and orig in atlas are not equal 

### ISSUE THREAD

**Issue by u14e** [EsotericSoftware/spine-runtimes#1477]
I'm using spine-canvas.js, My code comes from the official example at https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-ts/canvas/example/index.html.

When the region's size and orig are equal in atlas, spine-canvas work well.
```
atlas1.png
size: 1024,1024
format: RGBA8888
filter: Linear,Linear
repeat: none
alien/back-foot
  rotate: false
  xy: 351, 765
  size: 5, 3
  orig: 5, 3
  offset: 0, 0
  index: -1
```
But when they are not equal, spine-canvas seems scale incorrectlly.(However webgl work well!)
```
heroes.png
size: 1024,1024
format: RGBA8888
filter: Linear,Linear
repeat: none
Assassin/Assassin_arm_lower_far
  rotate: false
  xy: 128, 133
  size: 40, 43
  orig: 85, 69
  offset: 22, 13
  index: -1
```

Q1: What should I do to make spine-canvas work well when  size and orig are not equal in atlas?
Q2: spine-canvas‘s render overlap when animation is not static, Is there something I did wrong?

This is my test codes: https://github.com/wangheng-one/test-spine-canvas

**Comment by badlogic** [comment]
I'm afraid spine-canvas does not support white space stripped texture atlases. Please export your atlases without white space stripping.

Regarding your second question, you have an error in your canvas clearing code. This line:

https://github.com/wangheng-one/test-spine-canvas/blob/master/index_heroes.html#L133

should be:

```
context.fillStyle = "rgba(255, 255, 255, 255)";
```
