### ISSUE TITLE
[cpp] No way to set _regionDegrees in MeshAttachment

### ISSUE THREAD

**Issue by rh101** [EsotericSoftware/spine-runtimes#1480]
Now that a new field has been added to AtlasRegion (degrees) and MeshAttachment (_regionDegrees) in v3.8, it's causing issues with skin swapping when using texture regions that exist within a larger texture (non-Spine atlas sprite sheet), specifically when that texture region is rotated.  

The reason is that there is no way to set the `_regionDegrees` field in the MeshAttachment.  The only way it's set is by creating a new attachment from the AtlasAttachmentLoader, which means we cannot provide textures from other sources.

Would you please add something similar to the following for that field in MeshAttachment.h/.cpp?

```
int getRegionDegrees();
void setRegionDegrees(int inValue);
```

```
int MeshAttachment::getRegionDegrees()
{
    return _regionDegrees;
}

void MeshAttachment::setRegionDegrees(int inValue)
{
    _regionDegrees = inValue;
}
```

**Comment by badlogic** [comment]
Sorry for the oversight. This is now fixed in the 3.8 and 3.9-beta branches.
