### ISSUE TITLE
[cocos2dx] Unexpected behaviour for getBoundingBox

### ISSUE THREAD

**Issue by daniele-rapagnani** [EsotericSoftware/spine-runtimes#1483]
If `SkeletonRenderer::getBoundingBox` is called before the node is drawn for the first time the bounding box is empty. This happens because [`_boundingRect`](https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-cocos2dx/src/spine/SkeletonRenderer.cpp#L274) is calculated inside `SkeletonRenderer::draw`. 

This is a breaking change with the previous versions of the runtime which correctly returned a bounding box without the need to issue a draw call.
I also think this is not the expected behaviour considering that one often needs to calculate the node's position prior to drawing based on the current animation size and doing so after the first frame is drawn will result in unwanted flickering.

I think there's another problem with this solution: the `_boundingRect` property will never be calculated if `CC_USE_CULLING` is not defined.

**Comment by badlogic** [comment]
Thank you for reporting. This is fixed in the 3.8 and 3.9-beta branches.
