### ISSUE TITLE
[libgdx] Skin.setAttachment() does not work as expected.

### ISSUE THREAD

**Issue by piotr-j** [EsotericSoftware/spine-runtimes#1485]
Changing attachement via `Skin.setAttachment()` does not update internal keys in `OrderedMap`. This results in `SkinEntry.attachment` being different in `Skin.getAttachment()` vs `Skin.getAttachments()`. 

Perhaps thats expected, but im replacing attachments during runtime and updating didnt work.

**Comment by badlogic** [comment]
Could you post a simple repro for me here?

**Comment by piotr-j** [comment]
Sure thing. Its minor modification to `SkinBonesMixAndMatchTest.java` if its not clear.
https://gist.github.com/piotr-j/c8d629f3eaf44d18249c66d7428e7e83
Perhaps Im holding it wrong.
