### ISSUE TITLE
[unity] Mix and Match Equip example submesh draw order problem

### ISSUE THREAD

**Issue by TowerCrow** [EsotericSoftware/spine-runtimes#1486]
Something's going wrong with Spine boy's arms in the latest runtimes, downloaded today. 

GIF: https://i.imgur.com/UAwHTul.gifv

**Comment by TowerCrow** [comment]
Issue persists even when deleting existing Runtimes folders and importing it fresh. I'm on Unity 2019.2.4f1. Is it perhaps related to Lightweight Render Pipeline? I thought the default unlit shaders should still work properly in LWRP as well. 

--- 

I deleted LWRP asset file to roll back to default renderer and now works without issues as intended. So it seems to be LWRP related.

**Comment by badlogic** [comment]
The shaders should indeed work as intended with LWRP. What platform are you running on? Windows/Linux/macOS/iOS/Android?

**Comment by TowerCrow** [comment]
I'm on Windows myself. Unity is also running the Windows platform.

**Comment by HaraldCsaszar** [comment]
Shaders are not the cause, same draw order problem occurs with Unity's provided LWRP shaders.
LWRP seems to be more agressive with re-ordering draw calls of submeshes.

Disabling batching in Project settings has no effect, thus cannot be solved this way.

Working workaround:
When setting a different MaterialPropertyBlock at each submesh, draw call order is maintained.
Clean solution based on this test is in progress.

**Comment by HaraldCsaszar** [comment]
Now providing additional **Fix Draw Order** parameter at SkeletonRenderer, defaults to `disabled` (previous behaviour). See http://esotericsoftware.com/spine-unity#Setting-Advanced-Parameters.
   
Applies only when 3+ submeshes are used (2+ materials with alternating order, e.g. "A B A").
If true, MaterialPropertyBlocks are assigned at each material to prevent aggressive batching of submeshes by e.g. the LWRP renderer, leading to incorrect draw order (e.g. "A1 B A2" changed to "A1A2 B"). You can leave this parameter disabled when everything is drawn correctly to save the additional performance cost.

**Comment by HaraldCsaszar** [comment]
New unitypackages are available for download.
Thanks TowerCrow for reporting!

**Comment by HaraldCsaszar** [comment]
New problem occurred in Unity 2019.2 as reported in this forum thread:
http://esotericsoftware.com/forum/Spine-Animation-rendering-problem-10189

Reproduction package sent via email as zip file:
FMfcgxwGBmnBCfTzCJQZdzpncxxHQKdM

Instantiating materials fixes the problem, is not a desired solution though.
