### ISSUE TITLE
[lua] Multiple clippings problem

### ISSUE THREAD

**Issue by lifestreamer** [EsotericSoftware/spine-runtimes#1489]
https://github.com/EsotericSoftware/spine-runtimes/blob/df748dbe4b38b7737c48dfa164a22b139d154bd7/spine-lua/SkeletonClipping.lua#L78
I am having problems using multiple clippings. Seems like the problem is that if statement in line 78 is always false. I think that endSlot has to be compared to slot.data in order to work:
self.clipAttachment.endSlot == slot.data

Please check it out, thanks.

**Comment by badlogic** [comment]
Good catch! This has been fixed in the 3.8 and 3.9-beta branches.
