### ISSUE TITLE
Slot not found: name (Error with Spine Version 3.8.x) 

### ISSUE THREAD

**Issue by ColtonPhillips** [EsotericSoftware/spine-runtimes#1495]
Our team has discovered an issue with the latest Spine version (3.8) where it is exporting the skins object in the JSON in a different format making the file not loadable by our runtime.

This user has also had the same issue, and is saying that the fix is to export the file using 3.7.x
http://www.html5gamedevs.com/topic/43549-error-with-spine-version-3860/

Is this an intentional change? I'm hoping not, as it's going to break a lot for our team. haha. 

Can you please comment on if you are addressing this issue and if so, when? I can give additional information but the attached thread describes the issue well.

**Comment by ColtonPhillips** [comment]
Oh crap. I now see that a major change was made for this version. OK.

**Comment by badlogic** [comment]
Yeah, sorry about that. Spine releases are not guaranteed to be backward compatible. In the case of the 3.8 release, we had to modify the JSON and binary export formats to enable our new skin bones and constraint feature (see http://esotericsoftware.com/blog/Spine-3-8-released#Runtime-improvements).

If i remember correctly, Panda 2 doesn't modify the Spine TypeScript sources. You could try to update the Spine Runtime used by Panda 2 yourself.
