### ISSUE TITLE
[cpp] Undefined type compilation error

### ISSUE THREAD

**Issue by rh101** [EsotericSoftware/spine-runtimes#1498]
Recent changes (the removal of several STL include statements) now result in `identifier "uint32_t" is undefined` errors in Animation.cpp.  

Dev env: VS2019 on Windows 10.

**Comment by badlogic** [comment]
I've compiled the changes with VS2017 on Windows 10 as part of our UE4 example project without issues.

I'll try with VS2019 and the cocos2d-x project.

**Comment by rh101** [comment]
Sorry, I forgot to mention that it was with cocos2d-x 3.17.2.  Adding `#include <stdint.h>` in Animation.cpp fixed the issue for me.
