### ISSUE TITLE
[spine-tsl] Webgl - support render to texture (useful for Construct plugin)

### ISSUE THREAD

**Issue by MikalDev** [EsotericSoftware/spine-runtimes#1501]
In webgl, also support render to texture instead of only render to canvas's webgl context frame buffer. Currently, have somewhat worked around this by adding the following around the Spine render:

```
// render to our targetTexture by binding the framebuffer
gl.bindFramebuffer(gl.FRAMEBUFFER, this.spineFB);
this.render(); // Spine render
// Restore render to the canvas for C3
gl.bindFramebuffer(gl.FRAMEBUFFER, null);
```
However, a number of parameters in the render tie directly to the webgl managed context's canvas characteristics (e.g. canvas width and height) which do not match the texture size we are rendering to. There may be other parameters besides that.

Would it be possible to add support for this or suggestions on how/where to do changes (e.g. on the creation of ManagedWebGLContext() or somewhere else) if I create my own change and PR?

**Comment by badlogic** [comment]
SkeletonRenderer and PolygonBatcher should have zero dependencies in the canvas. Are you using SceneRenderer? If so, I suggest using the lower level APIs.

**Comment by MikalDev** [comment]
Thanks, yes using SceneRenderer right now, I will try out SkeletonRenderer instead. Thanks for the suggestion.

**Comment by MikalDev** [comment]
Looks like skeletonRenderer is working and no changes for Spine-TS needed, thanks for help (now chasing down PMA and restoring more of the C3 webgl state.)
