### ISSUE TITLE
[spine-ts] "default" skin backwards compatibility is broken.

### ISSUE THREAD

**Issue by jonchun** [EsotericSoftware/spine-runtimes#1503]
This was code that used to return a Skin object. 
`skeletonData.findSkin("default");`

making the following snippet valid:
`skeleton.setSkinByName("default");`

However, with the changes in the new export format, it looks like the skin "default" is no longer included, meaning there is no more empty "default" skin, so code such as `skeleton.setSkinByName("default");`
will error out saying `Skin not found: default`

(I've only checked the JSON export formats, but the code in `SkeletonBinary` reads like it would have the same problem to me.)

In my case, I came across this issue as I'm trying to update the Phaser Spine plugin:
https://github.com/photonstorm/phaser/blob/v3.19.0/plugins/spine/src/gameobject/SpineGameObject.js#L517
and update it for use with spine3.8 runtime. I'm sure that there are other developers who are also using `setSkinByName("default")` in their code. 

I've fixed this issue for myself by adding a check at the end of the skin loading loops in both `SkeletonJson.ts` and `SkeletonBinary.ts`.

e.g. inserted into line 261 in `SkeletonJson.ts` 
```
if (skeletonData.defaultSkin == null) {
	skeletonData.defaultSkin = new Skin("default");
	skeletonData.skins.push(skeletonData.defaultSkin);
}
```
If the design change to return `null` for an empty default skin was intentional, this issue should be dismissed. However, it might be nice to provide a marginal amount of backwards compatibility.

**Comment by badlogic** [comment]
This looks like a bug, thanks for reporting! I'll restore the old behaviour.

**Comment by badlogic** [comment]
I've had a look at this now. It appears this was already the behavior in Spine 3.7. If the default skin does not have any attachments in the editor, no `default` skin will be exported to either JSON or .skel. Also, neither the old `SkeletonJson` nor the old `SkeletonBinary` loaders would create an empty skin if no `default` skin was found in the JSON or .skel file.

As such, we won't add this behavior to the 3.8 or 3.9-beta runtimes. Could this possibly be a behavior introduced by the Phaser Spine plugin?

**Comment by jonchun** [comment]
> Could this possibly be a behavior introduced by the Phaser Spine plugin?

Yes, it probably is. I guess `skeleton.setSkinByName("default");`  is not a call that is always valid. I'll go report this on the Phaser end. (They run the above upon instantiation of every Spine game object... which is not great if you're not always going to have at least an empty default skin)

Thanks for looking at this!
