### ISSUE TITLE
[spine-ts] webgl should allow `LINEAR` and `NEAREST` only in texture magnification filter

### ISSUE THREAD

**Issue by Deardrops** [EsotericSoftware/spine-runtimes#1508]
These is one line `filter: MipMapLinearLinear,MipMapLinearLinear` in my `.atlas` file, when import resource files by `spine-ts/player`, it cause an error in browser:
`GL_INVALID_ENUM: Texture filter not recognized.`

In line `filter: MipMapLinearLinear,MipMapLinearLinear`, means
**assign `gl.LINEAR_MIPMAP_LINEAR` to texture magnification filter**, and
assign `gl.LINEAR_MIPMAP_LINEAR` to texture minification filter.

By I found in [WebGL document on MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texParameter)

pname | Description | param
-- | -- | --
gl.TEXTURE_MAG_FILTER | Texture magnification filter | **gl.LINEAR (default value), gl.NEAREST.**
gl.TEXTURE_MIN_FILTER | Texture minification filter | gl.LINEAR, gl.NEAREST, gl.NEAREST_MIPMAP_NEAREST, gl.LINEAR_MIPMAP_NEAREST, gl.NEAREST_MIPMAP_LINEAR (default value), gl.LINEAR_MIPMAP_LINEAR.

Texture magnification filter not allow values like `gl.LINEAR_MIPMAP_LINEAR`, so The first parameter of `filter`(assign `gl.LINEAR_MIPMAP_LINEAR` to texture magnification filter) will cause the error.

Suggestion: `spine-ts` add a check for this case, and convert disallowed texture magnification filter value to default value (`gl.LINEAR`) automatically.

https://github.com/EsotericSoftware/spine-runtimes/blob/9c1143198852b754dba539cdbdd8668b7252fc53/spine-ts/core/src/TextureAtlas.ts#L64-L66

Between Line L64 and L65, add a check, ensure the only available values are `LINEAR` and `NEAREST`.
In other cases, convert to default value `LINEAR`.
If it is an unexpect value, throw error `Unknown texture filter`.

**Comment by badlogic** [comment]
Ah, that's definitely a bug, thanks for reporting!
