### ISSUE TITLE
[ue4] performance

### ISSUE THREAD

**Issue by jolu368** [EsotericSoftware/spine-runtimes#1509]
Hi, 

I am going to make a 2D game by UE4, and consider to use spine2D to make characters, but when I try to test performance on UE4, the FPS was low.

The way I test, I made a 3D scene, putted 100 spineBoy on the scene, the FPS was like 60. I made a real 3D character by Max, triangles 6500, bones 64, putted 100 on the scene, the FPS was 120. I made a fake 2D character with lots mesh by Max, triangles 54, bones 26, putted 100 on the scene, the FPS was 120, too. I read profiling, only know it's like CPU bottleneck, GameThread was high, WorldTick Time, Tick Time, Post Tick component Update was so high than made by Max, and I noticed recreate time spent 2.88 ms. I have no idea what is recreate time.

By the way, I am a newer with UE4, thx for helping!

**Comment by badlogic** [comment]
Spine does not support GPU side skinning which means it has to be done on the CPU side. This is why you see the CPU side load. The comparison to your Max characters might not be quite valid, especially with the second 2D Max character, as Spineboy is a quite complex setup in terms of rig and meshes. For a fair comparison, you'd have to animate the Max characters as well.

The drop from 120hz to 60hz is a bit suspicious, what's your monitor refresh rate? 

At the end of the day, these kind of benchmarks are usually not super helpful. I suggest simulating what you are aiming for in your game instead.

**Comment by jolu368** [comment]
Hi, 
Thanks for your reply! I think you are right, I agree the effect of spine2D to make 2D is good and convince than max! Does monitor refresh rate influences FPS?

By the way, I want to make game on Android, not PC.

**Comment by badlogic** [comment]
Yes, the monitor refresh rate does influence the frame rate if something called vsync is turned on. If it is turned on, you can't draw more frames than the monitor refresh rate. That the FPS went down by exactly 50% in your tests is somewhat suspicious in that it might have something to do with refresh rate.

Spine for UE4 works just fine on iOS and Android as well. As I said, setup a test scene with the complexity you are aiming for and see if the performance is OK. Note that the examples you find in our GitHub repository are all quite heavy and not mobile optimized, your mileage may vary :)

**Comment by jolu368** [comment]
Hi, 
I did some test to improve FPS which putted 100 spineboys on the empty scene, and disable 50 spineboys's tickComponent in USpineSkeletonRendererComponent and  USpineSkeletonAnimationComponent, the FPS rise. It means I can disable tickComponent of spine2D which doesn't inside camera but need on the scene. It works!

**Comment by badlogic** [comment]
Yes, culling like that will work well! The problem is that we can not anticipate the needs of the application. Some might require `tickComponent()`  to execute even if the skeleton is not on screen, while other apps might not.
