### ISSUE TITLE
[cpp] Add getters for _x and _y on SkeletonData

### ISSUE THREAD

**Issue by daniele-rapagnani** [EsotericSoftware/spine-runtimes#1518]
The `skeleton`/`format` element of both the JSON and binary format exposes some useful values such as the width and height and min of the AABB of the setup pose. 

These fields are present in both the [JSON](http://it.esotericsoftware.com/spine-json-format) and [binary](http://it.esotericsoftware.com/spine-binary-format) format documentation and this makes me think they are not for internal use, yet only the `_width` and `_height` are exposed on `SkeletonData`. I can't think of a good reason for not doing the same with `_x` and `_y`, which are equally useful.

The only other way to get these values would be to use the `getBounds` method after setting the skeleton in setup pos, which is way more expensive and feels contrived.

**Comment by badlogic** [comment]
You're absolutely right, sorry for overlooking this. The two fields are now exposed through getters and setters in both the 3.8 and 3.9-beta branches.
