### ISSUE TITLE
[UE4] Can't compile project with 3.8 spine-runtimes 'SpineLitNormalMaterial.uasset'

### ISSUE THREAD

**Issue by raxi2012** [EsotericSoftware/spine-runtimes#1523]
Project uncompilable with ../Plugins/SpinePlugin/Content/SpineLitNormalMaterial.uasset file, removing SpineLitNormalMaterial.uasset completely solves the problem
![git_error](https://user-images.githubusercontent.com/17443915/66858695-16e2d300-ef8a-11e9-9806-3576e11222b8.png)

**Comment by badlogic** [comment]
What UE4 version are you using?

**Comment by raxi2012** [comment]
4.21.3

**Comment by GitHub-NetFly** [comment]
The engine version corresponding to version 3.8 should be 4.22. If you want to use it under 4.21, you can rebuild this material in version 4.21.

**Comment by badlogic** [comment]
If you don't use the material and it's the packaging that errors, you can simply delete the material.

If you want to use the material, you have to rebuild it in 4.12 as @GitHub-NetFly said. Here's what it looks like:

https://marioslab.io/uploads/screenshots/UE4Editor_sQ6CyWFY8m.jpg
