### ISSUE TITLE
[unity] Request: texture importer settings taken from a preset

### ISSUE THREAD

**Issue by Eyesiah** [EsotericSoftware/spine-runtimes#1524]
Currently the texture settings that are set on a new importer in `SetDefaultTextureSettingsIfNew` are hardcoded. However, the settings that work for a given texture are somewhat dependant on the export settings used in Spine. It would be great if these could be specified by users in the project's SpineSettings, preferably using the unity Preset system. For example:

```            var preset = AssetDatabase.LoadAssetAtPath<UnityEditor.Presets.Preset>("Assets/Presets/TextureImporter_Spine_Standard.preset");
            if (preset != null)
            {
                preset.ApplyTo(texImporter);
                EditorUtility.SetDirty(texImporter);
                AssetDatabase.ImportAsset(texturePath);
            }
```

**Comment by HaraldCsaszar** [comment]
I am very sorry for the late reply, I seem to have missed your post for a long time now!

Please note that we have an issue ticket for adding a config parameter to define which workflow is used: https://github.com/EsotericSoftware/spine-runtimes/issues/1410
@Eyesiah Would this also resolve your requirements? Or do you have additional settings in mind?

**Comment by Eyesiah** [comment]
Well we'd like to be able to configure all the settings that texture importers can have, to be honest. As such the existing unity preset feature seems like a good fit.

**Comment by HaraldCsaszar** [comment]
@Eyesiah This feature has just been completed. See the changelog.md file (bottom part under `Additions`) for further info:
https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/CHANGELOG.md#unity

You can download the new unitypackages here as usual:
http://esotericsoftware.com/spine-unity-download

**Comment by Eyesiah** [comment]
Thanks! Looks like an improvement, but may I ask why you have the SpineSettings.TextureSettingsReference reference a Texture2D asset, instead of a Preset asset? (as in, what's created here: https://docs.unity3d.com/Manual/Presets.html)

**Comment by Eyesiah** [comment]
Also: in AssetUtility.cs, SetReferenceTextureSettings should return if reference == null:

`		static bool SetReferenceTextureSettings (string texturePath, SpineAtlasAsset atlasAsset, string referenceAssetPath) {
			TextureImporter reference = TextureImporter.GetAtPath(referenceAssetPath) as TextureImporter;
            if (reference == null)
            {
                return SetDefaultTextureSettings(texturePath, atlasAsset);
            }`

Otherwise it will throw an exception later in the function.

Also an error message that the referenceAssetPath couldn't be loaded would be nice.
Even if it must be a Texture2D, why load the asset via string rather than just allowing a straight reference to the texture?

**Comment by Eyesiah** [comment]
Please also add this to the list of settings that are copied over:

`texImporter.textureType = reference.textureType;`

**Comment by HaraldCsaszar** [comment]
Thanks very much for reporting the issues above, especially the missing `return` slipped through.

The bugfixes are committed, new unitypackages are available as download as usual:
http://esotericsoftware.com/spine-unity-download

Regarding Texture2D vs Preset assets:
The main reason is that we still need to support Unity 2017.1, Preset assets have been introduced in 2018.1 if I recall that correctly.
Nevertheless you have a point there, since we already have #if branches for Unity 2018.3+, it would indeed provide a nicer implementation to use Preset assets in this code branch instead.

I will reopen the ticket for implementation of Preset asset support.

**Comment by HaraldCsaszar** [comment]
@Eyesiah Preset assets are now used as atlas texture reference settings on Unity 2018.3+ instead of template Texture2D assets. New unitypackages have just been released.

**Comment by Eyesiah** [comment]
Thanks very much!
