### ISSUE TITLE
[TS] Creating a curve timeline where x=0 use a linear timeline

### ISSUE THREAD

**Issue by smaren** [EsotericSoftware/spine-runtimes#1537]
Issue is in https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-ts/core/src/SkeletonJson.ts#L787
The line  `if (!map.curve) return;` where the value of `map.curve` is `0` which is a falsy value

**Comment by badlogic** [comment]
Thank you for reporting.

**Comment by badlogic** [comment]
I've tried to reproduce this, trying out various combinations of curve types (linear, bezier. stepped) and types of timelines (rotation/scale/translation). All were loaded and animated correctly.

Please post a minimal skeleton JSON file for me to reproduce this issue.

**Comment by smaren** [comment]
```
{
"skeleton": { "hash": "G/hS9ErDX5gq+UBh6QU9XHiVqzg", "spine": "3.8.72", "x": -161, "y": -118, "width": 323, "height": 236 },
"bones": [
	{ "name": "root" },
	{ "name": "test", "parent": "root" }
],
"animations": {
	"test": {
		"bones": {
			"test": {
				"scale": [
					{ "x": 0, "y": 0, "curve": 0, "c2": 0.69, "c3": 0.917, "c4": 0.23 },
					{ "time": 0.2333 }
				]
			}
		}
	}
}
}
```

The issue exists if the `curve` part of the scale timeline is `0`

**Comment by smaren** [comment]
@badlogic I've provided a minimal Skeleton JSON. Please let me know if you need further info.

**Comment by badlogic** [comment]
Terribly sorry, this went under in a flood of notifications! Thanks for the repro, i'll take a look.
