### ISSUE TITLE
[TS] Animation TrackEntry pool does not clear mixBlend

### ISSUE THREAD

**Issue by vinerz** [EsotericSoftware/spine-runtimes#1541]
The `trackEntry` pool resets the entry properties to default when requested. The `mixBlend` isn't reseted thus making the blending leak across other tracks when reused.

https://github.com/EsotericSoftware/spine-runtimes/blob/654c20e5b0e523040b6366bbd1042510d2645134/spine-ts/core/src/AnimationState.ts#L512

**Comment by badlogic** [comment]
Confirmed, thanks for reporting!
