### ISSUE TITLE
[cpp] Non consistent handling of the empty names

### ISSUE THREAD

**Issue by AIGRIND-LLC** [EsotericSoftware/spine-runtimes#1543]
Hi,
Some comments says that corresponding API may be called with the empty strings.
[Example 1](https://github.com/EsotericSoftware/spine-runtimes/blob/8e0a2e0c75e43e83e7e6426039805519cedac329/spine-cocos2dx/src/spine/SkeletonRenderer.h#L87)
[Example 2](https://github.com/EsotericSoftware/spine-runtimes/blob/8e0a2e0c75e43e83e7e6426039805519cedac329/spine-cocos2dx/src/spine/SkeletonRenderer.h#L95)
But actually it's impossible due to asserts in `spine.ContainerUtil.find***WithName `.

**Comment by AIGRIND-LLC** [comment]
Moreover our legacy code relies on the old behaviour when the empty names were legal :)

**Comment by badlogic** [comment]
Thanks for reporting. This should be fixed in the 3.8 and 3.9-beta branches.
