### ISSUE TITLE
Errors importing skeleton in spine-libgdx

### ISSUE THREAD

**Issue by foldedpaper** [EsotericSoftware/spine-runtimes#1547]
This is the first time I am attempting to export from Spine and import into a project, so I apologize in advance if I'm missing something simple. That said, I believe I am following the right steps to import a skeleton.

I have tried opening the sample Spineboy project in Spine Essential edition, then exporting it as a JSON file (exported atlas, png, and json [attached as a zip](https://github.com/EsotericSoftware/spine-runtimes/files/3843435/spineboy-ess.zip) to this issue). I use the following code attempting to import in my libgdx project:

```
        TextureAtlas atlas = new TextureAtlas(Gdx.files.internal("spine/spineboy-ess.atlas"));
        SkeletonBinary json = new SkeletonBinary(atlas);
        SkeletonData skeletonData = json.readSkeletonData(Gdx.files.internal("spine/spineboy-ess.json"));
```
 produces an exception:
```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 32
	at com.esotericsoftware.spine.SkeletonBinary.readSkeletonData(SkeletonBinary.java:182)
```

Using the following versions:
- Spine 3.8.76 Essential
- spine-libgdx 3.8.55.1

**Comment by badlogic** [comment]
No biggie! You are trying to load a `.json` file with a `SkeletonBinary` instance. Use a `SkeletonJson` instance instead :)

**Comment by foldedpaper** [comment]
OOOOOOPS! Yes, I see it now, thanks for the very basic reminder.
