### ISSUE TITLE
[cpp] Setting a new renderer object does not dispose of the existing renderer object

### ISSUE THREAD

**Issue by rh101** [EsotericSoftware/spine-runtimes#1549]
In this class:

```
class SP_API HasRendererObject {
public:
	explicit HasRendererObject() : _rendererObject(NULL), _dispose(NULL) {};

	virtual ~HasRendererObject() {
		if (_dispose && _rendererObject)
			_dispose(_rendererObject);
	}

	void* getRendererObject() { return _rendererObject; }
	void setRendererObject(void* rendererObject, DisposeRendererObject dispose = NULL) {
		_rendererObject = rendererObject;
		_dispose = dispose;
	}
private:
	void *_rendererObject;
	DisposeRendererObject _dispose;
};
```
If we have a render object already set with a valid dispose callback function, and we call `setRendererObject()`, the current class members are simply overwritten, which means the previous renderer object is never disposed of.

Is that intentional?

Also, if it is to be changed, the current _rendererObject would need to be checked against the new rendererObject to make sure they're not the same, otherwise it'll dispose of that same object.

Would something like this make sense:
```
	void setRendererObject(void* rendererObject, DisposeRendererObject dispose = NULL) {
                if (_dispose && _rendererObject && _rendererObject != rendererObject)
			_dispose(_rendererObject);

		_rendererObject = rendererObject;
		_dispose = dispose;
	}
```

**Comment by badlogic** [comment]
Your solution looks good to me. I'll check its effect on the various engine integrations and get back to you hear asap.

**Comment by badlogic** [comment]
Thanks for reporting. Your proposed change was compatible with all runtimes. It's now live on the 3.8 and 3.9-beta branches.

**Comment by rh101** [comment]
That's great news, thank you!
