### ISSUE TITLE
spine-cpp readSkeletonDataFile() crash

### ISSUE THREAD

**Issue by Melochineer** [EsotericSoftware/spine-runtimes#1552]
With a skeleton json file exported from spine 3.8.76 on line 439 of SkeletonJson.cpp skinMap->_name is null. Reverting to spine 3.7.94 fixes the problem.

**Comment by badlogic** [comment]
Your skeleton file version doesn't match the runtime version. I.e. you can not load skeletons exported with Spine Editor version 3.7 with Spine Runtimes version 3.8. See our release blog post:

http://esotericsoftware.com/blog/Spine-3-8-released#Runtime-improvements

And this discussion about version management:

http://esotericsoftware.com/forum/Spine-editor-and-runtime-version-management-6534
