### ISSUE TITLE
API for playing animation N times

### ISSUE THREAD

**Issue by marcusalanen** [EsotericSoftware/spine-runtimes#1561]
There is no API for playing an animation N times. You can queue an animation several times, but that has drawbacks in our case:

In our game the player can throw a spell. Depending on level etc, the spell can take a varying amount of time. We do this by having three animations, a start animation, a middle animation and an end animation. The middle animation is only 0.1 seconds long. By queueing up several of these we can make the spell last any duration.

The problem is that this creates ~1000 instances :) This could be solved by having an "int loops" instead of "bool loop" in the API (and -1 meaning infinite loops for backwards compatibility).

At the moment, there also seems to be a linear algorithm in there somewhere. Playing the full sequence of animations takes longer and longer, even though it shouldn't.

And yes, I do realize there are other ways to fix this outside of Spine, but the current code is what it is... Furthermore this would actually be a useful addition to the API anyway.

**Comment by HaraldCsaszar** [comment]
Please do not enqueue hundreds of animations.

If you want to keep a middle animation repeating, please either:
1. use `addAnimation` to set the end animation. The delay is how long the middle animation should play. or, 
2. let the middle animation play, then use `setAnimation` to set the end animation.
