### ISSUE TITLE
[unity] Spine LWRP Sprite shader error

### ISSUE THREAD

**Issue by AgitAngst** [EsotericSoftware/spine-runtimes#1563]
**Unity 2019.2.15.f1 + Spine 3.8  +spine.lwrp-shaders 3.8** 
I'm using example scene that comes with lwrp-shaders. Same error in Unity 2019.2.15.1f + spine 3.9b versions
Can't get access to material properties, got this error all the time:

`ArgumentException: Could not find MaterialProperty: '_OutlineWidth', 
Num properties: 34
UnityEditor.ShaderGUI.FindProperty (System.String propertyName, UnityEditor.MaterialProperty[] properties, System.Boolean propertyIsMandatory)
 (at C:/buildslave/unity/build/Editor/Mono/Inspector/ShaderGUI.cs:51)
UnityEditor.ShaderGUI.FindProperty (System.String propertyName, UnityEditor.MaterialProperty[] properties) 
(at C:/buildslave/unity/build/Editor/Mono/Inspector/ShaderGUI.cs:40)
SpineShaderWithOutlineGUI.FindProperties (UnityEditor.MaterialProperty[] props) 
(at Assets/Spine/Editor/spine-unity/Editor/Shaders/SpineShaderWithOutlineGUI.cs:79)
SpineSpriteShaderGUI.FindProperties (UnityEditor.MaterialProperty[] props)
 (at Assets/Spine/Editor/spine-unity/Editor/Shaders/SpineSpriteShaderGUI.cs:203)
SpineSpriteShaderGUI.OnGUI (UnityEditor.MaterialEditor materialEditor, UnityEditor.MaterialProperty[] properties)
 (at Assets/Spine/Editor/spine-unity/Editor/Shaders/SpineSpriteShaderGUI.cs:180)
UnityEditor.MaterialEditor.PropertiesGUI () 
(at C:/buildslave/unity/build/Editor/Mono/Inspector/MaterialEditor.cs:1726)
UnityEditor.MaterialEditor.OnInspectorGUI () 
(at C:/buildslave/unity/build/Editor/Mono/Inspector/MaterialEditor.cs:475)
UnityEditor.UIElements.InspectorElement+<CreateIMGUIInspectorFromEditor>c__AnonStorey1.<>m__0 () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorElement.cs:501)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)
`
Screenshot: [https://ibb.co/ZH437BC]

**Comment by HaraldCsaszar** [comment]
We are sorry for the trouble! Thanks for reporting.
This has been fixed and new unitypackages uploaded.

It has been tracked under this issue ticket:
https://github.com/EsotericSoftware/spine-runtimes/issues/1565
