### ISSUE TITLE
[cocos2dx] Cannot render Spine animation to RenderTexture in certain scenarios

### ISSUE THREAD

**Issue by rh101** [EsotericSoftware/spine-runtimes#1566]
If the Spine animation is to be rendered to a RenderTexture, then it will not work if this is attempted in a scheduled task. For example:

```
const auto director = Director::getInstance();
director->getScheduler()->schedule([this](float) {
    const auto boundingBox = skeletonAnimation->getBoundingBox();

    auto renderTexture = RenderTexture::create(int(boundingBox.size.width), int(boundingBox.size.height), PixelFormat::RGBA8888);
    renderTexture->beginWithClear(0, 0, 0, 0);

    skeletonAnimation->setGlobalZOrder(0);
    skeletonAnimation->setPosition(boundingBox.size.width / 2, 0); // Position is affected by your Spine model anchor point
    skeletonAnimation->visit();

    renderTexture->end();
    renderTexture->saveToFile(FileUtils::getInstance()->getWritablePath() + "/snapshot.png");
    Director::getInstance()->getRenderer()->render();
}, this, 0, 0, 0, false, "SaveSnapshot");
```

The reason is related to the changes made in this commit: 
https://github.com/EsotericSoftware/spine-runtimes/commit/5cb9afd2fab20cac97c0afc6c9db0283bad7b541

Specifically this section of code:
```
SkeletonRenderer::draw() {
    ...
    #if CC_USE_CULLING
    const cocos2d::Rect bb = computeBoundingRect(worldCoords, coordCount / 2);

    if (cullRectangle(renderer, transform, bb)) {			
        VLA_FREE(worldCoords);
        return;
    }
    #endif
    ...
}

bool cullRectangle(Renderer* renderer, const Mat4& transform, const cocos2d::Rect& rect) {
    if (Camera::getVisitingCamera() == nullptr)
        return true;
    ...
}
```
If the visiting camera is null, then `cullRectangle()` should return false instead of true, which fixes this issue. 

The older version of the code worked correctly, since it checked for the camera first, and only attempted to cull if a camera existed:
```
if (camera && cullRectangle(transform, brect, *camera)) {
    VLA_FREE(worldCoords);
    return;
}
```

In cocos2d-x, the default is that if the visiting camera is null, then no culling takes place (refer to `Node::isVisitableByVisitingCamera()`).  For instance, this would occur when we explicitly call `Director::getInstance()->getRenderer()->render()` outside the normal render loop, such as what would be required when rendering to a RenderTexture.

**Comment by badlogic** [comment]
Cheers! This is fixed in the 3.8 branch. I'll merge it into the 3.9-beta branch as soon as I'm done with getting spine-cocos2dx with cocos2dx v4 working.
