### ISSUE TITLE
JSON Format Check bone is hidden (FLAG)

### ISSUE THREAD

**Issue by Yahor10** [EsotericSoftware/spine-runtimes#1567]
Hello.
How to handle json and validate with code when bone is hidden?
I have few bones invisible. How to check it by code
![Screenshot from 2019-12-10 17-31-19](https://user-images.githubusercontent.com/1306298/70540913-1d9b5a00-1b77-11ea-8ae8-1fbdd3a7a688.png)

**Comment by Yahor10** [comment]
It is easy to set bone invisitor in editor, but i cant find hidden flag in json

**Comment by badlogic** [comment]
Please post questions like this on our forum at https://esotericsoftware.com/forum. This issue tracker is reserved for actual bugs or enhancements.
