### ISSUE TITLE
Animation blending/mixing doubt

### ISSUE THREAD

**Issue by WaaghMan** [EsotericSoftware/spine-runtimes#157]
When I mix two animations by using the AnimationState class with a set mix value, the mixing is done by applying the source animation, and then mixing the target animation with an alpha value that increases over time.

I've experienced some issues with this kind of blending (Source * 1 + Target * Alpha), depending on what animations we're mixing, so I've tried doing a different blending (Source * (1- Alpha) + Target * Alpha) and I think it's working better.

I just don't know if I should submit this in a pull request since it's a change in the way animation mixing works, and maybe other people prefer the current way... what do you think?

**Comment by Xelnath** [comment]
Did this ever get resolved?

**Comment by Fenrisul** [comment]
No.  Working as intended.  Just like everything else in the Unity animation ecosystem.

**Comment by Xelnath** [comment]
Specifically, I was curious if support was added for mixing a track away rather than just removing it.
