### ISSUE TITLE
How can I build spine-c or spine-cpp as .dll?

### ISSUE THREAD

**Issue by halx99** [EsotericSoftware/spine-runtimes#1571]

**Comment by badlogic** [comment]
That depends on your build system We provide `CMakeLists.txt` for spine-cpp which should allow you to generate the necessary files for your build system. You will have to adjust the `STATIC` linkage here https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-cpp/CMakeLists.txt#L14.

**Comment by halx99** [comment]
but when I change to SHARED, it will cause link error:
![image](https://user-images.githubusercontent.com/6977319/70852884-8d944200-1ee1-11ea-9e6d-46d47140d356.png)

**Comment by badlogic** [comment]
This should help
http://esotericsoftware.com/spine-cpp#Integrating-spine-cpp-in-your-engine

**Comment by halx99** [comment]
So I should modify Extension.cpp or add a new cpp and put to spine-cpp/src/spine to implement   like follow:
![image](https://user-images.githubusercontent.com/6977319/70853443-2a0e1280-1ee9-11ea-9ca5-4956bb946b16.png)

**Comment by badlogic** [comment]
Looks about right.

**Comment by halx99** [comment]
I think, when build as shared, implement it at Extension.cpp may be better
```
SpineExtension* spine::getDefaultExtension()
{
	static DefaultSpineExtension s_defaultSpineExtension;
	return &s_defaultSpineExtension;
}
```

**Comment by badlogic** [comment]
I see a cocos2d-x file there. Check out the spine-cocos2dx runtime in this
GitHub repository. No need to implement it yourself.
