### ISSUE TITLE
Unreal Engine 23 does not work with Spine Runtime

### ISSUE THREAD

**Issue by whybother2** [EsotericSoftware/spine-runtimes#1573]
I am able to get Spine Runtime working with Unreal v21 but not v22 / v23 / v24.
Unreal Engine complains about not being able to compile the plugin.  Is this a known issue or is it planned to be updated soon?

**Comment by badlogic** [comment]
Please post the exact error you are getting. I assume you use the latest sources from our 3.8 branch?

**Comment by badlogic** [comment]
Our spine-ue4 example project from this repository's 3.8 branch is a UE 4.23 project. I just compiled it without issue, including the plugin, on Windows.

Please post additional information, such as your platform, and the exact error.
