### ISSUE TITLE
[corona] Animation layering not working correctly

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1574]
See http://esotericsoftware.com/forum/Animation-layering-doesn-t-work-in-Corona-13204?p=58512#p58512

**Comment by imikh** [comment]
Hi, @badlogic, any updates on this bug? Unfortunately it blocks our development.

**Comment by DonBanan** [comment]
@badlogic @imikh I also have encountered a problem. Any news?
