### ISSUE TITLE
[cocos2dx v4]Incorrect display with spine runtimes 3.8 for cocos2dx v4

### ISSUE THREAD

**Issue by coldwinter2** [EsotericSoftware/spine-runtimes#1579]
Use the spine file in example-v4
Sometimes, it's looks perfect. But ，Occasionally, the following figure will appear.

![TIM截图20191218224100](https://user-images.githubusercontent.com/4240994/71095407-82922800-21e7-11ea-8dfe-89c4af49defe.png)

**Comment by badlogic** [comment]
What operating system are you testing this on?

**Comment by coldwinter2** [comment]
> What operating system are you testing this on?

WIndows 10 1903

I can't remember which commit I used to.  After update to the latest commit 
( commit b67bf99) for cocos2dx-v4, this problem hasn't reappeared.

**Comment by badlogic** [comment]
I couldn't repro with the latest cocos2d-x commits either.
