### ISSUE TITLE
[ts] Force mime type for .atlas files

### ISSUE THREAD

**Issue by Nashorn** [EsotericSoftware/spine-runtimes#1583]
Hi,
when testing locally, there is an annoying "XML Parsing Error: syntax error" for atlas files being loaded by XMLHttpRequest. I was able to resolve these by setting the request.overrideMimeType();  ex:

var request = new XMLHttpRequest();
request.overrideMimeType("text/html");

I tested in a few method calls in the spine-js runtime and it works fine. Could we get this fixed?

**Comment by badlogic** [comment]
I've added this fix to `AssetManager` and `SharedAssetManager` in both the 3.8 and 3.9-beta.
