### ISSUE TITLE
[win32] compile error in cocos2dx-v4

### ISSUE THREAD

**Issue by codetypess** [EsotericSoftware/spine-runtimes#1585]
1>SkeletonBounds.cpp
1>G:\cocos-lua\frameworks\cocos2d-x\cocos\editor-support\spine\SkeletonBounds.cpp(130): error C2872: “Polygon”: 不明确的符号
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\wingdi.h(5127): note: 可能是“BOOL Polygon(HDC,const POINT *,int)”
1>G:\cocos-lua\frameworks\cocos2d-x\cocos\editor-support\spine/SkeletonBounds.h(93): note: 或    “spine::Polygon”
1>G:\cocos-lua\frameworks\cocos2d-x\cocos\editor-support\spine\SkeletonBounds.cpp(130): error C2065: “polygon”: 未声明的标识符
1>G:\cocos-lua\frameworks\cocos2d-x\cocos\editor-support\spine\SkeletonBounds.cpp(130): error C2062: 意外的类型“float”
1>G:\cocos-lua\frameworks\cocos2d-x\cocos\editor-support\spine\SkeletonBounds.cpp(130): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>G:\cocos-lua\frameworks\cocos2d-x\cocos\editor-support\spine\SkeletonBounds.cpp(130): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)

The name Polygon(spine:: Polygon) is conflicted the win function Polygon of 'BOOL Polygon(HDC,const POINT *,int)'

**Comment by badlogic** [comment]
Thanks for reporting, this is fixed in the 3.8 and 3.9-beta branches.
