### ISSUE TITLE
[ts] Skin.attachAll: empty skin placeholders wont be reattached after a skin change

### ISSUE THREAD

**Issue by modjke** [EsotericSoftware/spine-runtimes#1586]
Exactly what title says
Steps to reproduce:
Spine with at least two skins
Skin A: skin placeholder with no attachement
Skin B: above skin placeholder, but with attachement
```
setSkinByName('Skin A')
setSkinByName('Skin B')
```
Skin attachement will not be attached and will not be visible

https://github.com/EsotericSoftware/spine-runtimes/blob/12897260d72d1d8458d1288101086bf2c4ec1a28/spine-ts/core/src/Skin.ts#L182

**Comment by modjke** [comment]
https://github.com/EsotericSoftware/spine-runtimes/pull/1587

**Comment by NathanSweet** [comment]
Appears to have been resolved in #1587.
