### ISSUE TITLE
[unity] `Universal Render Pipeline/2D/Spine/Sprite` negative scaleX loses normal-map functionality

### ISSUE THREAD

**Issue by Jamez0r** [EsotericSoftware/spine-runtimes#1591]
Flipping the skeleton animation by setting scaleX to negative number causes it to lose normal-map functionality.

Note: setting the GameObject's scale to a negative number does not break the normal-map functionality.

**Repro project:** https://drive.google.com/open?id=14rF3WqBZz2zYOgFGJ8gnGCy9y_Dh6GhY

-Project uses the updated shader from after this issue was fixed: https://github.com/EsotericSoftware/spine-runtimes/issues/1588
-Run the project and press "p" to flip the character

**Forum post** (bottom comments section): 
http://esotericsoftware.com/forum/URP-Shaders-lights-configuration-question-13262?sid=c7d7cd708ca5f8c384346608941c1e2c

**Comment by Jamez0r** [comment]
**Additional info:**

[How it looks without being flipped (correctly using the normal-map)](https://i.imgur.com/iXYLhaW.png)

[How it looks with "Initial Flip X" selected (lit as though it didn't have a normal-map)](https://i.imgur.com/Z5UJhFX.png)

[Material settings (note, it says "Material requires a mesh with Normals and Tangents" whether or not it is flipped)](https://i.imgur.com/KNKqCh0.png)

[Normal Map settings, in case it matters](https://i.imgur.com/Ba9rA0o.png)

**Comment by HaraldCsaszar** [comment]
Thanks for reporting! The issue has been fixed, new URP Shaders UPM packages have been uploaded.

You can download them here as usual:
http://esotericsoftware.com/spine-unity-download
