### ISSUE TITLE
[unity] Support multiple atlas textures at SkeletonGraphic

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1592]
Requested on this forum thread:
http://esotericsoftware.com/forum/SkeletonGraphic-with-multiple-atlases-11647

Related to this issue ticket:
https://github.com/EsotericSoftware/spine-runtimes/issues/1316

**Comment by thsbrown** [comment]
Any chance this could come with the ability to scale SkeletonGraphic as well?

This issue here pretty much lays it out http://esotericsoftware.com/forum/Unity-UI-scaling-with-Spine-objects-11049?p=60194#p60194

**Comment by HaraldCsaszar** [comment]
Thanks for the request @thsbrown, there is now a separate issue ticket here:
https://github.com/EsotericSoftware/spine-runtimes/issues/1640
