### ISSUE TITLE
[unity] `Universal Render Pipeline/2D/Spine/Sprite` flipped-x sprite with normal-map is lit backwards on x-axis

### ISSUE THREAD

**Issue by Jamez0r** [EsotericSoftware/spine-runtimes#1597]
Skeleton Animation now keeps normal-map when flipped on x-axis (either through "Initial Flip X" or by ScaleX = -1), but the resulted lighting is backwards on the x-axis. 

[Screenshot of issue](https://i.imgur.com/IHXkZeM.png)

[Repro Project](https://drive.google.com/open?id=1fsIU4Dm-i3B8_661xSE8NYgMyJlvSxAj)

[Forum Post](http://esotericsoftware.com/forum/URP-Shaders-lights-configuration-question-13262?p=58879#p58879)

Thanks!

**Comment by HaraldCsaszar** [comment]
Thanks for reporting!

The screenshot posted in the description shows that in your configuration has `Solve Tangents` disabled, which will lead to incorrect normalmap orientation during animation, as well as when flipped.
Please enable `Solve Tangents` at `SkeletonRenderer` components when using normalmaps.
