### ISSUE TITLE
[unity] Building for platforms results in compiler warning CS0414

### ISSUE THREAD

**Issue by seansaleh** [EsotericSoftware/spine-runtimes#1604]
When building a Unity game with the Spine runtime I receive a compiler warning:
`Assets\Spine\Runtime\spine-unity\Asset Types\SkeletonDataCompatibility.cs(43,15): warning CS0414: The field 'SkeletonDataCompatibility.wasVersionDialogShown' is assigned but its value is never used`

This is because in [SkeletonDataCompatibility.cs](https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-unity/Assets/Spine/Runtime/spine-unity/Asset%20Types/SkeletonDataCompatibility.cs) [`static bool wasVersionDialogShown`](https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-unity/Assets/Spine/Runtime/spine-unity/Asset%20Types/SkeletonDataCompatibility.cs#L42) is only used within code blocked off by [`#if UNITY_EDITOR`](https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-unity/Assets/Spine/Runtime/spine-unity/Asset%20Types/SkeletonDataCompatibility.cs#L73). Therefore building the game other than for `UNITY_EDITOR` will cause a warning.

To fix this I've added `#pragma warning disable CS0414 // Remove unused private members warning disabled. Warns when built for not UNITY_EDITOR` and `#pragma warning restore CS0414` around [`static bool wasVersionDialogShown`](https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-unity/Assets/Spine/Runtime/spine-unity/Asset%20Types/SkeletonDataCompatibility.cs#L42)

Can you help us remove compiler warnings by fixing this upstream?

**Comment by HaraldCsaszar** [comment]
We have just fixed the warning via adding `#if UNITY_EDITOR` guards around the static variables. Thanks for reporting.

**Comment by seansaleh** [comment]
Thanks! That works too :)
