### ISSUE TITLE
[cocos2d-x] Memory leaks on initialize

### ISSUE THREAD

**Issue by Volodar** [EsotericSoftware/spine-runtimes#1605]
When reinitializing, a memory leak occurs:

```
void SkeletonAnimation::initialize () {
...
_state = new ...
...
}
````

When necessary change skeleton (json) the already created SkeletonAnimation - memory allocation without delete early allocated.

**Comment by badlogic** [comment]
Sorry, I'm having troubles understanding what you are trying to achieve. You are calling `SkeletonAnimation::initialize()` twice? What's the use case for this? As I understand the cocos2d-x API contract for that method, it's only supposed to be called once. I can of course add a check for preexisting allocated memory and release it upon additional `initialize()` calls.

**Comment by badlogic** [comment]
I've looked into this a little closer now. The `initWithXXX` functions are not supposed to be called multiple times on the same instance. Please simply allocate a new node if you need to modify the skeleton powering the `SkeletonRenderer` or `SkeletonAnimation`.
