### ISSUE TITLE
[unity] Texture quality setting `Half Res` causes incorrect image regions

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1609]
As reported on the forum (including reproduction package):
http://esotericsoftware.com/forum/Sprite-Attacher-Sprites-Only-Half-Render-13361

Reproducible on Unity 2019.3.
Does not occur on Unity 2019.2.
Does not occur on Unity 2017.1.

**Comment by HaraldCsaszar** [comment]
Could be a bug in `Graphics.CopyTexture()` overload with region parameter in Unity 2019.3 when `QualitySettings-masterTextureLimit > 0`. The region checks do not allow a larger area, `mipMap` parameter does not allow for srcMip==1 on texture without mipmaps.

When calling `Graphics.CopyTexture()` simple overload without region parameter, the correct region is copied.

**Comment by AnthonyUccello** [comment]
I opened a bug with Unity as I suspected this exact same thing (a bug in CopyTexture). Here is the bug:
https://fogbugz.unity3d.com/default.asp?1214481_c0lmc52ptf43qjc7

**Comment by HaraldCsaszar** [comment]
Thanks very much @AnthonyUccello, very much appreciated!

**Comment by HaraldCsaszar** [comment]
Another minimal bug report issued for Unity:
https://fogbugz.unity3d.com/default.asp?1215135_osdh4nkb8rv9n59p

**Comment by HaraldCsaszar** [comment]
Closing since the cause seems to reside on Unity side and no workaround is currently possible (see second comment above).
