### ISSUE TITLE
[lua] Wrong size calculation for animation frames

### ISSUE THREAD

**Issue by KoiKoi2000** [EsotericSoftware/spine-runtimes#1611]
![image](https://user-images.githubusercontent.com/18212837/73544966-995ca900-443a-11ea-82ae-5bebfe44dfa7.png)

Animation.lua // line 1375
			local i = zlen(frames.length)
must be:
			local i = zlen(frames)

**Comment by badlogic** [comment]
Thank you for reporting. This has been fixed in both the 3.8 and 3.9-beta branch.
