### ISSUE TITLE
Spine 3.8.82 PRO: Error "y lies outside the raster" exporting when stripping whitespace

### ISSUE THREAD

**Issue by Eyesiah** [EsotericSoftware/spine-runtimes#1613]
Hello,
Today we found that Spine wouldn't even load and demanded it be reinstalled to a new version. When we did that, projects that used to export fine now give the following error:

`java.awt.image.RasterFormatException: y lies outside the raster
	at java.desktop/sun.awt.image.ByteInterleavedRaster.createWritableChild(Unknown Source)
	at EH.<init>(SourceFile:38)
	at Er.S(SourceFile:49)
	at Ei.C(SourceFile:209)
	at Ei.S(SourceFile:96)
	at Ei.S(SourceFile:88)
	at EI.S(SourceFile:148)
	at Eq.S(SourceFile:96)
	at DT.S(SourceFile:255)
	at Ea.S(SourceFile:218)
	at DT.S(SourceFile:56)
	at DT.S(SourceFile:162)
	at BW.S(SourceFile:86)
	at Aa.run(SourceFile:665)
	at java.base/java.lang.Thread.run(Unknown Source)`

These projects have many sprites with whitespace in them, so we use the 'Strip Whitespace X/Y' options to reduce the number of texture atlases (from 18 atlases to 8 at 4096x4096 to give you a sense of the size of this project). When i disable 'Strip Whitespace', the error no longer happens.

If you want the project to debug, let me know where to send a link to it.
Thanks!

**Comment by badlogic** [comment]
Sorry for the forced update. It was necessary due to a certificate that is about to expire in the near future. That said, the update only concerned the Spine launcher, the app that allows you to select a specific Spine Editor version. Did you also uodate your Spine Editor version? If so, from what version to what version?

**Comment by badlogic** [comment]
I have moved this issue over to the spine-editor tracker. Please subscribe to the issue there: https://github.com/EsotericSoftware/spine-editor/issues/527

**Comment by Eyesiah** [comment]
Yes, we updated the editor. Unfortunately I'm not sure what version we had before, though it was 3.8.x. We got this message when starting up:
http://esotericsoftware.com/spine-reinstallation
So we re-downloaded and reinstalled it as instructed.

Apologies about reporting in the wrong git project.

**Comment by NathanSweet** [comment]
Fixed in 3.8.83 (available in a few minutes).

**Comment by badlogic** [comment]
@Eyesiah no worries about reporting it on the wrong tracker, we're glad people take their time to report issues! Give 3.8.83 a try and let us know if that now works for you.

**Comment by Eyesiah** [comment]
Yup, my animator says it's fixed! thanks very much.
