### ISSUE TITLE
[starling] Texture Packer Rotation

### ISSUE THREAD

**Issue by llorenzo** [EsotericSoftware/spine-runtimes#1617]
When rotation is allowed in Texture Packer, Spine rendering is off. Without rotation the rendering is fine.
Related classes : StarlingAtlasAttachmentLoader & RegionAttachment
Packing size is increased a lot due to this bug.

**Comment by badlogic** [comment]
Files to reproduce the issue: https://www.dropbox.com/s/jef18hpkcnytdmf/Test-Spine-TP-Rotation.zip?dl=0

Forum thread: http://esotericsoftware.com/forum/starling-mesh-attachment-issue-with-allow-rotation-checked-8478

**Comment by llorenzo** [comment]
Well, it feels more like a bug than an enhancement. Anyway, in my current project it is a necessity. Please look after that. Thanks

**Comment by badlogic** [comment]
I'm sorry, we have discontinued spine-starling and are therefore closing this issue.
