### ISSUE TITLE
[cpp] Memory leak in SkeletonBounds

### ISSUE THREAD

**Issue by DevJ0049** [EsotericSoftware/spine-runtimes#1623]
Polygons which allocated and stored in _polygonPool vector gets never deleted causing memory leaks.

**Comment by badlogic** [comment]
Please tell us which runtime you are talking about.

**Comment by DevJ0049** [comment]
Oh, sorry. It is spine-cpp

**Comment by badlogic** [comment]
Cheers! I've fixed this up without pulling in your PR. Live on both the 3.8 and 3.9-beta branches.
