### ISSUE TITLE
[as3] Path constraint not working

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1625]
As per forum, the tank example shows the issue, the chains are not moving.

http://esotericsoftware.com/forum/Starling-Path-Constraint-not-working-13537

**Comment by llorenzo** [comment]
Hi, is this planed anywhere in the near future? Our animation desiger is waiting for a go to use path animations. Thx.

**Comment by llorenzo** [comment]
Could it be a simple spelling mistake?
In the class SkeletonJson around line 624 it looks for the string "paths".
I found that it should be "path" instead.
```
			var paths : Object = map["path"];
//			var paths : Object = map["paths"];
```
That makes path constraints working.
I have not testet everything though.
