### ISSUE TITLE
[unity] Prefab with `SkeletonRenderSeparator` constantly loading in editor

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1626]
Originally reported by @fvfreedom in this issue ticket:
https://github.com/EsotericSoftware/spine-runtimes/issues/1273

Selecting a prefab asset with a `SkeletonRenderSeparator` component in the project panel will load repeatedly.

Originally reported occurring on Unity 2018.4.17, reproduced also on 2019.3.

**Comment by TowerCrow** [comment]
looking forward to this fix.

**Comment by HaraldCsaszar** [comment]
New unitypackages including the bugfix are now available. Sorry for the long delay. Thanks for reporting!
