### ISSUE TITLE
[unity] 2D Hinge Chain rotation issue (repro project)

### ISSUE THREAD

**Issue by Jamez0r** [EsotericSoftware/spine-runtimes#1636]
2D Hinge Chains "freaking out" during specific animations - from this thread: http://esotericsoftware.com/forum/Video-Issue-with-2D-Hinge-Chain-Or-my-setup-13523?sid=0ca1c62e5cfb9aff38ef9d5cd1932f6e

Unity Project: https://drive.google.com/open?id=1_HRNhDwV9H2YvYRk0PhdqOfUrTwHUVaD
Spine Project: https://drive.google.com/open?id=1Jk4if6Y9TTtNDXdaWqw9gOhCXoCleJHm

Note: Run the game in Unity and then press Spacebar to set the animation to one that shows the problem (see "Test Sandir" script)

Thanks!

**Comment by HaraldCsaszar** [comment]
Thanks for reporting and the repro project!

**Comment by HaraldCsaszar** [comment]
Unfortunately this seems to be a bug with the Joint2D behaviour. While they behave normally at the start, when disabled and re-enabled, joints with certain angles suddenly start rotating by 360 degrees, as if min/max angle limits were setup incorrectly by +-360 degrees.

This occurs on all tested Unity versions, 2017.1 - 2020.1.
A Unity bug has been reported:
https://fogbugz.unity3d.com/default.asp?1271399_ncbdfioakuikacak

Unfortunately the angle-related behaviour is more complex than initially expected, so any workaround compensation scripts that test the current angle failed to work in all circumstances. Unfortunately we have to close the issue until we receive any feedback from Unity.
