### ISSUE TITLE
[as3] Curve animation not always working

### ISSUE THREAD

**Issue by llorenzo** [EsotericSoftware/spine-runtimes#1639]
I guess there are some bugs in the class SkeletonJson in the function readCurve().

`if (!curve) return;` returns when curve has the value 0.
It should only return when it is undefined:
`if (curve == null) return;`

Similar things happen in the same function in the else satement a little down.
`map["c2"] || 0 `will work since it returns a default of 0 when map["c2"] has the value of 0 (false).
`map["c3"] || 1` does not work. It returns a value of 1 when map["c3"] has the value of 0 (false).

So really it should be something like:
`timeline.setCurve(frameIndex, parseFloat(curve.toString()), Number(map["c2"] == null?0:map["c2"]), Number(map["c3"] == null?1:map["c3"]), Number(map["c4"] == null?1:map["c4"]));`

**Comment by badlogic** [comment]
Uff, good catch(es). Fixed in 3.8 and 3.9-beta!
