### ISSUE TITLE
[ts] Make AnimationStateListener methods optional

### ISSUE THREAD

**Issue by jramstedt** [EsotericSoftware/spine-runtimes#1642]
Currently you have to implement all listeners even if you only wan't to add one.
Making the methods optional (like in Java implementation) only the desired listeners would be needed to be implement.

**Comment by badlogic** [comment]
If you are using `TypeScript` with the runtime, you can extends `AnimationStateListenerAdapater` to only implement the methods you want. If you are using `JavaScript`, then you can just create a JS object with the methods you need:

```TypeScript
animationState.setListener({
   complete(entry) { alert("Animation completed."); }
})
```
