### ISSUE TITLE
[cocos2dx] Debug draw doesn't display correctly if global Z value is not 0

### ISSUE THREAD

**Issue by rh101** [EsotericSoftware/spine-runtimes#1655]
In `SkeletonRenderer::drawDebug`, the drawNode defaults to a global Z of 0, but if the spine animation is using a higher global Z value, then the draw node items will be displayed behind the animation.  

Simple fix is to set the DrawNode global Z to what the current animation global Z value is set to:

```
	void SkeletonRenderer::drawDebug (Renderer* renderer, const Mat4 &transform, uint32_t transformFlags) {
...
		DrawNode* drawNode = DrawNode::create();
		drawNode->setGlobalZOrder(getGlobalZOrder());  // add this line
...
}
```

**Comment by badlogic** [comment]
Cheers! Fixed in 3.8 and 3.9-beta.
