### ISSUE TITLE
[JavaScript] When `timeScale<0` , the Event can't be emit correctly

### ISSUE THREAD

**Issue by finscn** [EsotericSoftware/spine-runtimes#1656]
I use the last version of spine-runtimes (js version).
When timeScale<0  ( play the animation reversely) , 
there is only `EventType.start` could be emit correctly ,
the `EventType.end` & `EventType.complete` can't be emit.

**Comment by badlogic** [comment]
`TrackEntry` or `AnimationState``timeScale` may not be < 0 in Spine Runtimes <= 3.8. We do have an experimental `reverse` flag on `TrackEntry` in the 3.9-beta Java reference implementation. But neither the 3.9-beta editor nor the other 3.9-beta runtimes have been updated or published yet.

For the time being, I suggest to create a reverse animation in the Spine Editor.

**Comment by finscn** [comment]
@badlogic   , Is there a tool for reversing  an animation in the  Spine Editor ?

**Comment by erikari** [comment]
@finscn Hello! Here's how you can reverse an animation in Spine:
1. In animate mode, use the pose tool to select all the bones and meshes you may have.
2. On the timeline select all the keyframes by clicking in a place where there are no keyframes and then dragging the mouse to select everything. Just the first row it's fine, it will select everything else by itself.
3. The selected area should be blue now, look at the timing, let's say you have a 30 frames animation, go to the left border of your selection the cursor should change to a double arrow, click and drag forward to frame 60 (double your number of frames). Now your animation plays backwards, (in your case, it will play fine)
4. click in the middle of the selection to drag all the frames back to the first frame.
If you have curves you'll have to manually reverse them, but we're working on a new graph editor.

**Comment by finscn** [comment]
@erika Thank you very much.
