### ISSUE TITLE
[JavaScript] if `timeScale<0` , when the animation's  finished playing, the last frame is wrong

### ISSUE THREAD

**Issue by finscn** [EsotericSoftware/spine-runtimes#1657]
I use the last version of spine-runtimes (js version).
If timeScale<0 ( play the animation reversely) ,
when the animation's  finished playing,  the animation  can not stop at   the first frame.
It's become the default Skeleton.  ( as same as  don't set any animation)

**Comment by badlogic** [comment]
Do you have a reproduction sample for me to see the issue?

**Comment by badlogic** [comment]
TrackEntry or AnimationState``timeScale may not be < 0 in Spine Runtimes <= 3.8. We do have an experimental reverse flag on TrackEntry in the 3.9-beta Java reference implementation. But neither the 3.9-beta editor nor the other 3.9-beta runtimes have been updated or published yet.

For the time being, I suggest to create a reverse animation in the Spine Editor.
