### ISSUE TITLE
[unity] SkeletonMecanim indexing error during transition interruption

### ISSUE THREAD

**Issue by Jamez0r** [EsotericSoftware/spine-runtimes#1658]
Getting this index out of range error:

![mecanim_error](https://user-images.githubusercontent.com/3651077/79825745-ea0fde00-8367-11ea-99c9-81d4e2cedd3d.png)

This is the section of code for SkeletonMecanim:

**The error is on the line:**
`var info = interruptingClipInfo[c];`

![mecanim_code section](https://user-images.githubusercontent.com/3651077/79825757-f431dc80-8367-11ea-87c2-e84e1e53c036.png)

I added two debug lines of code there - the top line, interruptingClipInfoCount logs as 2. The bottom line interruptingClipInfo.Count logs as 1.

This is my simple animator, it just goes from an "idle" animation to a "moving" blend tree animation:

![mecanim_animator transition](https://user-images.githubusercontent.com/3651077/79825763-f85dfa00-8367-11ea-8a23-19079700b7e4.png)

The transition from Idle to Moving Blend Tree has a transition duration of 0.1.
The transition from Moving Blend Tree back to idle has a transition duration of 0.35.

The transitions are triggered by the players velocity (pressing WASD to move the character, and then releasing to transition back to idle). 

The error only seems to happen when I press and release the WASD quickly. My thoughts are that the transition from Moving Blend Tree back to Idle is triggered, and then while that transition is being processed (0.35 second transition), the interrupting transition from Idle back to Moving Blend Tree is triggered multiple times (by pressing and releasing WASD quickly).

Maybe "interruptingClipInfoCount" is counting the total interrupts, but interruptingClipInfo.Count sees that it was the same Clip/State that caused the multiple interrupts and only counts it as 1?

Also worth mentioning that the Moving Blend Tree is indeed a Blend Tree, in case that makes a difference.

Thanks =)

Edit: Package version: spine-unity-3.8-2020-04-07.unitypackage

**Comment by HaraldCsaszar** [comment]
Thanks for reporting! 

Unfortunately I could not reproduce the issue. Could you please send us a minimal reproduction package? Then we can be sure that any codechanges really fix the problem.

**Comment by Jamez0r** [comment]
Emailed repro 👍

**Comment by HaraldCsaszar** [comment]
The issue has just been resolved, a new 3.8 unitypackage is available for download.

Another issue was (accidentally) filed under this ticket id: https://github.com/EsotericSoftware/spine-runtimes/issues/1661
