### ISSUE TITLE
[unity] The type or namespace name could not be found

### ISSUE THREAD

**Issue by TowerCrow** [EsotericSoftware/spine-runtimes#1666]
http://esotericsoftware.com/forum/The-type-or-namespace-name-could-not-be-found-13878?p=61290#p61290

**Comment by HaraldCsaszar** [comment]
Problem could not be reproduced directly, but a potential problem has been resolved, a new unitypackage is available on the download page as usual.

**Comment by TowerCrow** [comment]
This appears to be fixed in 2019.3.13.

**Comment by HaraldCsaszar** [comment]
Thanks for the info @TowerCrow, we can confirm that.
