### ISSUE TITLE
How can I import a old version of binary to skeleton viewer?

### ISSUE THREAD

**Issue by K7cl** [EsotericSoftware/spine-runtimes#1667]
I got an old version(3.2.01) of binary file, how can i import it to skeleton viewer? Where can i found a suitable version? i am using spine trial, so I can not import it to spine and export a higher version. Thanks!

**Comment by badlogic** [comment]
You'll have to checkout a commit for spine-runtimes version 3.2, then compile spine-libgdx and spine-libgdx-tests which has SkeletonViewer in it. Both projects are Java projects. I think 3.2 was before I added Maven support, so you might have to import them as Eclipse projects into Eclipse, and also checkout libGDX from sources and import that. I'm afraid we do not have that version of SkeletonViewer around anymore :/

**Comment by K7-Lenovo** [comment]
thanks.
my final goal is use it in web project, but i found there where no spine-ts or webgl in 3.2. Do I have to upgrade the file version? what can I do next with only v3.2 binary file got?

**Comment by K7cl** [comment]
> You'll have to checkout a commit for spine-runtimes version 3.2, then compile spine-libgdx and spine-libgdx-tests which has SkeletonViewer in it. Both projects are Java projects. I think 3.2 was before I added Maven support, so you might have to import them as Eclipse projects into Eclipse, and also checkout libGDX from sources and import that. I'm afraid we do not have that version of SkeletonViewer around anymore :/

thanks.
my final goal is use it in web project, but i found there where no spine-ts or webgl in 3.2. Do I have to upgrade the file version? what can I do next with only v3.2 binary file got?
