### ISSUE TITLE
[runtimes] Skeleton scale seems to be applied twice to some bones

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1668]
Reported on the forum:
http://esotericsoftware.com/forum/Problem-with-scale-skeleton-with-Unity-runtime-13895

Reproducible in spine-unity and also in spine-libgdx via SkeletonViewer, using e.g. `Spineboy` or `Hero` example project.

Steps to reproduce:
- start SkeletonViewer.
- open exported `Spineboy` project.
- via the SkeletonViewer GUI, set `Scale X` and `Scale Y` to `200%`.
- observe `rear-foot` and `front-foot` being scaled more than 2x (looks like 4x).

Potential problem location:
When commenting out these lines the issue is no longer visible:
https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Bone.java#L200-L203

Remarks:
Seems to be not related to constraints, as deleting constraints from the project before exporting does not resolve or affect the issue.

**Comment by madlexus** [comment]
New issue happened! Bones are breaking when set Skeleton.ScaleX to negative value, eg for mirroring...

**Comment by NathanSweet** [comment]
@madlexus Thanks, you're right! We've got a fix and will port to all runtimes ASAP.

**Comment by HaraldCsaszar** [comment]
@madlexus Thanks for reporting! A new 3.8 unitypackage with the bugfix is available for download: http://esotericsoftware.com/spine-unity-download

**Comment by badlogic** [comment]
Fixed in all runtimes.

**Comment by wang606** [comment]
Sorry, but I seem to have encountered this problem again. When I open this asset with the latest SkeletonViewer-4.1, I find that her calf scaling is applied twice. I am not sure if it is a problem with my asset or a problem with the runtime. (I have quite a few assets with this problem)

100%：

<img width="1920" height="1050" alt="Image" src="https://github.com/user-attachments/assets/b165df3c-d8dd-4b11-b8b0-3a936990aca1" />

50%：

<img width="1920" height="1050" alt="Image" src="https://github.com/user-attachments/assets/a9f6fed9-c197-4033-8ad4-0ed9cb1722da" />

150%：

<img width="1920" height="1050" alt="Image" src="https://github.com/user-attachments/assets/b38b532c-fd2f-4d2c-9fc9-7d257c48b0f6" />

[Skeleton scale seems to be applied twice to some bones again.zip](https://github.com/user-attachments/files/21602835/Skeleton.scale.seems.to.be.applied.twice.to.some.bones.again.zip)

**Comment by wang606** [comment]
Case closed — it was an issue with my assets. I suspect these assets were created using a runtime in which that bug hadn’t been fixed yet.
