### ISSUE TITLE
how to mix different tracks at the point of animation end

### ISSUE THREAD

**Issue by drelaptop** [EsotericSoftware/spine-runtimes#1669]
#### version: 
  - spine 3.8 cpp
#### situation: 
  - assume existed 2 animation,`idle` and `attack`
  -  play animation `idle` at track 0 with loop
  -  play `attack` at track 1 when the `idle` playing
  - when the `attack` animation end, not smoothly

any advice will be appreciated!

> also empty animation have added at track 1 after play `attack`, but the `attack` didn't mixed with `idle` well.

**Comment by badlogic** [comment]
Hey, could I ask you to ask this on the forums at https://esotericsoftware.com/forum? That way other people have an easier time finding an answer to the question. The issue tracker is reserved for requests for enhancements and bugs.
