### ISSUE TITLE
[TS] Skin bone bug

### ISSUE THREAD

**Issue by smaren** [EsotericSoftware/spine-runtimes#1673]
Bug: bone properties are not reset to their setup pose

Steps to reproduce:
1. Have an active skin with a skin bone
2. Play an animation that keys a property on the skin bone

3. Swap to a skin without the skin bone
4. Play an animation that does not key the skin bone

5. Set the skin with the skin bone active again
 -  The skin bone still has the keyed properties, and is not in setup pose as it should be.

**Comment by badlogic** [comment]
This is actually working as intended. There's no way for the runtime to decide what state you want things in after the sequence of actions you describe. You can either queue a new animation with the skin bone keyed, or explicitely set things back to setup pose.
