### ISSUE TITLE
JavaFX support

### ISSUE THREAD

**Issue by addstone** [EsotericSoftware/spine-runtimes#1682]
spine-runtimes is supported by javafx ?

**Comment by badlogic** [comment]
I'm afraid Spine does not support JavaFX nor do we have any short or mid term plans to support it. That said, the spine-libgdx runtime is Java based, and contains the core API that is rendering independent. You could take that and build a renderer for JavaFX on top of it. The renderer would have to be able to draw textured triangle meshes with blending. I'm not sure if that's possible in JavaFX.
