### ISSUE TITLE
[as3] Wrong error message in Atlas class constructor

### ISSUE THREAD

**Issue by PByH** [EsotericSoftware/spine-runtimes#1684]
Hello.

Class "Atlas" (flash version)
line 48: throw new ArgumentError("object must be a TextureAtlas or AttachmentLoader.");

As far as I understand there is no way to put TextureAtlas as an argument into Atlas constructor. It should be String or ByteArray.

Thanks!

**Comment by badlogic** [comment]
Good catch, fixed!
