### ISSUE TITLE
Cocos Creator runtime - animation timing is linear instaed of Bezier

### ISSUE THREAD

**Issue by balazsnemeth** [EsotericSoftware/spine-runtimes#1685]
We built a coin effect in Spine 3.8:
https://www.dropbox.com/s/j7qysr2esdc1fyp/bwcoin_demo.mp4?dl=0

We exported it (atlas + JSON + png) format, and tested in Cocos Creator v2.3.1, v2.3.4 and v2.4.0-rc1, but all the animation keyframe become linear instead of bezier regardless the version:
https://www.dropbox.com/s/6xpjed5ckdpi1ih/bwcoin_problem_linear_timing.mov?dl=0

However the web runtime does play it correctly, here is a very short test:
http://runiosit.com/coins/

Is this maybe a bug in cocos-spine runtime?

I'm tagging folks working with Spine runtime and CocosCreator, may one of them can help efficiently: @jareguo, @sunnylanwanjun

**Comment by jareguo** [comment]
Hi, I saw your post in Creator forum. Could you send the exported demo so we can check them out?

**Comment by balazsnemeth** [comment]
Sure, here is the exported demo animation in .zip:
[coins.zip](https://github.com/EsotericSoftware/spine-runtimes/files/4709622/coins.zip)

**Comment by jareguo** [comment]
Please check out https://github.com/cocos-creator/engine/pull/6798 , the spine runtime is upgraded to a recent version.

After upgrade https://www.dropbox.com/s/10shu9obgit4l8j/Screen%20Recording%202020-06-01%20at%205.33.32%20PM.mov?dl=0

**Comment by badlogic** [comment]
@jareguo thanks for the fix! closing this out.
