### ISSUE TITLE
[libgdx] Release spine-libgdx 3.8.95 to Maven Central

### ISSUE THREAD

**Issue by FStranieri** [EsotericSoftware/spine-runtimes#1687]
Hi,
I've the spine editor version 3.8.95 but the latest gradle dependency for spine runtimes is minor than 3.8.95.

**Comment by badlogic** [comment]
Sorry for that, we haven't released that version to Maven Central yet.

**Comment by FStranieri** [comment]
Hi, thanks for the answer.
When will it be released? Because we're stuck with the editor version 3.8.95 and its exports are not compatible with our spine runtimes 3.8.55.1 . 
Thanks

**Comment by rizmaulana** [comment]
Hi, 
Meanwhile waiting for libgdx-3.8.95 published into maven central, is any workaround that can solve this issue https://github.com/EsotericSoftware/spine-runtimes/issues/1485 on libgdx-3.8.55.1 ?

**Comment by quarzoq** [comment]
Hi guys i have the same request, is posible update this to maven central?

**Comment by soundasleep** [comment]
Another vote for a release please! I'm trying to connect up `SkeletonDataParameter` but it [doesn't exist in 3.8.55.1](http://en.esotericsoftware.com/forum/Libgdx-AssetManager-for-Spine-Stuff-15024?sid=998e4f4d11178cf18e63589fec3345e0&p=66197#p66197)

**Comment by badlogic** [comment]
spine-libgdx 3.8.99.1 has been released to Maven Central. Currently synching. Should be available soon.
