### ISSUE TITLE
[runtimes] Fix 1-bone IK for transform mode noRotationOrReflection when skeleton scale is applied.

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1692]
See https://github.com/EsotericSoftware/spine-runtimes/commit/5cab7e946071f447bf2626339d6be3dcf28dddcc

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua 
- [x] spine-love
- [x] spine-corona

**Comment by HaraldCsaszar** [comment]
[csharp] commit can be found here: https://github.com/EsotericSoftware/spine-runtimes/commit/85dd60bf579145606c249596e3649afd4a7a8448
