### ISSUE TITLE
UE4 Spine Widget skins do not show up.

### ISSUE THREAD

**Issue by embodiedchaos** [EsotericSoftware/spine-runtimes#1693]
I created a spine widget, and it shows the default skin just fine, but when I assign any other skins they do not show up on the widget, but they show up in all other spine asset types just fine.

**Comment by GitHub-NetFly** [comment]
Can you provide some demos to reproduce the problem?

**Comment by badlogic** [comment]
I'm afraid I can't reproduce this. If you can provide a reproduction sample, I will reopen this issue.
