### ISSUE TITLE
[runtimes] Clipping.endClipping not called when slot.bone.active==false

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1694]
Reproduction asset:
FMfcgxwHNgfrrbwvmMKrSjpXZRvHBwQh

Problem: The first clipping region continues over the second clipping, because `slot.bone.active==false` and never called `clipper.clipEnd(slot)`. Thus the first clipping mesh is used for things that should be clipped by the second region.

Reproduced Unity and in SkeletonViewer.
- in skeletonviewer load reproduction skeleton
- set active skin to `_2`
- start animation `appear`, non-looping
- observe cucumber being clipped nearly entirely, since clipped by first clipping mesh instead of second one.

Solution:
Every occurrance of the line in clipping context:
```if (!slot.bone.active) continue;```
shall be replaced with 
```
if (!slot.bone.active) {
    clipper.clipEnd(slot);
    continue;
}
```

---
- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-cpp
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua 
- [x] spine-love
- [x] spine-corona

**Comment by johnSjo** [comment]
Hey,

for spine-ts threejs there are two more place where `clipper.clipEnd(slot);` is needed
`if (finalVerticesLength == 0 || finalIndicesLength == 0)
							continue;`

this is for when the `endSlot` is outside of the clipping area

and the second place is if the `endSlot` is neither a `Region, Mesh, or ClippingAttachment` 

basically before all `continue` in this drawOrder for loop
