### ISSUE TITLE
[ts] Skeleton.setAttachment does not accept null in attachmentName

### ISSUE THREAD

**Issue by jramstedt** [EsotericSoftware/spine-runtimes#1701]
Documentation says attachmentName parameter can be null, but declaration doesn't allow that.

Error:
Argument of type 'null' is not assignable to parameter of type 'string'.ts(2345)

**Comment by NathanSweet** [comment]
The code doesn't explicitly check for null and throw an error:
https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-ts/core/src/Skeleton.ts#L509

Are you using strict null checking? spine-ts doesn't have that enabled, therefore the type `string` is treated as `string | undefined | null`.
