### ISSUE TITLE
[cpp] Access to regions in spine::Atlas class

### ISSUE THREAD

**Issue by AIGRIND-LLC** [EsotericSoftware/spine-runtimes#1703]
Hi,
It would be really handy to get the method: ```Vector<AtlasRegion*> &getRegions()``` in ```spine::Atlas``` class. We use it for custom attachment loader. 

By the way ```static Atlas *abortAtlas(Atlas *atlas)``` seems to be not implemented.

**Comment by badlogic** [comment]
Thanks! This is fixed in the 3.8 and 4.0-beta branches. `Atlas::abortAtlas()` was a relict from the spine-c port and has been removed.
