### ISSUE TITLE
[unity] Support tint black at lit shaders

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1705]
Only the unlit shader `Spine/Skeleton Tint Black` supports the vertex color animation based tint-black functionality.

The lit shaders (`Skeleton Lit` and the `Sprite` shaders) could efficiently support this functionality via a configurable `#ifdef` branch.

As requested on the forum:
http://esotericsoftware.com/forum/URP-2D-tint-black-14142

**Comment by HC-Mark** [comment]
Hi, is there any update on adding this new shader?

**Comment by HaraldCsaszar** [comment]
We are very sorry that we didn't get to implement this issue ticket yet!

**Comment by HaraldCsaszar** [comment]
@HC-Mark We have finally added support for [Tint Black](http://en.esotericsoftware.com/spine-slots#Tint-black) functionality at all Spine URP shaders (2D and 3D shaders) and at all standard pipeline `Spine/Sprite` shaders. This feature can be enabled via the `Tint Black` material parameter in the Inspector. Note: The URP Sprite shaders provided in the Spine URP Shaders extension UPM package require the latest version of the spine-unity runtime (package version 4.1.12, 2023-05-31 or newer) to display the added material parameters in the Inspector GUI.

The respective commits have been pushed to both the 4.1 and 4.2-beta branches.
New 4.1 and 4.2-beta spine-unity unitypackages and Spine URP shaders UPM packages are available for download here as usual:
https://esotericsoftware.com/spine-unity-download

Sorry that this feature has been delayed for such a long time!
