### ISSUE TITLE
UE4 Crash when clicking on the atlas or the skel-data in Spine Skeleton Animation Component.

### ISSUE THREAD

**Issue by Xnuman** [EsotericSoftware/spine-runtimes#1707]
Hello there.
Using the Unreal Engine 4.24.2 and spine-ue4 3.8
When I am trying to change skeleton data or skeleton atlas the ue4 is crushing. I think that the case in the wrong assets, but it would be nice to have some error description and not just crushing.
![image](https://user-images.githubusercontent.com/47171642/85146715-8e25e080-b256-11ea-893e-1f723b639a58.png)

P.S. Also tested on Unreal Engine 4.25.0 - same result.

**Comment by Xnuman** [comment]
I figured it out that when you are trying to change Atlas or Skeleton Data, you first need to clear these fields. In other case Spine will try to combine the unchanged field with the new one and ofcourse they won't match and Spine just will cause ue4 to crash.
So, example.
![image](https://user-images.githubusercontent.com/47171642/85691619-564aed00-b6dd-11ea-92d4-c52d67d7241a.png)
If I click now to something other than "skeleton_main_atlas", spine will try to render sprite with new atlas and old skeleton data and ue4 will crash.
But If I clear all fields first, I can change everything without crash.
STILL, it would be nice to have some error handling here - crashing isn't the good way of telling the users that they did something wrong.

**Comment by youZhuang** [comment]
The same problem with me!

**Comment by badlogic** [comment]
Thanks for reporting and sorry for the fix taking so long. I've now pinpointed the issues and reworked some internal code for this to be fixed in both the 3.8 and 4.0-beta branch.
