### ISSUE TITLE
[cpp] Slots' dark colors are not being set when the slots are set to their setup poses.

### ISSUE THREAD

**Issue by kek1us** [EsotericSoftware/spine-runtimes#1713]
Hello!

I've encountered that, when a slot is set to its setup pose in the C++ runtimes, the dark color is not set using the internal `SlotData`'s dark color. Specifically, here:
```
void Slot::setToSetupPose() {
	_color.set(_data.getColor());

	const String &attachmentName = _data.getAttachmentName();
	if (attachmentName.length() > 0) {
		_attachment = NULL;
		setAttachment(_skeleton.getAttachment(_data.getIndex(), attachmentName));
	} else {
		setAttachment(NULL);
	}
}
```
Therefore, in the current version, their dark colors are applied only when two color timelines are being used. So, by checking out other runtimes (C, C# and TypeScript), I've confirmed that they do set the dark color and this is indeed a bug.

Here is the fix I applied locally (definitely not rocket science):
```
void Slot::setToSetupPose() {
	_color.set(_data.getColor());

	if (_hasDarkColor) {
		_darkColor.set(_data.getDarkColor());
	}

	const String &attachmentName = _data.getAttachmentName();
	if (attachmentName.length() > 0) {
		_attachment = NULL;
		setAttachment(_skeleton.getAttachment(_data.getIndex(), attachmentName));
	} else {
		setAttachment(NULL);
	}
}
```
Cheers!

**Comment by badlogic** [comment]
This has been fixed in the 3.8 and 4.0-beta branches, cheers!
