### ISSUE TITLE
Spine animations are invisible on Android [cocos2d-x v4]

### ISSUE THREAD

**Issue by oziphantom** [EsotericSoftware/spine-runtimes#1723]
So I have an product that I've upgraded to Cocos2d-x V4 and I'm using the Cocos2dx-v4 branch, and I've manged to get it to link in and use the v4 version of it. 
On windows the animations show perfectly no issues, work like a charm. On Android nothing shows. I've stepped through the loading code thinking it was the special "hi I'm android and I put things in a bundle but you can't just load from them you have to use these custom special functions" issue. But stepping through the init, it reads the json, the atlas and seemingly the texture as expected. Nothing complains about a missing file, no errors appear in the TTY when loading or playing it back. 

I tried to get the "example working" but the example instructions are for the original C version and not this new V4 C++ version so it doesn't work.

Any ideas on what I can debug to try and work it out. I've already tried forcing scale to 1.0 and changing the Y to be -Y and inverting the Y. Nothing.

**Comment by badlogic** [comment]
Sorry for the delayed response! It's hard to say what might be going on without being able to reproduce it. You say that you couldn't get the V4 spine-cocos2dx runtime to work? I think our first approach should be to get you into a working state with our example. These instructions did not work for you? https://github.com/EsotericSoftware/spine-runtimes/tree/3.8/spine-cocos2dx#android-on-macos-1

Also, could you share what Android device and Android version you are trying to run this on?

**Comment by badlogic** [comment]
I'll reopen if you can show me a reproduction sample. The example project works on the Android devices I have available.

**Comment by oziphantom** [comment]
Sorry the other notification emails must have gone to junk. 

So it was the cocos-2dx V4 "branch" not just the cocos-2dx V4 runtime, so not the 3.8 branch version. Which has these instructions https://github.com/EsotericSoftware/spine-runtimes/tree/cocos2dx-v4/spine-cocos2dx which don't work ;) as they are still V3 based. 
Although I would point out that the one you linked(3.8) has TBD under Setup::Cocos2d-x v4.x up the top still. 

I'm using a Samsung Tab A7 SM-T280 which has Android 5.5 despite it not being that old.
