### ISSUE TITLE
[player] Webplayer not loading assets in documentation page

### ISSUE THREAD

**Issue by erikari** [EsotericSoftware/spine-runtimes#1744]
An error is displayed instead of showing a working webplayer:
> Error: assets could not be loaded

http://prntscr.com/u2oz3a

On the documentation page:
http://esotericsoftware.com/spine-player#Putting-it-all-together

**Comment by badlogic** [comment]
Issue is that the server is serving the doc page via HTTP, while the assets are requested via HTTPS.

**Comment by badlogic** [comment]
It's actually because we load code into an editor and execute it via a data URL in an iframe. Need to set CORS headers on the files.
