### ISSUE TITLE
[unity] Mesh not rendering on Unity 2020.1

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1745]
As reported on the forum:
http://esotericsoftware.com/forum/Unity-2020-1-2-Runtimes-14437

Meshes are generated and correct, the shader or materials seems to be left in an improper state by Unity.
1. Enabling and disabling the `Spine/Skeleton` shader's outline parameter (switching it to the separate shader for the outline variant) (sometimes) fixes the issue.
2. Changing any shader parameter and hitting undo also fixes the issue.

**Comment by asashour** [comment]
This is fixed in `2020.1.5f1`, thanks.

**Comment by HaraldCsaszar** [comment]
Verified that the issue is occurring no longer. Thanks @asashour for reporting!

**Comment by gundamoof** [comment]
I'm facing the similar issue with unity 2020.1.11f1c1. Everytime when i drag  atlas.txt json and png file into the project. File name changed with  _  replaced the the first character and console displaying error "Material is missing texture:XXXXX" Material is missing texture, i mannually put it in does not change anything and the method above does not help also.

**Comment by HaraldCsaszar** [comment]
@gundamoof What do you mean by "File name changed with _ replaced the the first character"?

**Comment by gundamoof** [comment]
@HaraldCsaszar  For example, my exported files names are box.atlas.txt box.json and box.png. Once i dragged then into the unity, file names are atuto changed to _ox.atlas.txt _ox.json and _ox.png

**Comment by HaraldCsaszar** [comment]
I assume that you already have existing files in the same directory. If you don't like Unity's behaviour of handling drag-and-drop when the files exist already, please create a ticket at their issue tracker, not ours. So when you want to overwrite (update by replacing) existing files you have to make sure they end up replacing your files, not being renamed and placed alongside existing files with no longer matching names.
