### ISSUE TITLE
[Unity] Incorrect color calculation for TintBlack shaders

### ISSUE THREAD

**Issue by bilck** [EsotericSoftware/spine-runtimes#1747]
We use TintBlack shaders for our customizable characters and have noticed that color calculation is not right, generating some white lines (usually on borders) due to color interactions.
We use Straight Alpha for our materials and images.

The fix is simple, but I don't know to properly suggest changes to Spine Runtimes code.

Just change `Spine-Skeleton-TintBlack.shader` code:
```
float4 frag (VertexOutput i) : SV_Target {
    float4 texColor = tex2D(_MainTex, i.uv);

    float4 blackColor =  float4(((1-texColor.rgb) * (_Black.rgb + float3(i.uv1.r, i.uv1.g, i.uv2.r))), 0);// * texColor.a;
    #if !defined(_STRAIGHT_ALPHA_INPUT)
    blackColor.rgb *= texColor.a;
    #endif		
    float4 finalColor = texColor + blackColor;                
    #if defined(_STRAIGHT_ALPHA_INPUT)
    finalColor.rgb *= finalColor.a;
    #endif

    return finalColor * i.vertexColor;
    // Original Code:
    //return (texColor * i.vertexColor) + float4(((1-texColor.rgb) * (_Black.rgb + float3(i.uv1.r, i.uv1.g, i.uv2.r)) * texColor.a*_Color.a*i.vertexColor.a), 0);
}
```

**EDIT:** I have added a few screenshots [here](https://drive.google.com/drive/folders/1HvZBBh1B0tWV1S-6uXMrU6tqdx8C3mVr?usp=sharing).

**Comment by HaraldCsaszar** [comment]
Thanks for reporting and sorry for the late reply, we missed your ticked amoung other git notifications.

**Comment by HaraldCsaszar** [comment]
Thanks very much for reporting, we just pushed a bugfix commit for the issue.

Please note that you might want to update to the official shader later (an updated unitypackage is not yet published) as your shader code is not behaving correctly under all conditions.

**Comment by HaraldCsaszar** [comment]
A new 3.8. unitypackage has just been release, available for download here as usual:
http://esotericsoftware.com/spine-unity-download

**Comment by bilck** [comment]
Does this latest package include the shader fix?

Thanks!

**Comment by HaraldCsaszar** [comment]
We discovered some problems with the last bugfix update and are working on a bugfix. We'll let you know once the issue has been resolved.

**Comment by HaraldCsaszar** [comment]
The issue has just been fixed by commit 5c1faa8.

New unitypackages are available for download here as usual:
http://esotericsoftware.com/spine-unity-download

**Comment by bilck** [comment]
Thanks @HaraldCsaszar !

**Comment by HaraldCsaszar** [comment]
Thanks for reporting @bilck !
