### ISSUE TITLE
[unity] Fix build warnings/messages

### ISSUE THREAD

**Issue by bklooster** [EsotericSoftware/spine-runtimes#1753]
Could you please update to fix the following warnings in your project? I don't believe that any 3rd-party plugin should be producing warnings/messages when using the imported code at all. Also don't use the ?? or ?. operator on Unity objects. Their lifecycle exists outside of C# (on the C++) end which the overloaded == operator checks for, but the ??/?. does not. (more info) https://forum.unity.com/threads/elvis-operator-null-coalescing-operator.433767/

------ Build started: Project: spine-unity, Configuration: Debug Any CPU ------
Components\Following\BoneFollower.cs(59,3): info UNT0013: SerializeField attribute is invalid or redundant for property or field: boneName
Components\Following\PointFollower.cs(46,3): info UNT0013: SerializeField attribute is invalid or redundant for property or field: skeletonRenderer
Components\Following\BoneFollowerGraphic.cs(58,3): info UNT0013: SerializeField attribute is invalid or redundant for property or field: boneName
Components\SkeletonGraphic.cs(242,23): info UNT0006: The Unity message "Update" has an incorrect signature.
Components\SkeletonAnimation.cs(184,15): info UNT0006: The Unity message "Update" has an incorrect signature.
Runtime\spine-unity\Utility\AtlasUtilities.cs(615,16): info UNT0017: SetPixels is slower than SetPixels32
Runtime\spine-unity\Utility\AtlasUtilities.cs(598,17): info UNT0017: SetPixels is slower than SetPixels32
------ Build started: Project: spine-timeline, Configuration: Debug Any CPU ------
Runtime\SpineAnimationState\SpineAnimationStateBehaviour.cs(51,16): warning CS0414: The field 'SpineAnimationStateBehaviour.isInitialized' is assigned but its value is never used
------ Build started: Project: spine-unity-editor, Configuration: Debug Any CPU ------
Editor\spine-unity\Editor\Windows\SkeletonBaker.cs(624,11): info UNT0007: Unity objects should not use null coalescing.
Editor\spine-unity\Editor\Asset Types\SpineAtlasAssetInspector.cs(111,17): info UNT0007: Unity objects should not use null coalescing.
Editor\spine-unity\Editor\Asset Types\SpineSpriteAtlasAssetInspector.cs(74,17): info UNT0007: Unity objects should not use null coalescing.

**Comment by HaraldCsaszar** [comment]
Thanks for reporting, the remaining reported issues have just been fixed in the above commit.

If anybody knows a way to suppress info warnings issued by Microsoft's Analysers for Unity (like `#pragma warning disable 414`), please let us know. We would like to get rid of the following info warnings as well:
`"info UNT0017: SetPixels is slower than SetPixels32"`
`"info UNT0006: The Unity message "Update" has an incorrect signature."`
