### ISSUE TITLE
[ts] support running spine-ts in a webworker

### ISSUE THREAD

**Issue by MikalDev** [EsotericSoftware/spine-runtimes#1758]
Support spine-ts running in a webworker (Construct 3 renders to offline canvas in a web worker to reduce FPS jank from DOM.)

Some example changes needed:

- change Image . img.src to use fetch (fetch to blob)
- change HTMLCanvas..., HTMLImage... to worker supported elements
- change document.createElement("img") to worker supported element (blob?)
- disable DOM 'UI' elements (document.addEventListener("mousemove", mouseMove), etc.)

**Comment by MikalDev** [comment]
For HTMLImage, can probably use ImageBitmap instead. So would fetch to blob and then create ImageBitmap to store in rawassets.

Probably change HTMLImage to imageBitmap also?

Example for fetch -> imageBitmap (ignore document, etc. this is from https://jsfiddle.net/greggman/kzqxs1wv/ )
```javascript
const ctx = document.querySelector('canvas').getContext('2d');

const url = 'https://i.imgur.com/ZKMnXce.png';
const options = {mode: 'cors'};

fetch(url, options).then(function(response) {
  if (!response.ok) {
    throw response;
  }
  return response.blob();
}).then(function(blob) {
  return createImageBitmap(blob, {
    premultiplyAlpha: 'none',
    colorSpaceConversion: 'none',
  });
}).then(function(bitmap) {
  // can pass bitmap to texImage2D but just to be short
  // here's using it with canvas 2d
  ctx.drawImage(bitmap, 0, 0, 300, 150);
});
```

**Comment by MikalDev** [comment]
Found a nice additional chunk of work possibly required:

Change Texture.ts and GLTexture.ts to also support ImageBitMap, not only ImageElement.

**Comment by badlogic** [comment]
The corresponding PR has been merged. Cheers!
