### ISSUE TITLE
[corona] Runtime error in spine-lua/AnimationState.lua 

### ISSUE THREAD

**Issue by XeduR** [EsotericSoftware/spine-runtimes#1759]
Loading the Corona sample project and navigating to the second sample animation, i.e. the walking cycle for the guy with the blaster, will result in a runtime error after the animation has played out for approximately 3 seconds.

The error occurs on [line 509 in AnimationState.lua](https://github.com/EsotericSoftware/spine-runtimes/blob/d43b7b0a9f21658e4eda48531bc280d5f64ff65e/spine-lua/AnimationState.lua#L509).

The error message is: `AnimationState.lua:509: attempt to index local 'skeleton' (a number value)`

**Comment by badlogic** [comment]
This has been fixed.
