### ISSUE TITLE
[corona] rename "spine-corona" to "spine-solar2d"

### ISSUE THREAD

**Issue by XeduR** [EsotericSoftware/spine-runtimes#1760]
On 1 May, Corona engine went fully open source and rebranded itself as Solar2D. Here's a [link to the official blog post](https://coronalabs.com/blog/2020/04/30/future-of-corona/).

In order for new, as well as existing Solar2D developers to find the Spine runtime that they need, it'd make sense to rename "spine-corona" to "spine-solar2d".

**Comment by NathanSweet** [comment]
Maybe for 4.0?
