### ISSUE TITLE
A/libc: spine-runtimes/spine-cpp/spine-cpp/src/spine/Skin.cpp:96: spine::Skin::Skin(const spine::String &): assertion "_name.length() > 0" failed

### ISSUE THREAD

**Issue by kalozfauzan1** [EsotericSoftware/spine-runtimes#1766]
I use spine in cocos2dx v4, with code 
auto loading = SkeletonAnimation::createWithJsonFile("HD/Spine/misc/loading.json", "HD/Spine/misc/loading.txt",1.5f);
            loading->setPosition(cocos2d::Vec2(origin.x + visibleSize.width / 2, origin.y + visibleSize.height / 2));
            backBg->addChild(loading, 102);
            loading->setAnimation(0, "loading", true);

**Comment by badlogic** [comment]
As discussed on the forum, you are trying to load a file you exported from a Spine Editor version that is not equal to the Spine Runtimes version you are using.
