### ISSUE TITLE
[unity] SkeletonDataModifierAsset not invoked on Unity 2020.1.6 and newer

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1768]
As reported on the forum:
http://esotericsoftware.com/forum/Unity-2020-1-6f1-SkeletonDataModifierAsset-not-called-14648

Reproduced the problem on Unity 2020.1.7f1.
Confirmed SkeletonDataModifierAsset is working on Unity 2019.4.11f1, so seems to be related to 2020 only.

**Comment by ledvinam** [comment]
Can we have this resolved please. It is a project breaker. :-(

**Comment by HaraldCsaszar** [comment]
Please check the reply on the forum thread, perhaps we are talking about different issues and yours can be fixed easily.

**Comment by HaraldCsaszar** [comment]
Turns out to have been false alarm. After adding a `SkeletonDataModifierAsset` to the list of a `SkeletonDataAsset`, you have to save the asset once, afterwards upon either a) modifying the json skeleton file or b) reimporting the parent directory, the `SkeletonDataModifierAsset` `Apply()` method is called correctly.

Just without saving, it behaved inconsistently, most of the time not applying the `SkeletonDataModifierAsset`.
