### ISSUE TITLE
[UE4] Attach to bones

### ISSUE THREAD

**Issue by martoof** [EsotericSoftware/spine-runtimes#1773]
We can have a "Get Bone World Transform" node but is not possible to communicate directly to a bone.
Like attach to component.
Is it possible to add reference to bone on the SpineSkeleton scene component (Renderer or SkeletonAnimation) ?

**Comment by badlogic** [comment]
Have a look at the skeleton follower component. http://en.esotericsoftware.com/spine-ue4#Skeleton-Follower-Component
