### ISSUE TITLE
[UE4] Set Animation per bone

### ISSUE THREAD

**Issue by martoof** [EsotericSoftware/spine-runtimes#1774]
There is Animation track to merge 2 animations together.
Is it possible to allow a bone name parameter to blend only child hierarchy and forget other bones ?
Like the layered blend per bone on UE4 AnimGraph ?

**Comment by badlogic** [comment]
As discussed on the forum, this is not possible in the way you describe it, but can be done by mixing animations on multiple tracks, each only modifying a subset of bones.
