### ISSUE TITLE
[unity] Add `Writing your own shaders` section to docs

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1776]
As reported on the forum, an example scene references the documentation for additional info:
http://esotericsoftware.com/forum/Custom-spine-shader-14681
Currently the shader docs section contains no additional info, so such a section shall be added.

**Comment by Fuzzel11** [comment]
The example scene in question is `Spine Examples/GettingStarted/5 Basic Platformer`

**Comment by HaraldCsaszar** [comment]
Section can be found here:
http://esotericsoftware.com/spine-unity#Writing-your-own-shaders
