### ISSUE TITLE
[c] Event > setAnimation > freed linked list

### ISSUE THREAD

**Issue by jllust** [EsotericSoftware/spine-runtimes#178]
When listening for an event, Animation_end, Animation_complete, custom. Then leads to a setAnimation the in process loop will continue to access freed memory from the previous animation’s linked list via the "current" pointer in AnimationState.c
Temp fix at: ab3c66107aefc0660425b4a32320a65950a87e05

**Comment by NathanSweet** [comment]
AnimationState has been upgraded starting with Spine 3.5. This and many other issues have been fixed, see #621.
