### ISSUE TITLE
[spine-cpp] SegFault when app ends

### ISSUE THREAD

**Issue by Niolak** [EsotericSoftware/spine-runtimes#1780]
The commit 47873c041b7c7c308379dfba65672b115f9bce63 introduced a bug.

RTTI inherits from SpineObject and a static instance of RTTI is declared which means that the destruction of this static instance is done after the call to ~SpineExtension. Therefore SpineExtension should not be called in ~SpineObject.

**Comment by badlogic** [comment]
Good catch. This has been resolved by not having RTTI inherit from SpineObject.
