### ISSUE TITLE
[xna] Debug renderer IOOBs with bounding boxes with more than 4 vertices

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1782]
See http://esotericsoftware.com/forum/XNA-skeletonDebugRenderer-error-polygon-over-4-vertices-14732

**Comment by Predator75** [comment]
Hi,
maybe I have the solution
in ShapeRenders.cs, row 118 void Polygon
this fix the problem
`//count <<= 1; //Commented by Cristian`
and remove the -2 from the for loop, change this
`for (int i = offset, n = offset + count - 2; i<n; i += 2) {`
to
`for (int i = offset, n = offset + count; i<n; i += 2) {`
