### ISSUE TITLE
[unity] The SkeletonMecanim does not handle negative normalizedTime

### ISSUE THREAD

**Issue by stefanbursuc** [EsotericSoftware/spine-runtimes#1784]
The SkeletonMecanim does not properly handle animation state's normalizedTime when it goes negative.

The animation freezes on the first animation frame.

This behavior can be viewed on this video: https://streamable.com/gg3926.
And can be tested on the attached test project on this forum thread:
http://esotericsoftware.com/forum/Bug-The-SkeletonMecanim-does-not-handle-negative-times-14744

**Comment by stefanbursuc** [comment]
I have proposed a fix with the pull request #1785.

**Comment by HaraldCsaszar** [comment]
Fixed in this issue ticket:
https://github.com/EsotericSoftware/spine-runtimes/issues/1790

**Comment by stefanbursuc** [comment]
Sorry for the late reply. 
The fix for this bug added a regression.
Please test again the provided scene from the forum thread mentioned above.
Change the Animator's "New State" Speed value (not the Multiplier) to a negative value (i.e. -1).
The animation should go backwards with a positive multiplier (change-able from the Game View) and forwards for negative multiplier.

**Comment by stefanbursuc** [comment]
I have created a follow-up issue: #1810

**Comment by HaraldCsaszar** [comment]
Thanks for reporting @stefanbursuc !
