### ISSUE TITLE
[ue4] Motion blur post processing affects skeletons that are stationary relative to camera

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1788]
See http://esotericsoftware.com/forum/UE4-SpineSkeletonRenderer-and-Motion-Blur-14757

**Comment by NathanSweet** [comment]
User says they have a solution:

> Default material for the SpineRenderMesh is a material with Translucent BlendMode. For working with motion blur in this blend mode it is necessary to enable the OutputVelocity option in MaterialDetails.

We may just need a note in the docs.

**Comment by badlogic** [comment]
Added to spine-ue4 docs.
