### ISSUE TITLE
error set animation by name, please help me :(

### ISSUE THREAD

**Issue by Qusdrok** [EsotericSoftware/spine-runtimes#1811]
i got error 
C:\Users\Admin\Downloads\Example\Example\spine-lua\AnimationState.lua:509: attempt to index local 'skeleton' (a number value)
13:30:32.226  stack traceback:
13:30:32.226  	C:\Users\Admin\Downloads\Example\Example\spine-lua\AnimationState.lua:509: in function 'applyAttachmentTimeline'
13:30:32.226  	C:\Users\Admin\Downloads\Example\Example\spine-lua\AnimationState.lua:384: in function 'apply'
13:30:32.226  	C:\Users\Admin\Downloads\Example\Example\libs\play_game.lua:65: in function 'showAnimation'
13:30:32.226  	C:\Users\Admin\Downloads\Example\Example\libs\play_game.lua:81: in function 'performAnimation'
13:30:32.226  	C:\Users\Admin\Downloads\Example\Example\libs\play_game.lua:345: in function 'func'
13:30:32.226  	D:\a\corona\corona\platform\resources\init.lua:202: in function <D:\a\corona\corona\platform\resources\init.lua:189>
i am running project of spine-corona and in the second animation after it ran the set animation it got this error, please help me :(

**Comment by badlogic** [comment]
What Spine Runtime version are you using? What is the Spine Editor version you exported your skeleton from? Can you share your code and or assets?
