### ISSUE TITLE
[unity] SkeletonGraphic incorrectly displays in build when `CanvasGroup compatible` enabled

### ISSUE THREAD

**Issue by Maaaaayao** [EsotericSoftware/spine-runtimes#1812]
When I change the Alpha of the CanvasGroup, the animation cannot fade away. Normally displayed in **UnityEditor**, but **cannot** be displayed normally after Build: **Android, Windows EXE**
How can i solve this problem?
material:
![image](https://user-images.githubusercontent.com/30713076/100042612-c6a19a00-2e46-11eb-8967-7d8df29aa704.png)

prefab:
![image](https://user-images.githubusercontent.com/30713076/100042692-f51f7500-2e46-11eb-9a24-28dc07955693.png)

**Comment by HaraldCsaszar** [comment]
You have enabled `CanvasGroup Tint Black` at the `SkeletonGraphic` component, but you are using the normal `Spine/SkeletonGraphic` shader. The `CanvasGroup Tint Black` parameter shall only be enabled when using a `Spine/SkeletonGraphic Tint Black` shader, not when using the normal `Spine/SkeletonGraphic` shader.

Please let us know if this fixes your problem.
We will add an Inspector warning that detects this incorrect combination to hopefully prevent further problems.

**Comment by HaraldCsaszar** [comment]
Upon further inspection I noticed that the `CanvasGroup Tint Black` parameter has no effect when `Tint Black` is disabled, so this should not be the cause of your problem.

Can you please send us a minimal reproduction Unity project that still shows the problem, as a zip package to contact@esotericsoftware.com, or attach a download link to this ticket.

**Comment by Maaaaayao** [comment]
**Thanks, according to the method you provided, it can be used after modification.**

=============================

The main reason why I could not display normally before is that all the resources in my project are packaged into assetbundle, and the spine shader may not be packaged into the apk normally. What is more puzzled is that I have already associated the shader resource into "**Preloaded "Shaders**" are inside, I don't know why I still need to manually put it in Resources. The following are the shaders that I have linked to the project. Which shaders do I need to link to before I can use them?
![image](https://user-images.githubusercontent.com/30713076/100183489-09807200-2f1a-11eb-99f8-d853b1ac9ff7.png)


> Upon further inspection I noticed that the `CanvasGroup Tint Black` parameter has no effect when `Tint Black` is disabled, so this should not be the cause of your problem.
> 
> Can you please send us a minimal reproduction Unity project that still shows the problem, as a zip package to [contact@esotericsoftware.com](mailto:contact@esotericsoftware.com), or attach a download link to this ticket.

**Comment by HaraldCsaszar** [comment]
> Thanks, according to the method you provided, it can be used after modification.

Glad you've figured it out, thanks for letting us know.

> The following are the shaders that I have linked to the project. Which shaders do I need to link to before I can use them?

I'm afraid I don't quite understand your question. In general you need to make sure that all actually used shaders are available when e.g. loading via asset bundles. If you don't ever use the `Outline` feature at materials used by your `SkeletonGraphic` components, you don't need to include `Spine/Outline/SkeletonGraphic` in your build/assetbundles for example.

**Comment by Maaaaayao** [comment]
> > Thanks, according to the method you provided, it can be used after modification.
> 
> Glad you've figured it out, thanks for letting us know.
> 
> > The following are the shaders that I have linked to the project. Which shaders do I need to link to before I can use them?
> 
> I'm afraid I don't quite understand your question. In general you need to make sure that all actually used shaders are available when e.g. loading via asset bundles. If you don't ever use the `Outline` feature at materials used by your `SkeletonGraphic` components, you don't need to include `Spine/Outline/SkeletonGraphic` in your build/assetbundles for example.

**Thanks, The problem itself has been solved, thank you very much.**
The following description is for the convenience of subsequent developers who encounter the same problem and provide a solution. All the resources used in my project are packaged in assetbundle. It seems that **Spine/SkeletonGraphic** is not packaged normally. I manually built a **material** and put it in **Resources**.

**Comment by HaraldCsaszar** [comment]
Thanks for the clarification @Maaaaayao!
