### ISSUE TITLE
[unity] BlendModeMaterialsAsset causes pink material error on some reload modes

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1822]
As reported on the forum:
http://esotericsoftware.com/forum/Additive-Screen-Blendmode-Slots-Enter-Exit-Playmode-Issues-15100

This can also be reproduced in Unity 2020.1 with the `BlendModes` example scene and project settings:
Enter play mode options: enabled
  Reload domain: disabled
  Reload scene: enabled

**Comment by astro75** [comment]
I fixed a similar issue on my project by adding the following code to `SkeletonDataAsset` class
```C#
#if UNITY_EDITOR

		static readonly List<SkeletonDataAsset> allLoadedAssets = new();
		
		// OnEnable is more reliable than Awake for ScriptableObject
		public void OnEnable() => allLoadedAssets.Add(this);

		[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
		public static void reset() {
			// When Domain Reload is disabled in the editor and we use BlendModeMaterialsAsset,
			// we will see pink rectangles on second time we enter play mode.
			// For this reason we need to clear all loaded SkeletonDataAsset objects.
			
			// Unity does not have a callback on asset delete, check if it is still alive
			allLoadedAssets.RemoveAll(asset => !asset);
			foreach (var asset in allLoadedAssets) {
				asset.Clear();
			}
		}

#endif 
```

**Comment by HaraldCsaszar** [comment]
Thanks for sharing your code @astro75. We already implemented a more powerful blend mode solution instead which solves multiple problems at once.

From the changelog:
> * Added **native support for slot blend modes** `Additive`, `Multiply` and `Screen` with automatic assignment at newly imported skeleton assets. `BlendModeMaterialAssets` are now obsolete and replaced by the native properties at `SkeletonDataAsset`. The `SkeletonDataAsset` Inspector provides a new `Blend Modes - Upgrade` button to upgrade an obsolete `BlendModeMaterialAsset` to the native blend modes properties. This upgrade will be performed automatically on imported and re-imported assets in Unity 2020.1 and newer to prevent reported `BlendModeMaterialAsset` issues in these Unity versions. spine-unity 4.0 and newer will automatically perform this upgrade regardless of the Unity version.

New 3.8 and 4.0-beta unitypackages are available for download here as usual:
http://esotericsoftware.com/spine-unity-download
