### ISSUE TITLE
[unity] SkeletonGraphic with multiple materials displays white square and error

### ISSUE THREAD

**Issue by samanabo** [EsotericSoftware/spine-runtimes#1826]
Unity version:  **2019.4.14f1**
Spine-unity package version: **spine-unity-3.8-2020-11-20**

I am seeing a rendering issue when using a SkeletonGraphic (Unity UI Canvas) component in a UI prefab.

The SkeletonGraphic has four materials and one atlas file, and is configured to use Unscaled Time, Multiple CanvasRenderers and has no Slot Separators.

The prefab is shown when the game is paused (so our Time.timeScale is 0), and is a "skin selection" menu. As the player hovers over different buttons on the screen we update the SkeletonGraphic to display the selected skin.

`skeletonGraphic.Skeleton.SetSkin(skin.ID);
skeletonGraphic.Skeleton.SetSlotsToSetupPose();`

Additionally, when the user clicks on a skin selection button, we play an animation on the SkeletonGraphic.

When changing skins, and when playing an animation the SkeletonGraphic will display only a white square for a single frame, multiple times. When playing the animation especially, this white square might show up 4 or 5 times over the course of a 2 second animation.

I also get this error in the console, although I'm not 100% sure it is directly related since it doesn't show up every time the white square is shown:
`Trying to add Renderer4 (UnityEngine.UI.RawImage) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
UnityEngine.GameObject:SetActive(Boolean)
Spine.Unity.SkeletonGraphic:UpdateMeshMultipleCanvasRenderers(SkeletonRendererInstruction) (at Assets/Plugins/Spine/Runtime/spine-unity/Components/SkeletonGraphic.cs:618)
Spine.Unity.SkeletonGraphic:UpdateMesh() (at Assets/Plugins/Spine/Runtime/spine-unity/Components/SkeletonGraphic.cs:513)
Spine.Unity.SkeletonGraphic:Rebuild(CanvasUpdate) (at Assets/Plugins/Spine/Runtime/spine-unity/Components/SkeletonGraphic.cs:220)
UnityEngine.UI.ScrollRect:LateUpdate() (at /Applications/Unity/Hub/Editor/2019.4.14f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/ScrollRect.cs:805)
`

Any idea on what might be causing this rendering problem? Or what I could do to investigate further?

**Comment by HaraldCsaszar** [comment]
Thanks for reporting. Could you please provide some reproduction assets? Please provide at least the Skeleton assets (the three exported files), or even better a minimal Unity project that still demonstrates the issue. You can either attach it to this ticket or send it to contact@esotericsoftware.com.

**Comment by samanabo** [comment]
I've replied via email including a sample repro project. Let me know if there is anything else I can do to help.

**Comment by HaraldCsaszar** [comment]
Thanks for sending the reproduction project. We received everything and will get back to you when we've figured out what's going wrong.

**Comment by HaraldCsaszar** [comment]
Both the issue of the white box and the error message have been fixed. A new 3.8 unitypackage is available for download.

**Comment by semgilo** [comment]
@HaraldCsaszar 
I got a white box at 1st frame of animation and the commit [82a0de8](https://github.com/EsotericSoftware/spine-runtimes/commit/82a0de85bc8feea2179461eac4d4de8ed259a9a5) has applied.
I saw the renderer with UI Default Material. It will be modified next frame.

UnityVersion: 2020.3.2
SpineVersion: 3.8.xx

Repro.
1.Add a SkeletonGraphic (UGUI)
2.Advance-Multiple CanvasRenderers
3.Setup data animation name "start" and start loop
4.A "white box" appear sometime at 1st frame.
[hero_fg_1.zip](https://github.com/EsotericSoftware/spine-runtimes/files/9185967/hero_fg_1.zip)

**Comment by HaraldCsaszar** [comment]
@semgilo Please note that your applied commit is not sufficient to fix this issue. It also needs commit 214c778b, as described in this forum posting:
http://esotericsoftware.com/forum/spine-Advanced-multiple-CanvasRenderers-16677?p=73077#p73077
IIRC, this forum posting also contains a zip package providing an already patched 3.8 `SkeletonGraphic.cs` script.

**Comment by semgilo** [comment]
@HaraldCsaszar 
It work. Thank you very much.

**Comment by HaraldCsaszar** [comment]
@semgilo Glad to hear, thanks for confirming.
