### ISSUE TITLE
[unity] AnimationName updates after second change

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1832]
When changing `Animation Name` in `SkeletonAnimation` Inspector, the first change does not change the animation, the same animation name has to be selected a second time to take effect, or Play-mode needs to be entered and exited once.

Reported via email:
FMfcgxwKkbjMVFrTPTBmSQjJgXKqdMpn
And also on the forum:
http://esotericsoftware.com/forum/x-15308

**Comment by thejaemi** [comment]
Unity Editor on Windows 2019.4.18f1 version

When animationName.stringValue enters TrySetAnimation, it does not change in the first frame, but in the second frame.
wasAnimationNameChanged bool variable is already treated as changed

When entering the TrySetAnimation function, animationName.stringValue is written to the previous animation name and does not change.

private string m_selectedAnimationName = string.Empty;
Add a variable, If you modify the TrySetAnimation function as follows, it was confirmed that it works normally.

protected void TrySetAnimation (SkeletonAnimation skeletonAnimation, bool multi) {
			if (skeletonAnimation == null) return;
			if (!skeletonAnimation.valid)
				return;

			if (!isInspectingPrefab) {
				if (wasAnimationNameChanged || !m_selectedAnimationName.Equals(animationName.stringValue)) {
					var skeleton = skeletonAnimation.Skeleton;
					var state = skeletonAnimation.AnimationState;

					if (!Application.isPlaying) {
						if (state != null) state.ClearTrack(0);
						skeleton.SetToSetupPose();
					}

					Spine.Animation animationToUse = skeleton.Data.FindAnimation(animationName.stringValue);

					if (!Application.isPlaying) {
						if (animationToUse != null) {
							skeletonAnimation.AnimationState.SetAnimation(0, animationToUse, loop.boolValue);
						}
						skeleton.UpdateWorldTransform();
						skeletonAnimation.LateUpdate();
						requireRepaint = true;
					} else {
						if (animationToUse != null)
							state.SetAnimation(0, animationToUse, loop.boolValue);
						else
							state.ClearTrack(0);
					}
				}

				// Reflect animationName serialized property in the inspector even if SetAnimation API was used.
				if (Application.isPlaying) {
					TrackEntry current = skeletonAnimation.AnimationState.GetCurrent(0);
					if (current != null) {
						if (skeletonAnimation.AnimationName != animationName.stringValue)
							animationName.stringValue = current.Animation.Name;
					}
				}
				m_selectedAnimationName = animationName.stringValue;
			}
		}

**Comment by HaraldCsaszar** [comment]
Thanks for posting the code. Unfortunately it did not resolve the problem at our local test setups. Anyway we have already been working on a bugfix, which has just been committed.

You can download the latest 3.8 and 4.0-beta unitypackages here as usual:
http://esotericsoftware.com/spine-unity-download
Thanks for reporting.
