### ISSUE TITLE
[spine-ts] worker mode broken with #1804

### ISSUE THREAD

**Issue by MikalDev** [EsotericSoftware/spine-runtimes#1833]
spine-ts can no longer run in web worker mode with this change by @badlogic, investigating fixes. The error is:

```ReferenceError: HTMLCanvasElement is not defined``` based on this line (in the js build)

```NEW - if (canvasOrContext instanceof HTMLCanvasElement || canvasOrContext instanceof EventTarget) {```

HTMLCanvasElement is not defined in web worker mode (this is why the previous version used this instead:)

```ORIGINAL - if (!((canvasOrContext instanceof WebGLRenderingContext) || (canvasOrContext instanceof WebGL2RenderingContext))) {```

Looking at the change for iOS 14, it looks like webgl context detection may be an issue right now, so I'm reviewing that info to find out more details. I do note that there are quite a few reports of iOS 14 issues with webgl circulating around right now, it also may need to settle out on iOS side:

https://developer.apple.com/forums/thread/662251
https://developer.apple.com/forums/thread/659557
https://bugs.webkit.org/show_bug.cgi?id=215908

I am running beta versions of iOS and in iOS 14.4 Public Beta 1 (webgl1 tested, webgl2 tested) on an iPhone XR, the ORIGINAL condition works (perhaps some of the webgl bux fixes have been done.)

After iOS 14.4 releases, I suggest that we can again make this worker compatible using the ORIGINAL condition. I will do some testing then also with the official release, not the beta.

**Comment by MikalDev** [comment]
Further testing:

iPhone XR, iOS 14.4 Public Beta 2, Spine animation works with ORIGINAL condition
iPhone iPad AIR iOS 14.3 Release, Spine animation works with ORIGINAL condition

At least in my small testing official iOS 14.3 Release works with the ORIGINAL condition.

**Comment by badlogic** [comment]
The change has been reverted and verified on iOS 14.6
