### ISSUE TITLE
what  can i  parse the 3.7 binary file use javascript

### ISSUE THREAD

**Issue by q3226257** [EsotericSoftware/spine-runtimes#1834]
excuse me，what  can i  parse the 3.7 binary file use javascript

**Comment by HaraldCsaszar** [comment]
Please do not post questions as github issues. Would you mind posting your question on the Spine forum, please?
http://www.esotericsoftware.com/forum/
This way others can join the discussion and benefit from the answers. Don't worry, we tend to answer forum posts quite quickly! Thank you!
