### ISSUE TITLE
[ts] worldToLocalRotation() returns incorrect values, error amount is quite big

### ISSUE THREAD

**Issue by ShinhuPark** [EsotericSoftware/spine-runtimes#1836]
I imported skeleton in webgl runtime and apply the locatation/rotatation/scale of all bones with global(worldX) angles I parsed from other skeleton animation.

all bones are animated as I expected, except for one bone that rotates back and forth around the angle that it should be.
https://youtu.be/HvV-6EKxkvU

the angle calculated from bone.worldToLocalRotation() repeats two angles that are plus or minus by some error amount to the expected angle(in the video above, it should be between 0~5 degree, which is almost the average value of repeating values.

I tracked the a, b, c, d, rotation, shearX value of the bone when it starts to wiggle-wiggle.
'global rotation to apply' corresponds to the value I put as parameter of worldToLocalRotation().

```
frame : 16
 global rotation to apply : 59.71
 a : 0.5195181594435452
 b : -0.8210202594454984
 c : 0.7471284240399313
 d : 0.5708990572597284
 rotation : 178.35118927891028
 shearX : 0
 local rotation calculated by worldToLocalRotation() : 182.468538639338
frame : 17
 global rotation to apply : 59.7
 a : -0.13915575329380667
 b : 0.9887420882990631
 c : -0.9195301388890053
 d : -0.14962981930754288
 rotation : 182.468538639338
 shearX : 0
 local rotation calculated by worldToLocalRotation() : 342.16461794556807
frame : 18
 global rotation to apply : 59.52
 a : 0.8381920327735188
 b : -0.43323344171147493
 c : 0.40290708134133896
 d : 0.9012817456172239
 rotation : 342.16461794556807
 shearX : 0
 local rotation calculated by worldToLocalRotation() : 374.1158964445553
frame : 19
 global rotation to apply : 59.26
 a : -0.06153537736657333
 b : -0.9978085565182305
 c : 0.9279619589898894
 d : -0.06616709559142608
 rotation : 374.1158964445553
 shearX : 0
 local rotation calculated by worldToLocalRotation() : 341.4974280032252
frame : 20
 global rotation to apply : 59.08
 a : 0.8633436426801387
 b : -0.3717659613872986
 c : 0.34574232405620936
 d : 0.9283264888786582
 rotation : 341.4974280032252
 shearX : 0
 local rotation calculated by worldToLocalRotation() : 376.7702505160503
frame : 21
 global rotation to apply : 58.99
 a : -0.03848300771860522
 b : -0.9991434974966595
 c : 0.9292034535648959
 d : -0.04137960137727673
 rotation : 376.7702505160503
 shearX : 0
 local rotation calculated by worldToLocalRotation() : 345.2705974105002
```

And here's the inside of worldToLocalRotation() function in spine-webgl.js module.
```
Bone.prototype.worldToLocalRotation = function (worldRotation) {
	var sin = spine.MathUtils.sinDeg(worldRotation), cos = spine.MathUtils.cosDeg(worldRotation);
	return Math.atan2(this.a * sin - this.c * cos, this.d * cos - this.b * sin) * spine.MathUtils.radDeg + this.rotation - this.shearX;
};
```

And this is my code :
https://github.com/ShinhuPark/3d_to_2d_animating/blob/main/motion_capture.js

I suspect this is because of the calculation error in worldToLocalRotation() function.
Why is this happening? What could be reason for this, and what's the solution?

**Comment by badlogic** [comment]
I've spent a lot of time debugging this, as the manual modification of the bone data isn't straight forward. A bone's `a`, `b`, `c`, and `d` build an orthonormal basis, i.e. the local rotation expressed as 2 vectors relative to the world coordinate system. It appears you are scaling bones non-uniformly, e.g. by setting scaleX. This can result in a non-orthonormal basis, which will distort the results of `worldToLocalRotation()`. Check out the denormalization in e.g. frame 16 or `arm1_R` (the parent of the "problematic" bone) and `arm2_R`:

```
name: arm1_R
motion_capture.js:322 frame : 16
motion_capture.js:323 global rotation to apply : 308.06
motion_capture.js:324 a : -0.022310069956240117
motion_capture.js:325 b : 0.9478505056551957
motion_capture.js:326 c : -0.06634953487815624
motion_capture.js:327 d : -0.31871526309417586
motion_capture.js:328 rotation : -195.60788595456717
motion_capture.js:329 shearX : 0
motion_capture.js:330 cha bone rot: 308.06
motion_capture.js:331 local rotation calculated by worldToLocalRotation() : -189.53768127610223
motion_capture.js:321 name: arm2_R
motion_capture.js:322 frame : 16
motion_capture.js:323 global rotation to apply : 59.71
motion_capture.js:324 a : 0.5195181594435452
motion_capture.js:325 b : -0.8210202594454984
motion_capture.js:326 c : 0.7471284240399313
motion_capture.js:327 d : 0.5708990572597284
motion_capture.js:328 rotation : 178.35118927891028
motion_capture.js:329 shearX : 0
motion_capture.js:330 cha bone rot: 59.71
motion_capture.js:331 local rotation calculated by worldToLocalRotation() : 182.468538639338
Math.sqrt(-0.022310069956240117 * -0.022310069956240117 + 0.9478505056551957 * 0.9478505056551957)
0.9481130313903836
Math.sqrt(0.5195181594435452 * 0.5195181594435452 + -0.8210202594454984 * -0.8210202594454984)
0.9715829271923021
```

If the input `a`, `b`, `c` and `d` aren't orthonormal, all bets are off, and `worldToLocalRotation()` simply can not reconstruct a local rotation value properly. And since the parent "inherits" its basis to the child, those errors distribute and get large.

I'm afraid there's no mathematical way to compensate for this that I know of.
