### ISSUE TITLE
[ts][threejs] Missing some informations on SkeletonMeshMaterialParametersCustomizer available parameters

### ISSUE THREAD

**Issue by swingingtom** [EsotericSoftware/spine-runtimes#1844]
Hello EsotericSoftware and its community, 
I'm having hard time to figure out how to use the ` materialCustomizer?: SkeletonMeshMaterialParametersCustomizer` from the `SkeletonMesh constructor()`.

According to this https://github.com/EsotericSoftware/spine-runtimes/issues/1590 and that https://github.com/EsotericSoftware/spine-runtimes/issues/1590 and referring to `THREE. MeshStandardMaterialParameters extends MaterialParameters` I end up with this list possible parameters : 

```
        uniforms?: { [uniform: string]: IUniform };
	vertexShader?: string;
	fragmentShader?: string;
	linewidth?: number;
	wireframe?: boolean;
	wireframeLinewidth?: number;
	lights?: boolean;
	clipping?: boolean;
	skinning?: boolean;
	morphTargets?: boolean;
	morphNormals?: boolean;
	extensions?: {
		derivatives?: boolean;
		fragDepth?: boolean;
		drawBuffers?: boolean;
		shaderTextureLOD?: boolean;
	};
	glslVersion?: GLSLVersion;

        alphaTest?: number;
	blendDst?: BlendingDstFactor;
	blendDstAlpha?: number;
	blendEquation?: BlendingEquation;
	blendEquationAlpha?: number;
	blending?: Blending;
	blendSrc?: BlendingSrcFactor | BlendingDstFactor;
	blendSrcAlpha?: number;
	clipIntersection?: boolean;
	clippingPlanes?: Plane[];
	clipShadows?: boolean;
	colorWrite?: boolean;
	defines?: any;
	depthFunc?: DepthModes;
	depthTest?: boolean;
	depthWrite?: boolean;
	fog?: boolean;
	name?: string;
	opacity?: number;
	polygonOffset?: boolean;
	polygonOffsetFactor?: number;
	polygonOffsetUnits?: number;
	precision?: 'highp' | 'mediump' | 'lowp' | null;
	premultipliedAlpha?: boolean;
	dithering?: boolean;
	flatShading?: boolean;
	side?: Side;
	shadowSide?: Side;
	toneMapped?: boolean;
	transparent?: boolean;
	vertexColors?: boolean;
	visible?: boolean;
	stencilWrite?: boolean;
	stencilFunc?: StencilFunc;
	stencilRef?: number;
	stencilMask?: number;
	stencilFail?: StencilOp;
	stencilZFail?: StencilOp;
	stencilZPass?: StencilOp;
```

So I tried with `fog` boolean 

```
    this.skeletonMesh = new spine.threejs.SkeletonMesh(skeletonData, function(parameters) {
      parameters.fog = true;
    });
```
But this leads to 
```
Uncaught TypeError: Cannot read property 'value' of undefined
    at Object.refreshFogUniforms (three.module.js?5a89:22384)
```
So the current uniforms seems not ready to handle fog I guess...

Can you give us some hints or some guidelines on which parameters can be set ? Or should we do ie:  refresh/rebuild the material ?

I might be completely wrong by reaching this path, but what I try to achieve is to lighten the Skeleton with some lights and also apply the fog on it too. Like we can have on MeshStandardMaterial.

Thanks in advance,

**Comment by badlogic** [comment]
The runtime doesn't use `MeshStandardMaterial` but the more lower level `ShaderMaterial` https://github.com/EsotericSoftware/spine-runtimes/blob/e60a60ccd5cfa4bd38ea95118eae02b365d26141/spine-ts/threejs/src/SkeletonMesh.ts#L35

Our fragment and vertex shaders do not support lighting out of the box. You could override the shaders to support that via the customizer.
