### ISSUE TITLE
skel、atlas、png 。How to rende？

### ISSUE THREAD

**Issue by lixue128** [EsotericSoftware/spine-runtimes#1859]
skel、atlas、png 。Is there a corresponding NPM package？

**Comment by lixue128** [comment]
Looking forward to the author's reply 
Thanks！！！

**Comment by HaraldCsaszar** [comment]
Please see the documentation pages here:
http://esotericsoftware.com/spine-runtimes
In general, please do not post questions as github issues, but post on the forum instead:
http://esotericsoftware.com/forum/
