### ISSUE TITLE
[cpp] Animations with IK Constraints not behaving as expected

### ISSUE THREAD

**Issue by cp4117** [EsotericSoftware/spine-runtimes#1860]
I've noticed an issue in IkConstraint.cpp which leads to animations that use such constraints to not animate correctly.  

Going through the json implementation I noticed the label `break_outer` is in a different location.  Moving this goto label from line 240 to 176 to line up with the json implementation appears to fix the issue.

**Comment by badlogic** [comment]
I've tried to reproduce this with our stretchyman example, which triggers the `goto break_outer`. It behaves as expected and in line with the reference implementation. Happy to reopen if you can supply me with an animation that does not work for you.
