### ISSUE TITLE
[unity] Binary file incorrectly reported as json and import aborted

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1867]
As reported on the forum:
http://esotericsoftware.com/forum/Unity-Import-Error-15600

**Comment by rekcah1986** [comment]
public static bool IsJsonFile (TextAsset file) {
    string fileText = file.text;
    ...

fileText is "" in my project.

**Comment by HaraldCsaszar** [comment]
@rekcah1986 Is it aborting import for a correctly exported asset? Could you please post your problematic asset, then we can check what's going wrong.

**Comment by rekcah1986** [comment]
[test.zip](https://github.com/EsotericSoftware/spine-runtimes/files/6240736/test.zip)

**Comment by HaraldCsaszar** [comment]
@rekcah1986 Thanks for sending the project. Unfortunately we fail to see any incorrect behaviour, your file imports without any error. What kind of problem did you encounter?

**Comment by rekcah1986** [comment]
![image](https://user-images.githubusercontent.com/3055444/113370995-c76baf00-9397-11eb-8c11-a503b89b1be9.png)
![image](https://user-images.githubusercontent.com/3055444/113372017-406c0600-939a-11eb-868b-0b4aaba5fdc6.png)

**Comment by HaraldCsaszar** [comment]
Thanks for posting the screenshots. Interestingly we did not receive an empty string here, but it could be locale-related or due to similar differences. We will modify the code accordingly.

**Comment by HaraldCsaszar** [comment]
@rekcah1986 We have just pushed a fix for your issue, a new 3.8 spine-unity unitypackage has been released and is available for download. 4.0-beta packages will follow in the next few days.

**Comment by rekcah1986** [comment]
@HaraldCsaszar Thank you very much ~

**Comment by HaraldCsaszar** [comment]
You're welcome, thanks for reporting.
