### ISSUE TITLE
[libgdx]a ArrayIndexOutOfBoundsException crash at SkeletonJson.java line:751

### ISSUE THREAD

**Issue by qlang122** [EsotericSoftware/spine-runtimes#1878]
version: v3.8.55.1
crash info:
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=22; index=22
        at com.esotericsoftware.spine.SkeletonJson.readAnimation(SkeletonJson.java:751)
        at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:342)

lib code:
int[] unchanged = new int[slotCount - offsets.size];
int originalIndex = 0, unchangedIndex = 0;
for (JsonValue offsetMap = offsets.child; offsetMap != null; offsetMap = offsetMap.next) {
	SlotData slot = skeletonData.findSlot(offsetMap.getString("slot"));
	if (slot == null) throw new SerializationException("Slot not found: " + offsetMap.getString("slot"));
	// Collect unchanged items.
	while (originalIndex != slot.index)
		unchanged[unchangedIndex++] = originalIndex++;
	// Set changed items.
	drawOrder[originalIndex + offsetMap.getInt("offset")] = originalIndex++;
}

**Comment by badlogic** [comment]
Please provide the Spine Editor version you used, fhe spine-runtimes version, and the .json file that crashes. I'll re-open then.

**Comment by qlang122** [comment]
It doesn't matter, although it's a problem with JSON files. but this index, emmm..
