### ISSUE TITLE
Error reading skeleton JSON file for SkeletonData asset: mcandidate_SkeletonData 

### ISSUE THREAD

**Issue by jiji-Bi** [EsotericSoftware/spine-runtimes#1885]
Error reading skeleton JSON file for SkeletonData asset: mcandidate_SkeletonData
Unsupported skeleton data, please export with a newer version of Spine.
Solved by renaming  "spine": "3.8.75" [Solved: Change to 3.8.0] (located in the .json file )

**Comment by alfaro-92** [comment]
Thanks, that was very helpful
