### ISSUE TITLE
[ts] Spine Player fails to load skeleton .json file

### ISSUE THREAD

**Issue by Pionell** [EsotericSoftware/spine-runtimes#1888]
Part of the exported spines are not working on web.
js lib - https://esotericsoftware.com/files/spine-player/3.8/spine-player.js
spine.json -"spine":"3.8.99"

the console does not throw any errors, it just fails to load, giving this error (even though the file is there): 
Error: cound not load skeleton .json
{}

I only see one common correlation between the 2 working spines: their json files aren't minified.
We tried to export the skeletons multiple different ways - with/without pretty print, with/without nonesential data.

Some of the spines work and some of them don't...

I can provide a url where the problem would be visible if that would be helpful.

**Comment by badlogic** [comment]
Please provide the assets that don't load with spine-player.

**Comment by Pionell** [comment]
[http://2021.tutotoons.com/assets/spines/fluvsieTest/fluvsieTest.json](http://2021.tutotoons.com/assets/spines/fluvsieTest/fluvsieTest.json)
[http://2021.tutotoons.com/assets/spines/fluvsieTest/fluvsieTest.atlas](http://2021.tutotoons.com/assets/spines/fluvsieTest/fluvsieTest.atlas)
[http://2021.tutotoons.com/assets/spines/fluvsieTest/fluvsieTest.png](http://2021.tutotoons.com/assets/spines/fluvsieTest/fluvsieTest.png)

**Comment by badlogic** [comment]
I've used your assets with the Spine Web Player example in spine-ts/player/example from the 3.8 branch and it works as intended.

<img width="643" alt="Screenshot 2021-05-14 at 13 44 34" src="https://user-images.githubusercontent.com/514052/118266304-b21b9180-b4ba-11eb-94d9-9d92692cdcec.png">

```
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<script src="https://esotericsoftware.com/files/spine-player/3.8/spine-player.js"></script>
	<link rel="stylesheet" href="https://esotericsoftware.com/files/spine-player/3.8/spine-player.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<style>
body {
	background: gray;
	margin: 0px;
}
</style>

<body>
	<div id="container" style="width: 640px; height: 380px;"></div>	
</body>
<script>
	// Creates a new spine player. The debugRender option enables
	// rendering of viewports and padding for debugging purposes.
	new spine.SpinePlayer("container", {
		jsonUrl: "assets/fluvsieTest.json",
		atlasUrl: "assets/fluvsieTest.atlas",
		animation: "action",
		premultipliedAlpha: true,
		backgroundColor: "#cccccc",
		viewport: {
			debugRender: true,
		},
		showControls: false,
	});
</script>
</body>
</html>
```

Running a simple Python server in `spine-ts/` via `python -m SimpleHTTPServer` (Python 2.7).

Could it be that you serve the assets with an incorrect MIME Type or try to access them from a different domain without having CORS enabled?

**Comment by Pionell** [comment]
What we narrowed it down is "using indexes" checkbox when exporting the assets in the texture packer settings.
I was using an apache web server, unmodified. On a local machine/multiple servers with no differences whatsoever.
When inspecting the asset loading through the inspect element - network tab - they load just fine.

**Comment by badlogic** [comment]
I've used the files from your links above from today. Were these exported with the "using indexes" checkbox checked or unchecked? It appears it was unchecked, as some atlas regions have number suffices. For loading the skeleton and atlas, it should not matter at all if this setting is set.

If you've updated the assets with the working setting, could you maybe send me the assets exported with the setting that was not working? I don't have any projects setup like yours, so it's hard to reproduce for me.

**Comment by Pionell** [comment]
yes, we updated the files as we were testing it throughout the day trying to narrow down what is working and what is not. 
Here is the version that is not working for us:
https://2021.tutotoons.com/assets/spines/not_working.zip

**Comment by Pionell** [comment]
> I've used the files from your links above from today. Were these exported with the "using indexes" checkbox checked or unchecked? 

checked - throws skeleton .json not found error
unchecked - works fine
Although this setting is only a presumption, we've tried a couple of other things as well.

**Comment by badlogic** [comment]
Thank you for the repro files. indeed, having the texture atlas option checked will not work. The attachments `ice_1` to `ice_5` will get rewritten to just `ice`. However, the skeleton `.json` file references them by their indexed name, i.e. `ice_1`. Looking those attachments up will fail, as the atlas only has attachments named `ice`. This is intended behaviour (though I'll circle that back with Nate, who designed this option).

On a related note, it seems the error reporting is swallowing the exception for some reason. That would have given us a quicker way to identify the issue:

```
Error: Region not found in atlas: ice_1 (mesh attachment: ice_1)
    at AtlasAttachmentLoader.newMeshAttachment (spine-player.js:2443)
    at SkeletonJson.readAttachment (spine-player.js:5825)
    at SkeletonJson.readSkeletonData (spine-player.js:5742)
    at SpinePlayer.loadSkeleton (spine-player.js:11440)
    at SpinePlayer.drawFrame (spine-player.js:11334)
    at spine-player.js:11323
```

I'll fix that up in the player sources.

Thanks for reporting!
