### ISSUE TITLE
[ts] Rotation timeline cause positional drift

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#1889]
See http://esotericsoftware.com/forum/Spineruntime3-8-Canvas-mode-position-and-size-error-BUG-15823 for repro assets.

**Comment by yyetest** [comment]
I tried to solve it myself, but failed, as if the problem was not with the core but with the SkeletonRenderer

**Comment by badlogic** [comment]
I came to the same conclusion, that it's not an issue in spine-ts but in the canvas implementation of `SkeletonRenderer`. However, I'm still trying to figure out what exactly is going wrong. The data fed to canvas looks correct to me.

**Comment by NathanSweet** [comment]
I converted the project to 4.0 and reproduced the problem with the 4.0 runtimes. I then repacked the atlas without whitespace stripping and confirmed it works correctly without whitespace stripping.
http://n4te.com/x/1911-assets.zip

**Comment by NathanSweet** [comment]
The fix was this line used `region.width`:
```
let atlasScale = attachment.width / region.originalWidth;
```

I also ported RegionAttachment `updateOffset` from spine-csharp (hard to tell if it is the same, but seems to be), then decided the old spine-ts method had fewer operations, so I changed csharp to use the ts code.
