### ISSUE TITLE
[unity] Error reading skeleton JSON file for SkeletonData asset: coin-pro_SkeletonData

### ISSUE THREAD

**Issue by xuzhuoxi** [EsotericSoftware/spine-runtimes#1898]
Import demo "coin-pro" error :
Error reading skeleton JSON file for SkeletonData asset: coin-pro_SkeletonData
Unsupported skeleton data, please export with a newer version of Spine.

Spine version: 3.8.75 Professional
Package version: spine-unity-3.8-2021-06-01.unitypackage
Unity version: 2019.4.26f1c1

**Comment by badlogic** [comment]
Please export your data with a newer version of Spine.
