### ISSUE TITLE
[spine-ts] limitation on max webgl context being 8 for android devices

### ISSUE THREAD

**Issue by Pionell** [EsotericSoftware/spine-runtimes#1901]
When I add more than 8 spine characters on a webpage (the layout requires this) - I get an error, and the first webgl context destroys itself.
Error:
`Too many active WebGL contexts. Oldest will be lost.`
Is there any way to avoid this?

**Comment by badlogic** [comment]
I assume you are using the web player. Each instance has it's own canvas and thus WebGL context. Different browsers across various OS' have different maximally supported instances of WebGL contexts. This is a browser limitation which we have no control over. There are two options:

1. Render the skeletons into a single canvas. The easiest way to achieve this is via pixi-spine, unless you feel comfortable doing lower level work by using our spine-ts WebGL runtime.
2. If not all characters and thus player instances are visible on the page, you can "juggle" a maximum number of contexts. 4 is save for mobile browsers. The way this works is to allocate 4 canvases and corresponding WebGL contexts. Next setup container divs, sized and layouted as you need them. Register a callback on page scroll changes and check which divs are visible. Then relocate canvases to those divs as needed. This is very involved and tricky to get right. We did it for our live demos https://esotericsoftware.com/spine-demos. The page includes a link to the sources on GitHub.
