### ISSUE TITLE
[spine-ts] Demo HTML5 WebGL – JavaScript/TypeScript is not functional

### ISSUE THREAD

**Issue by alex94539** [EsotericSoftware/spine-runtimes#1907]
https://esotericsoftware.com/files/runtimes/spine-ts/examples/webgl/
https://esotericsoftware.com/files/runtimes/spine-ts/examples/threejs/index.html

all got same error
```
Uncaught TypeError: Cannot read property 'getAttachment' of null                                 SkeletonJson.ts:778
    at SkeletonJson.readAnimation (SkeletonJson.ts:778)
    at SkeletonJson.readSkeletonData (SkeletonJson.ts:274)
    at loadSkeleton (index.html:82)
    at load (index.html:56)
```
and I got same error when trying to load these data into [WebGL](https://esotericsoftware.com/files/runtimes/spine-ts/build/spine-webgl.js) runtimes which were functional last week
[big_cloth0.zip](https://github.com/EsotericSoftware/spine-runtimes/files/6681067/big_cloth0.zip)

**Comment by badlogic** [comment]
We are in the processing of releasing Spine 4.0, so some things are in flight. Your assets are exported via Spine 3.8. Please use the runtime from the corresponding branch here on GitHub.

**Comment by NathanSweet** [comment]
I've updated the specified links to 4.0.

As mentioned, to use the 4.0 runtimes you'll need to export your data with the 4.0 editor:
http://esotericsoftware.com/spine-versioning#Synchronizing-versions
