### ISSUE TITLE
[unity] Enabled `CanvasGroup compatible` on TintBlack shader causes incorrect rendering

### ISSUE THREAD

**Issue by birdkingz** [EsotericSoftware/spine-runtimes#1908]
Hi, 

Here's the sample project to demonstrate what's the problem.
I'm using spine-unity 3.8 (updated 2021-06-01)

[Sample Project](https://drive.google.com/file/d/1k0xOMZLaBQw--EnRepXEXa2FQZQvrC8o/view?usp=sharing)

**Comment by HaraldCsaszar** [comment]
Thanks for reporting. Please always check the official docs pages first.

http://esotericsoftware.com/spine-unity#Shaders
> `Spine/Skeleton Graphic (Default shader for SkeletonGraphic)`
> [..] Does not support Additive blend mode when used with a `CanvasGroup`, when required use `Spine/Skeleton Graphic Tint Black` instead.

**Comment by birdkingz** [comment]
I followed the docs to set up yet the result isn't the same as using the standard Spine shader.
Is this the limitation of the plugin?

[Updated Sample Project](https://drive.google.com/file/d/1yvheGx34cfZktKY-adABBeAlK2kPCvpC/view?usp=sharing)

**Comment by HaraldCsaszar** [comment]
It indeed seems like there is a bug in the implementation, we could reproduce the differences thanks to your example project. Thanks for reporting back.

**Comment by HaraldCsaszar** [comment]
We have just fixed the issue on the 4.0 branch, a new 4.0 unitypackage is available for download:
http://esotericsoftware.com/spine-unity-download
If you are using spine-unity 3.8, you can either apply the above commit manually or copy the `MeshGenerator.cs` file from 4.0 over the existing 3.8 implementation. 
Thanks for reporting!

**Comment by Lucaffo** [comment]
Hi! I know it's an old question and it's not related strictly to spine, but how do you make your shaders to works correctly with CanvasGroup?
