### ISSUE TITLE
[spine-ts] [v4.0] SpinePlayer constructor throws "cannot read property appendChild of undefined" when config is invalid

### ISSUE THREAD

**Issue by mayorandrew** [EsotericSoftware/spine-runtimes#1909]
When config is invalid, `SpinePlayer` constructor calls the `showError` function:
https://github.com/EsotericSoftware/spine-runtimes/blob/c1e18a2237f98ee9bcbc769be4cc1ada9f74887c/spine-ts/player/src/Player.ts#L216

Which tries to call `this.dom.appendChild` while `this.dom` is still undefined at that point.
https://github.com/EsotericSoftware/spine-runtimes/blob/c1e18a2237f98ee9bcbc769be4cc1ada9f74887c/spine-ts/player/src/Player.ts#L1022

This throws an error `cannot read property appendChild of undefined` instead of actual error which should be thrown.

`this.dom` is defined only when `this.create()` is called here:
https://github.com/EsotericSoftware/spine-runtimes/blob/c1e18a2237f98ee9bcbc769be4cc1ada9f74887c/spine-ts/player/src/Player.ts#L221
https://github.com/EsotericSoftware/spine-runtimes/blob/c1e18a2237f98ee9bcbc769be4cc1ada9f74887c/spine-ts/player/src/Player.ts#L269

I suggest moving creation of `this.dom` into a separate function from inside of `this.create`, and use `appendChild` in `this.create` to append controls if `showControls` is set.

**Comment by NathanSweet** [comment]
Sorry about that. `dom` is now set before validating the config.
https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-ts/player/src/Player.ts#L235
