### ISSUE TITLE
[corona] :setReferencePoint vs anchor

### ISSUE THREAD

**Issue by wojciak** [EsotericSoftware/spine-runtimes#191]
Is the code:
image:setReferencePoint(display.CenterReferencePoint)
there for a purpose? This is depracated in graphics v2 (http://www.develephant.net/3-things-you-need-to-know-about-corona-sdk-graphics-2-0/)
and should be translated to
image.anchorX = .5
image.anchorY = .5

**Comment by badlogic** [comment]
Fixed in spine-lua-update branch, to be merged into master.
