### ISSUE TITLE
[unity] Shader bugfix for Unity 2021.2 beta

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1912]
As reported on the forum, Unity beta 2020.2b1 reports a shader error:
http://esotericsoftware.com/forum/ALPHA-2021-2-a19-Skeleton-Lit-15920
A bugfix is already provided, however with a remark that colors are somehow off.

**Comment by HiKit** [comment]
same error. worry up

**Comment by HaraldCsaszar** [comment]
There is no use commenting that one gets the same error on unsupported versions, as everyone will get the same error under the same conditions. Having to read it costs us time that could be spent in better ways.
