### ISSUE TITLE
[UE4] Spine animation doesn't work with UE4 widget animation (ignoring render transform)

### ISSUE THREAD

**Issue by alex-kolb** [EsotericSoftware/spine-runtimes#1914]
Hi,

If we use spine animation with UE4 widget animations it doesn't work together, seems you need to replace line 199 in SSpineWidget.cpp (branch 4.0) from:
	FVector2D offset = AllottedGeometry.AbsolutePosition;
to:
	FVector2D offset = AllottedGeometry.GetAbsolutePositionAtCoordinates(FVector2D(0.0f, 0.0f));

**Comment by badlogic** [comment]
Thank you for reporting, this has been fixed in the 4.0 branch.
