### ISSUE TITLE
spine-cpp doesn't build on macOS

### ISSUE THREAD

**Issue by JCash** [EsotericSoftware/spine-runtimes#1922]
I'm using `Apple clang version 12.0.0 (clang-1200.0.32.28)`

It complains about several `error: a space is required between consecutive right angle brackets (use '> >')` which is a C++11 feature.

From the [README.md](https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-cpp/README.md):

`Note, this library uses C++03 for maximum portability and therefore does not take advantage of any C++11 or newer features such as std::unique_ptr.`

Repro steps:

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release .. 
make -j8
```

**Comment by badlogic** [comment]
Uff, formatter strikes again. Was applying it a second time after checking all builds. Sorry for the trouble. I'm setting up automated builds for all supported compilers to catch this early. Thanks for reporting.
