### ISSUE TITLE
[c] spVertexAttachment_computeWorldVertices() access violation

### ISSUE THREAD

**Issue by kikuuuty** [EsotericSoftware/spine-runtimes#1926]
An access violation occurs in spVertexAttachment_computeWorldVertices() when using the spine-c 4.0 runtime and Spine 4.0.04.
spine-c 4.0ランタイムとSpine 4.0.04を使用した場合に、spVertexAttachment_computeWorldVertices()でアクセス違反が発生します。

![0](https://user-images.githubusercontent.com/5368780/125729064-cde10148-9dda-45bc-adbe-bd386736477f.png)

The same asset did not cause any problems when using spine-c 3.8 runtime and Spine 3.8.99.
spine-c 3.8ランタイムとSpine 3.8.99を使用した場合において、同様のアセットで問題は起きていませんでした。

**Comment by badlogic** [comment]
Please send is your .skel or .json file. Email works too contact@esotericsoftware.com. Please include a link to this issue in your email.

**Comment by kikuuuty** [comment]
I have sent you an email. Please check it.

**Comment by Nitrillo** [comment]
I had the same crash after converting some files from 3.8 to the 4.0 version. @kikuuuty I have a small patch to avoid the crash (but probably not a proper fix) in case you need it.

**Comment by kikuuuty** [comment]
@Nitrillo I'm in no hurry to update to 4.0, so I'm good!

**Comment by badlogic** [comment]
@kikuuuty thank you for the report! This is now fixed via this commit https://github.com/EsotericSoftware/spine-runtimes/commit/ac86ef9ce8646c50d4d35b03cd6cc841b81f527f
