### ISSUE TITLE
[c] Reproduceable vertex coordinate glitch (with demo)

### ISSUE THREAD

**Issue by AbePralle** [EsotericSoftware/spine-runtimes#1927]
I'm getting a fairly consistent bug with a particular pair of animations when queued in sequence. Everything is fine at first and then suddenly the vertex coordinates are wildly inaccurate. It looks like a missing initialization + garbage memory issue as the numbers are different every time. There is about a 50% chance it will happen any given animation playthrough.

I've been integrating a bunch of Spine animations in my game and all other states & animations have been working fine; it's just this particular pair that are glitching.

I made a C console demo of the bug: https://github.com/AbePralle/SpineRuntimeBug

**Comment by badlogic** [comment]
Thank you for the excellent repro! This is fixed in the 4.0 branch now.
