### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/spine-runtimes#1932]
I hope someone can provide spine skeletonviewer 3.8.75 for me,since I can't use 3.8.99 to load my spine files.

[test.zip](https://github.com/EsotericSoftware/spine-runtimes/files/6904664/test.zip)

**Comment by badlogic** [comment]
You can find skeleton viewer for previous releases here: http://en.esotericsoftware.com/spine-skeleton-viewer

Kust match the major.minor version of your files to the skeleton viewer version.
