### ISSUE TITLE
[libgdx] Maven central release for version 4 spine-libgdx?

### ISSUE THREAD

**Issue by cfnz** [EsotericSoftware/spine-runtimes#1934]
Hi, just learning libgdx and Spine and have been trying to use a version 4 file in kotlin/java.

Is there, or will there be soonish, a maven central release of spine-libgdx?

The readme implies there is one:
```
    dependencies {
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"

        compile "com.esotericsoftware.spine:spine-libgdx:4.0.02.1"
    }
```
But this does not seem to work for me... also searching maven central only brings up a 3.8.xxx version (if I am looking for the right thing that is).

**Comment by badlogic** [comment]
Sorry there seems to have been an issue with deploying via SonaType. I'll rerelease this today

**Comment by badlogic** [comment]
spine-libgdx `4.0.18.1` has now been released to Maven Central. It may take a few hours for the mirroring to go through.

**Comment by cfnz** [comment]
👍
