### ISSUE TITLE
[c] Lack of Android and iOS support

### ISSUE THREAD

**Issue by enfipy** [EsotericSoftware/spine-runtimes#1942]
I tried to build a rust wrapper of [spine](https://github.com/axieinfinity/spine-rs) and got errors for Android and iOS targets. Is this on the spine-c side?

**Comment by badlogic** [comment]
spine-c is a platform independent runtime and used by 3rd parties, like spine-rs, to build platform specific runtimes. It compiles with every C compiler under the sun, including Clang used by Android and iOS. I'm afraid I do not know how spine-rs works in combination with iOS or Android. As such, this is something that you have to take up with the spine-rs maintainers.
