### ISSUE TITLE
[monogame][xna] Discontinue spine-xna in favor of spine-monogame

### ISSUE THREAD

**Issue by julhe** [EsotericSoftware/spine-runtimes#1949]
I'm trying to run the example for the monogame implementation. However, loading the ``spine-monogame-example`` project fails with this message:
```
C:\Users\Julian\wkspaces\PUBLIC\spine-runtimes\spine-monogame\example\spine-monogame-example.csproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets" was not found. Also, tried to find "MonoGame\v3.0\MonoGame.Content.Builder.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\Julian\AppData\Local\Microsoft\VisualStudio\16.0_40d2f8fe\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Users\Julian\wkspaces\PUBLIC\spine-runtimes\spine-monogame\example\spine-monogame-example.csproj
```

Im on Windows 10 64-Bit with Visual Studio 2019. (Building anything in MonoGames works.)

--- 
Digging deeper, the monogame implementation seems to depend on ``spine-xna``, which I cannot open either:
```
C:\Users\Julian\wkspaces\PUBLIC\spine-runtimes\spine-xna\spine-xna.csproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\XNA Game Studio\Microsoft.Xna.GameStudio.targets" was not found. Also, tried to find "Microsoft\XNA Game Studio\Microsoft.Xna.GameStudio.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "C:\Users\Julian\AppData\Local\Microsoft\VisualStudio\16.0_40d2f8fe\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Users\Julian\wkspaces\PUBLIC\spine-runtimes\spine-xna\spine-xna.csproj
```
I saw on the [XNA-Spine readme](https://github.com/EsotericSoftware/spine-runtimes/tree/4.0/spine-xn)  that I have to install XNA 4.0, where the link would just lead me to this project [https://mxa.codeplex.com/releases/view/618279](), but I can't make any sense out of it how to install this.

**Comment by badlogic** [comment]
Sorry for the late reply to this! It appears there's no longer a way to get spine-xna up and running. We will discontinue spine-xna in favor of spine-monogame, which will mean we'll also update the example project accordingly. I've updated this issues title to reflect this.

**Comment by badlogic** [comment]
We have now discontinued spine-xna in favor of spine-monogame in the 4.1-beta branch and updated the documentation accordingly.
