### ISSUE TITLE
Too many materials, high DC, affecting the frame rate and poor game experience.

### ISSUE THREAD

**Issue by scc172fly** [EsotericSoftware/spine-runtimes#1950]
Unity 2020.3.14f1
Spine Runtime 3.8.xx

I don't understand why I only have one atlas and two materials. Why do I have so many mesh materials? What's the use of this atlas and materials? Can't bring me any optimization? This problem bothers me so much that I have no reason to continue to use it. Excuse me, is this problem caused by my improper operation, your bug or the problem when making the editor? I'm in a hurry. Can you help me solve this problem?

![20210907105031](https://user-images.githubusercontent.com/7484984/132276726-24fb0e8b-9213-4a07-91b2-a0cc6fcedadb.png)

**Comment by HaraldCsaszar** [comment]
You seem to have organized your draw order badly.
http://esotericsoftware.com/spine-unity#Material-Switching-and-Draw-Calls
When mixing normal and multiply slots, be sure to group them to reduce necessary material switches.
