### ISSUE TITLE
How to load spine animation json file in react-native

### ISSUE THREAD

**Issue by tusharprajapati8888** [EsotericSoftware/spine-runtimes#1952]
I have a spine animation JSON file I want to load that in my project.

I found [this](https://medium.com/substantial/animation-in-unity-and-react-native-166d6f069a3c) blog regarding the spine animation.

> Attempts to use middleware animation tools like Spine in combination with React Native were not successful. Spine had many different runtimes but nothing out of the box for RN. We would have had to import WebGL-react-native and glue it together with our own custom tooling.

I am using react native so is there any library/SDK that helps me to load JSON files. Or is this library support in react native if yes what's the step to implement in react native I am not able to find anything regarding react native.

Any help would be highly appreciated.

**Comment by badlogic** [comment]
Please use the forums for general questions like this: https://esotericsoftware.com/forum.

To answer your question here: there is currently no way to integrate Spine with React Native. While spine-ts, our browser runtimes, are written in TypeScript that's compiled to JavaScript, they won't run in React Native, as that's not a browser environment.

For Spine to work with React Native we'd have to build iOS and Android specific APIs in Swift and Java, which can then be integrated with React Native via bindings. Alternatively, the spine-ts core API could be combined with React Native. However, that would require rendering being performed through React Native APIs, which currently are not flexible enough to draw arbitrary textured triangle meshes.

So the short answer: there's no way to integrate Spine with react-native and we currently have no plans to add this capability.
