### ISSUE TITLE
[Unity] "Initial Flip" doesn't currently show the flip in Editor mode

### ISSUE THREAD

**Issue by Jamez0r** [EsotericSoftware/spine-runtimes#1953]
Pressing the "Initial Flip X" checkbox on a SkeletonAnimation in Editor mode currently doesn't show the flip. However, when you run the game it does then correctly flip the skeleton.

To repro **(TL:DR: Using the latest runtime, press the "Initial Flip X" button)**
1) New project with most current spine-unity runtime
2) Create SkeletonAnimation using Spine Examples > Spine Skeletons > Dragon
3) Press the "Initial Flip X" button on the SkeletonAnimation -> The skeleton doesn't flip (in Editor mode)
4) Run game, the skeleton is correctly flipped.

In Editor mode, if you press "Reload" on the skeleton after changing the Flip, it then updates it to show the correct flip.

Skeletons that were previously flipped in my actual project are still correctly flipped in Editor mode. It just isn't updating them if I make a new change to the Flip value.

**Comment by HaraldCsaszar** [comment]
Remark: reported on the forum here:
http://esotericsoftware.com/forum/Initial-Flip-doesn-t-currently-show-flip-in-Editor-mode-16457
