### ISSUE TITLE
[Unity] "Update When Invisible" setting causing strange Event timing

### ISSUE THREAD

**Issue by Jamez0r** [EsotericSoftware/spine-runtimes#1954]
Using the latest Spine-Unity runtime, and using SkeletonAnimation component. Unity version 2020.2.0f1.

### The Issue: 

1) The SkeletonAnimation has "Update When Invisible" set to "Only Animation Status".
2) The skeleton is currently deemed "invisible".
3) An animation is played on the skeleton, and it gets to 50% completed.
4) The skeleton then becomes "visible".
5) A spine event that is keyed earlier in the animation (in my case, on frame 0) is processed immediately when it became "visible".

**Link to repro project: https://drive.google.com/file/d/12hrwj2LKyegx61Gd7wPf7wtzMIqBWpDw/view?usp=sharing**

In the repro project, the SkeletonAnimation has an animation called "abilities/disengage/Back". This animation has an Event keyed near the beginning of the animation called "audio/Fallen_Rider_Disengage".
The character in unity is set up so that you can press "F" to trigger the disengage animation, and when the Spine Event is processed, it will log it to the console.

**Steps to reproduce:**
1) Run the game, note that the character is fully visible, and press "F". The console logs the Spine Event right near the beginning of the animation. Also note that the disengage animation is around 2 seconds long.
2) Disable the Mesh Renderer on the character (the character is now "not visible").
3) Press "F" to activate the animation, then wait 1 second and re-enable the Mesh Renderer. The console will log the Spine Event, even though the animation was already halfway completed when it became visible again.

Forum Post: http://esotericsoftware.com/forum/Update-When-Invisible-setting-causing-strange-Event-timing-16448

### Side question, possibly related:

When the Mesh Renderer is re-enabled, the character appears for 1 frame at the last position they were when they were previously visible (easy to see if you pause the game right before re-enabling the Mesh Renderer, and then step forward frame-by-frame). 
The fix that I had been doing for this in my actual project was to call skeletonAnimation.Update(0) immediately when my character goes from being "not visible" to "visible" (mentioned in this forum post: http://esotericsoftware.com/forum/Switching-visible-skeleton-while-maintaining-animations-14377?p=63363&hilit=update+when+invisible#p63363). 

Essentially just like this (simplified version):
```
private void Update() {
        if (skeletonShouldBecomeVisibleThisFrame) {
            skeletonAnimation.Update(0f);
            meshRenderer.enabled = true;
        }
    }

```

But I recently noticed (around the time I updated to Spine 4, but I was refactoring some of my own code at the same time, so I assumed it was something I might have changed in my code) that this doesn't seem to be working anymore in my actual project. I am not sure if there is a new 'order of operations' going on or if something else would be required to fix this 1-frame positioning. Could something have changed in the runtime to have caused this? If I need to provide more info on this just let me know, or if I should submit this as a separate issue or question on the forum.

Thanks a lot!

**Comment by HaraldCsaszar** [comment]
The above commit fixes both issues (which were not related). A new 4.0 unitypackage is available for download:
http://esotericsoftware.com/spine-unity-download
