### ISSUE TITLE
how to  async load spine in cocos2d

### ISSUE THREAD

**Issue by HelloAndGoodbye0** [EsotericSoftware/spine-runtimes#1957]
how to  async load spine in cocos2d

**Comment by badlogic** [comment]
Please post such questions on our forums at https://esotericsoftware.com/forum.

As for async loading of Spine skeleton and atlas files: there is no mechanism in cocos2dx to load arbitrary resources asynchronoulsy. The only resource cocos2dx can load asynchronously are image files. This could be done for atlas pages, but would not solve loading the atlas and skeleton files asynchronously.
