### ISSUE TITLE
[c] The C runtime doesn't build due to missing argument in findPathConstraintIndex

### ISSUE THREAD

**Issue by JCash** [EsotericSoftware/spine-runtimes#1958]
```
spine-runtimes-4.0.31/spine-c/spine-c/src/spine/SkeletonJson.c:633:79: error: too few arguments to function call, expected 3, have 2
                int constraintIndex = findPathConstraintIndex(skeletonData, constraint->name);
```

In my case, I'm building all the *.c files using the includes provided in the `spine-c` folder.

How do you build this before release?
Do you have an autobuilder for this?

Regards,
Mathias

**Comment by JCash** [comment]
Ok, so the main (alpha) 4.0 branch builds correctly.
I suggest you make a new release since the current one doesn't build.

**Comment by badlogic** [comment]
Sorry for the error in the release. We generally suggest to use the latest commit on the version branch of the editor version you are using. Only <version>-beta branches are considered unstable. And while we try to be diligent, sometimes an error like you encountered sneaks into a release branch.
