### ISSUE TITLE
[Unity] "Update When Invisible" + Skeleton Render Separator = Invisible Character

### ISSUE THREAD

**Issue by Jamez0r** [EsotericSoftware/spine-runtimes#1960]
Figured out the steps to recreate the (initial) issue I posted here: http://esotericsoftware.com/forum/Mesh-Filter-lost-reference-None-16384

If a character is using the "Update When Invisible - Only Animation Status" setting along with a Skeleton Render Separator, the character can get into a situation where none of the Meshes are visible

Youtube video showing the steps: [https://youtu.be/MIe6nV9xahE](https://youtu.be/MIe6nV9xahE)

Also noted at 3:00 in the video, its possible to have the Skeleton Render Separator disabled, but the actual Parts Renderers still active. 

Another thing I noticed that probably isn't related - disabling/enabling the Skeleton Render Separator component via the "Enable Separator" checkbox doesn't "dirty" the gameobject. 

Thanks for your help!!

**Comment by HaraldCsaszar** [comment]
Sorry for the very long delay and thanks again for reporting @Jamez0r! Two of the three issues reported in this ticket should be resolved by the above commit (EDIT: both on the 4.1 and 4.2-beta branches). New spine-unity unitypackages are available for download.

> Also noted at 3:00 in the video, its possible to have the Skeleton Render Separator disabled, but the actual Parts Renderers still active.

What I could not reproduce unfortunately is the error of the Mesh still being assigned as shown around 3:00 in your video. When trying to reproduce this issue, the child separator renderer's MeshFilter mesh was always properly set to null after the scene has been reopened. May I ask which project settings `Enter play mode options` you used? If you can still reproduce this issue, please let us know, then I'll happily create a new issue ticket for it.
