### ISSUE TITLE
[Background] Change color

### ISSUE THREAD

**Issue by null15** [EsotericSoftware/spine-runtimes#1963]
Hello,

Got 2 questions, how hard would it be to change the background to completely green, so I can screenshare my skeleton, and easily use something like Magic Wand to remove the BG? Or export the "Base" animation as a png without the background? Also getting rid of the "lines" thats in the background.

Thanks a ton for answers.

**Comment by null15** [comment]
(For 3.7.94 version)

**Comment by badlogic** [comment]
I assume this is a question regarding the Spine Editor, not the Spine Runtimes. Please repost the question on the forums at https://esotericsoftware.com/forum
