### ISSUE TITLE
[ts] blendmode does not allow batch rendering of skeletons

### ISSUE THREAD

**Issue by tionkje** [EsotericSoftware/spine-runtimes#1966]
While trying to batch render multiple Skeleton instances i stumbled on the following issue.

It seems that setting the blendmode on the polygonBatcher calls flush even if the blendMode didn't change
https://github.com/EsotericSoftware/spine-runtimes/blob/555c124a4440526ac2b89232e12037563c0e0100/spine-ts/spine-webgl/src/PolygonBatcher.ts#L74-L83

SkeletonRenderer calls polygonBatcher if the blendMode changed
https://github.com/EsotericSoftware/spine-runtimes/blob/555c124a4440526ac2b89232e12037563c0e0100/spine-ts/spine-webgl/src/SkeletonRenderer.ts#L165-L172

but blendMode is a local variable in the SkeletonRenderer's draw function
https://github.com/EsotericSoftware/spine-runtimes/blob/555c124a4440526ac2b89232e12037563c0e0100/spine-ts/spine-webgl/src/SkeletonRenderer.ts#L68

which forces each SkeletonRendere.draw to flush the polygonBatcher. And blocks batch rendering multiple skeletons.

WIth a small hack like in this diff

```diff
--- a/spine-ts/spine-webgl/src/PolygonBatcher.ts
+++ b/spine-ts/spine-webgl/src/PolygonBatcher.ts
@@ -45,6 +45,7 @@ export class PolygonBatcher implements Disposable {
        private srcColorBlend: number;
        private srcAlphaBlend: number;
        private dstBlend: number;
+       public blendMode: BlendMode;

        constructor (context: ManagedWebGLRenderingContext | WebGLRenderingContext, twoColorTint: boolean = true, maxVertices: number = 10920) {
                if (maxVertices > 10920) throw new Error("Can't have more than 10920 triangles per batch: " + maxVertices);

--- a/spine-ts/spine-webgl/src/SkeletonRenderer.ts
+++ b/spine-ts/spine-webgl/src/SkeletonRenderer.ts
@@ -163,8 +163,9 @@ export class SkeletonRenderer {
                                }

                                let slotBlendMode = slot.data.blendMode;
-                               if (slotBlendMode != blendMode) {
+                               if (slotBlendMode != blendMode && slotBlendMode != batcher.blendMode) {
                                        blendMode = slotBlendMode;
+                                       batcher.blendMode = blendMode;
                                        batcher.setBlendMode(
                                                WebGLBlendModeConverter.getSourceColorGLBlendMode(blendMode, premultipliedAlpha),
                                                WebGLBlendModeConverter.getSourceAlphaGLBlendMode(blendMode),
```

I was able to batch 175 skeleton instances of the mix-and-match example project from 175 draw calls to 12 draw calls.

Is there a specific reason that the blendMode is only rememberd per skeleton draw instead of for the polygonBatcher?

**Comment by badlogic** [comment]
SkeletonRenderer only cares about batching the rendering of slots, as it can not anticipate code outside of it changing the blend mode. However, PolygonBatcher is able to make assumptions about the initial blend state, as it operates within `begin()` and `end()` calls. So, this is a bug I'll fix. Thanks for reporting!
