### ISSUE TITLE
[ts] 4.0.9 is the last working version

### ISSUE THREAD

**Issue by Andy1210** [EsotericSoftware/spine-runtimes#1968]
From 4.0.9 above the player is not rendering my animations, in debug view I can see the skeleton animating, but the images are simply not rendered at all.

4.0.9
![image](https://user-images.githubusercontent.com/964291/137310597-8eb40d6c-8bf1-4457-a3f4-13a67414a41d.png)
4.0.14
![image](https://user-images.githubusercontent.com/964291/137310781-9bf2e659-aa4e-42ff-860e-dda89f765743.png)

Also version 4.1.0 published to npm is completely broken, in https://github.com/EsotericSoftware/spine-runtimes/blob/4.1-beta/spine-ts/spine-core/src/attachments/Sequence.ts it tries to import from "src" which is not ok in the dist of course.

**Comment by badlogic** [comment]
For 4.0, I'll need your skeleton and texture atlas images to fix the issue. The screenshots alone don't help I'm afraid.

Sorry for the 4.1 foobar, I'll fix that asap.

**Comment by Andy1210** [comment]
Thank you. 
Here are the assets
[spine_assets.zip](https://github.com/EsotericSoftware/spine-runtimes/files/7346594/spine_assets.zip)

**Comment by badlogic** [comment]
I've tried your assets with 4.0.14 directly from source and that renders correctly for me:

<img width="949" alt="Screenshot 2021-10-14 at 16 12 17" src="https://user-images.githubusercontent.com/514052/137335230-c3b4576b-afb4-4c41-b991-a219a0055d31.png">
<img width="949" alt="Screenshot 2021-10-14 at 16 12 19" src="https://user-images.githubusercontent.com/514052/137335242-1552214b-81f1-472a-9fc3-df317d88ca6f.png">

I've then replaced the locally compiled spine-webgl.js with the published one at https://unpkg.com/@esotericsoftware/spine-webgl@4.0.14/dist/iife/spine-webgl.js and that too works as intended (same result as above).

Do you have a public URL I can check out that demonstrates the issue?

(I've released a fixed 4.1.1 as well).

**Comment by Andy1210** [comment]
hmm, now it's working for me as well 😅 I have no idea why. I've tried to install the v4.0.14 multiple times, and it was never working. Whenever I've rolled back to 4.0.9, it was fine. Now it's fine with 4.0.14 and I've tried now with 4.1.1 and it's fine as well.

Thanks for the quick fix for the 4.1. I think you can close this issue now.

**Comment by badlogic** [comment]
Awesome! Thanks for reporting the 4.1 issue as well!
