### ISSUE TITLE
[cpp] Access out of bounds in VertexAttachment::computeWorldVertices

### ISSUE THREAD

**Issue by Nitrillo** [EsotericSoftware/spine-runtimes#1970]
I got this assert in the CPP runtime library (index out of bounds)
![image](https://user-images.githubusercontent.com/1926191/138032593-300e3886-0a77-4201-9f2a-754ff53b1216.png)

Please let me know how I can help to debug the issue
thanks!

**Comment by badlogic** [comment]
@invicticide sorry for the late reply. I'll need a way to reproduce this. Can you provide the exported skeleton .json/.skel and atlas? If it's a Spine issue, I should be able to reproduce the issue outside your custom engine. I'll also need to know which animations are triggering this as well as any skins you may have set. Finally, I'll need to know the Spine Runtimes and Editor version you are using.

**Comment by badlogic** [comment]
@Nitrillo I'll reopen this if you can provide a repro.
