### ISSUE TITLE
[Unity] Prefab "Identifier uniqueness violation" warnings

### ISSUE THREAD

**Issue by OdinsRightEye** [EsotericSoftware/spine-runtimes#1973]
Having multiple prefabs/prefab variants with SpineAnimation component on GameObjects with same name added to scene resulting in warnings, for example:
I have scene with prefab "Base" which contains GameObject "Human" with SpineAnimation, and prefab variants of base "Variant1" and "Variant2". This resulting in warnings:
`Identifier uniqueness violation: 'Name:Skeleton Prefab Mesh "Human", Type:Mesh'. Multiple Objects with the same name/type are generated by this Importer. There is no guarantee that subsequent imports of this asset will properly re-link to these targets.`
The issue is in SpineEditorUtilities.cs where name for mesh is generated from GameObject's name:
`string meshName = string.Format("Skeleton Prefab Mesh \"{0}\"", renderer.name);`
There should be some way to get rid of these warnings, maybe making mesh names more unique.

**Comment by HaraldCsaszar** [comment]
Thanks very much for reporting and for providing the fix! New 4.0 and 4.1-beta spine-unity unitypackages are available for download.
