### ISSUE TITLE
[ts] WebGL backend doesn't disable culling nor set the vertex attribute divisor

### ISSUE THREAD

**Issue by Exedrus** [EsotericSoftware/spine-runtimes#1976]
While trying to integrate the WebGL backend with other rendering code, I noticed that the `SceneRenderer` class doesn't do either of these (as of version `4.0.14` from NPM):

* Run `gl.disable(gl.CULL_FACE)` to disable back/front-face culling. When culling is switched on (seems likely that many 3D TypeScript projects would do this), the renderings can become entirely invisible.
* Run `gl.vertexAttribDivisor(vertexAttributeLocation, 0)`. This tells WebGL2 that the given attribute should not be traversed according to WebGL's instanced-rendering API. I usually run this along side `gl.enableVertexAttribArray()`  calls.
    * On my system (Firefox + Ubuntu Linux), if a prior rendering program sets attribute locations to be "instanced", it caused the Spine renderer to draw nothing. Though I'm not sure if this is how WebGL is supposed to work.
    * Unlike back-face culling, I'm not sure how commonly instanced rendering is used. Though it seems like it could be very handy.

Neither is exactly required, but I can definitely see these saving people time if they try to run Spine's runtimes along side some existing external rendering code that uses either of the above.

**Comment by badlogic** [comment]
Great suggestions. Disabling culling by default is a no brainer I think. I too am unsure about instanced rendering. My guess is that people doing that would setup and tear down the respective states anyways.
