### ISSUE TITLE
TYPO in spine-lua AnimationState

### ISSUE THREAD

**Issue by wickeym** [EsotericSoftware/spine-runtimes#1978]
Hi, I found a typo:
https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-lua/spine-lua/AnimationState.lua#L497

`holdMix.mixtime` should be `holdMix.mixTime`

Sincerely,
Michael Wickey

**Comment by badlogic** [comment]
Thanks for reporting!
