### ISSUE TITLE
[unity] MeshGenerator doesn't update triangle indices when inactive bone clears attachment

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1984]
Reported on the forum:
http://esotericsoftware.com/forum/Extra-images-in-animation-16634

Problem is that an optimization `GeometryNotEqual` check always returned `false` and didn't update triangle indices, since a disabled bone didn't clear the previously active attachment to null, thus leading to no difference in e.g. a second loop iteration of an animation.

**Comment by jpeterson88** [comment]
Awesome. Thanks for fixing this again Harald. I appreciate the quick turnaround so that our team can meet our release date.

**Comment by HaraldCsaszar** [comment]
You're very welcome, thanks for reporting. All the best for your release!
