### ISSUE TITLE
[Solar2d] Update runtimes to use the new update:mesh() method

### ISSUE THREAD

**Issue by depilz** [EsotericSoftware/spine-runtimes#1986]
**[NOTE]: This change only works from Solar2D 3661 onwards.**

The new [mesh:update()](https://github.com/coronalabs/corona/pull/299) is already accepted and will be present in the next Solar2D build.

I already updated the Solar2D runtimes for the versions 4.0, 3.8 and 3.7 and tested them with many animations, and the performance gain is between 30-70%.

I'm opening this issue so I can point the PR's to this place.

These are 2 of the animations I tested:
![CleanShot 2021-11-11 at 18 33 22](https://user-images.githubusercontent.com/5722355/141502497-d7013505-0f8a-4350-802a-5f19c7791c89.gif)

![CleanShot 2021-11-11 at 18 33 55](https://user-images.githubusercontent.com/5722355/141502511-604ef5cc-27b4-43fc-a510-e7d6ea6759ed.gif)

**Comment by depilz** [comment]
The build [3661](https://github.com/coronalabs/corona/releases/tag/3661) is already up!

**Comment by badlogic** [comment]
Merged for 3.7, 3.8, 4.0 runtimes. Excellent work @depilz thank you!
