### ISSUE TITLE
The RotateTimeline states not reset properly at loop mode, maybe bugs on all runtimes

### ISSUE THREAD

**Issue by halx99** [EsotericSoftware/spine-runtimes#1995]
Other runtime may have same problem, follow runtime confirmed:

- 4.0 web-js 
- 3.8 cocos2dx
- 3.8 unity

**Comment by badlogic** [comment]
How can I reproduce this? The tests I have look as they should.

**Comment by halx99** [comment]
Let's waiting the orignal reporter to provide more information...

**Comment by badlogic** [comment]
Oki. I'll reopen as soon as we have more info.

**Comment by kangleblue** [comment]
[spineres.zip](https://github.com/EsotericSoftware/spine-runtimes/files/7655341/spineres.zip)
@badlogic  The spine ressoure

**Comment by halx99** [comment]
Just play the animation `attack` loop mode as follow:
```cpp
  spineAnim->setAnimation(0, "attack", true);
```
Then you can see the left hand will rotate faster and faster

**Comment by halx99** [comment]
@badlogic You can simply checkout branch `spine-issue-1995` of [axmol](https://github.com/axmolengine/axmol/tree/spine-issue-1995), then build and run the `HelloCpp` target:
```bat
cmake -B build
cmake --build build --target HelloCpp
```

**Comment by kangleblue** [comment]
@badlogic do you have any idea?

**Comment by halx99** [comment]
The unity also has this issue, please see the reproduce attachment demo project(created with unity 2020.3.24f1):
[spine-issue-1955-unity.zip](https://github.com/EsotericSoftware/spine-runtimes/files/7791513/spine-issue-1955-unity.zip)

**Comment by halx99** [comment]
Any news?
