### ISSUE TITLE
[godot] Skins not working on Godot Engine

### ISSUE THREAD

**Issue by cesarizu** [EsotericSoftware/spine-runtimes#1996]
When importing animations with skins, nothing is shown. Without skins it seems to be working just fine.

The skin names are shown on the inspector alongside 2 empty options. Selecting any of those doesn't do anything:
![image](https://user-images.githubusercontent.com/658725/144729064-d811266e-6f77-4185-8daf-a93eb667e131.png)

Result:
![image](https://user-images.githubusercontent.com/658725/144729081-3201e4e3-bc29-4d0d-9f6a-dea66c7f71f9.png)

Minimal project that reproduces the problem: [skin-test.tar.gz](https://github.com/EsotericSoftware/spine-runtimes/files/7655005/skin-test.tar.gz)

**Comment by Udderpunch** [comment]
any update on this? I'm getting the following error anytime I attempt to run an example. 
E 0:00:00.554   ClassDB::add_property: Invalid setter 'SpineSprite::set_skin' for property 'custom_skin_resource'.
  <C++ Error>   Condition "!mb_set" is true.
  <C++ Source>  core\class_db.cpp:903 @ ClassDB::add_property()

Godot does see the "default" skin but won't set to it.

(edit) Still get the error whenever I run but I was able to get the animations playing.

**Comment by badlogic** [comment]
I've picked up work on spine-godot in the 4.2-beta branch. See mix-and-match.gd in the `example/` project. Please note that spine-godot is very much still heavily in flux and building a project on its current state is strongly discouraged. Many of the things in the old module have been removed and partially replaced with alternatives, and are being cleaned up as well, including renaming of classes, properties and methods.
