### ISSUE TITLE
Add an error message when loading old data

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#1998]
If a runtime fails to load data AND the version found in the data is older than the runtime version, the error message should include text explaining that the data is too old.

Currently users who try to load old data get an error that makes it look like loading is broken. They have to post on the forum, wait for our response, and we waste time responding. It would be better to give them the reason right away.

**Comment by HaraldCsaszar** [comment]
already implemented for spine-unity runtime.

**Comment by badlogic** [comment]
Also for ue4 and ts.
