### ISSUE TITLE
[ue4] Update docs to describe adding the plugin to Build.cs

### ISSUE THREAD

**Issue by dynamo-foundation** [EsotericSoftware/spine-runtimes#2005]
Clone repo.  Copy spine-ue4 to new folder.  Right click project and build visual studio files - fails.  Open SLN created and compile:

Error	C1083	Cannot open include file: 'spine/spine.h': No such file or directory	
Error	C1083	Cannot open include file: 'spine/Animation.h': No such file or directory

**Comment by badlogic** [comment]
You also have to copy over spine-cpp as per step 4: https://github.com/EsotericSoftware/spine-runtimes/tree/4.0/spine-ue4#usage

**Comment by dynamo-foundation** [comment]
Those documents are missing a step.  You have to add "SpinePlugin" to the public dependency modules.  You can't just create a new project.  After copying the source files as noted the demo project does work, however the docs should be updated to include the step to add the p
<img width="549" alt="Capture" src="https://user-images.githubusercontent.com/81651363/146576951-7d5059ff-ad32-43fb-b254-955ccca6ccdc.PNG">
lugin dependency in the Build.cs.

**Comment by badlogic** [comment]
Ahh, sorry, you're absolutely right. It does mention it in the spine-ue4 guide, but not as a required step. I'll update the README.md and guide.

**Comment by badlogic** [comment]
Updated both README.md and guide.
