### ISSUE TITLE
[ue4] Calling delegates on animation state events crashes indeterministically

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2006]
See http://esotericsoftware.com/forum/UE4-CRASH-I-want-to-solve-the-problem-16805?view=unread#unread

**Comment by badlogic** [comment]
Ran the provided repro case and as per instructions using desktop PIE mode, it crashes after around 10 times of back and forth between the list view and individual view. However, my stacktrace is entirely different and it does not crash in the delegate:

![image](https://user-images.githubusercontent.com/514052/147257121-e040f879-1b24-4449-b6da-97c6b624c952.png)

I'm unsure how the constructor of the slate material can crash like this. Maybe the onPaint() call is triggered after the widget is no longer part of the UMG UI for some reason, making the provided material invalid?

**Comment by badlogic** [comment]
We've previously worked around a bug in the FSlateMaterialBrush constructor here: https://github.com/EsotericSoftware/spine-runtimes/issues/1458

I've reverted this fix temporarily, but the crash persists. An exception is thrown without any information.

**Comment by badlogic** [comment]
The material provided to the brush may be invalid. However, we store materials in a TArray in the SpineWidget that's tagged via UPROPERTY, so the material should never be garbage collected.

**Comment by badlogic** [comment]
The parent material we use to create the dynamic material in the widget may have been garbage collected? https://answers.unrealengine.com/questions/316316/umaterialinstance-from-umaterialinstancedynamic-de.html

**Comment by badlogic** [comment]
The parent material instance shouldn't be garbage collected either, as it is a UPROPERTY on the widget.

**Comment by badlogic** [comment]
It's not a garbage collection issue. The SpineSlateMaterialBrush/FSlateMaterialBrush is assigning the material's full name to ResourceName. That triggers a check of the resource name which fails, as the resource name eventually becomes super large. That hints at the widget construction code having an issue, i.e. recursively nesting UIs. I've fixed the resulting crash by assigning a custom resource name to the brush.

´´´
FString brushName = TEXT("spineslatebrush");
brushName.AppendInt(brushNameId++);
ResourceName = FName(brushName);
´´´

**Comment by xiaogou78** [comment]
Hey, just want to remind you that the memory allocated for a new FName will NEVER be released. Eventually the app will crash because of all of the FNames. Please make the FNames resuseable.
