### ISSUE TITLE
[godot] Can't access AnimationState tracks

### ISSUE THREAD

**Issue by bryab** [EsotericSoftware/spine-runtimes#2007]
As far as I can tell, there is no API access to SpineAnimationState's tracks.  So, there is, for example no way to see how many tracks there are or to access a track without adding or setting an animation.

This is missing:
http://en.esotericsoftware.com/spine-api-reference#AnimationState-tracks

**Comment by bryab** [comment]
Sorry, to clarify, there is a way to get a track by its id (`get_current`), but there is no way I can find to check how many tracks there are.

**Comment by badlogic** [comment]
Thanks for the suggestion. The Godot runtime is currently heavily WIP and I'll make sure to expose this somehow.

**Comment by badlogic** [comment]
The latest 4.2-beta commit now exposes `get_num_tracks()` on `SpineAnimationState`
