### ISSUE TITLE
Flutter questions

### ISSUE THREAD

**Issue by chenenyu** [EsotericSoftware/spine-runtimes#2014]
Hi, i'm writing an runtime implementation for Flutter, the flutter canvas works just like js canvas, so i referenced the `spine-core` and `spine-canvas` in `spine-ts`, but the `spine-canvas` only supports `RegionAttachment` and `MeshAttachment`. If i want to support all spine features, is there any other libraries or documents i can refer to? Thanks.

**Comment by badlogic** [comment]
Please post questions on the forum at https://esotericsoftware.com/forum going forward.

You can use TypeScript code with Flutter? That'd be new to me. How are you doing that?

`RegionAttachment` and `MeshAttachment` are the only two types that will actually be rendered. There is also `ClippingAttachment` that clips region and mesh attachments to a polygon, resulting in a triangle mesh that can be rendered like a mesh attachment.

The spine-webgl backend has a fully featured renderer you can reference:
https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-ts/spine-webgl/src/SkeletonRenderer.ts

Flutter can render textured, vertex colored triangle meshes as far as I can remember. That makes the spine-webgl backend much closer to what you want than the spine-canvas backend, which uses a bad hack to render triangle meshes.

**Comment by chenenyu** [comment]
Thank you , i'm rewriting a dart implementation.

**Comment by badlogic** [comment]
Ah, very cool! I just checked the Flutter Canvas API, and this is what you want to use for both region and mesh attachments:
https://api.flutter.dev/flutter/dart-ui/Canvas/drawVertices.html

This should also allow you do support all the blend modes.

You can probably implement clipping attachments via this:
https://api.flutter.dev/flutter/dart-ui/Canvas/clipPath.html

The only thing you won't be able to supports is two color tinting. For that, Flutter would have to support shaders and custom vertex attributes.
