### ISSUE TITLE
Spine JSON and Atlas format specs

### ISSUE THREAD

**Issue by YakupTURKAN-pf** [EsotericSoftware/spine-runtimes#2016]
Hello, I need to create a simple packager for animations. I have found these [json](http://en.esotericsoftware.com/spine-json-format) and [atlas](http://en.esotericsoftware.com/spine-atlas-format) specs from EsotericSoftware website. But when I implemented the parser using provided spec I got several unparsed tags(outdated I believe). Does Spine have up to date spec documentation?

**Comment by badlogic** [comment]
The spec you found is for the latest release version of Spine 4.0. The pages should be up to date. What tags did you encounter that are not in the docs? 

You can also check the JSON and atlas parser reference implementations:
https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/SkeletonJson.java
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java#L269
