### ISSUE TITLE
[unity] Import issue when suitable atlas found in multiple directories

### ISSUE THREAD

**Issue by TableBreaker** [EsotericSoftware/spine-runtimes#2033]
Hi, I've found a issue that when I import two exported spine projects in two different folders at the same time,  then the two generated skeleton data asset will reference one same atlas asset wrongly
And I checked the code and found one line may cause this issue:

atlasesForSkeleton = atlasesForSkeleton.Union(newAtlases).ToList(); at [line 357](https://github.com/EsotericSoftware/spine-runtimes/blob/6b8c6b31cfed894126f7920b9ad59c78dc1392d6/spine-unity/Assets/Spine/Editor/spine-unity/Editor/Utility/AssetUtility.cs#L357)

Because of the Union operation, all imported new atlases will be added into the list, so when two or more spine atlas assets's attachments have same names, the first atlas will always pass the GetMatchingAtlas check, and then all skeleton will reference the first atlas. even if they are in different folders.

**Comment by HaraldCsaszar** [comment]
We are sorry for the troubles, thanks for reporting!

**Comment by HaraldCsaszar** [comment]
This issue has just been fixed on both 4.0 and 4.1-beta branches.
New 4.0 and 4.1-beta unitypackages are available for download. Thanks again for reporting.

**Comment by TableBreaker** [comment]
Got it, thanks Harald!

**Comment by HaraldCsaszar** [comment]
You're very welcome, thanks for reporting!
