### ISSUE TITLE
[unity] Exception at prefab baking

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#2034]
As reported on the forum:
http://esotericsoftware.com/forum/spine-4-0-4-1-spine-skeleton-prefub-baker-17082

**Comment by AshaSalorina** [comment]
Hello there. I try to use skeleton baker at 4.2 to get the same error.
They happend like
`fram[f]`
on 
BakeBoneConstraints
ParseTranslateTimeline
...

**Comment by HaraldCsaszar** [comment]
@AshaSalorina In general please open a thread on the [Spine forums](https://esotericsoftware.com/forum/) instead of creating github issue tickets yourself or adding comments to it, as it makes it easier to communicate and attach images and videos.

Regarding your reported issue: unfortunately we could not reproduce this issue, also not with skeletons containing rather recently added 4.2 physics constraints. Which exact versions (in the Unity Package Manager or name of the unitypackage, also listed in `Assets/Spine/version.txt`) of the spine-unity and spine-csharp packages are you using? Please make sure to use the latest packages.

If your issue persists with the latest 4.2 packages, please open a new thread on the forum and also please send us your problematic Spine skeleton files (the three exported assets) which fail to bake to contact@esotericsoftware.com.
