### ISSUE TITLE
Make AnimationState seekable?

### ISSUE THREAD

**Issue by littlesome** [EsotericSoftware/spine-runtimes#2039]
Currently AnimationState can only be updated with delta time, it will be very useful to make it seekable for making cutscene. 

And unity's timeline support module impl this in [SpineAnimationStateMixerBehaviour.cs](https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-unity/Modules/com.esotericsoftware.spine.timeline/Runtime/SpineAnimationState/SpineAnimationStateMixerBehaviour.cs), I think this impl is a little complex, if AnimationState is seekable, it can be changed to just queuing animations and seeking here and there. 

I'm trying to recreate a new AnimationState and update with a large delta to simulate seek behaviour, found that update cannot jump over TrackEntry, is this a bug?

**Comment by badlogic** [comment]
`AnimationState` is designed as a store of multiple tracks (which are basically queues of track entries) For each track, you specify which animations should be played back in what order (with additional parameters, like mix time, etc.).

When you update an animation state with a delta time, it processes the tracks and removes track entries that are no longer valid for the current timestamp. This can not work with seeking, as seeking requires animation state to hold on to all track entries indefinitely.

While it would be possible to have a special "seekable" mode in animation state, it would further complicate its implementation, which is already in space ship territory. We'd rather not do that.

If you want to make an animation state seekable, you can do it like this in your own code (also giving you more freedom if you need to do something special).

1. For each track, store the animations (and their parameters, like delay) in your own data structure.
2. Clear all tracks in the animation state.
3. Queue up all the animations based on the info in your data structure.
4. Update the animation state with the timestamp you want to seek to passed in as the delta time
5. Apply the state to your skeleton(s) and update the skeleton(s) world transform(s).

Repeat steps 2-5 if you need to seek more than once, e.g. if you build something like a timeline to scrub through.
