### ISSUE TITLE
[c] Documentation for rendering not using the attachment colors

### ISSUE THREAD

**Issue by JCash** [EsotericSoftware/spine-runtimes#2040]
The documentation + example could be clearer about how to take the attachment colors into account I believe.
(e.g. the implementation skips it entirely)

http://en.esotericsoftware.com/spine-c#Implementing-Rendering

**Comment by badlogic** [comment]
Cheers! I've updated the docs. http://esotericsoftware.com/spine-c

As a further reference I always suggest to look at the actual renderer implementations we have, e.g. spine-sfml.

**Comment by JCash** [comment]
Great, thanks!
