### ISSUE TITLE
Missing library link

### ISSUE THREAD

**Issue by duyk16** [EsotericSoftware/spine-runtimes#2043]
I can't believe they remove all library url 3.x. All my products gone down

https://esotericsoftware.com/files/spine-player/3.8/spine-player.js

**Comment by huangyiming9228** [comment]
I have met the same problem.
hi @badlogic , is there any way to get the resources of spine-player@3.8?

**Comment by NathanSweet** [comment]
If everyone on the internet linked to files on our servers then our servers would be crushed by all the traffic. You should host the files yourself so you don't rely on the availability of servers that aren't in your control.

You can get the 3.8 files here:
https://github.com/EsotericSoftware/spine-runtimes/tree/3.8/spine-ts/build
You don't need to compile or do anything else, just put those files on your server and link to them.

For Spine Runtimes 4.0+ you can use the UNPKG CDN if you don't want to host the files yourself:
http://esotericsoftware.com/spine-player#Adding-the-JavaScript-%26amp%3B-CSS-files
For example, to use the latest 4.1 spine-player:
https://unpkg.com/@esotericsoftware/spine-player@4.0.*/dist/iife/spine-player.min.js
