### ISSUE TITLE
[ue4]  Some interfaces (HasSkin, SetAttachment)

### ISSUE THREAD

**Issue by dcx515253** [EsotericSoftware/spine-runtimes#2045]
USpineSkeletonComponent::HasSkin / USpineWidget::HasSkin should use findSkin() instead of findAnimation().

And USpineWidget::SetAttachment / USpineSkeletonComponent::SetAttachment the if judgment in the function will cause the ‘attachment’ on the slot to be unable to be cleared when the attachmentName is None

sorry English is not very good to use google translate

**Comment by badlogic** [comment]
Thank you for reporting. This has been fixed in the 4.1-beta branch.

**Comment by dcx515253** [comment]
> 感谢您的报告。这已在 4.1-beta 分支中修复。
I looked at the merge log, why only USpineSkeletonComponent was modified。。。
And USpineWidget?

**Comment by badlogic** [comment]
That's fixed as well, please pull the latest commits and also update spine-cpp in your plugin folder https://github.com/EsotericSoftware/spine-runtimes/blob/4.1-beta/spine-ue4/Plugins/SpinePlugin/Source/SpinePlugin/Private/SpineWidget.cpp#L248
