### ISSUE TITLE
Unity 2017.3 does not contain the definitions from the Spine Runtime

### ISSUE THREAD

**Issue by cwbeta** [EsotericSoftware/spine-runtimes#2053]
Runtime:
[spine-unity 4.0](https://esotericsoftware.com/files/runtimes/unity/spine-unity-4.0-2022-03-22.unitypackage) (updated 2022-03-22, [changelog](https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/CHANGELOG.md#c-2))
Compatible with Spine 4.0.00 or newer and Unity 2017.1-2021.1.

However, the SkeletonRenderTexture.cs contains 2 undefined definitions:
![QQ截图20220402163917](https://user-images.githubusercontent.com/8300417/161375013-124824a3-fee5-4e14-90f0-8e29892f631a.png)

**Comment by cwbeta** [comment]
Found the script is in examples and I just delete the examples folder and everything goes right.

**Comment by HaraldCsaszar** [comment]
Same issue tracked under this issue ticket as well:
https://github.com/EsotericSoftware/spine-runtimes/issues/2056
Fixed in commit:
https://github.com/EsotericSoftware/spine-runtimes/commit/53ae86a0259bc3e31bdd399a4278b401af6fd5d2
Thanks for reporting!
