### ISSUE TITLE
[xna] [monogame] Can not load texture normally

### ISSUE THREAD

**Issue by EndlessMISAKA** [EsotericSoftware/spine-runtimes#2054]
I want to create a WPF app use XNAControl to show a spine animation on PC decktop, but there is something wrong with the XNA Runtime，such as "lose parts", "alpha error".
To find out the reason for those errors, I used Spine-Unity to load it, it was shown perfectly.
The animation maybe only create for unity, so I also used Spine-TS to load it, it was shown perfectly again.
So I think the error is in Spine-Xna, but I don't know why.

The animation file can download from this url: (Adult content !!!!)
[mega.nz](https://mega.nz/folder/AzJiARxJ#ErJ2R9Mj-e5VM-E_-kmmZw)
The "1001_H1" lose parts, "1003" is alpha error or color error.
Spine Version is 3.8.99.

**Comment by badlogic** [comment]
Sorry, your link doesn't work. You can also send your files to contact@esotericsoftware.com via email.

**Comment by EndlessMISAKA** [comment]
Sorry, link is fixed.

**Comment by badlogic** [comment]
I can not reproduce this without the original project files. I strongly suggest to update to Spine 4.1, both editor and runtime side. Let me know if the issue still exists.
