### ISSUE TITLE
[Question] About License

### ISSUE THREAD

**Issue by ericoporto** [EsotericSoftware/spine-runtimes#2057]
Hello,

If I look into building a plugin for a game engine, can I copy the code from [spine-cpp](https://github.com/EsotericSoftware/spine-runtimes/tree/4.0/spine-cpp) into a codebase, adding it's [LICENSE](https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-cpp/LICENSE) and the notice? Can I distribute it as a binary .dll file that mixes my code to the plugin interface and the spine-cpp code?

Thanks! Just asking because I could not fully understand what was allowed and what wasn't from the license.

**Comment by badlogic** [comment]
If you distribute spine-cpp as part of a plugin for a game engine, be it in source or binary form, then any user of your plugin must have a valid Spine license. That's what's set forth in the LICENSE file and license headers of spine-cpp source files. It references Section 2 of our license agreement which states the above in legalese: http://esotericsoftware.com/spine-editor-license#s2
