### ISSUE TITLE
[unity] Unity 2018.4 does not contain some definitions from the Spine Timeline 4.0 Plugin

### ISSUE THREAD

**Issue by mayo-cl** [EsotericSoftware/spine-runtimes#2062]
Runtime:
[spine-unity 4.0](https://esotericsoftware.com/files/runtimes/unity/spine-unity-4.0-2022-03-22.unitypackage) (updated 2022-03-22)
[Spine Timeline 4.0](https://esotericsoftware.com/files/runtimes/unity/com.esotericsoftware.spine.timeline-4.0-2022-03-24.zip)  (updated 2022-03-24)

I am on Unity 2018.4, and I see these compile errors. Not happening on Unity 2019 though.

<img width="958" alt="Screen Shot 2022-04-06 at 10 54 01" src="https://user-images.githubusercontent.com/55756417/162004079-5b32a53c-8658-47be-9907-4149cbc22c73.png">

**Comment by HaraldCsaszar** [comment]
@mayo-cl Thanks for reporting and sorry for the troubles.
In general, please always post the compile error description messages from the Unity console Window, not a screenshot of your IDE (which is neither precise nor reliable). I assume that you received the error message `[..]/SpineAnimationStateGraphicTrackInspector.cs(40,58): error CS0246: The type or namespace name 'TrackEditor' could not be found. Are you missing an assembly reference?`, is this correct?

**Comment by HaraldCsaszar** [comment]
This issue has just been fixed. New 4.0 and 4.1-beta spine timeline UPM packages are available for download:
http://esotericsoftware.com/spine-unity-download
Thanks again for reporting.
