### ISSUE TITLE
export to png

### ISSUE THREAD

**Issue by zeak6464** [EsotericSoftware/spine-runtimes#2078]
could export to png be added to this ?

**Comment by shadowfox87** [comment]
Hi, 

I too would think it would be a great feature and addition to this program if one could export as PNG.

**Comment by badlogic** [comment]
You can export to PNG via the editor. If you need to export to PNG via the Spine Runtimes, then it depends on what runtime you are using and what your use case is. Neither of you have stated which runtime you use and what your use case is.
