### ISSUE TITLE
[unity] null check missing in SkeletonRendererCustomMaterials

### ISSUE THREAD

**Issue by Oletus** [EsotericSoftware/spine-runtimes#2081]
I had to add a null check for slotObject in SkeletonRendererCustomMaterials SetCustomSlotMaterials() and RemoveCustomSlotMaterials() to get my game build working. Not sure if this is the correct fix, what could be the root cause? I don't think this was happening with the previous version of Spine 4.0 we had dating back to December.

**Comment by HaraldCsaszar** [comment]
Thanks for reporting and sorry for the troubles! We have added the two null checks. It seems that the replacement slot name is set to a value which is not found in the target skeleton slots, so you might want to check the slot names accordingly. Nevertheless it shall not fail with an exception of course.

**Comment by Oletus** [comment]
Great, thanks for the quick fix!
