### ISSUE TITLE
spine-cpp SkeletonJson.cpp timeline type color

### ISSUE THREAD

**Issue by fatmingwang** [EsotericSoftware/spine-runtimes#2082]
I have tried to parse a json file (version "spine": "3.8-from-4.0.62")
it get the error
Invalid timeline type for a slot: color
then I change  SkeletonJson.cpp  line : 915
from 
} else if (strcmp(timelineMap->_name, "rgb") == 0) {
change to 
} else if (strcmp(timelineMap->_name, "rgb") == 0 || strcmp(timelineMap->_name, "color") == 0) {

**Comment by badlogic** [comment]
Please provide the .json file and the spine-runtimes version you are using.

**Comment by HaraldCsaszar** [comment]
Please also note that version "3.8-from-4.0.62" is not supported to be used in runtimes, it's only intended for recovering work, to be able to import a 4.0 project in Spine 3.8. When using runtime version 3.8, please import the project in Spine Editor version 3.8 and export it from there as version 3.8. This might already resolve your issue.

See the documentation here for details:
http://esotericsoftware.com/spine-versioning#Recovering-work-from-a-newer-version
