### ISSUE TITLE
[spine-threejs] "Invalid value used as weak map key” after threejs update to r131

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-runtimes#2086]
Using the example at https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-ts/spine-threejs/example/index.html with the latest Threejs version to date (0.136.2), the example was throwing error messages on each `skeletonMesh.update(delta)`: 
"Invalid value used as weak map key". And it wasn't showing the spine mesh in the threejs scene.

After searching both here and on threejs I found the following thread of somebody having the same issue, but with a different use case:
https://discourse.threejs.org/t/invalid-value-used-as-weak-map-key-after-update-to-r131/30124

When I only downgraded threejs in my project to 0.130.0 the issues dissappeared and the spine object became visible in the scene.

So it looks like something in recent threejs versions had changed, but spine-threejs didn't adapt to this change yet.

Versions:
"@esotericsoftware/spine-threejs": "^4.2.2",
"@esotericsoftware/spine-ts": "^4.0.2",

**Comment by badlogic** [comment]
Thanks for reporting, I'll get to thismjext week. As a word of advise: always make sure the major/minor version of spine-ts and the soine-xxx backend you depend on match.

**Comment by bencresty** [comment]
Alright thanks for getting to it and for the tip @badlogic

**Comment by badlogic** [comment]
I've downgraded the 4.0, 4.1-beta, and 4.2-beta branches to Threejs 0.136.2 as well as 0.131 and did not observe any issues in the example.

<img width="1388" alt="Screenshot 2022-05-30 at 11 52 07" src="https://user-images.githubusercontent.com/514052/170967351-4292e39b-54fe-4a91-adba-5245d20a89e6.png">

I've then upgraded the example to Threejs 0.141.0 (the actual latest Threejs release) in all branches, and again, things work as expected.

You can try it yourself by checking out any of the branches in this repo, then `cd spine-ts && npm install && npm run dev && open spine-threejs/example/index.html`

Please provide a full reproduction sample so I can see the issue on my end. I'll close this out in the meantime.
