### ISSUE TITLE
[libgdx] Question

### ISSUE THREAD

**Issue by IntroEvEivie** [EsotericSoftware/spine-runtimes#2088]
Can you please tell me if there are more detailed instructions for assembling at least the regular version of Skeleton Viewer? I can not deal with the project and find the necessary project.

**Comment by badlogic** [comment]
For Spine Runtimes versions +4.1, you can run `./gradlew spine-libgdx:jar spine-skeletonviewer:jar` on the CLI. This will give you `spine-libgdx/spine-skeletonviewer/build/libs/spine-skeletonviewer.jar` which you can run via `java -jar spine-skeletonviewer.jar` or double clicking it in the file explorer.

For older Spine Runtimes versions, you'll have to use Eclipse, clone https://github.com/libgdx/libgdx and the Spine Runtimes repository, then import all the projects from both repositories, then right click on `spine-skeletonviewer` in the project view and select `Run as Java Application`. This will run SkeletonViewer and create a launch configuration. Then, again in the project view and select `Export`. In the dialog that pops up, select `Java -> Runnable Jar` and select the `SkeletonViewer` run configuration and set an export destination.

Or simply download a prebuild SkeletonViewer from our website at: http://en.esotericsoftware.com/spine-skeleton-viewer

**Comment by IntroEvEivie** [comment]
> 

Thank you. You helped a lot.
