### ISSUE TITLE
[Unreal] Spine runtime 4.0.64 not importing skeleton in Unreal 5

### ISSUE THREAD

**Issue by itsAdi** [EsotericSoftware/spine-runtimes#2091]
I am using Spine editor v4.0.64 and Spine runtime v4.0.64 but when I import my skeleton into Unreal 5 it says cannot import data as runtime version not matching 
![image](https://user-images.githubusercontent.com/33220608/171676492-a2984488-3510-48a3-ab12-d3bb6ecb5476.png)

See the version in exported version
![image](https://user-images.githubusercontent.com/33220608/171676803-83c692da-d023-4e69-8052-e08d72e24001.png)

This is the runtime I am using
![image](https://user-images.githubusercontent.com/33220608/171677497-6da95346-6ab3-44f0-9930-732bde1ba32d.png)

Here is the exported spine file
[SpineExport.zip](https://github.com/EsotericSoftware/spine-runtimes/files/8842593/SpineExport.zip)

**Comment by badlogic** [comment]
Please also post your file.

**Comment by itsAdi** [comment]
> Please also post your file.

Sorry for the late reply and I hope you meant the spine exported file, if so, here it is 
[SpineExport.zip](https://github.com/EsotericSoftware/spine-runtimes/files/8842570/SpineExport.zip)

**Comment by itsAdi** [comment]
closed by mistake

**Comment by badlogic** [comment]
No worries :)

**Comment by itsAdi** [comment]
> Please also post your file.
Added the exported spine files at the end

**Comment by itsAdi** [comment]
@badlogic just wanted to know if you managed to take a look at the issue

**Comment by badlogic** [comment]
For some reason, you choose the file extension `.json` instead of `.skel`. But your file is a binary export, not a JSON export. Rename the file to end in `.skel` and it will work just fine.
