### ISSUE TITLE
Build crashing on Unity 2022.1.3 on PostprocessSpinePrefabMeshes() calling AssetDatabase.SaveAssets()

### ISSUE THREAD

**Issue by mavlac** [EsotericSoftware/spine-runtimes#2093]
Unable to build in 2022.1.3

Seems like bug in Unity causing immutable prefab from Core RP package trying to be saved by call of `AssetDatabase.SaveAssets()` that is invoked from [SpineBuildProcessor](https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/spine-unity/Assets/Spine/Editor/spine-unity/Editor/Utility/SpineBuildProcessor.cs) method `PostprocessSpinePrefabMeshes()`

Suggested fix I tried is avoiding save of "all dirty assets", but saving changes on modified ones one by one:

		internal static void PostprocessSpinePrefabMeshes () {
			BuildUtilities.IsInSkeletonAssetBuildPostProcessing = true;
			try {
				foreach (string assetPath in prefabsToRestore) {
					GameObject g = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
					SpineEditorUtilities.SetupSpinePrefabMesh(g, null);
					AssetDatabase.SaveAssetIfDirty(g);
				}
				prefabsToRestore.Clear();
			} finally {
				BuildUtilities.IsInSkeletonAssetBuildPostProcessing = false;
			}
		}

Possibly related Unity bug:
[https://issuetracker.unity3d.com/issues/core-render-pipeline-argumentexception-cant-save-an-immutable-prefab](https://issuetracker.unity3d.com/issues/core-render-pipeline-argumentexception-cant-save-an-immutable-prefab)

**Comment by mavlac** [comment]
Build error from console:

```
Saving Prefab to immutable folder is not allowed: Packages/com.unity.render-pipelines.core/Runtime/Debugging/Prefabs/Resources/DebugUICanvas.prefab
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Spine.Unity.Editor.SpineBuildProcessor:PostprocessSpinePrefabMeshes () (at Assets/Spine/Editor/spine-unity/Editor/Utility/SpineBuildProcessor.cs:103)
Spine.Unity.Editor.SpineBuildProcessor:PostprocessBuild () (at Assets/Spine/Editor/spine-unity/Editor/Utility/SpineBuildProcessor.cs:67)
Spine.Unity.Editor.SpineBuildPostprocessor:UnityEditor.Build.IPostprocessBuildWithReport.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport) (at Assets/Spine/Editor/spine-unity/Editor/Utility/SpineBuildProcessor.cs:189)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Comment by HaraldCsaszar** [comment]
Thanks for reporting and sorry for the troubles! Thanks very much for sharing a bugfix code as well, much appreciated! We have implemented this bugfix (and similar occurrances) on both 4.0 and 4.1-beta branches. New 4.0 and 4.1-beta spine-unity unitypackages are available for download.

**Comment by mavlac** [comment]
Thank you for prompt solution and runtime release, much appreciated.
