### ISSUE TITLE
[godot] Atlas resource load bug

### ISSUE THREAD

**Issue by blackier** [EsotericSoftware/spine-runtimes#2094]
https://github.com/EsotericSoftware/spine-runtimes/blob/63065eefed2b0e96bac70c065b761a77bab8e638/spine-godot/spine_godot/SpineAtlasResource.cpp#L164

https://github.com/EsotericSoftware/spine-runtimes/blob/63065eefed2b0e96bac70c065b761a77bab8e638/spine-godot/spine_godot/SpineAtlasResource.cpp#L196

The `atlas_data.utf8()` size and `atlas_data.size()` may not be equal, which will cause a crash.

The length of `atlas_data.utf8()`  should be used.

**Comment by badlogic** [comment]
Ouch, that's a subtle one. Thank you for reporting it! This likely also applies to the JSON file format loader.

**Comment by badlogic** [comment]
Addendum: the JSON loader is not affected: https://github.com/EsotericSoftware/spine-runtimes/blob/63065eefed2b0e96bac70c065b761a77bab8e638/spine-godot/spine_godot/SpineSkeletonDataResource.cpp#L167
