### ISSUE TITLE
Spine for SDL

### ISSUE THREAD

**Issue by peerless2012** [EsotericSoftware/spine-runtimes#2097]
SDL is designed for many platform ，so it is any plan to add SDL support ？

[SDL](https://github.com/libsdl-org/SDL)

**Comment by peerless2012** [comment]
Maybe like spine for sfml， it has a c impl and a c++ impl.

**Comment by badlogic** [comment]
We currently don't have a plan for SDL, but it should be pretty simple with SDL 2.0 which has functions to draw textured triangles directly. http://wiki.libsdl.org/SDL_RenderGeometry. However, we'd likely need to implement a custom batcher, as SDL doesn't batch draw calls itself, at least judging by the documentation. That'd increase the complexity a little.

**Comment by badlogic** [comment]
This has been done, see Spine 4.1 branch
