### ISSUE TITLE
[runtimes] [c#] [spine 4.*] string propertyIds in timelines cost too much time to join string 

### ISSUE THREAD

**Issue by Light0457** [EsotericSoftware/spine-runtimes#2102]
After spine 4.0, the type of timeline's propertyIds change into string from int in spine 3.8, this makes the skeleton data parse time increase so much. The joint operation of string will occupy so much time in parsing data.
![image](https://user-images.githubusercontent.com/6023553/176842281-344a7abc-5907-4ed7-b14e-91437d70e57a.png)
![image](https://user-images.githubusercontent.com/6023553/176842507-ec7be1f4-1945-4b35-a79f-eff2bfd5bb44.png)
![image](https://user-images.githubusercontent.com/6023553/176842528-cbabdf02-6fd7-4528-9a68-b682b66993c8.png)

**Comment by badlogic** [comment]
Profiling small methods like this usually gives bogus results. String concatenation is optimized in the .NET runtimes (maybe not in IL2CPP). The operations performed are extremely unlikely to have any meaningful impact on the actual parsing duration. Do you have an exported .skel file for 3.8 and 4.0 where you can show a significant increase in load times (using wall clock time for the entire parsing process, not profiler timings for individual methods)?

**Comment by Light0457** [comment]
> 

I had not compare the .skel file parsing time between 3.8 and 4.0, but I had tried to changed the string propertyIds back into integer, it reduce the parse time. 
I changed all the code like these
``` C#
public ScaleTimeline (int frameCount, int bezierCount, int boneIndex)
	: base(frameCount, bezierCount, //
		(int)Property.ScaleX + "|" + boneIndex, //
		(int)Property.ScaleY + "|" + boneIndex
	) {
	this.boneIndex = boneIndex;		
}
```
into
```C#
public ScaleTimeline (int frameCount, int bezierCount, int boneIndex)
	: base(frameCount, bezierCount, //
		((int)Property.ScaleX << 24) + boneIndex, //
		((int)Property.ScaleY << 24) + boneIndex
	) {
	this.boneIndex = boneIndex;		
}
```
And I use `System.Diagnostics.Stopwatch` to watch the parsing time cost as following code,
```C#
var timer = new System.Diagnostics.Stopwatch();  
var time_costs = new System.Collections.Generic.List<Tuple<long, long>>();                  
SkeletonData data = null;
var test_times = 10;
while( test_times > 0 ) {
    timer.Reset();
    timer.Start();
    data = binary.ReadSkeletonData(input, allocator, skeletonDataName);
    input.Position = 0;
    var cost_time = new Tuple<long, long>(timer.ElapsedMilliseconds, timer.ElapsedTicks);
    time_costs.Add(cost_time);
    test_times -= 1;
}
var idx = 0;    
var msg = new System.Text.StringBuilder();
msg.AppendFormat("{0} parse time cost: \n", skeletonDataName);
foreach(var cost in time_costs){
    msg.AppendFormat("\t[{0}] {1} ms, {2} tick\n", idx, cost.Item1, cost.Item2);
    idx += 1;
}                                  
UnityEngine.Debug.Log(msg.ToString());
```
and got the result for the same .skel file is:
* Using string propertyIds : 333 ~ 856ms
```
[0] 713 ms, 7134771 tick
[1] 856 ms, 8563117 tick
[2] 333 ms, 3335679 tick
[3] 333 ms, 3335760 tick
[4] 869 ms, 8695426 tick
[5] 329 ms, 3298055 tick
[6] 334 ms, 3343548 tick
[7] 333 ms, 3338731 tick
[8] 333 ms, 3338132 tick
[9] 407 ms, 4078318 tick
```
* Using int propertyIds : 254 ~ 657ms
```
[0] 629 ms, 6299704 tick
[1] 257 ms, 2579077 tick
[2] 397 ms, 3971603 tick
[3] 657 ms, 6573610 tick
[4] 256 ms, 2562689 tick
[5] 252 ms, 2524188 tick
[6] 257 ms, 2572472 tick
[7] 532 ms, 5329432 tick
[8] 525 ms, 5255982 tick
[9] 254 ms, 2547671 tick
```

**Comment by badlogic** [comment]
You got to take the average of each of the 10 runs, which come down to 484ms and 401ms. Clearly, a strictly 32-bit integer based property id system is a bit faster (though 10 runs on a JITed platform like the .NET runtime is not enough to actually judge the significance of the difference).

In the future, we may add property ids that can not be encoded as integers, which is why we'll stick to the string based property ids.
