### ISSUE TITLE
[unity] Part of animation don't work

### ISSUE THREAD

**Issue by semgilo** [EsotericSoftware/spine-runtimes#2103]
Unity version: 2020.3.12f1c1
Spine Runtime Version: spine-unity-3.8-2021-11-10.unitypackage
Spine Version: 3.8

It work perfect in preview window, but doesn't work in SkeletonGraphic
Note: 
It will show when i close PMA Vertex Color, but color is wrong.

Repro:
1.add import skeleton assets to project
2.add a SkeletonGraphic (Unity UI)
3.set SleletonData 
4.set animation skill0_up

[assets.zip](https://github.com/EsotericSoftware/spine-runtimes/files/9042611/assets.zip)

**Comment by HaraldCsaszar** [comment]
Please note that your skeleton uses 2 atlas texture pages. When using `SkeletonGraphic` you need to enable `Advanced - Multiple CanvasRenderers` as described here:
http://esotericsoftware.com/spine-unity#Important-Material-Requirements
(Alternatively you can of course also ensure to pack to a single larger atlas texture to avoid this)
If this is not your issue and your are encountering other problems, please describe them in more detail here and we're happy to reopen the ticket.

**Comment by semgilo** [comment]
Thank you for your reply, but this is not my problem, some special effects of this animation (skill0_up) are lost at the beginning, you can see the correct effect through the preview.
Simply toggle Advanced - PMA Vertex Color to see the difference

**Comment by HaraldCsaszar** [comment]
Could you perhaps please share a screenshot of the problem (expected result vs wrong result)? Please note that we aren't familiar with what your effect animation should look like. Disabling `PMA Vertex Color` changes too much to help us here, a screenshot would be much better.

**Comment by semgilo** [comment]
> screenshot
I put two same SkeletonGraphic, turn on PMA Vertex Color on the top one, turn off PMA Vertex Color on the bottom, 
the beginning part of the top part is lost, the bottom part looks wrong, but it does play
![image](https://user-images.githubusercontent.com/7121873/177363969-8d7d64f1-7ec7-40d5-9569-f597e822c20d.png)

![image](https://user-images.githubusercontent.com/7121873/177363726-1228d510-8894-4735-a268-80932ff4ad50.png)

**Comment by semgilo** [comment]
> 

Are you able to reproduce now？

**Comment by HaraldCsaszar** [comment]
Thanks, now I could reproduce the issue. The problem here is that the `Renderer0` and `Renderer1` GameObjects below the `SkeletonGraphic` object need to have `CanvasRenderer` - `Cull Transparent Mesh` disabled. Otherwise the alpha of 0 of additive parts will be treated as "it's completely transparent, it will be culled as transparent mesh".

This (and other issues) are fixed automatically in newer versions (4.1) of the spine-unity runtime, in 3.8 you will need to manually disable this setting.

Please let us know if you have any problems remaining after this, then we're again happy to reopen the ticket.

**Comment by semgilo** [comment]
thanks, it work now

**Comment by HaraldCsaszar** [comment]
Thanks for getting back to us, glad it resolved your issue.
