### ISSUE TITLE
xcode This function declaration is not a prototype

### ISSUE THREAD

**Issue by mm-longcheng** [EsotericSoftware/spine-runtimes#2107]
SP_API spColor *spColor_create();
add void for avoid this warning.
SP_API spColor *spColor_create(void);

**Comment by badlogic** [comment]
What Xcode version are you using? I've compiled this with Clang 13.0.0 that comes with Xcode 13.4.1.

**Comment by badlogic** [comment]
sfml

**Comment by mm-longcheng** [comment]
Sorry i'm late.

Version 12.5.1 (12E507)   
C Language Dialect GNU99 [-std=gnu99]

There are several functions:
SP_API void spAnimationState_disposeStatics(void);
SP_API spAtlasRegion *spAtlasRegion_create(void);
SP_API int/*bool*/spBone_isYDown(void);
SP_API spColor *spColor_create(void);
float _spRandom(void);
SP_API void _spSetRandom(float (*_random)(void));
SP_API spSkeletonBounds *spSkeletonBounds_create(void);
SP_API spSkeletonClipping *spSkeletonClipping_create(void);
SP_API spSkeletonData *spSkeletonData_create(void);
SP_API spTriangulator *spTriangulator_create(void);
