### ISSUE TITLE
[Unity] SkeletonRootMotion index error when selecting non-default Root Motion Bone

### ISSUE THREAD

**Issue by Jamez0r** [EsotericSoftware/spine-runtimes#2110]
Updated from 4.0 to 4.1 and am receiving this error when running the game:
![spinebug unity](https://user-images.githubusercontent.com/3651077/178583299-dfc94811-e8de-4e1e-99f7-50d3b7152ab2.png)

This error only happens when I select a custom bone to be the Root Motion Bone (as seen in screenshot above). When I use the default Root bone, I do not get the error.

I added some debug lines (whose output are shown in the Unity screenshot above):
![spinebug rootmotionbase](https://user-images.githubusercontent.com/3651077/178583498-f5c42a36-e482-46ad-b452-b03e7de33ea9.png)

And this is where I believe might be the cause of the problem:
![spinebug potential cause](https://user-images.githubusercontent.com/3651077/178583550-ef927caa-7ec8-4d0f-93d2-3584a34b02df.png)

**Comment by HaraldCsaszar** [comment]
Thanks very much for reporting and finding the cause of the problem already, much appreciated!
A bugfix of the spine-unity runtime is available on both 4.1 and 4.2-beta branches, available for download here as usual:
http://esotericsoftware.com/spine-unity-download

**Comment by Jamez0r** [comment]
Issue still persists - I've uploaded the spine character that I am using to test the root motion that is getting the error, in case that helps with testing: https://drive.google.com/drive/folders/1RP95ZSm2wqiw512TAeNU_MLcC0hh-QHo?usp=sharing

I am using the bone called "[Front] Spine_Movement_Test_Bone" as the bone for root motion.

![spinebug2 unity](https://user-images.githubusercontent.com/3651077/178803760-1ea1f266-cb1b-4c5b-98d4-8b4417053838.png)

![spinebug2 skeletonrootmotionbase](https://user-images.githubusercontent.com/3651077/178803769-9baeb062-f802-4380-ba75-469a4c2c1338.png)

Thanks for the help!

**Comment by HaraldCsaszar** [comment]
Sorry! Thanks for providing the repro asset, they helped a lot. Now it should really be fixed (for both 4.1 and 4.2-beta). New unitypackages have been released as well.

**Comment by Jamez0r** [comment]
Thanks @HaraldCsaszar, the issue appears to be fixed!
