### ISSUE TITLE
[libgdx] latest runtime `4.1` release is not synced with maven central

### ISSUE THREAD

**Issue by fgnm** [EsotericSoftware/spine-runtimes#2116]
`4.1` runtime is still not available in maven central, only `4.0.18.1`: https://repo1.maven.org/maven2/com/esotericsoftware/spine/spine-libgdx/

The `4.1.0-SNAPSHOT` on sonatype looks like updated to the 1st July, so probably it's the latest and stable one, however a properly release in the stable channel would be nice. Is there any particular reason why this is not done yet? Like is it fine to switch to Spine 4.1 or there are still some WIP?

Thanks!

**Comment by badlogic** [comment]
Whoops, just released 4.1.0 to Maven Central. Will be a while until it distributes around the nodes. Thanks for the heads up!
