### ISSUE TITLE
[unity] When using multiple clipping polygons, the number of frames drops sharply

### ISSUE THREAD

**Issue by ye503837526** [EsotericSoftware/spine-runtimes#2118]
![FCB37955-78D2-4232-8192-7454B8023025](https://user-images.githubusercontent.com/44283825/179686447-df4b1216-8e69-40b3-9e28-befff1164460.png)
Using multiple spine components in the scene and turning on spinemask will lead to a sharp decline in the number of frames of the game. What is the reason? Is there any way to avoid it?
![F425621B-56B3-4F1D-8FF7-36939F3DB184](https://user-images.githubusercontent.com/44283825/179680447-02e07da0-7fd0-49ff-b45e-a33964288f51.png)
There is a difference of more than 300 frames between using and not using spinemask, which is obviously a huge performance problem, but I don't know how to solve it.

**Comment by HaraldCsaszar** [comment]
Clipping polygons shall only be used when they cannot be avoided, and if so, try to use as few vertices at the clipping polygon as possible (prefer 3 to 4).
For more info and alternatives see:
http://esotericsoftware.com/forum/Unity-SkeletonClipping-ClipTriangles-17634?p=77319#p77319
http://esotericsoftware.com/forum/Bad-performance-on-mobile-with-few-animations-17526?p=76905#p76905
http://en.esotericsoftware.com/spine-clipping#Performance

**Comment by ye503837526** [comment]
I am already using untiy mask to mask spineanimation (circular mask). However, the unity mask component is invalid to mask spineanimation on Samsung Galaxy j4+ devices. It becomes square. The mask layer I use is circular. Moreover, on this device, non spine images can be normally masked into circles. I'm sure it's spineanimation. Is there any solution. Due to special reasons, it's not convenient for me to upload the picture, but the problem really exists.

**Comment by HaraldCsaszar** [comment]
> However, the unity mask component is invalid to mask spineanimation on Samsung Galaxy j4+ devices. It becomes square. 

Does it mask correctly inside the Unity Editor but not once you run the executable on a Samsung Galaxy j4+ device? Does it work on other devices?

If it works in the editor but not on other devices, we would need a minimal Unity reproduction project that still shows this problem. You can send it to contact@esotericsoftware.com, or attach a link to this ticket.

**Comment by ye503837526** [comment]
Yes, other devices are normal, including windows, MAC and many Android devices, as well as the unity compiler. It is only invalid on Samsung Galaxy j4+ devices. I will send a demo to contact@esotericsoftware.com Mailbox, I hope you have the device and can solve this problem.

**Comment by ye503837526** [comment]
Sorry, I just found a problem when making the demo. The image mask used in our project is the rewritten vertex rendering interface for clipping, so as to obtain higher performance. Not unity mask. It should be a long time, I forgot it. Therefore, after testing, the mask image of unity mask on Samsung Galaxy j4+ device is also invalid. It's unity mask. It's not spine's problem. Thank you for your timely reply. I wish you a happy life!

**Comment by HaraldCsaszar** [comment]
Thanks very much for following up, very glad to hear that you've figured it out. We wish you all the best for your project as well! :)
