### ISSUE TITLE
[godot] Is the setter variable type wrong?

### ISSUE THREAD

**Issue by blackier** [EsotericSoftware/spine-runtimes#2133]
the setter variable type is bool
https://github.com/EsotericSoftware/spine-runtimes/blob/2141cfff6a3ff86bd728effb64734da51517ee6d/spine-godot/spine_godot/SpineAnimationTrack.cpp#L490

but the menber type is float
https://github.com/EsotericSoftware/spine-runtimes/blob/2141cfff6a3ff86bd728effb64734da51517ee6d/spine-godot/spine_godot/SpineAnimationTrack.h#L53

**Comment by blackier** [comment]
It also exists in
https://github.com/EsotericSoftware/spine-runtimes/blob/2141cfff6a3ff86bd728effb64734da51517ee6d/spine-godot/spine_godot/SpineAnimationTrack.h#L120

**Comment by badlogic** [comment]
That is indeed wrong! Thanks for reporting, will fix it asap.
