### ISSUE TITLE
[spine-ts] Mipmaps renders black even on power of two textures

### ISSUE THREAD

**Issue by Gerokusu** [EsotericSoftware/spine-runtimes#2138]
Using mipmaps makes a skeleton go black, with the following warning on Firefox : `drawElementsInstanced: TEXTURE_2D at unit 0 is incomplete: Bad mipmap dimension or format.`

Strangely, Chrome and Edge behaves the same without any warning.

The texture I want to render is PNG, power of two, squared, RGBA8888, is set to use Mipmaps and uses premultiply alpha. My WebGL context is set accordingly (PMA, no straight alpha). It does not happen when the texture is its min filter is set to Linear or Nearest. Mag filter seems to be ignored and works the same regardless of its value.

I wonder if each subimage in the texture set is treated individually ? If it is the case, they obviously are not all power of two, but that would be weird if that were how it is processed.

**Comment by badlogic** [comment]
<img width="1272" alt="Screenshot 2022-08-19 at 17 45 38" src="https://user-images.githubusercontent.com/514052/185657048-24fe7bc4-20bd-47e7-b0e2-bc7e301d65e9.png">

I can repro this in the latest Firefox, Chrome and Safari on macOS with a square, power of two (256x256) atlas using `MipMapLinearLinear` for both the min and mag filter, and PMA.

**Comment by badlogic** [comment]
Mip maps weren't generated in all cases. For WebGL 1, the atlas page image still must be power of two, for WebGL 2 it can have any dimension. 

I've published new packages to NPM for the 4.1 and 4.2-beta branches.

Thanks for reporting!

**Comment by Gerokusu** [comment]
My browser is running on Windows 11, but my server is on Ubuntu (WSL 2). Anyway the new version you just pushed works like a charm, no more black textures ! Thank you very much :)
