### ISSUE TITLE
Spine for OpenGL/OpenGL ES

### ISSUE THREAD

**Issue by peerless2012** [EsotericSoftware/spine-runtimes#2146]
Opengl ES is widely supported by Android, iOS and many other platform, if spine support OpenGL ES to render, it will be easy to use it in native app.

And I find a library [spine-opengl](https://github.com/keith2018/spine-opengl) already support OpenGL render for Android, IOS, Mac, with this, it will be simple to render the anim in native widget.

So, it may be easy to add spine-opengl to this library, and make spine run on more places.

**Comment by badlogic** [comment]
Sorry, we have plans for Android and iOS support. A generic OpenGL (ES) runtime won't help much with platform limitations. E.g. you can't just have dozens of `TextureView` instances in an Android UI. Same for `GLKView` on iOS. Related: OpenGL ES is deprecated on iOS (and macOS). While I don't think Apple will rip out support soon, it's not a good strategy to target a deprecated API with a new runtime. Also, the code needed just to draw a Spine skeleton is just a few hunder LOCs tops.

**Comment by peerless2012** [comment]
So you are already have a tech road for Android and iOS ？what's that ？

**Comment by badlogic** [comment]
As a first step, we are adding a Flutter runtime, see the 4.2-beta branch. Next, we'll add native runtimes for both iOS and Android. We are still undecided on the rendering tech to use on each platform for the native runtimes.

**Comment by peerless2012** [comment]
Except gl or vulkan on Android and gl or matel on iOS ，I don't know an another way wo render this,  so I am very curious if there is another easy way to do the renderer.
