### ISSUE TITLE
Spine godot import error and crash

### ISSUE THREAD

**Issue by CGCFSS** [EsotericSoftware/spine-runtimes#2153]
Hello.
I am using pre-built Godot editor for Linux with spine runtime from [http://ru.esotericsoftware.com/spine-godot ](http://ru.esotericsoftware.com/spine-godot)
When I try to import .skel resources, I get an error and the resource itself is marked with a red cross.

`ERROR: Error importing 'res://assets/images/spine/hero/hero.skel'.
   at: _reimport_file (editor/editor_file_system.cpp:1759)`

When I try to import a .json binary file, the program crashes completely

`Unicode error: invalid skip
godot-4.1-3.5-stable: /home/runner/work/spine-runtimes/spine-runtimes/spine-godot/spine_godot/spine-cpp/src/spine/Json.cpp:124: spine::Json::Json(const char*): Assertion `value' failed.`

Pin my spine assets

[spineAsset.zip](https://github.com/EsotericSoftware/spine-runtimes/files/9559266/spineAsset.zip)

**Comment by badlogic** [comment]
Your assets were exported with Spine 4.0.64, while the Godot build you are using is based off of the Spine Runtimes version 4.1. Your major.minor versions of the editor and runtimes must match.

Please export using the latest Spine Editor version 4.1.x.

**Comment by badlogic** [comment]
Btw, the .json file in your zip is not a .json file.
