### ISSUE TITLE
Cannot use generated file with pixi/spine

### ISSUE THREAD

**Issue by kerimdragolj** [EsotericSoftware/spine-runtimes#2155]
Hello, 
I've been trying to load character from Spine in Angular application with pixi/spine. No matter how i export, no matter which version, i always get error about missing version field inside of JSON file... i always have to add it manually to proceed... 

Versions that im using:
Spine pro 4.1.09
"pixi-spine": "^3.1.0",
"pixi-viewport": "^4.34.4",
"pixi.js": "^6.2.0",

Also there is some info in [this thread](https://github.com/pixijs/spine/issues/415) too

**Comment by badlogic** [comment]
Based on the `.json` file you have posted in the other thread, you are exporting to version 4.0 from Spine Editor version 4.1. Do not do that. Please export from Spine Editor version 4.0.x if you want to use Spine Runtime version 4.0, or export from Spine Editor 4.1.x if you want to use Spine Runtime version 4.1. Do not export from Spine Editor version 4.1 to version 4.0. This type of export is not meant for use in runtimes and will likely lose information, as explained by the tooltip.

**Comment by kerimdragolj** [comment]
@badlogic Thank you for the response, aware of that i was just trying out and uploaded wrong file, in penultimate comment in [the thread](https://github.com/pixijs/spine/issues/415) ive posted correct version and it had same issue... thing is runtime is expecting version to be in the root object of json as field "version", but Spine exports it under `skeleton: { ..., spine }` ...
expected: 
![slika](https://user-images.githubusercontent.com/12545884/192556846-954f6e04-bc36-4cfe-8cf8-ee2264c1c8d7.png)

actual export:
![slika](https://user-images.githubusercontent.com/12545884/192556637-0fde3fd1-350c-4365-8948-4e18dd2a5763.png)

**Comment by manico** [comment]
Have the same issue. I think spine is not registering atlas loader and spine is not loaded correctly.

**Comment by davidetan** [comment]
> Have the same issue. I think spine is not registering atlas loader and spine is not loaded correctly.

This issue is nearly three years old and concerns a non-official runtime. There are no related bugs in the official runtimes.  

Please create a [forum thread](https://esotericsoftware.com/forum/) including your Spine asset version, the runtime and its version, and a minimal reproduction code, and we'll be happy to support you :)
