### ISSUE TITLE
[c] typo error after last changes in AnimationState.c

### ISSUE THREAD

**Issue by nt-bsokolowski** [EsotericSoftware/spine-runtimes#2156]
https://github.com/EsotericSoftware/spine-runtimes/blob/81708ebb0d0133c4953b6025cdb46db35457ca26/spine-c/spine-c/src/spine/AnimationState.c#L441

it should be:

`else if (timeline->type == SP_TIMELINE_ATTACHMENT)`

**Comment by badlogic** [comment]
Good catch, thanks! Fixed in 4.1 and 4.2-beta.
