### ISSUE TITLE
How to combine two SkeletonAnimation in spine-cocos2dx, just like the example “SkeletonAttachmentTest” in spine-libgdx

### ISSUE THREAD

**Issue by xiaoxiaocainiao** [EsotericSoftware/spine-runtimes#2159]
put a walking goblins on the spineboy's shoulder

**Comment by badlogic** [comment]
Have a lookt at this example:
https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-cocos2dx/example/Classes/SkeletonRendererSeparatorExample.cpp

**Comment by xiaoxiaocainiao** [comment]
> Have a lookt at this example: https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-cocos2dx/example/Classes/SkeletonRendererSeparatorExample.cpp

thank you  for ur replay~  but there is no SkeletonAttachement class, so i did not know how to put a skeleton to a slot.
