### ISSUE TITLE
[cpp] Incorrect parsing of dark color from skeleton binary file.

### ISSUE THREAD

**Issue by sp-javier-lupianez** [EsotericSoftware/spine-runtimes#2170]
## Description of the issue
We can see in this line
https://github.com/EsotericSoftware/spine-runtimes/blob/9d6afa18538d652c9a23d6a36d95edef5d783f51/spine-cpp/spine-cpp/src/spine/SkeletonBinary.cpp#L180
that the parser is retrieving **four bytes to set the Dark Color**, but then it only uses RGB to set the DarkColor inside the Slot's data inside the if block:
https://github.com/EsotericSoftware/spine-runtimes/blob/9d6afa18538d652c9a23d6a36d95edef5d783f51/spine-cpp/spine-cpp/src/spine/SkeletonBinary.cpp#L182

However, if we look at the exported .Json (since I cannot look plainly at the binnary), we see the following (screenshot of json exported with latest version v4.1.13 ENT):
![image](https://user-images.githubusercontent.com/30235017/194321929-b2c0b3cc-73b6-4a0a-b454-062f54dfa8be.png)

`"color"` has alpha (4 bytes) but `"dark"` does not have alpha (only 3 bytes). This matches with what can be seen in the Editor's interface:

(Light) Color
![image](https://user-images.githubusercontent.com/30235017/194322779-3d7a95b8-905e-4188-af9f-cb6c576d6c27.png)

Dark Color ("tint black" enabled)
![image](https://user-images.githubusercontent.com/30235017/194322717-eadda4c1-af5d-46a9-ba2d-1406e63ebfb3.png)

However, the color that get parsed in line 180 of `SkeletonBinary.cpp` is leaving the **red value always to Zero** and displacing the rest of bytes by 1 byte. 

Below can be seen a dark color set to yellow (0xFA, 0xFF, 0x10) in editor but drawn in cocos2dx runtime as (0x0, 0xFA, 0xFF), leaving the last byte (0x10) inside the alpha and thus unused:
![image](https://user-images.githubusercontent.com/30235017/194323942-00390c79-64ef-4fe5-93ae-3b3e285c95f2.png)

## Proposal and questions:
If the RGB of the Dark color is always displaced by 1 byte, it means two things:
- The parser should **only read three bytes for Dark color**, not four
- There is an "**unknown**" byte in the binaries between the Light color and the dark color that can only be **found within the source code of the editor**.

**Comment by badlogic** [comment]
Thank you for reporting this @sp-javier-lupianez. It's definitely a bug and looks to be a mistranslation of the reference implementation here:
https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/SkeletonBinary.java

This affects all spine-cpp based runtimes, I've changed the title of the issue accordingly. I'll fix this up in the 4.0-4.2-beta branches this week!

**Comment by badlogic** [comment]
This has now been fixed in the 4.0, 4.1, and 4.2-beta branches. Thanks for reporting!

**Comment by sp-javier-lupianez** [comment]
Thank you @badlogic!
