### ISSUE TITLE
how to add "SkeletonAttachment" in web project and iOS project?

### ISSUE THREAD

**Issue by xiaoxiaocainiao** [EsotericSoftware/spine-runtimes#2171]
Only android relate project "[spine-libgdx](https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-libgdx)" contains this   
class, I want to use this class in web project and iOS project, what should I do?

**Comment by badlogic** [comment]
`SkeletonAttachment` is not a supported feature in any runtime other than the `spine-libgdx` runtime. We currently do not plan on getting this to work in other runtimes in the short term.
