### ISSUE TITLE
[unity] SpineBuildProcessor modifies prefab when building android package

### ISSUE THREAD

**Issue by MonsterZhangChen** [EsotericSoftware/spine-runtimes#2174]
it is on **SpineBuildProcessor.cs**
```
public class SpineBuildProcessor {
		internal static bool isBuilding = false;

#if HAS_ON_POSTPROCESS_PREFAB
		static List<string> prefabsToRestore = new List<string>();
#endif

		internal static void PreprocessBuild () {
			isBuilding = true;
#if HAS_ON_POSTPROCESS_PREFAB
			var assets = AssetDatabase.FindAssets("t:Prefab");
			foreach(var asset in assets) {
				string assetPath = AssetDatabase.GUIDToAssetPath(asset);
				GameObject g = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
				if (SpineEditorUtilities.CleanupSpinePrefabMesh(g)) {
					prefabsToRestore.Add(assetPath);
				}
			}
			AssetDatabase.SaveAssets();
#endif
		}
}
}
```
W~(62W}{JGIDH9](https://user-images.githubusercontent.com/55493588/195268465-5f60f85a-836c-407d-b37f-ede15185e828.png)

when  I bulid,"**SpineEditorUtilities.CleanupSpinePrefabMesh(g)**" will modify spine prefab's meshrenderer, our game resources need hot update,This results in different assets each time you package project.
I want to know this Meaning of modification ,or can I  delete this modification?

**Comment by HaraldCsaszar** [comment]
If you did not intentionally modify the Materials at the skeleton MeshRenderer in the prefab, you can safely revert the modifications.

If you want to avoid preprocessing prefabs during build (which is there to remove the procedurally generated mesh at the `MeshFilter` to reduce build size), you can either remove (or comment out) this section of code or on recent 4.1 versions of the runtime disable Spine skeleton prefab optimization via `Edit - Preferences - Spine` under `Prefabs - Optimize Prefab Meshes`. You seem to be using an older version of the spine-unity runtime, which does not yet provide this option (I assume you are using a not up to date version 4.0).

**Comment by MonsterZhangChen** [comment]
Thanks for your help,  @HaraldCsaszar .
Today I get a new similar problem:even through nothing changed for assets , the spine ab packges will modified each time when  buliding AssetsBundles on mac OS...Up to now ,I don't found the causes of this modification,or can I comment out somewhere to disable it?
this is my version:
`This Spine-Unity runtime works with data exported from Spine Editor version: 4.0.xx
Package version: spine-unity-4.0-2022-01-19.unitypackage`
it without a option for " Optimize Prefab Meshes".I want to update verison but I'm afraid for a new bug.

**Comment by HaraldCsaszar** [comment]
@MonsterZhangChen Did you comment out the code that processes the prefabs in `SpineBuildProcessor.cs`?

Sice you are using version `4.0-2022-01-19`: please note that this is not the latest 4.0 spine-unity runtime available. Please download the latest 4.0 package from the download page (as always, backup your work before upgrading):
http://esotericsoftware.com/spine-unity-download#Older-Versions
