### ISSUE TITLE
Split the runtimes into individual repositories

### ISSUE THREAD

**Issue by jasonwinterpixel** [EsotericSoftware/spine-runtimes#2175]
To build the Godot Spine runtime as part of our fork of Godot, we are using a symlink into this repo, which is added to our game projects as a submodule. We would like to not use symlinks, and not have to check out this entire repository. The file size of cloning this repo is large (> 300MB), and symlinks in git are fragile, especially on windows. Having all the examples atlases is wasteful for us.

I recommend a more modular repository approach where each runtime is its own repo, ie:

https://github.com/EsotericSoftware/spine-godot
and
https://github.com/EsotericSoftware/spine-cpp

etc

I understand it would be a difficult task to change the repository architecture now, but I am submitting this issue to inform Esoteric of my thoughts here.

spine-godot shoud reference spine-cpp as a submodule, and not via copying.
https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-godot/build/setup.sh#L40

**Comment by NathanSweet** [comment]
We are aware and it's been suggested before:
https://github.com/EsotericSoftware/spine-runtimes/issues/758

Please see the comments there for our stance. If you don't like downloading the whole repo, you could use Git's partial/shallow clone.
