### ISSUE TITLE
[spine-cpp]Parameter optimization for ‘Animation::hasTimeline(Vector<PropertyId> ids)’

### ISSUE THREAD

**Issue by zhiyangyou** [EsotericSoftware/spine-runtimes#2177]
As the title says, the construction of the Vector<< PropertyId >>object will call its copy constructor, which may indirectly result in many calls to malloc.

https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-cpp/spine-cpp/src/spine/Animation.cpp#L53

![image](https://user-images.githubusercontent.com/70576712/195809331-436f79c2-076e-453c-b262-206546e60bc8.png)

**Comment by badlogic** [comment]
Oh dear, good find. Fixed in the 4.1 and 4.2-beta branches.
