### ISSUE TITLE
[godot] Latest build of Godot Editor does not load exported Spine projects with skins

### ISSUE THREAD

**Issue by lukeeingram** [EsotericSoftware/spine-runtimes#2184]
Reported by a user in our forums here:
http://esotericsoftware.com/forum/Importing-to-Godot-18149?p=79687#p79687

Reproduced this with Spine 4.1.14, latest build of the Godot editor available from our spine-godot documentation.
The Godot editor cannot load exported Spine projects whether exported as .skel or .json files. 

The Godot editor will load Spine assets that do not have skins attached.

Output shown below:
Godot Engine v3.5.stable.custom_build (c) 2007-2022 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- GDScript language server started ---
 No loader found for resource: res://spine-export/mix-and-match-pro.png.
 /home/runner/work/spine-runtimes/spine-runtimes/spine-godot/spine_godot/SpineAtlasResource.cpp:74 - Can't load texture: "res://spine-export/mix-and-match-pro.png"
New Scene Root
Create Node
Set skeleton_data_res
Set atlas_res
Set skeleton_file_res

**Comment by badlogic** [comment]
Repro:
1. Put exported assets into Godot project folder
2. Create a `SpineSkeletonDataResource`, set the caveman .atlas and .skel files

Error in console:
```
/Users/badlogic/workspaces/spine-runtimes/spine-godot/spine_godot/SpineSkeletonDataResource.cpp:177 - Error while loading skeleton data: res://assets/caveman/caveman-data.tres
 /Users/badlogic/workspaces/spine-runtimes/spine-godot/spine_godot/SpineSkeletonDataResource.cpp:178 - Error message: Error reading attachment: Dress
```

**Comment by badlogic** [comment]
The exported skeleton has multiple attachments called `Dress` in them. They each have different paths for lookup in the atlas. One of them has the path `DressGray.png`, which can not be found in the atlas. In fact, the skeleton has no attachment called `Dress` in it at all, but it's still exported by the editor multiple times.

**Comment by badlogic** [comment]
This is not a runtime issue.

The project has a skin placeholder called `Dress`, which has a region attachment called `Dress` beneath it. The project also has multiple skins, like `Grey0`, or `Yellow1`. The image path of the `Dress` region changes with each of those skins. For the `GreyXX` skins, the image path is set to `DressGrey.png`, for the `YellowXX` skins, the image path is set to `DressYellow.png`. When exporting the skeleton to JSON or binary, those image paths are written including the suffix. However, the regions in the exported atlas do no longer have that suffix. When the runtime tries to load the regions, it can't find `DressGrey.png` and consorts in the atlas and thus fails to load the skeleton.

I've fixed up the image paths for all skins in the project here:
[caveman.zip](https://github.com/EsotericSoftware/spine-runtimes/files/9850626/caveman.zip)

I'm unsure if this is a bug in the editor that needs fixing, or if users have to manually fix up the image paths.
