### ISSUE TITLE
spine - canvas 3.8 version in React

### ISSUE THREAD

**Issue by glitch-txs** [EsotericSoftware/spine-runtimes#2186]
Hello, I would like to use the library spine-canvas version 3.8 in React/Next but the npm package only dates from the 4.0.1 version. Same with spine-core.

 Is there a way to make them run in React?

Thanks!

**Comment by badlogic** [comment]
I'm afraid the build system of 3.8 isn't set up to be deployed to NPM or a local package repository. You can try to create your own `package.json`. I strongly suggest to upgrade to Spine 4.1.
