### ISSUE TITLE
[unity] Spine -> 2D Animation Package?

### ISSUE THREAD

**Issue by Gamer-XP** [EsotericSoftware/spine-runtimes#2190]
Do you have plans to make a support for 2D Animation package to replace mesh-based animations at some point?
https://docs.unity3d.com/Packages/com.unity.2d.animation@7.0/manual/index.html

Its main advantage over Spine's runtime is that it uses Unity's sprites, which allows to pack and batch characters properly withing Unity - it can batch Normal Sprite -> Deformed Sprite -> Normal Sprite without any issues.

We've used our own Spine -> Mecanim converter before for optimization purposes, but, after we started to use deformations, we were unable to keep using it and switched to official runtime. 2D Animation package does support skinning, so, in theory, it's possible to make use of it when importing spine animations.

**Comment by badlogic** [comment]
I'm afraid we have no such plans. Our runtime architecture and theirs is way too different for a conversion to actually work.
