### ISSUE TITLE
[unity] SkeletonRenderTexture not working on Android

### ISSUE THREAD

**Issue by havudk** [EsotericSoftware/spine-runtimes#2192]
Hi,

I have 2 problems with SkeletonRenderTexture. 
1. SkeletonRenderTexture not working on Android. You can reproduce in your sample "RenderTexture FadeOut Transparency" scene. In my case, it showing nothing.

2. And another problem is: it seem not working with mask. If I set the "Mask Interaction" of Skeleton Animation is "Visible inside mask", Render Texture will be rendered outside the mask.

Thanks very much.

**Comment by HaraldCsaszar** [comment]
Thanks for opening a new issue ticket.

Regarding issue 1, SkeletonRenderTexture not working on Android:
Unfortunately we could not reproduce this issue. When building and deploying on an Android test-device everything rendered as desired. Please note that for the `SkeletonGraphicRenderTexture` to display on the device, you need to add the shader `UI/Default` to the `Project Settings - Graphics - Always Included Shaders` list. The `SkeletonRenderTexture` GameObject `Spineboy CorrectFadeout` displayed right from the start in our test setup. Perhaps you need to also add the `Spine/RenderQuad` shader to your `Always Included Shaders` list as well, or make sure that the `SkeletonRenderTexture` component has the  `RenderQuadMaterial` assigned at the `Quad Material` property. Please check your setup accordingly, whether these project settings help resolve the issue for you.

Regarding issue 2, working with masks:
This is expected, the render-texture component will always just render the object to the texture. You need to assign a mask material (e.g. a copy of any `_Inside_Mask` material) at the used `Quad Material` that is assigned at your `SkeletonRenderTexture`.

**Comment by havudk** [comment]
Thanks for your reply.

About issue 2, working with mask. I was able to fix it. Thanks very much.

About issue 1, working on Android. I still cannot fix it.
What step I done is:
1. Create new unity project
2. Import spine-unity-4.1-2022-09-28.unitypackage
3. Add `Spine/RenderQuad` to `Always Included Shaders` (`UI/Default` was added already)
4. Open `RenderTexture FadeOut Transparency` scene
5. Build 
(Result: iOS is working and not working on Android)

My environment:
Unity 2021.3.8f1
Spine package version: spine-unity-4.1-2022-09-28
Tested on Android 10 and Android 11

I very appreciate If you can check my minimal Unity reproduction project 
[Spine4.1.zip](https://github.com/EsotericSoftware/spine-runtimes/files/9972579/Spine4.1.zip)
Thanks very much..

**Comment by HaraldCsaszar** [comment]
Unfortunately I still could not reproduce issue 1, your minimal reproduction project displays all three skeletons on our end.

> Spine package version: spine-unity-4.1-2022-09-28

Why are you using package version 2022-09-28 when the bugfix regarding render textures that we have provided for you in issue ticket #2180 was released on 22-10-28? Please always test using the latest package when issuing any bug reports, especially when a highly related bug has been fixed recently.
