### ISSUE TITLE
Is there a way replacing meshAttachment into regionAttachment in runtime?

### ISSUE THREAD

**Issue by TongDaDa** [EsotericSoftware/spine-runtimes#2194]
Hi, everyone, this question perplexing me for a long time after trying numerous methods to resolve it.  Why do this? The detailed reason is below. Maybe you are able to help me, please !!

**CONTEXT:**
Spine Runtime: canvas of spine-ts
Special Rendering Environment: Canvas2D (Can not use WebGL for some reasons)

**DETAILED QUESTION:**
As said in the [post](http://en.esotericsoftware.com/forum/canvas-12023) in _esotericsoftware_. The canvas does not support real 
MeshAttachment, so the official demo use `DrawTriangle` to finish it in Canvas rendering context, but with slow drawing.

Force canvas to render triangles is a waste of CPU resources. Or, is there a way to take another workaround for this situation by cutting the animated mesh region down? For example, to adapt the position of the region for mesh attachment, even if the mesh region cannot move flexibly.(using rect based on bone, other than triangles)

I tried this workaround by setting transformations `ctx.transform(bone.a, bone.c, bone.b, bone.d, bone.worldX, bone.worldY); ctx.rotate(bone.rotation * Math.PI / 180);`  for MeshAttachment. But, unfortunately, it appears incorrect translates, rotates without using triangles, vertices, uvs to draw it.

Just like the way, the figure is rendered below...

![截屏2022-11-12 下午10 29 20](https://user-images.githubusercontent.com/23241188/201478830-bf0f76df-c8fb-47da-86af-5218c6fe8b8a.png)

The figure rendered by setting `triangleRendering`:

![截屏2022-11-12 下午10 31 21](https://user-images.githubusercontent.com/23241188/201478912-8499c847-eee7-4ff4-b0dc-591ffda993df.png)

`triangleRendering` in canvas was very slow, that workaround (Replace it into rect region, just like regionAttachment) would be the best choice **without changing the `spine` file in keeping faster render.** 

Because there is a scenario using WebGL and Canvas in software, of course, we can use MeshAttachment smoothly for users whose computer supports WebGL, and the another will be taking a long time for rendering a frame in canvas. that is unfriendly to these users.

**Comment by NathanSweet** [comment]
The best solution is to use a skeleton that doesn't have meshes. You could replace meshes with regions at runtime, with enough effort to write the code, but you'd lose all bone weights and deformations, making it unlikely to be useful.

**Comment by TongDaDa** [comment]
> The best solution is to use a skeleton that doesn't have meshes. You could replace meshes with regions at runtime, with enough effort to write the code, but you'd lose all bone weights and deformations, making it unlikely to be useful.

Hello, NathanSweet, thanks for your reply😄. I'm curious about the `enough effort`, is that mean drawing MeshAttachment as a region with the correct position by computing triangles, vertices, uvs? could you detail more about this if you can, it is meaningful for me.

As far as know, losing all bone weights and deformations means related bones cannot animate perfectly, but the i**nitial positions** of bones can pose integrally. (As below)

![截屏2022-11-14 10 35 53](https://user-images.githubusercontent.com/23241188/201563425-65e4ccdf-3c52-4c34-946d-f792d8a4f809.png) (using triangle mode 😭)


I would give it a try if it's feasible by computing the vertices & uvs to shape an initial frame, even though related bones do not benefit from weights and deformation, it's acceptable.

**Comment by NathanSweet** [comment]
You can look at how a region attachment is drawn. Instead of drawing a mesh, you would draw the texture atlas region your mesh uses, like drawing a region attachment. You won't know where to draw it though, as a mesh is just a list of vertices. The mesh vertices could be moved, deforming the mesh and making it difficult to decide where to draw a rectangular image approximating the mesh.

The entire idea to draw a region instead of a mesh is just not going to work. It doesn't make any sense because a mesh can deform and a region cannot. It would be a lot of work and the results won't look good.

**Comment by TongDaDa** [comment]
> You can look at how a region attachment is drawn. Instead of drawing a mesh, you would draw the texture atlas region your mesh uses, like drawing a region attachment. You won't know where to draw it though, as a mesh is just a list of vertices. The mesh vertices could be moved, deforming the mesh and making it difficult to decide where to draw a rectangular image approximating the mesh.
> 
> The entire idea to draw a region instead of a mesh is just not going to work. It doesn't make any sense because a mesh can deform and a region cannot. It would be a lot of work and the results won't look good.


Ok, I understand that, thanks for your answer with patience. 🙏

**Comment by NathanSweet** [comment]
You can open the skeleton in Spine, use the tree filter to show only meshes, select all the meshes, and uncheck `Mesh` to turn them into region attachments. Spine will try to position the region attachments in a way that makes the most sense. If that looks OK, you could export the skeleton and use it for Canvas rendering instead of the skeleton with meshes.

**Comment by TongDaDa** [comment]
> You can open the skeleton in Spine, use the tree filter to show only meshes, select all the meshes, and uncheck `Mesh` to turn them into region attachments. Spine will try to position the region attachments in a way that makes the most sense. If that looks OK, you could export the skeleton and use it for Canvas rendering instead of the skeleton with meshes.

Ooook, sometimes, I want to go to Puerto Rico... 😁

**Comment by NathanSweet** [comment]
Best time is December to June. It's nice to enjoy the sun when it's snowing everywhere else!

**Comment by TongDaDa** [comment]
> Best time is December to June. It's nice to enjoy the sun when it's snowing everywhere else!

Followed you on GitHub, hoping to get a trip there, haha.
