### ISSUE TITLE
[godot] SpineSlotNode applies normal material to wrong node if Draw Order is changed during animation.

### ISSUE THREAD

**Issue by jasonwinterpixel** [EsotericSoftware/spine-runtimes#2195]
SpineSlotNode applies normal material to wrong node if Draw Order is changed during an animation.

https://user-images.githubusercontent.com/78934401/202018454-6a3a5e22-7433-41de-8ecc-0726e3628583.mp4

![image](https://user-images.githubusercontent.com/78934401/202019149-4356242b-3d84-448c-bfa3-689eca450217.png)

**Comment by jasonwinterpixel** [comment]
Probably need to adjust `SpineSprite::sort_slot_nodes` or call it more frequently.

**Comment by badlogic** [comment]
@jasonwinterpixel can you provide a small Godot project that let's me reproduce the issue?

**Comment by jasonwinterpixel** [comment]
Id like to, but I only have a gigantic project atm. I'm more inclined to fix it myself than break it down.

**Comment by badlogic** [comment]
The subtree in the scene in your video that shows the issue seems to be pretty simply. If you can share the skeleton file, the atlas and png files, the name of the animation you are playing back, and your materials, I can try to create a scene myself and reproduce the issue.

**Comment by jasonwinterpixel** [comment]
[spine_bug_repro.zip](https://github.com/EsotericSoftware/spine-runtimes/files/10044758/spine_bug_repro.zip)
I made a reproduction example. Play the 'floss' animation in the bug_example scene and you will see the shader alternate between the body and the left arm.

![image](https://user-images.githubusercontent.com/78934401/202801300-677f765d-4db6-4986-9c3f-8f4e718d1720.png)

**Comment by badlogic** [comment]
I'm so sorry, I missed your last comment! I'll check the repro and the fix submitted by @jordo on Monday!
