### ISSUE TITLE
ue4.27.2/spine-runtime4.1 Import direct error

### ISSUE THREAD

**Issue by caiyuncheng** [EsotericSoftware/spine-runtimes#2196]
![image](https://user-images.githubusercontent.com/28284861/202383155-b6c66ef0-bc9a-4466-8959-2db2b6ee3b05.png)

resource：
[loading_boy4.1.zip](https://github.com/EsotericSoftware/spine-runtimes/files/10028947/loading_boy4.1.zip)

**Comment by badlogic** [comment]
It's impossible to say what's wrong just based on this stack trace. Please provide a way to reproduce the issue, e.g. by describing what it is you are doing, by posting your assets, or a small project that shows the problem.
