### ISSUE TITLE
Spine Flutter runtime

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2200]
- [x] Debug renderer
- [x] `SpineWidgetController` coordinate system conversion methods (widget, global, skeleton local, etc.) + example(s)
- [x] Rename package to `spine_flutter` and publish (thanks @jtakakura)
- [x] Blend modes
- [x] Runtime documentation on website
- [x] Doc comments for API (also update C++ docs in the process)

# Issues
- [x]  https://github.com/flutter/flutter/issues/115919
- [x] https://github.com/flame-engine/flame/issues/2184

**Comment by LatCui** [comment]
I have the same problem. Have you solved it?
