### ISSUE TITLE
[spine-cpp] position xy would be a NaN, its acceptable?

### ISSUE THREAD

**Issue by huangwei1024** [EsotericSoftware/spine-runtimes#2208]
![image](https://user-images.githubusercontent.com/667876/205081428-fdf1129b-7eaf-438b-9ff4-e6b264d45128.png)

this png was capture frame in GPA.

I discoverd it when track a bug which missed some part of draw, so it perplex me.

wrong,  lost some part
![image](https://user-images.githubusercontent.com/667876/205082557-56331108-d08a-4580-83c1-3ae2fa5c25c5.png)

right
![image](https://user-images.githubusercontent.com/667876/205082803-95e8533c-728d-4fcc-9b47-9d021bd4fefa.png)

I'm not sure the bug directly related with NaN, But the missing part just the vertex were.

**Comment by badlogic** [comment]
NaN should never be seen in any of the runtimes computations. Please share code + assets so I can reproduce the issue. Please also let me know what version of the runtimes you are using.

**Comment by huangwei1024** [comment]
4.0.56
[huojianqiang.zip](https://github.com/EsotericSoftware/spine-runtimes/files/10151706/huojianqiang.zip)

play `skill1` animation

**Comment by huangwei1024** [comment]
I'm trying to make an experiment which update each spine in thread and draw it in main thread, every spine had an thread local pool(vertex, indice, command, etc)
could  you give me some advice on that?

**Comment by badlogic** [comment]
Do the `NaNs` show up only in your experiment? In general, spine-cpp is not thread safe. You can share `SkeletonData` across threads, but you can't share `Skeleton` without making sure only one thread can access the skeleton at any given time. I.e. if you use a thread to update the skeleton (`skeleton->updateWorldTransforms()`) and another thread to draw the attachments, chances are that one thread will stomp over the other, and you'll see `NaNs` and other misbehaviour.

I've created a little testbed using spine-cpp with spine-sfml, drawing your assets with animation `skill1`. I don't see an issue. However, the skeleton you send doesn't look anything like the images in your first post (neither for the "dun" nor the "putong" skin)

<img width="320" alt="Screenshot 2022-12-05 at 13 21 33" src="https://user-images.githubusercontent.com/514052/205636147-52aa6d1b-d049-4cb6-b889-7a8b36958484.png">

**Comment by huangwei1024** [comment]
each spine own their `SkeletonData` which no shared for other, and I test only one spine in experiment.

`NaN` are also existed in original `spine-cpp` implementation, but it look harmless.

in my thread case, I copy the vertex and indice to other place. the update thread was computed coord in indepented mem.

**Comment by huangwei1024** [comment]
whether `TwoColorTrianglesCommand._triangles ` would be write or read after `TwoColorTrianglesCommand::init` ?
