### ISSUE TITLE
[c] 'color.a' may be used uninitialized

### ISSUE THREAD

**Issue by pinguin999** [EsotericSoftware/spine-runtimes#2216]
Hi

my CI points out this Error. 

```
SkeletonJson.c:272:17: error: 'color.a' may be used uninitialized [-Werror=maybe-uninitialized]
  272 |         spColor color, color2, newColor, newColor2;
```

In toColor2 color->a is only written if hasAlpha is true. As far as I can see it's not accessed uninitialized but can we set it to 1.0f if hasAlpha is False?

Thanks,
Kolja

**Comment by badlogic** [comment]
Cheers, fixed!
