### ISSUE TITLE
Spine Phaser runtime

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2218]
- [x] Port rest of Phaser examples that apply
- [x] Write documentation
- [x] Deploy to NPM
- [x] Coordinate with Richard to tell Phaser community about the change.

**Comment by brett19** [comment]
This ticket implies that the implementation now works as expected.  Would you be able to confirm whether this is the case or is it still in the process of being implemented?

The context for the question is that I tried to pull it into an example, just to see how it works and the rendering does not appear to be working as expected (it draws upside down).

**Comment by badlogic** [comment]
@brett19 no, it's not ready unless this ticket is closed :)

Can you post your example and info on which browser/os you're running on?

**Comment by brett19** [comment]
It was just a spine skeleton with a single image, no animations or anything.  Loaded into the latest phaser with spine-phaser.  WEBGL was broken, CANVAS seemed to work mostly fine though (although I believe it was inverted).

**Comment by badlogic** [comment]
I can't fix the issue you see with your assets without them (and possibly info on your build/dependencies). I've ported almost all Phaser Spine demos over and they work as intended. My guess is that you may be pulling in a wrong spine-core and spine-webgl version somehow. See https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-ts/spine-phaser/example

Please post your small project so I can get a better idea of what's going on.

**Comment by spayton** [comment]
> I can't fix the issue you see with your assets without them (and possibly info on your build/dependencies). I've ported almost all Phaser Spine demos over and they work as intended. My guess is that you may be pulling in a wrong spine-core and spine-webgl version somehow. See https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-ts/spine-phaser/example
> 
> Please post your small project so I can get a better idea of what's going on.

All the official examples I've tried don't show correctly, texture is always green.  I assumed this was because it was under development, so when you say "they work as intended" then you must mean they look better than this?

![image](https://user-images.githubusercontent.com/4949575/234938879-5ab68487-02aa-44f0-b684-cd74749fb510.png)

**Comment by badlogic** [comment]
Ouch that's obviously broken. I can't reproduce this on any of my machines or browsers. Could you please provide me with your system specs, Chrome version, etc.?

**Comment by spayton** [comment]
Win10 x64, Chrome v112, straight git checkout today, built in nodeJs 19.4.0 - Same on Canary, Opera, Edge

Also tried on pixel5/chrome - same.  so probably my build.

Are the examples being hosted anywhere I can compare against?

**Comment by badlogic** [comment]
There's nothing in the build that could possibly cause this. I see if I can find a way to reproduce this. Thanks for the info!

**Comment by badlogic** [comment]
You can find the basic example here:
https://marioslab.io/dump/spine-phaser/example/basic-example.html

Does that work for you? Could you host your build somewhere so I can counter check?

**Comment by badlogic** [comment]
One more observation: I do not get the error your console shows at the bottom.

The green texture you see in your version is actually Phaser's placeholder texture used when referencing a texture fails. I see all the assets are being loaded, but it might be that turning the texture atlas .png into a WebGL texture is somehow failing in your case, which would trigger Phaser to use the placeholder texture. Maybe it's related to the error?

**Comment by spayton** [comment]
Your build works.  It also intermittently displays the same error.  The difference I see is a websocket which I'd guess is the dev  live reload.

![image](https://user-images.githubusercontent.com/4949575/234960028-6718ce85-b5c3-4c1b-bc11-dc71effe3a5d.png)

**Comment by badlogic** [comment]
Is there any indication where the error shown in your console is coming from? You get it both locally (where the websocket server exists) and when accessing the build on my server. That makes no sense.

Do you have any Chrome extensions that may interfere? Could you try in Firefox on your machine?

**Comment by spayton** [comment]
Yeah, a dozen or so extensions, always causing problems, disabling them doesn't fix the problem, but it does stop the error message.  Here's all extensions disabled.

![image](https://user-images.githubusercontent.com/4949575/234962200-cbcab604-55da-476a-9af4-0d8a56ef4138.png)

**Comment by badlogic** [comment]
I don't want to burden you with installing software you may not want. But could you try your local build on a clean install of Firefox without any extensions?

**Comment by spayton** [comment]
Sure, happy to help, we all benefit.

Also I did use your unminified spine-phaser.js, but still the same.

And spector captures are identical, except the WebGLUniformLocation IDs (sounds reasonable) and memory (hmmmm?):

![image](https://user-images.githubusercontent.com/4949575/234967763-79146934-6c74-40d5-84ac-a0634ff5d67a.png)

**Comment by spayton** [comment]
Fresh install Firefox v112.0.2 (64-bit), does the same as all other browsers that fail on my build.  And displays correctly your build.

**Comment by spayton** [comment]
Found it.  It's the End-Of-Line in the atlas file, mine has windows 0xOD, 0xOA, the files here have just 0x0A.  I didn't trace it far enough to see exactly what failed, but at least it did pull out the image filename.

I use Atlassian Source Tree, it's the prime suspect for converting them, anyway that's my problem to sort out.

Thanks for your help.

**Comment by spayton** [comment]
It looked like my setup was common so was surprised that this doesn't seem to be happening a lot, so dug deeper.

It turns out the the altlas data is being parsed ok except the image filename.  The image file is loaded but its key is added to the cache with a '\r' on the end, which gets stored incorrectly and subsequently not found/used correctly.

So maybe the spine runtime could tidy the key up, maybe phaser could also check the key.  I think probably both could address the issue to both be more robust, what do you think?

![image](https://user-images.githubusercontent.com/4949575/234989611-fe385759-a15c-428c-8a75-ab87277ccb6a.png)

**Comment by badlogic** [comment]
Oh my, that's indeed it. I mostly build things on macOS, so my checkout of the Git repository uses `\n` for textual files. I was able to reproduce by changing the line endings in the Spineboy `.atlas` file to `\r\n`.

<img width="237" alt="Screenshot 2023-04-28 at 09 00 37" src="https://user-images.githubusercontent.com/514052/235077602-19f04640-8689-4be0-b8a6-b656ef301d9b.png">

Which is very puzzling, as the code responsible for splitting the `.atlas` file into lines is doing the right thing:

```
this.lines = text.split(/\r\n|\r|\n/);
```

I'll have this fixed stat. Thanks for your help!

**Comment by spayton** [comment]
That's fixed it, with EOL left at 0D+0A, all phaser examples working as expected.

thanks

**Comment by badlogic** [comment]
Thanks for reporting!

**Comment by badlogic** [comment]
Done!
