### ISSUE TITLE
[player] Take clipping into account when calculating animation viewport

### ISSUE THREAD

**Issue by Disorrder** [EsotericSoftware/spine-runtimes#2219]
https://github.com/EsotericSoftware/spine-runtimes/blob/6661ae9322986c84267f7b4b71d66d332dad6d29/spine-ts/spine-player/src/Player.ts#L762

I suggest to calculate viewport size by clipping, but not min-max vertices. Sometimes animation goes out of bounds and player fits viewport size to not visible parts. It's unexpected behaviour for me, so I have to setup viewport manually which is taking much time and exhausting. 
See example, I expect to see these two animations in same bounding box, but 2nd orange jump outside of bottom border

(Could try to provide PR later if you agree with idea. But only for JS platform)

<img width="222" alt="image" src="https://user-images.githubusercontent.com/2883539/210064497-94655b8d-8fee-4d96-a960-68b26409fb85.png">
<img width="222" alt="image" src="https://user-images.githubusercontent.com/2883539/210064472-4782700f-008b-42a5-8ad0-488303ee36d5.png">

**Comment by badlogic** [comment]
Oh, that's actually a bug! This method must absolutely incorporate clipping. I'll try to get this fixed after my vacation, unless you send a PR before that!

**Comment by Disorrder** [comment]
@badlogic This method doesn't incorporate clipping because it's described inside `skin` category. But method only read animation params

**Comment by badlogic** [comment]
The method itself doesn't care where attachments, including clipping attachments, come from. What it needs to do is simulate the logic of `SkeletonRenderer` and clip region and mesh attachments when a clipping attachment is active, then take their min/max.

**Comment by davidetan** [comment]
This has been fixed with 03f8f67 and f309722.
See https://github.com/EsotericSoftware/spine-runtimes/pull/2220#issuecomment-2092602776 for more details.
