### ISSUE TITLE
Shader Language Transparency Incompatibility [Godot 3.5]

### ISSUE THREAD

**Issue by LemonadeFlashbang** [EsotericSoftware/spine-runtimes#2221]
First, take the following shader:
```
shader_type canvas_item;

uniform float whitening : hint_range(0, 1);
uniform vec4 shade_color : hint_color = vec4(1,1,1,1);

void fragment() {
    vec4 texture_color = texture(TEXTURE, UV);
   COLOR = vec4(mix(texture_color.rgb, shade_color.rgb, whitening), texture_color.a);
}
```
This shader takes an image and allows me to replace its color with a different one- often white- without modifying the transparency. This is useful for making something flash white or red when it takes damage, for example.

However, when attached to a SpineSpriteNode it disables all transparency in the animation. Take this character for example- we experimented with an "aura" around her but decided ultimately to drop it. This is her node WITHOUT the shader in place.

![SpineSprite with no Material](http://esotericsoftware.com/forum/download/file.php?id=11697)

Here she is with the shader with ZERO whitening- which should leave no color mixing or modification to transparency. You'll notice a previously transparent element, her aura, is now fully visible.

![SpineSprite with no Material](http://esotericsoftware.com/forum/download/file.php?id=11698)

And finally, here's what happens when you turn the whitening parameter up. She'll turn white, as expected. Her aura remains visible (And would become white, if it wasn't already).

![SpineSprite with no Material](http://esotericsoftware.com/forum/download/file.php?id=11699)

This is all with the shader in the "normal material" slot. The shader doesn't do anything when placed in additive/multiply/screen. Maybe there's a solution there? I couldn't find any documentation as to how to use them.

I'm guessing that, since the texture HAS color and is being hidden by the animation system, the shader is wiping the alpha value away. Does the runtime have any way to expose what the display transparency is to Godot's shader language? I'd love to be able to use color modifying shaders, but it's a no go if it reveals hidden elements.

**Comment by badlogic** [comment]
Did you actually hide the aura attachment in the skeleton? It's hard to tell what might be going on without knowing your skeleton setup in Spine.

Generally, the color of a pixel of a Spine attachment is defined by three things:
* The skeleton color
* The slot color
* The texture color

The skeleton and slot color are mixed and set as the vertex color for each vertex of an attachment in a slot. I guess you might have hidden the aura by setting its slot color, but you are only using the texture color of the aura attachment. You'll need to pass the vertex color to the shader as well and mix that in.

This is not really a bug in Spine, it's simply how things work. On our end, I don't quite see what we could do differently, so I'm closing this out but am happy to keep discussing your issue here.

**Comment by LemonadeFlashbang** [comment]
Thank you- your message helped me find a solution. In case someone stumbles upon this issue via Google, I'm going to document what worked for me. Mixing the vertex color did most of the work. I am not an animator, and can only view the project using Spine's trial version.

There's a more relevant animation for a different character where they have an element that "fades out" which obviously doesn't happen with the material attached. The original animation, used as a display case, involves some fx that I don't really know how is colored.

I can see the transparency being set via slot color here.

![image](https://user-images.githubusercontent.com/81896582/211167172-4487810b-0b4d-420f-a92c-6ddc24a463f9.png)

Passing in the alpha from the vertex **does not** fix the issue entirely. Here's an example case:
![image](https://user-images.githubusercontent.com/81896582/211167554-16861763-fe10-4712-ad88-aeabdc2e9233.png)
![image](https://user-images.githubusercontent.com/81896582/211167567-f51e0de1-b856-47a3-aa25-144a76d048db.png)

For my use case, we want the lowest alpha setting, so the following adjustment gets everything working smoothly.

`shader_type canvas_item;

uniform float whitening : hint_range(0, 1);
uniform vec4 shade_color : hint_color = vec4(1,1,1,1);

void fragment() {
	vec4 texture_color = texture(TEXTURE, UV);
	vec4 vertex_color = COLOR;
	
	COLOR = vec4(mix(texture_color.rgb, shade_color.rgb, whitening), min(texture_color.a, vertex_color.a));
}`

![image](https://user-images.githubusercontent.com/81896582/211167741-a0be7e94-8d25-433a-99b4-e194ce9b804c.png)
