### ISSUE TITLE
[godot] Extremely slow in-engine performance with large projects

### ISSUE THREAD

**Issue by LemonadeFlashbang** [EsotericSoftware/spine-runtimes#2226]
Hello!

I recently changed my animation engine from Creature2D to Spine2D. After doing so, I noticed a significant degradation in Godot's performance in-engine (not in game).

* Click events now take ~5 seconds to register.
* Drag and drop takes ~5 seconds to register.
* There is significant lag in the scripting interface.

I have two computers- and installed Spine on each of them. I am using Godot 3.5-master with a single script change to RichTextLabel to fix a rendering bug. [That script change is outlined here](https://github.com/godotengine/godot/pull/64540), although I don't believe it's relevant.

Here's a screenshot of the Task manager monitoring performance between three versions of the editor.

At the very top is a 3.5 Master with the Spine Runtime. It takes about 5.5 Gb of memory to run.
Below that is a version of 3.5 Master with Creature2D runtimes enabled. It takes about 2.0 Gb of memory to run.
The very bottom is 3.5 Stable with no additional modifications, for reference. It takes 1.6 Gb of memory to run.

![image](https://user-images.githubusercontent.com/81896582/213282055-d972be8e-43b6-406d-bf6a-95dea16115e8.png)

The 3.5 stable has NO in-editor lag. The version with Creature2D has SOME editor lag (click events may take a second to load). The version with Spine enabled has SIGNIFICANT in-editor lag.

![image](https://user-images.githubusercontent.com/81896582/213279957-d3cd0849-45df-4435-bec8-a9a113e6222c.png)

The entire game is preloaded at the start since Godot does not support multithreaded instancing. It fits in about 1Gb of memory, in debug mode.

My current computer isn't weak- it has 32 Gb of RAM, an i7-6700k CPU and an NVIDIA GTX 1070 GPU. I still find myself having to make modifications on my other computer, which has 64 Gb of RAM, a Ryzen 9 5950X CPU and a 3080, which I find completely overkill. 

This helps reduce, but notably does not eliminate in-engine lag using Spine.

Other things I've noticed while testing:

1. I opened a second project, [the background loading demo.](https://github.com/godotengine/godot-demo-projects), and memory usage dropped to 2.5 Gb for each.

![image](https://user-images.githubusercontent.com/81896582/213284584-3ef77690-c435-45c3-9d90-c89320c8c191.png)

2. There is no lag in click events in editor in the demo project referenced above. It's likely this issue only occurs in large projects.

3. My task manager sees CPU usage spike to 25% and power usage jump to "Very High" when I enter a click event in my current project.

![image](https://user-images.githubusercontent.com/81896582/213284804-8072630c-14cf-4699-953b-cd2386fcb47e.png)

I wanted to make this post to document the issues, and see if we could potentially find a solution. I'm not sure what's causing the sizable memory increase, and I'm also not sure what's causing the huge CPU spikes upon registering a click I don't think it's just a matter of memory- given that my current computer has so much available. With the current lag spikes and power usage as they are, however, the engine is essentially unusable on this machine.

I ran the engine with the --verbose flag turned on, and didn't find anything helpful.

**Comment by badlogic** [comment]
It's impossible to say what's going on without being able to reproduce this on my end. I'll need more info.

1. Given you apply a fix to the rich text label, you do compile each engine binary youself, correct? How do you compile them?
2. Can you load the project with the Godot binary we provide? See http://esotericsoftware.com/spine-godot#Installation
3. Is there a way for me to get the big project of yours so I can locally try to reproduce the issue? I've not seen anything like this before and I honestly have no idea what could be the cause.

**Comment by LemonadeFlashbang** [comment]
1. I follow the setup instructions through "./build/setup.sh 3.5-stable false" in accordance with [this guide](http://esotericsoftware.com/spine-godot#Compiling-the-Godot-editor-and-export-templates-from-source). I then enter the created "godot" folder, replace the two changed files in the /scene/ folder with custom ones, and then resume following the guide to completion.

2. Using the pre-compiled binary doesn't appear to have any performance improvement:
![image](https://user-images.githubusercontent.com/81896582/213314214-8c1de82e-91e4-4c87-b6aa-78176f42e11f.png)

3. Yep- I'll add you as a collaborator. The game is relatively far in development for a Godot project so I figured repro might be difficult. You'll want the "spine" branch specifically.

**Comment by LemonadeFlashbang** [comment]
Actually- I've managed to reproduce it in a MUCH simpler manner. I'll leave you as a collaborator so we can validate against the full project, but here's a smaller test case.

Here's an [example repo.](https://github.com/LemonadeFlashbang/SpineBugRepro) All I've done is flooded the "assets" folder with copies of the exact same 8 images. This is smaller than a full project- no sound, no code, etc., but is a good demonstration of just raw bulk.

I've then created a basic resource so you can check the drag and drop functionality. It just has 10 exposed Texture variables.

Repro steps:

1. Open the project in 3.5 Godot + Spine. Open the "Assets_Small" folder and drop the images there into "new_resource.tres", click around, etc.,
2. Do the same thing in 3.5 Master.

It's possible the project will struggle to open the first time in 3.5 with Spine integrated, because it'll freeze up when importing the files. I'd recommend opening it with 3.5 Master FIRST until the imports are handled, then swapping over to 3.5 with Spine.

This repo is NOT as laggy as my current project, but it's only about a quarter the size. You should still notice some lag, but if you have a very powerful machine you can duplicate the files in the Assets folder once / twice / thrice and you should begin to notice results.

**Comment by Mazianni** [comment]
This issue is not just present with large projects. I was exploring the prebuilt editor to begin working on some portions of a small project and experienced considerably lag with the prebuilt binary for Windows - even when opening the prebuilt editor to simply _open_ a project had significant UI lag (~1-2s), and it took close to a minute to actually open the project I wanted to work on previously. These issues are not present in the normal Godot editor (3.5.1).

**Comment by badlogic** [comment]
To me this sounds like I have an error in the way I bild the pre-built
editor. I'm investigating. Thanks for the repro.

**Comment by badlogic** [comment]
I'm actually seeing the exact same problem with vanilla Godot 3.5-1 build by the Godot folks as well. I'm running it on a super beefy Windows laptop, and just opening an empty project takes forever. The UI is also very unresponsive. I'm talking to the Godot folks to try and figure this out.

**Comment by LemonadeFlashbang** [comment]
It's odd to me you're seeing it with new projects on 3.5-1, since aside from maybe startup that editor's quick for me.

Thank you for the transparency.

**Comment by badlogic** [comment]
I found the issue. The Windows build was actually incorporating address sanitizer, which leads to various issues, including things being terribly slow. I've fixed this in the 4.1 and 4.2-beta branches and the pre-built binaries are currently being build via GitHub actions.

You can download them from the URLs found in the docs once this action has completed (should be about 2 hours from now):
https://github.com/EsotericSoftware/spine-runtimes/actions/runs/3995038482

**Comment by badlogic** [comment]
@LemonadeFlashbang since you are building the editor yourself, make sure you pull in the latest `spine-godot/build/build.sh` script. It contains the fix for the issue.

**Comment by LemonadeFlashbang** [comment]
@badlogic The custom build is failing- looks like some of the CPP files are pointed for headers without the "Spine" prefix:

![image](https://user-images.githubusercontent.com/81896582/214384355-7573ae10-0e82-4786-a2d6-4a690bc6c61c.png)

The pre-compiled editor looks like it failed to upload to S3- so I can't verify if the issue is fixed there.

**Comment by badlogic** [comment]
Sorry, I kept working on the runtime to get it up to speed with Godot 4.0 again.

The errors you get in your custom build stem from [spine-cpp] not being where it should be. Did you run the `build/setup.sh` script? You should have a `spine-godot/spine_godot/spine-cpp` folder in your checkout of the runtime after running that script.

**Comment by LemonadeFlashbang** [comment]
Looks like that directory isn't there. I ran:

`./build/setup.sh 3.5.1-stable false`

Which created the `spine-godot/godot` directory, but did not create the `spine-godot/spine-godot/spine-cpp`

**Comment by LemonadeFlashbang** [comment]
Issue was user error and has been corrected.

Confirming the issue is fixed- the engine is super quick now. Thank you so much! This is a gigantic performance increase!

**Comment by badlogic** [comment]
Yay :)

I tested all the pre-built binaries after the last action run as well. All good. Thanks for alerting me to this!
