### ISSUE TITLE
[ts][webgl] Polygon culling bug

### ISSUE THREAD

**Issue by lukeeingram** [EsotericSoftware/spine-runtimes#2227]
Reported by a user in our forums here:
http://esotericsoftware.com/forum/spine-ts-4-1-spine-webgl-PolygonBatcher-ts-cull-face-bug-18515?p=81156#p81156

**Comment by NathanSweet** [comment]
Culling was disabled in #1976, but users may want it enabled as it can be useful for skeletons that use faux 3D effects. The editor has a setting to enable it (disabled by default).

@badlogic Maybe it would be better to not set culling and leave it to the user?
