### ISSUE TITLE
[player] Assets could not be loaded from data url

### ISSUE THREAD

**Issue by jomin398** [EsotericSoftware/spine-runtimes#2228]
>Error: Assets could not be loaded.
{&#34;ï»¿c112_00.png&#34;:&#34;Couldn&#39;t load image: ï»¿c112_00.png&#34;,&#34;c112_00.atlas&#34;:&#34;Couldn&#39;t load texture atlas c112_00.atlas page image: ï»¿c112_00.png&#34;}

```js
async function f2Durl(p) {
    const response = await fetch(p);
    const blob = await response.blob();
    //console.log(blob)
    const base64 = await new Promise(r => { let a = new FileReader(); a.onload = r; a.readAsDataURL(blob) }).then(e => e.target.result);
    return base64;
}
//spine player option object
spo.rawDataURIs['c112_00.atlas'] = await f2Durl('./asset/c112_00.atlas');
spo.rawDataURIs['c112_00.png'] =await f2Durl('./asset/c112_00.png'); 
```

i looked atlas file with [Base64 decoder](https://www.base64decode.org/).
it looks same as atlas file.
```txt
﻿c112_00.png
size:2048,2048
```

why it's parsed wrong?

**Comment by badlogic** [comment]
It looks like your files have an encoding issue. The image path in the atlas after base64 decoding seems to start with ` ï»¿`. Make sure that the `.atlas` is UTF-8 encoded.
