### ISSUE TITLE
[Godot] Adding a windows native icon causes debugger to fail

### ISSUE THREAD

**Issue by LemonadeFlashbang** [EsotericSoftware/spine-runtimes#2229]
Running the editor with a Windows icon in the settings causes the debugger to immediately fail.

Here's an output of the logs when Godot 3.5-1 with Spine is run with the --verbose command.

![image](https://user-images.githubusercontent.com/81896582/214256739-f6e46794-4058-4fce-8813-c7af203187ac.png)
[spine_crash_log.txt](https://github.com/EsotericSoftware/spine-runtimes/files/10488129/spine_crash_log.txt)

Screencap of the console output, with the complete output attached.

For comparison, below is a log for the same exact project on 3.5-1.
[spine_crash_log_master.txt](https://github.com/EsotericSoftware/spine-runtimes/files/10488141/spine_crash_log_master.txt)

Reproduction steps:

1. Move an icon into the project directory
2. Set the Windows Native Icon to the new icon
3. Hit run

Tested on Godot 3.5-1 as well as the pre-built Spine editor from the webpage.

Notably, you can export a project to an executable with the icon intact- this only crashes projects via the in-editor debugger.

**Comment by badlogic** [comment]
Currently resolving all the issues you've been reporting. The build for the pre-built binaries contained an incorrect build option flag. The above error will go away once the new pre-built binaries are build.

**Comment by LemonadeFlashbang** [comment]
That's fantastic news. Thank you!
