### ISSUE TITLE
[spine-player] Cannot load image from base64 URL?

### ISSUE THREAD

**Issue by jomin398** [EsotericSoftware/spine-runtimes#2231]
why Cannot load image from base64 URL?

i checked out `.atlas` file written with **UTF-8** and also i tested with fetch, All data file is accessible.
but throws error. where came from?

![image](https://user-images.githubusercontent.com/23178638/215243347-b1e9f1c3-0280-499f-a14e-e6c3003e14c9.png)

**Comment by badlogic** [comment]
It's impossible to say why it fails based on your screenshots. The only thing I can decipher is that loading the `.png` file failed. Please provide a full reproduction sample so I can debug this.
