### ISSUE TITLE
[godot 4 beta] hero (the Spine example) shows all attachments all the time

### ISSUE THREAD

**Issue by karljs** [EsotericSoftware/spine-runtimes#2232]
I'm using the 4.0 build provided recently and am noticing some weird behavior with the Hero example (from Spine, not an example bundled with the runtimes). I export/import it according to the instructions, but it seems that the unused attachments/skins are not hidden when unused.

Here's what I see when I initially import and create a SpineSprite. Note the weapons at the bottom.

<img width="498" alt="Screenshot 2023-01-28 at 21 09 48" src="https://user-images.githubusercontent.com/317063/215307026-be6d1bf5-6539-4717-8b40-d29dbbc0fa76.png">

If I then set the skin to one weapon or the other, it works as expected, but the other never disappears:

<img width="450" alt="Screenshot 2023-01-28 at 21 10 19" src="https://user-images.githubusercontent.com/317063/215307072-e6e13c31-a6b7-42cb-9de1-d13c8ce9b783.png">

Finally, if I switch from the skin I just set to the other, the sword stays where it was:

<img width="453" alt="Screenshot 2023-01-28 at 21 10 29" src="https://user-images.githubusercontent.com/317063/215307096-46cc5912-f39f-4871-8256-148490a81be4.png">

I also noticed this (possibly unrelated) error when I import the Spine files into Godot. This specific instance of the error was me trying to reproduce this with the mix-and-match example, which I was unable to do, but it happens for all the imports I've tried. The import appears to continue though, and the PNG looks normal inside Godot.

<img width="1007" alt="Screenshot 2023-01-28 at 21 23 36" src="https://user-images.githubusercontent.com/317063/215307143-a297c70d-b150-42d7-9934-3e40ec062407.png">

**Comment by badlogic** [comment]
Re: the second issue, I've seen this as well and I have no idea why it happens.

Regarding the hero, I'm investigating. Note that the 4.0 binary we ship is still "experimental" as Godot 4.0 hasn't been relesaed yet, and there are a lot of regression compared to Godot 3.5. It will be a while before Godot 4.0 can be considered stable.

**Comment by badlogic** [comment]
Found the issue: the renderer also rendered slots of inactive bones. Fixed in 4.1 and 4.2-beta branch. New binaries are being build here in GitHub via actions. Thanks for reporting!
