### ISSUE TITLE
Generation of the Core API C# project failed

### ISSUE THREAD

**Issue by jerrychoux** [EsotericSoftware/spine-runtimes#2238]
need compile spine-godot with mono
`
scons $target tools=yes module_mono_enabled=yes mono_glue=no compiledb=yes custom_modules="../spine_godot" opengl3=yes --jobs=$cpus	
bin/godot.windows.editor.x86_64.mono --generate-mono-glue modules/mono/glue
scons $target tools=yes module_mono_enabled=yes compiledb=yes custom_modules="../spine_godot" opengl3=yes --jobs=$cpus	
`
![image](https://user-images.githubusercontent.com/37604487/217452034-e4063ffa-1b0d-4658-b468-50a128fe1240.png)
thx !

**Comment by badlogic** [comment]
I'm not setup to build Godot with Mono support currently, but tried to fix this anyways. Please give the latest commit on either the 4.1 or 4.2-beta branch a try and let me know if it resolves the issue for you.

**Comment by jerrychoux** [comment]
Thank you for your reply
I tried to compile again in windows at the latest commit on spine-runtimes 4.1, and godot master.
compile is ok
but crash when create a new project and open it
![image](https://user-images.githubusercontent.com/37604487/217787803-2e33184b-bfd7-4ceb-b200-584b03f2bc4a.png)
thx !

**Comment by badlogic** [comment]
Based on the stacktrace, the Mono integration itself crashes, nothing
related to the Spine Godot module crashes. I'm afraid I can't help with
that. The folks in the Godot chat can help. Also note that Godot 4.0 lacks
batching, on which the Spine Godot module relies. I'd advice against using
Godot 4.0 for the time being.
