### ISSUE TITLE
[godot] Add pivot point visual to SpineSprite node in editor.

### ISSUE THREAD

**Issue by DASilverStraw** [EsotericSoftware/spine-runtimes#2239]
The pivot point is where the root bone is located. It would be helpful to be able to see it especially when positioning SpineSprite node in the scene space.

**Comment by badlogic** [comment]
Does this help? Pushed to 4.1 and 4.2-beta branch.

<img width="1265" alt="Screenshot 2023-02-10 at 23 18 49" src="https://user-images.githubusercontent.com/514052/218209403-974cf461-07a5-4abc-a705-7b42f86c1696.png">

**Comment by DASilverStraw** [comment]
Yes, it does. Would it be possible to commit to stable branch? A case scenario would be using it for y-sorting sprites as the draw order is determined by the root bone location. The only way of determining the root location in Godot that I can think of is resetting the Node2d transform position. Going between the origin and another location in the scene space leads to slower progress especially for large scenes.
