### ISSUE TITLE
Please help me fix the webgl problem.

### ISSUE THREAD

**Issue by 2elffire** [EsotericSoftware/spine-runtimes#2240]
Hello.

I want to control the camera when I touch two fingers.

new spine. CameraController(canvas, renderer. camera);
After running , I want to delete the camera control when only one finger touches it.

I want the controlBones to move when touched with one finger.

I want only the controlBones to move when I touch with one finger, and only zoom and move the camera when I touch with two fingers.

I ask for your help.

**Comment by lukeeingram** [comment]
Hello,

Do you have code that you could share with us on how you're trying to accomplish this?

**Comment by badlogic** [comment]
This is not a bug report. Let's handle it on the corresponding forum thread. https://esotericsoftware.com/forum/d/18564-webgli-want-to-control-it-with-two-fingers-on-mobile/3
