### ISSUE TITLE
[godot] SpineSprite node cannot be duplicated/copied/pasted because of SpineMesh2D class

### ISSUE THREAD

**Issue by DASilverStraw** [EsotericSoftware/spine-runtimes#2242]
Class 'SpineMesh2D' or its base class cannot be instantiated.
 scene\main\node.cpp:2188 - Condition "!obj" is true. Returned: nullptr
 editor\scene_tree_dock.cpp:727 - Condition "!dup" is true. Continuing.

**Comment by badlogic** [comment]
Oh no, I overlooked that. Thanks for reporting. Fixing.

**Comment by badlogic** [comment]
Forgot to register the `SpineMesh2D` type. Copy and pasting works now. But for some reason it now shows the "internal" `SpineMesh2D` instances in the tree view. Those shouldn't get copied at all. Investigating why that happens.

<img width="239" alt="Screenshot 2023-02-10 at 22 58 19" src="https://user-images.githubusercontent.com/514052/218206680-53c8a799-d4a1-43fd-8104-e41b6d8eaa47.png">

**Comment by badlogic** [comment]
Looks like a bug in Godot 4.0, for which there's a PR that hasn't been merged yet...

https://github.com/godotengine/godot/pull/63130
