### ISSUE TITLE
[c] Step curve not applied when using JSON export

### ISSUE THREAD

**Issue by jabuwu** [EsotericSoftware/spine-runtimes#2253]
Hey friends, I made a really simple Spine rig which only uses step curves and was surprised when it used a linear curve instead. The video below demonstrates the correct behavior, followed by the incorrect behavior. The only difference is that the first skeleton is loaded using binary format, and the second uses JSON.

I demonstrated the issue in a repo. The source Spine file is also in the repo (treats/source), export files are from Spine 4.1.19 Professional.

https://github.com/jabuwu/spine_json_rotate_bug

https://user-images.githubusercontent.com/46233424/220027614-134cbee0-799a-43c4-bb05-69834c004b0e.mov

Thanks for your time!

**Comment by badlogic** [comment]
Thank you for the great repro! I've fixed this in both the 4.1 and 4.2-beta branches.
