### ISSUE TITLE
[c] JSON loader segfaults when loading an empty skin

### ISSUE THREAD

**Issue by jabuwu** [EsotericSoftware/spine-runtimes#2258]
Loading JSON files with an empty skins (no attachments) causes a segmentation fault in latest spine-c. A simple repro is to create a new project, add a single skin, export as JSON (I'm using 4.1.19 Professional), and try to load the file with `spSkeletonJson_readSkeletonDataFile`.

Binary files do not have this problem.

Thanks for your time!

**Comment by badlogic** [comment]
Thanks for reporting. This has been fixed in the 4.1 and 4.2-beta branches.
