### ISSUE TITLE
[ts][webgl] Running spine animation on iOS 16.4 Beta cause the web page to be unresponsive

### ISSUE THREAD

**Issue by KingsleyChung** [EsotericSoftware/spine-runtimes#2259]
Our team apply the spine-webgl runtime to render spine animation in our project. We found that the webview in our app would be unresponsive on iOS 16.4 Beta1 and Beta2，and even the official spineboy demo running on the Safari will reproduce this issue

**Comment by badlogic** [comment]
I don't have a device with any of the betas on them to test. But on the simulator our demos work as intended:
http://esotericsoftware.com/spine-demos

Can you share sample code that reproduces the issue?

**Comment by KingsleyChung** [comment]
> I don't have a device with any of the betas on them to test. But on the simulator our demos work as intended: http://esotericsoftware.com/spine-demos
> 
> Can you share sample code that reproduces the issue?

I used this demo to reproduce the problem:

**Comment by KingsleyChung** [comment]
> I don't have a device with any of the betas on them to test. But on the simulator our demos work as intended: http://esotericsoftware.com/spine-demos
> 
> Can you share sample code that reproduces the issue?

I use this demo to reproduce the problem:
http://esotericsoftware.com/files/runtimes/spine-ts/examples/webgl/

Open this demo and leave the phone for about 5 minutes, and the animation will freeze.

**Comment by badlogic** [comment]
As I said, I currently do not have a device that runs iOS 16.4 Beta1 or Beta2. I let it run on a beta simulator and it did not freeze.

We've previously seen issues with WebGL on beta iOS and Safari releases. They all were bugs in the betas. I'm afraid on our end, there's not much we can do, as our WebGL code is correct.

**Comment by KingsleyChung** [comment]
I have reproduced the problem by running this demo:

**Comment by KingsleyChung** [comment]
> As I said, I currently do not have a device that runs iOS 16.4 Beta1 or Beta2. I let it run on a beta simulator and it did not freeze.
> 
> We've previously seen issues with WebGL on beta iOS and Safari releases. They all were bugs in the betas. I'm afraid on our end, there's not much we can do, as our WebGL code is correct.

I have reproduced the problem by running this demo(http://esotericsoftware.com/files/runtimes/spine-ts/examples/webgl/) on Safari of iPhone 14 Pro Max iOS 16.4 simulator, and I left the simulator at the background for about 30 minutes, the animation froze. It didn't recover even though I changed animation or changed skeleton. For comparison, I also did the same thing on iPhone 14 Pro Max iOS 16.2 simulator, it didn't has this problem.

Here is the video: https://drive.google.com/file/d/173S2bjXu4-h6l00HvP8d1iJ3nfphQIYM/view?usp=share_link

**Comment by KingsleyChung** [comment]
> As I said, I currently do not have a device that runs iOS 16.4 Beta1 or Beta2. I let it run on a beta simulator and it did not freeze.
> 
> We've previously seen issues with WebGL on beta iOS and Safari releases. They all were bugs in the betas. I'm afraid on our end, there's not much we can do, as our WebGL code is correct.

The problem was solved by updating to iOS 16.4 Beta3. Thanks.
