### ISSUE TITLE
[Godot] How to get alpha channel (transparency) of SpineSprite node?

### ISSUE THREAD

**Issue by wacyym** [EsotericSoftware/spine-runtimes#2260]
In our project we have some SpineSprites which has transparency fade-in Spine animation.
I want to inherit the transparency of this SpineSprite (parent) for the transparency of Node2D (child for SpineSprite).

I tried to use the Node SpineBoneNode in Follow mode and it works for transformations from the parent SpineSprite, but this does not work for transparency. Are there any ways to obtain transparency from SpineSprite?

**Comment by badlogic** [comment]
You can get the color (and thus alpha channel value) for any slot in a `SpineSprite` via `SpineSprite.get_skeleton().find_slot("slot name").get_color()`. That will return a Godot [`Color`](https://docs.godotengine.org/en/stable/classes/class_color.html) from which you can get the alpha channel value as either a float or 8-bit int.

As for your use of `SpineBoneNode`, if you need your child to be sorted correctly into the drawing order of your `SpineSprite` attachments, consider using `SpineSlotNode` instead.
