### ISSUE TITLE
Add windows export template to archive for 4.0

### ISSUE THREAD

**Issue by tapir2342** [EsotericSoftware/spine-runtimes#2262]
Hey, could you please add the windows template to the export template archive that's downloadable [here](http://en.esotericsoftware.com/spine-godot)? Thanks!

As of the time of writing, this is the file listing of the archive:

```
$ unzip spine-godot-templates-4.1-4.0-stable.tpz 
Archive:  spine-godot-templates-4.1-4.0-stable.tpz
 extracting: ios.zip                 
 extracting: macos.zip               
  inflating: linux_x11_64_debug      
  inflating: linux_x11_64_release    
 extracting: web_debug.zip           
 extracting: web_release.zip         
  inflating: android_release.apk     
  inflating: android_debug.apk       
 extracting: android_source.zip      
 extracting: version.txt
```

Thank you!

**Comment by badlogic** [comment]
Sorry, it's unclear why the tempalte is not included. You can find it here in the meanwhile:
https://github.com/EsotericSoftware/spine-runtimes/actions/runs/4322808934
