### ISSUE TITLE
[c] Atlas default values are not handled

### ISSUE THREAD

**Issue by jabuwu** [EsotericSoftware/spine-runtimes#2264]
Hey again. 😅

Spine does not export a value for `format` in the atlas file if it's `RGBA8888`. Presumably, this is the default expected value. However, it's not set to this default before parsing, so if `format` isn't found, it's never set and remains 0 (`SP_ATLAS_UNKNOWN_FORMAT`).

This is the only line `format` is set:

https://github.com/EsotericSoftware/spine-runtimes/blob/7c76c5803c086b04065bfceee323f948ce9a3c7c/spine-c/spine-c/src/spine/Atlas.c#L325-L326

`filter` has the same problem if using `Nearest,Nearest`, min and mag filters remain `SP_ATLAS_UNKNOWN_FILTER`, since it's not written to the atlas file.

As always, thanks for your time.

**Comment by badlogic** [comment]
Jeez, I'm starting to look like a real amateur. Thanks for all the issues. I'll fix them up tomorrow!

**Comment by jabuwu** [comment]
I don't blame you for not wanting to spend too much time writing C, but it's great that you guys have such a portable runtime. I'm happy to help work through the kinks!

**Comment by badlogic** [comment]
Cheers, this has been fixed in the 4.1 and 4.2-beta branches.
