### ISSUE TITLE
[spine-player] rendering multiple characters

### ISSUE THREAD

**Issue by jomin398** [EsotericSoftware/spine-runtimes#2267]
If I have one character, I can rendering it as  following an example, but it's more than one, or the character and background have to be rendered at the same time, so what should I do?

I need a guide to follow.

**Comment by badlogic** [comment]
The player is only meant to render one character. If you want a background, then see the documentation:
http://en.esotericsoftware.com/spine-player#Background-image

If you want to render multiple characters, you'll have to use spine-webgl, or the [Phaser Spine Runtimes](https://phaser.io/examples/v3/category/spine), or the [pixi-spine runtimes](https://github.com/pixijs/spine)
