### ISSUE TITLE
[unity] Create SkeletonDataAsset from .skel.bytes file at runtime

### ISSUE THREAD

**Issue by zawazawagh** [EsotericSoftware/spine-runtimes#2271]
I want to do these things

- Download .skel.bytes, png, atlas.txt from remote server
- Create SkeletonDataAsset instance at runtime
- NOT importing these files in editor process. I mean, just instancing in runtime process.

In official doc, you said that[ it is possible](http://esotericsoftware.com/spine-unity#Advanced---Instantiation-at-Runtime) to create SkeletonDataAsset from .skel.bytes at runtime, but I can't find a way to make TextAsset  from .skel.bytes and read it correctly.

Please tell me how to create valid TextAsset from .skel.bytes for instancing SkeletonDataAsset.

I'm currently writing this code and cannot perform correctly.

``` csharp
void Start()
{
    //get resources path out of the assets folder.
    var dataPath = Directory.GetCurrentDirectory();
    var pngFile = $"{dataPath}/{s_actionName}.png";
    var atlasTextFile = $"{dataPath}/{s_actionName}.atlas.txt";
    var skelFileFl = $"{dataPath}/{s_actionName}-fl.skel.bytes";
    var skelFileBr = $"{dataPath}/{s_actionName}-br.skel.bytes";

    //Create needed assets
    TextAsset atlasTextAsset = new TextAsset(File.ReadAllText(atlasTextFile));
    _mat = new Material(SpineSkeletonShader);
    var pngBytes = File.ReadAllBytes(pngFile);
    _tex = new Texture2D(2, 2);
    _tex.LoadImage(pngBytes);
    _mat.mainTexture = _tex;

    //create SpineAtlasAsset
    SpineAtlasAsset = ScriptableObject.CreateInstance<SpineAtlasAsset>();
    SpineAtlasAsset.name = $"{s_actionName}_Atlas";
    SpineAtlasAsset.atlasFile = atlasTextAsset;
    Atlas atlas = SpineAtlasAsset.GetAtlas(onlyMetaData: true);
    foreach (var atlasRegion in atlas.Regions)
    {
        atlasRegion.page.rendererObject = _mat;
    }

    SpineAtlasAsset.materials = new[] { _mat };

    //Create SkeletonDataAsset

    //this workaround correctly read .skel.bytes file. BUT cannot create SkeletonDataAsset from SkeletonData
    SkeletonAsset = ScriptableObject.CreateInstance<SkeletonDataAsset>();
    AtlasAttachmentLoader atlasLoader = new AtlasAttachmentLoader(atlas);
    SkeletonBinary binary = new SkeletonBinary(atlasLoader);
    SkeletonData data = binary.ReadSkeletonData(skelFileFl);

    // Cannot read .skel.bytes file and ends up with errors.
    // 1. TextAsset skelBytesTextAsset = new TextAsset(Convert.ToString(File.ReadAllBytes(skelFileFl)));
    // 2. TextAsset skelBytesTextAsset = new TextAsset(Encoding.Default.GetString(File.ReadAllBytes(skelFileFl)));
    // 3. TextAsset skelBytesTextAsset = new TextAsset(Encoding.ASCII.GetString(File.ReadAllBytes(skelFileFl)));
    // 4. TextAsset skelBytesTextAsset = new TextAsset(Encoding.UTF32.GetString(File.ReadAllBytes(skelFileFl)));
    skelBytesTextAsset.name = "mymotion.skel.bytes";
    SkeletonDataAsset runtimeSkeletonDataAsset
        = SkeletonDataAsset.CreateRuntimeInstance(skelBytesTextAsset, SpineAtlasAsset, true);
    runtimeSkeletonDataAsset.name = $"{s_actionName}_SkeletonData";
    SkeletonAnimation instance =
        SkeletonAnimation.NewSkeletonAnimationGameObject(runtimeSkeletonDataAsset);
}
```

And each 1-4 ends up with these errors.

```
1.
Error reading skeleton JSON file for SkeletonData asset: {my .skel.bytes file}
Attempted to read past the end of the stream.
Failed to read 'mymotion.skel.bytes'. It is likely not a binary Spine SkeletonData file.

2.
Error reading skeleton JSON file for SkeletonData asset: {my .skel.bytes file}
Non-negative number required.
Failed to read 'mymotion.skel.bytes'. It is likely not a binary Spine SkeletonData file.

3.
Error reading skeleton JSON file for SkeletonData asset: {my .skel.bytes file}
name cannot be null.

4.
Error reading skeleton JSON file for SkeletonData asset: {my .skel.bytes file}
Attempted to read past the end of the stream.
Failed to read 'mymotion.skel.bytes'. It is likely not a binary Spine SkeletonData file.
```

Environment
- Unity 2021.3.16
- Spine 4
- Windows 10

Can somebody help? I'm struggling this problem these days : (

**Comment by HaraldCsaszar** [comment]
@zawazawagh In general, please post questions on the [forum](https://esotericsoftware.com/forum/), not as a github ticket.

See here on how to create a `TextAsset` from a binary file:
https://forum.unity.com/threads/how-create-a-textasset-from-external-binary-file.1112608/

**Comment by zawazawagh** [comment]
Thank you for your reply. It seems that I have to put spine-unity as a local package, but you know, customizing 3rd party library is burdensome. Hmm. It would be nice if I can create SkeletonDataAsset with byte array directly.
Anyway, thanks for the information.

**Comment by HaraldCsaszar** [comment]
> It seems that I have to put spine-unity as a local package, but you know, customizing 3rd party library is burdensome. 

You should not need to modify the spine-unity runtime for that, if that's what you meant. You need to create a `TextAsset` with the respective binary content outside the spine-unity runtime.

>  It would be nice if I can create SkeletonDataAsset with byte array directly.

Unfortuantely that would not fit the existing design well, as `SkeletonDataAsset` is currently keeping a reference to the `TextAsset` as an attribute in order to not only read once but reload data from the same asset if requested.
