### ISSUE TITLE
[godot] Importing skeleton data crashes the engine

### ISSUE THREAD

**Issue by Dodoveloper** [EsotericSoftware/spine-runtimes#2274]
Hello!

I am getting an engine crash when using a particular `.skel` file with a `SpineSprite` node.
```
/home/runner/work/spine-runtimes/spine-runtimes/spine-godot/spine_godot/spine-cpp/include/spine/Vector.h:162: T& spine::Vector<T>::operator[](size_t) [with T = spine::Skin*; size_t = long unsigned int]: Assertion `inIndex < _size' failed
```
Version: `godot-4.1-3.5.1-stable`
Platform: Linux amd64
Minimal reproduction project: [SpineTest.zip](https://github.com/EsotericSoftware/spine-runtimes/files/11212158/SpineTest.zip)

Basically what I do is:
1. Create a 2D scene with a `SpineSprite`
2. Add a new `SpineSkeletonDataResource`
3. Add the `.skel` file under the `skeleton_file_res` property
4. Godot crashes with the error above

By the way, maybe it is irrelevant, but the absolute path in the error does not exist on my drive.

**Comment by lluancarlo** [comment]
I started to have the same issue here.
I created a project on spine to test it. I've noticed that the `.skel` file doesn't have the `skins` property. However, the `.spine-json` does have it. I've exported the animation in both `.skel` and `.spine-json` with these configs:

![Screenshot 2023-04-13 at 15 08 37](https://user-images.githubusercontent.com/32052204/231780368-14f6bb51-f03f-4d24-afb7-f348fbd53b17.png)
![Screenshot 2023-04-13 at 15 08 48](https://user-images.githubusercontent.com/32052204/231780354-bc6b0968-0e00-4e78-b0c9-62d7a47a152a.png)

So when I import the `.skel` file to the engine, the error that @Dodoveloper reported happens. On file `SkeletonBinary.cpp` in the  `readAnimation()` function we have this line. It's trying to get the position 0 of the array `_skins`, which is size 0. I've checked too the function `readSkeletonData()` where it's supossed to import the `skins`, but the `readVarint()` returns 0 and it does not iterate to fill this array.

![image](https://user-images.githubusercontent.com/32052204/231766403-57ca0ebe-854c-48bd-bdab-66cfe405ac33.png)

In the other hand, if I do the same for `.spine-json`, but it does have something, even though there's no `skins` on spine.

![Screenshot 2023-04-13 at 15 04 28](https://user-images.githubusercontent.com/32052204/231780491-6500a45e-020f-48b5-b011-33b9fff39012.png)

Based on that, is Spine exporting the `.skel` file wrongly? I let the question to the experienced guys 'cause I'm new on it. 

Spine version: 4.1.20
[boxtest.zip](https://github.com/EsotericSoftware/spine-runtimes/files/11223010/boxtest.zip)

**Comment by badlogic** [comment]
Thanks for the report and analysis! It looks like the binary format loader has a bug. I'll investigate and provide a fix asap.

**Comment by badlogic** [comment]
The crash happens because loading the default skin of the skeleton fails. The atlas does not contain the region `box_00`. Instead, the atlas has regions all with the same name `box`:

```
boxtest.webp
size:332,800
filter:Linear,Linear
box
index:0
bounds:2,580,216,216
offsets:68,68,352,352
box
index:1
bounds:2,388,190,190
offsets:81,81,352,352
box
index:2
bounds:2,194,166,166
offsets:93,93,352,352
box
index:3
bounds:2,2,140,140
offsets:106,106,352,352
box
index:4
bounds:220,686,110,110
offsets:121,121,352,352
box
index:5
bounds:220,492,86,86
offsets:133,133,352,352
```

The reason this happens is because you have the `Indices` checkbox checked in the texture packer settings. If you uncheck that option, the regions will get their full names and can be resolved by the skeleton binary loader.

I'm not actually wondering why that option exists in the texture packer. Will investigate :)

**Comment by Dodoveloper** [comment]
This does fix it indeed. 
Thanks for the assistance!
