### ISSUE TITLE
How can I use spine-cpp-unit-tests

### ISSUE THREAD

**Issue by kouxiongfei** [EsotericSoftware/spine-runtimes#2280]
Good Day,
When I make build in spine-cpp-unit-tests, it not work.
Thanks
![企业微信20230428-145112](https://user-images.githubusercontent.com/33421397/235080550-ccac5b72-eb01-4694-b5c0-ef94a3aef4e3.png)

This is how I do it
1. cd spine-cpp && mkdir build && cd build && cmake .. && sudo make install all
2. cd ../spine-cpp-unit-tests/
3. mkdir build && cd build && cmake .. && make

**Comment by badlogic** [comment]
Please pull the latest commit on the 4.1 branch. Then, in the `spine-runtimes` directory:

```bash
mkdir build && cd build && cmake .. && make
cd spine-cpp/spine-cpp-unit-tests
./spine_cpp_unit_test
```
