### ISSUE TITLE
[c] Integer values in events broken with binary loader

### ISSUE THREAD

**Issue by jabuwu** [EsotericSoftware/spine-runtimes#2281]
The "integer" value associated with events doesn't seem to be loading correctly with the binary loader. It should be easily reproducible by creating a new spine project with an event that has a non-zero integer value, but I can provide one if it's somehow not reproducible (using Spine 4.1.20 Pro). If I use a value of `1` it becomes `-2`. A value of `10` becomes `-11`.

The JSON loader works as expected.

Thanks for your time as always!

**Comment by badlogic** [comment]
Thanks for reporting, this is now fixed in the 4.1 and 4.2-beta branches!
