### ISSUE TITLE
Weird renderer when atlas page size differ with actual image size on spine-ts.

### ISSUE THREAD

**Issue by firodj** [EsotericSoftware/spine-runtimes#2287]
Try resize the PNG image, eg. 1.5x or 2x then reload on the example.

I was experimented using spine-canvas, and found there is issue on these line:

https://github.com/EsotericSoftware/spine-runtimes/blob/fc05ecf9316a65499f1c6b9aa4f907f1a30e5d46/spine-ts/spine-canvas/src/SkeletonRenderer.ts#L102

for source width and hight should be:

```js
ctx.drawImage(image, image.width * region.u, image.height * region.v, image.width * (region.u2 - region.u), image.height * (region.v2 - region.v), 0, 0, w, h); 
```

Also found issue when using spine-webgl. Please check also on other implementation.

**Comment by badlogic** [comment]
You mean you manually resized the .png and didn't use the scale setting in Spine's texture packer settings?

**Comment by firodj** [comment]
correct.

**Comment by badlogic** [comment]
That's not a bug. The region width/height depends on the image size. If you manually resize a PNG then the region width/height won't match, resulting in an error. Please use the texture packer to create multiple scaled atlases.
