### ISSUE TITLE
[unity] NullReferenceException upon SkeletonGraphic drag&drop instantiation

### ISSUE THREAD

**Issue by npicouet** [EsotericSoftware/spine-runtimes#2292]
Hello! We have an animation that works great when dragging it in as a normal SkeletonAnimation.
When we try to add it to our canvas UI, it gives us a null error instead?

Spine: 4.1.21
Spine Runtime: 4.1.10
Unity: 2021.3.17f1

I've attached the animation in question:
[instruct-banner-spine-v1.zip](https://github.com/EsotericSoftware/spine-runtimes/files/11479104/instruct-banner-spine-v1.zip)

`NullReferenceException: Object reference not set to an instance of an object
Spine.Unity.MeshGenerator.GenerateSingleSubmeshInstruction (Spine.Unity.SkeletonRendererInstruction instructionOutput, Spine.Skeleton skeleton, UnityEngine.Material material) (at Library/PackageCache/com.esotericsoftware.spine.spine-unity@149aad2fa0/Runtime/spine-unity/Mesh Generation/MeshGenerator.cs:153)
Spine.Unity.SkeletonGraphic.PrepareInstructionsAndRenderers (System.Boolean isInRebuild) (at Library/PackageCache/com.esotericsoftware.spine.spine-unity@149aad2fa0/Runtime/spine-unity/Components/SkeletonGraphic.cs:701)
Spine.Unity.SkeletonGraphic.Rebuild (UnityEngine.UI.CanvasUpdate update) (at Library/PackageCache/com.esotericsoftware.spine.spine-unity@149aad2fa0/Runtime/spine-unity/Components/SkeletonGraphic.cs:313)
Spine.Unity.SkeletonGraphic.Awake () (at Library/PackageCache/com.esotericsoftware.spine.spine-unity@149aad2fa0/Runtime/spine-unity/Components/SkeletonGraphic.cs:296)
UnityEditor.ObjectFactory:CreateGameObject(String, Type[])
Spine.Unity.Editor.EditorInstantiation:NewGameObject(String, Boolean, Type[]) (at Library/PackageCache/com.esotericsoftware.spine.spine-unity@149aad2fa0/Editor/spine-unity/Editor/Utility/AssetUtility.cs:1371)
Spine.Unity.Editor.SkeletonGraphicInspector:NewSkeletonGraphicGameObject(String) (at Library/PackageCache/com.esotericsoftware.spine.spine-unity@149aad2fa0/Editor/spine-unity/Editor/Components/SkeletonGraphicInspector.cs:538)
Spine.Unity.Editor.SkeletonGraphicInspector:InstantiateSkeletonGraphic(SkeletonDataAsset, Skin) (at Library/PackageCache/com.esotericsoftware.spine.spine-unity@149aad2fa0/Editor/spine-unity/Editor/Components/SkeletonGraphicInspector.cs:510)
Spine.Unity.Editor.SkeletonGraphicInspector:SpawnSkeletonGraphicFromDrop(SkeletonDataAsset) (at Library/PackageCache/com.esotericsoftware.spine.spine-unity@149aad2fa0/Editor/spine-unity/Editor/Components/SkeletonGraphicInspector.cs:501)
Spine.Unity.Editor.DragAndDropInstantiation:HandleSkeletonComponentDrop(Object) (at Library/PackageCache/com.esotericsoftware.spine.spine-unity@149aad2fa0/Editor/spine-unity/Editor/Utility/Instantiation.cs:150)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32) (at /Users/bokken/build/output/unity/unity/Editor/Mono/GUI/GenericMenu.cs:125)
`

**Comment by HaraldCsaszar** [comment]
@npicouet Sorry for the troubles, and thanks very much for reporting! We have just fixed this issue, new 4.1 and 4.2-beta spine-unity packages are available for download.
https://esotericsoftware.com/spine-unity-download
