### ISSUE TITLE
[flutter] Rendering issues on iOS with Dart3/Impeller

### ISSUE THREAD

**Issue by sioomy** [EsotericSoftware/spine-runtimes#2293]
can not see the animation in dart3 ios,android is ok.
but it is ok in dart2.19,both android an ios

**Comment by badlogic** [comment]
Are you using the new Impaler renderer?

**Comment by badlogic** [comment]
Confirmed with Flutter 3.10.1 and Impeller in the iOS simulator.

**Comment by badlogic** [comment]
This is a bug in Impeller. See https://github.com/flutter/flutter/issues/127486

You can run things without Impeller as documented here:
https://docs.flutter.dev/perf/impeller#ios

**Comment by badlogic** [comment]
Flutter branch `flutter-3.10.candidate.1` now has a fix for this. I've also improved performance where possible with the current API, though it is not ideal. Region and mesh attachments with vertex colors != `0xffffffff` have to take a slow path through the Impeller renderer using an offscreen surface.

The engine team has acknowledged the need for either more fast paths, or shaders with UV support. Once either of those lands, we can improve the renderer again.
