### ISSUE TITLE
[crash] android

### ISSUE THREAD

**Issue by CodeEagle** [EsotericSoftware/spine-runtimes#2297]
[crashlog.txt](https://github.com/EsotericSoftware/spine-runtimes/files/11607519/crashlog.txt)

[crash_log_10__2023_0524_134802.zip](https://github.com/EsotericSoftware/spine-runtimes/files/11609206/crash_log_10__2023_0524_134802.zip)

crash log

**Comment by badlogic** [comment]
There's absolutely no information in the crashlog that is in any way helpful, not even a stack trace for the thread that crashed. The only thing I found is that you are using Flutter.

Please submit a new issue with a reproduction project so I can reproduce the crash on my end.
