### ISSUE TITLE
[flutter] RuntimeError: Aborted

### ISSUE THREAD

**Issue by akzhol0921** [EsotericSoftware/spine-runtimes#2298]
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/43620746/ac4a3c86-daf3-4e6f-9b25-58743f3ede66)
after i install the newest flutter_spine package i have this problem while running.  my flutter version is 3.10.1
i ignored it and try to use official sample called spineboy, the animation is working properly.
after i try to use mine animation it gives me this error
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/43620746/fc2e9237-50c4-4455-bff3-4585ee4c843b)

**Comment by badlogic** [comment]
You've tried to set an animation which does not exist in the skeleton. Ensure the animation name you specify exists.
