### ISSUE TITLE
[ue] Compilation error on Android with UE 5.2

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2301]
See https://esotericsoftware.com/forum/d/24315-ue-52-build-error

**Comment by antidamage** [comment]
I'm using UE 5.2 and ndk r21b at the moment. It was suggested that I might be on the wrong ndk version, however UE doesn't see any ndk _other than_ r21b, but states it wants r25b instead.

Any help with this would be appreciated.

**Comment by badlogic** [comment]
This should be fixed now and also work with r21b! Thanks for reporting.

**Comment by antidamage** [comment]
I did manage to finally upgrade to:

Packaging (Android (ETC2)): NDK toolchain: r25b, NDK version: 250200, ClangVersion: 14.0.6
Packaging (Android (ETC2)): Compiling Native 64-bit code with NDK API 'android-33'

The new commit works good with this setup, thank you :)

**Comment by animacio** [comment]
Confirming that "const char *toChar = TCHAR_TO_UTF8(*data.To); ... Error: temporary whose address is used as value of local variable 'fromChar' will be destroyed at the end of the full-expression [-Werror,-Wdangling] " 
was affecting iOS Packaging also (UE5.2). The new update resolved the issue. 
Thanks badlogic!

**Comment by badlogic** [comment]
Sorry I didn't catch it. I usually test with MSVC not Clang.

**Comment by animacio** [comment]
Hi Mario, 
One more question regarding compiling with Xcode (Visual Studio /  PC works). Getting this error and failure on MacOS, Please advise:

"Showing All Messages
[6/20] Compile [Apple] Module.SpinePlugin.3_of_3.cpp
In file included from /Users/xxx/Perforce/clones/Wormwood/Animacio/Unreal/Wormwood5.2/Plugins/SpinePlugin/Intermediate/Build/Mac/arm64/UnrealEditor/Development/SpinePlugin/Module.SpinePlugin.3_of_3.cpp:26:
Vector<Polygon *> &SkeletonBounds::getPolygons() {
       ^
/Users/xxx/Perforce/clones/Wormwood/Animacio/Unreal/Wormwood5.2/Plugins/SpinePlugin/Source/SpinePlugin/Public/spine-cpp/src/spine/SkeletonBounds.cpp:193:8: reference to 'Polygon' is ambiguous
typedef MacPolygon                      Polygon;
                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/Headers/Quickdraw.h:267:41: candidate found by name lookup is 'Polygon'
        class Polygon : public SpineObject {
              ^
In file included from /Users/xxx/Perforce/clones/Wormwood/Animacio/Unreal/Wormwood5.2/Plugins/SpinePlugin/Intermediate/Build/Mac/arm64/UnrealEditor/Development/SpinePlugin/Module.SpinePlugin.3_of_3.cpp:26:
/Users/xxx/Perforce/clones/Wormwood/Animacio/Unreal/Wormwood5.2/Plugins/SpinePlugin/Source/SpinePlugin/Public/spine-cpp/include/spine/SkeletonBounds.h:110:8: candidate found by name lookup is 'spine::Polygon'
Vector<Polygon *> &SkeletonBounds::getPolygons() {
       ^
/Users/xxx/Perforce/clones/Wormwood/Animacio/Unreal/Wormwood5.2/Plugins/SpinePlugin/Source/SpinePlugin/Public/spine-cpp/src/spine/SkeletonBounds.cpp:193:8: reference to 'Polygon' is ambiguous
typedef MacPolygon                      Polygon;
                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/Headers/Quickdraw.h:267:41: candidate found by name lookup is 'Polygon'
        class Polygon : public SpineObject {
              ^
2 errors generated."

Thank you,
Ivan

**Comment by animacio** [comment]
In SkeletonBounds:
Vector<Polygon *> &SkeletonBounds::getPolygons() {
	return _polygons;
}
thrown error is: reference to 'Polygon' is ambiguous

**Comment by animacio** [comment]
Seem to have resolved the problem by modifying SkeletonBounds:
Vector<spine::Polygon *> &SkeletonBounds::getPolygons() {
	return _polygons;
}

Is this a correct approach? Thanks Ivan
