### ISSUE TITLE
[Godot] SpineEventData class missing audio_path 

### ISSUE THREAD

**Issue by jordo** [EsotericSoftware/spine-runtimes#2302]
Spine runtime for godot is missing `getAudioPath` and `SetAudioPath` in the `SpineEventData` class.  This is available in spine-cpp, other runtimes, and is supported in the spine editor.

<img width="1377" alt="Screen Shot 2023-06-06 at 5 56 12 AM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/0106ba2b-ca92-43a7-9094-ae7e5dfc78e0">

<img width="457" alt="Screen Shot 2023-06-06 at 5 57 01 AM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/ee6169db-18c7-4f92-9cb9-58d8bc088dbd">

**Comment by badlogic** [comment]
Thanks for the PR!
