### ISSUE TITLE
[c] missing implementation for spSkeletonDrawable_destroy() in SDL compatibility layer (branch 4.1)

### ISSUE THREAD

**Issue by ubalot** [EsotericSoftware/spine-runtimes#2304]
In file `spine-sdl/src/spine-sdl-c.h` there's a function declaration
```c
SP_API void spSkeletonDrawable_destroy(spSkeletonDrawable *self);
```
but I can't find the implementation of such function in file `spine-sdl/src/spine-sdl-c.c`.

That function has no implementation because it was useless and the memory pointed by `spSkeletonDrawable*` get free somewhere else in code? or it is just a oversight and implementation should be added?

**Comment by badlogic** [comment]
Apologies, the declaration in the header was wrong. It should be `spSkeletonDrawable_dispose`. Fixed in the 4.1 branch.
