### ISSUE TITLE
Would it be possible to add the Axmol engine runtimes to this repository

### ISSUE THREAD

**Issue by rh101** [EsotericSoftware/spine-runtimes#2308]
The [Axmol](https://github.com/axmolengine/axmol) fork of Cocos2d-x v4 has diverged quite significantly from Cocos2d-x, and while multiple versions of the Spine runtimes for it are being maintained [here](https://github.com/axmolengine/spine-axmol), is there any chance that those runtimes can be added to this repository?

Cocos2d-x is no longer maintained, as the focus has shifted to Cocos Creator, and the last commit was in December 2021.  My own projects have been moved to Axmol permanently, and others have released games using it.  So, it would be great if the Axmol Spine runtimes become part of this repository, as the Axmol game engine is being actively used and maintained.

**Comment by lukeeingram** [comment]
Hello, thank you for the suggestion. We don't add Spine Runtimes that we don't develop/maintain to this Github page; rather, we add links to 3rd party repositories from our main site. You can see [see here for more information](http://en.esotericsoftware.com/spine-runtimes), and we'll be happy to add Axmol.
