### ISSUE TITLE
[unity] URP shaders compile error on Unity 2023.1

### ISSUE THREAD

**Issue by DavidCauchiDev** [EsotericSoftware/spine-runtimes#2311]
Hi I was wondering if there is an ETA on support for unity 2023.1? There are a few shader errors that I am getting, but not sure on what the best fix would be.

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/21057342/0caa17dc-df0f-43c2-ad4d-5bc824cdc2bb)

**Comment by HaraldCsaszar** [comment]
@DaveTheGameDev Thanks for reporting the compile errors with Unity 2023.1! We've just pushed a fix for this issue. Please do let us know if this resolves all compile errors on your end, and also if you encounter any other issues with Unity 2023.1 in general.

A new URP Shaders 4.1 UPM zip package is available for download here as usual:
https://esotericsoftware.com/spine-unity-download

**Comment by HaraldCsaszar** [comment]
@DaveTheGameDev Regarding official compatibility with Unity 2023.1: We are always open for any bug reports regarding Unity 2023.1, or any non-beta Unity version in general. We will perform some more testing and await some potential late bug reports (as always when newer Unity versions are coming out of beta) until we declare official compatibility.

**Comment by DavidCauchiDev** [comment]
Thanks so much!
