### ISSUE TITLE
[phaser] SpineGameObject.setDepth() can cause unexpected sideeffects

### ISSUE THREAD

**Issue by saintflow47** [EsotericSoftware/spine-runtimes#2317]
Hi there, i tried to isolate the root cause of the issue but sadly was not able to. The difference between normal behaviour and what you can see in the attachment is one single call:

`this.cannonBase.setDepth(5);`

which is a SpineGameObject added like 
`this.scene.add.spine(this.cannonPosition.x+this.x, this.cannonPosition.y+this.y, 'cannon-data', 'cannon-atlas')`

If I make the setDepth call, its broken, if i dont make the call, its working. However, there is more:
If i call setDepth(1), everything is working
If I call setDepth(3), just the cannon disappears

I do not use any containers for the spine objects.
https://github.com/EsotericSoftware/spine-runtimes/assets/32780344/0b44723f-177a-4199-b0cb-1cb1f312c0ba

**Comment by badlogic** [comment]
@saintflow47 is there any chance I could get one of the problematic skeleton exports + atlas? I can't reproduce this with our own assets.

**Comment by saintflow47** [comment]
> @saintflow47 is there any chance I could get one of the problematic skeleton exports + atlas? I can't reproduce this with our own assets.

Yes of course here you are. i included the cannonbase and some of the bubbles. i tried reproducing it within the new phaser spine examples but could not manage to reproduce it either 
[spine.zip](https://github.com/EsotericSoftware/spine-runtimes/files/12049797/spine.zip)

**Comment by badlogic** [comment]
I'm afraid I can't repro it with your files either. There must be something in your full project that's causing this. Since I don't have access to it, I'm afraid I have to ask you to boil it down to something that might help us identify the cause. I can't see how the code in the latest spine-phaser version could be impacted by setDepth(). Did you ensure to use the latest spine-phaser release version 4.1.36?

**Comment by saintflow47** [comment]
Hey Mario, I understand. I did make sure to use the latest version! Its not the outcome I hoped for and I completely understand where you are coming from but for me, i will cut my losses and roll back to the phaser spine version. thanks for your time!
