### ISSUE TITLE
Free CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by aWilson41** [EsotericSoftware/spine-runtimes#2320]
https://github.com/EsotericSoftware/spine-runtimes/blob/5308ddb04b9915cfceb7d3f531300ef52d12533e/CMakeLists.txt#L4

I'd recommend doing this instead here:

```
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR} CACHE PATH "Install location" FORCE)
endif()
```

This will give you binary directory by default, which is what I think you meant by "./" (local directory). But still allows users to supply their own CMAKE_INSTALL_PREFIX install path.

The particular use case is when spine is used as a library in anothers build. I'd expect to direct all my dependencies to install to the same directory. But this causes spine to always install to its local directory which is not the local directory of the parent build.

**Comment by badlogic** [comment]
That's a great suggestion. The CMake build needs an overhaul eventually anyways. It's very old and not very great.

I've pushed this change to the 4.1 and 4.2-beta branches.
