### ISSUE TITLE
[flutter] Uncaught TypeError: Cannot set properties of null (setting 'exports')

### ISSUE THREAD

**Issue by akzhol0921** [EsotericSoftware/spine-runtimes#2321]
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/43620746/4b064f5d-76e8-475a-a53c-407d0e0fc900)
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/43620746/795cf2ef-4c41-4bfe-9c15-acf473d79d61)
having this issue when start debugging, using newest version of spine_flutter.
here is main function
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/43620746/22eb6303-0c16-4d87-8e34-3f9bdbe4092f)

**Comment by badlogic** [comment]
Weirdly enough, I do get this error as well, however, I can still run and debug our example project:

<img width="1200" alt="Screenshot 2023-07-18 at 14 17 58" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/38c75e6b-f5e6-4f7d-9bfd-ff278e2a48b7">

I'll investigate.

**Comment by badlogic** [comment]
Thanks for the report, this is now fixed in spine_flutter 4.1.4 and 4.2.14.
