### ISSUE TITLE
[flutter] Upgrade http plugin to 1.1.0 

### ISSUE THREAD

**Issue by thanhnvpk01168** [EsotericSoftware/spine-runtimes#2327]
<img width="1848" alt="Screenshot 2023-07-28 at 18 08 03" src="https://github.com/EsotericSoftware/spine-runtimes/assets/58645779/7d2639a9-5841-4bfb-928b-fac215a7c687">

**Comment by badlogic** [comment]
This is now fixed in both the 4.1 and 4.2-beta branches. I've published new versions 4.1.5 and 4.2.15 with the updated dependencies.
