### ISSUE TITLE
[ue] 4.0.64 Cannot compile on UE 5.2.1

### ISSUE THREAD

**Issue by enokinoki1** [EsotericSoftware/spine-runtimes#2328]
I tried Spine 4.1 before, and was able to run it properly in UE 5.2.1, but when I tried to use Spine 4.0.64, it won't compile.
Here is the log from Visual Studio.
[LOG.txt](https://github.com/EsotericSoftware/spine-runtimes/files/12198623/LOG.txt)

Any solution? or should I try another version of Unreal?

**Comment by badlogic** [comment]
Very weird it would complain about SpineWidget.h, as it's pretty much the same in 4.0 and 4.1. I'll have a look, thanks for reporting!

**Comment by badlogic** [comment]
Fixed in the 4.0 branch!
