### ISSUE TITLE
[godot] Improve performance

### ISSUE THREAD

**Issue by jordo** [EsotericSoftware/spine-runtimes#2331]
We are generally finding there are a few hot spots in the spine godot runtime.  For the most part, spine-cpp is quite performant but there are a few things in the godot layer that we are hitting walls in.  I'll post some profiling runs form a CPU sampler, (both in chrome and xcode), and highlight the spots we are seeing.   I'll also be working on this today and submit a PR or two to address:

Profile from chrome.  Our scene tree `idle` takes 7.19ms, and of that 6.02ms come from spine `update_skeleton`.
<img width="1506" alt="Screen Shot 2023-08-03 at 11 20 03 AM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/296fec76-35db-4b2d-b849-085bd59b964b">

From that, on close inspection, a lot of time are spent here:  Mainly allocation and releasing temporary `SpineBone`s, `SpineSlot`s and also `StringName`s.   

<img width="1096" alt="Screen Shot 2023-08-03 at 11 21 51 AM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/450d0778-187e-4d6e-9cdf-f2bf25b19aa8">

We've encountered this a lot, and have improved a whole bunch of our godot cpp code by using static StringName's instead.  But Basically any godot API that that takes a a `const StringName&` argument ex:  `emit_signal`, you pay a huge cost by calling the function with a `const char*`.  For example:

```cpp
emit_signal("animation_started")
```   
Is actually quite costly becuase under the hood godot ends up constructing a `StringName` from the `const char*` overloaded constructor, and this ends up allocating memory and acquiring a global lock/mutex.  (Annoying I know).

At any rate, godot master and we ourselves even though it isn't backported to `3.x` use a macro `SNAME` which statically constructs a `StringName` from a `const char*` into static storage for the lifetime of the application.  This keeps the StringName around in the global map indefinitely which elimintes the construction cost of these everywhere.

`SNAME` is defined as:  
```cpp 
#define SNAME(m_arg) ([]() -> const StringName & { static StringName sname = _scs_create(m_arg); return sname; })()
```
And you can use as a replacement like:

```cpp
emit_signal(SNAME("animation_started"))
```

Line 163 seems to be quite quite heavy in our profiles...  `slot->get_bone()` end up allocating (temporarily) quite heavy godot objects, and it looks like this is called often every frame.  
<img width="810" alt="Screen Shot 2023-08-03 at 11 31 30 AM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/92ddafbc-9298-476a-ad4f-b336dce39094">

<img width="504" alt="Screen Shot 2023-08-03 at 11 34 32 AM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/778a21c0-a59b-4434-b223-e6d68ad35552">

Anyways, looks like a couple of these hotspots could be worked around with either some local caching here or something:
<img width="739" alt="Screen Shot 2023-08-03 at 11 47 58 AM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/290291c2-8e37-4081-b2fc-57ab1499f4c6">

Will try and make a couple PR's for these in the next couple days...

**Comment by jordo** [comment]
CPU sampler profile from Xcode/Instruments showing same hotspots.  `SceneTree::idle` roughly at 57% cpu, `SpineSprite::_update_skeleton(float)` at roughly 47% of our CPU load.  

<img width="1231" alt="Screen Shot 2023-08-03 at 11 53 14 AM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/86b32977-02e9-4cee-a1bd-f943bdd80bc5">

**Comment by jordo** [comment]
Almost everything boiling down to here for us:

<img width="1194" alt="Screen Shot 2023-08-03 at 12 32 18 PM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/d1d8ebbe-77da-4869-9007-7c230299dfca">

So a couple questions I suppose regarding a couple these functions.  I'm not too too familiar with the spine-cpp runtime, but  can we cache these references in a map[string->Ref](for SpineSkeleton):
`SpineSkeleton::find_slot`

And for  `SpineSlot::get_data`  and `SpineSlot::get_bone` can we store the reference returned by these funcs?

I'll try and do those, as I _think_ it is correct to store these references locally...  AFAICT the skeleton setup is kinda static once it's loaded.

**Comment by jordo** [comment]
```
Ref<SpineBone> SpineSkeleton::find_bone(const String &name) {
	SPINE_CHECK(skeleton, nullptr)
	if (EMPTY(name)) return nullptr;
	auto bone = skeleton->findBone(SPINE_STRING(name));
	if (!bone) return nullptr;
	Ref<SpineBone> bone_ref(memnew(SpineBone));
	bone_ref->set_spine_object(sprite, bone);
	return bone_ref;
}
```

Also, in above, maybe we could have the `SPINE_STRING` macro expand to take the additional `owns` argument.  And for any place `SPINE_STRING` is used as a stack temporary, we could construct with the ownership as true which will eliminate an alloc and a memcpy:
<img width="1183" alt="Screen Shot 2023-08-03 at 12 48 41 PM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/1bad5259-8083-4645-b6cf-a8d0d7afc82b">

<img width="1470" alt="Screen Shot 2023-08-03 at 12 51 03 PM" src="https://github.com/EsotericSoftware/spine-runtimes/assets/323868/5fa47716-6022-48a6-a088-a7dd78261b30">

**Comment by badlogic** [comment]
Commented on the PR. It's crazy that the temporary object allocation is that heavy and outdoes the actual computations the runtime has to do. Thanks for digging into this. I don't have a scene with heavy `SpineSlotNode` usage where this would become more visible in terms of performance.

Caching should be fine, as noted in my PR review. Let's continue the discussion there.
