### ISSUE TITLE
[Phaser] plugin object name conflict with existing plugin

### ISSUE THREAD

**Issue by spayton** [EsotericSoftware/spine-runtimes#2333]
This is more of a suggestion than notification of a problem.

This new offical spine plugin for the Phaser3 framework is great and a highly welcome addition.  In use I have found one aspect of it that could be more flexible, that would have multiple benefits.

This is the name of the spine object type, currently it is 'spine' the same as Phaser's own spine plugins.  This is the property name that is used to generate the functionality such as

```js
scene.add.spine
```

This constant is set in src/keys.ts

```js
export const SPINE_GAME_OBJECT_TYPE = "spine";
```

In practice, this can cause confusion because this has been used up till now solely by Phaser's own spine plugins which have a different API.  All of Phaser's current spine users will be used to using that game object type with its own API.

I'm suggesting that this game object type can be changed from the default 'spine' by the user.  Being able to do this would have the following benefits:

- there would be no confusion over which spine object was being created, thus no confusion over which API is being used eg.
```js
scene.add.spine    // legacy plugin
scene.add.spinePhaser    // official plugin
```
- multiple spine plugins could be loaded and be operational, ie phasers own spine plugin could co-exist with the new official one. This is quite a benefit, it would allow:
  - easy project conversion to official plugin by tackling spine asset usage one at a time, rather than the 'all in' approach you would get by swapping to a different plugin and everyhthing being broken at the same time.
  - the ability to be able to use older spines with newer versioned ones, ie wouldn't have to update all spines to same version just to suit one plugin version

I'm only suggesting adding functionality.  The default behaviour would remain unchanged, and would suit Phaser users with no previous spine usage or spine baggage.

I can easily achieve this by editing the SPINE_GAME_OBJECT_TYPE string in the plugin src and rebuilding, but it seems such a useful addition that it should be available 'out-of-the-box'.

**Comment by badlogic** [comment]
It's an interesting idea, though I'm of the opinion that mixing plugins and versions is a very bad thing. It leads to version conflicts, confusion which asset files are compatible with what, etc. It is a one time thing to update, it's a continuous pain to keep multiple versions around. I'd not officially endorse this.

However, making it configurable is still sensible. The problem is: I don't know how. There's no mechanism to inject something into a plugin before it is registered, at least not as far as I can see. Any ideas?

**Comment by spayton** [comment]
Yeah, I can see why having multiple versions is undesirable and I agree that this shouldn't be the norm, but if it could be a "technically its possible but not supported" kind of way then that would be great.

It looks like the the plugin populates 'window.spine' once executed, in here user code could set a string or call a function that would be picked up by the plugin to override SPINE_GAME_OBJECT_TYPE.  The window of opportunity to do this is simply after the plugin load/parse/execute step but before the plugin can register the game object, which would be before Phaser is instantiated.

**Comment by badlogic** [comment]
This is possible now. Simply set `window.SPINE_GAME_OBJECT_TYPE` to whatever you want, and the game object factory function will take on that name.

See the `custom-spine-game-object.html` example.
