### ISSUE TITLE
[godot] Can't download editor & templates from the website

### ISSUE THREAD

**Issue by Kelin2025** [EsotericSoftware/spine-runtimes#2334]
Trying to download export templates [from here](http://en.esotericsoftware.com/spine-godot) but no luck

It seems that the action that uploads to s3 has crashed

<img width="936" alt="image" src="https://github.com/EsotericSoftware/spine-runtimes/assets/4208480/61302961-26af-4973-931c-4379f978244d">

<img width="844" alt="image" src="https://github.com/EsotericSoftware/spine-runtimes/assets/4208480/4729d8a1-9267-4ea2-bf04-89a9f034bcbb">

**Comment by badlogic** [comment]
Sorry, should be good now!
https://github.com/EsotericSoftware/spine-runtimes/actions/runs/5770883302
https://esotericsoftware.com/spine-godot

**Comment by Kelin2025** [comment]
Not quite, now "Export templates" link downloads windows editor instead of template
Templates themselves are accessible by s3 direct link tho
https://spine-godot.s3.eu-central-1.amazonaws.com/4.1/4.1.1-stable/spine-godot-templates-4.1-4.1.1-stable.tpz

**Comment by badlogic** [comment]
Apologies, I shouldn't work on deployment stuff at midnight on a Saturday...

Fixed!
