### ISSUE TITLE
[Phaser] missing iife typescript type definitions

### ISSUE THREAD

**Issue by PhaserEditor2D** [EsotericSoftware/spine-runtimes#2336]
Hi!

I can't find the `.d.ts` files for the iief build of the `spine-phaser` runtime. I see the type definitions for ES modules, but not for iief.

I was doing a bit of research about esbuild but I can't find a short path for generating the .d.ts files for iief.

Btw, I think the type definitions for iief are missing in the other spine-ts runtimes, too.

**Comment by badlogic** [comment]
The iief build is for folks who want to quickly get something up and running with vanilla JS. If you want types, you can just pull in the package via NPM.

**Comment by PhaserEditor2D** [comment]
Well... At least in the Phaser community a lot of guys code in vanilla javascript or typescript (without ES modules).

Types in NPM are valid if you are using only ES modules syntax.

In any case, I did a script for making the iief `.d.ts` files:

https://github.com/PhaserEditor2D/spine-phaser-iife-types/

Thanks

**Comment by badlogic** [comment]
Sorry, I wasn't aware. I'll see if we can generate and package the d.ts files.

**Comment by PhaserEditor2D** [comment]
Oh, great! Thanks!

**Comment by badlogic** [comment]
@PhaserEditor2D circling back on this. How does the development setup look with vanilla JS and the `.d.ts` files?

E.g. I create a new folder for my project, slap an `index.html` and `index.js` file in there. In the `index.html` I have `<script>` tags for Phaser and `spine-phaser` (iief version).

Then I open it in an editor/IDE, say VS Code. How do I tell the editor to use the `d.ts` file? I just don't see how this works without at least using NPM to pull in types into the local `node_modules`. At least I can't find docs for VS Code that describe a use case without using NPM but still getting typings.

**Comment by badlogic** [comment]
Accidentially closed the issue...

**Comment by PhaserEditor2D** [comment]
Hi!

> E.g. I create a new folder for my project, slap an index.html and index.js file in there. In the index.html I have <script> tags for Phaser and spine-phaser (iief version).

Yes. And is a typical case for tutorial creators, newbies, or online environments, like the Phaser examples.

> Then I open it in an editor/IDE, say VS Code. How do I tell the editor to use the d.ts file?

You copy the `d.ts` manually. Or you can pull it from NPM. The problem with the current `d.ts` files in NPM is they are created only for ES modules. If you pull the types from NPM, the `spine` global scope is not defined in the `d.ts` files.

Let's see an example.

This works:

```ts
import { Skin } from "@esotericsoftware/spine-phaser";
const skin = new Skin("custom");
```

In vanilla JS, without importing ES modules, it doesn't work:

```ts
const skin = new spine.Skin("custom");
```

The `spine` object (or namespace) is not defined in the `d.ts` files.

So the script I did removes all ES modules syntax (import/export), joins all `d.ts` files in a single file for runtime, and groups all definitions into a `spine` namespace. It is a temporal solution.

I'm not an expert in authoring libraries with typescript/javascript, but after reading a bit about esbuild, I think it is not the best option for it. In the esbuild documentation, I don't see any topic regarding authoring libraries. Actually, I think it doesn't generate any `d.ts` file at all.

I see in the building scripts of this project it generates the `d.ts` files with typescript and not esbuild:

```
"build:modules": "npx tsc -b -clean && npx tsc -b"
```

With esbuild it only outputs the `js` iife files. TypeScript is not a bundler. It cannot transform ES modules syntax into iife.


P.S. I'm Arian the author of Phaser Editor 2D which is a third-party tool, I'm not part of the Phaser team. Sometimes the name of the tool is confusing :)

**Comment by PhaserEditor2D** [comment]
>  At least I can't find docs for VS Code that describe a use case without using NPM but still getting typings.

I think by placing the d.ts files in the same source folder it works. Also, you can use the `typeRoots` parameter (https://www.typescriptlang.org/tsconfig/typeRoots.html) in a `jsconfig.json` or `tsconfig.json` file.

**Comment by badlogic** [comment]
Thanks for the info! Yes, esbuild doesn't build .d.ts types, it basically just throws away all TypeScript types. My plan is to use the TypeScript compiler to generate the d.ts files for the iief versions (`--declarations` flag).

**Comment by PhaserEditor2D** [comment]
You are welcome!

> My plan is to use the TypeScript compiler to generate the d.ts files for the iief versions (--declarations flag).

Hum... Good luck with that. I bet TypeScript cannot generate the iife types because it cannot transform ES modules into a single iife file. Maybe it is possible if you set esbuild to generate the iife file in TypeScript, let's say to `spine-phaser.ts`, then you compile it with TypeScript to the `js` and `d.ts` files. But I think esbuild can't do it. Well, let's see. Maybe I'm missing something. Thanks!

**Comment by PhaserEditor2D** [comment]
Hi.

In the Spine Discord server someone provide me a solution like this:

index.d.ts:

```
export * from "@esotericsoftware/spine-phaser";
export as namespace spine;
```

So I'm closing this issue. Thanks!

**Comment by badlogic** [comment]
Oh, where do you put that?

**Comment by PhaserEditor2D** [comment]
In the `dist/index.d.ts` file, if you add:

```
export as namespace spine;
```

It will export all the runtime classes in the `spine` namespace. I tested it and works.

Or the client of the spine-phaser runtime can import all classes from the spine modules and wrap them in a `spine` namespace.

After debating in the Discord forum with someone from Pixi, I think the second option is the best. In this way, you don't have to change anything in the runtimes.

I think the best is to have a single d.ts file for iife, so it is easy for clients to grab it. Or at least to separate the types from the source code. Let's say, a `@types/spine-phaser` module. But it wasn't a popular idea in the forum.

In any case, with the `export as namespace spine` "trick", the client of the spine-phaser runtime can get the type definitions of iife. Thanks for your attention!

**Comment by PhaserEditor2D** [comment]
Actually, reading the TypeScript Handbook, it says:

>> If your types are generated by your source code, publish the types with your source code

So, that's the standard, not creating a separate @types module. So no actions are required :)
