### ISSUE TITLE
使用cocos2d-objc时， 使用CCDirector加载spine，多个控制器同时加载问题

### ISSUE THREAD

**Issue by 675088349** [EsotericSoftware/spine-runtimes#2339]
在A控制器中
    CCDirector *director = [CCDirector sharedDirector];
    [self.view addSubview: director.view];
    [[CCDirector sharedDirector] replaceScene:[GoblinsExample scene]];
 CCDirector 是个单利， 当我需要同时在B控制器加载时， 该如何去处理？

**Comment by badlogic** [comment]
抱歉，这是一个 cocos2d-obj 问题，与 Spine 无关。 您可以在他们的支持论坛上询问吗？

I'm sorry, this is a cocos2d-obj question, and not really related to Spine. Could you please ask on their support forums?
