### ISSUE TITLE
[cocos2dx] what should I do that a cocos Node add to a spine instance and this node can betwwen boneA and boneB?

### ISSUE THREAD

**Issue by hahazoe** [EsotericSoftware/spine-runtimes#2340]

**Comment by badlogic** [comment]
Please have a look at this example:
https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-cocos2dx/example/Classes/SkeletonRendererSeparatorExample.cpp

**Comment by hahazoe** [comment]
Thank you ~ @badlogic
