### ISSUE TITLE
A suggestion for spine-ts: importing file with .js extension

### ISSUE THREAD

**Issue by qingwabote** [EsotericSoftware/spine-runtimes#2352]
I use spine-core npm package as native es6 module, but importing files without .js extension(e.g. export * from './Animation';) can not work directly on native es6 web brower. "export * from './Animation.js';" is better for es6.

**Comment by badlogic** [comment]
spine-core is written using TypeScript and transpiled to JS via esbuild. As far as I can see, there's no way for us to make non `.js` imports/exports work in that setup.

**Comment by qingwabote** [comment]
"no way for us to make non .js imports/exports"? but there is non .js imports/exports in project spine-core.
https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-ts/spine-core/src/Animation.ts
