### ISSUE TITLE
[Spine-ts WebGL] SkeletonBinary().readSkeletonData() not reading data from the variable

### ISSUE THREAD

**Issue by NapXDD** [EsotericSoftware/spine-runtimes#2354]
I'm looking at [this repo](https://github.com/LinXueyuanStdio/AnimPlayer/blob/master/index.html) to learn how to read the assets from multiple cysp file and then combined all of these file in one variable. I'm writing this with React + TypeScript in [this repo](https://github.com/NapXDD/princonnePlayer/blob/main/src/utils/animation/animation.ts) and all of the code was wrote in the utils/animation.ts file. After read all the cysp file and combined it to a variable call newBuff and put this variable to readSkeletonData() like this:
```
      const skeletonBinary = new SkeletonBinary(atlasLoader);
      skeletonBinary.scale = 1;
      const skeletonData = skeletonBinary.readSkeletonData(newBuff);
```
But when I console.log(skeletonData) the data is not there, just an empty Array:
![SharedScreenshot](https://github.com/EsotericSoftware/spine-runtimes/assets/85546667/6cf5ab07-456b-4e32-9810-6706dbca2f65)
Did I do anything wrong ? I'm new with the Spine Runtime and hope someone can help
P/s: sorry for the bad code of my repo

**Comment by badlogic** [comment]
It appears both projects you are linking to are trying to rip assets from Cygame property. I'm afraid we can't help with that.
