### ISSUE TITLE
[Phaser] Add existing SpineGameObject bug

### ISSUE THREAD

**Issue by PhaserEditor2D** [EsotericSoftware/spine-runtimes#2356]
Hi

I have an issue adding an existing spine game object to the scene. The issue happens if I add a spine object using the game object factory (`this.add.spine()`) and later I add an existing spine game object (`this.add.existing()`):

This works:

```js
this.add.spine(200, 400, "goblins", "goblins-atlas");
this.add.spine(500, 400, "goblins", "goblins-atlas");
```
![works](https://github.com/EsotericSoftware/spine-runtimes/assets/12187299/3a3c4af4-ff61-460d-8b6f-2c1c8f1529e9)

This doesn't work:

```js
this.add.spine(200, 400, "goblins", "goblins-atlas");
this.add.existing(new spine.SpineGameObject(this, this.spine, 500, 400, "goblins", "goblins-atlas"));
```

![bug](https://github.com/EsotericSoftware/spine-runtimes/assets/12187299/8a72168f-df10-4510-832c-7daa1eecdd8c)

I installed the current version of Phaser and the `spine-phaser` runtime from NPM.

Here I attach a demo project to reproduce the issue (you should `npm install` first).

It has 3 tests, `test3()` is the one with the issue.

I hope I'm missing something :(

Thanks
Arian

**Comment by badlogic** [comment]
@PhaserEditor2D the repro didn't get through I'm afraid. Can you try to re-upload it here or elsewhere?

**Comment by PhaserEditor2D** [comment]
Oh, I missed it! Here we go... Thanks @badlogic!

[spine-phaser-gameobject-issue.zip](https://github.com/EsotericSoftware/spine-runtimes/files/12517139/spine-phaser-gameobject-issue.zip)

**Comment by badlogic** [comment]
This appears to be a regression in Phaser 3.60.0. It works as expected in Phaser 3.55.2. I'm investigating.

**Comment by badlogic** [comment]
The `SpinePlugin.boot()` method is called twice in Phaser 3.60.0. This will create a second `webGLRenderer` internally. This makes no sense. Possibly a bug in Phaser?

**Comment by badlogic** [comment]
Fixed, thanks for reporting! Publishing new packages to NPM in a bit.

**Comment by PhaserEditor2D** [comment]
Amazing! Thanks!
