### ISSUE TITLE
[unity] Event values doesn't work

### ISSUE THREAD

**Issue by EmreBeratKR** [EsotericSoftware/spine-runtimes#2359]
- This code works as expected.
```cs
private void OnAnimationStateEvent(TrackEntry trackEntry, Event e)
{
    if (e.Data.Name == _combatDashEventName)
    {
        var distance = e.Float; // returns 1 as expected
        var direction = _player.GetDirection();

        OnCombatDash(direction, distance);
    }
}
```

- But, if I use e.Data instead the default values are returned
```cs
private void OnAnimationStateEvent(TrackEntry trackEntry, Event e)
{
    if (e.Data.Name == _combatDashEventName)
    {
        var distance = e.Data.Float; // returns 0, it should return 1
        var direction = _player.GetDirection();

        OnCombatDash(direction, distance);
    }
}
```

I think EventData class may not be updated sometimes?

- Unity 2021.3.5f1
- Spine 4.1.23

**Comment by badlogic** [comment]
`EventData` is never updated. It contains the "base" values as defined in the setup pose. This works as intended. The `Event` has the values that are calculated based on the currently queued animations.

**Comment by EmreBeratKR** [comment]
Even this behaviour is intended you should have add some warnings about it.

**Comment by HaraldCsaszar** [comment]
Please note that this is general design principle of the Spine runtimes, it applies to all shared setup pose data (ending with `Data`) vs instance data (never ending with `Data`).

http://esotericsoftware.com/spine-api-reference#EventData
http://esotericsoftware.com/spine-api-reference#Event

http://esotericsoftware.com/spine-api-reference#Class-diagram
"The instance data is created for each skeleton instance and stores the skeleton's pose and other state. The setup pose data is stateless and shared across skeleton instances. It contains the setup pose, attachments, and animations."

**Comment by EmreBeratKR** [comment]
Oh my bad, I got it right now. Thanks a lot for your help.
