### ISSUE TITLE
[Flutter] Use `FilterQuality.medium` instead of `FilterQuality.high`

### ISSUE THREAD

**Issue by spydon** [EsotericSoftware/spine-runtimes#2362]
Regardless of the names, `FilterQuality.medium` actually almost always gives a better rendering output than `FilterQuality.high`, except when you need to scale up a lot, which I don't think is the case here.

I think this is the only place that needs to be changed:
https://github.com/EsotericSoftware/spine-runtimes/blob/4.2-beta/spine-flutter/lib/spine_flutter.dart#L140

I could provide a PR, but seems like more effort to sign the CLA etc than someone internally just doing that one-liner.

**Comment by badlogic** [comment]
I'll happily add this manually. I wonder if we should make it configurable though. What do you think @spydon ?

**Comment by spydon** [comment]
Sounds like a good idea, that's what we did in Flame, but defaulting to `medium`. :)

**Comment by badlogic** [comment]
Fixed in the latest releases. You can configure it via Atlas.filterQuality. Default is now `medium`
