### ISSUE TITLE
[godot] Editor with C# supports fails to find .NET SDK on Windows

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2365]
See https://esotericsoftware.com/forum/d/24781-godot-c-failed-to-load-net-runtime

**Comment by badlogic** [comment]
Fixed in latest release. Fetch the new binaries from: http://en.esotericsoftware.com/spine-godot

**Comment by zhishu520** [comment]
hello, i try it , but didnt work.

**Comment by brogan89** [comment]
Hey not sure if related to this bug specifically, but I can't seem to get access to the `SpineSprite` class. When I debug I can see the node is of type `Godot.SpineSprite` but I can't cast to the type to access the methods. 

I've followed the [docs here](http://en.esotericsoftware.com/spine-godot#C%23-Project-Setup) but doesn't seem to work. Did I miss something or is there an update coming that solves it? 

Thanks

**Comment by badlogic** [comment]
Without more info it's hard to say what is going wrong.

Are you using an IDE? If so, which one? Can you show the contents of your project's root folder?

**Comment by brogan89** [comment]
Hey yeah, I'm using Rider. 
I'm not sure what else info to give. Let me know if you need anything else.

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/8637789/85894be9-ee36-4a46-b98f-bbc4ed8dd043)

**Comment by brogan89** [comment]
Hey just FYI, I updated to 4.1.2 and, copied the new .nupkg over and now its working 👍 
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/8637789/033e0a83-678a-4466-ac66-e56946a7ab97)

**Comment by badlogic** [comment]
Great! Sorry for the late reply, was out with the Rona.

**Comment by knightofiam** [comment]
For posterity, if anyone else experiences the same issue as @brogan89, when upgrading the spine-godot runtime (4.1.1 => 4.1.2 in this case), even after following the **C# Project Setup** [instructions](https://en.esotericsoftware.com/spine-godot#C%23-Project-Setup):

I was only able to fix it by deleting everything Godot-related in my local NuGet cache (i.e., `~/.nuget/packages/godot*` on macOS).

@badlogic May be worth updating those [instructions](https://en.esotericsoftware.com/spine-godot#C%23-Project-Setup) with a note about clearing the NuGet cache in case the Spine C# API is not found after copying over the updated package assemblies.

Hopefully some weary soul will stumble upon this solution in the middle of the night and get a few extra hours of sleep.

**Comment by Eudge91** [comment]
> I was only able to fix it by deleting everything Godot-related in my local NuGet cache (i.e., ~/.nuget/packages/godot* on macOS).

You are a star! Thx!

**Comment by c-schembri** [comment]
> For posterity, if anyone else experiences the same issue as [@brogan89](https://github.com/brogan89), when upgrading the spine-godot runtime (4.1.1 => 4.1.2 in this case), even after following the **C# Project Setup** [instructions](https://en.esotericsoftware.com/spine-godot#C%23-Project-Setup):
> 
> I was only able to fix it by deleting everything Godot-related in my local NuGet cache (i.e., `~/.nuget/packages/godot*` on macOS).
> 
> [@badlogic](https://github.com/badlogic) May be worth updating those [instructions](https://en.esotericsoftware.com/spine-godot#C%23-Project-Setup) with a note about clearing the NuGet cache in case the Spine C# API is not found after copying over the updated package assemblies.
> 
> Hopefully some weary soul will stumble upon this solution in the middle of the night and get a few extra hours of sleep.

You're a legend. I'm not sure why IDEs/NuGet doesn't automatically detect that the package contents are different despite having the same name.
