### ISSUE TITLE
[godot] Cannot download Godot from doc links

### ISSUE THREAD

**Issue by MXXXXXS** [EsotericSoftware/spine-runtimes#2367]
#2334 It seems the problem has occurred again

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/28096993/6a5dab2f-45a2-4a58-94d5-9d7b3bd72977)

**Comment by badlogic** [comment]
Can not reproduce, both export templates for 4.1.1 with and without C# support work.
<img width="353" alt="Screenshot 2023-09-19 at 14 02 25" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/91128811-b9a9-465c-945e-0eb671e30530">

https://spine-godot.s3.eu-central-1.amazonaws.com/4.1/4.1.1-stable/spine-godot-templates-4.1-4.1.1-stable.tpz

https://spine-godot.s3.eu-central-1.amazonaws.com/4.1/4.1.1-stable/spine-godot-templates-4.1-4.1.1-stable-mono.tpz

Maybe you hit the bucket while it was updated by the GitHub workflow.
