### ISSUE TITLE
[ts] How to destroy `SpineCanvas` or stop the `app.update` and `app.render`?

### ISSUE THREAD

**Issue by aaronlin0122** [EsotericSoftware/spine-runtimes#2370]
Should we add a condition to this function or give a [`requestId`](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame) to cancel the `requestAnimationFrame`?

https://github.com/EsotericSoftware/spine-runtimes/blob/b83ee23be8c0de65c66c3c1ff2ea50b6d0efbee2/spine-ts/spine-webgl/src/SpineCanvas.ts#L99-L104

**Comment by badlogic** [comment]
I just added a new method to `SpineCanvas` called `dispose()`. Call it to stop the rendering loop. You can also provide a `disposed()` callback function in the canvas' configuration.

**Comment by badlogic** [comment]
This is now on NPM, versions 4.1.43 and 4.2.23.
