### ISSUE TITLE
[Godot] Some textures in the atlas are not displayed when imported into Godot

### ISSUE THREAD

**Issue by MXXXXXS** [EsotericSoftware/spine-runtimes#2372]
Here is the [Godot4 project file](https://github.com/MXXXXXS/BugFeedback/raw/main/file/Godot4SpineTextureLoadBug.zip)

Godot version: v4.1.1.stable.custom_build.bd6af8e0e

![Spine_n1gZDK0t3W](https://github.com/EsotericSoftware/spine-runtimes/assets/28096993/f6847df5-db2c-4372-ad4c-883e3ffaafd1)

Godot downloaded from [spine-godot](https://en.esotericsoftware.com/spine-godot#Samples)

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/28096993/ff3bedd4-5943-4aec-add6-6fdd1a4911e7)

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/28096993/1c9f812d-da71-4843-bbe5-b774387fa96d)

**Comment by badlogic** [comment]
Please share the exported files with us.

**Comment by MXXXXXS** [comment]
> Please share the exported files with us.

Exported files contianed in the [Godot4 project file](https://github.com/MXXXXXS/BugFeedback/raw/main/file/Godot4SpineTextureLoadBug.zip)

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/28096993/bd2e38a0-599f-4143-ad80-10acf8b379dd)

**Comment by badlogic** [comment]
Apologies, overlooked the link to the project file.

**Comment by badlogic** [comment]
Displays correctly in SkeletonViewer and spine-sfml, displays incorrectly in spine-godot.

**Comment by badlogic** [comment]
The issue is related to the use of non-ASCII characters for attachment names. This seems to be Godot specific, investigating.

**Comment by badlogic** [comment]
This and #2374 have now been fixed in the 4.1 and 4.2-beta branches. Please download the latest Binaries from https://esotericsoftware.com/spine-godot once this build has finished:
https://github.com/EsotericSoftware/spine-runtimes/actions/runs/6275057111

Thanks for reporting!
