### ISSUE TITLE
[godot][cpp] Clipping broken

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2373]
See https://esotericsoftware.com/forum/d/24796-godot-41-clipping-problem/7

See email FMfcgzGtxKQQpLLMTQXsVfpXKZklcXnH for repro

**Comment by badlogic** [comment]
Works in spine-sfml, likely culprit is the spine-godot Renderer.

**Comment by luanhadev** [comment]
I also have this bug. Everything is fine except for the mask/Clipping part, which is broken. I hope to fix this bug soon.  [Video here](https://youtu.be/MCF2fbENcVE)

**Comment by badlogic** [comment]
Please note that we can usually not fix an issue just based on a video. OP provided assets to us with which wr can reproduce the issue. If in the future you find an asset specific bug, please always attach the assets, so we can reproduce the issue locally.

I've found the bug in the code already and am trying to fix it. It's an issue with mesh invalidation when the vertices of an attachment change due to clipping.

**Comment by luanhadev** [comment]
I am very glad that you found the cause. I will attach the file if I encounter an issue in the future, thank you for the reminder.
Here my exported file. 
[Machine.zip](https://github.com/EsotericSoftware/spine-runtimes/files/12700176/Machine.zip)

**Comment by badlogic** [comment]
This has been fixed now. You can download new Godot binaries from our site once this build has finished:
https://github.com/EsotericSoftware/spine-runtimes/actions/runs/6274395636

Thank you for reporting!
