### ISSUE TITLE
[godot] SpineSlotNode stuck on initial transform

### ISSUE THREAD

**Issue by GameJawnsInc** [EsotericSoftware/spine-runtimes#2381]
SpineSlotNode no longer moves during an animation, any children are stuck in its initial state.

Check 07-slot-node in the examples, the raptor, godot icon, and tiny spineboy no longer move when the big spineboy is animating. attached gif example

![godot-4 1-4 1 1-stable_1_bgUUTbSqxZ](https://github.com/EsotericSoftware/spine-runtimes/assets/122755272/d390cb9a-5f76-4519-b083-0222394086d2)

**Comment by badlogic** [comment]
Thanks for reporting, I've noticed this as well yesterday night when I finished porting the examples to C#. It's on my todo for today.

**Comment by badlogic** [comment]
It's a regression introduced here which I didn't catch:
https://github.com/EsotericSoftware/spine-runtimes/pull/2332/files#diff-d769d87c37a3c77b67fdf5049ff58af963f210bc60fef469da55bcbe670c8545R77

Fixed in 4.1 and 4.2-beta branch. Thanks for reporting.
