### ISSUE TITLE
[flutter]Can the slot use HSV color change?

### ISSUE THREAD

**Issue by sarah707** [EsotericSoftware/spine-runtimes#2382]
The SetColor can only change RGB color and cannot make changes from hue, saturation, and brightness. How to change the HSV color for a slot ? like colorFilter or something else?

**Comment by badlogic** [comment]
Please use the forums for questions like this: https://esotericsoftware.com/forum. The issue tracker is for bugs and enhancements.

To answer your question: you can use Flutter's built-in [HSVColor](https://api.flutter.dev/flutter/painting/HSVColor-class.html) class. It has a method called `toColor()` which converts your HSV color to RGB, which you can then set on the slots.

**Comment by sarah707** [comment]
> Please use the forums for questions like this: https://esotericsoftware.com/forum. The issue tracker is for bugs and enhancements.
> 
> To answer your question: you can use Flutter's built-in [HSVColor](https://api.flutter.dev/flutter/painting/HSVColor-class.html) class. It has a method called `toColor()` which converts your HSV color to RGB, which you can then set on the slots.

Thank you for your reply, and I apologize for posting the question in the wrong place.

**Comment by badlogic** [comment]
No worries!
