### ISSUE TITLE
[flutter]I added a colorFilter to the canvas.drawVertices in spine_flutter.dart, it doesn't work on iOS

### ISSUE THREAD

**Issue by sarah707** [EsotericSoftware/spine-runtimes#2384]
To change the brightness of an individual slot, I added a colorFilter to the paint parameter before the canvas.drawVertices in spine_flutter.dart. It worked well on windows, web, macOs and android, but not on IOS. On iOS, the image appears in the colors that haven't been altered by the colorFilter.
The code like:
```
List<RenderCommand> renderToCanvas(Canvas canvas) {
    var commands = render();
    for (final cmd in commands) {

      final List<double> matrix = getHSVMatrix(
          hue: 0, brightness: 0.7, saturation: 0.1);

      Paint paint = atlas.atlasPagePaints[cmd.atlasPageIndex][cmd.blendMode]!;

      Paint copiedPaint = Paint()
        ..color = paint.color
        ..strokeWidth = paint.strokeWidth
        ..style = paint.style
        ..blendMode = paint.blendMode
        ..maskFilter = paint.maskFilter
        ..filterQuality = paint.filterQuality
        ..isAntiAlias = paint.isAntiAlias
        ..strokeCap = paint.strokeCap
        ..strokeJoin = paint.strokeJoin
        ..shader = paint.shader;

      copiedPaint.colorFilter = ColorFilter.matrix(matrix);
      canvas.drawVertices(
          cmd.vertices, rendering.BlendMode.modulate, copiedPaint);
    }

```
 I tested canvas.drawVertices in my own file, and in my test, colorFilter can work normally on iOS. Is there any advice on how I should modify it in spine_flutter.dart so that colorFilter can be used on iOS?

**Comment by badlogic** [comment]
Can you share your own test for `canvas.drawVertices()`? On iOS, the default renderer Flutter uses is called [Impeller](https://docs.flutter.dev/perf/impeller) which seems to have quite some differences to the other renderer(s). I'm afraid I would not know why changing the paint like in your example above doesn't work on iOS. As you saw yourself, our code doesn't do anything special. We simply construct a `Paint` and use it to draw vertices through the Flutter `Canvas` API.

**Comment by sarah707** [comment]
@badlogic my test code like

```
class MyPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final vertices = ui.Vertices(
      VertexMode.triangles,
      [
        Offset(100, 100), 
        Offset(200, 100), 
        Offset(150, 200), 
      ],
    );
    final List<double> matrix =
        cla.getHSVMatrix(hue: 1, brightness: 0.8, saturation: 0);

    final paint = Paint()
      ..color = Colors.blue 
      ..style = PaintingStyle.fill 
      ..blendMode = rendering.BlendMode.srcOver
        ..strokeMiterLimit = 0.0
        ..filterQuality = FilterQuality.none

      ..colorFilter = ColorFilter.matrix(matrix);

    canvas.drawVertices(vertices, rendering.BlendMode.modulate, paint); 
  }
```

The test doesn`t use ImageShader, I am currently thinking that perhaps this issue is due to a conflict between ImageShader and ColorFilter. I am trying to conduct a test with a paint that has used ImageShader. Unfortunately, since I am a Flutter beginner, I haven't even succeeded in writing a test yet…

**Comment by badlogic** [comment]
Closing this out, as there's nothing we can do on our end. This appears to be a bug in Impeller. Hopefully future releases will fix it.
