### ISSUE TITLE
[godot] Spurious errors when importing atlas pngs and Spine icon not showing up

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2385]
See https://esotericsoftware.com/forum/d/24839-cant-import-skeletons

No idea where these come from, or why the path shown is entirely weird.

The errors are non-sensical, the import works as intended.

The Spine icon is not shown for Spine resources in Godot 4.x.

**Comment by PiewieP** [comment]
I am in the process of testing updating from runtime 4.2.1 to 4.2.2 and I can confirm that "The Spine icon is not shown for Spine resources in Godot 4.x" is still an active issue in 4.2.2.

**Comment by misaki-eymard** [comment]
Another user reported on this issue on the forum, so I did some research and would like to add the following:

This error can be easily reproduced by simply creating a Godot 4.x project and importing the skeleton files. The following error log is printed in the Output dock:
-   No loader found for resource: res://spineboy-pro.png (expected type: )
-   /Users/runner/work/spine-runtimes/spine-runtimes/spine-godot/spine_godot/SpineAtlasResource.cpp:74 - Can't load texture: "res://spineboy-pro.png"
<img width="876" alt="Screenshot 2024-06-03 at 9 56 20" src="https://github.com/EsotericSoftware/spine-runtimes/assets/85478846/bb497da8-a7b5-4d8a-9615-b874f1e79c8f">

However, there are no particular problems with displaying the skeleton in the scene, so there is no real harm.

This occurs in Godot 4.1.4, 4.1.4-mono, 4.2.2 and 4.2.2-mono, and does not occur in Godot 3.5.3. 
This error has been confirmed to occur for both Windows and macOS users.

**Comment by PiewieP** [comment]
Tested with Godot 4.3, still no icons. Would it be possible to create a separate issue for this? I believe the missing icons is not related to the error messages shown above.

**Comment by DASilverStraw** [comment]
Godot version 4 changed naming rule for icons.

Godot 4: SpineSprite.svg
Godot 3: icon_spine_sprite.svg

**Comment by badlogic** [comment]
Solution here:
https://esotericsoftware.com/forum/d/25615-godot-421-spine-icon-missing-for-all-resources

They renamed the expected icon name.

**Comment by badlogic** [comment]
Finally figured this out. When importing `.atlas` files, the corresponding `.png` files might not have been imported yet. Then the atlas resource loader tries to load the corresponding textures, it fails, as those textures have not been imported yet.

This wasn't an issue after the import, i.e. when assigning the atlas resource to a skeleton data resource, because the atlas resource would be reloaded, with the textures now being imported as well.
