### ISSUE TITLE
Can't Godot 4x support Spine 3x or 2x versions?

### ISSUE THREAD

**Issue by mrpanzhi** [EsotericSoftware/spine-runtimes#2388]
Can't Godot 4x support Spine 3x or 2x versions?

**Comment by mrpanzhi** [comment]
What about Spine 3x or 2x version materials?

**Comment by badlogic** [comment]
I'm not sure what you mean by "materials". In any case, spine-godot only supports exports from Spine Editor version 4.1.x+.
