### ISSUE TITLE
[ue] How to attach image widget to a bone

### ISSUE THREAD

**Issue by hojjatjafary** [EsotericSoftware/spine-runtimes#2402]
How can we attach a image widget to a bone attachment?
I just tried getting bone transform and apply it to the image but the position was wrong.
The `GetBoneTransform` method returns `FTransform` but the image widget require `FWidgetTransform` and there is not conversion method.
We have so many icons that updates regularly and don't want to make them an atlas, so we are going to attach it to a specified bone.

**Comment by badlogic** [comment]
This is currently not possible, and if it were, it wouldn't work like you'd expect. E.g. you can not insert an image widget in the drawing order of the skeleton's attachments due to the way Slate rendering works. I'm afraid there's no work around either.
