### ISSUE TITLE
[ts webgl] Unexpected token 'export' with vite dev server

### ISSUE THREAD

**Issue by zip-fa** [EsotericSoftware/spine-runtimes#2407]
Hi.
I use spine-webgl inside my angular application. Angular v17 uses vite under-the-hood to run development server.
It crashes with this error when importing AssetManager or something other from your library:

```
Error when evaluating SSR module /main.server.mjs: failed to import "@esotericsoftware/spine-webgl"
|- C:\ng-spine-vite-bug\node_modules\@esotericsoftware\spine-webgl\dist\index.js:1
export * from "./AssetManager";
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

This bug can be reproduced with this repo: https://github.com/zip-fa/ng-spine-vite-bug

```
npm i
npm run start
```

**Comment by zip-fa** [comment]
Angular's team member explained what's wrong here: https://github.com/angular/angular-cli/issues/26209

**Comment by davidetan** [comment]
Did you activate SSR intentionally?
I'm not 100% sure, but even with the fix, there might be problems using SSR since on server side `node` is used, but `spine-webgl` uses components that are present in browsers only.

**Comment by zip-fa** [comment]
It's not about using SSR, it's about importing. I am disabling spine component on SSR so it will not run in server environment. But it still throws, so need to be fixed.

**Comment by davidetan** [comment]
Oh, ok, got it.

I was thinking that if you activated it unintentionally, you could prevent the problem by creating a project without SSR enabled. 

In that case you have to wait for the fix.

**Comment by badlogic** [comment]
Thanks for reporting, the ESM support of the spine-ts packages has been fixed. I've published versions 4.1.45 and 4.2.26 to NPM.

That said, you are trying to load spine-webgl in a server side rendering setting. That won't work, as spine-webgl requires browser APIs that are not available in NodeJS. This is not something we will "fix".

<img width="922" alt="Screenshot 2023-11-06 at 12 50 20" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/cb8e5868-f56f-4d64-bb4d-35605b939944">

**Comment by spayton** [comment]
The build has now broken for me, it broke on this commit - 9d4d86ced3cb1dae07a3e8ce501cf036316ea62d - which relates to this issue.

There's a number of errors but this is the 1st error I am seeing, though it's the phaser iife builds I'm missing:

```console
[5] > @esotericsoftware/spine-ts@4.1.45 build:threejs
[5] > npx esbuild --bundle spine-threejs/src/index.ts --tsconfig=spine-threejs/tsconfig.json  --sourcemap --outfile=spine-threejs/dist/iife/spine-threejs.js --external:three --format=iife --global-name=spine
[5]
[2] X [ERROR] No matching export in "spine-webgl/src/WebGL.ts" for import "WebGLBlendModeConverter"
[2]
[2]     spine-webgl/src/SkeletonRenderer.js:30:9:
      30 │ import { WebGLBlendModeConverter } from "./WebGL";
[2]          ╵          ~~~~~~~~~~~~~~~~~~~~~~~
[2]
[2] 1 error
```

**Comment by spayton** [comment]
forgot to say, the build error was on Win10-64bit, Node 19.4.0, Npm 9.2.0

**Comment by badlogic** [comment]
what package version?

**Comment by spayton** [comment]
upto and including v4.1.44 (c00ffb2e2d30f364e059ff92a5f1e60191d97840) builds fine, anything after that fails (v4.1.45+)

**Comment by badlogic** [comment]
Just so I understand, you are working off of the spine-runtimes repo. You've pulled the latest 4.1 or 4.2-beta branch commites, then in `spine-ts/` you do `npm install`? I can not reproduce this on my machines at all. There's also no case sensitivity issue involved here afaict. 

And this line

```
import { WebGLBlendModeConverter } from "./WebGL";
```

Is nowhere in the entire source tree.

**Comment by badlogic** [comment]
I just tried on a Windows 10 machine with Node 20 and it also works as intended. Please provide me with step by step instructions to repro this issue.

**Comment by badlogic** [comment]
The GH action also builds just fine https://github.com/EsotericSoftware/spine-runtimes/actions/runs/6770768936

**Comment by spayton** [comment]
ok, I'll try again, maybe reverting to a specific commit and 'npm i' ing isnt preparing it enough

**Comment by spayton** [comment]
Tried building on both a github codespace and to a fresh local checkout - and they both built ok.

So, something wrong with my working repo!

**Comment by badlogic** [comment]
Alright! If you figure it out, lmk.

**Comment by spayton** [comment]
I had a hung instance of vs-code with some filelocks on some files down in node_modules, resolving that didn't fix problem.

I had a load of .js & .d.ts files, ie the output of the compiled .ts files dumped into same location as src .ts files, mostly dated 28/4/23 or after.  No idea how/why, did this used to be part of the build process then?  Anyway, I had to manualy delete all these .js and .d.ts files, and it then started building properly.

**Comment by badlogic** [comment]
Classic case of "have you tried turning it off and on again". Sorry, I'm at a loss what could have happened here. The build actually cleans out all build dirs entirely, so nothing old should be left over.

**Comment by spayton** [comment]
There were 161 intermediate .js/.d.ts files sat alongside their .ts src files, so to be clear, these files were in the src folders not the build output folders.  Here's a snippet of my recycle bin, in case it's useful in the future, but for me, issue resolved, time to move on.
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/4949575/961a1879-d686-4f0a-a955-4425449594a1)
