### ISSUE TITLE
[Unity] Is it possible to generate meshes offline?

### ISSUE THREAD

**Issue by AliA74** [EsotericSoftware/spine-runtimes#2411]
We have about 50-60 spine objects loaded at runtime using Addressables in a Unity project. Each one when loaded we get a spike that is caused by mesh generation from Spine.

I wonder if it is possible to create the meshes at Edit time to avoid generating meshes at runtime?

**Comment by badlogic** [comment]
Could I ask you to please use the forum for general questions? https://esotericsoftware.com/forum

The issue tracker is meant for filing bugs/enhancements and keeping track of them.
