### ISSUE TITLE
[cpp][godot] Skeleton renders incorrectly

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2412]
See https://esotericsoftware.com/forum/d/24955-c-the-type-or-namespace-name-spinesprite-could-not-be-found/10

**Comment by DoniaMohamedAbdEl-Rahim** [comment]
Is there any update about this ?

**Comment by badlogic** [comment]
@DoniaMohamedAbdEl-Rahim sorry, took a little while. It was a bug in IKConstraint. I've now pushed fixes for all language runtimes.
