### ISSUE TITLE
[Unity]  A Memory Leak in SkeletonPartsRenderer.cs

### ISSUE THREAD

**Issue by ArthurUnreal** [EsotericSoftware/spine-runtimes#2414]
SkeletonPartsRenderer is destroyed without dispose MeshBuffers. It caused a Memory leak in my project when SkeletonPartsRenderer was destroyed during changing scene.

**Comment by HaraldCsaszar** [comment]
@ArthurUnreal Thanks for reporting, good catch!
We've pushed a bugfix, new spine-unity 4.1 and 4.2-beta unitypackages are available for download here as usual:
https://esotericsoftware.com/spine-unity-download
