### ISSUE TITLE
[flutter] compilation errors with the release of flutter 3.16.0

### ISSUE THREAD

**Issue by erickzanardo** [EsotericSoftware/spine-runtimes#2420]
With the release of Flutter 3.16.0 which happened yesterday (November 15th, 2023), some compilation errors were introduced in the `raw_image_provider` package, used by the flutter runtime, which make the the spine_flutter package not work in this new flutter version.

I've already submitted a PR to the `raw_image_provider` package: https://github.com/yrom/flutter_raw_image_provider/pull/1

If that PR gets merged, I am happy to open a PR here to update the dependency, but I am opening this issue here so it can be tracked here as well.

**Comment by badlogic** [comment]
Thank you!

**Comment by badlogic** [comment]
Since the author is not reactive to your pull request, I've included the dependency directly in source form in spine-flutter.

I've also bumped our minimum Flutter SDK target version up to 3.16.0 and released new packages to pub.dev.

**Comment by erickzanardo** [comment]
Thanks!!!
