### ISSUE TITLE
[spine-csharp]  This function is executed unnecessarily many times, which causes a lot of Spine to take a long time

### ISSUE THREAD

**Issue by pangxiaobo** [EsotericSoftware/spine-runtimes#2424]
ExposedList.cs  ---->  Clear() ------> Array.Clear(Items, 0, Items.Length);

**Comment by pangxiaobo** [comment]
> ExusedList.cs ----> Clear() ------> Array.Clear(Items, 0, Items.Length);

It has been cleared and does not need to be executed

**Comment by HaraldCsaszar** [comment]
@pangxiaobo Please provide the stack trace from where this method is called too often. Without the necessary context info we can't improve anything. Closing this ticket for now. We will happily reopen it when the necessary reproduction info is available.
