### ISSUE TITLE
[spine-ts] Question: Would you consider publishing 3.6 and 3.8 to NPM ?

### ISSUE THREAD

**Issue by epreston** [EsotericSoftware/spine-runtimes#2426]
Hello there. Would you consider publishing 3.6 and 3.8 to NPM ?

With the guidance of the people at PlayCanvas, we were able to update the Spine plugin.
https://github.com/playcanvas/playcanvas-spine

The solution (and build system) could be a little more graceful if we could source all versions of Spine via NPM.

**Comment by badlogic** [comment]
I'm afraid that won't happen. 3.8 and especially 3.6 are ancient, and we no longer provide bug fixes or feature updates for them. As such, it doesn't make much sense for us to bolt on a build system onto those branches and publish them to NPM.

What's the use case for 3.6?

**Comment by epreston** [comment]
Spine runtime versions directly correspond to the version of the Editor used. People like the product and create lots of content.  They see upgrading their old content files as risky (and there have been some changes, like alpha blending, bone ordering).  None of this is a bad thing its just awkward to dig into an old branch to pull out a runtime.

With a package, no one is impacted if the branch is removed.

No need to put together a build system.  A quick package.json and a one time publish would do.  Maybe a few words in the readme directing people towards the latest versions.

**Comment by epreston** [comment]
My use case for 3.6 is that it needs to be supported in any changes I make to the PlayCanvas integration.  I've added support for 4.0 and 4.1.  I've been following the project so I can add 4.2 support quickly when it comes out.
