### ISSUE TITLE
I can not run my spine animation, created with spine v3.8.75

### ISSUE THREAD

**Issue by nirobhasanbd** [EsotericSoftware/spine-runtimes#2428]
Here is my development environment:
`MacBook Pro M2 2022, macOS Sonoma 14.0, Xcode 15.0, Spine 3.8.75`

I am using the `spine-runtime (spine-cpp with spine-cocos2dx)` from `3.8 branch`. But I can not run my spine animation created with spine `v3.8.75`. It is crashing here:

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/62602617/7eae5c03-5af8-4a4e-a322-c3e60ea8f677)

I debug the library by searching `Unsupported skeleton data, please export with a newer version of Spine.` and found the below:

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/62602617/ad736843-ce7c-4428-a12c-38cf3891166d)

There is a a condition in `SkeletonJson::readSkeletonData()` where it is providing exception if the spine version is exactly `3.8.75`.
If I delete this condition then my spine animation is working fine.

So I want to know why this condition is there. And If I remove this condition then what kind of problem I will face in future?

Thanks in advance.

**Comment by NathanSweet** [comment]
3.8.75 has bugs in its exports and is not supported. The runtimes require updating your Spine version so we don't get bug reports when things don't work correctly. Please export with a newer version of Spine. If you must use 3.8 then export with 3.8.99. The 3.8 runtime is extremely old, it would be better to move to 4.1 or 4.2. We have physics in 4.2!
