### ISSUE TITLE
[Unity] Spine build processor slows down builds significantly. Overuse of UnloadUnusedAssetsImmediate()

### ISSUE THREAD

**Issue by michalpypek** [EsotericSoftware/spine-runtimes#2429]
The spine build processor script: https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-unity/Assets/Spine/Editor/spine-unity/Editor/Utility/SpineBuildProcessor.cs

method `PreprocessSpinePrefabMeshes ` - goes over ALL the prefabs in the project and calls `EditorUtility.UnloadUnusedAssetsImmediate();` for each prefab. Making build times extremely long, 

`PostprocessOnDemandTextureLoaders` and `PreprocessSpriteAtlases` are also calling the UnloadUnusedAssetsImmediate method quite a lot

This (especially the prefab loop) makes build times grow incredibly long, with the only logs in the log file being
```
Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
(...)
```

spammed continuously, as the script goes through every single prefab in the project and waits for unity GC.
Calling that method seems overzealous, especially calling it in a foreach loop. And the processor script not printing any logs while it starts running makes it hard to find the cause for slow builds.

To show the scale of the problem- commenting out these lines made our build times go from:
`4h 33m`  -> `59m`  on Android
`2h 46m` -> `24m` on iOS

by commenting out these calls.

**Comment by michalpypek** [comment]
I just noticed that it's moved out of the foreach loops on the repository, the package iI've been using must've been out of date.

**Comment by HaraldCsaszar** [comment]
@michalpypek Glad to hear you could resolve the issue, thanks for updating the ticket accordingly.
