### ISSUE TITLE
[godot] Skeleton Render Separator feature request

### ISSUE THREAD

**Issue by tarragonfly** [EsotericSoftware/spine-runtimes#2432]
SpineSeperatorNode or SpineRenderSeparatorNode would split a Spine skeleton in two or more parts with different Node2D Z Index property values. Presumably, this would be set to be a parent node of any SpineSprite that would require this functionality. 

Use cases: 

1. Users might need to display in-world objects between parts of Spine character, e.g. to let the character run into a tree and display one leg in front and one behind the trunk. 

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/81910799/f35de304-f668-4572-aba4-f75d000696a0)

2. Interactions between multiple separate Spine characters that have different rendering order requirements depending on the animations played. For things like hugs.
3. This would also work for advanced character customization systems where the body is separate from the head skeleton and the head has to render the face in front of the body and some of the hair behind the body skeleton. I'm aware SpineSlotNode could sorta achieve this by inserting the body in a dummy slot between the face and the hair, but this does not address all use cases, especially when the body is the same and it's only the heads which are swapped.

**Comment by badlogic** [comment]
Yes, see https://github.com/EsotericSoftware/spine-runtimes/issues/2430
