### ISSUE TITLE
Bones scale is not always applied, when bone is initially attached- Haxe

### ISSUE THREAD

**Issue by lewisD115** [EsotericSoftware/spine-runtimes#2434]
I have an animation (wild_lvl2_panda_jumping_part3_left) which works fine with Spine 4.0, but with Spine 4.1, sometime the scale will be incorrect for a frame when the bone is attached. 
https://github.com/EsotericSoftware/spine-runtimes/assets/56297577/0b887574-6369-4064-9603-ddbe5290bbc9

This is part of the animation that seems to cause the bug:
`"bones": {
			"panda_lvl2": {
				"scale": [
					{ "curve": "stepped" },
					{ "time": 0.6, "x": 0.601, "y": 0.601 }
				]
			}`
I can hack a fix in the json file, by changing time to 0.59, but this does not solve the root problem in the library.

When tracing in ScaleTimeline, the scale is represented correctly for the time i.e. before 0.6 scaleX is always 1, and after it's 0.601.
I'm not sure if the bug is down to a rounding/float point error, or an efficiency issue somewhere in the library.

I have attached the animation files, where I have simplified the animations in the json file, however I have not reduced bones, slots, and skins so apologies for the extra code and unnecessary pngs.
[PandaScaleBug.zip](https://github.com/EsotericSoftware/spine-runtimes/files/13659959/PandaScaleBug.zip)

I will continue to investigate, mainly looking at changes from 4.0 to 4.1, but I would appreciate any help :)

**Comment by lewisD115** [comment]
Apologies, I was being an idiot, it was a small change in the runtime. Closing the ticket.

**Comment by badlogic** [comment]
@lewisD115 could you elaborate what you mean with "it was a small change in the runtime"? Do you mean you modified the runtime? If so, I'm always happy to hear why folks modify the runtime. Your changes may be worthwhile to be included in the official runtimes.

**Comment by lewisD115** [comment]
@badlogic  I was just messing around making use of rotation, so that you could configure bones to rotate to follow the curser, and in doing so I added another state.apply(skeleton) when advancing the time. So something like:
```
state.update(time * timeScale);
state.apply(skeleton);
skeleton.updateWorldTransform();
this.rotateBones();
state.apply(skeleton);
```
The last line caused the issue.

**Comment by badlogic** [comment]
Oh,.whoopsies :) Thanks for taking the time to reply!
