### ISSUE TITLE
[spine-flutter] not compatible with `use_frameworks! :linkage => :static`

### ISSUE THREAD

**Issue by hyiso** [EsotericSoftware/spine-runtimes#2438]
Adding `spine_flutter` to a Flutter module (for add2app usage), and run the host iOS project, it can't find the spine_flutter.framework/spine_flutter when opening Flutter page in Debug mode

```bash
flutter: Invalid argument(s): Failed to load dynamic library 'spine_flutter.framework/spine_flutter': dlopen(spine_flutter.framework/spine_flutter, 1): image not found
flutter: #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
flutter: #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
flutter: #2      _dylib.<anonymous closure> (package:spine_flutter/init.dart:38:27)
flutter: #3      _dylib (package:spine_flutter/init.dart:47:2)
flutter: #4      _dylib (package:spine_flutter/init.dart)
```

Flutter SDK version is 3.7.12
spine_flutter version is 4.2.12

**Comment by badlogic** [comment]
I'm afraid I have no experience with `add2app`. Do you happen to know if it has special requirements regarding loading dynamic libraries?

**Comment by hyiso** [comment]
I'm not sure whether this plugin needs any configurations else, as I cannot find spine_flutter.framework in the `Frameworks` directory under the output HostProject.app

**Comment by hyiso** [comment]
I've tested a simple add2app example, only a little different from my iOS host project, this plugin runs as expected.

The main difference is in Podfile
```ruby
# Simple add2app example
use_frameworks!
```
```ruby
# My iOS host project
use_frameworks! :linkage => :static
```
It seems not compatible with `:linkage => :static`

Then I changed the Podfile of the simple add2app example with `:linkage => :static`, it throws the exception.

So the real problem is that this plugin cannot be used with `:linkage => :static`

In my iOS host project, some other static libraries are required, so `:linkage => :static` cannot be removed.

Could this plugin support using static library?

**Comment by hyiso** [comment]
Also tried the example in spine-flutter, adding `:linkage => :static,` after `use_frameworks!`, it also throws the exception

**Comment by badlogic** [comment]
Sorry for this taking so long. I believe I have fixed this. You will have to adjust the way spine-flutter is initialized. E.g.

```dart
  await initSpineFlutter(useStaticLinkage: true);
```

This will instruct Dart FFI to lookup symbols in the process/executable instead of trying to locate them in a framework.

I've published a new spine_flutter package to pub.dev, version 4.2.24.
