### ISSUE TITLE
[spine-ts] Webp support

### ISSUE THREAD

**Issue by kajgiesbersflavour** [EsotericSoftware/spine-runtimes#2451]
We would like to use webp for the atlas instead of png for performance and bandwidth because the webp file is 3 times smaller.
Spine-ts however doesn't seem to support webp, when exporting the atlas as webp it seems to export correctly the exported webp file looks good when opened separately. When using the exported json/webp/atlas files with the webp player as described in [the guide](https://esotericsoftware.com/spine-player) there are artifacts in the animation.

What it looks like with the webp artifacts:
![NVIDIA_Share_cW4q6K8AkM](https://github.com/EsotericSoftware/spine-runtimes/assets/72016203/11a8e79f-863d-4508-83cf-5d889d98af69)

What it is supposed to look like, and what it looks like when exporting as png:
![NVIDIA_Share_3cCfqN1L4O](https://github.com/EsotericSoftware/spine-runtimes/assets/72016203/11d07b50-7732-4406-a53c-9daf0acd53d3)

Is this a bug in spine-ts? Or are we missing something?

Kind regards,

Kaj

**Comment by badlogic** [comment]
Looks like premultiplied alpha is incorrect. Do you export lossy WEBP? Then that's what you'll get I'm afraid, as the alpha will be "compressed" in weird ways. This is not a bug in spine-ts, but a result of lossy compression.

**Comment by kajgiesbersflavour** [comment]
Using lossless compression slightly improves it but there are still artifacts. Disabling premultipliedAlpha in the SpinePlayerConfig solved the issue. Thanks you for the help!

Maybe some information about this could be added to the guide?

**Comment by badlogic** [comment]
Good point, I'll update the Spine Player docs accordingly.

**Comment by dvelasquez-dk** [comment]
@badlogic Is [this the Spine Player documentation](https://esotericsoftware.com/spine-player) you were referring to? Didn't see anything re: webp. We are using Spine to export our webp from source using the defaults and that gave very similar issues to OP with threejs. Are there any recommended export settings for getting webp and pma to play nicely?

**Comment by davidetan** [comment]
> @badlogic Is [this the Spine Player documentation](https://esotericsoftware.com/spine-player) you were referring to? Didn't see anything re: webp. We are using Spine to export our webp from source using the defaults and that gave very similar issues to OP with threejs. Are there any recommended export settings for getting webp and pma to play nicely?

I've answered to you in this other issue: https://github.com/EsotericSoftware/spine-runtimes/issues/2604#issuecomment-2516608564

We should probably mention this in the export section of our guide.
