### ISSUE TITLE
[Spine-ts] Will Spine-core 4.2.x support skeleton files exported from version 4.1

### ISSUE THREAD

**Issue by RGCHN** [EsotericSoftware/spine-runtimes#2452]
I found it that：
when I choose export  nonessential  data in Spine Editor, it  showed error :  Offset is outside the bounds of the DataView
<img width="1010" alt="image" src="https://github.com/EsotericSoftware/spine-runtimes/assets/38219632/aa1ee9d9-30e7-444e-afd9-e77b23306eb4">
when choose not  export  nonessential data in Spine Editor, it  showed error :  Bone name must not be null.
<img width="272" alt="image" src="https://github.com/EsotericSoftware/spine-runtimes/assets/38219632/8a0b1148-8120-4fec-b0dd-6ebe1a052c9a">
The key point is that in SkeletonBinary.readSkeletonData function, skeletonData will have properties: icon、visible, which not includes in 4.1 version
<img width="576" alt="image" src="https://github.com/EsotericSoftware/spine-runtimes/assets/38219632/90289b05-bf2e-4765-aff0-6f9b9300e733">
I have lots of skeleton files exported from version 4.1, is it possible to support the skeleton files exported from version 4.1

**Comment by badlogic** [comment]
No, that is not possible. Please have a look at our [version documentation](https://esotericsoftware.com/spine-versioning)
