### ISSUE TITLE
load skel error

### ISSUE THREAD

**Issue by zhangyc** [EsotericSoftware/spine-runtimes#2467]
Restarted application in 1,749ms.
E/flutter (16324): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 44)
E/flutter (16324): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1741:7)
E/flutter (16324): #1      Utf8Decoder.convert (dart:convert/utf.dart:349:37)
E/flutter (16324): #2      Utf8Codec.decode (dart:convert/utf.dart:63:20)
E/flutter (16324): #3      Utf8Pointer.toDartString (package:ffi/src/utf8.dart:49:17)
E/flutter (16324): #4      SkeletonData.fromBinary (package:spine_flutter/spine_flutter.dart:237:29)
E/flutter (16324): #5      SkeletonData.fromAsset (package:spine_flutter/spine_flutter.dart:255:14)
E/flutter (16324): <asynchronous suspension>
E/flutter (16324): #6      SkeletonDrawable.fromAsset (package:spine_flutter/spine_flutter.dart:3929:24)
E/flutter (16324): <asynchronous suspension>
E/flutter (16324): #7      _SpineWidgetState.loadFromAsset (package:spine_flutter/spine_widget.dart:421:22)
E/flutter (16324): <asynchronous suspension>
E/flutter (16324):

**Comment by badlogic** [comment]
You are most likely trying to load a skeleton exported with Spine Editor version 4.1 with a spine-runtime version 4.2-beta.

Please ensure the versions match. Note that spine-runtimes 4.2-beta is currently unstable and in flux. Please use 4.1.x for both the Spine Editor and spine-runtimes for production.

**Comment by zhangyc** [comment]
> You are most likely trying to load a skeleton exported with Spine Editor version 4.1 with a spine-runtime version 4.2-beta.
> 
> Please ensure the versions match. Note that spine-runtimes 4.2-beta is currently unstable and in flux. Please use 4.1.x for both the Spine Editor and spine-runtimes for production.

thank guy。
