### ISSUE TITLE
[spine-flutter] Incorrect rendering on Chrome

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#2479]
https://esotericsoftware.com/forum/d/25703-spine_flutter-4222-/2

**Comment by Jarvan1997** [comment]
I also encountered this issue, and according to my testing, the reason for this issue is that `Atlas.filterQuality` is set to `FilterQuality.medium` by default, and changing it to `FilterQuality.low` or `FilterQuality.high` can make it work properly.
`Atlas.filterQuality = FilterQuality.low;`

**Comment by badlogic** [comment]
Huh, we've changed this a while ago as per a suggestion by the Flame
authors. It appears the latest Canvaskit renderer might have a bug.
Annoying.

**Comment by badlogic** [comment]
Alright, finally had time to investigate. It appears that `FilterQuality` has various issues open on the Flutter tracker, specifically for the web canvaskit rendering backend:

https://github.com/flutter/flutter/issues/131549
https://github.com/flutter/flutter/issues/139028

What we see here seems to be a bug in the canvaskit backend, and as such, it's out of our hands to fix it. Given the existing issues, I refrained from posting another one.
