### ISSUE TITLE
[spine-cpp] Breaking changes in SkeletonBounds interface

### ISSUE THREAD

**Issue by marcinlawicki-hg** [EsotericSoftware/spine-runtimes#2484]
Hi. I am trying to upgrade from Spine 4.0.64 to 4.1.00. I have noticed that some methods that I use are no longer available and there is no information about their removal in the changelog.

Those methods are:
```
SkeletonBounds::getPolygonCount()
SkeletonBounds::getMinX()
SkeletonBounds::getMinY()
```
Can you suggest some other way of getting these information? I cannot find qnything suitable.

**Comment by HaraldCsaszar** [comment]
Which runtime are you using? These properties have not been removed from the spine-csharp runtime for example.

**Comment by marcinlawicki-hg** [comment]
I am using c++ runtime. Thank you for prompt answer.

**Comment by badlogic** [comment]
Those methods have never been part of spine-cpp. I assume ChatGPT suggested those to you?

**Comment by marcinlawicki-hg** [comment]
No, it seems that someone in my company introduced them while moving from C runtime to C++ and didn't document that. But thanks for professional answer.
