### ISSUE TITLE
How to check whether the atlas file is standardized, for example, whether it is missing a certain part of the atlas

### ISSUE THREAD

**Issue by hahazoe** [EsotericSoftware/spine-runtimes#2485]
How to check whether the atlas file is standardized, for example, whether it is missing a certain part of the atlas

**Comment by hahazoe** [comment]
I want use C or C++ runtime to check this

**Comment by HaraldCsaszar** [comment]
@hahazoe Please post questions on the Spine forum, not as github issue tickets.
https://esotericsoftware.com/forum/
