### ISSUE TITLE
[ts-threejs]blend=screen,image still displays with a black background

### ISSUE THREAD

**Issue by s01o** [EsotericSoftware/spine-runtimes#2488]
When I use version 3.6 of spine-runtimes/spine-ts/spine-threejs to load the spine in the attachment, the effect of blend=screen becomes ineffective, and the image still displays with a black background.

[example.zip](https://github.com/EsotericSoftware/spine-runtimes/files/14669883/example.zip)

**Comment by badlogic** [comment]
Please update to the latest version, we do no longer provide bug fixes for Spine 3.6.
