### ISSUE TITLE
Unreal 5.3  use Spine 4.2  Error ！

### ISSUE THREAD

**Issue by liubeichuan** [EsotericSoftware/spine-runtimes#2492]
你们提供的demo，也打不开，紧急一
You provide demo, also can not open, emergency one

  SpineSkeletonAnimationComponent.h(105): [C2039] "getAttachmentThreshold": 不是 "spine::TrackEntry" 的成员
  SpineSkeletonAnimationComponent.cpp(113): [C2661] “spine::Skeleton::updateWorldTransform”: 没有重载函数接受 0 个参数

请迅速修复这个问题，发布最新的文件，谢谢！
Please fix this problem quickly and publish the latest file, thank you!

**Comment by liubeichuan** [comment]
一周过去了，没有人回复………
A week passed and no one responded...

**Comment by HaraldCsaszar** [comment]
得知您遇到麻烦，我们深感抱歉。 请注意，并非所有 4.2-beta 运行时都与最新的 Spine Editor 4.2 导出更改保持同步，这些工作正在进行中。 如果您需要稳定的环境，请使用带有 4.1 运行时的 Spine 4.1，或者等到 4.2 结束测试版。
Sorry to hear you're having troubles. Please note that not all 4.2-beta runtimes are up to date with the latest Spine Editor 4.2 export changes yet, these are ongoing work in progress. If you require a stable environment, please use Spine 4.1 with 4.1 runtimes, or wait until 4.2 is out of beta.

**Comment by liubeichuan** [comment]
> 得知您遇到麻烦，我们深感抱歉。 请注意，并非所有 4.2-beta 运行时都与最新的 Spine Editor 4.2 导出更改保持同步，这些工作正在进行中。 如果您需要稳定的环境，请使用带有 4.1 运行时的 Spine 4.1，或者等到 4.2 结束测试版。 Sorry to hear you're having troubles. Please note that not all 4.2-beta runtimes are up to date with the latest Spine Editor 4.2 export changes yet, these are ongoing work in progress. If you require a stable environment, please use Spine 4.1 with 4.1 runtimes, or wait until 4.2 is out of beta.



==========
I really like the quick import of version 4.2 to PS, and I have already made some of the character animations in 4.2, so if I use 4.1 now, I have to remake these animations, and the repetition is complicated, so I tried to get the correct version configuration from the official ue5Demo, but it seems that the official ue5Demo can't be opened, which makes me feel helpless. I hope to be able to provide me with a working 4.2 connection, thank you very much!

**Comment by HaraldCsaszar** [comment]
@liubeichuan
https://esotericsoftware.com/forum/d/25890-ue-532-build-42-beta-error/6
