### ISSUE TITLE
MeshGenerator.ScaleVertexData have Vector3.op_Multiply() Vector3..ctor()

### ISSUE THREAD

**Issue by prefectover** [EsotericSoftware/spine-runtimes#2500]
``` C#
		public void ScaleVertexData (float scale) {
			var vbi = vertexBuffer.Items;
			for (int i = 0, n = vertexBuffer.Count; i < n; i++) {
				vbi[i] *= scale; // vbi[i].x *= scale; vbi[i].y *= scale;
			}
			meshBoundsMin *= scale;
			meshBoundsMax *= scale;
			meshBoundsThickness *= scale;
		}
```
why, no use vbi[i].x *= scale; vbi[i].y *= scale;

**Comment by HaraldCsaszar** [comment]
I assume you are referring to the `MeshGenerator` in the spine-unity runtime. By default it scales the Z component as well, however the commented line is there in case you want to customize the runtime and only scale the X and Y components.

If I misunderstood what you mean, please explain in more detail what you would like to know.

**Comment by prefectover** [comment]
In Unity, vbi [i] *=scale; Will generate GC, while the rest will not

**Comment by HaraldCsaszar** [comment]
@prefectover How did you get to the assumption that this would cause any GC-relevant allocations?

**Comment by prefectover** [comment]
In Unity, the Vector2 data is multiplied by the following method
```cshape
        public static Vector2 operator *(Vector2 a, float d)
        {
            return new Vector2(a.x * d, a.y * d);
        }
```
Use vbi[i].x *= scale; vbi[i].y *= scale; Not 'new Vector2()'

**Comment by HaraldCsaszar** [comment]
@prefectover Thanks for sharing your thoughts. The question persists, how do you get the impression that this `new Vector2()`, which BTW is a `Vector3`, will be allocated on the heap?
