### ISSUE TITLE
[cocos2dx] Double free warning in Spine Examples

### ISSUE THREAD

**Issue by TyelorD** [EsotericSoftware/spine-runtimes#2505]
When running the Spine Examples and loading a Skeleton from json (such as the RaptorExample.cpp), the Spine DebugExtension reports the following:
```
[...]/cocos2d/cocos/editor-support/spine/Atlas.cpp:59 (address omitted): Double free or not allocated through SpineExtension
[...]/cocos2d/cocos/editor-support/spine/SkeletonJson.cpp:127 (address omitted): Double free or not allocated through SpineExtension
```

I'm a bit confused by this warning though, since this Skeleton and its Atlas were most definitely allocated through SpineExtension. I'm assuming that this is just an oversight or that the DebugExtension doesn't properly mark data read using it's _readFile function.

In the project I'm working on these warnings tend to clutter the Console: though the memory allocation appears to be working normally since DebugExtension reports no leaks detected upon closing the game. So it appears that this warning is likely just cosmetic, but I thought I should report it nonetheless.

**Comment by TyelorD** [comment]
I found a potential work around. I can make a pull request for this fix, if it's deemed appropriate and bug free.

My change is as follows, in Debug.h change the definition of DebugExtension::_readFile to:
```
virtual char *_readFile(const String &path, int *length) {
    auto data = _extension->_readFile(path, length);
    
    if (_allocated.count(data) == 0) {
        _allocated[data] = Allocation(data, sizeof(char) * (*length), nullptr, 0);
        _allocations++;
        _usedMemory += sizeof(char) * (*length);
    }
    
    return data;
}
```

I will note that this doesn't add the __FILE__ or __LINE__ values to the Allocation struct, since I wanted to avoid making changes outside of Debug.h.

**Comment by badlogic** [comment]
The warning is actually correct. While Atlas calls the extension, the extension itself is not allocating this memory. It's Cocos2D-x that loads the file and allocates the in-memory buffer for its contents.

See https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-cocos2dx/spine-cocos2dx/src/spine/spine-cocos2dx.cpp#L134-L150

That said, the warning no longer really serves a purpose, as that part of the runtime has been thoroughly tested. I've applied your change. Thanks!
