### ISSUE TITLE
[player] Allow loading different data files.

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#2506]
Add a method to load different JSON/binary and atlas files.

https://esotericsoftware.com/forum/d/26038

**Comment by badlogic** [comment]
As discussed off GitHub, the only thing you gain is not needing to create the shaders, compared to simply instantiating a new player and swapping it for the old one in the DOM.

Allowing to load any data files at any point in time would require a significant rewrite of the player internals, which many edge cases that need to be handled, that would not occur when simply instantiating a new player.
