### ISSUE TITLE
[runtimes] Copy constructor for Constraints reference bones and slots of the original skeleton

### ISSUE THREAD

**Issue by EdwinMindcraft** [EsotericSoftware/spine-runtimes#2511]
As far as I can tell, I copy constructor for constraints have references to the original skeleton's bones and slots, not the copy's.

* [IkConstraint](https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-csharp/src/IkConstraint.cs#L72-L74)
* [PathConstraint](https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-csharp/src/PathConstraint.cs#L78-L80)
* [PhysicsConstraint](https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-csharp/src/PhysicsConstraint.cs#L77-L78)
* [TransformConstraint](https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-csharp/src/TransformConstraint.cs#L72-L74)

I may have missed something somewhere, but I can't find any changes to those by searching for the usage of those fields.

**Comment by HaraldCsaszar** [comment]
(reopening until other runtimes are fixed as well)

**Comment by HaraldCsaszar** [comment]
@EdwinMindcraft Thanks for bringing this to our attention! This issue has been fixed on the spine-csharp runtime and will soon be fixed on all other runtimes as well. A new spine-unity 4.2 unitypackage is available for download:
https://esotericsoftware.com/spine-unity-download
