### ISSUE TITLE
[spine-csharp] MathUtils.Atan2Deg isn't defined when USE_FAST_SIN_COS_ATAN2_APPROXIMATIONS is defined

### ISSUE THREAD

**Issue by EdwinMindcraft** [EsotericSoftware/spine-runtimes#2517]
When using the `#define USE_FAST_SIN_COS_ATAN2_APPROXIMATIONS`, the method [`MathUtils.Atan2Deg(float x, float y)`](https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-csharp/src/MathUtils.cs#L120-L122) isn't defined.

**Comment by HaraldCsaszar** [comment]
@EdwinMindcraft Thanks for reporting! We've fixed the issue in the above commit, a new spine-unity 4.2 unitypackage is available for download.
https://esotericsoftware.com/spine-unity-download
