### ISSUE TITLE
[TS] MixDuration setter issues

### ISSUE THREAD

**Issue by smaren** [EsotericSoftware/spine-runtimes#2518]
I am not sure what the intended behavior of the new mixDuration setter method of track entries is.

If I have a track with the empty animation (duration of 0 seconds), and then add another animation, the calculated delay is `-mixDuration`, resulting in the first frames being missed.

Further, the delay is always adjusted according to its current value, so calling `entry.mixDuration = value` adjusts the delay every time:

```javascript
// Mixing from empty animation with duration 0.
console.log(entry.delay); // 0
entry.mixDuration = 100;
console.log(entry.delay); // -100
entry.mixDuration = 100;
console.log(entry.delay); // -200
entry.mixDuration = 100;
console.log(entry.delay); // -300
```

I think the purpose is to adjust the delay, so the animation is fully mixed in when the previous animation ends.
I think it also makes sense to make sure that the animation is not started too early and that multiple calls with the same `mixDuration` results in the same delay.

**Comment by badlogic** [comment]
Sorry, this is a bug. I've pushed a new package to NPM. The old `TrackEntry.mixDuration` behaviour was restored. There's a new `TrackEntry.setMixDurationWithDelay()` method, which will allow you to recalculate the delay.

**Comment by smaren** [comment]
Hello, you named the method setMixDurationWithDelta (delta, not delay). Should it not function similar to the way it works in the LibGDX version? Currently, it subtracts delay instead of mix duration, and multiple calls to this function will still result in different results.
 In any case, this fixes my issues, since we can set the mixDuration without any sideeffects.

**Comment by badlogic** [comment]
Uff, I didn't have my coffee yet. It should be called `setMixDurationWithDelay`.  I fixed up both the name and implementation. Thanks for reporting!
