### ISSUE TITLE
[flutter] Animation may not be applied correctly to the skin bones of the mix-and-match skeleton in the Dress Up example.

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-runtimes#2526]
**Description:**
When applying a new skin to the mix-and-match skeleton in the Dress Up example in the spine-flutter runtime example, the dance animation may not be applied correctly to the skin bones. 
![Screenshot 2024-05-15 at 11 21 06](https://github.com/EsotericSoftware/spine-runtimes/assets/85478846/e0dff4a9-fb60-4243-9765-534402b266bd)

This problem does not always occur and may or may not occur even if the skin is applied in the same way. See the following video for more information on the randomness of this issue.:
https://youtu.be/6JvDvCC58_g
(The video above also shows an issue that clicking on the costume icon sometimes fails to apply the skin).

**Expected behavior:**
Whenever a skin is applied, animation is always applied to the bones contained in the applied skin.

**Steps to reproduce:**
1. Run the example project located in the `example/` folder. (In the video in the description, I ran the example on an iPhone 15 Pro Max iOS 17.4 simulator, but I have confirmed that it can be reproduced on a macOS simulator.)
2. Choose `Dress Up` in the example list.
3. Try adding a blue cape or red cape skin. It may work the first time, but you should be able to see that sometimes the skin bone does not move, as if it is stuck in the process of repeatedly putting it on and taking it off.

**The version of runtime in which this issue was found:**
spine-flutter 4.2

**Comment by badlogic** [comment]
This is happening also in the spine-flutter 4.1 branch, indicating that the issue is not related to the changes in 4.2, e.g. the addition of physics.

The user side Flutter code of the dress up example looks correct. There might be a bug in spine-cpp, which is actually performing all calculations.

I'm investigating.
