### ISSUE TITLE
[ts][pixi] Add `tint` property for Pixi's convention

### ISSUE THREAD

**Issue by furic** [EsotericSoftware/spine-runtimes#2527]
[Pull Request 2528](https://github.com/EsotericSoftware/spine-runtimes/pull/2528)

[Pixi uses](https://pixijs.download/v6.1.0-rc.2/docs/PIXI.Sprite.html#tint) `tint: number` for color, it would be nice to match the convention and expose the property for easy usage:

```
spineboy.tint = 0xff00ff;
console.log(spineboy.tint);
```

**Comment by davidetan** [comment]
It works well!
We made a little modification into Utils to use a lambda.
Merge and released in `4.4.43`.
Thanks!
