### ISSUE TITLE
[UE] Crash when callbacks called

### ISSUE THREAD

**Issue by hojjatjafary** [EsotericSoftware/spine-runtimes#2537]
We had a random crash in our game activating spine animation, the crash occurs in `callbackWidget` function inside the `SpineWidget.cpp` https://github.com/EsotericSoftware/spine-runtimes/blob/63dc7d1bb80c7a4c37c43c8f761bc2e887c880c5/spine-ue/Plugins/SpinePlugin/Source/SpinePlugin/Private/SpineWidget.cpp#L39

When the `TrackEntry` try accessing the `UTrackEntry` by calling `getRendererObject()`.

This can be happened because the `TrackEntry` is a native class that has a `void *` pointer to a `UObject` class that can be garbage collected by Unreal Engine so the  `getRendererObject()` will return a dangled pointer that is not null but is invalid and garbage.

To fix this we implemented `BeginDestroy()` in the `UTrackEntry` class to clean up the  `void *` pointer from the `TrackEntry` in this way:

```cpp
virtual void BeginDestroy() override
{
	if (entry)
	{
		entry->setRendererObject(nullptr);
	}

	Super::BeginDestroy();
}
```

**Comment by badlogic** [comment]
Cheers! I've applied and tested your fix.
