### ISSUE TITLE
[ts][pixi] Spine Tint Black alpha not working 

### ISSUE THREAD

**Issue by joshsurin-eg** [EsotericSoftware/spine-runtimes#2550]
When using the Tint black feature in Spine, the slot's alpha is not correctly following the animation. It seems the rgb2 tint is working, but not the alpha (tested both separate alpha and not, neither is working). 
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/112670645/ab0d8886-3740-4033-b996-7401ab66d3f7)

An example of an rgba2 tint black key from an exported json:
```				
"rgba2": [
    { "light": "ffffffff", "dark": "000000" },
    { "time": 0.8333, "light": "ffffffff", "dark": "ffffff" },
    { "time": 1.6667, "light": "ffffff00", "dark": "000000" }
]
```
It seems the `light` value is not properly updating the alpha of the slot. 

In this example I have 3 orange circles, the 2 smaller ones are tinted with Tint Black and are just set to go from black to white tint and also fade to 0 alpha. The tint works properly, but the alpha does not change. When I use PixiJS Devtools to change the alpha of the DarkSlotMesh, it does reduce the alpha but there is a visible bounding box artifact.

![13-06-2024-17-04-14-Arc-Arc](https://github.com/EsotericSoftware/spine-runtimes/assets/112670645/b37a70f2-a432-4a44-b2fa-dff7d3e44b9e)

The expected behavior is that the 2 circles on the left disappear fully as per this video:

![13-06-2024-17-07-24-Spine-Spine_-_spinetint](https://github.com/EsotericSoftware/spine-runtimes/assets/112670645/d34ac433-0ffa-49b8-8459-8074bcdc0956)

Not sure if this is related to #2439 or not. For what it is worth, this tint black feature works fine in PixiJs's pixi-spine implementation. 

Here is the example file:

```
{
"skeleton": { "hash": "R5qwGitXY+k", "spine": "4.2.29", "x": -391, "y": -366.57, "width": 1220.58, "height": 803.79 },
"bones": [
	{ "name": "root" },
	{ "name": "orangeball", "parent": "root", "x": -141, "y": 12.24 },
	{ "name": "orangeball2", "parent": "root", "x": 427.69, "y": 35.32, "scaleX": 1.6076, "scaleY": 1.6076 },
	{ "name": "orangeball3", "parent": "root", "x": 236.74, "y": 36.02 }
],
"slots": [
	{ "name": "orangeball", "bone": "orangeball", "color": "ffffff00", "dark": "000000", "attachment": "orangeball" },
	{ "name": "orangeball2", "bone": "orangeball2", "attachment": "orangeball" },
	{ "name": "orangeball3", "bone": "orangeball3", "dark": "000000", "attachment": "orangeball", "blend": "additive" }
],
"skins": [
	{
		"name": "default",
		"attachments": {
			"orangeball": {
				"orangeball": { "width": 500, "height": 500 }
			},
			"orangeball2": {
				"orangeball": { "width": 500, "height": 500 }
			},
			"orangeball3": {
				"orangeball": { "width": 500, "height": 500 }
			}
		}
	}
],
"animations": {
	"animation": {
		"slots": {
			"orangeball": {
				"rgb2": [
					{ "light": "ffffff", "dark": "000000" },
					{ "time": 0.8667, "light": "ffffff", "dark": "ffffff" },
					{ "time": 1.6667, "light": "ffffff", "dark": "585858" }
				],
				"alpha": [
					{ "value": 1 },
					{ "time": 1.6667, "value": 0 }
				]
			},
			"orangeball3": {
				"rgba2": [
					{ "light": "ffffffff", "dark": "000000" },
					{ "time": 0.8333, "light": "ffffffff", "dark": "ffffff" },
					{ "time": 1.6667, "light": "ffffff00", "dark": "000000" }
				]
			}
		}
	},
	"idle": {}
}
}
```

```
tinttest.png
size:108,113
filter:Linear,Linear
scale:0.3
orangeball
bounds:2,2,104,109
offsets:23,21,150,150
```

![tinttest](https://github.com/EsotericSoftware/spine-runtimes/assets/112670645/32867813-70d6-4226-8ef1-62ec5a3b5379)

**Comment by davidetan** [comment]
Thanks for reporting this and the repro project!
We'll look into that.

------

We found the problem and should be able to fix it tomorrow 👍

**Comment by davidetan** [comment]
Sorry for the delay in fixing this. We actually found the solution (see this WIP branch: https://github.com/EsotericSoftware/spine-runtimes/tree/pixi-darktint-alpha), but this issue required several changes, and it deserves to be tested very well before releasing it.

It shouldn't take more than a couple of days!

**Comment by davidetan** [comment]
We finally fixed the issue, and you can test it in version `4.2.47`, which will be released shortly!

Thanks again for opening this issue and providing us with the repro project :)

**Comment by furic** [comment]
Confirmed it's working, thanks.
