### ISSUE TITLE
[godot] v4.2.2 runtime rendering issues (PRO)

### ISSUE THREAD

**Issue by SlakkedisStudio** [EsotericSoftware/spine-runtimes#2554]
I downloaded the examples for the 4.2.2 Godot runtime for Windows without C# support, When I import the goblins example into a new scene with a simple spine sprite, it renders fine in the editor but when the project is ran it does not render at all, I tried all 3 render modes Forward+, Mobile and Compatibilty.

I think this has something to do with skins specifically cause other simple animations without skins seem to work just fine.

This is in the editor:
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/24301428/6c8a1894-f6da-444f-b4a3-ea2376266c89)

This is during runtime:
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/24301428/e0e3faf1-28a9-49e1-9a85-db21d5d605e5)

**Comment by badlogic** [comment]
This is not a bug. The goblin skeleton does not have a default skin set for the body, only for the equipment.

In the Godot inspector, you can set a preview skin that is used in the editor viewport.

<img width="1440" alt="Screenshot 2024-06-17 at 13 39 56" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/7c209699-2304-461d-990e-722f1d9255dc">

At runtime, you'll have to set the skin in code, e.g.
<img width="653" alt="Screenshot 2024-06-17 at 13 42 41" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/bb9b0c22-a950-4e2c-ba68-9afc66c37bd7">

**Comment by SlakkedisStudio** [comment]
Thank you for the response and answer, I tested and that seemed to work just fine. 

It's interesting as on Godot 4.2.1 runtime we never had to do that, it's always just showed the preview skin during runtime. I'm wondering what changed?

Thanks for clarifying!

**Comment by badlogic** [comment]
Ahh, that was actually a bug we fixed :)
