### ISSUE TITLE
[cpp] Did a memory leak occur?

### ISSUE THREAD

**Issue by yakswa** [EsotericSoftware/spine-runtimes#2563]
https://github.com/EsotericSoftware/spine-runtimes/blob/578084806dfba0da3b50e837acdf633d7e40a982/spine-cpp/spine-cpp/src/spine/SkeletonBinary.cpp#L103-L129

input and skeletonData heap is not freed
skeletonJson.cpp also

**Comment by badlogic** [comment]
Thank you, this is fixed in the 4.2 branch now.
