### ISSUE TITLE
Will spine_flutter support version 3.7 in the future?

### ISSUE THREAD

**Issue by ownlight6** [EsotericSoftware/spine-runtimes#2565]
<img width="1012" alt="image" src="https://github.com/EsotericSoftware/spine-runtimes/assets/63946721/fda04dff-a6bd-4de6-a298-da6351fe2ff4">
<img width="326" alt="image" src="https://github.com/EsotericSoftware/spine-runtimes/assets/63946721/9637eaa2-807c-4b35-b745-1ab0feeff4c8">
do I have to use webview to do that

**Comment by badlogic** [comment]
No, you need to export your skeleton from Spine Editor version 4.2.x. The runtime and editor version must match.
