### ISSUE TITLE
[spine-pixi] performance problems in spine-pixi

### ISSUE THREAD

**Issue by dragonbaba** [EsotericSoftware/spine-runtimes#2569]
I have talked about something on the email, and now here I list it especially
I correct the files of Spine-Pixi during the runtime file
In Spine-Pixi Slotmesh.ts file, UpdateFromSpineData (), The current method has a large number of this.geometry.getBuffer calls. Each time you execute this statement, you will read the current binding attribute Attrubute from the webgl. Let vertexbuffer = Geometry.getBuffer ("Atexturecoord"). Data; Then determine whether the current BUFFER condition is met, and the conditions are not met to re -assign the new Float32array to Vertexbuffer;
Secondly, in Spine.Ts, the following operation of the following operation of the following operation if (Attachment InstanceOFIONACHMENT) {} Else IF (Attachment Instancetachment) {}, Instance f is used to obtain an example, I know you are going to get it The current attachment type, so why not add it in the constructor of the regionattachment, this distinction between this.type = "region"? , Then you can change this code to const type = Attachment.type; Switch (Type) case "region": case "mesh"; case "clip" is not faster in terms of logical or execution efficiency? 
Then there is the cache of Mesh, getMeshforslot, the method you provide is to use MAP as a mapping for cache, but the MAP's duration is very large.For how to modify, I can provide the following code, in Spine
Create this.meSheScache = [];
    this.meShesnamecache = object.create (null) Modify GetMeshforslot (Slot) {
      const attachment = slot.attachment;
      const key = Attachment.name;
      const namecache = this.Meshesnamecache;
      const cache = this.Meshescache;
      const index = Reflect.get (namecache, key) || -1;
      let Mesh = Cache[Index];
      if (mesh === void 0) {{
        mesh = this.slotmeshfactory ();
        this.addchild (Mesh);
        namecache [key] = this.meshcount ++;
        cache.push (Mesh);
        return Mesh;
      } Else {
        mesh.visible = true;
        return Mesh;
      }
    }
Quickly query the index stored in the current name storage through the object, quickly obtain the Mesh stored in the array through the index, remove and modify the Mesh, and only need to modify the MeshnameCache. When traversing the Mesh each time, you only need to perform the MESH array. He is much faster than MAP. The MAP object is essentially a double -array structure. Whether it is a key inquiry or a value inquiry, it requires two -way traversal, which is very slow, and the access of object attributes is very fast, especially the modern JS engine. Essence Brother, your code habit is not very good, don't ignore the tips and warnings brought by the TS editor. Enjoying the characteristics of modern high -end APIs is to achieve the function quickly. If the elder brother has any places or places where there is any conflict, we can communicate friendly. At the same time The performance detection tool that comes is still very useful

**Comment by davidetan** [comment]
Thanks for your report, we'll look into that.
Which instrument did you use to detect these performance issues?

To summarize what you pointed out:

- locally store the buffer saved into this.geometry.getBuffer(name).data
- using an object rather than a map to store meshes
- add a type property to attachments and use that instead of instanceof to check mesh type

Is that correct?
It would be really useful for us if you could provide a benchmark example that we can try before and after code modification. Could you do that?

**Comment by dragonbaba** [comment]
[SpineExample.zip](https://github.com/user-attachments/files/16094423/SpineExample.zip)
you can download this project
if you have another question,you can tell me ~

**Comment by dragonbaba** [comment]
@davidetan

**Comment by davidetan** [comment]
> [SpineExample.zip](https://github.com/user-attachments/files/16094423/SpineExample.zip) you can download this project if you have another question,you can tell me ~

@dragonbaba Thanks for the example project.
I was doing some tests yesterday and immediately faced the performance issues due to `updateFromSpineData`. We'll definitely fix that.

However, I cannot see any particular improvement when changing from a Map to an object + array to cache meshes. In this case, using your fixes for `resetMeshes` and `getMeshForSlot` gives me a slight performance penalty.
Can you show me how you detected the performance improvement using our version of `resetMeshes` and `getMeshForSlot`?

**Comment by davidetan** [comment]
We have integrated the performance improvement fix for `updateFromSpineData` in this commit: https://github.com/EsotericSoftware/spine-runtimes/commit/52cc1d44d821e72aa7b94b4db30a63dbc9fdd561.

I'll be happy to integrate the other fix about the mesh cache as well, but as I said above, currently I cannot get any improvement with the code you provided, only a slight performance penalty.

**Comment by dragonbaba** [comment]
A slight performance loss will be a significant improvement in a large number of cases. You should carefully check the code I submitted. On the one hand, the logic of slotmesh has been modified. Compared with your previous code, there is a slight difference. You should understand that all codes have and should be determined before the loop. A certain attribute to be used should be obtained in advance as a variable. For pixi's mesh, the attributes obtained and set in its geometry are accessed by getters and setters. This operation mode should not be called frequently. Secondly, the code I submitted cannot modify the type of each Attachment. I have said before that the type of each Attchment needs to be pre-defined in the constructor. I don't think the above mentioned performance improvements are minor. For each frame, reducing the code time of tens of milliseconds is extremely effective for any game development and use, especially on mobile phones. The performance of mobile devices is much lower than that of computer devices. Then, isn't the improvement brought by better code better for mobile phones? I mentioned in the previous email communication that I am a person with strict performance and strict code. It is not that I don't trust your technology, but I hope you can do better.  I learned all my code by myself, and I checked the language specifications by myself. I am not as experienced as you programmers who have been working for many years, but I will check every line of code carefully as long as I notice abnormal execution time. Whether it is giving you suggestions or giving suggestions to pixi, I am very direct, which may make people feel uncomfortable sometimes. If you have this bad feeling, I say sorry to you 😄😄. I haven't delved into the other parts for the time being, because the code is basically OK after checking it roughly, but there is one more thing I need to point out. For the judgment of equality, === has better performance than ==. == requires implicit type conversion, while === will strictly judge whether both parties are equal. Without type conversion operations, your runtime is judged by == throughout, which is not very good. I am very happy with the tests I have conducted so far. By the way, when you are looking at my project, don't ignore the README file in the project, where I point out my test results.@davidetan

**Comment by dragonbaba** [comment]
> We have integrated the performance improvement fix for `updateFromSpineData` in this commit: https://github.com/EsotericSoftware/spine-runtimes/commit/52cc1d44d821e72aa7b94b4db30a63dbc9fdd561.
> 
> I'll be happy to integrate the other fix about the mesh cache as well, but as I said above, currently I cannot get any improvement with the code you provided, only a slight performance penalty.
However, for the current spine mesh cache, I can only think of this method. It has better performance than map in a single execution, but when the number is large enough, the gap will be magnified. There is another point. In fact, for the current mesh, if each slot is bound when the spine is initialized, the drawing order can be traversed during rendering, and the texture and data of each mesh can be modified. I want to think about how to implement this method. If it is implemented, I will also submit a new project example to you 😃

**Comment by davidetan** [comment]
I've read your README 👍

I 100% agree with you. In the render loop, any small performance improvement has to be taken into consideration. If that's the case, no doubt we'll integrate the required changes.

However, with my own machine I cannot get any performance improvement with the other changes you suggested, but a performance penalty.

I'll try to make some more tests tomorrow, maybe I'm making some mistakes. In the meantime, if you are able to show me the other performance improvement with your mesh cache implementation, it would be really appreciated.

**Comment by dragonbaba** [comment]
[spine_fix.zip](https://github.com/user-attachments/files/16107779/spine_fix.zip)
 a newer code fix here~ @davidetan

**Comment by dragonbaba** [comment]
> 我已经阅读了你的自述文件 👍
> 
> 我100%同意你的看法。在渲染循环中，任何微小的性能改进都必须考虑在内。如果是这样的话，毫无疑问，我们将整合所需的更改。
> 
> 但是，使用我自己的机器，我无法通过您建议的其他更改获得任何性能改进，而是性能损失。
> 
> 明天我会尝试再做一些测试，也许我犯了一些错误。同时，如果您能够向我展示您的网格缓存实现的其他性能改进，我们将不胜感激。

I updated the code. The previous performance was not obvious because my code was not fully called when getting it. Instead, it also called your cache, which caused it to generate twice the number of meshes. In addition, I removed the current modification because I found that the mesh stored in the previous way would have mismatched behavior. However, I modified other places to improve some performance. Each modification provides my questions and suggestions, as well as why I think it is done this way. Of course, there may also be areas where I lack understanding. If there are any problems, I hope you can correct me. I am happy to learn and understand. Learning makes me happy!

**Comment by davidetan** [comment]
I did more tests today and I'm sorry to say that there are no performance improvements with your latest modifications.

I spawned 1000 spineboys, waited 10 seconds to be sure everything was loaded correctly, captured the frametime and number of ticks for 60 seconds.
Then I executed the test 10 times and averaged the numbers.

The test **without** your modifications resulted in:
- ticks: 879
- frametime: 72.09

The test **with** your modifications resulted in:
- ticks: 836
- frametime: 75.90

If you are really convinced your modifications  benefits, please share a test that we can run, where performance is captured more reliably.
You can also fork and make a PR with your modifications and the reproducible profiling test.
