### ISSUE TITLE
[spine-pixi] Memory leak, spine object not destroyed properly

### ISSUE THREAD

**Issue by JBrinken-ignition** [EsotericSoftware/spine-runtimes#2571]
Hello, I'd like to report a bug.
The destroy method is not removing Spine object properly, it stays in memory. I checked and turns out references are not cleared.

![destroy1](https://github.com/EsotericSoftware/spine-runtimes/assets/80957628/7be49d03-ca42-4c76-ad7f-d28ab37047b3)

For comparison, this is how it's done in pixi-spine library:

![destroy2](https://github.com/EsotericSoftware/spine-runtimes/assets/80957628/89c4e6e8-ac14-4395-b4e4-7cd640eb2920)

**Comment by dragonbaba** [comment]
The destruction of spine depends on the setting of its options. The setting of pixi-spine is too complicated. You only need to write destroy({children:true}) on the parent of spine when destroy occurs. All children will destroy their children. Do you understand?

**Comment by davidetan** [comment]
> Hello, I'd like to report a bug. The destroy method is not removing Spine object properly, it stays in memory. I checked and turns out references are not cleared.
> 
> ![destroy1](https://private-user-images.githubusercontent.com/80957628/346099819-7be49d03-ca42-4c76-ad7f-d28ab37047b3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODUwMDUsIm5iZiI6MTcyMDE4NDcwNSwicGF0aCI6Ii84MDk1NzYyOC8zNDYwOTk4MTktN2JlNDlkMDMtY2E0Mi00Yzc2LWFkN2YtZDI4YWIzNzA0N2IzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDEzMDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNmExMTIyNDY0MDQ0NmU1OThjMDI3OTZmODZlYzc0NDFiNTczM2Q3ZWI5NGFhZDFjOWRjMjJiYzgwN2Q5YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iUEALu99jneCDJ2LSfYaWJ4ACA93Do-0ow-ZmXBaYuw)
> 
> For comparison, this is how it's done in pixi-spine library:
> 
> ![destroy2](https://private-user-images.githubusercontent.com/80957628/346101827-89c4e6e8-ac14-4395-b4e4-7cd640eb2920.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODUwMDUsIm5iZiI6MTcyMDE4NDcwNSwicGF0aCI6Ii84MDk1NzYyOC8zNDYxMDE4MjctODljNGU2ZTgtYWMxNC00Mzk1LWI0ZTQtN2NkNjQwZWIyOTIwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDEzMDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNzIwZmJkNTkzMWFkNDcyMTM2MWU1YjQ0NWU5YzEzOGIwYmM5NzAyMzJjYmIzODg5YjAyZWJhNGY5MmJjNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WKjfTznzkbobQMm1bjHYG5vmcoCd3FNv7loVlGwffbI)

Thanks for reporting this. We'll look into that 👍

**Comment by JBrinken-ignition** [comment]
> The destruction of spine depends on the setting of its options. The setting of pixi-spine is too complicated. You only need to write destroy({children:true}) on the parent of spine when destroy occurs. All children will destroy their children. Do you understand?

Sorry, I should've been more clear. The part I was referencing in pixi-spine's destroy method was that before calling super.destroy(options), they're setting class variables to null. 

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/80957628/1f7634d8-71ec-41f6-b041-f673e8751eee)

That is to ensure the object and its children can be garbage collected. In case of spine-pixi's destroy method, passing {children: true} isn't enough if object holds references to its children.

**Comment by davidetan** [comment]
The memory leak was due to not removing the object from the shared ticker when `autoUpdate` is true (default).
The ticker was retaining the destroyed objects.

Thanks again for reporting this! :)

**Comment by dragonbaba** [comment]
> > 脊柱的破坏取决于其选项的设置。pixi-spine的设置太复杂了。当 destroy 发生时，您只需要在主干的父级上写入 destroy（{children：true}）。所有的孩子都会毁掉他们的孩子。你明白吗？
> 
> 对不起，我应该说得更清楚。我在 pixi-spine 的 destroy 方法中引用的部分是，在调用 super.destroy（options） 之前，他们将类变量设置为 null。
> 
> ![image](https://private-user-images.githubusercontent.com/80957628/346143810-1f7634d8-71ec-41f6-b041-f673e8751eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTE2NDYsIm5iZiI6MTcyMDE5MTM0NiwicGF0aCI6Ii84MDk1NzYyOC8zNDYxNDM4MTAtMWY3NjM0ZDgtNzFlYy00MWY2LWIwNDEtZjY3M2U4NzUxZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE0NTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYmVjNjMxOWM1ZDNkZTFmNjRmYTZiMzFmZTVlMzZlOGVhNmJkNWRiNGJhZjJjZTQ0ZWIyMGVhMWMyMGU0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.45gSqExPlyX447K4ODnkqeLotn0-ayaAJs_uFIe8LwE)
> 
> 这是为了确保对象及其子对象可以被垃圾回收。在 spine-pixi 的 destroy 方法中，如果对象包含对其子项的引用，则传递 {children： true} 是不够的。

you are wrong,when spine is destroy ,spine's parent remove spine 's reference then javascript gc system can delete spine .do you know?

**Comment by dragonbaba** [comment]
> > 脊柱的破坏取决于其选项的设置。pixi-spine的设置太复杂了。当 destroy 发生时，您只需要在主干的父级上写入 destroy（{children：true}）。所有的孩子都会毁掉他们的孩子。你明白吗？
> 
> 对不起，我应该说得更清楚。我在 pixi-spine 的 destroy 方法中引用的部分是，在调用 super.destroy（options） 之前，他们将类变量设置为 null。
> 
> ![image](https://private-user-images.githubusercontent.com/80957628/346143810-1f7634d8-71ec-41f6-b041-f673e8751eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTE2NDYsIm5iZiI6MTcyMDE5MTM0NiwicGF0aCI6Ii84MDk1NzYyOC8zNDYxNDM4MTAtMWY3NjM0ZDgtNzFlYy00MWY2LWIwNDEtZjY3M2U4NzUxZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE0NTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYmVjNjMxOWM1ZDNkZTFmNjRmYTZiMzFmZTVlMzZlOGVhNmJkNWRiNGJhZjJjZTQ0ZWIyMGVhMWMyMGU0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.45gSqExPlyX447K4ODnkqeLotn0-ayaAJs_uFIe8LwE)
> 
> 这是为了确保对象及其子对象可以被垃圾回收。在 spine-pixi 的 destroy 方法中，如果对象包含对其子项的引用，则传递 {children： true} 是不够的。

javascript gc system know spine has none referened by others,though,when spine destroy children ,spine will remove child reference ,so only need clear mesh cache ,another thing is unnecessayr!

**Comment by davidetan** [comment]
@JBrinken-ignition Released in 4.2.50.

**Comment by JBrinken-ignition** [comment]
@davidetan Thank you!
@dragonbaba Ah, okay, got it! I'm just used to having to clear references in pixi
