### ISSUE TITLE
[unity] Quotation marks generated in Skeleton Prefab Mesh names causes Unity Search Indexing issues

### ISSUE THREAD

**Issue by DeanIsseyegh** [EsotericSoftware/spine-runtimes#2572]
When Unity Spine imports and generates Mesh Filter's Mesh names, it does so with quotation marks using the format `Skeleton Prefab Mesh \"{0}\"`. This causes Unity's Search Index Manager to not be able to properly process the path of the prefab, making the prefab and its sub-components unsearchable.

See this code which generates the quotes: https://github.com/EsotericSoftware/spine-runtimes/blob/a1f077d43c4f8d55a85d87ae5dd79aa6296aed33/spine-unity/Assets/Spine/Editor/spine-unity/Editor/Utility/SpineEditorUtilities.cs#L131C5-L131C70

Could we possibly replace the usage of quotation marks with brackets instead?

Unity Version: 2021.3.21f

To reproduce, you can:
1. Open any Unity project with a Spine prefab and a generated Mesh on it
2. Open up the Search Index Manager via the toolbar by going to Window -> Search - Index Manager
3. (Optional) Delete any existing search indexes for a clean test
4. In the Includes section, choose a File and select the prefab directly, click Save/Build
5. (Optional) Under Options, tick Sub objects
6. Observe errors in the Unity console stating "Failed to build search index for <AssetPathHere>.prefab" with a stack trace pointing to System.IO.Path.GetFileName() exceptions and illegal characters in path. Please note these errors only seem to sometimes surface to the Unity console
7. Press Ctrl + K to open the Advance Search window, and notice how your prefab with mesh filter is unsearchable and does not appear

**Comment by HaraldCsaszar** [comment]
@DeanIsseyegh Thanks for reporting! The above commit fixes the issue.
A new spine-unity 4.2 unitypackage is available for download:
https://esotericsoftware.com/spine-unity-download

**Comment by DeanIsseyegh** [comment]
That was very quick! Much appreciated!
