### ISSUE TITLE
[cpp] Crash because of negative setSize in SkeletonClipping.cpp

### ISSUE THREAD

**Issue by kefky** [EsotericSoftware/spine-runtimes#2579]
Details + sample in the forum here: https://fr.esotericsoftware.com/forum/d/26530-spine-cpp-crash-because-of-buggy-allocation-in-skeletonclippingcpp

Some clipping computations can result in a call to `Vector::setSize()` with a negative size. Since it expects a `size_t`, which is unsigned, this will try to realloc more than 4GBs of memory and break.

**Comment by badlogic** [comment]
Thanks for the repro! I'll get to this this week.
