### ISSUE TITLE
[spine-pixi] Can't create empty atlas

### ISSUE THREAD

**Issue by daserra** [EsotericSoftware/spine-runtimes#2581]
Hi everyone,
In the previous version I was able to instantiate an empty atlas and fill it with my textures using the following code:
`private readonly _atlas = new TextureAtlas();`
`const loadedSprites = await Assets.load(this._spriteSheetsNames); `
`for (const loadedSprite of Object.values(loadedSprites)) { `
`  this._atlas.addTextureHash(loadedSprite.textures, true); `
`}`
Now, with the latest update, the addTextureHash method was deprecated and now atlasText as a parameter is required to instantiate the TextureAtlas. Is there any way to achieve the same dynamic atlas creation as in the previous version?

Thank you!

**Comment by davidetan** [comment]
Hello :)

> In the previous version I was able to instantiate an empty atlas and fill it with my textures using the following code:
private readonly _atlas = new TextureAtlas();
const loadedSprites = await Assets.load(this._spriteSheetsNames); 
for (const loadedSprite of Object.values(loadedSprites)) { 
  this._atlas.addTextureHash(loadedSprite.textures, true); 
}

Which runtime are you referring to? `spine-pixi` is pretty recent and has never had a `addTextureHash` method.
Is it possible you are referring to `pixi-spine`?

> Now, with the latest update, the addTextureHash method was deprecated and now atlasText as a parameter is required to instantiate the TextureAtlas. Is there any way to achieve the same dynamic atlas creation as in the previous version?

If you really want to fill a `TextureAtlas` by yourself, you can instantiate a `TextureAtlas` passing an empty string. Then, it will be your responsibility to fill it with initialized `pages` and `regions`, and to assign the `rendererObject` (texture) to the region.

Can you describe your goal better?

**Comment by daserra** [comment]
Hi @davidetan, thanks for the reply.

My goal is the following, I'm trying to migrate my project to pixiv8 and also migrate to spine 4.2, I was previously using the version 3.8. 
In my previous project I'm not using .atlas files to load my animations I was only using the .json and the textures. For backwards compatibility reason I need to find a way to load my animation without having .atlas file.
When we look the previous runtime I could achieve that because that was the implementation of it.
![image](https://github.com/user-attachments/assets/318e9f53-c715-41f4-920e-6f5b4aae11d7)

I will try to do like you said using empty string.

Thank you!

**Comment by davidetan** [comment]
`addTexture` seems to do the necessary things to create a new page in the atlas.
However, that might not be very efficient in terms of performance at runtime.
As far as I understood, you're loading a separate texture for each attachment. If that's the case, it might significantly increase the number of draw calls.

Refer to [this paragraph](https://en.esotericsoftware.com/spine-runtime-skins#Creating-attachments) in the runtime guide that might give you some hints on how to create attachments programmatically.
