### ISSUE TITLE
[ts][pixi] v8 support

### ISSUE THREAD

**Issue by davidetan** [EsotericSoftware/spine-runtimes#2584]
The goal of this issue is to add to `spine-pixi` support for PixiJS v8.

**Comment by yev-stash** [comment]
@davidetan  I don't see spine-pixi in this repo anymore even for pixi JS v7. Is it in purpose?

**Comment by yev-stash** [comment]
oh ok I see all web spine runners are under spine-ts now. I think you need to update documentation page https://esotericsoftware.com/spine-pixi. Because current page is not found anymore

**Comment by alvov-evo** [comment]
Just in case, there's this PR: [Add PixiJS v8 support to spine](https://github.com/EsotericSoftware/spine-runtimes/pull/2641)

**Comment by davidetan** [comment]
The runtime was finally released! Read more in [this](https://esotericsoftware.com/blog/spine-pixi-v8-runtime-released) blog post.

**Comment by jeth88** [comment]
I am rooting for this update. Keep it up guys! :)
