### ISSUE TITLE
[libgdx]How to set the black background color to transparent？

### ISSUE THREAD

**Issue by csbz17027** [EsotericSoftware/spine-runtimes#2585]
![1721790521102](https://github.com/user-attachments/assets/1dc217b9-7e94-4f4e-8f0d-6936f25d1583)
My animation image looks like this. I want to make the black background transparent when running this animation. How should I proceed?

**Comment by badlogic** [comment]
Please use the forums for general questions: https://esotericsoftware.com/forum

You will have to modify the source image transparency in an image editor. Spine can not help you with that.
