### ISSUE TITLE
[ts][webgl] `this.lastTexture.bind` is not a function

### ISSUE THREAD

**Issue by Lotes** [EsotericSoftware/spine-runtimes#2588]
Hi!

I am quite new to Spine. So I hope it is just an usage error.

I am using the Typescript runtime `@esotericsoftware/spine-webgl` version `4.2.56`.
I picked out  the `SpineCanvas` class to render an animation.

My render loop looks like this:

```ts
//inside of a class `App` in method `render`
canvas.clear(0, 0, 0, 1);
canvas.renderer.begin();
canvas.renderer.circle(true, 0,0,100, Color.BLUE); //gets drawn
canvas.renderer.drawSkeleton(skeleton);            //not drawn
canvas.renderer.end();                             //<--error was thrown
```

In the last line there was thrown an error by the `PolygonBatcher`, `Uncaught TypeError: this.lastTexture.bind is not a function`:

```ts
//from PolygonBatcher.ts
flush() {
    if (this.verticesLength == 0)
        return;
    if (!this.lastTexture)
        throw new Error("No texture set.");
    if (!this.shader)
        throw new Error("No shader set.");
    this.lastTexture.bind();         //Uncaught TypeError: this.lastTexture.bind is not a function
    this.mesh.draw(this.shader, this.context.gl.TRIANGLES);
    this.verticesLength = 0;
    this.indicesLength = 0;
    this.mesh.setVerticesLength(0);
    this.mesh.setIndicesLength(0);
    this.drawCalls++;
    PolygonBatcher.globalDrawCalls++;
}
```

`lastTexture` here is of type `CanvasTexture`. I cannot see any `bind` method in the class hierarchy.

Is this a bug?

If not, I can provide more reproduction steps (it would take me some amount of time to extact the code to an example project).

**Comment by davidetan** [comment]
Hello @Lotes and thanks for reporting this.

`lastTexture` shouldn't be of type `CanvasTexture`, but of type `GLTexture`.
`CanvasTexture` belongs to `spine-canvas`, not `spine-webgl`.

This suggests to me that you have imported `AssetManager` from `spine-canvas` and not from `spine-webgl`. I guess that happened due to your IDE suggesting `AssetManager` twice, one from `spine-canvas` and the other from `spine-webgl`.

Does it solve your problem?

**Comment by Lotes** [comment]
This makes so much sense! Thank you.

I will evaluate this later this day, but I think you are absolutely right. I was working with React and implemented a solution for Canvas first and later for WebGL. The loading process was decoupled by me into a preloading component and a kind of player component, so I lost track of the used asset loader. The preloader indeed uses the Canvas approach. I totally missed this fact. So I actually need two different preloaders depending on the runtime I want to use finally.

I will already close this issue. I think the answer will definitely solve my issue.

**Comment by Lotes** [comment]
Works! Thanks.
