### ISSUE TITLE
[unity] error in URP's blend shaders when MainLight is disabled

### ISSUE THREAD

**Issue by Saseska** [EsotericSoftware/spine-runtimes#2592]
I noticed a bug in Spine unity urp shaders for versions 4.2 (2024-07-09) and 4.1 (2023-10-26):
When using Universal Render Pipeline with Main Light and Additional Lights disabled, an error occurs - in the editor everything looks fine, but in the game build I get errors like "Universal Render Pipeline/Spine/Blend Modes/Skeleton Additive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)" and purple rects instead of expected animation. After commenting UsePass in Blend Modes shaders or simply enabling the Main Light option in the rendering pipeline, the errors disappear and the additives look as expected. Shaders on commit a08c7dd41981a0bd63597d3455ab0fcf36cd3470 with explicit ShadowCaster pass also work as expected

**Comment by HaraldCsaszar** [comment]
@Saseska Thanks for reporting and sorry for the troubles! We've just fixed this issue for the three URP blend mode shaders `Universal Render Pipeline/Spine/Blend Modes/*`.
A new URP Shaders UPM package is available for download:
https://esotericsoftware.com/spine-unity-download
