### ISSUE TITLE
[Unity] error has invalid dependencies or related test packages:

### ISSUE THREAD

**Issue by yyh9488** [EsotericSoftware/spine-runtimes#2593]
[Package Manager Window] Error adding package: https://github.com/EsotericSoftware/spine-runtimes.git?path=spine-unity/Assets/Spine#4.2.
Unable to add package [https://github.com/EsotericSoftware/spine-runtimes.git?path=spine-unity/Assets/Spine#4.2]:
  Package com.esotericsoftware.spine.spine-unity@https://github.com/EsotericSoftware/spine-runtimes.git?path=spine-unity/Assets/Spine#4.2 has invalid dependencies or related test packages:
    com.esotericsoftware.spine.spine-csharp (dependency): Cannot fetch authorization code. User access token is expired or invalid. You may need to sign out and sign in again.

**Comment by HaraldCsaszar** [comment]
Did you install the spine-csharp package beforehand? Note that the order is important. There is no automatic dependency resolution (automatic download) of the spine-csharp package.
See the installation documentation here:
https://esotericsoftware.com/spine-unity-installation#Via-Unity-Package-Manager
If the problem persists thereafter, we're happy to re-open the ticket, then please describe what steps you performed that failed.
