### ISSUE TITLE
iOS use cocopods has some problem

### ISSUE THREAD

**Issue by juntutu** [EsotericSoftware/spine-runtimes#2602]
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Spine iOS Example' do
 # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!

 pod 'Spine', :podspec => 'https://raw.githubusercontent.com/EsotericSoftware/spine-runtimes/4.2/Spine.podspec'
 pod 'SpineCppLite', :podspec => 'https://raw.githubusercontent.com/EsotericSoftware/spine-runtimes/4.2/SpineCppLite.podspec'
 pod 'SpineShadersStructs', :podspec => 'https://raw.githubusercontent.com/EsotericSoftware/spine-runtimes/4.2/SpineShadersStructs.podspec'
end
My project does not use use_frameworks when using cocopods, it will crash after integration, how to solve?

**Comment by badlogic** [comment]
Please provide more information, such as error logs. I'll reopen the issue then.
