### ISSUE TITLE
[ts][threejs] Custom shader ignores light and shadows

### ISSUE THREAD

**Issue by davidetan** [EsotericSoftware/spine-runtimes#2606]
As reported by a user in [this forum thread](https://esotericsoftware.com/forum/d/26699-threejs-%E3%81%AB%E3%81%8A%E3%81%84%E3%81%A6-skeletonmesh-%E3%81%AB%E5%85%89%E3%81%A8%E5%BD%B1%E3%82%92%E9%81%A9%E7%94%A8%E3%81%97%E3%81%9F%E3%81%84), the custom shader we use to render our meshes does not take into consideration lights and shadows.

It seems that using the [`onBeforeCompile`](https://threejs.org/docs/index.html#api/en/materials/Material.onBeforeCompile) callback is possible to modify the threejs base shader rather than replacing it.

See this official [example](https://threejs.org/examples/?q=modified#webgl_materials_modified) ([code here](https://github.com/mrdoob/three.js/blob/master/examples/webgl_materials_modified.html#L86)).

**Comment by HarmHoeksema** [comment]
Is this shadow related?
I couldn't get this to work in Pixi Version 8 + this Spine version 
Old working example custom Spine implementation + Pixi version 7:
https://pixijs.io/examples-v5/#/filters-advanced/pixie-shadow-filter.js

Is somebody able to get this shadow to work on the latest version of Spine?

**Comment by davidetan** [comment]
> Is this shadow related? I couldn't get this to work in Pixi Version 8 + this Spine version Old working example custom Spine implementation + Pixi version 7: https://pixijs.io/examples-v5/#/filters-advanced/pixie-shadow-filter.js
> 
> Is somebody able to get this shadow to work on the latest version of Spine?

That's not related at all. It's definitely better to open a new issue about that.

**Comment by davidetan** [comment]
This has been released with 4.2.67. Big changes happened in `spine-threejs` that can be read here: https://esotericsoftware.com/blog/spine-threejs-runtime-update
