### ISSUE TITLE
[ts] white screen in some mobiles

### ISSUE THREAD

**Issue by amirking59** [EsotericSoftware/spine-runtimes#2613]
some times in mobile some of our spines rendered all white 

![photo_2024-08-28_03-28-10](https://github.com/user-attachments/assets/fc3b547c-1b08-4239-a9a6-2d3490435f30)

on desktop its completly ok

**Comment by badlogic** [comment]
We can not possibly identify the issue given your information. Please provide more information. 

- What exact runtime (WebGL, Player, Canvas, Phaser, Pixi) you are using
- What device, operating system (and version), and browser (and version)
- The assets (.skel, .json, .atlas, .png, ideally the Spine Project) that produce the error
- A simple project that reproduces the issue, e.g. a .html file that shows how you are loading, animating, and rendering the asset, resulting in the error.

**Comment by amirking59** [comment]
sorry for lack of information 

i use @esotericsoftware/spine-player

it happends to all low end mobiles time to time

i want to know that is it normal to happen in lower end devices?
is it related to using react ?
or high res spine png ?
i found an article about performance of spine and it said there is limitation in canvas count 
but it only happens on lower end devices not all of the devices.

 sorry but i cant share any spines or files 
 thanks for your time

**Comment by badlogic** [comment]
On low end devices, you can only have 4 spine-players at a time. That's a limitation by the browsers. If you have more than that, low end devices will likely not be able to render things, which would explain your issue.

High-res texture atlases can also be an issue for low end devices. To stay within save limits, make sure the atlas page images are no bigger than 1024x1024.

We are working on a new component that should allow you to render any number of skeletons, each in its own web component.
