### ISSUE TITLE
[cpp] skeletonJson version mismatch might cause a memory leak.

### ISSUE THREAD

**Issue by yakswa** [EsotericSoftware/spine-runtimes#2622]
I already reported https://github.com/EsotericSoftware/spine-runtimes/issues/2563 and fixed

https://github.com/EsotericSoftware/spine-runtimes/blob/c9c6b9821163890c44ae142750afbed0826ad5e9/spine-cpp/spine-cpp/src/spine/SkeletonBinary.cpp#L121-L131

But that delete codes are need to apply SkeletonJson.cpp  
root and skeletonData
https://github.com/EsotericSoftware/spine-runtimes/blob/c9c6b9821163890c44ae142750afbed0826ad5e9/spine-cpp/spine-cpp/src/spine/SkeletonJson.cpp#L143-L161

thank you

**Comment by badlogic** [comment]
Sorry for the oversight. This is now fixed in the 4.2 branch.
