### ISSUE TITLE
[unity] Incorrect package dependencies

### ISSUE THREAD

**Issue by c3-hoge-fuga-piyo** [EsotericSoftware/spine-runtimes#2628]
`spine-unity Runtime` depends on the following packages, which need to be added to the dependencies in package.json.

- `com.unity.ugui`
- `com.unity.modules.animation`
- `com.unity.modules.physics`
- `com.unity.modules.physics2d`

**Comment by HaraldCsaszar** [comment]
@c3-hoge-fuga-piyo Thanks for reporting.
