### ISSUE TITLE
Runtime for other language

### ISSUE THREAD

**Issue by bp74** [EsotericSoftware/spine-runtimes#264]
Hi, i was planing to do a Dart runtime for Spine based on the ActionScript runtime and also an implementation for my render engine called StageXL. After reading your license it looks to me that i'm not allowed to do this without your written permission. I do have a license for Spine because i was one of the backers on kickstarter. So i wonder what i can do and what i can't do!?

.... Without the written permission of Esoteric Software (typically granted by licensing Spine), you may not (a) modify, translate, adapt or otherwise create derivative works, improvements of the Software or develop new applications using the Software ....

**Comment by pharan** [comment]
@bp74 
Thanks for sharing! Feel free to post this in [the official forum](http://esotericsoftware.com/forum/viewforum.php?f=3) if the project is still alive! You get more visibility there.

**Comment by bp74** [comment]
Hi,

Thanks for your response. Yes the project is very much alive and i've posted the runtime on the Spone forum already: http://esotericsoftware.com/forum/StageXL-3488

Best Greetings, 
Bernhard
