### ISSUE TITLE
[godot] Request: SpineSprite and friends that inherit from Node3D, like Sprite3D

### ISSUE THREAD

**Issue by karljs** [EsotericSoftware/spine-runtimes#2654]
Godot has a node called `Sprite3D` that puts a 2D sprite into a 3D world.  Is it possible to have the Spine equivalent nodes that function just like the ones we have now, but inherit from Node3D?  It would unlock the ability to build 2.5D games using Spine + Godot.

**Comment by badlogic** [comment]
Yes, see here:
https://github.com/EsotericSoftware/spine-runtimes/issues/2135

:) I'm currently finishing spine-godot as a GDExtension and will then look into `SpineSprite3D`.
