### ISSUE TITLE
[godot] Can only export Android for arm64-v8a

### ISSUE THREAD

**Issue by SanteriLoitomaa** [EsotericSoftware/spine-runtimes#2657]
I'm using the latest releases of spine-godot 4.3 for Windows and export templates. I have an Android export using gradle build and all architectures selected. The result is an AAB with only arm64-v8a data inside. Is this a problem with the templates or Godot in general?

**Comment by SanteriLoitomaa** [comment]
Looked into this more and it seems like the libs for the other architectures are entirely missing from the Android export templates' AAR files. Is there a reason why they are not included?

**Comment by SanteriLoitomaa** [comment]
Started to look into building the templates myself and noticed that the shell script included in this repo seems to be outdated. The scons arch arguments in Godot's own documentation are `arm32` and `arm64` but they are `armv7` and `arm64v8` in the shell script.

Edit: Also the shell script doesn't seem to use the `generate_apk=yes` argument for the final scons build like the 4.3 Godot documentation recommends.

**Comment by badlogic** [comment]
Eeks, good catch. I've fixed up the `build-templates-v4.sh` script to generate both armv7 and arm64 binaries and corresponding APKs We'll refrain from building x86 binaries. That can be achieved by cloning this repository, enabling workflows, modifying the `build-templates-v4.sh` script to add that arch, and using the GitHub workflow to build the templates (or run it locally with Android SDK installed).

**Comment by SanteriLoitomaa** [comment]
> Eeks, good catch. I've fixed up the `build-templates-v4.sh` script to generate both armv7 and arm64 binaries and corresponding APKs We'll refrain from building x86 binaries. That can be achieved by cloning this repository, enabling workflows, modifying the `build-templates-v4.sh` script to add that arch, and using the GitHub workflow to build the templates (or run it locally with Android SDK installed).

Thanks for the fix. Already got to the point where I can manually build all the archs but I should probably look into utilizing the ready workflows as building everything myself seems to take a lot of my time and space from my disk.
