### ISSUE TITLE
version4.2.6  Android use SpineView  happen like this

### ISSUE THREAD

**Issue by huanghongfu** [EsotericSoftware/spine-runtimes#2661]
![image](https://github.com/user-attachments/assets/2e10b2d2-beee-464f-8654-b5c86e9eb28c)

**Comment by huanghongfu** [comment]
his face not good

**Comment by davidetan** [comment]
Are you using premultiplied alpha textures? Read the warning regarding pma textures on [this paragraph](https://esotericsoftware.com/spine-android#Exporting-for-spine-android) of the documentation.

**Comment by huanghongfu** [comment]
> Are you using premultiplied alpha textures? Read the warning regarding pma textures on [this paragraph](https://esotericsoftware.com/spine-android#Exporting-for-spine-android) of the documentation.

![image](https://github.com/user-attachments/assets/8aad54e3-8ec6-401b-b768-e4d4fbbbb033)

**Comment by huanghongfu** [comment]
Android  how to use premultiplied this method？

**Comment by davidetan** [comment]
> Android how to use premultiplied this method？

You've just sent a screenshot of the paragraph I mention. It clearly states that: **The spine-android runtime currently does not support atlases exported using pre-multiplied alpha**.

**Comment by huanghongfu** [comment]
Thank you for your response
