### ISSUE TITLE
[spine-ios] can't use `SkeletonBounds` for doing hit detection

### ISSUE THREAD

**Issue by kikiloveswift** [EsotericSoftware/spine-runtimes#2666]
Class `SkeletonBounds` in pod SpinCppLite, path `spine-cpp/spine-cpp/include/spine/SkeletonBounds.h`

**Function:**
```
void update(Skeleton &skeleton, bool updateAabb);
```

**Question:**
this function need `Skeleton`, but `Spine.Generated.swift` has set to internal level.

`Spine.Generated.swift`
![image](https://github.com/user-attachments/assets/14721a44-798f-45c3-9110-c656bb97927d)

**Suggestion**
May be `SkeletonBoundsWrapper` is wannted.

**Comment by kikiloveswift** [comment]
@badlogic please support `SkeletonBounds ` for spine-ios.

**Comment by kikiloveswift** [comment]
I did it, and I support it.
I don't believe you guys actually like the spine-ios project. This issue has been open for a long time, with no responses and not even a single update. It's quite disheartening.

**Comment by badlogic** [comment]
You've opened this issue a week ago, a week where I was sick. We do care about the spine-ios runtimes just like we care about all the others. We are a small team, and sometimes things take time.

**Comment by kikiloveswift** [comment]
> You've opened this issue a week ago, a week where I was sick. We do care about the spine-ios runtimes just like we care about all the others. We are a small team, and sometimes things take time.

Sorry to hear that. We're also paid enterprise users of Spine, and we really care about the quality and functionality of the spine-ios SDK. We highly value Spine's product. I took a close look at the code logic in `spine-cpp/spine-cpp-lite/spine-cpp-lite-codegen.py`, so I understand how Spine interacts with SpineCppLite. I’ve managed to get it working, but while using it, I noticed a clear issue in `SkeletonBinary.cpp` related to `AttachmentType_Boundingbox`. I've already submitted a PR (https://github.com/EsotericSoftware/spine-runtimes/pull/2668) and sent an email about it, so please take a look and review it when you can.

**Comment by badlogic** [comment]
I've exposed SkeletonBound and fixed the issue in SkeletonBinary. Thanks for reporting.
