### ISSUE TITLE
[godot] The same animation cannot be played back consecutively on the same track in AnimationPlayer

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-runtimes#2670]
**Description:**
There are times when you want the same animation to run continuously on the same track in AnimationPlayer, not in a loop, but with a slight pause like this:
![Screenshot 2024-11-06 at 12 07 50](https://github.com/user-attachments/assets/a8c004d7-34e1-48f3-bd06-a31604558af8)
When this is previewed with the play button in the Animation dock, it plays correctly, but when the scene is run, only the first animation plays, and the next animation does not play correctly. Here is a video you can see the problem:
https://github.com/user-attachments/assets/9124bce3-7539-4b61-9406-46de5a7ce0b6

**Expected behavior:**
All animations on the same track play correctly, even if the same animation is set consecutively on the same track.

**Steps to reproduce:**
1. Download the attached .zip file: [The same animation cannot be played back consecutively on the same track in AnimationPlayer.zip](https://github.com/user-attachments/files/17641228/The.same.animation.cannot.be.played.back.consecutively.on.the.same.track.in.AnimationPlayer.zip)
2. Open the project contained in the unpacked zip with Godot 4.3. (It should open automatically, but if not, open `res://Animation-player/animation-player.tscn`.)
3. Select the `AnimationPlayer` node in the Scene Dock, then select the `Test` animation in the Animation Dock:
![Screenshot 2024-11-06 at 12 21 21](https://github.com/user-attachments/assets/444263d0-8d18-4934-85c3-1161f3037253)
5. Play the animation using the play button, and confirm that the `shoot` animation plays four times on Track 0 and once on Track 
6. Run the current scene. You can see that after the `shoot` animation is first played once on track 0, nothing happens for a while, and only after about 3 seconds the `shoot` animation set on track 1 is played.

**The version that can reproduce this issue:**
Godot 4.3 (Other versions have not yet been tested.)

**This issue was reported in the following thread on the forum:**
https://esotericsoftware.com/forum/d/27217-animationplayer-bug

**Comment by badlogic** [comment]
I can not reproduce this using the latest spine-godot and Godot 4.3, build from source, nor with the latest spine-godot build of 4.3 from our website at https://esotericsoftware.com/spine-godot

https://github.com/user-attachments/assets/b36a3018-eb6d-4958-a989-4037c7f1b11f

**Comment by badlogic** [comment]
Nevermind, I didn't read step 5. Can reproduce. Investigating.

**Comment by badlogic** [comment]
In `update_animation_state`, we check if the current TrackEntry name is the same as the animation name that was keyed in the Godot AnimationPlayer. If that's the case, we do nothing. This won't work with two keys that key the same animation.

Fix was to switch the AnimationPlayer tracks to discrete update mode, then react to name or loop track changes directly.
