### ISSUE TITLE
[ts][pixi-v8] Slot objects render with a delay

### ISSUE THREAD

**Issue by SerG-Y** [EsotericSoftware/spine-runtimes#2675]
Hi guys, first of all, thanks for adding Pixi v8 support, great job!

I encountered a few issues when migrating from PixiJS v7 to v8 (all of these worked fine with PixiJS v7 and pixi-spine v7):
- Slot objects render with a delay. You can notice the "PLAY" text blinking, as the slot object becomes visible 1–2 frames later than the animation itself.
- Unable to destroy the animation within the complete callback.
- Unable to create a new animation within the complete callback.

I have prepared an example demonstrating all these issues:
v8:
https://codesandbox.io/p/sandbox/9yh9cf

working example v7: 
https://codesandbox.io/p/sandbox/k8jdnc

**Comment by davidetan** [comment]
Hello and thanks for trying the new runtime!

The issues seem quite clear and I have already an idea about what could cause the the lasts two.

I'll let you know as soon as I fixed them!

**Comment by davidetan** [comment]
We just released 4.2.65 that should address all three issues.
You probably need to move the destroy after the new button has been created to avoid an empty frame.

**Comment by Serhiy-Y** [comment]
@davidetan Thanks a lot!
Also, I saw your commit [fb3855a](https://github.com/EsotericSoftware/spine-runtimes/commit/fb3855ad6588d5d8ed5cfb5991a13fd858af9a29), great job!
