### ISSUE TITLE
[ts][pixi-v8] Slot objects are no longer interactable

### ISSUE THREAD

**Issue by Serhiy-Y** [EsotericSoftware/spine-runtimes#2683]
Hey, pixiObject becomes uninteractable after being added to the slot using `animation.addSlotObject(slotName, pixiObject);`.
The reason for this is that you set `container.includeInBuild = false;` here
https://github.com/EsotericSoftware/spine-runtimes/blob/000df0702795186e7702b9e45463f6ce04448acb/spine-ts/spine-pixi-v8/src/Spine.ts#L727

and here
https://github.com/EsotericSoftware/spine-runtimes/blob/000df0702795186e7702b9e45463f6ce04448acb/spine-ts/spine-pixi-v8/src/SpinePipe.ts#L148

PixiJS has the following check which makes this object not interactable 
https://github.com/pixijs/pixijs/blob/fc1820cc8612d876c4ec34f03d9d7dcc4be97f54/src/events/EventBoundary.ts#L551

Is it possible to make pixiObject interactable inside the slot? (it works in v7)

**Comment by davidetan** [comment]
This might be tough, we'll see what we can do.

**Comment by davidetan** [comment]
As anticipated yesterday, preventing that check on spine-pixi side, it's not possible. This would require some hack or deep rethinking of slot objects.

We had a quick conversation with PixiJS team and they're probably going to relax that check on Pixi side, so it will require a library upgrade and hopefully that will resolve this issue.
So, many thanks (again!) to the Pixi team for being so proactive and collaborative 🎉 

We'll keep this issue open until the modification will go through.

**Comment by Zyie** [comment]
hey, we have merged this pr https://github.com/pixijs/pixijs/pull/11069 which should make spines interactable again. 
You can test it out using `npm i pixi.js@dev`

should have a proper release with this fix in soon

**Comment by davidetan** [comment]
> hey, we have merged this pr [pixijs/pixijs#11069](https://github.com/pixijs/pixijs/pull/11069) which should make spines interactable again. You can test it out using `npm i pixi.js@dev`
> 
> should have a proper release with this fix in soon

That's awesome! Thanks Zyie 🥳

**Comment by DMitev11** [comment]
Hi! @Zyie Is there a plan when would that fix be included in a stable build, therefore when would be the next stable version?

**Comment by Zyie** [comment]
> Hi! @Zyie Is there a plan when would that fix be included in a stable build, therefore when would be the next stable version?

Hey, we have 2 PR's that need to be wrapped up, then we will be doing a new release. I'm hoping this will be sorted by the end of the week

**Comment by DMitev11** [comment]
Makes sense. Thank you for the quick response!

**Comment by davidetan** [comment]
Yesterday PixiJS `8.6.0` was release. Tested this morning and interactions with slot objects work correctly 🥳 

I close this one. Feel free to reopen this if something doesn't work as expected.
