### ISSUE TITLE
[Godot] 4.3 Add thread support for web export templates

### ISSUE THREAD

**Issue by PiewieP** [EsotericSoftware/spine-runtimes#2684]
When turning 'thread support' ON in the web export preset, the export template is not found. This is from the export templates downloaded from the website.
![Screenshot 2024-11-14 144235](https://github.com/user-attachments/assets/3bf78c90-c7d2-4438-8427-77a4ae0fe3df)

I am also suspicious that the default setting ('thread support' OFF) functions as a thread support ON, because when I export my project I get the usual SharedArrayBuffer and cross origin isolation errors on Itch.io until I enable the SharedArrayBuffer support setting. This should not be necessary with this setting disabled, however.

**Comment by badlogic** [comment]
This is indeed wrong and strange. I worked on this 2 weeks ago and thought I had fixed the corresponding GitHub action. Sorry for the trouble, I'll put this on top of my todo for Monday. Thanks for reporting!

**Comment by badlogic** [comment]
Hm, the GH Action is building all web variations:

https://github.com/EsotericSoftware/spine-runtimes/actions/runs/11836184133/job/32980547259

<img width="399" alt="Screenshot 2024-11-15 at 15 04 03" src="https://github.com/user-attachments/assets/4df02f21-9919-41e9-a863-8a43b5e7bce3">

And the action that is responsible for packaging all templates and uploading them to S3 is also doing it's job.

<img width="542" alt="Screenshot 2024-11-15 at 15 04 35" src="https://github.com/user-attachments/assets/c26682c8-2726-4d07-8f4e-3e82b1a69d2b">

**Comment by badlogic** [comment]
Ok, it looks like I pushed the wrong change for the packaging task. I've amended this and queued a new job. Once this has completed (5h from now...) I'll test the resulting template and report back.

https://github.com/EsotericSoftware/spine-runtimes/actions/runs/11857874317

**Comment by PiewieP** [comment]
Any update on this?

**Comment by badlogic** [comment]
Yes, we are blocked by GitHub actions not being able to build on Windows runners anymore. Reason and solution unclear.

**Comment by badlogic** [comment]
This is now finally fixed. The GH Action build kept failing due to a change in the Windows runners and a problem in thorvg. The last run finally made it through and the export templates zip from https://esotericsoftware.com/spine-godot now includes all the web export templates.
