### ISSUE TITLE
[cpp doc improvement] cmake fetching

### ISSUE THREAD

**Issue by hsdk123** [EsotericSoftware/spine-runtimes#2699]
The current docs recommend
```
include(FetchContent)
FetchContent_Declare(
 spine-runtimes
 GIT_REPOSITORY https://github.com/esotericsoftware/spine-runtimes.git
 GIT_TAG 4.2
 GIT_SHALLOW TRUE
)
FetchContent_MakeAvailable(spine-runtimes)
FetchContent_GetProperties(spine-runtimes)
if(NOT spine-runtimes_POPULATED)
   FetchContent_Populate(spine-runtimes)
endif()
add_subdirectory(${spine-runtimes_SOURCE_DIR}/spine-c ${CMAKE_BINARY_DIR}/spine-runtimes)
```
But 
- `spine-c` is mentioned, when it should be `spine-cpp`
- the implementation is against [cmake standards](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_populate)

I'd like to propose:
```
FetchContent_Declare(
 spine-runtimes
 GIT_REPOSITORY https://github.com/esotericsoftware/spine-runtimes.git
 GIT_TAG 4.2
 GIT_SHALLOW TRUE
 SOURCE_SUBDIR spine-cpp
)
FetchContent_MakeAvailable(spine-runtimes)
```
Which achieves the same goal but without the above cons. 
I'd send in a PR, but I don't notice a repo for one.

**Comment by badlogic** [comment]
Huh, I wonder why I put that `FetchContent_Populate `  there. It's definitely not right! Thanks for being so attentive, we'll fix this up in the docs.

**Comment by lukeeingram** [comment]
I updated the documentation, thank you for reporting this!
