### ISSUE TITLE
slots is a reserved keyword on qt

### ISSUE THREAD

**Issue by martell** [EsotericSoftware/spine-runtimes#27]
Hi Nate,

In QT the words signals and slots are reserved but you are slots in.

SkeletonData.h in the SkeletonData typedef on line 43
SlotData*\* slots;

Suggestions or Compromises on a name?

Many Thanks Martell

**Comment by ruffianeo** [comment]
I tried to use ECL (a common lisp) and the reserved keyword `slots` spoils the whole idea I had:

In ecls object.h
```
struct ecl_instance {           /*  instance header  */
        _ECL_HDR1(isgf);
        cl_index length;        /*  instance length  */
        cl_object clas;         /*  instance class  */
        cl_objectfn entry;      /*  entry address  */
        cl_object sig;          /*  generation signature  */
        cl_object *slots;       /*  instance slots  */
};
```
So what again is an easy way to work around this?
