### ISSUE TITLE
[cpp] loading files from memory

### ISSUE THREAD

**Issue by hsdk123** [EsotericSoftware/spine-runtimes#2702]
Hi, I'm currently trying to load the spine formats into my engine.
I don't work with filesystems directly and load my files into memory. 

I notice
```
class SP_API Atlas : public SpineObject {
public:
	Atlas(const String &path, TextureLoader *textureLoader, bool createTexture = true);

	Atlas(const char *data, int length, const char *dir, TextureLoader *textureLoader, bool createTexture = true);
```
The second function might be what I'm looking for to load an Atlas, but I have no idea what `dir` means. May I request clarification?

**Comment by hsdk123** [comment]
Another question:
What is the time unit for `delta` in `AnimationState::update(float delta)`?

**Comment by lukeeingram** [comment]
Hi, our Spine Forum would be a better place to ask both of these questions:
https://esotericsoftware.com/forum/t/Spine-Runtimes

Our issue tracker for the Spine Runtimes repo is for bug reports and requesting/suggesting improvements to the Runtimes, whereas the Forum is our preferred place to receive and answer questions like yours. It also enables anyone else that has the same questions as you do to quickly find our responses to your questions. 

We look forward to assisting you with these questions on the Forum.
