### ISSUE TITLE
[spine-cpp] setScaleY not working properly

### ISSUE THREAD

**Issue by hsdk123** [EsotericSoftware/spine-runtimes#2703]
Hi, `setScaleY` doesn't seem to be working properly.
My engine has the y axis upside down compared to Spine. 
By default thus the animation displays as so:

![image](https://github.com/user-attachments/assets/c9a51502-3ac2-4bc7-b44f-2edd2871c6f7)
(rain is under the cloud as it should be)

When I `setScaleY(-1)` however, the rain animation doesn't seem to be appearing in the right place:
![image](https://github.com/user-attachments/assets/a3b624b2-908d-491d-94d0-ddca07317738)
(rain is above the cloud)

**Comment by davidetan** [comment]
To change the y axis direction, we have a dedicated variable `yDown` on the `Bone` class.
See the link here: https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-cpp/spine-cpp/src/spine/Bone.cpp#L39

**Comment by hsdk123** [comment]
> To change the y axis direction, we have a dedicated variable yDown on the Bone class

Thanks! This doesn't however seem to align with the document here, which mentions using `setScaleY` for the entire skeleton:
https://en.esotericsoftware.com/spine-cpp#Flipping

(Would like to mention `spine::Bone::setYDown(true);` does work as expected though, thank you!)

**Comment by davidetan** [comment]
The flipping section tells how to flip a single skeletons.
The `yDown` is a static variable to globally invert the y direction.
You can flip your skeleton regardless how `yDown` is set.
But we could actually mention it somewhere in the generic runtime guide.
