### ISSUE TITLE
[ts][pixi-v8] Skeleton and atlas parsers missing

### ISSUE THREAD

**Issue by Wazrop** [EsotericSoftware/spine-runtimes#2704]
Hello,

We're having issue when migrating from @pixi/spine-pixi to @esotericsoftware/spine-pixi-v8. The problem we occur is the skeleton/atlas assets are not being loaded. From the warnings to the console it seems Pixi asset loader does not recognize files .skel (.json) and .atlas:

```
PixiJS Warning:  [Assets] http://localhost:1239/assets/Spine/spineboy-pro.skel could not be loaded as we don't know how to parse it, ensure the correct parser has been added
PixiJS Warning:  [Assets] http://localhost:1239/assets/Spine/spineboy-pma.atlas could not be loaded as we don't know how to parse it, ensure the correct parser has been added
PixiJS Warning:  [Assets] Asset id spineSkeleton was not found in the Cache
PixiJS Warning:  [Assets] Asset id spineAtlas was not found in the Cache
```

According to https://esotericsoftware.com/spine-pixi#Spine-Pixi-runtime the correct parsers should be added along with the spine-pixi-v8.

Node.js v22.11.0
"@esotericsoftware/spine-pixi-v8": "~4.2.66",
"pixi.js": "^8.6.2"

**Comment by davidetan** [comment]
There's really nothing special to do about loaders. The installation process is completely transparent to the user.

We have a typescript example that works [here](https://github.com/EsotericSoftware/spine-runtimes/tree/4.2/spine-ts/spine-pixi-v8/example/typescript).
Dependecies are:
```
"@esotericsoftware/spine-pixi-v8": "~4.2.63",
"pixi.js": "^8.4.0"
```
But I tried to upgraded to latest of both and everything still works correctly.

Can you identify the difference with our example and your?
Or can you share a toy example that reproduce the issue?

**Comment by Wazrop** [comment]
Hey, thanks for the quick response. I made a compare with the provided example - somehow I missed that you had an example. 

The problem was we had `"module": "commonjs"` in our `tsconfig.json`. Not really sure if it should or if it shouldn't work with commonjs. We switched to ES6.


Thank you!
