### ISSUE TITLE
[ts][pixi-v8] Replace texture of MeshAttachment during runtime

### ISSUE THREAD

**Issue by sneaky-angel** [EsotericSoftware/spine-runtimes#2707]
Hello, as described in the title I need to replace the texture of MeshAttachment during runtime.

It was possible in previous runtimes: https://github.com/pixijs/spine/blob/master/packages/base/src/SpineBase.ts#L685

The easiest way I found is:

    const mesh = mySpineObj.findSlot('mySlot').attachment;

    const texture = new SpineTexture(someTexture);

    mesh.region.texture = texture;

But I'm not sure whether this is the correct way of replacing a texture.
Thank you in advance.

**Comment by davidetan** [comment]
Hello!

That API `hackTextureBySlotName` and all related was not ported.
We have currently [this open issue](https://github.com/EsotericSoftware/spine-runtimes/issues/2639) where we want to define a common way in our runtimes to make texture swap at runtime possible. We did not work on it yet.

Regarding your code:

> The easiest way I found is:
> ```
> const mesh = mySpineObj.findSlot('mySlot').attachment;
> 
> const texture = new SpineTexture(someTexture);
> 
> mesh.region.texture = texture;
> ```

Are you sure that this code actually work? Where `someTexture` comes from?
The only way this can work is if `someTexture` has the texture region in the very same position of the starting texture atlas. Something like a "recoloring" of the same texture atlas.

Ideally, the minimum actions you should do to swap a texture region with an external texture are the followings:
```js
// load the new texture
PIXI.Assets.add({alias: "swap", src: "./assets/swap.png" });
await PIXI.Assets.load(["swap"]);

// create the pixi sprite
const swap = PIXI.Sprite.from('swap');

// create the pixi-sprite wrapper for Spine
const spineTexture = spine.SpineTexture.from(swap.texture.source)

// select the slot
const slot = spineboy.skeleton.findSlot("slot");

// redefine the region dimensions
const region = slot.attachment.region;
region.u = region.v = 0;
region.u2 = region.v2 = 1;
region.page.width = region.width = region.originalWidth = spineTexture._image.width;
region.page.height = region.height = region.originalHeight = spineTexture._image.height;
slot.attachment.region.texture = spineTexture;

// inform the attachment of the new region updates
slot.attachment.updateRegion();
```

Be aware that you are replacing the `TextureAtlasRegion` of an existing `TextureAtlasPage`, both belonging to an existing `TextureAtlas`.

Apart from that, it should be safe doing something like this.
This won't work with sequences.

Let me know if this work for your use case.

**Comment by sneaky-angel** [comment]
Hello, thank you very much. Yes, my example seems to work just fine, but it could be because of the reason you've mentioned.
Nevertheless, I've added your logic as well.

One more thing I didn't mention is that my intention is to replace with `PIXI.RenderTexture` and not just a regular `PIXI.Texture`.
In order to do that I had to manually override `RenderTexture.source.resource` property as it is undefined by default but is required by `SpineTexture`


    renderTexture.source.resource = {
        width: renderTexture.width,
        height: renderTexture.height
    };

    const slot = mySpineObj.findSlot('mySlot');
    const region = slot.attachment.region;
    const spineTexture = new SpineTexture(texture.source);

    // redefine the region dimensions
    region.u = region.v = 0;
    region.u2 = region.v2 = 1;
    region.page.width = region.width = region.originalWidth = spineTexture._image.width;
    region.page.height = region.height = region.originalHeight = spineTexture._image.height;
    region.texture = spineTexture;

    // inform the attachment of the new region updates
    slot.attachment.updateRegion();

Thank you for your help!

**Comment by davidetan** [comment]
When we'll work on the issue mentioned above, we'll make this feature available in all runtimes and swapping textures will be easier and transparent.
