### ISSUE TITLE
Is is possible to use pixi-spine runtime 4.1 and 4.2 together?

### ISSUE THREAD

**Issue by kulabros** [EsotericSoftware/spine-runtimes#2709]
Hi. I'm looking at new versions, changes, repository move and rename.

Right now I'm using pixi v7 and I'm importing @pixi-spine/base and @pixi-spine/runtime4.1.
Now I'm thinking of supporting new version of spine runtime 4.2, but also I have a lot of assets in 4.1. 

Since the pixi-spine has moved, it's quite unclear in the docs I've found, how it should be imported and used.
Can anybody link me to the appropriate docs, where the imports for @esotericsoftware/spine-pixi-v7 are described? Or maybe just a small example can help.

Is it possible, to have both runtime 4.1. and 4.2 running together in one scene?
Is the 4.2 runtime backwards compatible, so I can use only one runtime for 4.2. and 4.1 assets? 

Thanks a lot for any help, have a nice day!

**Comment by kulabros** [comment]
Sorry, I've finally found the docs how to import the 4.2... 

https://en.esotericsoftware.com/spine-pixi

**Comment by davidetan** [comment]
You find the docs while I was answering 😄 

Our runtimes support 4.2 assets only since they are pretty recent.
You could try to upgrade all your assets to 4.2.

Maybe, `pixi-spine` and `spine-pixi` can live together, but I cannot guarantee that.

**Comment by kulabros** [comment]
Understand, thank you!

At previous version, I was also importing SpineBase, to applySpine2dMixin, because of pixi-projection 2D projection plugin support. Now I see there's now SpineBase. Should I use convertTo2d() at the intance, or is there some way how to keep this functionality?

I know I can re-export assets fin the new version, but there's really a LOT of assets.
Isn't there some conversion / migration script, to convert assets runtime versions?

**Comment by davidetan** [comment]
We have a [CLI](https://en.esotericsoftware.com/spine-command-line-interface) and an [export script](https://en.esotericsoftware.com/spine-command-line-interface) that can help you in exporting your assets in 4.2.

**Comment by kulabros** [comment]
Ok thank you for quick reply and tips, I'll try!

I was thinking of my situation.. I don't want to mix runtime versions for several reasons. I'll keep current project version with current 4.1 runtime, and for new upcoming project builds I'll use the 4.2 version, and I'll re-export 4.1 assets which I will need in the new project, so there'll be only one assets version.

I'll explore pixi-projection and adding pixi-spine container into projection plane by now, it looks it should work in v7.

Thanks you in advance:)
