### ISSUE TITLE
In Flutter runtime, how can I obtain an AtlasRegion?

### ISSUE THREAD

**Issue by iamdennisme** [EsotericSoftware/spine-runtimes#2710]
I am using Flutter version 4.2, and I hope to obtain an AtlasRegion, but I haven't found any related API for it. Is there a way to do this?

**Comment by badlogic** [comment]
I'm afraid it is currently not possible to retrieve or set AtlasRegions in the Flutter runtime.

In general, please use the forum for questions:

https://esotericsoftware.com/forum
