### ISSUE TITLE
[ts][pixi-v8] pixi.js@8.6.5 + @esotericsoftware/spine-pixi-v8@4.2.67 = crash

### ISSUE THREAD

**Issue by tonku321** [EsotericSoftware/spine-runtimes#2713]
<img width="988" alt="Screenshot 2024-12-16 at 15 33 46" src="https://github.com/user-attachments/assets/ed420214-fcca-429c-b686-23d07f2704c3" />

- pixi.js@8.6.5 + @esotericsoftware/spine-pixi-v8@4.2.69 = crash
- pixi.js@8.6.5 + @esotericsoftware/spine-pixi-v8@4.2.66 = crash
- pixi.js@8.6.4 + @esotericsoftware/spine-pixi-v8@4.2.66 = no crash
- pixi.js@8.6.4 + @esotericsoftware/spine-pixi-v8@4.2.69 = no crash

**Comment by davidetan** [comment]
Thanks for reporting this, but I cannot reproduce the error.
Can you share an example to reproduce it? You can also send it to contact@esotericsoftware.com.

**Comment by tonku321** [comment]
fixed by https://github.com/pixijs/pixijs/pull/11167 (included in pixi.js@8.6.6)

**Comment by davidetan** [comment]
Great! Thanks for reporting the issue :)
