### ISSUE TITLE
[Cocos2DX] setAnimation leads to frame overlap

### ISSUE THREAD

**Issue by wb197** [EsotericSoftware/spine-runtimes#314]
I'm using spine-runtimes with cocos2dx 3. I'm now working on an application for recording an spine animation's frames into png pictures. I found that the update method of class Layer doesn't run syncronized. I have many animations in one spine file(jsonFile, atlasFile). I want the application plays all the animation one by one and record each frames into png files. I found that the final frame of an animation goes overlap the first frame of next animtion after animation siwtched. I don't know how to modify the program. Can someone please give me some advice?

I made all the load in HelloWorld::init()

	actor = SkeletonAnimation::createWithFile(jsonFile.c_str(), atlasFile.c_str(), gScale);
	
	spSkeleton* skeleton = actor->getSkeleton();

	for (int i = 0; i < skeleton->data->animationsCount; i++)	{
		string animName = skeleton->data->animations[i]->name;
		animationNames.push_back(animName);
		DebugPrintln("[idx]%d, [animName]%s", i, animName.c_str());
	}

	animIdx = 0;
	_animName = animationNames[animIdx];

set the animatioin complete listener in a lambda expression

	//---------------------------------------------------------------------------------------------
	auto animComplete = [this] (int trackIdx, int loopCount) {

		if (!this->animationPlayNext())
		{
			DebugPrintln("end in animComplete");
			Director::getInstance()->end();
		}
		else
		{
			//render();
		}
	};

	actor->setCompleteListener(animComplete);

implement a method to switch the animation after one animtion runs over.
bool HelloWorld::animationPlayNext()
{
	++groupId;

	if (animIdx < animationNames.size())	{
		_animName = animationNames[animIdx];
		actor->setAnimation(0, _animName.c_str(), false);
		
		int idx = _animName.find('_');
		_groupIdx = _animName.substr(0, idx);

		ofs_airFile<<"\n\n; "<<_groupIdx<<endl;
		char buf[256] = {0};
		sprintf(buf, "[Begin Action %s]", _groupIdx.c_str());
		ofs_airFile<<buf<<endl;

		++animIdx;
		DebugPrintln("groupNumber:%s    animName:%s", _groupIdx.c_str(), _animName.c_str());

		float _x, _y;
		actor->getPosition(&_x, &_y);
		DebugPrintln("actor position:%f, %f", _x, _y);

		animJustSwitched = true;

		return true;
	}

	return false;
}

void HelloWorld::update(float deltaTime)
{
	Director* director = Director::getInstance();
	director->pause();

	DebugPrintln("update animation --- deltaTime:%f  picId:%d", deltaTime, picId);
	
	if (animIdx < animationNames.size())	{
		actor->setScale(1.0);
		render();
	}

	animJustSwitched = false;

	director->resume();
}

void HelloWorld::render()
{
	DebugPrintln("render group:%s", _groupIdx.c_str());

	if (!_groupIdx.empty() && isdigit(_groupIdx.c_str()[0]))	{

		//if (_lastAnimName != _animName)
		if (animJustSwitched)
		{
			picId = 0;
			int idx = _animName.find('_');
			_groupIdx = _animName.substr(0, idx);
			_lastAnimName = _animName;

			DebugPrintln("(---) picId reset to ZERO!  groupIdx:%s  _lastAnimName:%s", _groupIdx.c_str(), _lastAnimName.c_str());
		}

		//-------- saving *.def Mugen Picture Data --------//
		char strBuf[256] = { 0 };
		sprintf(strBuf, "%s, %d, %s\\%s_%04d.png, %d, %d", 
			_groupIdx.c_str(), picId, outputPath.c_str(), _lastAnimName.c_str(), picId, offsetX, offsetY);
		ofs_defFile<<strBuf<<endl;

		//-------- saving *.air Mugen Animation Data --------//
		char buf[256] = {0};
		sprintf(buf, "%s, %d, 0, 0, %d", _groupIdx.c_str(), picId, (int)ticks);
		ofs_airFile<<buf<<endl;

		//-------- saving *.png File ---------//
		char path[256] = { 0 };
		sprintf(path, "%s_%04d.png", _animName.c_str(), picId);
		DebugPrintln("save picture: --- %s, debugIndex:%d", path, debugIndex++);
		saveScreenShot(path);

		++picId;
	}
}

**Comment by pharan** [comment]
I will be closing this issue. You have better chances getting help in the forums where many users are more active! http://esotericsoftware.com/forum/viewforum.php?f=3
