### ISSUE TITLE
Possible error in spine-as3 and flip timelines

### ISSUE THREAD

**Issue by bp74** [EsotericSoftware/spine-runtimes#327]
Found here:
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-as3/spine-as3/src/spine/SkeletonJson.as#L401

I think the code should be:

    duration = Math.max(duration, flipTimeline.frames[flipTimeline.frameCount * 2 - 2]);

instead of

    duration = Math.max(duration, flipTimeline.frames[flipTimeline.frameCount * 3 - 3]);

**Comment by Fraggle** [comment]
I think I agree with that :)
Can you check please ?

**Comment by NathanSweet** [comment]
This was fixed at some point, also since then flip timelines are gone.
