### ISSUE TITLE
Maven artifacts for libgdx runtime

### ISSUE THREAD

**Issue by jjzazuet** [EsotericSoftware/spine-runtimes#330]
Hi! Like the title says. Are the re any plans to publish Maven artifacts for libgdx? Right now I'm using them in a project but I have to maintain my own private maven repo.

Thanks!

**Comment by mars3142** [comment]
This would be really great.

**Comment by obigu** [comment]
I agree, libGDX runtime should be Gradleized

**Comment by pharan** [comment]
I will be closing this issue.
I've listed this suggestion down in the ideas list but do consider posting future suggestions in the forums. Many users are active there and can better chime in on ideas. http://esotericsoftware.com/forum/viewforum.php?f=3
