### ISSUE TITLE
[JS] FFD not working in JavaScript

### ISSUE THREAD

**Issue by darionco** [EsotericSoftware/spine-runtimes#331]
After fixing some syntax issues and an infinite loop in PR #328 the FFD attachments simply won't work, their positional info seems to be empty. I could look at the libGDX implementation and port it over but I know from #315 that @NathanSweet wants to keep a handle on the code base, so I'll wait for him to pitch in.

**Comment by JaredSartin** [comment]
Any progress? I am having the hardest time with getting FFD working in JS. I have tried adapting the spine-canvas demo to work with the Raptor animation, but cannot get it working.

**Comment by lucap86** [comment]
up

**Comment by darionco** [comment]
Take a look at:
https://github.com/TrompoGames/pixi.js/tree/trompo-dev
(Trompo-dev branch just in case) I have been using FFD in pixi.js for a while now.
Hope it helps.

**Comment by badlogic** [comment]
This will be fixed in the upcoming spine-js 3.4.0 update. See https://github.com/EsotericSoftware/spine-runtimes/issues/613
