### ISSUE TITLE
Black box when render [Spine|cocos2dx|WP8]

### ISSUE THREAD

**Issue by cowboybkit** [EsotericSoftware/spine-runtimes#343]
I met issue render black box like screenshot.
![blackbox](https://cloud.githubusercontent.com/assets/450528/5802027/8343a3be-a023-11e4-9e16-ae89b00aed5b.png)
Please help me find problems. Here is spine files:

http://www.mediafire.com/download/ayj0f9bhf8zbbae/black.zip

Thanks

**Comment by pharan** [comment]
Thanks for reporting!

I will be closing this issue. You will have better chances getting help in the forums where many users are more active! http://esotericsoftware.com/forum/viewforum.php?f=3

I suspect this was a transient bug (or unaddressed issue) by the Cocos2D-X framework.
