### ISSUE TITLE
btw I have this three.js fork

### ISSUE THREAD

**Issue by makc** [EsotericSoftware/spine-runtimes#359]
[here](https://github.com/makc/spine-runtimes/tree/three.js). Developed as part of commercial project, but I have the permission to share it. It is basically does all (or almost all) what turbulenz does, and I will probably be fixing bugs there when they are found.

Take a look and let me know if you would be interested in pull request.

**Comment by JaredSartin** [comment]
Would love to see some support/demos for meshes/FFD! Also, the "not quite stable - for testing only" is unfortunate when it comes to these runtimes. Looks good for basic stuff though!

This would be PERFECT for an upcoming project.

**Comment by makc** [comment]
well the story is that I did this for a project where the guy had spine animations but wanted to use them in 3js scene. so I did this. I've never received any bug reports, therefor I assume it is not stable.

**Comment by JaredSartin** [comment]
Ok! Cool. I would love to use it, vur have had some trouble with Mesh/FFD animations, was just hoping that was in place or "upcoming" but it sounds like it was a past project.

Thanks!

**Comment by makc** [comment]
it is indeed, and this issue was made in hope that this repo owners would become its foster parents, but apparently they aren't interested.

**Comment by JaredSartin** [comment]
Have you put in a Pull Request?

**Comment by JaredSartin** [comment]
I just put in a pull request - #383

**Comment by mreinstein** [comment]
@makc  @JaredSartin it seems that newer versions of three.js cause some minor breakage. I tried upgrading three.js to version 72 (current stable) and the goblin skins don't toggle.

**Comment by makc** [comment]
do you have a stack trace or anything?

**Comment by mreinstein** [comment]
It doesn't throw any errors in the console, just prints the three.js version number `THREE.WebGLRenderer 72`

**Comment by makc** [comment]
@mreinstein sorry I forgot about you here :( well, I can confirm there is some sort of issue with r72, at the same time it goes away again with r73, so I am not sure there is anything to fix. I shall see in detail, just in case...

**Comment by makc** [comment]
seems there was the bug in three.js that they fixed in [this commit](https://github.com/mrdoob/three.js/commit/da52161619bd29c02486a89e1c91c45c98a75b96).

**Comment by NathanSweet** [comment]
Sorry, we are a bit behind on servicing GitHub issues.

FWIW, I'm not super happy with the Turbulenz runtime. Drawing rectangles was fine enough, but only after I added a SpriteBatch class. Drawing meshes is a different story and appears quite difficult with the available APIs. I want a game toolkit that doesn't put so much between spine-js and WebGL. We already have the vertices, etc it should just be a matter of handing them off. Is that possible with three.js? If not, I prefer to hold out until we come across a more reasonable JavaScript library. If we do ever find that, we might even drop Turbulenz since it's basically just a simple demo and doesn't support all the features (meshes).

**Comment by makc** [comment]
> I want a game toolkit that doesn't put so much between spine-js and WebGL. We already have the vertices, etc it should just be a matter of handing them off.

that's fine as long as you want to stay 2D, of course. the point of this threejs thing was that you could have spine animation within threejs 3D world, not merely underneath or on top of it.

**Comment by makc** [comment]
[here](https://github.com/mrdoob/three.js/blob/master/examples/webgl_buffergeometry.html#L182-L186) would be an example of "handing off" the vertices to threejs, maybe, if you have them packed into Float32Array-s. if not, you might still be able to try and rely on duck typing pretendng to be THREE.Vector3-s, that may be possible as well...

**Comment by makc** [comment]
Yes, but it should be still there in #383
