### ISSUE TITLE
Spine.js SkeletonJson issues

### ISSUE THREAD

**Issue by superness** [EsotericSoftware/spine-runtimes#360]
Couple of issues with SkeletonJson in Spine.js

line 2044: duration = Math.max(duration, timeline.frames[timeline.frameCount * 3 - 3]);
line 2105: duration = Math.max(duration, timeline.frames[timeline.frameCount - 1]);

both of these timeline.frameCount calls should be getFrameCount()

The next issue is a little less defined. Had lots of issues with timeline vertices array not having values set and being seen as NaN later on (causing animations to fail). I didn't find the root cause.. but it seems to be related to starting at 'offset' in timelines and not setting 0 for the first 'offset' values.

**Comment by superness** [comment]
If I have some spine animations that are messed up are you guys interested in looking at them? They load up correctly in Skeleton Viewer: http://esotericsoftware.com/spine-skeleton-viewer

**Comment by lucap86** [comment]
Some issues for me,
many problems with meshes.

trying with goblin-mesh spine example and spinejs runtime.
[goblins-mesh.zip](https://github.com/EsotericSoftware/spine-runtimes/files/53645/goblins-mesh.zip)

this is how it is rendered, spear has completely wrong verticles
![spear](https://cloud.githubusercontent.com/assets/15343100/11622739/2df09500-9cc8-11e5-97c0-24ce20ddd939.png)

**Comment by dcalogue** [comment]
this is probably too late, but you can check my branch [https://github.com/dcalogue/spine-runtimes]

I fixed the mesh animations and used them in a shipped project

**Comment by lucap86** [comment]
This totally fix the problem for me!
thank you very much dcalogue you are a monster ;)

https://github.com/EsotericSoftware/spine-runtimes/compare/master...dcalogue:bugFixing

**Comment by badlogic** [comment]
This will be fixed in the upcoming 3.4.0 update of the spine-js runtime. See https://github.com/EsotericSoftware/spine-runtimes/issues/613
