### ISSUE TITLE
Ingest option disappear

### ISSUE THREAD

**Issue by liszto** [EsotericSoftware/spine-runtimes#361]
When I select my JSON file or anything else in the project, there is no more "Ingest" option in menu.
Some changes happen or is this a bug ?

I compare the current unity version on your github with the last one i use which is a december version.

There is a way to see a number version somewhere ? If this can help you to answer me :/

**Comment by Fenrisul** [comment]
I removed manual ingest because it caused more problems than it solved.  Simply right click on JSON file and hit "Reimport" - this should trigger the asset post processor again.
