### ISSUE TITLE
Scaling a Skeleton (Runtime)

### ISSUE THREAD

**Issue by kalligula** [EsotericSoftware/spine-runtimes#363]
Hi, we have implemented Spine in our engine, Rainbow (C++ with Lua scripting), and we are having a kickass time with it!

But we are having problems scaling skeletons on runtime. We followed this documentation:

http://esotericsoftware.com/spine-using-runtimes#Scaling

We can reload the skeleton - and then set a new scale, but that's no good outside quick tests.

Here is a pastebin of our implementation:

http://pastebin.com/edkB07JS

Are we doing anything obviously wrong? Can anyone help?

**Comment by tn0502** [comment]
The complete implementation can be found here: [.h](https://bitbucket.org/tido/rainbow/src/67d35938ea5efe3bce319778a67bcd68143ca197/src/ThirdParty/Spine/spine-rainbow.h?at=master) [.cpp](https://bitbucket.org/tido/rainbow/src/67d35938ea5efe3bce319778a67bcd68143ca197/src/ThirdParty/Spine/spine-rainbow.cpp?at=master)

**Comment by pharan** [comment]
I will be closing this issue. You will have better chances getting help in the forums where many users are more active! http://esotericsoftware.com/forum/viewforum.php?f=3
