### ISSUE TITLE
spSkin_attachAll() behaves incorrectly

### ISSUE THREAD

**Issue by petrikero** [EsotericSoftware/spine-runtimes#376]
I believe the spSkin_attachAll() function has a bug in it.

When switching skins, the function iterates through the old skin's attachments and sees if those slots have a corresponding attachment in the new skin. Where this breaks is when the old and new skins don't have all the same attachments. For example, when the old skin only has a body attachment, but the new one has body + limbs, then only the body attachment is changed.

The bug manifested as both leaked attachments from previous skins (when skin's attachment count went down) as well as missing attachments (when skin attachment count went up).

I was able to get our content to work with the code below, but am not sure that my fix is otherwise correct. (Apologies for the stylistic inconsistencies with existing code.)

	void spSkin_attachAll (const spSkin* self, spSkeleton* skeleton, const spSkin* oldSkin) {
		// Clear all old attachments.
		for (int slotNdx = 0; slotNdx < skeleton->slotsCount; slotNdx++)
			spSlot_setAttachment(skeleton->slots[slotNdx], NULL);

		// Attach all entries from new skin to correct slots.
		const _Entry* entry = SUB_CAST(_spSkin, self)->entries;
		while (entry) {
			spSlot *slot = skeleton->slots[entry->slotIndex];
			spAttachment *attachment = spSkin_getAttachment(self, entry->slotIndex, entry->name);
			if (attachment) spSlot_setAttachment(slot, attachment);
			entry = entry->next;
		}
	}

**Comment by petrikero** [comment]
Foofoo

	void spSkin_attachAll (const spSkin* self, spSkeleton* skeleton, const spSkin* oldSkin) {
		// Clear all old attachments.
		for (int slotNdx = 0; slotNdx < skeleton->slotsCount; slotNdx++)
			spSlot_setAttachment(skeleton->slots[slotNdx], NULL);

		// Attach all entries from new skin to correct slots.
		const _Entry* entry = SUB_CAST(_spSkin, self)->entries;
		while (entry) {
			spSlot *slot = skeleton->slots[entry->slotIndex];
			spAttachment *attachment = spSkin_getAttachment(self, entry->slotIndex, entry->name);
			if (attachment) spSlot_setAttachment(slot, attachment);
			entry = entry->next;
		}
	}

**Comment by petrikero** [comment]
My original fixed version was incorrect. It did resolve the issue we were having, but broke default-skin handling. Below is a version which works with default skins and changes in attachment slots between skins.

```
void spSkin_attachAll (const spSkin* self, spSkeleton* skeleton, const spSkin* oldSkin) {
	// Remove old attachments.
	const _Entry *oldEntry = SUB_CAST(_spSkin, oldSkin)->entries;
	while (oldEntry) {
		spSlot *slot = skeleton->slots[oldEntry->slotIndex];
		if (slot->attachment == oldEntry->attachment)
			spSlot_setAttachment(slot, NULL);
		oldEntry = oldEntry->next;
	}

	// Attach all entries from new skin to correct slots.
	const _Entry* entry = SUB_CAST(_spSkin, self)->entries;
	while (entry) {
		spSlot *slot = skeleton->slots[entry->slotIndex];
		spAttachment *attachment = spSkin_getAttachment(self, entry->slotIndex, entry->name);
		if (attachment) spSlot_setAttachment(slot, attachment);
		entry = entry->next;
	}
}
```

**Comment by pharan** [comment]
Thanks for the report. I'll be closing this issue and tracking it here: https://github.com/EsotericSoftware/spine-runtimes/issues/506
