### ISSUE TITLE
Use Spine.js with error selSprite=undefined

### ISSUE THREAD

**Issue by jtianling** [EsotericSoftware/spine-runtimes#381]
error info like this:(Cocos2d-js with the new spine)
JS: selSprite=[object Sprite]
JS: attachment is not instanceof spine.RegionAttachment and selSprite=[object Sprite]
JS: selSprite=undefined
JS: attachment is not instanceof spine.RegionAttachment and selSprite=undefined
JS: selSprite=undefined

**Comment by badlogic** [comment]
We are updating the spine-js runtime to be compatible with the latest Spine version. See https://github.com/EsotericSoftware/spine-runtimes/issues/613

We can re-open this if you can provide a reproduction case if the spine-js update doesn't fix your issue.
