### ISSUE TITLE
spSkeletonData_dispose() crashes

### ISSUE THREAD

**Issue by AntonPetrov83** [EsotericSoftware/spine-runtimes#386]
When spSkeletonJson_readSkeletonData() loads animations it is possible to fail animation loading (I am still investigating the reason animation loading fails), so _spSkeletonJson_readAnimation() disposes failed animation and returns 0.

After that spSkeletonData::animations[] contains one already released animation.

So spSkeletonData_dispose() tries to release its animation for second time.

**Comment by Think-Jumper** [comment]
Me too, the same problem.

**Comment by badlogic** [comment]
Please try the latest spine-c runtime compatible with Spine 3.4.0 in the master branch.
