### ISSUE TITLE
[js] There has an error in spine.js

### ISSUE THREAD

**Issue by dingpinglv** [EsotericSoftware/spine-runtimes#407]
The function `apply` of spine.FlipXTimeline and  spine.FlipYTimeline forgot to add 'this' at https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-js/spine.js#L897 and https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-js/spine.js#L925. 

`skeleton.bones[boneIndex].flipY = frames[frameIndex + 1] != 0;` will throw an error.

**Comment by badlogic** [comment]
This will be fixed in the upcoming 3.4.0 upgrade of the spine-js runtime, see https://github.com/EsotericSoftware/spine-runtimes/issues/613
