### ISSUE TITLE
[Generic Runtime Request] Cache animated interpolated values to avoid calculating every value every update.

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-runtimes#411]
Hello,

In AS3 the cost for interpolating the data and uploading the vertex each frame is not insignificant, would it be possible to pre-calculate the animation for a specific frame rate and try to cache as much as possible (static vertex buffer etc..).
I think it would be an interesting addition :-)

Thanks for considering this.

**Comment by pharan** [comment]
Obviously, this is a case of trading memory for speed.
How much, memory? probably just number of (vertices * size of vertex data) + (number of triangles + 3 + size of an int) + a bit of object model overhead.
Might make the most sense if you have a boatload of verts.

But this feature seems like a super specific optimization and highly opinionated to be part of the official runtime. (though such things aren't really my call to make)

I would say though that this amounts to letting the Spine system pose the `Skeleton` for each desired frame, then storing the resulting meshes it generates (or its vertex buffer objects and related components), probably serializing it into a list of saved meshes if you don't want to do this at loadtime, then using that for playback. Playing this back at runtime wouldn't even need to pass through Spine's animation system.

I'm not an AS3 person, so I wouldn't know how to go about it in ActionScript.
