### ISSUE TITLE
[Editor Request] Save animation bounds in the data file

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-runtimes#412]
Hello,

We already have the width and height of the setup pose but it would be even more useful to have the bounds of the setup pose (x,y,width,height) and also the bounds of each animation sequence (max bounds of the sequence).
I added a getBounds myself but it would save a LOT of calculations to do it at export time.
Btw, having a getBounds method in the runtime (with calculateBounds true/false if you want) could be quite nice :)

Thanks!

**Comment by pharan** [comment]
I will be closing this issue.
I've listed this suggestion down in the ideas list but do consider posting future suggestions in the forums. Many users are active there and can better chime in on ideas. http://esotericsoftware.com/forum/viewforum.php?f=3
