### ISSUE TITLE
Spine-starling commit 27270a5781c93ea7d14f169d73dfa89f38076110 killed all *.png files

### ISSUE THREAD

**Issue by lavoryk** [EsotericSoftware/spine-runtimes#425]
Seems this changes
Spine Runtimes license update. 
27270a5781c93ea7d14f169d73dfa89f38076110
killed all *.png files
It added license text at begin of all files, including *.png

e.g.
goblins-mesh.png 

/******************************************************************************^M
 * Spine Runtimes Software License^M
 * Version 2.3^M
 * ^M
 * Copyright (c) 2013-2015, Esoteric Software^M
 * All rights reserved.^M
 * ^M
 * You are granted a perpetual, non-exclusive, non-sublicensable and^M
 * non-transferable license to use, install, execute and perform the Spine^M
 * Runtimes Software (the "Software") and derivative works solely for personal^M
 * or internal use. Without the written permission of Esoteric Software (see^M
 * Section 2 of the Spine Software License Agreement), you may not (a) modify,^M
 * translate, adapt or otherwise create derivative works, improvements of the^M
 * Software or develop new applications using the Software or (b) remove,^M
 * delete, alter or obscure any trademarks or any copyright, trademark, patent^M
 * or other intellectual property or proprietary rights notices on or in the^M
 * Software, including any copy thereof. Redistributions in binary or source^M
 * form must include this license and terms.^M
 * ^M
 * THIS SOFTWARE IS PROVIDED BY ESOTERIC SOFTWARE "AS IS" AND ANY EXPRESS OR^M
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF^M
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO^M
 * EVENT SHALL ESOTERIC SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,^M
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,^M
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;^M
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,^M
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR^M
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF^M
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.^M
 *****************************************************************************/

.PNG^M
^Z^M
^@^@^@^M
IHDR^@^@^D^@^@^@^@.^H^F^@^@^@..^[H^@^@.^@IDATx...<----->.lYU....-...^R^DAe....9Gd.s.9'..<.^Y....x..5^BULB+ ?...?b ۭ.s.i..C^[.EQQQ^T.^T.^M

**Comment by pharan** [comment]
Closing this issue because there's a PR. Further discussion can be carried out there.
