### ISSUE TITLE
[Starling] SkeletonSprite not compatible with Starling fragment filter

### ISSUE THREAD

**Issue by vync79** [EsotericSoftware/spine-runtimes#429]
Hello,
this is an enhacement request to get the FragmentFilter compatible with the SkeletonSprite in spine starling runtime.

This seems related to the current implementation of the getBounds methods which always return the width and height as 0 and which in turn prevent the filters from properly computing their texture bounds.

Isn't there any possibility to get the width and height set to some value after a getBounds call (even some rought estimate of the skeleton boudaries) ?
I guess this was not done because of performance considerations but it would be really interesting to be able to use the FragmentFilter with skeletons.

**Comment by vync79** [comment]
Hi guys,
any news about this request?

**Comment by vync79** [comment]
Hello guys,
I am still enjoying using your framework. However could you let me know if anyone is screening the opened tickets ?
Is it at least possible to know if this issue as some known workaround or if a fix is to be expected some day ?
Thanks.

**Comment by Fraggle** [comment]
I did it myself by subclassing and overriding getbounds, i took most of the code from hittest.

**Comment by vync79** [comment]
Hi Fraggle, 
I also tried this quickly on my side but I faced some weird offset issues for which I have not taken the time to debug yet... Would you be willing to share your code?

**Comment by vync79** [comment]
Hello Spine team,
I see that Daniel Sperl from Gamua is working on Starling v2.0 which seems greatly improved for mesh support and cache mechanism. 
With the current Starling v2.0 WIP, the starling spine runtime does not compile.

Are you planning on proposing an updated version when the v2.0 is officially introduced ?
If so, would you be able to provide a fix for the width/height determination in skeleton sprites ?

**Comment by badlogic** [comment]
We have updated the spine-starling runtime to be compatible with Spine 3.4.0 and Starling 2.0!
