### ISSUE TITLE
[C] SpineEvents: Pointer to UserData

### ISSUE THREAD

**Issue by galmeidadavid** [EsotericSoftware/spine-runtimes#439]
How am i supposed to use the Events API and save some "User defined data" to receive with the event system?

For now i edited the source code to add optional User Data support to spAnimationState.

**Comment by gadavid** [comment]
This is the code:

AnimationState.h

    spAnimationStateListener listener;
    void* userData;

AnimationState.c

    entry->listener(..., ..., ..., ..., ..., self->userData);

**Comment by pharan** [comment]
spAnimationStateListener is a function pointer. You can set that to point to a function that has this signature.
```
void (*spAnimationStateListener) (spAnimationState* state, int trackIndex, spEventType type, spEvent* event, int loopCount);
```
This can be found here: https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-c/include/spine/AnimationState.h#L49

The user-defined event can be accessed in the `spEvent* event` parameter. Check for the spEventType first.

I will be closing this issue. You will have better chances getting help in the forums where many users are more active! http://esotericsoftware.com/forum/viewforum.php?f=3
