### ISSUE TITLE
[Request] Packing atlas using SpriteUV (or something similar)

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-runtimes#441]
I just heard about that:
http://www.spriteuv.com/

It's quite fantastic and could reduce atlas size and per pixel work.

What do you think ?

**Comment by pharan** [comment]
I will be closing this issue.
I've listed this suggestion down in the ideas list but do consider posting future suggestions in the forums. Many users are active there and can better chime in on ideas. http://esotericsoftware.com/forum/viewforum.php?f=3
