### ISSUE TITLE
Missing override keyword in SkeletonRenderer.h will issue many warning in XCode7

### ISSUE THREAD

**Issue by zilongshanren** [EsotericSoftware/spine-runtimes#446]
Hi @NathanSweet 

I'm a core member from Cocos2D-X and we are upgrading to XCode 7. 
But there are a few warnings in Spine header files. 

We use `treat warning as error' compile option in our test project but now it can't build .

**Comment by NathanSweet** [comment]
I'm afraid I'm backed up and won't be able to get to this soon. You can
maybe compile only the Spine part without treating warnings as errors. Or
would you like to send a PR?

**Comment by zilongshanren** [comment]
@NathanSweet  Sure, thanks. I will send the PR soon.

**Comment by zilongshanren** [comment]
@NathanSweet  Here is the PR: https://github.com/EsotericSoftware/spine-runtimes/pull/447

**Comment by badlogic** [comment]
Not an issue in Xcode 7.3.1.
