### ISSUE TITLE
[cocos2dx] Crash when removing from parent SkeletonAnimation

### ISSUE THREAD

**Issue by raul-plungeinteractive** [EsotericSoftware/spine-runtimes#448]
We're seeing a crash on the SkeletonAnimation update after we call removeFromParent().
We've tried to call unscheduleUpdate first, but it still crashes.

Do we have to stop the animation or anything before removing it so it doesn't crash?

Thanks,

**Comment by pharan** [comment]
What runtime is this?

**Comment by raul-plungeinteractive** [comment]
I think we've found a solution for this.
The crash was happening when calling the removeFromParent() method on a completeListener of the animation. I've tried adding setCompleteListener(nullptr) before the removeFromParent() call, and that seems to solve the issue.

**Comment by pharan** [comment]
@raul-plungeinteractive Okay. But what runtime is this? We're updating the runtimes soon and we'd like to apply a fix if we can.

**Comment by raul-plungeinteractive** [comment]
What do you mean by runtime?
We're using Version 2.3 on cocos-2dx 3.8.

**Comment by pharan** [comment]
Yes, that's the runtime. Thanks.

**Comment by DonMizzi** [comment]
Hi, I have 2.5 runtime for Cocos2d-x 3.14.1, but I have the same problem, catch in the SkeletonAnimation::udpdate with the following code:

```
SkeletonAnim * anim = SkeletonAnimation::createWithJsonFile(skeletonDataFile, atlasFile, 1.0);
  this->addChild(anim);

  spTrackEntry * entry = anim->setAnimation(0, animName2, false);
  anim->setTrackCompleteListener(entry, [anim] (int trackIndex, int loopCount)
  {
    anim->removeFromParentAndCleanup(true);
  });
```

**Comment by badlogic** [comment]
This is not possible to fix. The completion listener is called while the `AnimationState` inside the `SkeletonAnimation` is processing the currently set animations. The `removeFromParentAndCleanup` call will free all the memory associated with the `SkeletonAnimation`, including the `AnimationState`.

You can use the cocos2d-x `Scheduler` to schedule a callback for removal of the `SkeletonAnimation` from the scene.
