### ISSUE TITLE
Libgdx runtimes java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by dzungpv** [EsotericSoftware/spine-runtimes#464]
Sometime my game crash with this log:

```
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
    at com.badlogic.gdx.utils.Array.get(Array.java:127)
    at com.esotericsoftware.spine.AnimationState.apply(AnimationState.java:118)
    at game.widgets.IceEffectActor.act(IceEffectActor.java:57)
    at com.badlogic.gdx.scenes.scene2d.Group.act(Group.java:49)
    at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:223)
```

IceEffectActor.java line 57 is **animState.apply(skeleton)**:

```
    @Override
    public void act(float delta) {

        skeleton.setX(getX() + getWidth() / 2.0f);
        skeleton.setY(getY());

        skeleton.update(delta);
        skeleton.updateWorldTransform();

        animState.update(delta);
        animState.apply(skeleton);

        super.act(delta);
    }
```

**Comment by NathanSweet** [comment]
Are you doing anything on another thread? Eg, are AnimationState listeners being removed from a different thread?

**Comment by dzungpv** [comment]
@NathanSweet  I am not sure, below is some of my code. I call multiple time to showEnemyAttackSign(). I am not really understand about Libgdx Action in Scene2d.
I use Spine animation as Actor.

 ```
	private synchronized void showEnemyAttackSign() {
		if(attackSignCnt==0){
			attackSignFinish = false;
			attackSignCnt++;
		}
		if(attackSign !=null&&!attackSignFinish){
			attackSignFinish = true;
			attackSign.setVisible(true);
                        attackSign.animState.setAnimation(0, "ice", false)
			listener = new AnimationStateAdapter() {
				@Override
			    public void event (int trackIndex, Event event) {
			        // Inspect and respond to the event here.
					if (event!=null){
						if (event.getString().equalsIgnoreCase("end_ice_fx")) {
							attackSignCnt--;
							attackSign.animState.removeListener(listener);
							if(attackSignCnt==0){
								attackSignFinish = true;
							}
							if(attackSignCnt>=1){
								attackSignCnt--;
								addAction(Actions.delay(0.33f, new Action() {
									@Override
									public boolean act(float delta) {
										showEnemyAttackSign();
										return true;
									}
								}));
								
								attackSignFinish = false;	
							}
						}	
					}

				}
			};
			////
			attackSign.animState.addListener(listener);
		}
		else{
			attackSignCnt++;
		}

	}
```

**Comment by NathanSweet** [comment]
You call `apply` which iterates the listeners and fires events. You call `removeListener` during the firing of events, so the listener iteration fails.

During listener iteration, AnimationState should delay removal of the listeners until after listener iteration. I'll leave this issue until we can implement that for all the runtimes. Until that time, you should avoid removing listeners while events are being fired.

**Comment by dzungpv** [comment]
I have try, if not remove listeners, this error show more frequently. My final solution is block line:
``` listeners.get(iii).event(i, event); ``` with try/catch block. But when it occur, my game screen all bank.

**Comment by NathanSweet** [comment]
I suggest simplifying your problem so you understand what is going on and can see a solution.
http://sscce.org/

**Comment by dzungpv** [comment]
I follow the guide to simplifying the problem, you can check here:
https://www.dropbox.com/s/8u5udpzjd2wyqns/test_spine.zip?dl=0 . I am still don't know how to fix it.
You can run, click mouse about 15 times, and then it will show exception

**Comment by NathanSweet** [comment]
That is not an [SSCCE](https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code)!

As I described above, you call `attackSign.animState.removeListener(listener);` inside of the event listener. Comment out that line and the crash goes away.

**Comment by amcolash** [comment]
Sorry to re-open a very old topic at this point, just my experience. I have been running into this issue as well lately. As it is very hard to pinpoint at this time where things are going wrong in our game (hundreds of thousands of LoC), I decided to make the listeners array into a DelayedRemovalArray. Not sure if this is a bad practice, but just my experience with this situation and things have been working smoothly!

**Comment by zhaoweih** [comment]
Sorry to reopen this issue.Anyone solved this problem?

**Comment by NathanSweet** [comment]
@amcolash Sorry I missed your comment. Using `DelayedRemovalArray` is fine. Using `SnapshotArray` would also work, the difference being that with `DelayedRemovalArray` removals will not happen until after iteration while `SnapshotArray` does the removal and iteration continues using a copy. We can make the change to spine-libgdx in 3.9.

@zhaoweih Are you using spine-libgdx?
