### ISSUE TITLE
[pixi] alignment problem

### ISSUE THREAD

**Issue by yushli** [EsotericSoftware/spine-runtimes#467]
When using spine skeleton animation, there is some noticeable space between two skeletons. 
![qq20150907170245](https://cloud.githubusercontent.com/assets/1681453/9713345/6f41b336-5583-11e5-849f-a0ce1cfba780.png)
![qq20150907170214](https://cloud.githubusercontent.com/assets/1681453/9713346/73f763d0-5583-11e5-89c7-7f6e81ad56db.png)
The following are the spine files:
```json
{
"bones": [
	{ "name": "root" },
	{ "name": "bone", "parent": "root" },
	{ "name": "l_head", "parent": "bone" },
	{ "name": "r_head", "parent": "bone" }
],
"slots": [
	{ "name": "body", "bone": "bone", "attachment": "lose_chicken" },
	{ "name": "s_l_head", "bone": "l_head", "attachment": "lose__hand" },
	{ "name": "s_r_head", "bone": "r_head", "attachment": "lose__hand" }
],
"skins": {
	"default": {
		"body": {
			"lose_chicken": { "width": 58, "height": 57 }
		},
		"s_l_head": {
			"lose__hand": { "x": -47.99, "y": 7.99, "width": 59, "height": 54 }
		},
		"s_r_head": {
			"lose__hand": { "x": 40.99, "y": 18, "scaleX": -1, "width": 59, "height": 54 }
		}
	}
},
"animations": {
	"animation": {
		"bones": {
			"r_head": {
				"rotate": [
					{ "time": 0.1666, "angle": -22.58 },
					{ "time": 0.3333, "angle": 0 }
				]
			}
		}
	}
}
}
```

![skeleton](https://cloud.githubusercontent.com/assets/1681453/9713421/c8f4f1fe-5583-11e5-932a-f6369c61679e.png)

**Comment by pharan** [comment]
I think you may have been using meshes, and whitespace stripping.

Try asking in [the forums](http://esotericsoftware.com/forum/viewforum.php?f=3) for specific support. More users are there to help.

**Comment by yushli** [comment]
Hi, this issue is fixed by the pixi guys. 
https://github.com/pixijs/pixi.js/issues/2084
I will close it here now

**Comment by pharan** [comment]
@yushli Thanks for letting us know!

**Comment by yushli** [comment]
You are welcome.
And thank you all for making such a nice skeleton animation library.
