### ISSUE TITLE
Dynamic loading skins textures

### ISSUE THREAD

**Issue by IgorMats** [EsotericSoftware/spine-runtimes#469]
Hi guys!

Recently I meet a problem with my project.
I have one Spine object and many skins on it. All textures of all skins of this Spine object is around 500MB, so I can't load them all at one time.

Tell me please how to work with it? Maybe you have some completed solution? Because I forced to write this by myself.

Thank you!

**Comment by pharan** [comment]
Try asking in [the forums](http://esotericsoftware.com/forum/viewforum.php?f=3). Most people discuss implementation stuff there, and repo bugs here.
