### ISSUE TITLE
Spine.js:timeline.frameCount is undefined, It should be timeline.getFrameCount() 

### ISSUE THREAD

**Issue by drawapp8** [EsotericSoftware/spine-runtimes#471]
I tried to integrate spine.js into [Hola Studio](http://studio.holaverse.cn/), it works well for the basic samples, but when I load goblins-mesh.json, it crashed because the timeline duration is NaN.

timeline.frameCount is undefined, I Think It should be timeline.getFrameCount() .

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-js/spine.js#L2054

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-js/spine.js#L2115

**Comment by fillmoreb** [comment]
I can confirm this, I just ran into and fixed this bug on my own project today.

**Comment by badlogic** [comment]
We are updating all runtimes to 3.4.0, including spine-js. I'll fix this in this issue https://github.com/EsotericSoftware/spine-runtimes/issues/613

Thanks for reporting.
