### ISSUE TITLE
Crash in SkeletonJson.c

### ISSUE THREAD

**Issue by zapolnov** [EsotericSoftware/spine-runtimes#478]
I am getting a crash in loader after exporting animation from Spine. I can send you a .json file that results in this crash, but I can't post it to public site, so please give me a e-mail where to send it.

![stacktrace](https://cloud.githubusercontent.com/assets/1921392/11228852/2323a082-8d90-11e5-9037-b1a72d29216f.png)

**Comment by zapolnov** [comment]
The reason is that `originalIndex` is 38, but `slotIndex` is 36 on the entrance to this while loop. As a result, this loop never ends and gets out of memory bounds.

**Comment by NathanSweet** [comment]
Can you please email the JSON to contact@esotericsoftware.com?

**Comment by zapolnov** [comment]
Yes, I have sent it to you.

**Comment by NathanSweet** [comment]
Thanks. It was interesting to figure out. In skeleton "skeleton" you have two slots named "люди/verevki/na vsyakiy sluchai2" (note the Russian doesn't appear in Spine -- yet!) except one of the slots has a space at the end. Please find the slot with the space at the end (it's on the root bone) and delete the space.

Do you have any idea how you created a slot with a space at the end? The UI should not allow this.

**Comment by NathanSweet** [comment]
Also, your slots named "люди/verevki/na vsyakiy sluchai2" have the same problem.

**Comment by zapolnov** [comment]
Thank you very much that you have helped to find the problem. Actually, it would be much better if Spine would report an error instead of generating a json file that crashes the runtime :)

It was the artist who created it. I believe this is because originally image file names had space at the end (like "Hello, world .jpg"). When creating node from image, Spine names nodes after filenames. These already created problems with .atlas files (Spine runtime strips trailing spaces when parses .atlas file and so it fails with assertion because it can not find entry in the atlas), but the problem I have reported was much harder to diagnose for me :)

By the way, there are two more problems with filenames.
1) When generating an atlas file, spine strips path from the name, so if there are identically-named images in different subdirectories, they will generate two identical entries in the atlas file and that will result in a broken animation.
2) For some reason, Spine strips digits after `_` in some filenames resulting in an incorrect atlas. For example, for string `1306173384_broken_glass_01` it writes `1306173384_broken_glass` into an .atlas file. I don't know a reason for this, and I have just renamed such files.

**Comment by zapolnov** [comment]
Regarding the (1) - I have modified my version of spine runtime to strip filename from path. Because the default runtime reads file like "directory/file" from json and looks for it in the atlas file, but in atlas it is named just "file".  So I have added a "dirty hack" to strip everything before the last slash

**Comment by NathanSweet** [comment]
Yep, in v3 it trims names during data import and provides an error for duplicate names. It also fixes any projects with this error when opened. Also it trims names when creating slots and attachments from the image name. If the trimmed attachment name doesn't match the image file name, the attachment path is set to the untrimmed image file name.

1) Spine's texture packer only strips folder prefixes if `Flatten Path` is checked.
2) Spine's texture packer only strips underscore followed by a number suffixes if `Use indexes` is checked.

**Comment by zapolnov** [comment]
Thanks! I was working with Spine for the first time and I didn't know that this is configurable.
