### ISSUE TITLE
[Spine-Unity] SkeletonRenderer.CheckIfMustUpdateMeshStructure false negative

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#481]
This bug potentially causes the submesh to use an incorrect(un-updated triangle array) when slots switch between a RegionAttachment and a four-vertex MeshAttachment.

This is because SkeletonRenderer.CheckIfMustUpdateMeshStructure can't tell the difference between these two.

See this user's problem:
http://esotericsoftware.com/forum/Triangle-Missing-from-Image-in-Unity-Runtime-5458

I summon @LostPolygon , in attack mode.
Just dug this up. Haven't figured out a fix yet.

**Comment by LostPolygon** [comment]
Should be easy to fix by having the actual type of the attachment as a part of compared info. I'll look into into soon (ish).

**Comment by pharan** [comment]
Other things it should probably do in general if it's going to do this at all:
- Update triangle indexes when switching between two different MeshAttachments with the same number of verts and tris
- Update triangle indexes when draw order changes, even if no attachment changes happened. Active attachments could be any mix of Region and MeshAttachments.


I remember years back, we had to handle this stuff. SkeletonRenderer had an "alwaysUpdateTriangles" checkbox. Which it later did by default, and the checkbox was later turned into its opposite: "immutableTriangles" after these issues remained unsolved.

Immutable Triangles assumes you never change attachments or draw order.
Always Update Triangles assumed anything can happen (like the above cases).

**Comment by LostPolygon** [comment]
Pushed a fix to this. The idea is simple - instead of trying to compare specific properties of attachments (material, triangle count, etc.), compare the references to actual Attachments. This works, because, as long as I understand, the mesh structure of a *single attachment* is never changed (except when flipped).

**Comment by pharan** [comment]
Cool. I'll have to review SkeletonRenderer closely sometime. It's gotten to a point where I have no idea how it does things anymore.
