### ISSUE TITLE
[Spine-Unity] Flickering from incorrect double buffer handling

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#487]
@LostPolygon 
Has this been applied to the code yet? http://esotericsoftware.com/forum/Flickering-and-a-solution-for-it-5299
Seems like a few other people are having problems. http://esotericsoftware.com/forum/Animation-Disappearing-and-or-Blinking-5525

I'm planning to work on updating the runtime early next week to address the backlog.

**Comment by LostPolygon** [comment]
I haven't done anything regarding that particular issue. No repro - no fix :(
Perhaps maybe this issue also got fixed as part of other fixes _that are still not merged_...

**Comment by pharan** [comment]
Guh...

**Comment by pharan** [comment]
I had the flickering issue even after the merge.

I naively applied mrthebeej's fix to the latest SkeletonRenderer in my project and it seems to have fixed the problem.
But I'm not confident about the changes since I haven't closely examined how SkeletonRenderer currently works.

**Comment by LostPolygon** [comment]
Repro? Gimme

**Comment by LostPolygon** [comment]
But yeah, mrthebeej's fix actually seems to be quite reasonable...

**Comment by pharan** [comment]
Let me make a branch and you can check out the diff.

**Comment by pharan** [comment]
https://github.com/EsotericSoftware/spine-runtimes/commit/6778a039c6bad0a8e2808ac2b83cf25b918a402d

**Comment by pharan** [comment]
@LostPolygon I'm closely reviewing the SkeletonRenderer code now.

Did you wrangle all the dirty checks into the CheckIfMustUpdateMeshStructure for readability purposes or performance benefits of prefetch due to array access? 'cause it does immediately look like it has O(n) behavior in common cases.

Is it ok if modify it to put its attachment-match/count/flip checks right where LateUpdate iterates through the attachments?
