### ISSUE TITLE
[Starling] The mesh of animation with alpha incorrectly displays

### ISSUE THREAD

**Issue by pSi-X** [EsotericSoftware/spine-runtimes#489]
If the mesh animation with a change in the alpha channel, it appears black.
Example:
![Image of one](http://dl3.joxi.net/drive/0008/2829/535309/151204/3885d99d63.jpg)
Must be:
![Image of one](http://dl1.joxi.net/drive/0008/2829/535309/151204/eb8e539a2d.jpg)

Mistake might be in the class SkeletonSprite, in function addToBatch, here:
```
if (image) {
	a *= skeletonA * slot.a;
	r *= skeletonR * slot.r * a;
	g *= skeletonG * slot.g * a;
	b *= skeletonB * slot.b * a;
	polygonBatch.add(image.texture, worldVertices, verticesLength, uvs, triangles, r, g, b, a, slot.data.blendMode, matrix);
}
```
Must be:
```
if (image) {
	r *= skeletonR * slot.r * a;
	g *= skeletonG * slot.g * a;
	b *= skeletonB * slot.b * a;
	a *= skeletonA * slot.a;
	polygonBatch.add(image.texture, worldVertices, verticesLength, uvs, triangles, r, g, b, a, slot.data.blendMode, matrix);
}
```

**Comment by pharan** [comment]
I'm not sure how Starling (Flash?) defines blend functions but the above code works correctly for premultiplied alpha.

If the code on the bottom is for straight alpha blending, it should be:
```
    r *= skeletonR * slot.r;
    g *= skeletonG * slot.g;
    b *= skeletonB * slot.b;
    a *= skeletonA * slot.a;
```
