### ISSUE TITLE
Error when building in Unity 5.3.0f4 for Windows Store/Phone 8.1

### ISSUE THREAD

**Issue by actraiser** [EsotericSoftware/spine-runtimes#495]
Hi there,

I was just going to build my project in Unity 5.3.0f4 on a Windows 8.1 machine using Windows Store with Phone 8.1 option selected in the Unity Build Settings. I used "Windows 8 Store" before as the Build Target but this option has been removed from Unity as of 5.3.0 . 

With this I get errors from the .NET compiler.  While the messages are in German (sorry), the english CS–code description might be useful: 

CS1502: https://msdn.microsoft.com/en-us/library/b66k5sz9.aspx
CS1503: https://msdn.microsoft.com/library/8zf99ds2.aspx
CS0246: https://msdn.microsoft.com/library/w7xf6dxs.aspx

I do not exactly know where to start looking to debug. Maybe there is a #Define sitting somewhere in the spine–runtime code which does not consider the Windows Store/Phone8.1 environment. 
Does anyone have an advice or knows if this is a problem on the system side, hence unrelated to spine?

![bildschirmfoto 2015-12-23 um 14 52 25](https://cloud.githubusercontent.com/assets/5455/11977685/5fd8e5da-a985-11e5-8d5e-dace3416ecf3.png)

best and Merry Christmas
–act

**Comment by pharan** [comment]
I think someone submitted a PR for a related issue: https://github.com/witcher112/spine-runtimes/commit/14803b4fab189e4cb258a19c0456566a8225c9dd

It was merged a while back but I think that person was only using SkeletonBinary.
He seems to switch from BufferedReader to FileReader. There's definitely a difference between the libraries it needs to use when compiling for the old Metro/WP8 environment. This has been a sticking point for years. I'm not sure what classes should be replaced with which though, and we don't have a Windows phone setup to test.

Can you try applying these same changes in SkeletonJSON.cs and Atlas.cs and see if that fixes it for you?

**Comment by actraiser** [comment]
Thanks for the pointer! I will review the previous fixes in that PR after christmas and check if they can solve the problem.

**Comment by actraiser** [comment]
I found the solution in another forum post over at http://de.esotericsoftware.com/forum/Can-t-build-a-Windows-Store-App-with-Unity-Errors-4354

I had to remove the following methods to make the build work on Windows Phone 8.1 on Unity 5.3.0:

Atlas.Atlas(String path, TextureLoader textureLoader)
SkeletonBinary.ReadSkeletonData(String path)
SkeletonJson.ReadSkeletonData(String path)

–act

**Comment by pharan** [comment]
Thanks. I'd like to leave this issue open until we can make the code compile safely for Unity and UWP and Phone 8.1 without having to manually comment out lines.
