### ISSUE TITLE
error on importing spine-unity

### ISSUE THREAD

**Issue by kwickgames** [EsotericSoftware/spine-runtimes#497]
hey i am facing error on spine-unity package import i am using unity 4.6.1f1
i am attaching the error details.
![s1](https://cloud.githubusercontent.com/assets/16473476/12031258/a5f17302-ae2b-11e5-8cfe-459dd98b4e49.png)

**Comment by pharan** [comment]
Refer to thread: http://esotericsoftware.com/forum/spine-unity-has-lot-of-errors-on-import-5594
