### ISSUE TITLE
[Unity] Matrix stack full depth reached and IndexOutOfRangeException

### ISSUE THREAD

**Issue by kenmarold** [EsotericSoftware/spine-runtimes#501]
I'm getting two recurring errors in the Unity console window that endlessly loop when I click on my character's SkeletonData file. As a result I cannot interact with any SkeletonData in the Inspector window. Any ideas what's going on? Running Unity 5.3.0.

<img width="600" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5041536/12058513/8ba90ca2-af12-11e5-8a2a-dd1fe7f11836.png">

Matrix stack full depth reached
UnityEditor.Handles:DrawLine(Vector3, Vector3)
SkeletonDataAssetInspector:DoRenderPreview(Boolean) (at Assets/spine-unity/Assets/spine-unity/Editor/SkeletonDataAssetInspector.cs:683)
SkeletonDataAssetInspector:OnInteractivePreviewGUI(Rect, GUIStyle) (at Assets/spine-unity/Assets/spine-unity/Editor/SkeletonDataAssetInspector.cs:595)
UnityEditor.DockArea:OnGUI()

IndexOutOfRangeException: Array index is out of range.
SkeletonDataAssetInspector.DrawBoundingBox (Spine.Bone bone, Spine.BoundingBoxAttachment box) (at Assets/spine-unity/Assets/spine-unity/Editor/SkeletonDataAssetInspector.cs:712)
SkeletonDataAssetInspector.DoRenderPreview (Boolean drawHandles) (at Assets/spine-unity/Assets/spine-unity/Editor/SkeletonDataAssetInspector.cs:694)
SkeletonDataAssetInspector.OnInteractivePreviewGUI (Rect r, UnityEngine.GUIStyle background) (at Assets/spine-unity/Assets/spine-unity/Editor/SkeletonDataAssetInspector.cs:595)
UnityEditor.ObjectPreview.DrawPreview (IPreviewable defaultPreview, Rect previewArea, UnityEngine.Object[] targets) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/Editor.cs:225)
UnityEditor.Editor.DrawPreview (Rect previewArea) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/Editor.cs:530)
UnityEditor.InspectorWindow.DrawPreviewAndLabels () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:761)
UnityEditor.InspectorWindow.OnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:388)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by pharan** [comment]
Thanks for the report. This is definitely the first time I've seen this. We'll try to look into it but @Fenrisul is a bit busy these days. (He's the guy who implmeneted `SkeletonDataAsset`'s inspector preview thing)

For now, I think if you can find a way to collapse the preview panel (by left-clicking on the preview panel title bar once), that may prevent the error from firing.

Do you have especially complicated meshes in your skeleton that's causing this error?
Do you have simpler SkeletonData? Can you confirm whether or not that error fires on those as well?

**Comment by kenmarold** [comment]
Been trying different things and I've found that when I deleted the different Skins the error went away. Could you recommend a work-around for this? My character is needing to change weapon types and I've been using Skins for this, is there another way to accomplish this?

**Comment by kenmarold** [comment]
I'm also getting this error when I hit play in Unity:

System.ArgumentException: An element with the same key already exists in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.Int32,UnityEngine.GameObject].Add (Int32 key, UnityEngine.GameObject value) [0x0007e] in /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404 
  at SpineEditorUtilities.HierarchyWindowChanged () [0x00031] in /Users/kenmarold/GitHub/Prism (Mecanim)/Assets/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs:201 
  at SpineEditorUtilities.Initialize () [0x000dd] in /Users/kenmarold/GitHub/Prism (Mecanim)/Assets/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs:185 
  at SpineEditorUtilities..cctor () [0x00032] in /Users/kenmarold/GitHub/Prism (Mecanim)/Assets/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs:164 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

**Comment by pharan** [comment]
You can probably open up a thread in the forums for other problems.

**Comment by pharan** [comment]
Can you note anything unusual about your project?
'cause a lot of people use Spine-Unity and the features you mention and get none of these GUI errors.

**Comment by kenmarold** [comment]
I'll definitely get these errors into the forum. Are you referring to the forums on esoteric? I can't think of anything unusual about my project. This is the first character I've imported in to a new project.  The character consists of 11 animations and 4 skins.
