### ISSUE TITLE
Keys near the end of an animation can be dropped.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#502]
http://esotericsoftware.com/forum/Event-are-thrown-after-Complete-End-5005
An interesting point raised in the forum.

The sequence is normally:
```
state.update(deltaTime);
state.apply(skeleton);
```

If the animation doesn't loop. `state.update` can cause the time go past the duration/endTime of the `Animation` and cause the trackEntry to be cleared.
So by the time state.Apply does its thing, the current trackEntry will be null. No interpolation. No events. No nothing near the end.

This seems to mean a bunch of things:
- That the last key value has a teeny tiny chance of ever being applied. Essentially, you'll rarely see the final pose.
- Event and attachment keys that are near enough to the end (depending on the framerate) have very little chance of being applied or fired.
- At low-enough framerates and short-enough animations; events, poses, attachments, draworder keys... stuff breaks.

I guess the messy user-side fix is to somehow add an `apply` call right before it clears the trackEntry at the end of `AnimationState.update`.
This also affects all runtimes.

**Comment by NathanSweet** [comment]
Note update uses `lastTime`, so is always late 1 frame.
https://github.com/EsotericSoftware/spine-runtimes/commit/f8ad5514af548871af80b57797c0a91294f5cc37
