### ISSUE TITLE
[runtimes] Should SetSkin null slots?

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#506]
http://esotericsoftware.com/forum/Skinning-4726
http://esotericsoftware.com/forum/Problem-with-SetSkin-to-change-skin-at-runtime-Unity-5666

Use case:
Switching between skins. When different skins don't assign attachments to different skin placeholders.

Current behavior when you call SetSkin:
- if the slot setup pose is empty, the slot is untouched.
- if the skin doesn't have an entry for the slot setup pose attachment, the slot is untouched.
- because of that, when switching between skins with a different set of keys, some parts of a previously set skin will persist.

Expected behavior:
- When you switch between skins, whatever's not on that skin should not be visible (should be removed).

**Comment by pharan** [comment]
The code in question can be found here:
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Skin.java#L101
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Skeleton.java#L282

Both are kind of similar code.
Both also have null checks which prevent the attachment from changing at all, instead of being set to null, for the use case above.

One solution for this is to remove some null checks or explicitly set attachment to `null` in all cases.
The other solution is to add an extra boolean parameter to Skeleton#setSkin and Skin#attachAll to enable or disable this behavior.

The question is, why was it doing it this way originally? What cases are covered? To not accidentally remove programmatically set attachments?

**Comment by pharan** [comment]
Related issue: https://github.com/EsotericSoftware/spine-runtimes/issues/376

**Comment by NathanSweet** [comment]
A skin is used solely to look up attachments. Changing which skin is used to look up attachments doesn't necessary mean all the current attachments should be discarded. It also doesn't mean all the attachments in the new skin should be shown. When a new skin is set, attachments from the new skin are attached if the corresponding attachment from the old skin was attached.

If the new skin has attachments not in the old skin, how do we know they should be visible? If the old skin has attachments not in the new skin, how do we know they should be hidden? If both the old skin and new skin have an attachment but I've manually hidden it before setting the new skin, how do we know the attachment from the new skin should be visible? If neither the old skin nor new skin have an attachment, but I've set one manually before setting the new skin, how do we know the attachment should be hidden? (hint: all the answers are "we don't" :D)

For many skeletons, it may make sense for application code to call `setSkin` then `setSlotsToSetupPose`. For others, the runtime doesn't know what the application wants to do when the skin changes, so application code needs to manage when happens to attachments when the skin changes.

I'm open to making this more convenient. You described your proposed solution as "removing some null checks". How exactly would your proposal work?

**Comment by pharan** [comment]
> Changing which skin is used to look up attachments doesn't necessary mean all the current attachments should be discarded. It also doesn't mean all the attachments in the new skin should be shown.
A user setting a new skin never means he wants to combine it with the old skin though. If the new skin does attachment ANY replacement at all, it should never keep attachments from the old skin especially if it knows what the old skin is.

That was all [removing this null check](https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Skin.java#L107) meant.

After that, a majority of cases would be a lot easier to solve if the skeleton left an attachmentName in the slot whenever something tried to call `setAttachment` and the old skin didn't have a value to return. If this was there, the above solution would be complete.

I'm imagining a hilarious class called `NotFoundAttachment` just to subclass Attachment and have a mutable name and just sit there in the slot. It would only be instantiated the first time a skin lookup fails to return a value for that slot.

Without all this though, what's the vanilla recommendation for the common user?
`setSlotsToSetupPose`, then `AnimationState.apply` (assuming the new AttachmentTimeline behavior) then reapply all their manual changes?

(users relying on animation sideeffects need to swim in their miserable sea of side effects)

**Comment by NathanSweet** [comment]
> A user setting a new skin never means he wants to combine it with the old skin though. If the new skin does ANY attachment replacement at all, it should never keep attachments from the old skin especially if it knows what the old skin is.

You mean attachments in the old skin that are not in the new skin should never be left attached? I can agreed with that, at least I can't think of any scenario where you'd still want some attachments from the old skin (in that case, you should probably have them in the new skin). @badlogic want to make that change?

> Without all this though, what's the vanilla recommendation for the common user?

We don't know what the user wants attached. Our only information is what was attached in the old skin, so we use that information. If they would rather have the setup pose, then they can use `setSlotsToSetupPose`. If they would rather have something else, they'll need to set each attachment manually.

**Comment by badlogic** [comment]
Merged into https://github.com/EsotericSoftware/spine-runtimes/issues/841
