### ISSUE TITLE
[Starling] PolygonBatch flush()/resize() method bug

### ISSUE THREAD

**Issue by b005t3r** [EsotericSoftware/spine-runtimes#507]
In PolygonBatch class, when resizing above maximum capacity (method ```resize()```) ```flush()``` is called. In my scenario this method throws an exception at line 221:

```as3
_verticesBuffer.uploadFromVector(_vertices, 0, _verticesCount >> 3);
```

when it tries to upload more vertices than ```_verticesBuffer``` maximum size (max. size is set to 2000 vertices).

Let me know if you need more info.

**Comment by neuronix** [comment]
Hi, 

I'm running into the same issue. 2000 is very low. Is there any chance you can raise this limit or work around it ?

**Comment by rahulkamra** [comment]
any update on this? We are facing the same issue, Can we increase the 2000 value as starling limit is different.

**Comment by b005t3r** [comment]
Esoteric Software, come on. Are you going to at least say something? It's been almost 5 months. @NathanSweet, are you getting notified about this?

**Comment by NathanSweet** [comment]
Sorry for the delay. We've been run thin for some time, but we are working on expanding the team. We've been focused on the editor and admittedly the runtimes have suffered somewhat. This will change over the next few weeks.

There is no problem with raising `maxCapacity`. It needs to be large enough for the most vertices any single attachment will have. It also defines how much geometry is cached before being flushed.

I'll leave this issue open with our action item being making `maxCapacity` configurable through the API and possibly increasing the default value.

**Comment by b005t3r** [comment]
Sounds terrific, thanks!
