### ISSUE TITLE
[Starling] SkeletonAnimation still drawn even when visible is set to false

### ISSUE THREAD

**Issue by b005t3r** [EsotericSoftware/spine-runtimes#508]
If I add a ```SkeletonAnimation``` to stage and set its ```visible``` property to ```false``` it still gets displayed (not animated, but it looks like the first animation frame is still being rendered).

**Comment by b005t3r** [comment]
I see its probably the same problem as #416
And I can see it's not fixed since April.

**Comment by neuronix** [comment]
Hi guys,

Any news on this?

**Comment by badlogic** [comment]
This has been fixed in #416
