### ISSUE TITLE
[cocos2d-x] Animation element draws at wrong position

### ISSUE THREAD

**Issue by ignacio-pascual-plunge** [EsotericSoftware/spine-runtimes#509]
I have an animation in spine which an animated character hides in certain timing of the animation and then show up back when It plays other animation.

Through a graphic debbuger I could see that the char at the moment of "dissapear" what It is truly happening is char vertices draw in wrong positions (specificaly far more at the bottom from It should).

I guess the bug is at manipulating data, in plain c runtime.

I'm willing to share a faulty animation.

**Comment by pharan** [comment]
Hey. You're the first to report this but there was a recent change in the runtimes. When did you download your spine-runtime?

**Comment by ignacio-pascual-plunge** [comment]
Spine runtime which I'm using is up to date with cocos2d-x 3.8 branch.

I just updated changes manually in slot.c in relation with commit 318b9939e6d6cd84d292b5ebe11d0eac41c6f058 and that It didn't fix the issue.

**Comment by NathanSweet** [comment]
The renderer for cocos2d-x has been [rewritten](http://esotericsoftware.com/blog/C-C++-and-Objective-C-runtime-updates). Does this problem still persist?

**Comment by badlogic** [comment]
Please try the latest spine-cocos2dx runtime compatible with Spine 3.4.0. Will re-open if you can provide a reproduction case.
