### ISSUE TITLE
Error after importing spine-unity in assets

### ISSUE THREAD

**Issue by dusuney** [EsotericSoftware/spine-runtimes#511]
Error:
"Assets/Sprites/Player/SpineData/spine-unity/Assets/Examples/Scripts/Chimera.cs(21,59): error CS1061: Type `Skeleton' does not contain a definition for `FindSlot' and no extension method `FindSlot' of type `Skeleton' could be found (are you missing a using directive or an assembly reference?)"
I use Unity3d 5.2.3f1

**Comment by pharan** [comment]
That error doesn't make sense. How can the Skeleton class be defined without FindSlot defined?
That's also an oddly deep folder structure.

Is this the first time you imported Spine-Unity? What way did you import it? the unitypackage? or manually?

**Comment by dusuney** [comment]
I add manually
I also tried to create a new Unity project and add a spine-unity and csharp but received an error:
Assets/spine-unity/Assets/spine-unity/Editor/SkeletonBaker.cs(165,83): error CS0117: `UnityEditor.Animations.AnimatorController' does not contain a definition for `AddAnimationClipToController'

**Comment by pharan** [comment]
This is really weird. I've imported and reimported Spine several times in several projects for the past few weeks and it hasn't given me these errors.

Did you try importing using the .unitypackage too?

That second error, for some reason, the compiler thinks you're not on Unity 5. https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-unity/Assets/spine-unity/Editor/SkeletonBaker.cs#L135

That first error just makes no sense. There was never a time when Skeleton didn't have FindSlot.

**Comment by TAOOAT** [comment]
I have the exact same problem.
Assets/spine-unity/Modules/Mesh Generation Samples/VertexHelperSpineMeshGenerator.cs(91,30): error CS1061: Type `UnityEngine.Mesh' does not contain a definition for `SetVertices' and no extension method `SetVertices' of type `UnityEngine.Mesh' could be found (are you missing a using directive or an assembly reference?)

**Comment by pharan** [comment]
@TAOOAT 
Yours may be a separate issue. Are you using an older version of Unity? That method is supposed to exist and it's used by Unity's UI system.

anyway, you can delete the `Mesh Generation Samples` folder without problems.

**Comment by pharan** [comment]
I will be closing this issue. You will have better chances getting help in the forums where many users are more active! http://esotericsoftware.com/forum/viewforum.php?f=3

No other user seems to be having this problem and we have updated the runtimes several times already.
