### ISSUE TITLE
Update NuGet-package to Spine v3

### ISSUE THREAD

**Issue by Hinidu** [EsotericSoftware/spine-runtimes#516]
Hi, I found that you recently updated spine-csharp runtime. Could you please update NuGet-package?
Thanks.

**Comment by pharan** [comment]
There's a spine nuget package?

**Comment by Hinidu** [comment]
https://www.nuget.org/packages/Spine/

**Comment by pharan** [comment]
I don't think we know who this exDreamDuck guy is who uploaded that in the first place. (He probably shouldn't have used the Esoteric Software logo.)

**Comment by Hinidu** [comment]
Perhaps you could contact him and take ownership of this package?

**Comment by Hinidu** [comment]
How to treat closing of this issue? Are there any plans to publish up-to-date C# runtime on NuGet?

**Comment by pharan** [comment]
We maintain a lot of runtimes and we'd like to manage them here on github in one place.
I've tried to contact the owner of that nuget package and have not received a reply yet. In any case, the github repo will always be the most up to date.
