### ISSUE TITLE
Update spine-c runtime to v3

### ISSUE THREAD

**Issue by Hinidu** [EsotericSoftware/spine-runtimes#517]
Hi, we've already updated our Spine projects to v3 and we've really needed the updated spine-c runtime so we've made it ourselves. It still needs some testing though, but after that I could create a PR. Would it be helpful for you?
**UPDATE**
I didn't reinvent the wheel - I just ported the changes from spine-libgdx.

**Comment by pharan** [comment]
Already done: https://github.com/EsotericSoftware/spine-runtimes/commit/d7d08d263a4ee12fe21bc360e6f8194a971876ca

**Comment by Hinidu** [comment]
Haha, it seems that I've should ask about estimates before porting C# and C runtimes myself :laughing: Fortunately it took just about one day of work.
Thank you for your work!
