### ISSUE TITLE
Is spine-c v3 ready to use with the authoring tool?

### ISSUE THREAD

**Issue by iboB** [EsotericSoftware/spine-runtimes#523]
I'm using the spine-c stable release 2.1.25 and it works fine.

I tried integrating the v3 (which was very easy: I only had to rename "Skinned" to "Weighted"  in my code) and all bones with IK constraints broke. When IK constraints are not into play, everything is fine.

I haven't yet delved too deep in this, but it seems to me that spine-c v3 is somehow not intended for use with the latest version of the spine authoring tool or is just not completed.

Is this the case?

If not, maybe there are other changes I need to make. Are those documented? I can send you a very simple animation that looks different in the authoring tool from what it does in a simple integration (like the one in the sfml example).

**Comment by NathanSweet** [comment]
The [spine-c](https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-c#spine-version) page now has a section on Spine version compatibility.
