### ISSUE TITLE
bone scale and rotation inheritance

### ISSUE THREAD

**Issue by bp74** [EsotericSoftware/spine-runtimes#525]
Hi guys,

I did the Spine v3 update for my runtime (https://github.com/bp74/StageXL_Spine) and i wonder about the bone scale and rotation inheritance calculations. The Bone.updateWorldTransformWith method does those matrix mutliplications based on the data.inheritRotation and data.inheritScale settings. The question is if this is correct, because only the settings of the child bone is taken into account but not the settings of the parents. If you go up from one parent to the other wouldn't it be necessary to check the scale and rotation inheritance of each parent? Isn't it possible that for e.g. the first two parents inherit the rotation but the third generation parent does not?

Thanks guys, keep up the good work!

**Comment by pharan** [comment]
It does check all the parents' properties where it's necessary. What are you talking about?

**Comment by bp74** [comment]
I'm talking about parent.data.inheritRotation for example.
Your "What are you talking about" sounds a little bit hostile.

**Comment by pharan** [comment]
No hostility intended, I assure you. You have to admit, text communication has ambiguous tone most of the time unless you super edit it consciously.

By default, it inherits everything. If one of the transform operations' inheritance is disabled, it only needs to check its immediate parent 'cause it really only means "I shouldn't inherit my parent's rotation/scale". It does't tell its children what to do. It just gives them what it has (its transformation matrix, which may have ignored some portion of its parent's transformation matrix)
That's how it works, right? Were you thinking something else?

**Comment by bp74** [comment]
Thanks for your response and your explanation. I could be totally wrong and i probably miss something, but let me try to show you a little bit of the AS3 code to clear things up a bit. I think after this everything should be clear.

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-as3/spine-as3/src/spine/Bone.as#L127

			while (parent != null) {
				radians = parent.appliedRotation * MathUtils.degRad;
				cos = Math.cos(radians);
				sin = Math.sin(radians);
				var temp1:Number = pa * cos + pb * sin;
				pb = pa * -sin + pb * cos;
				pa = temp1;
				temp1 = pc * cos + pd * sin;
				pd = pc * -sin + pd * cos;
				pc = temp1;
				parent = parent.parent;
			}

This loop is executed in the case where data.inheritRotation = true and data.inheritScale = false. My question is if this loop should contain something like this:

				if (parent.inheritRotation == false) break;

The same thing for the case where data.inheritRotation = false and data.inheritScale = true. But i think you get the idea.

**Comment by NathanSweet** [comment]
Good catch! Cheers!

**Comment by bp74** [comment]
Great! Happy that it was a real issue and i didn't waste your time :)

**Comment by pharan** [comment]
Awesome.
