### ISSUE TITLE
[c] Using generic macro names cause name collisions

### ISSUE THREAD

**Issue by foofel** [EsotericSoftware/spine-runtimes#527]
Spine functions are prefixed with a "spFunctionName" it would be nice if the macros from extensions.h could also be prefixed. I have some variables named PI and DEG_RAD, RAD_DEG that are getting overwritten by spine macros. There are several very generic macro names that probably could also cause name collisions.

**Comment by NathanSweet** [comment]
The only place we define generically named macros is in `extension.h`, which should not need to be included for your application code. It should only be needed to extend spine-c to work for a particular game toolkit. Are you using `extension.h` in a different way?

**Comment by badlogic** [comment]
Works as intended. Will re-open if @foofel can show his use case for including `extensions.h`
