### ISSUE TITLE
Example links in the readme are not working 404 :)

### ISSUE THREAD

**Issue by Gamezpedia** [EsotericSoftware/spine-runtimes#533]
Hi

Example links in the readme are not working 404 :)

thanks

**Comment by NathanSweet** [comment]
Which links are broken? We have READMEs for all 20 runtimes.

**Comment by Gamezpedia** [comment]
Hi , 

in > https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-as3

Demo Link:
http://esotericsoftware.com/files/demos/as3/spineboy/index.html

Giving page not found :)

**Comment by NathanSweet** [comment]
Thanks!
