### ISSUE TITLE
[runtimes] Queued Animations custom start time

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#535]
This code modifies TrackEntry's `.time` field.
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-csharp/src/AnimationState.cs#L88
```
				TrackEntry next = current.next;
				if (next != null) {
					next.time = current.lastTime - next.delay;
					if (next.time >= 0) SetCurrent(i, next);
				}
```

Because of this, you cannot pre-set TrackEntry's time and expect it to play starting at that point when its turn comes up in the queue.

**Comment by NathanSweet** [comment]
If we add `startTime` to solve #593, then it would also solve this issue. However, it would break anyone who is currently relying on setting `time` and then calling `setAnimation`.
