### ISSUE TITLE
[Spine-Unity] Use namespaces

### ISSUE THREAD

**Issue by LostPolygon** [EsotericSoftware/spine-runtimes#538]
There is no good reason not to use namespaces these days. There were some problems with them in pre-4.5 era, but that's ancient history now. Having a ton of Spine-Unity stuff in global namespace is seriously annoying.

**Comment by pharan** [comment]
Yeah. It's the future. Spine 3.1. And Unity 5.4 is coming tomorrow, I think it's high time.

I actually already started using the `Spine.Unity` namespace for new classes. I'll likely make this change pretty soon.

**Comment by LostPolygon** [comment]
> And Unity 5.4 is coming tomorrow
Coming June 2016. But yeah.

**Comment by pharan** [comment]
They announced the new "public beta" after I said it. It was scheduled for March 16, but it looks like they're just turning EVERYONE into beta testers and delaying a release for one whole update cycle.
Damnit, Unity. They've been pushing things back a lot lately. Still no new 2D tools.

**Comment by LostPolygon** [comment]
To be honest, I approve that. Unity have gone too far with releasing
unstable releases that add a ton hardly working features and regressions.
And now they finally seem to understand that. I'd happy to have a version
of Unity that *actually* works smooth, something that I miss 4.x for.

No new 2D tools sucks, though.

**Comment by pharan** [comment]
The only thing they've done seems to be give themselves permission to be sloppy by releasing as beta what should've been a full release. I guess I appreciate the honesty. I do think they shouldn't call it finished when it's not. And if they need more time to work on a feature, sure, they should adjust their release schedule so it's realistic. At least they have more people to test it now, if that's any help.

I agree though. 4.x was nice and stable. I haven't had huge problems in 5.x myself but man are people pissed with 5.3.

I just tried 5.4b10 on my project and it just went haywire. It's not even stable enough to test there.

**Comment by LostPolygon** [comment]
@pharan 
Perhaps editor stuff should be put in a separate namespace, like `Spine.Unity.Editor`? Similar to what Unity does with `UnityEngine` and `UnityEditor`. Would make everything a little bit cleaner, I guess.

**Comment by pharan** [comment]
I want to find out where the line is. I don't want to go overboard and oversegregate everything.
That's noted though. I was just making some inspector stuff and I kept code completion kept hitting some Spine classes.

**Comment by pharan** [comment]
@LostPolygon 
The funniest thing. If you put it in the namespace `Spine.Unity.Editor`
and you use the UnityEditor.Editor class but only refer to it as `Editor`, the IDE gets confused and thinks `Editor` means `Spine.Unity.Editor`.

**Comment by LostPolygon** [comment]
@pharan 
Umm... Well, it kind of makes sense, since namespaces are hierarchical, the only problem is that `Editor` is also a name of the class. I guess it's not a big deal to just use `UnityEditor.Editor` instead?

**Comment by pharan** [comment]
@LostPolygon 
Even weirder:
When Editor A is within the `Spine.Unity.Editor` namespace.
And another Editor B is within the `Spine.Unity` namespace. All mentions of `Editor` within Editor B are interpreted as being Spine.Unity.Editor.

This is hilarious!
