### ISSUE TITLE
[cocos2dx] I Just create a SkeletonAnimation, but then Chinese characters missing(Mobile Sony Xperia Z2).

### ISSUE THREAD

**Issue by ypfsoul** [EsotericSoftware/spine-runtimes#541]
I create a SkeletonAnimation like this.
{
SkeletonAnimation* skeletonNode = SkeletonAnimation::createWithFile("spine/spineboy.json", "spine/spineboy.atlas", 0.6f);
}

And when I use 
{
CCString::createWithFormat(sa.c_str(), hero_head[_iIndex])->getCString()
}
or
{
	std::string sFormat = GETLANGSTR(226);//sFormat = "%d级开放"
	char buff[60];
	sprintf(buff, sFormat.c_str(), 5);
}

Chinese characters is missing !

It's not a problem about text formatting.(utf-8 no bom, ensure)

So I Annotation the code that creat skeletonNode, then Chinese characters is show normally.
I tried so many mobile, It only happens on Sony Xperia Z2.

spine-runtime: Latest commit c8afc24(latest version master)
cocos2dx:2.2.3
mobile:Sony Xperia Z2(Just happen on it)

Thanks, I need help!

**Comment by NathanSweet** [comment]
Sorry, I'm having a hard time understanding. Where are the Chinese characters missing? Do you mean the names of bones, slots, etc in your skeleton data?

You said, "I Annotation the code that creat skeletonNode, then Chinese characters is show normally." I don't understand, did you fix the problem? How?

**Comment by badlogic** [comment]
Will re-open if more info comes in.
