### ISSUE TITLE
Is worldToLocal correct?

### ISSUE THREAD

**Issue by ivanpopelyshev** [EsotericSoftware/spine-runtimes#544]
Hello! I'm updating pixi.js spine runtime. While copying new 3.0 code i found this thing:

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Bone.java#L359

```javascript
world.x = (x * a * invDet - y * b * invDet);
world.y = (y * d * invDet - x * c * invDet);
```

while my math sence tells me that this one is correct:

```javascript
world.x = (x * d * invDet - y * b * invDet);
world.y = (y * a * invDet - x * c * invDet);
```

In most cases, a==d, but if we apply some skew it might be a problem, and IK will behave differently.

**Comment by ivanpopelyshev** [comment]
Oh, I just noticed that its not used anymore. Not critical, then :)

**Comment by NathanSweet** [comment]
Yessir, you are right! Good catch!

It's a convenience method, so API users don't have to figure it out. It's not much help when it's wrong though, eh? ;)
