### ISSUE TITLE
Something wrong with binary

### ISSUE THREAD

**Issue by semgilo** [EsotericSoftware/spine-runtimes#546]
runtime 2.3
Something different binary data with json data,when i use json then skinnedmesh triangles is normal,and binary data is wrong 

there isn't "edges" ,"width" and "height" in skinned mesh

**Comment by pharan** [comment]
Which runtime/framework?

**Comment by semgilo** [comment]
i try to finish binary reader in cocos2dx-framework, i debug it, and found skinned mesh triangles is wrong sometime.

**Comment by pharan** [comment]
The current spine-c and cocos2dx supports Spine version 3.0: https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-cocos2dx/3#spine-version

The current Spine editor version is 3.1.05.
You may have to roll back your Spine editor for binary to be compatible with the runtime. Updates are coming soon. New features were added in 3.1 and 3.1.05 and that changed the binary format.

**Comment by NathanSweet** [comment]
Remember when the binary format changes, you have to export your data from Spine again. 3.1.05 was just released and changed the binary format, see that commit: 3a06b829cc81203ebeec996efad33e4bef6cc8c7 Also the binary format is now [documented](http://esotericsoftware.com/spine-binary-format).

**Comment by westsuper2** [comment]
I'm doing the something. shall we do it together? @semgilo

**Comment by semgilo** [comment]
@westsuper2  yes, with pleasure

**Comment by semgilo** [comment]
@Fraggle @NathanSweet spine 2.1.27  i can read format correctlty, but i compare with json data,  attachment mesh's triangles is diff sometimes, most of time they are same

**Comment by westsuper2** [comment]
I have make a QQgroup. num:245799483.welcome ! @semgilo

**Comment by semgilo** [comment]
@NathanSweet @Fraggle 3q for reply,i had find found issue, the reason is  forgot to memset memory block!!
