### ISSUE TITLE
Add bower.json file

### ISSUE THREAD

**Issue by goldsam** [EsotericSoftware/spine-runtimes#548]
Adding a bower.json file would greatly enhance usability of this library by enabling it as a bower dependency.

**Comment by pharan** [comment]
Can you elaborate?

**Comment by goldsam** [comment]
It would be very nice to include the spine-js run-time as a dependency when developing in javascript using [bower](http://bower.io/) as a dependency manager. I have creating a bower.json file for version 2.1.25 in [PR550](https://github.com/EsotericSoftware/spine-runtimes/pull/550).

**Comment by NathanSweet** [comment]
We can track this in the PR.
