### ISSUE TITLE
PolygonSpriteBatch doesn't have transparent [Libgdx Spine runtime]

### ISSUE THREAD

**Issue by MrGru** [EsotericSoftware/spine-runtimes#556]
I use Libgdx spine runtime with polygonSpiteBatch, but it doesn't have transparent?

**Comment by NathanSweet** [comment]
It doesn't have transparency? Please ensure the premultiplied alpha texture atlas setting matches the premultiplied alpha setting on the SkeletonMeshRenderer.

**Comment by badlogic** [comment]
Closing this out, works as intended.
