### ISSUE TITLE
Broken text PPtr in file error

### ISSUE THREAD

**Issue by MrTactic** [EsotericSoftware/spine-runtimes#557]
![2016-04-19 15 51 33](https://cloud.githubusercontent.com/assets/6072592/14642720/40457ee6-0654-11e6-8d28-cf8cffd9e71e.png)

Have this problem importing spine animation and change/save animator states

Unity 5.3.4p2
spine-unity-v2.unitypackage

**Comment by LostPolygon** [comment]
This actually looks more like a Unity bug. Or, the Animator Controller is not generated correctly... I guess it'd be easier to fix if you shared the problematic controller file.

**Comment by MrTactic** [comment]
I install Unity 5.4 beta15 and problem disappeared

**Comment by badlogic** [comment]
Thanks, closing this out.

**Comment by duriumm** [comment]
Is there a fix to this issue?
