### ISSUE TITLE
[spine-unity] Can't support new Shear tool

### ISSUE THREAD

**Issue by feisan** [EsotericSoftware/spine-runtimes#560]
After import resource into Unity, get these message:

```
Error reading skeleton JSON file for SkeletonData asset: skeleton_SkeletonData
Invalid timeline type for a bone: shear (root)
```

**Comment by MartinSenovsky** [comment]
Look at SkeletonJson.cs line 510 and add else if(timelineName == "shear") //do nothing, else throw exception. And wait while they add it o:)

**Comment by pharan** [comment]
This is coming with spine-csharp 3.2.
