### ISSUE TITLE
[spine-unity] OnPostprocessAllAssets crash

### ISSUE THREAD

**Issue by alexandershestakov** [EsotericSoftware/spine-runtimes#561]
Hi, I'm on Unity 5.3.4p5, Spine runtime 2.3. On our build machine we started getting an exception thrown by Spine, an InvalidCastException. 

Here's how I've fixed that, in SpineEditorUtilities line 720 replace
`Dictionary<string, object> root = (Dictionary<string, object>)obj;`
with
`Dictionary<string, object> root = obj as Dictionary<string, object>;`
`if (root == null) return false;`

To be honest I'm surprised you guys assume that jsons can't be arrays and it didn't pop up earlier :)

**Comment by pharan** [comment]
Thanks for reporting!
That code hasn't been touched for almost a year now (the one who wrote it hasn't been with the team).

The Json contract may have changed since we switched our JSON deserializer. Nobody's ever run into this problem though.
