### ISSUE TITLE
[cocos2d-x] Crash on iOS when system UI is triggered

### ISSUE THREAD

**Issue by jamesnoble** [EsotericSoftware/spine-runtimes#564]
I'm seeing a crash in my cocos2d-x application on iOS when recieving a notification popup, activating notification center, or activating control center with a spine animation on-screen.

I think it's related to SkeletonBatch resetting `_position` in the update method. When cocos2d-x's Director is paused (as happens when the previously mentioned system UI is activated while your application is active) updates scheduled with the Director aren't called, but rendering continues. This is causing `_position` to never be reset, and so the buffer resizing code in `SkeletonBatch::addCommand` is being run when it doesn't really need to be.

After this buffer resize happens, I'm seeing a crash in cocos2d's Renderer, in `Renderer::fillVerticesAndIndices.`

**Comment by gitshah** [comment]
I am facing the same issue.  Do we have any workaround for this?

**Comment by gitshah** [comment]
Ok so I kind of found a fix for this issue.  Here is the pull request: https://github.com/EsotericSoftware/spine-runtimes/pull/605

@jamesnoble Could you please try it out to see if it fixes the issue for you too?

**Comment by badlogic** [comment]
Thanks to @gitshah this should be resolved now. @jamesnoble please report back if this fixes the issue for you.
