### ISSUE TITLE
[libgdx] Gradle support

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#567]

**Comment by pharan** [comment]
Just linking an old issue I closed 'cause I did put this request on a separate list. https://github.com/EsotericSoftware/spine-runtimes/issues/330

**Comment by badlogic** [comment]
Filed for access to groupId on SonaType https://issues.sonatype.org/browse/OSSRH-28973

**Comment by badlogic** [comment]
Got rights to publish to SonaType. Don't forget to post on their tracker once we publish the first artifact. https://issues.sonatype.org/browse/OSSRH-28973

**Comment by badlogic** [comment]
Done! See updated [README.md](https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-libgdx/README.md)
