### ISSUE TITLE
[cocos2d-x] std::max in XCode

### ISSUE THREAD

**Issue by mars3142** [EsotericSoftware/spine-runtimes#570]
The current cocos2dx commit 8d7f761 doesn't compile within XCode.

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-cocos2dx/3/src/spine/SkeletonBatch.cpp#L85 is the problem, because std::max isn't working: **No matching function for call to 'max'**

**Comment by 215566435** [comment]
Hi man, i think we have same issue there.
I just rewrite a function call man above the skeleton batch.cpp
and bon~~~~~voyage

**Comment by badlogic** [comment]
This should be fixed, works in Xcode 7+.
