### ISSUE TITLE
[Unity][2D Toolkit] ";" - lost

### ISSUE THREAD

**Issue by nosick** [EsotericSoftware/spine-runtimes#576]
v2.1.25
error CS1525: Unexpected symbol `skeletonDataScale'
![2016-05-17 10 58 00](https://cloud.githubusercontent.com/assets/4725570/15315139/894c1034-1c1e-11e6-89b5-da6e66250b16.png)

**Comment by pharan** [comment]
Thanks for reporting.
If I add the semicolon, does it work just fine?

**Comment by pharan** [comment]
This doesn't seem to be an error in the latest version: https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-unity/Assets/spine-unity/Asset%20Types/SkeletonDataAsset.cs#L115
