### ISSUE TITLE
[spine-js] sourceAttachment is not defined

### ISSUE THREAD

**Issue by olssonfredrik** [EsotericSoftware/spine-runtimes#577]
There is an `Uncaught ReferenceError: sourceAttachment is not defined` in `spine.FfdTimeline.apply`

`if (slotAttachment != this.attachment && (!slotAttachment.inheritFFD || slotAttachment.parentMesh != sourceAttachment)) return;`

[https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-js/spine.js#L982](https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-js/spine.js#L982)

**Comment by NathanSweet** [comment]
Sorry about that. Fixed in d7633706e7cd2dae163e1b4fac376e19e5889620
