### ISSUE TITLE
Assert failed: Invalid timeline type for a bone: shear

### ISSUE THREAD

**Issue by JarvisMMMM** [EsotericSoftware/spine-runtimes#581]
"bones": {
			"bone7": {
				"rotate": [
					{ "time": 0, "angle": 0 }
				],
				"translate": [
					{ "time": 0, "x": 0, "y": 0 }
				],
				"scale": [
					{ "time": 0, "x": 1, "y": 1 }
				],
				"shear": [
					{ "time": 0, "x": 0, "y": 0 }
				]
			},

Assert failed: Invalid timeline type for a bone: shear
what can I do?

**Comment by pharan** [comment]
"Shear" is a new bone property added in Spine 3.2

Practically all runtimes are still officially at version 3.1.

What you can do:
You can remove all the "shear" animation items from the json.

Alternatively, you can also force your runtime to ignore shear.

**Comment by NathanSweet** [comment]
Removing shear timelines from the dopesheet in Spine will also remove it from the JSON.

Really though, it is safest to use the editor version that matches when the runtime you are using supports.

**Comment by JarvisMMMM** [comment]
I have solved it.
it's to much "shear" form the JSON,
so,I'm forced to ignore it.
