### ISSUE TITLE
Update runtimes to support v3.2 (shearing)

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#586]
* Bone shearing.
* ShearTimeline.
* Transform constraint offsets and mixes.
* TransformConstraintTimeline.
* Skeleton#updateCache fixes.
* JSON and binary format updates.

- [x] spine-libgdx
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d
- [x] spine-c
- [x] spine-sfml
- [x] spine-cocos2d-iphone
- [x] spine-cocos2dx
- [x] spine-as3
- [x] spine-starling
- [ ] spine-js
- [ ] spine-turbulenz
- [ ] spine-threejs
- [ ] spine-lua
- [ ] spine-love
- [ ] spine-corona

**Comment by badlogic** [comment]
Closing this, covered by v3.4 runtime update issue.
