### ISSUE TITLE
Update spine-starling to Starling v2

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#591]
http://esotericsoftware.com/forum/Starling-v2-support-5947

**Comment by israelazo** [comment]
+1 

(sorry for duplicate comment)

**Comment by badlogic** [comment]
We are going to remove starling v1 support and only support v2 going forward. Seems the Starling maintainers will not backport anything to v1 and won't do maintenance.

**Comment by neuronix** [comment]
Thanks for the update @NathanSweet  and @badlogic ! :)
