### ISSUE TITLE
[runtimes] Runtime utilities

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#592]
It would be convenient to provide functions for common tasks across all runtimes:
- Creating an attachment with an arbitrary image.
- Skin#add(skin) Add all the attachments from one skin to another. This allows a new skin to be a combination of multiple other skins.
- Skeleton#clearAttachments() Remove all attachments.
- Skeleton#setAttachments(skin) / Skeleton#clearAttachments(skin) Attach/remove all attachments in the skin. Possibly revisit how Skeleton#setSkin(skin) works. http://esotericsoftware.com/forum/viewtopic.php?f=9&t=3700

**Comment by pharan** [comment]
linking because related: https://github.com/EsotericSoftware/spine-runtimes/pull/465

Also related to skins and "creating an attachment with an arbitrary image" at runtime:
- Make a new linked mesh. (provide parent mesh and region/image)
- Duplicate an attachment but with a different region/image.
- Change a RegionAttachment/MeshAttachment's region/image (for cases where the attachments aren't shared/the skeleton is only ever instantiated once).

**Comment by pharan** [comment]
May be relevant: https://gist.github.com/pharan/d3597424698a47925ca34f3e0e7cebcf

Also additional API ideas:

### copy constructors
- new RegionAttachment(RegionAttachment) - copy constructor
- new MeshAttachment(MeshAttachment) - copy constructor
- new MeshAttachment(MeshAttachment, boolean linked) - create a new linked mesh
- new BoundingBoxAttachment(BoundingBoxAttachment) - copy constructor
- path attachment??

#### setRegion
- RegionAttachment.setRegion(AtlasRegion)
- MeshAttachment.setRegion(AtlasRegion)
- runtime-specific stuff that can create AtlasRegions, and/or set regions based on a runtime structure?

#### Skin stuff
- new Skin(Skin) - copy constructor
- Skin.add(Skin) - adds/overwrites skin entries using another skin. For mix and match.
- Skin Skeleton.unshareSkin() - gets a copy of the current active skin and default skin combined. sets it to the currently active skin. This allows the user to make any changes to that skin without affecting other instances.
- Skin.unshareAttachments(bool linked) - replaces all attachments with clones. Optionally clone MeshAttachments as linked meshes. This allows the user to make changes to the attachments without affecting other skins that may use the same attachments (say if it came from the default skin).
- static Skeleton.reapplyActiveSkin(skeleton, AnimationState) - calls setSlotsToSetupPose and AnimationState.apply (AttachmentTimeline.Apply for all slots) to reapply all the appropriate attachments after a skin change. Previous attachment changes done directly through setAttachment must be reapplied after.

**Comment by badlogic** [comment]
Merged info from here into https://github.com/EsotericSoftware/spine-runtimes/issues/841

The skin helper methods can be done with the new skin API. I don't like having a hundred ways of doing something, but we can add those helpers later if necessary.
