### ISSUE TITLE
Not support multi materials with SkeletonGraphic

### ISSUE THREAD

**Issue by shadow0162** [EsotericSoftware/spine-runtimes#597]
Spine animation imported by Unity GUI.
![ce10z1ku9vbm cx rja5afc](https://cloud.githubusercontent.com/assets/2087112/15740242/a1e80650-28e6-11e6-8406-c1499ef4669f.png)
Not support multi materials with SkeletonGraphic module.

**Comment by pharan** [comment]
Single-texture/single-material is a limitation of MaskableGraphic which SkeletonGraphic uses so that masking works.

**Comment by shadow0162** [comment]
All right, we made multi to single.
