### ISSUE TITLE
JS Runtime Error

### ISSUE THREAD

**Issue by pinguin999** [EsotericSoftware/spine-runtimes#598]
Hi I tried the js example with my spine model and get this error:

TypeError: this.attachmentLoader.newWeightedMeshAttachment is not a function
spine.SkeletonJson.prototype.readAttachment()
spine.js:2100
spine.SkeletonJson.prototype.readSkeletonData()
spine.js:1995
spine.SkeletonRenderer.prototype.load()
spine-canvas.js:58
<anonym>

In the js debugger newWeightedMeshAttachment and newMeshAttachment are missing in this.attachmentLoader (at line 2100 )

But I can not find the error. Any Ideas?

**Comment by badlogic** [comment]
The spine-js runtime has not been updated to the latest Spine version yet. It currently supports exports from Spine 3.1.08. The way meshes are encoded in the exports has changed in Spine 3.2.0. You can switch to an older Spine version in the settings dialog for now. I'm updating the spine-js runtime to 3.4.0 at the moment.

I'm closing this out if OK. Watch the forums or this repo for updates on the spine-js runtime.
