### ISSUE TITLE
Fix mesh bugs in spine-lua

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#601]
We've not had a Lua game toolkit that renders Spine meshes until now -- Corona can as of #600. We need to fix up bugs related to mesh support in spine-lua. Eg, the raptor cannot be rendered.

**Comment by Shchvova** [comment]
To kick the train going, I'll throw in some work-in-progress I got.
1. I got atlas importer working for Corona. [Here](https://gist.github.com/Shchvova/90a56bc8a691569782454354fa6f1b54) it is.
2. [Here's](http://i.imgur.com/6obHpSB.gifv) vid of Raptor demo rendered from atlas (I didn't master perfect loops, sorry)
3. There are some issues in math in Animation.lua, and I expect others. To get raptor going I had to put in [this](https://gist.github.com/Shchvova/b8e9f73a4020cebacb4556191cebcdbf) hacks
4. This is why you see glitches. This patch ins't a fix. Just a way for me to get atlas imported working somehow. It's WIP as well. I think it should be part of spine-lua and part of it in spine-corona

**Comment by ggcrunchy** [comment]
Ah, nice to hear about #1. I pretty much skirted around that.

Assuming this wasn't fixed since the last version I saw... animation-wise, there's a little skip when a **basic** mesh goes from its final frame to its first one (I think). I expect this is a simple fix-but never got around to dealing with it. I was concentrating on the FFD timeline and got a bit of tunnel vision. :smile:

**Comment by Shchvova** [comment]
I updated loader in [1](https://gist.github.com/Shchvova/90a56bc8a691569782454354fa6f1b54) and patch in [3](https://gist.github.com/Shchvova/b8e9f73a4020cebacb4556191cebcdbf), so raptor moves nice and smooth. Required version of corona is `2016.2892` for atlas loader to work properly.

**Comment by Shchvova** [comment]
Hello! I created pull request for atlases in Lua runtime (#620) and Corona in particular. Documentation is in pull request, as well as [here](https://gist.github.com/Shchvova/8749454260e9e38eb194e1d511919dcd).

**Comment by badlogic** [comment]
Merging this issue with https://github.com/EsotericSoftware/spine-runtimes/issues/613

@Shchvova I'll cherry pick from your PR for the 3.4.0 update of the spine-lua/spine-corona update. Thanks!

**Comment by Shchvova** [comment]
@badlogic Sure! Just in case, that pull request ins't a fix for any of the issues in Meshes, just parsing and Corona adaptation of `.atlas` files
