### ISSUE TITLE
[lua][corona] Spine-corona mesh will remove-create every frame

### ISSUE THREAD

**Issue by zero-meta** [EsotericSoftware/spine-runtimes#606]
In Spine.lua:240
    I add (image.attachment == image.attachment) below to fixed it.
This is a tiny bug. Issue 603 is more important.

**Comment by NathanSweet** [comment]
This isn't a bug, it is done to ensure the draw order is correct.

**Comment by zero-meta** [comment]
The draworder is updated by 
     self.group:insert(image)
My handwriting is wrong.
Aactually, I add 
   (image. attachment = attachment)
to fixed it.
Without this reference to current attachment, it will remove and then create the same mesh every frame.

**Comment by badlogic** [comment]
Fixed in spine-lua-branch, to be merged into master.
