### ISSUE TITLE
[Unity] Skeleton graphic module, Animator can't play any animation.

### ISSUE THREAD

**Issue by shadow0162** [EsotericSoftware/spine-runtimes#609]
In Skeleton Graphic Module, Animator can't play any animation. Skeleton Graphic script can play only one animation at starting in inspector.How can i play animations by animator compnonet?By the way ,the skeleton animation is work well.
![i9_3w0s6uhuzc9 b lsothj](https://cloud.githubusercontent.com/assets/2087112/16069663/c9681078-3302-11e6-937c-acb345fd01fa.png)

**Comment by pharan** [comment]
This is not supported.
SkeletonGraphic is controlled via the Spine.AnimationState API: http://esotericsoftware.com/spine-unity#For-Typical-Use
