### ISSUE TITLE
Update runtimes to support v3.4 (paths)

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#613]
- [x] spine-libgdx
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d
- [x] spine-c
- [x] spine-sfml
- [x] spine-cocos2d-iphone
- [x] spine-cocos2dx
- [x] spine-as3
- [x] spine-starling
- [x] spine-js
- [x] spine-turbulenz
- [x] spine-threejs
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

**Comment by cqgreen** [comment]
Do you have the schedule for spine-unity?

**Comment by Hinidu** [comment]
I've started to update `spine-c` runtime in #619.

**Comment by xee3d** [comment]
When do you think 
The spine unity work will be done

**Comment by NathanSweet** [comment]
So glad to see this issue closed! 👯
