### ISSUE TITLE
Information related to spine versions sucks and needs fixing

### ISSUE THREAD

**Issue by neuronix** [EsotericSoftware/spine-runtimes#615]
The editor auto updates but runtimes are released afterwards. Github is full of "updated readme for v3.3" so at first glance, runtimes look up to date! Yay! 

Half a day lost trying to find out why all our animations are crashing, we finally find that in fact, as3 runtime only supports .... 3.1.08 ! That's 2 versions ago!

So we launch the editor with 3.1.08, and now all our projects crash.. since they were saved with editor 3.3.

Seriously guys, this is ridiculous. 

1. Runtimes on github should have the current supported version in the title : spine-as3 (v3.1.08)
2. Editor should NOT auto-update but ask user if update is required and warn about the runtime issue.

**Comment by neuronix** [comment]
3. You could have a select on the editor with a list of runtimes, allowing auto-updates to supported versions only
4. You could include a version number in the runtime source and compare it with a version number in the exported files and trigger an error/warning

**Comment by AIGRIND-LLC** [comment]
@neuronix you are right )
There are some "vision" explained by @NathanSweet and workaround that could help you to revert projects to previous version (look at JsonRollback utility).
http://esotericsoftware.com/forum/Spine-editor-and-runtime-version-management-6534

**Comment by NathanSweet** [comment]
Aye, we'll be improving things as explained in that thread. Sorry for the trouble in the meantime.
