### ISSUE TITLE
[lua][corona] Spine runtime bad performance

### ISSUE THREAD

**Issue by torbenratzlaff** [EsotericSoftware/spine-runtimes#622]
The current runtimes for Corona SDK and LUA in general have great potential for performance optimization. Or to put it in other words, the LUA implementations are unefficient.

General LUA optimization rules are ignored, like:
1. Localizing values (table fields, estimated values, global libraries etc.) is ignored nearly completely, especially in time critical processes like loops this becomes a problem.
2. The runtime creates new objects (attachments, slots, bones etc.) in a OOP manner, but makes no use of metatables. This creates a huge overhead, because every object has its own new functions which take up memory.

There are many guides for LUA optimization, one of the most general ones was published by the LUA team itself:
https://www.lua.org/gems/sample.pdf

I did the optimizations for myself and I've got great performance and memory consumption improvements when using more than 2 or 3 spine objects at once. (I would send you those or create a new fork for them if you are interested)

**Comment by pharan** [comment]
Thanks for reporting and for the link!

If you could share the code through a fork or pull request, that would be informative too.

**Comment by torbenratzlaff** [comment]
The thing is, the runtime I optimized is about 11 month old and has none of the current bug fixes and features implemented. If you want to check it out anyways, here is the link to the fork:
https://github.com/torbenratzlaff/spine-runtimes/tree/master/spine-corona/spine-corona

The whole LUA specific files are in the same folder as the Corona one, as that is how I use it in my projects.

**Comment by torbenratzlaff** [comment]
I compared the current Corona/LUA Version with the one I worked on a year ago, and most things are unchanged (except some Bug fixes and the mesh support of course). So it shouldn't be a big deal to convert the optimization to the new version :)

**Comment by badlogic** [comment]
This has been fixed, thanks @torbenratzlaff for the pointers!
