### ISSUE TITLE
spine mesh tangent mistake [Spine-Unity]

### ISSUE THREAD

**Issue by smartether** [EsotericSoftware/spine-runtimes#632]
According to SkeletonRender.cs script , "Vector3 tangent = new Vector3(0, 0, 1)" ,
Spine generated mesh is assigned tangent to (0,0,1),
If i change render's shader to Bumped Diffuse and put a pointLight behind the spine mesh,
The light is effect on the mesh,
![spine_tangent_error](https://cloud.githubusercontent.com/assets/3928724/16795215/aacb6c60-490e-11e6-8195-3d3d5ef7e753.png)

if i put a pointLight front of the spine mesh, the light is not effect on the mesh,
![spine_tangent_error1](https://cloud.githubusercontent.com/assets/3928724/16795348/7c4d7bf2-490f-11e6-8470-5a7993814831.png)
![spine_tangent_error2](https://cloud.githubusercontent.com/assets/3928724/16795358/802b9b1e-490f-11e6-8adf-0782ba6861f6.png)

Is something mistake on tangent  calculating?...

**Comment by pharan** [comment]
I think you have an older version of the runtime.

Tangents are supposed to be (1, 0, 0, -1).
See: https://github.com/EsotericSoftware/spine-runtimes/blob/2fdd820da00d0615fb371b01731bc1e97b7c45a6/spine-unity/Assets/spine-unity/SkeletonRenderer.cs#L406

However, this static tangent setup means the tangents are not rotated with animations and requires a separate tangent solver. It was discussed in the forums here: http://esotericsoftware.com/forum/Sprite-Shaders-for-Unity-5838

The solver will be incorporated into the mesh generation code as an option soon.
