### ISSUE TITLE
Default texture wrap parameter in cocos2dx runtime is SP_ATLAS_MIRRORREPEAT.

### ISSUE THREAD

**Issue by sbrednikhin** [EsotericSoftware/spine-runtimes#633]
SP_ATLAS_MIRRORREPEAT used as default texture wrapping parameter in cocos2dx runtime. It causes assertion fail while loading atlas with non POT textures. Is it correct behaviour? or SP_ATLAS_CLAMPTOEDGE must be default?

**Comment by badlogic** [comment]
This is the correct behaviour for non-POT textures. Mirroring is only supported for POT textures on mobile. I suggest to modify the sources for your needs.
