### ISSUE TITLE
[runtimes] AnimationState Start event not fired when using AddAnimation on empty track.

### ISSUE THREAD

**Issue by foriero** [EsotericSoftware/spine-runtimes#634]
with late Unity Runtime 3.4 Start Event of the SkeletonAnimation is not fired at all.

**Comment by foriero** [comment]
The start event is not fired for AddAnimation when initial animation of SkeletonAnimation component is set to None.

**Comment by pharan** [comment]
There hasn't been any changes in that part of the code in months.

Can you show some code?

**Comment by foriero** [comment]
Just simply set in unity Inspector animation to None and then from script call AddAnimation(some animation).
If you call SetAnimation start event is called.

**Comment by pharan** [comment]
Got it. This is a core spine runtime/spine-csharp problem.
So I can't just change it in the official release. It would have to be applied to all runtimes.

But the code in question is here: https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-csharp/src/AnimationState.cs#L234

I think...
```csharp
tracks.Items[trackIndex] = entry;
```
can be replaced with
```csharp
SetCurrent(trackIndex, entry);
```

**Comment by pishock** [comment]
> But the code in question is here: https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-csharp/src/AnimationState.cs#L233

The problematic line is still present in the C# runtime.

**Comment by NathanSweet** [comment]
It's fixed in the dev branch, which will soon be merged into master.
https://github.com/EsotericSoftware/spine-runtimes/blob/dev/spine-csharp/src/AnimationState.cs

**Comment by pishock** [comment]
My apologies.

**Comment by NathanSweet** [comment]
Erm, sorry I meant spine-csharp-3_5 branch:
https://github.com/EsotericSoftware/spine-runtimes/blob/spine-csharp-3_5/spine-csharp/src/AnimationState.cs
(We'll manage branches better for 3.6!)
