### ISSUE TITLE
[Unity] SkeletonGraphics Shader - Additive Blend Mode Doesn't Work

### ISSUE THREAD

**Issue by stakira** [EsotericSoftware/spine-runtimes#637]
Additive mode is not working with `SkeletonGraphics`. However, when I replace the code of `SkeletonGraphic.shader` with `Skeleton.shader`, additive could work. I'm not able to find the exact reason since very familiar with unity shader code. Also I wonder why SkeletonGraphics use a different shader from the very beginning. Could someone find out the proper fix for this issue? Thanks.

**Comment by pharan** [comment]
Open SkeletonGraphic.shader and comment out this line:
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-unity/Assets/spine-unity/Modules/SkeletonGraphic/Shaders/SkeletonGraphic.shader#L87

The SkeletonGraphic shader is a premultiply alpha adaptation of the default Unity UI shader. That was just a holdover. Apparently, it had an optional clipping mode that detected if the alpha was too low. (additive parts in a premultiply-alpha setup have an alpha of 0).

This change will be officially applied in a future update. Thanks for reporting!

**Comment by stakira** [comment]
Thank you!
