### ISSUE TITLE
[cocos2d-x][c] Texture wrap not parsed correctly

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#639]
Looks like we don't parse the texture wrap of atlas pages correctly. Should be clamp. See http://esotericsoftware.com/forum/Cocos2d-x-3-12-and-spine-3-4-6713?p=30913#p30913

**Comment by Bilalmirza** [comment]
Looks like a small problem. Any luck with this?

**Comment by badlogic** [comment]
Just fixed it here https://github.com/EsotericSoftware/spine-runtimes/commit/f81d0aa1b310b66d4d84859052bb688fcfe98ff1
