### ISSUE TITLE
[as3] Two minor issues in the code

### ISSUE THREAD

**Issue by bp74** [EsotericSoftware/spine-runtimes#640]
Hi,

I found two minor issues while porting the AS3 runtime to the StageXL runtime.

First one, false variable assignment ....

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-as3/spine-as3/src/spine/animation/ColorTimeline.as#L78

    r = frames[int(frame + PREV_R)];
    g = frames[int(frame + PREV_G)];
    b = frames[int(frame + PREV_B)];
    b = frames[int(frame + PREV_A)];  // should be a =

Second one, a problem with floating point precission ....

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-as3/spine-as3/src/spine/PathConstraint.as#L368

    // added the + 0.0001 to avoid the loop to continue and throw an index out of range exception
    if (p > length + 0.0001) continue; 

I got an exception with the "vine" example. I have forgotten the exact numbers but it was something like this: p = 154.123456 and length = 154.123455. The loop already iterated over the last segment but "p" was still bigger than "length". My runtime is Dart and JavaScript, but those floating point calculations may be a problem in other runtimes too. 

The same problem maybe occur on two similar places, but i haven't seen it:

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-as3/spine-as3/src/spine/PathConstraint.as#L206
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-as3/spine-as3/src/spine/PathConstraint.as#L313

**Comment by badlogic** [comment]
Ouch, good catch. I'll try to repo the vine issue. That's a bit scary, it shouldn't be precision sensitive.

Thanks for reporting!

**Comment by badlogic** [comment]
I could not reproduce the second issue you encountered. I've added the vine sample to the Starling example project and played around with values quite a bit. No issue turned up. I did the same for spine-sfml, without seeing any issues.

Could this be isolated to your Dart/JavaScript runtime?

**Comment by bp74** [comment]
I will try to reproduce it later today. Yes, maybe it's isolated to the Dart/JavaScript runtime.

**Comment by bp74** [comment]
Okay i know what the problem is. JavaScript uses 64 bit double values in all calculations. But i used a typed Float32Array (which is quite common) to store the segments and therefore the "length" value.  Since 32 bit floating point numbers have a smaller precision compared to 64 bit floating point numbers, the comparison does not work. So it's not a real bug and probably works fine if the segments are also stored in a 64 bit floating point number. Sorry for causing confusion!

**Comment by badlogic** [comment]
That's an excellent observation, thanks for the input. It will most likely
hit us in the spine-js update as well :/
