### ISSUE TITLE
[cocos2d-x] Rendering spine models interfers with rendering unicode text on Android 6.x

### ISSUE THREAD

**Issue by sxxdjj** [EsotericSoftware/spine-runtimes#645]
in android 6.x os, use spine.UIText can't render Chinese text.

**Comment by badlogic** [comment]
Please provide a sample that reproduces the issue.

**Comment by sxxdjj** [comment]
sample in https://github.com/sxxdjj/SpineTest.git

**Comment by sxxdjj** [comment]
How log fix this bug.my game.My game is on the line right now.

**Comment by badlogic** [comment]
We've since changed the rendering code if you followed the repository. Please give the latest cocos2d-x runtime a try.

**Comment by sxxdjj** [comment]
I try he latest cocos2d-x runtime.This bug is fixed.Thanks very much!
