### ISSUE TITLE
[unity] AnimationState.removePreviousAnimation definition removed?

### ISSUE THREAD

**Issue by CroquetteCroquette** [EsotericSoftware/spine-runtimes#647]
Hello,
Is there any replacement for that function ? I receive an error when I use it after update to the last "spine-unity.unitypackage" ( 3.4 I think )
I looked in the doc from Esoteric but I can't seem to find anything!

Thanks

**Comment by pharan** [comment]
That was never an official feature. But you can find that modified version of AnimationState here: https://gist.github.com/pharan/77c8ab0880c33716acb8

**Comment by CroquetteCroquette** [comment]
My bad! Indeed it was an update from a member of my team, sorry for that and thank you :)
