### ISSUE TITLE
[js 3.1] Some transformations don't match the editor

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#655]
http://esotericsoftware.com/forum/Spine-rotation-not-same-in-editor-runtime-6775
Sample images and test project are linked in the forum topic.

**Comment by sharyu** [comment]
Hi, would you please tell me when can this bug be fixed?

**Comment by badlogic** [comment]
I'm currently rewriting the JavaScript runtime. You can follow the progress here: https://github.com/EsotericSoftware/spine-runtimes/tree/spine-ts/spine-ts

**Comment by sharyu** [comment]
Hi, have you found the root cause of this issue? Can I modify current js-runtime to fix this issue?

**Comment by badlogic** [comment]
No, we have not found the root case. We'll take PRs for the current
spine-js runtime, but we will deprecate it as soon as spine-ts (and with it
the new JS runtime) are complete.

**Comment by badlogic** [comment]
I've tried your sample with the latest spine-ts runtime, using the WebGL backend. It works as intended. We've already informed the maintainers of cocos2d-x-js of the latest updates of spine-ts. It's on them to update their runtime.
