### ISSUE TITLE
Does The weightedmesh, skinnedmesh support dropped?

### ISSUE THREAD

**Issue by halx99** [EsotericSoftware/spine-runtimes#661]

**Comment by badlogic** [comment]
No, they've been merged, see the code and diffs. Please use the forums for questions.

**Comment by halx99** [comment]
ok, thanks

**Comment by halx99** [comment]
I got it, they are merged as ```linkedmesh```, but if use new runtime, I could not load the animation which is exported by old spine editor(such as 2.3.17)

**Comment by pharan** [comment]
That's correct.
Spine 3.2 runtimes no longer loads older jsons. This is not common when you use json, but 3.2 was just that much of a change.
You need to re-export your skeletons using an updated Spine editor.

**Comment by halx99** [comment]
Thanks.
