### ISSUE TITLE
[unity] SkeletonGraphicInspector static initializer causes Scene View problems.

### ISSUE THREAD

**Issue by GuipengLiao** [EsotericSoftware/spine-runtimes#665]
Infomation of my tools 
Unity 5.3.4f
Spine 3.3.07 Professional
Spine-runtimes：（include the newest spine-csharp and spine-unity）

follow the step:

1: Using The SkeletonGraphic（UnityUI）to Create A Unity UI Object
2: Drag the Dinosaur_SkeletonData to the SkeletonGraphic Script,he Skeleton Data Asset
3; If i dont change any property  In SkeletonGraphic Script,  running the game , no problem.
4: But in Editor Mode(before run the game),I change any property  (which property in keletonGraphic Script),especially change the Starting Animation Property, the Issue happen。(but i can runing the game normality,the spine animation also play normalityl in the game mode. )
5：after issue happened, my Unity Hierarchy canot Interaction, and all the object in Hierarchy hided.
but after reboot the unity software,evertthing get right(the spine animation can normal play  in game mode)

but when i changed  to use the old spine -runtimes ,the same spine animation data , the same unity version, ererything return to normal, I can change the StartAnimation perpoty in Inspector and no issue hanppen.

Debug in unity console:
UnityException: You are not allowed to call this function when declaring a variable.
Move it to the line after without a variable declaration.
If you are using C# don't use this function in the constructor or field initializers, Instead move initialization to the Awake or Start function.
UnityEngine.Object.FindObjectsOfType[SkeletonRenderer] () (at C:/buildslave/unity/build/Runtime/Export/UnityEngineObject.cs:108)
Spine.Unity.Editor.SpineEditorUtilities.HierarchyWindowChanged () (at Assets/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs:402)
Spine.Unity.Editor.SpineEditorUtilities.Initialize () (at Assets/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs:209)
Spine.Unity.Editor.SpineEditorUtilities..cctor () (at Assets/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs:181)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Spine.Unity.Editor.SpineEditorUtilities
Spine.Unity.Editor.SkeletonGraphicInspector..cctor () (at Assets/spine-unity/Assets/spine-unity/Modules/SkeletonGraphic/Editor/SkeletonGraphicInspector.cs:55)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Spine.Unity.Editor.SkeletonGraphicInspector
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at C:/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:123)

**Comment by pharan** [comment]
Thanks for reporting. I think I know the problem. Will take a look at it.

**Comment by pharan** [comment]
That should fix it.
The unitypackage has also been updated: http://esotericsoftware.com/spine-unity-download

**Comment by GuipengLiao** [comment]
successfully solving.
Thanks
