### ISSUE TITLE
[c] Confusing names for variables and fields

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#669]
For variable names we use xxxCount for the number of things (eg, vertexCount for the number of x,y pairs) and xxxLength for the number of values (eg verticesLength for the number of floats).

For struct field names we use xxxCount for the number of values in an array and xxx for the array.

The spVertexAttachment int verticesCount field matches the float* vertices field. SkeletonJson uses variables vertexCount and verticesLength, which leads to code like attachment->verticesCount = verticesLength, which looks terribly confusing.

I propose we rename our fields to xxxLength for the number of values in an array and xxx for the array.

**Comment by badlogic** [comment]
Closing this in favor of #735
