### ISSUE TITLE
[as3] scaleX issue in as3 runtime

### ISSUE THREAD

**Issue by mtari** [EsotericSoftware/spine-runtimes#671]
We are using as3 runtime and we are having a strange issue. In the animation we've created we set the root's scaleX to -1 to flip the whole animation. Unfortunately the result looks like this:

![scalex](https://cloud.githubusercontent.com/assets/1629354/17592814/ac5e98ca-5fdb-11e6-89c1-506f55c19db9.png)

It looks like every bones are rotated by 180.

**Comment by badlogic** [comment]
This should be fixed in the 3.5 update (see dev branch). Alternatively, you can also set flipX on the skeleton.
