### ISSUE TITLE
starling 1.7 shear

### ISSUE THREAD

**Issue by schsj** [EsotericSoftware/spine-runtimes#673]
tell me please when it will be added support data exporter from Spine 3.2 for starling 1.7? Can't use shear tool and new mesh format.

**Comment by badlogic** [comment]
We have deprecated the Starling 1.7 runtime in favor of the Starling 2.0 runtime. We will not backport changes to Starling 1.7. However, it should be simple to take the spine-as3 and spine-starling runtime for Starling 2.0 and backport the required changes yourself.
