### ISSUE TITLE
[ts] Handle context loss in WebGL backend and widget

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#675]
See http://esotericsoftware.com/forum/ts-webgl-Handling-Context-Lost-6861

**Comment by badlogic** [comment]
Users can theoretically re-create all resources themselves on context loss. However, it'd be nice to have a simpler mechanism so you don't need to recreate object instances. Problem is that all WebGL "classes" require a handle to the WebGLRenderingContext and must recreate meshes/textures/shaders as they were constructed (e.g. with/without mipmapping). Which means those "classes" need to store more info to recreate things.

**Comment by geddski** [comment]
@badlogic I'm hitting this in my app now after navigating a few times (single-page app). What do I need to handle/ recreate in order to avoid the app blowing up?

**Comment by badlogic** [comment]
Fixed in the 3.6-beta branch. See commit 2b4c2bcf94def732caa31420aca4a6d7ed1ac6a2 and [CHANGELOG](https://github.com/EsotericSoftware/spine-runtimes/blob/3.6-beta/CHANGELOG.md#webgl-backend)

**Comment by geddski** [comment]
Sweet I'll try it out now. Thanks @badlogic

**Comment by geddski** [comment]
Sweet I'll try it out now. Thanks @badlogic

**Comment by geddski** [comment]
@badlogic this totally fixes it! You're a genius.

**Comment by geddski** [comment]
@badlogic shoot, still errors out in Chrome on Windows. Chrome on Mac works fine. Edge and Firefox on Windows work fine.

**Comment by geddski** [comment]
```js
Uncaught TypeError: Cannot read property 'VERTEX_SHADER' of null
```

**Comment by badlogic** [comment]
When does this happen? After switching tabs a bunch of times while having a Spine widget on one of the tabs? Using 3.6-beta?

**Comment by geddski** [comment]
yep using 3.6-beta, happens not when switching tabs but when going to new routes in my single page app, where old contexts are discarded and new ones are created. Same error that used to happen in all the browsers before your fix. Now it's just in chrome.

**Comment by badlogic** [comment]
I've tried to recreate the issue, see this new test https://github.com/EsotericSoftware/spine-runtimes/commit/66c6d5cd899400b3770c62afb7f719c67060929d

Upon clicking the reload button, the old 5 widgets are removed from the DOM (after pausing them, so no further calls to requestAnimationFrame are made), and 5 new widgets are added to the DOM.

I tested this in Chrome, Firefox and Edge on Windows, and Safari, Chrome, and Firefox on macOS. I can hit the reload button forever, without any issues cropping up. The only thing that gets reported is that there are to many WebGL contexts, and that the oldest one is being lost in Chrome. This is not a problem, but a side effect of the GC not having cleaned the old contexts yet when the new ones are created.

I've also used Chrome's memory heap snapshot tool to check on the number of WebGLRenderingContext instances that are on the heap, and that number stays constant over dozens of reloads. 

Note that this only works because I call `pause` before removing widgets. If I don't do that, those widgets reside in memory, as they are constantly rescheduling calls to their `render` function via `requestAnimationFrame`.

Could you try this new test on your end? My Chrome version on Windows is `58.0.3029.110 (64-bit)`
