### ISSUE TITLE
[js] Support multiple atlas pages in threejs

### ISSUE THREAD

**Issue by SinglePotato** [EsotericSoftware/spine-runtimes#677]
Currently, there is a single texture material attached to the mesh created in threejs, and the **SkeletonMesh.prototype.updateGeometry** function swaps the texture without it being assigned to the geometry.

`if (texture != null) {
                        if (!this.material.map) {
                            var mat = this.material;
                            mat.map = texture.texture;
                            mat.needsUpdate = true;
                        }
                        this.batcher.batch(vertices, triangles, z);
                        z += zOffset;
                    }`

[Issue happening with the example dragon skeleton](http://imgur.com/a/XTVUe)

**Comment by badlogic** [comment]
This is a known limitation. Given the three.js rendering architecture, the only way around this at the moment would be to break up the batching into multiple meshes, all attached to a root node. This also has to be dynamic, as the attachments can change.
