### ISSUE TITLE
Unity3d 5.3.5f1- SkinnedMesh not found

### ISSUE THREAD

**Issue by Neuyazvimyi** [EsotericSoftware/spine-runtimes#682]
Hello, I am using last unitypackage of spine and also Spine Pro version.
I can't import animation.
Here is log.

ArgumentException: The requested value 'skinnedmesh' was not found.
System.Enum.Parse (System.Type enumType, System.String value, Boolean ignoreCase) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Enum.cs:692)
Spine.Unity.Editor.SpineEditorUtilities.GetRequiredAtlasRegions (System.String skeletonDataPath) (at Assets/spine-unity/Editor/SpineEditorUtilities.cs:803)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEditor.DockArea:OnGUI()

**Comment by Neuyazvimyi** [comment]
Closed. Spine runtime was 3, but Spine Application was 2.1. Why it is not updates automatically?

**Comment by NathanSweet** [comment]
Make sure you have set your Spine version to `Latest` in the Spine settings.
http://esotericsoftware.com/spine-settings#Version

**Comment by mixi57** [comment]
change the 'skinnedmesh' to 'mesh'

**Comment by NathanSweet** [comment]
No, export from the correct Spine version that matches your runtimes.
