### ISSUE TITLE
Spine-TS Canvas Demo points to missing spine-canvas.js file

### ISSUE THREAD

**Issue by shibekin69** [EsotericSoftware/spine-runtimes#683]
As what the title says. Tried the Spine-TS demo, but I noticed that the script include is pointing to spine-canvas.js in the ..\..\build\ directory. But that doesn't exist.

**Comment by badlogic** [comment]
As per the README.md, start a web server in the `spine-runtimes/spine-ts` folder, then everything works as expected.
