### ISSUE TITLE
weird in skeletonRenderer

### ISSUE THREAD

**Issue by fred1024** [EsotericSoftware/spine-runtimes#685]
Hi, I have found in Rect SkeletonRenderer::getBoundingBox()

	float minX = FLT_MAX, minY = FLT_MAX, maxX = FLT_MIN, maxY = FLT_MIN;

shouldn't maxX and maxY be initialized with -FLT_MAX ? like this :

float minX = FLT_MAX, minY = FLT_MAX, maxX = -FLT_MAX, maxY = -FLT_MAX;

I thought FLT_MIN was the smallest positive number representable in float not the smallest negative number.

**Comment by badlogic** [comment]
Good catch, fixed!

**Comment by fred1024** [comment]
... happy to contribute a tiny bit to this Fantastic tool
