### ISSUE TITLE
[c] SkeletonJson Setlocale returns new locale and  SkeletonJson changes current locale

### ISSUE THREAD

**Issue by sukobayashi-aim** [EsotericSoftware/spine-runtimes#690]
`oldLocale = setlocale(LC_NUMERIC, "C");` 
in `spSkeletonJson_readSkeletonData`, used to get currentlocale, however setlocale returns "new" locale
information after set except set "", or null.

Therefore, in my project cause locale error.  

Now we rollback to old json.c and not set locale .

**Comment by badlogic** [comment]
I've commited a fix for this, please give it a try. We now fetch the old locale with `setlocale(LC_NUMERIC, NULL)`, which should fix the issue.
