### ISSUE TITLE
haxe runtime

### ISSUE THREAD

**Issue by SlavaRa** [EsotericSoftware/spine-runtimes#691]
what do your think about haxe runtime? I could provide the code.

**Comment by pharan** [comment]
Feel free to share what you have and we can link to you.
There are many other Spine haxe runtimes and haxe runtimes with Spine compatibility: http://esotericsoftware.com/spine-runtimes#Haxe

**Comment by badlogic** [comment]
Closing this out, please write us at contact@esotericsoftware.com with the link we can put on our runtimes page. We currently have no plans of adding an officially supported Haxe runtime.
