### ISSUE TITLE
[c] memory leak is detected by Visual Studio

### ISSUE THREAD

**Issue by longht89** [EsotericSoftware/spine-runtimes#696]
Hi,
I used spine-c to implement my spine loader in my project, but somethings is wrong is reported by visual studio.

Here my logs:
`The thread 0x1b24 has exited with code 0 (0x0).
The thread 0x3834 has exited with code 0 (0x0).
Detected memory leaks!
Dumping objects ->
{13884} normal block at 0x016ACBD0, 0 bytes long.
 Data: <> Ìm\þÿÿÿø
{13019} normal block at 0x0320F1F0, 6 bytes long.
 Data: <drive > 64 72 69 76 65 00 
{12931} normal block at 0x0320F538, 8 bytes long.
 Data: <antenna > 61 6E 74 65 6E 6E 61 00 
{12855} normal block at 0x0321BFB0, 16 bytes long.
 Data: <cannonConnector > 63 61 6E 6E 6F 6E 43 6F 6E 6E 65 63 74 6F 72 00 
{12807} normal block at 0x0320F148, 7 bytes long.
 Data: <cannon > 63 61 6E 6E 6F 6E 00 
{12759} normal block at 0x0320EFF8, 9 bytes long.
 Data: <guntower > 67 75 6E 74 6F 77 65 72 00 
.etc...`

Is that right?
I checked, and spSkeletonBinary_readAttachment func created "name" variable, but not release it.
`	const char* name = readString(input);
	if (!name) MALLOC_STR(name, attachmentName);`

Could you please help me check it.

Thank you.

**Comment by badlogic** [comment]
Great find! I believe I have fixed the leak. Please give the latest sources in the master branch a try and report back if the fix doesn't work. I'm currently not setup with VS, so I can't run the leak detector here.
