### ISSUE TITLE
[spine-c] `spSkeletonJson_readSkeletonData` causes the default locale to be broken.

### ISSUE THREAD

**Issue by FrankStain** [EsotericSoftware/spine-runtimes#698]
https://github.com/EsotericSoftware/spine-runtimes/blob/684f6dcf3e156f342477927c690a1689edb4624a/spine-c/src/spine/SkeletonJson.c#L572
```.cpp
	oldLocale = setlocale(LC_NUMERIC, NULL);
	setlocale(LC_NUMERIC, "C");
	root = Json_create(json);
	setlocale(LC_NUMERIC, oldLocale);
```

It's crucial to duplicate returned by `setlocale()` values, as it may be invalidated after the sequential call of `setlocale()`. And here it's done!
After the call of `setlocale(LC_NUMERIC, "C");` function, `oldLocale` stores garbage.

http://en.cppreference.com/w/c/locale/setlocale
The crucial message here is:
> POSIX also specifies that the returned pointer, not just the contents of the pointed-to string, may be invalidated by subsequent calls to setlocale.

Easiest way to solve this issue is using next code:
```.cpp
	oldLocale = strdup(setlocale(LC_NUMERIC, NULL)); // strdup used to duplicate the name of locale.
	setlocale(LC_NUMERIC, "C");
	root = Json_create(json);
	setlocale(LC_NUMERIC, oldLocale);
	free(oldLocale); // Delete the duplicated memory.
```

**Comment by FrankStain** [comment]
@badlogic , take a look here plz. :)

**Comment by badlogic** [comment]
Thanks!

**Comment by FrankStain** [comment]
@badlogic , thanks for so fast fix! :+1: 
But, as i afraid, that was only fast fix.

First thing is that `strdup` marked deprecated on Windows, so every compilation the users will see nagging warning: "SkeletonJson.c(573): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details.".

Second thing is more fatal.. :(
According to sources from Android repo, direct call of `strdup` will cause `SIGSEGV`, cuz `setlocale(LC_NUMERIC, NULL)` will always return `nullptr`. `strdup` will fail while duplicating the `nullptr`.
https://android.googlesource.com/platform/ndk/+/master/sources/android/support/src/locale/setlocale.c
Also here is proof that locales are not supported from NDK.
http://stackoverflow.com/questions/23427230/does-the-android-ndk-support-locales
The answer is old, but still relevant.

So, we need more wide workaround here. Safe and crossplatform.

**Comment by badlogic** [comment]
Bah, broken fixes are the worst fixes. Switching to _strdup is easy enough, but the Android behaviour is terrible. How are we supposed to get at the locale in android? Adding a JNI call to Java just for android in spine-c is out of the question. I guess we'll have to pass on the locale setting to the user :/

**Comment by FrankStain** [comment]
> Adding a JNI call to Java just for android in spine-c is out of the question.
Indeed.
Also, i have no idea what the problems can be found on other platforms (NIX/Mac/iOs/Tizen/...).

But for android i can say one thing. On NDK side there only one locale may be installed - "C". :)
And it set by default. We may only guard us from SIGSEGV by checking the value returned by `setlocale()`.

**Comment by badlogic** [comment]
Yeah, I think we should not do any locale work on Android, and use _strdup plus null checks on other platforms.
