### ISSUE TITLE
[cocos2d-x] Crash on Android loading specific files

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#704]
See http://de.esotericsoftware.com/forum/Bug-Crash-on-Android-with-Cocos2d-x-7067?p=32433#p32433, files in e-mail by Max Muthig.

**Comment by ForestRingGames** [comment]
Answering Mario's questions here:

-The crash happened on my local Android device (Nexus 7 (2012))
-There was no "missing file" line in the console, but if I use a file that is not present the missing file error happens
-I logged the fileLength of the two files that are being loaded and it is non-zero (see forum post)
-I used Crashlytics to show the Stacktrace, since I'm working on a Mac and am therefore unable to debug on Android properly (Android Studio can't debug C++ with breakpoints)
-I tried to install the app multiple times on my android device with a full delete in between

**Comment by badlogic** [comment]
Perfect, thanks for the info. I'll try to get to the bottom of this. My guess is the recent locale changes may have something to do with this.

**Comment by badlogic** [comment]
Definitely related to https://github.com/EsotericSoftware/spine-runtimes/issues/698. Looks like Android returns a null value, and things go boom. Once I fix #698, this issue should be fixed too.

**Comment by badlogic** [comment]
Only crashes on Android 4.x now, but not on Android 5+, see latest comment in forum thread.

**Comment by ForestRingGames** [comment]
Thanks for the update, I've left the android version aside until this is fixed, so I didn't test in the meantime. We're testing on Android 4.4, so good to know this still happens.

**Comment by badlogic** [comment]
Could you please test the latest for your case on whatever Android version? I'm looking into this thread as well http://esotericsoftware.com/forum/Bug-Crash-on-Android-with-Cocos2d-x-7067?p=32818&hilit=android+cocos2d#p32818

**Comment by ForestRingGames** [comment]
I can't test on Android at the moment, unfortunately. I hope I'll be able to do it in the next days.
Have you been able to test it in the meantime / does it work for you?

**Comment by badlogic** [comment]
Haven't been able to test yet either, setting up cocos2d-x for Android is a
nightmare. I'll get to it next week after the spine-lua runtime is done.
Let me know if you get to test it before me.

**Comment by ForestRingGames** [comment]
Setting up Cocos2d-x for Android is actually quite easy....

It's quite scary that you guys do not test on device before shipping updates to be honest....

Are you working on Windows or Mac?

If you're on Windows, you can get a basic setup with Visual Studio done with this:
https://blogs.msdn.microsoft.com/vcblog/2016/07/12/cocos2d-x-visual-studio-android-project/ <https://blogs.msdn.microsoft.com/vcblog/2016/07/12/cocos2d-x-visual-studio-android-project/>

This is not really official yet, but there's also "normal" guides how to do it on Windows.

For Mac, you just download Android SDK and NDK, set up the Paths and run the cocos command line tool to create a new project.
If you made any mistake, the command line tool will tell you and also how to fix it.
The command line tool even asks you for your SDK / NDK root folder, so you can't really mess that up.



> Am 09.10.2016 um 13:28 schrieb Mario Zechner <notifications@github.com>:
> 
> Haven't been able to test yet either, setting up cocos2d-x for Android is a
> nightmare. I'll get to it next week after the spine-lua runtime is done.
> Let me know if you get to test it before me.
>

**Comment by badlogic** [comment]
The problems come with proper debugging support. NDK debugging is more than shaky, and Android Studio support isn't the greatest. I'm the new guy responsible that we actually test continuously on all target platforms. Doing my best to get up to speed here, sorry for it taking a bit.

**Comment by ForestRingGames** [comment]
No worries, I want to help you, so you can help me ;)

Do this Visual Studio Setup. It installs everything you need and additionally it offers full debugging on Android (breakpoints, live values, etc.)

This does NOT work on Mac in any way that I know off, which is really annoying. I often find myself debugging with Console Logs - very annoying.
But I don't need it as often as you do probably ;)

**Comment by badlogic** [comment]
Yeah, Mac is where my pain lies I'm afraid. Using a Mac so we can also
cover iOS/macOS, and the CLI tooling is nicer than on Windows. Comes with
the downside of Android NDK being terrible. I may consider setting up a
Windows VM to eleveate the pain a little.

Thanks for the input!

**Comment by ForestRingGames** [comment]
If you setup Windows, beware that you need to install Visual Studio PLUS Visual Studio Update 3 (extra download).

Together the install process takes around 4 hours.

But after that, everything just worked as in this microsoft article and I could debug / step on Android.

The rest of this setup is very very bad. No gradle / Android Studip compatibility, etc.

But for your case of debugging pure C++/C Code, it'll do ;)

> Am 09.10.2016 um 14:49 schrieb Mario Zechner <notifications@github.com>:
> 
> Yeah, Mac is where my pain lies I'm afraid. Using a Mac so we can also
> cover iOS/macOS, and the CLI tooling is nicer than on Windows. Comes with
> the downside of Android NDK being terrible. I may consider setting up a
> Windows VM to eleveate the pain a little.
> 
> Thanks for the input!
>

**Comment by badlogic** [comment]
I've now added an Android project to our cocos2d-x example for testing. The models we currently use in the examples work as intended. I tested on a Nexus 5, Android 6.0, which is the only test device I have access to at the moment :/ I'm going to try reproduce the crash with the file you sent via e-mail.

**Comment by ForestRingGames** [comment]
Cool!

We had to go back to Android NDK 10e due to issues with another SDK.
I think the error occured with NDK 12, don't with 10e.

Maybe that helps you.

**Comment by badlogic** [comment]
Good info, I'm on NDK 13. Not quite sure why there'd  be a difference for our code though, doesn't use much of libc.

**Comment by ForestRingGames** [comment]
I only have the experience that different NDKs destroy different SDKs of third parties ;)

I have four different version and am always evading bugs in the SDKs I use, trying to get Android to run ;)

**Comment by badlogic** [comment]
Well, lastest Cocos2D-X, Android NDK 13, Android 6.0 device works as intended. I simply plugged your model into our cocos2d-x example `SpineboxExample.cpp` and ran it on the device. No issues detected.

![http://sht.tl/6G9KsG](http://sht.tl/6G9KsG)

I'm going to try NDK 12, and see if I can setup a debug session with an Android 4.4 emulator.

**Comment by ForestRingGames** [comment]
Awesome! Thank you! I really appreciate your testing session time ;)

As well as the software looks, your device looks a bit harmed ;)

**Comment by badlogic** [comment]
NDK 12 on Android 6 works as intended as well. Setting up Android 4.4 ARM emulator now. If that doesn't crash, I won't be able to do much more I'm afraid. You can try to repro the issue with the new `proj.android` in our cocos2d-x example.

**Comment by badlogic** [comment]
NDK 12 on Android 4.4 ARM emulator works as intended as well

![http://sht.tl/myrlca](http://sht.tl/myrlca)

I'm out of ideas. If you can modify our example to reliably reproduce the issue I'm happy to give it another look.

**Comment by badlogic** [comment]
I'm closing this out until we have a reproduction case. Just ping me here if you get to testing things on your end.

**Comment by ForestRingGames** [comment]
Thank you!

It might be really working again now....the latest spine runtime does work again for me on NDK 10e.

I will test on 12 and 13 in the next days and report back if it happens again.

Thanks!

**Comment by ForestRingGames** [comment]
I guess that some of the updates after the crash happened for me randomly fixed it ;)
I've seen that there were updates on Spine after I had the issue - but I couldn't test then due to other issues I had.

Though the update didn't "officially" fix this bug.

Thanks for all your time and effort. It does work now (for whatever reason), so I'm super happy.

Thanks.

Cheers,
Max

**Comment by badlogic** [comment]
My guess? Cleaning didn't work on your end. Part of my struggle was getting
cleans to work, as cocos2dx hacky CLI tool doesn't jave cleaning outof the
box...

I'm not sure why people torture themselves with cocos2d-x :)

**Comment by ForestRingGames** [comment]
Well, I usually clean by hand haha. So that should have worked.

Deleted Obj / Lib / Bin folders

I just delete all the folders ;)

Never used the cocos2d-x cleaning tool.

> Am 11.10.2016 um 16:15 schrieb Mario Zechner <notifications@github.com>:
> 
> My guess? Cleaning didn't work on your end. Part of my struggle was getting
> cleans to work, as cocos2dx hacky CLI tool doesn't jave cleaning outof the
> box...
> 
> I'm not sure why people torture themselves with cocos2d-x :)
>

**Comment by badlogic** [comment]
Yeah, cause there is no cocos2d-x cleaning tool :) Torture, I say!

**Comment by ForestRingGames** [comment]
Cocos2d-x has many flaws, but this one is actually Google's fault in my opinion ;)

Still Android Studio does not support C++ properly. That's where the torture comes from ;)

> Am 11.10.2016 um 17:03 schrieb Mario Zechner <notifications@github.com>:
> 
> Yeah, cause there is no cocos2d-x cleaning tool :) Torture, I say!
>
