### ISSUE TITLE
[editor] Export in 3.4.02 Professional sometimes has Skeleton width & height == 0.

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-runtimes#708]
Hi,

It never happened in the previous version we used (3.2.x).
It also happen on Mac and Linux, binary or json export.

Seb

**Comment by badlogic** [comment]
Reproduction case via e-mail. Was able to reproduce it in 3.4.02. Export repro skeleton as JSON, no non-essential, no pretty printing, plain JSON. Same if non-essential is checked and other JSON variants are used. Same with 3.5.01-beta.

@Fraggle as a temporary workaround, I suggest to calculate the bounds at runtime, using `Skeleton#getBounds`. Not only do you get the width/height, but also the offset (lower left corner) of the axis aligned bounding box that encloses your skeleton.

**Comment by badlogic** [comment]
@Fraggle I'm closing this here, as it is an editor issue. Please continue following the issue in the editor tracker here: https://github.com/EsotericSoftware/spine-editor/issues/111
