### ISSUE TITLE
[c] binary skeletons are broken Ответить

### ISSUE THREAD

**Issue by jphw** [EsotericSoftware/spine-runtimes#709]
The thing is that some of the skeletons end up with noticeable visual artifacts when loaded using binary format, and it looks almost like vertices positions on some of the mesh attachments get corrupted during export from the editor or during load by the spine-c runtime.

Here are few screenshots of how it looks.
1) first screenshot is what I have in the editor:
![parrot_editor](https://cloud.githubusercontent.com/assets/5418483/18833508/a8e65222-83f9-11e6-9cf1-ba99859e3dd8.png)

2) second screenshot is how it looks in the game when I use json format:
![parrot_ingame_json](https://cloud.githubusercontent.com/assets/5418483/18833513/b02dbdb8-83f9-11e6-9858-f6e7a88b8bf6.png)

3) and third screenshot is how it looks in the game when binary format is used:
![parrot_ingame_binary](https://cloud.githubusercontent.com/assets/5418483/18833523/b6a0859a-83f9-11e6-9855-30936c80943e.png)

Clearly something is wrong ))))

Currently I use runtimes from commit 721de14, and the editor version is 3.4.02

**Comment by badlogic** [comment]
Could you provide me with the export for this animation so I can reproduce it locally?

**Comment by jphw** [comment]
@badlogic I have sent it to you on the forums via PM already.

**Comment by badlogic** [comment]
Mea culpa, to many information sources. I'll get to the bottom of this!

**Comment by badlogic** [comment]
I've plugged your model into the latest cocos2d-x runtime example and it appears to work as intended:

![https://media.giphy.com/media/l2YSFCYAmOa9TWMSI/giphy.gif](https://media.giphy.com/media/l2YSFCYAmOa9TWMSI/giphy.gif)

**Comment by jphw** [comment]
What spine-c commit and editor version you were using? We have just updated spine-c to the latest one but constrained parts (legs) still look broken. I have also tried the beta editor for export but it seems that it is not supported by the current spine-c runtimes, so I am still sitting on the 3.4.02.
When I remove constraints from the parrot's legs or when I use json export - everything works fine. I am very confused.

**Comment by badlogic** [comment]
I've taken the Spine project you sent via e-mail and exported it via Spine Editor version 3.4.02. I've then taken the sample cocos2d-x application in this repository's master branch and plugged in the export. Note that I had to remove the spine support from the cocos2d-x download which is an outdated, unofficial version of our runtime. The cocos2d-x repository describes what to remove in the README.md.

**Comment by jphw** [comment]
And you were using binary export, not json, right? I am just asking because sample cocos2d-x app here uses jsons;

**Comment by badlogic** [comment]
Yes, I tested both JSON and binary exports.

**Comment by jphw** [comment]
@badlogic 
Ok thanks. I checked the sources once more and the only major difference between our code and cocos's that I noted is that we use spSkeletonBinary_readSkeletonDataFile to load the skeletons and cocos use spSkeletonBinary_createWithLoader with a custom loader. So could you please check the default loader that is used inside spSkeletonBinary_readSkeletonDataFile? I am really confused and cannot find any other potential sources of the problem.

**Comment by jphw** [comment]
@badlogic 
I have found some differences in loaded skeleton data between our project and spine example project: http://clip2net.com/s/3DIf25I
Left screenshot is from our project debug window, and right is from cocos one. Somehow data loaded in our project ends up with constraints count = zero and constraints data empty.

**Comment by jphw** [comment]
@badlogic 
I have found the source of the problem at last: The thing is that we use Marmalade SDK and it adds -funsigned-char (or /J) to the compiler flags automatically for it's own purposes (and one cannot remove them). And in SkeletonBinary.c there is that function readSByte that returns just `char`, which in case of these flags becomes `unsigned char` and so line `data->bendDirection = readSByte(input);` ends up filling bendDirection with an invalid value (255 instead of -1). 
I have changed `char` to `signed char` in readSByte for now, but I'm not sure if you should change it in your sources.

**Comment by badlogic** [comment]
Sorry for not getting back to you earlier, busy with porting
AnimationState. That's a pretty great find, but also a bit of a disturbing
one. I believe we should change upstream to signed char. I've re-opened
this issue. Will do that as soon as I'm done with porting.
