### ISSUE TITLE
[cocos2d-x] setAnchorPoint on SkeletonAnimation has no effect

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#710]
See http://esotericsoftware.com/forum/setAnchorPoint-not-working-in-cocos2d-x-runtime-7111

**Comment by badlogic** [comment]
OK, looked into this. For anchor points to work, we need to set the content size of the skeleton node. This is a very heavy operation to be performed each frame. The content size may also change depending on the animation as the model's bounds change. The best solution for this problem is to set the bounds manually by calling spSkeleton_getBounds() on skeletonNode->getSkeleton(), e.g. in the setup pose.

**Comment by crookedbard** [comment]
@badlogic is it the same for cocos2d-x v4?
Any examples?
