### ISSUE TITLE
[ts][js] Publish artifacts to NPM

### ISSUE THREAD

**Issue by scottmcdonnell** [EsotericSoftware/spine-runtimes#711]
I can't currently install spine-runtimes as a project dependency using npm - can a package.json be added?

**Comment by badlogic** [comment]
We currently have no plans for this, but might do it in the future.

**Comment by badlogic** [comment]
Looks like you guys resolved this without us adding a `package.json`. Good stuff! https://github.com/pixijs/pixi-spine/issues/121

**Comment by dcalhoun** [comment]
@badlogic I didn't follow much of the Pixi thread discussion, but I would love to see Spine's runtimes published to npm. Manually downloading them for my project feels a bit antiquated.

**Comment by scottmcdonnell** [comment]
As far as I know, all that is needed is a package.json to be created at the root. Then it can be installed directly from github using `npm install --save-dev EsotericSoftware/spine-runtimes`

**Comment by dcalhoun** [comment]
@scottmcdonnell from what I understand, it's not possible to [install a subdirectory of a monorepo and it's not something that npm plans to support](https://github.com/npm/npm/issues/2974#issuecomment-169451651). So, merely adding a `package.json` to the root of this project would mean a user would have to install _every_ runtime when they need a single runtime for a project. This is far from ideal, in my opinion.

@badlogic do you have any additional thoughts on this?

**Comment by scottmcdonnell** [comment]
Lots of node_modules are large packages. All runtimes would be installed
but the 'main' param in package.json would point to the JavaScript index
file.

Then a bundler such as webpack would package up just the JavaScript runtime
if 'required'
