### ISSUE TITLE
[ts] Allow users to only specify callbacks for AnimationState events they are interested in

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#714]
Do the null check dance...

**Comment by ivanpopelyshev** [comment]
Something like this can work: https://github.com/Hypercubed/mini-signals

Just make a simple linked list per every event.

Also, may be passing "state" or "track" itself as a first parameter in event can be useful

**Comment by badlogic** [comment]
Went with the non-fancy version of simply performing null checks.
