### ISSUE TITLE
[as3] wrong rotateMode default value

### ISSUE THREAD

**Issue by jeremyfa** [EsotericSoftware/spine-runtimes#715]
At this line, I suspect there is a mistake: shouldn't default value be "tangent" instead of "rotateMode"? :)

https://github.com/EsotericSoftware/spine-runtimes/blob/16489aaf58aac43b1b3ebd9bf76fb47c6a2cd1b0/spine-as3/spine-as3/src/spine/SkeletonJson.as#L201

**Comment by badlogic** [comment]
Ah, good catch. Fixed!
