### ISSUE TITLE
[cocos2d-x] Infinite loop when reading vertices from a binary export.

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-runtimes#718]
Hello,

I don't know if the bug is in the binary reader or the editor export but we have an infinite loop on some assets.
The loop is in:
```spSkeletonJson_readSkeletonData > _readVertices```
The vertices[i] return a negative number there:
```for (i = 0; i < entrySize;) {
	int bonesCount = (int)vertices[i];
	attachment->bonesCount += 1 + bonesCount;
	attachment->verticesCount += 3 * bonesCount;
	i += 1 + bonesCount * 4;
}```

I sent some example files to contact@...

Good luck :)

**Comment by badlogic** [comment]
Likely related to https://github.com/EsotericSoftware/spine-runtimes/issues/709 as well

**Comment by badlogic** [comment]
This appears to be an issue with exports from Spine 3.2.01, from which the files you sent me have been exported. 

I've re-exported the model with Spine 3.4.02 and loading worked as intended without an infinite loop. Is it possible for you to export to 3.4.02 for exporting?

**Comment by badlogic** [comment]
Upon further inspection, the bounding box attachment of the model doesn't export the `vertexCount` attribute for the vertices array in the JSON file. 

I'm afraid you can not use models exported from Spine 3.2.01 with runtime versions newer than that, e.g. the latest one in master.

**Comment by Fraggle** [comment]
Okay, seems to do the trick. I'm sorry because i was pretty sure I sent you binary stuff but it actually was unrelated somehow.
