### ISSUE TITLE
[cocos2d-x] Some bones dismissed when the animation running looped

### ISSUE THREAD

**Issue by natural-law** [EsotericSoftware/spine-runtimes#723]
I have encounter a problem in the cocos2d-x runtime: The animation is running well at the first time. But some bones are dismissed if it's running looped. My code looks like this:

```
skeletonNode = SkeletonAnimation::createWithJsonFile("spine/diyuhuo/diyuhuo_shifa.json", "spine/diyuhuo/diyuhuo_shifa.atlas", 0.6f);
skeletonNode->setAnimation(0, "play", true);

Size windowSize = Director::getInstance()->getWinSize();
skeletonNode->setPosition(Vec2(windowSize.width / 2, 200));
addChild(skeletonNode);
```

And here is the resource encounter the problem: 
[diyuhuo.zip](https://github.com/EsotericSoftware/spine-runtimes/files/526248/diyuhuo.zip)

**Comment by badlogic** [comment]
This doesn't appear to be a spine-cocos2dx/spine-c specific bug. I can reproduce the issue in the SkeletonViewer as well. Could you provide us with your Spine project file so we can better inspect the animation? My gut feeling tells me there's something wrong with the ColorTimeline.

**Comment by natural-law** [comment]
@badlogic I'm sorry that the resource is got from another developer. I don't have the Spine project.
As he described, the reason is : when the animation played in the second, the properties of the last frame is used. But not reset the properties. So the problem is not only appeared on color property.

**Comment by NathanSweet** [comment]
Fixed in https://github.com/EsotericSoftware/spine-runtimes/commit/cd826f1836d3cc18a5642fc930b6ad9c82165450

Cheers!
