### ISSUE TITLE
[unreal] Add support for Unreal Engine

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#727]
- [x] `UTrackEntry` getters/setters
- [x] Add missing listeners to `UTrackEntry` and `USkeletonAnimationComponent`
- [x] Retain `UTrackEntry` instances in `UPROPERTY TArray` or similar until dispose event so they don't get GCed accidentially. Set `spTrackEntry` to ``nullptr` on `UTrackEntry` on dispose event.
- [x] Allow specifying `AnimationStateData` mixing pairs on `SkeletonData` asset
- [x] Expose APIs of `Skeleton` that make sense in blueprints (skins, attachments, bone world transforms getter/setter)
- [x] Blending on instanced materials is broken
- [x] License headers
- [x] Update to latest and greatest release (we'll need 4.15 with our CFLAGS fix https://github.com/EpicGames/UnrealEngine/pull/3015)
- [x] Write docs and samples

**Comment by HeadClot** [comment]
Been waiting for this for a while :D

**Comment by victoranthonyburgos** [comment]
Oh what?!?!?!? Do it, do it!!!! Go go go! Anything to make Paper2D better.

**Comment by Xeppher** [comment]
oh boy

**Comment by victoranthonyburgos** [comment]
FAIL

**Comment by badlogic** [comment]
Meaning?

**Comment by victoranthonyburgos** [comment]
That we love you?

**Comment by badlogic** [comment]
Fail is not necessarily the term I associate with love.
