### ISSUE TITLE
[unity] SpineEditorUtilities.OnPostprocessAllAssets() json asset exception

### ISSUE THREAD

**Issue by AndreyPostelzhuk** [EsotericSoftware/spine-runtimes#730]
We have our own asset with extention '.json'. 
class SpriteEditorUtilities throws an exception every time our json file is reimported:
> KeyNotFoundException: The given key was not present in the dictionary.
> System.Collections.Generic.Dictionary`2[System.String,System.Object].get_Item (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
> Spine.Unity.Editor.SpineEditorUtilities.IsValidSpineData (UnityEngine.TextAsset asset) (at Assets/spine-unity/Editor/SpineEditorUtilities.cs:1162)
> Spine.Unity.Editor.SpineEditorUtilities.ImportSpineContent (System.String[] imported, Boolean reimport) (at Assets/spine-unity/Editor/SpineEditorUtilities.cs:531)
> Spine.Unity.Editor.SpineEditorUtilities.OnPostprocessAllAssets (System.String[] imported, System.String[] deleted, System.String[] moved, System.String[] movedFromAssetPaths) (at Assets/spine-unity/Editor/SpineEditorUtilities.cs:510)

This line is causes exception:
`var skeletonInfo = (Dictionary<string, object>)root["skeleton"];`

**Comment by pharan** [comment]
This was already fixed in git. The unitypackage hasn't been updated yet.
