### ISSUE TITLE
[webgl][demos] Update exports to 3.5

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#731]
Once spine-ts is updated to 3.5 and merged with master, update demo exports.

**Comment by badlogic** [comment]
I do JS, @NathanSweet does assets :D

**Comment by NathanSweet** [comment]
You do all the things! I think this is done?

**Comment by NathanSweet** [comment]
Oh I was supposed to look into why the looping is broken. Doing that!

**Comment by badlogic** [comment]
Exports are up-to-date, unless they change on the final 3.5 stable release.

Looping does indeed need to be fixed. Thought that was my thingy, but knock
yourself out :D
