### ISSUE TITLE
[runtimes] Port AnimationState changes to runtimes

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#732]
See https://github.com/EsotericSoftware/spine-runtimes/issues/621
- [x] spine-libgdx
---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d
---
- [x] spine-c
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs
---
- [x] spine-as3
- [x] spine-starling
---
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

**Comment by badlogic** [comment]
@NathanSweet fixed up a bunch of stuff in the following commits, which also needs to be ported:

https://github.com/EsotericSoftware/spine-runtimes/commit/40d1224db895f80f64cd9ed3707b942c0c98232e
https://github.com/EsotericSoftware/spine-runtimes/commit/48e686ad953c1de2f9527cd3e93a10fa93051e00
https://github.com/EsotericSoftware/spine-runtimes/commit/2287256c72d445887166aa7a03ad5e095ccf48d2
https://github.com/EsotericSoftware/spine-runtimes/commit/fae60d88997f4486f7774dcea985fd2be3f84ba9

**Comment by pharan** [comment]
Heads up, some of the changes aren't in those 4 commits. Had to review the whole thing.

**Comment by badlogic** [comment]
Which changes? These are 4 changes Nate made after my first language port
to TypeScript last week.

**Comment by badlogic** [comment]
And another last minute change that needs porting

https://github.com/EsotericSoftware/spine-runtimes/commit/cd826f1836d3cc18a5642fc930b6ad9c82165450

**Comment by pharan** [comment]
This isn't AnimationState.
Also, in what way are these "last minute"?

**Comment by badlogic** [comment]
@pharan These are tightly connected to the AnimationState changes, hence we I didn't open a new issue. They are last minute in so far as Nate already said AnimationState is done 2 weeks ago :D

Here's another one to port in AnimationState https://github.com/EsotericSoftware/spine-runtimes/commit/d84a39ba90b79886431bdeb043dced7feb6a0521

**Comment by pharan** [comment]
https://github.com/EsotericSoftware/spine-runtimes/commit/fcb878081c481bd63ca77735fbf2e88ab8b5b354
I'm so good.
