### ISSUE TITLE
getWorldScaleX meaning

### ISSUE THREAD

**Issue by ivanpopelyshev** [EsotericSoftware/spine-runtimes#736]
Lets look at the code https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-ts/core/src/Bone.ts#L190

```ts
getWorldRotationX () {
	return Math.atan2(this.c, this.a) * MathUtils.radDeg;
}
```

Vector X of bone is (this.c, this.a).

And 8 lines below:

```ts
getWorldScaleX () {
	return Math.sqrt(this.a * this.a + this.b * this.b) * this.worldSignX;
}
```

Why "this.b"?

**Comment by badlogic** [comment]
This has been fixed in the spine-ts-3.5 branch, along with a new way of specifying the transform mode for bones.
