### ISSUE TITLE
[unity] In the spine joined the collision , complains in unity .

### ISSUE THREAD

**Issue by zxl408** [EsotericSoftware/spine-runtimes#740]
I joined in the collision in the spine , and then imported into unity , the unity generated skeleton SkeletonData times wrong.Below is the error log：
`Error reading skeleton JSON file for SkeletonData asset: skeleton_SkeletonData
Error reading animation: idle
  at Spine.SkeletonJson.ReadSkeletonData (System.IO.TextReader reader) [0x00d7e] in E:\UnityWorkSpaces\SpineStudy\Assets\spine-csharp\src\SkeletonJson.cs:290 
  at Spine.Unity.SkeletonDataAsset.GetSkeletonData (Boolean quiet) [0x0017e] in E:\UnityWorkSpaces\SpineStudy\Assets\spine-unity\Assets\spine-unity\Asset Types\SkeletonDataAsset.cs:142 
UnityEngine.Debug:LogError(Object, Object)
Spine.Unity.SkeletonDataAsset:GetSkeletonData(Boolean) (at Assets/spine-unity/Assets/spine-unity/Asset Types/SkeletonDataAsset.cs:148)
Spine.Unity.Editor.SkeletonDataAssetInspector:OnEnable() (at Assets/spine-unity/Assets/spine-unity/Asset Types/Editor/SkeletonDataAssetInspector.cs:111)
Spine.Unity.Editor.SkeletonDataAssetInspector:DoReimport() (at Assets/spine-unity/Assets/spine-unity/Asset Types/Editor/SkeletonDataAssetInspector.cs:302)
Spine.Unity.Editor.SkeletonDataAssetInspector:OnInspectorGUI() (at Assets/spine-unity/Assets/spine-unity/Asset Types/Editor/SkeletonDataAssetInspector.cs:177)
UnityEditor.DockArea:OnGUI()
`

**Comment by pharan** [comment]
@zxl408 
Sorry, this isn't enough information to know what went wrong.
Can you send your json and atlas files to unity@esotericsoftware.com?

**Comment by zxl408** [comment]
I have already send bug details by email

**Comment by pharan** [comment]
Your skeleton seems to have been exported from Spine 2.1.17
```
{"skeleton":{"hash":"vWQe9VfWSSYoO/rAqHZPqs1dUEQ","spine":"2.1.27","width":273.9,"height":408.08}
```

Make sure you are using the runtime that matches that. If you are using the latest runtime, it will not load that old format.
Particularly, Spine 3.3 runtime and higher cannot load older jsons.
