### ISSUE TITLE
Request for Phaser Runtime plugin

### ISSUE THREAD

**Issue by shibekin69** [EsotericSoftware/spine-runtimes#742]
Hi,

Yeah, as what the title says :). Phaser's a pretty popular JS game engine so I was expecting this to be supported when I bought Spine, but unfortunately that wasn't the case. Can we kindly request some sort of plugin/wrapper?

**Comment by badlogic** [comment]
We currently have no plans to add a Phaser runtime ourselves. However, there's a maintained Phaser Spine runtime that's based on the latest and greatest spine-ts runtime. See https://github.com/orange-games/phaser-spine
