### ISSUE TITLE
spine-ts not support weightedmesh!!

### ISSUE THREAD

**Issue by sherrydeng** [EsotericSoftware/spine-runtimes#744]
spine-ts not support weightedmesh!!

**Comment by badlogic** [comment]
Yes, it does. Please demonstrate how it does not giving reproduction steps and I'll reopen this issue.

**Comment by sherrydeng** [comment]
`"default": 
{
"arm1": {
"body/body_2": { "x": 79.89, "y": 7.38, "rotation": 77.06, "width": 190, "height": 239 }
},
"body": {
"body/body_3": {
"type": "weightedmesh",
"uvs": [],
"triangles": [],
"vertices": [],
"hull": 40
}}}`

json exported from 3.2.01
the type is **weightedmesh**


in SkeletonJson.ts
readAttachment function

switch (type) {
	case "region": {
	}
	case "boundingbox": {
	}
	case "mesh":
	case "linkedmesh": {
	}
	case "path": {
	}
}

not have weightedmesh, is this version not support or i did something wrong.

when i changed the code like below:
switch (type) {
	case "region": {
	}
	case "boundingbox": {
	}
	case "mesh":
	case "weightedmesh":
	case "linkedmesh": {
	}
	case "path": {
	}
}

it works, is this a bug?

**Comment by badlogic** [comment]
No, it's not a bug. You need to use the Spine Editor version compatible
with the Spine Runtime version you are using.

spine-ts from the master branch on GitHub is compatible with Spine editor
version 3.4.02. Please export your models from that Spine editor version.
