### ISSUE TITLE
[as3] new AnimationState with rotate timeline mix

### ISSUE THREAD

**Issue by bp74** [EsotericSoftware/spine-runtimes#746]
I updated my StageXL port of the AS3 runtime to the latest version (dev branch) and i had an issue where the mix of two rotate timelines did not work correctly. I checked the source code several times and i even compared it with the LibGDX version. 

https://github.com/EsotericSoftware/spine-runtimes/blob/dev/spine-as3/spine-as3/src/spine/animation/AnimationState.as#L292

The problem is that the "total" variable get's huge. The result is that the bones are rotating like crazy when you mix two rotate timelines. I don't really understand what the comment "Store loops as part of lastTotal" means (see line 287) - to me it looks like that this is the reason why "total" get's so big.

Code in AS3 and Java:

```
r1 += total * alpha;
bone.rotation = r1 - (16384 - int((16384.499999999996 - r1 / 360))) * 360;
```

My "workaround" code:

```
total -= (16384 - int((16384.499999999996 - total / 360))) * 360;
bone.rotation = r1 + total * alpha;
```

With the workaround it works perfectly fine. So maybe there is something wrong with my code somewhere else. But it would be great if you could take a look at it too. Thanks!

**Comment by NathanSweet** [comment]
How does mixing behave with your animations in the beta [Skeleton Viewer](http://esotericsoftware.com/spine-skeleton-viewer#Download)?

**Comment by bp74** [comment]
Hmmm ... does not run. For a fraction of a seconds i see a window opening, which closes immediately :(

**Comment by NathanSweet** [comment]
Run from a command prompt to see the error.

**Comment by bp74** [comment]
Okay, version 3.4.02 runs fine - only 3.5.04-beta does not.
See error message below (i don't have the spineboy folder there).

C:\Tools>java -jar skeletonViewer-beta.jar
com.badlogic.gdx.utils.SerializationException: Error parsing file: spineboy/spineboy.json
        at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:77)
        at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:103)
        at com.esotericsoftware.spine.SkeletonViewer.loadSkeleton(SkeletonViewer.java:165)
        at com.esotericsoftware.spine.SkeletonViewer.create(SkeletonViewer.java:121)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: spineboy\spineboy.json (Internal)
        at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
        at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:163)
        at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:75)
        ... 5 more
java.lang.NullPointerException
        at com.esotericsoftware.spine.SkeletonViewer.render(SkeletonViewer.java:300)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by NathanSweet** [comment]
Thanks. Please redownload the JAR and try again.

**Comment by bp74** [comment]
I copied "spineboy" to the folder and now the Skeleton Viewer starts fine. Changing from one animation to the other looks correct. So it's obviously something else that is wrong with my implementation ... 

Will test the new version of Skeleton Viewer now.

**Comment by bp74** [comment]
Yes, Skeleton Viewer Beta starts fine now!

**Comment by NathanSweet** [comment]
Seems like a bug in spine-as3 if it works fine in SK beta. Can you post (or email contact@esotericsoftware.com) the skeleton JSON?

**Comment by bp74** [comment]
I've sent it to the email adress. It's the Spineboy animation exported with 3.5.03-beta

**Comment by bp74** [comment]
This is my AnimationState:

    var animationStateData = new AnimationStateData(skeletonData);
    animationStateData.setMixByName("idle", "walk", 0.2);
    animationStateData.setMixByName("walk", "run", 0.2);

When i change from "idle" to "walk" or from "walk" to "run" all slots are starting to rotate in those 0.2 seconds. When only one animation is running everything is fine. And the reason is that the "total" variable starts at 0.0 but after a few frames it's -4000.0. It looks like that the value is reduced by appr. 360° every frame.

**Comment by NathanSweet** [comment]
OK, thanks for finding specifically what is wrong. Maybe the rotation clamping (the crazy bit with 16384) isn't working as it should in AS3. I'm sure @badlogic can fix it up Monday morning.

**Comment by bp74** [comment]
Awesome! Thanks a lot for your help.

**Comment by bp74** [comment]
I think i know the answer to the problem now. The problem is that Java returns the remainder when you do (a % b) and not the modulo. For example if you do -1 % 2 you will get -1 in Java, but 1 in other languages.

http://stackoverflow.com/questions/5385024/mod-in-java-produces-negative-numbers

So the following line of code will behave different depending on the programming language:
https://github.com/EsotericSoftware/spine-runtimes/blob/dev/spine-as3/spine-as3/src/spine/animation/AnimationState.as#L287

If you do this in Java:

    total = diff + lastTotal - lastTotal % 360; // Store loops as part of lastTotal.

You have to do this in other programming languages (depending on their modulo implementation):

    total = diff + lastTotal - lastTotal.remainder(360.0);
    total = diff + lastTotal - (lastTotal - (360 * int(lastTotal/360)));  // alternative

**Comment by bp74** [comment]
Just to clarify the issue (maybe the information got lost in the conversation). I saw that problem in my port of the runtime to the Dart language, i have not actually tried it in AS3. The AS3 runtime is just my reference for the port. But the problem may very likely appear in one of your ports too.

I found this information on Wikipedia:
https://en.wikipedia.org/wiki/Modulo_operation

For example in the Lua language the result of the modulo operator will always have the same sign as the divisor. In our case the divisor is positive (360) so the result will be positive too. 

Btw. i noticed that the code could be simplified to this (which will work in all languages):

    total = diff + (360 * int(lastTotal/360)));

**Comment by NathanSweet** [comment]
Ahh, you should have mentioned the bug is not actually in spine-as3. We can still help, but it keeps us from wasting time looking at the wrong things. You can use `ceil(x / 360 - 0.5f) * 360` instead. The mod is a fancy way to do `ceil`.

**Comment by bp74** [comment]
I don't think that i have wasted your time - sorry! Won't bother you in the future.

**Comment by badlogic** [comment]
Nate just woke up :) You haven't wasted our time! Going forward, please let
us know which runtime you found the bug in, even if it's your own.

**Comment by NathanSweet** [comment]
No worries, just mention the issue you are having is in your Dart port, and/or setup AS3 and give it a whirl. It was confusing how it could be we could have missed the problem in our testing of spine-as3. I think AS3 is OK. You're right that some languages need special treatment and can use `ceil`.
