### ISSUE TITLE
[SkeletonViewer] shows crazy textures

### ISSUE THREAD

**Issue by bp74** [EsotericSoftware/spine-runtimes#747]
This is not really an issue with the runtimes, but with the Skeleton Viewer - hope you don't mind.

The textures are not shown correctly. I have tested this on two different Windows 10 PCs with different graphics cards and drivers. So it looks like a common problem. The UI elements are looking okay, it's just the animation.

![image](https://cloud.githubusercontent.com/assets/1810450/19837251/39c009ce-9eb6-11e6-9fa0-e9d65c61ca9e.png)

**Comment by NathanSweet** [comment]
How are the images saved? Does unchecking `Premultiplied` help?

**Comment by bp74** [comment]
The export is without "Premultipied" - just a standard 32bit PNG image. But i noticed something else - if i export the atlas with 100% scale i see the problem, when i export it with 50% scale to problem is gone. I attach the two exports to this issue. 

[spineboy.zip](https://github.com/EsotericSoftware/spine-runtimes/files/561410/spineboy.zip)

**Comment by NathanSweet** [comment]
Unchecking `Premultiplied` in the Skeleton Viewer causes the images to be displayed correctly. The atlas format doesn't record if the images are premultiplied, so you have to use the rendering setting you exported the atlas with. When you have it checked, you are seeing the results of the `Bleed` texture packing setting, which is required to get proper blending without PMA. Using PMA is ideal though, you get proper blending, can do additive blending without a batch flush, and file sizes should be slightly smaller.
