### ISSUE TITLE
[lua][corna][bug]  Events 

### ISSUE THREAD

**Issue by BlytzStyle** [EsotericSoftware/spine-runtimes#751]
repeating event?
log corona
....
0 event: Intro, test, 0, 0, ''
0 event: Intro, test, 0, 0, ''
0 event: Intro, test, 0, 0, ''
0 event: Intro, test, 0, 0, ''
0 event: Intro, test, 0, 0, ''
....
sample is attachment
[spine_test_corona.zip](https://github.com/EsotericSoftware/spine-runtimes/files/571276/spine_test_corona.zip)

skeleton.json one event in animation

"events": [
			{ "time": 0.8333, "name": "test" }
		]

thank you for your attention!

**Comment by badlogic** [comment]
This issue has been fixed, see the linked commits. Thanks for reporting!
