### ISSUE TITLE
[as3] DrawOrderTimeline - return missing

### ISSUE THREAD

**Issue by bp74** [EsotericSoftware/spine-runtimes#752]
Hi,

I think there is a return missing here:
https://github.com/EsotericSoftware/spine-runtimes/blob/dev/spine-as3/spine-as3/src/spine/animation/DrawOrderTimeline.as#L75

Java has it here:
https://github.com/EsotericSoftware/spine-runtimes/blob/dev/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Animation.java#L954

**Comment by badlogic** [comment]
Good catch! Thanks for reporting, fixed!
