### ISSUE TITLE
[ts] trailing slashes

### ISSUE THREAD

**Issue by ivanpopelyshev** [EsotericSoftware/spine-runtimes#753]
https://github.com/EsotericSoftware/spine-runtimes/blob/dev/spine-ts/core/src/PathConstraint.ts#L139

https://github.com/EsotericSoftware/spine-runtimes/blob/dev/spine-ts/core/src/Skeleton.ts#L471

**Comment by badlogic** [comment]
Holy shit, I explicitely setup VS Code to remove ANY trailing whitespace. WTF is happening.

**Comment by badlogic** [comment]
Oh, nm, that's formatting helpers for Nate :D

**Comment by ivanpopelyshev** [comment]
Whats formatting helpers?

**Comment by badlogic** [comment]
Markers that keep e.g. Eclipse from eliminating new lines etc.
