### ISSUE TITLE
[lua] Problem with Skins and LinkedMeshes, "Parent Mesh not found"

### ISSUE THREAD

**Issue by Rennan24** [EsotericSoftware/spine-runtimes#754]
Currently in the Lua runtimes for spine there seems to be a problem with the SkeletonJson Lua module, when readAttachment is called from a linked mesh the code that gets the skin is incorrect which causes the linkedMesh to not have a skin reference to it, which causes the "Parent Mesh not found" error

In SkeletonJson.lua
```Lua
if parent then
	mesh.inheritDeform = getValue(map, "deform", true)
	table_insert(self.linkedMeshes, {
		mesh = mesh,
		skin = getValue(map, skin, nil), -- < Change this table reference
		slotIndex = slotIndex,
		parent = parent
	})
	return mesh
end
```
should be changed to 
```Lua
if parent then
	mesh.inheritDeform = getValue(map, "deform", true)
	table_insert(self.linkedMeshes, {
		mesh = mesh,
		skin = getValue(map, "skin", nil), -- < To this string
		slotIndex = slotIndex,
		parent = parent
	})
	return mesh
end
```

Which fixed the problem for me because getValue is just a dictionary lookup function but passing in a table to it is incorrect in this context, but passing in the string is correct. I haven't checked any of the other runtimes though so hopefully the problem is only in the Lua runtime...

Also sorry I couldn't just submit a pull request or commit since it seems like I didn't have enough permission and I'm still inexperienced when it comes to the whole Git thing, especially other people's projects. Thanks guys for this awesome runtime though! :D

**Comment by badlogic** [comment]
Thanks for reporting, fixed!
