### ISSUE TITLE
[lua][corona][bug] - 2 key when typing quickly

### ISSUE THREAD

**Issue by BlytzStyle** [EsotericSoftware/spine-runtimes#755]
Attempt to index global 'next' (a function value)

File: spine-lua/AnimationState.lua
Line: 692

stack traceback:
	spine-lua/AnimationState.lua:692: in function 'disposeNext'
	spine-lua/AnimationState.lua:572: in function <spine-lua/AnimationState.lua:559>
	(tail call): ?
	main.lua:133: in function <main.lua:130>
	?: in function <?:169>

main.lua

...
Runtime:addEventListener("key", function(event)
	if activeSkeleton == 1 and event.phase == "down" then
		state = skeletons[activeSkeleton].state
		state:setAnimationByName(0, "jump", false)
		state:addAnimationByName(0, "walk", true, 0)
	end
	return false
end)
...

**Comment by badlogic** [comment]
Thanks, fixed!
