### ISSUE TITLE
ColorTimeline doesn't work or isn't fully implemented in spine-canvas.js

### ISSUE THREAD

**Issue by Saniamos** [EsotericSoftware/spine-runtimes#756]
If you alter the given example of the spineboy.json so the muzzle in the shoot animation so it looks like this:
`"muzzle": {
	"color": [
		{
			"time": 0,
			"color": "ffffff99",
			"curve": [ 0.118, 0.99, 0.75, 1 ]
		},
		{
			"time": 1,
			"color": "ffffffff",
			"curve": [ 0.821, 0, 0.909, 0.89 ]
		},
		{ "time": 2, "color": "ffffff00" }
	],
	"attachment": [
		{ "time": 0, "name": "muzzle" }
	]
}`

The fading in the shoot animation in the widget example works fine, however it does not in with canvas

Since we cannot use webgl in this case we are quite dependend on it working in canvas. What is the state regarding this? Is it broken, or just not fully implemented?

**Comment by NathanSweet** [comment]
Please see the supported features of the spine-ts Canvas backend:
https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-ts#spine-version
The limitation is with the Canvas API.

**Comment by Saniamos** [comment]
oh sorry, missunderstanding from my side about the color tinting, sorry to bother you about it

**Comment by badlogic** [comment]
Could you elaborate on why WebGL is not an option for you?

**Comment by Saniamos** [comment]
We're running CEF on top of the actual program, enabeling webgl would make the whole thing incredebly slow.
But since we don't need actual color tinting, but only fading from black to transparent we altered the library a little and that's enough for our needs
