### ISSUE TITLE
[c3] Add support for Scirra Construct 3

### ISSUE THREAD

**Issue by SysDiman** [EsotericSoftware/spine-runtimes#762]
I think this plugin will be needed, at a large community Scirra
https://github.com/flyover/spine-c2-plugin is not working properly, and developer of this plug-in does not support it for more than 8 months, plus the functionality of this plugin not enough to work with animations (for example, there is no way to keep track of the start or the end of specific animation).

And in any case, the plugin from the official developers will be more qualitative than by 3d-party developer.

**Comment by badlogic** [comment]
We've been checking out Construct 2 a while ago. For us, we need to see community demand to consider spending resources on an official runtime.

**Comment by SysDiman** [comment]
https://www.scirra.com/forum/feature-request-spine-plugin_t184275
I asked the community to help in the promotion of this request, but it was a logical question - Spine better than Spriter?
I gave the answer as I could, I hope you will correct me and to give a more detailed response.

**Comment by glerikud** [comment]
I would be interested in this plugin. It could come handy in some of my projects. The C2 community is growing day-by-day. If you can support the engine with an official plugin, I think it would benefit both sides.

**Comment by makapixel** [comment]
I am using the very abysmal third party spine plugin for Construct 2. I have gotten to work a bit but I would very much appreciate a more official Construct 2 plugin. Hopefully this will help kick off more support in order for that to happen. Spine is leagues and leagues beyond Spriter and it should get the respect and support it deserves.

Thank you!

**Comment by virtmar** [comment]
I echo everything that has been said. This plugin would allow us to push our animations to completely new levels! I really hope we get enough people to support this, because Spine is such a great product. I confirm, we need this plugin!

**Comment by miskas** [comment]
Definitely need this plugin. Spine is great tool. This allows me to use my existing Spine assets in Construct projects. Without this plugin I need to use a different solution for my Construct projects.

**Comment by tatosgames** [comment]
Spine has much more potential than Spriter for construct... the needs of that caused the creation of a non official plugin.
Actually the non official Spine Construct 2 plugin is pretty buggy and it ruins the "public opinion" 
Spine > Spriter
Spriter C2 Plugin > Actual Spine Plugin
I would like to change this :)

In addition: now C3 beta is out but the plugin conversion is pretty simple

**Comment by mhazaru** [comment]
Would love to see this as well. Construct makes 2D stuff very easy to do, but it just needs a good animation engine like Spine to go with it.

**Comment by badlogic** [comment]
With the C3 release coming closer, and with Scirra planning on adding an editor SDK, we decided to start working on a C3 plugin, instead of C2.

**Comment by badlogic** [comment]
I've now looked into this for a few days. A few observations which lead me to temporarily freeze development of this runtime. If anyone has any input or solutions to the below problems, let me know!

- The SDK currently doesn't support editor plugins. We can not render Spine skeletons in the editor.
- The rendering API isn't very well documented. I found a few other OSS plugins that do custom rendering, but they also seem to mostly just do what they think is OK. It's unclear which WebGL state can be touched, how resources are managed, and so on.
- Both WebGL and Canvas based rendering needs to be tested on all target platforms. While desktop web platforms (Edge, Chrome, Firefox, Safari) are a no brainer, it's unclear to me what JS wrappers for mobile stand-alone apps should be tested.
- There doesn't appear to be an asset loading API. Everything needs to be done manually, by the user, to provide an instance with e.g. the contents of a JSON file. The Spine format consists of at least 3 files (JSON/binary, .atlas and one or more .png files for the atlas). It's entirely unclear how this can be done in a way not to burden the user with a multi-step workflow.

I've contacted Scirra via email, we'll see if there are SDK side changes on the horizon that will make this better.

**Comment by joelmayer87** [comment]
I would be very interested in a C3 Plugin for future projects as well :)

**Comment by Cipriux** [comment]
Construct 2 user here. I will replace the Spriter workflow with Spine and willing to pay for it. Spine is great tool. I honestly don't care much for Construct 3 since I will never use a software based on monthly/year payment plan and NEVER EVER use a browser based software for real development. So I support this idea as long as is for Construct 3 AND 2 also.

**Comment by teetteet** [comment]
Construct2 user here too. I would love to see Spine for C2 too.

**Comment by MikalDev** [comment]
@badlogic 

There is a new release  67of C3 with this comment, hopefully this will help you get going (and to request for features you need):

https://www.construct.net/make-games/releases/beta/r67

"Additionally we've started working on adding support in the SDK for drawing plugins (i.e. plugins that appear in the Layout View). This involves quite a large API surface, so it will probably take a few releases to mature. We'll be updating the documentation soon to cover the new features. We're interested in developer feedback to make sure we add all the features necessary for third-party drawing plugins to work."

**Comment by MikalDev** [comment]
@badlogic 

Another C3 release, now with documentation on the drawing plugins. The Spriter team is also working on a plugin for C3 now, hopefully Spine can have one also in the near future.

Details in this thread:
https://www.scirra.com/forum/drawing-plugins-now-supported-in-r68_t197970

**Comment by felixwcf** [comment]
Another C2 and soon-to-be C3 developer say hi...

**Comment by badlogic** [comment]
New SDK API allows us to at least get non-Mesh/FFD going. See https://www.scirra.com/forum/test-spriter-c3-addon_t198037

**Comment by Scoremonger** [comment]
That's great! Yet another C3 user here (they released their first stable version today), and I'm really wanting to use Spine instead of Spriter in my projects.

**Comment by Monkeyzav** [comment]
C3 user here, definitely a big +1 need :)
Hope things can make mesh being taken in account, 'cause spine without mesh is... uh.... not cool.

**Comment by bilgekaan** [comment]
+1

**Comment by tonnochiroad** [comment]
C2/C3 User here - A Spine plugin for C3 would be amazing for the indie game I've been developing with a small team. Would love to advocate for the fantastic Spine at events like Rezzed. But for now I'm a Spriter user.

**Comment by badlogic** [comment]
An update from Scirra relevant to this issue https://construct3.ideas.aha.io/ideas/C3-I-126

**Comment by MegaOptimus** [comment]
Any news/progress?
Making HTML5 games with Spine would be awesome.

**Comment by luckyrawatlucky** [comment]
+1 I need this plugin too

**Comment by theTMO** [comment]
+1 Spine support PLZ

**Comment by Paps90** [comment]
+1 I also need Spine support
Spine > Spriter

**Comment by starkiJi** [comment]
+1 Spine support !!!

**Comment by masscube** [comment]
+1 Please add spine support for construct 3 runtime! Thank you

**Comment by starkiJi** [comment]
Hello, is there information? We were already waiting!)

**Comment by kentkan** [comment]
I am a C2 and Spriter user. I would say Spine is more sophisticated. It could be one of the major reasons for me moving to C3 if Spine is well supported.

**Comment by sjrya** [comment]
I want

**Comment by cerxer** [comment]
Is there any progress?

**Comment by bilgekaan** [comment]
:(

**Comment by Nightshimmer** [comment]
It would be super nice to see a plugin for Construct 3. Thank you :)

**Comment by MegaOptimus** [comment]
Unity 2d skinning has all of the features spine has, and it works flawlessly with unity animator. Meaning you have no need for programming knowledge to use animations. With some cheap visual based programming plugins you can easily make anything you would with Construct. Spine has become obsolete in my opinion. Which is sad as I bought the pro version and never actually used it because of lack of support.

**Comment by MikalDev** [comment]
I am experimenting with this. With the new C3 JS features, it's a bit easier to directly use the Spine-TS runtime to integrate with C3.

As a first step, I integrated the Spine-TS meshes demo into a C3 project, rendering the Spine animation on a separate canvas. I also created a C3 helper plugin to display the Spine render canvas as a C3 object which can be controlled similar to a sprite. The control of the Spine animation must be done though JS Spine-TS API calls, the helper is not a full C3 plugin for Spine.

If you just need to get a few Spine animations into your C3 project and you know how to code JS in C3, you can check out this example and see if will help you. If you have not started coding in JS and C3 yet, I would not recommend this approach.

[C3 Spine Example Forum thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/spine-animation-js-template-145940)

**Comment by simonpaulkeating** [comment]
Please let C3 have spine support! This would be massive.

**Comment by MikalDev** [comment]
See work in progress below. The latest version is 1.3.0.0 (check the github for the latest in dist.)

https://gritsenko.github.io/c3_spine_plugin/

Latest version of addon:
https://github.com/gritsenko/c3_spine_plugin/tree/master/dist

**Comment by avatar45D** [comment]
An official plugin for construct 3 would be very helpful! Many thanks to MikalDev for his plugin! But official support from esotericsoftware would be very helpful.

**Comment by NathanSweet** [comment]
FWIW, MikalDev's Construct 3 runtime has gotten very nice!
http://esotericsoftware.com/forum/Construct-3-Spine-runtime-released-14296

**Comment by badlogic** [comment]
Mikal's plugin is excellent and based on our spine-ts and spine-webgl code. As such, the plugin can pretty much automaticallynget the latest amd greatest official changes, while Mikal ensures that the C3 side is as good as it can get. We aren't C3 experts as he is, so it makes sense to keep this split.
