### ISSUE TITLE
[c] memory leak

### ISSUE THREAD

**Issue by ka7713** [EsotericSoftware/spine-runtimes#764]
//AnimationState.c : line 68
void _spEventQueue_free (_spEventQueue* self) {
	FREE(self->objects);
        //-----------add
        FREE(self); 
}

//AnimationState.c : line 209
void spAnimationState_dispose (spAnimationState* self) {
	int i;
	_spAnimationState* internal = SUB_CAST(_spAnimationState, self);
	for (i = 0; i < self->tracksCount; i++)
		_spAnimationState_disposeTrackEntries(self, self->tracks[i]);
	FREE(self->tracks);
	_spEventQueue_free(internal->queue);
	FREE(internal->events);
	FREE(internal->propertyIDs);
        //---------add
        FREE(internal); 
}

//AnimationState.c : line 156
//if (entry->listener) entry->listener(SUPER(self->state), type, entry, 0);
if (entry->listener) entry->listener(SUPER(self->state), SP_ANIMATION_DISPOSE, entry, 0);
//if (self->state->super.listener) self->state->super.listener(SUPER(self->state), type, entry, 0);
if (self->state->super.listener) self->state->super.listener(SUPER(self->state), SP_ANIMATION_DISPOSE, entry, 0);

**Comment by badlogic** [comment]
Thanks, fixed!
