### ISSUE TITLE
Why build error by Using cocoa pods ?

### ISSUE THREAD

**Issue by poholo** [EsotericSoftware/spine-runtimes#765]
I can update third party libs by cocoapods within 'spine-cocoapods', but It show me this
`clang: error: invalid deployment target for -stdlib=libc++ (requires iOS 5.0 or later)` error when I building the project. Can you help me ?

**Comment by badlogic** [comment]
I'm afraid we are not maintaining a Cocoapod for Spine. Please fetch the sources from this repository instead. The pod I found is heavily outdated and was appearently published by an unknown 3rd party.
