### ISSUE TITLE
[Unity] skeleton graphic only load first material

### ISSUE THREAD

**Issue by netquer1** [EsotericSoftware/spine-runtimes#766]
Is it  a bug ?
1. export two picture file (use small size to split one)
2. test animation use both file
3. import to unity and add skeleton data, use skeleton graphic, will get error pixel in runtime (two parts of body use same material)

**Comment by pharan** [comment]
Hello!

SkeletonGraphic derives from the UnityEngine.UI.MaskableGraphic class that only supports one material/texture.

It's a limitation of the Unity class that incorporates into the UI system's masking.

**Comment by netquer1** [comment]
Oh, I got it.
thank you
