### ISSUE TITLE
Is duplicated call End Event at Event Queue?

### ISSUE THREAD

**Issue by eternitylsh** [EsotericSoftware/spine-runtimes#768]
//AnimationState.c : line 156
case SP_ANIMATION_END:
				if (entry->listener) entry->listener(SUPER(self->state), type, entry, 0);
				if (self->state->super.listener) self->state->super.listener(SUPER(self->state), type, entry, 0);
				/* Fall through. */
			case SP_ANIMATION_DISPOSE:
				if (entry->listener) entry->listener(SUPER(self->state), type, entry, 0);
				if (self->state->super.listener) self->state->super.listener(SUPER(self->state), type, entry, 0);
				_spAnimationState_disposeTrackEntry(entry);
				break;

under... one person fix code in prev issue.
//if (entry->listener) entry->listener(SUPER(self->state), type, entry, 0);
if (entry->listener) entry->listener(SUPER(self->state), SP_ANIMATION_DISPOSE, entry, 0);
//if (self->state->super.listener) self->state->super.listener(SUPER(self->state), type, entry, 0);
if (self->state->super.listener) self->state->super.listener(SUPER(self->state), SP_ANIMATION_DISPOSE, entry, 0);

**Comment by badlogic** [comment]
Thanks!
