### ISSUE TITLE
Starling Runtime + Texture Packer Trim, Offset bug

### ISSUE THREAD

**Issue by JustinLivi** [EsotericSoftware/spine-runtimes#77]
Hi Nate, I posted this in the Starling forum, but I just realized that this was probably the proper place to post. Sorry! 

Anyhow, the summary of the problem I've encountered is that if I don't trim the sprites in texture packer, everything works fine but if I trim them, they get shifted wildly out place.

I dug into the Starling runtime classes a bit and if you set 

attachment.regionOffsetX = 0;
attachment.regionOffsetY = 0;

in StarlingAtlasAttachmentLoader.newAttachment()

everything works except flipped images which get stretched out shape.

I can't figure out why the images would get stretched out of shape though because all your logic looks sound.

**Comment by tsangwailam** [comment]
Sorry, i want to pop up this issue again. The problem i am facing is using a non-trim image (all images have extra white space) and trim in texturePacker. Then, use the texture/atlas with Starling. The position of each images will be displaced. But if not trim in texturePacker, everything is ok.

I am using the newest version of spine-as3 and spine-starling. Also, with the newest version of Starling. I read this thread and found it should be fixed but i still have the problem. Could any one help?

**Comment by ravewings** [comment]
I hope you got a prenup Nate.
