### ISSUE TITLE
[spine-c] memory leaks

### ISSUE THREAD

**Issue by mrpuzzler** [EsotericSoftware/spine-runtimes#770]
I can see leaks for:
1. at _spAnimationState_resizeTimelinesFirst for int* newTimelinesFirst = CALLOC(int, newSize);
2. at spAnimation_create for spAnimation* self = NEW(spAnimation);
3. at spAnimation_create for MALLOC_STR(self->name, name);

**Comment by badlogic** [comment]
1. was a real leak, which I've fixed. 2 and 3 are only leaks if you forget to call spSkeletonData_dispose on your spSkeletonData (which will NOT be disposed if you dispose a spSkeleton).

**Comment by mrpuzzler** [comment]
There is an "<empty>" animation created by the system that is not being freed.

SP_EMPTY_ANIMATION

AnimationState.c line 190

**Comment by badlogic** [comment]
Ah right, forgot about that. It's essentially a static instance which should never be disposed for the life time of the application. Unless you put the spine code in a shared library and keep reloading that shared library, there's no "real" leak.

**Comment by mrpuzzler** [comment]
It's reported by memory tracker ... this is a real leak, as you never free it.

**Comment by badlogic** [comment]
Yes, and that is by design. It's a static spAnimation that we require throughout all instances of spAnimationState. It is supposed to live forever.

**Comment by mrpuzzler** [comment]
How to free it on game side? I don't want to get this leaks.

**Comment by badlogic** [comment]
It is not a leak. It's like any other static resource, it will live and stay the exact same size until your application is closed. Once your app is shut down by the operating system, the OS reclaims its memory, like it reclaims static memory from other parts of (3rd party) code in your app.

**Comment by mrpuzzler** [comment]
I understand, but it's reported by memory tracker, I don't want to see it ...

**Comment by mrpuzzler** [comment]
Anyway, this is not good to not free memory and relay on OS.

**Comment by badlogic** [comment]
You can add a new function in AnimationState.c/h ala spAnimationState_disposeStatic() and `FREE(SP_EMPTY_ANIMATION)` when your application terminates.

**Comment by mrpuzzler** [comment]
possible to make it on your side, so I should not merge updates?

**Comment by badlogic** [comment]
Added spAnimationState_disposeStatics().

**Comment by mrpuzzler** [comment]
Great, thanks

**Comment by jpoag** [comment]
```
void spAnimationState_disposeStatics () {
	FREE(SP_EMPTY_ANIMATION);
	SP_EMPTY_ANIMATION = 0;
}
```

**Comment by jpoag** [comment]
dispose, not free.  spAnimation* SP_EMPTY_ANIMATION allocates a name.

**Comment by jpoag** [comment]
void _spAnimationState_disposeTrackEntry (spTrackEntry* entry) {
    FREE(entry->timelinesFirst);
	FREE(entry->timelinesRotation); // missing this line
	FREE(entry);
}

**Comment by jpoag** [comment]
Opened new issue.
