### ISSUE TITLE
[spine-c] memcpy bugs

### ISSUE THREAD

**Issue by mrpuzzler** [EsotericSoftware/spine-runtimes#771]
Are you sure about this line at _spEventQueue_ensureCapacity

memcpy(newObjects, self->objects, self->objectsCount);

Last param should be number of bytes to copy ... 

Same at _spAnimationState_ensureCapacityPropertyIDs for memcpy

**Comment by mrpuzzler** [comment]
probably better to check all memcpy lines, as this is common issue

**Comment by mrpuzzler** [comment]
How about spSkeletonBounds_update  and memcpy there?

**Comment by badlogic** [comment]
You're right, missed that one. All other memcpys are good. Just commited a fix.
