### ISSUE TITLE
Placeholder SRT

### ISSUE THREAD

**Issue by Gaen** [EsotericSoftware/spine-runtimes#772]
TLDR1: You can't just swap graphics in runtime, you have to swap a RegionAttachment which is graphics and SRT. So when creating a new attachment, you have to get SRT from an old one, which is a real pain.

TLDR2: Placeholder shoud have its own SRT and its content should not, so you could set it up in editor once and then in runtime swap sprites freely.

I expected a placeholder to be some sort of container which allows a workflow similar to this (using Unity):
1. In editor create and export a skeleton with a placeholder that has SRT configured but no graphics inside
2. In runtime put a sprite inside the placeholder (by generating a skin and attaching it to the skeleton)
3. See the sprite attached with correct SRT

As it turned out, one does not simply put a sprite into a placeholder.
1. You have to create a RegionAttachment
2. RegionAttachment requires SRT
3. Your code has to dig inside the skeleton to find an attachment which will be replaced to get SRT from it
4. For that to work ,you have to put a picture in your skeleton to store an SRT for it, even if you don't need the graphics (dummy picture which is replaced with real graphics in runtime)

I also noticed that in editor you can select a placeholder but you can't transform it (previously selected object is transformed instead), looks like there is really no such a thing as placeholder, it's some kind of editor-only virtual entity.

It would be nice for placeholder to actually exist and store SRT, and for placeholder content to get SRT from a placeholder.

**Comment by NathanSweet** [comment]
Not all attachments have a transform (SRT), eg a mesh, path, or bounding box is just a list of vertices and other data. If it did work as you described for regions, what is the origin for each region that goes in the skin placeholder? The region center? When regions are different sizes or if you want to manually define an origin, then you end up with the same problem: each region needs to be positioned individually. If all your regions are the same size, positioning a skin placeholder by itself would not be very meaningful. It doesn't have a width/height, so it would probably be represented as a point. You'd need some sort of placeholder region so you could position the skin placeholder. This doesn't seem better than what we have now.

As you found, a skin placeholder only exists in the editor. At runtime, a skin is a map where a key is a composite key made up of slot index + placeholder name and the value is an attachment.
