### ISSUE TITLE
[spine-c] More memory leaks

### ISSUE THREAD

**Issue by jpoag** [EsotericSoftware/spine-runtimes#775]
SP_EMPTY_ANIMATION is complex allocated object, FREE doesn't dispose of internally allocated members.
```
void spAnimationState_disposeStatics () {
	if(SP_EMPTY_ANIMATION) spAnimation_dispose(SP_EMPTY_ANIMATION);
	SP_EMPTY_ANIMATION = 0;
}
```

timelinesRotation on TrackEntry* is not properly disposed of.
```
void _spAnimationState_disposeTrackEntry (spTrackEntry* entry) {
	FREE(entry->timelinesFirst);
	FREE(entry->timelinesRotation); // missing this line
	FREE(entry);
}
```

I'm still getting one more memory leak for an spTrackEntry , but until I can track it down I don't know who's at fault.

**Comment by badlogic** [comment]
Thanks, fixed! I should drink more coffee, dunno how that slipped.

**Comment by jpoag** [comment]
Thanks, I'm not getting anymore leaks.  Let's hope this is it.

BTW, it would be no problem for me to write a unit test with a memory leak detector.  My unit test code is only 1 or two files and has the ability to report errors to the Continuous Integration server (I use teamcity).  

Basically, it would load up example files using the C interface in one test fixture and C++ interface in another.  Then it would execute a series of animations by looping and sending 16ms update ticks until stopped (or time out).

Finally, the memory leak detector would report leaks as errors.  The CI runs on check-in, and emails you any errors.

Just a thought.

**Comment by mrpuzzler** [comment]
Still leaking _spAnimationState_trackEntry for spTrackEntry* entry = NEW(spTrackEntry);

**Comment by jpoag** [comment]
I stopped getting that, but I'm not sure why. Will look into it.

**Comment by mrpuzzler** [comment]
This is Spine end, not our.

**Comment by mrpuzzler** [comment]
Also getting leaks on _spAnimationState_resizeTimelinesFirst for int* newTimelinesFirst = CALLOC(int, newSize);

**Comment by mrpuzzler** [comment]
and _spAnimationState_resizeTimelinesRotation - also leaking ...

**Comment by mrpuzzler** [comment]
Probably happens while changing state

**Comment by jpoag** [comment]
Those second two are the result of the track entry leak, iirc

**Comment by badlogic** [comment]
Folks, please tell me what tracker are you using so I have the same baseline as you.

**Comment by mrpuzzler** [comment]
Our own, internal. Just track memory allocation with memory hooks you have.

пт, 25 нояб. 2016 г. в 16:43, Mario Zechner <notifications@github.com>:
