### ISSUE TITLE
[c] CI test integration

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#780]
See https://github.com/EsotericSoftware/spine-runtimes/issues/776#issuecomment-263152599

**Comment by badlogic** [comment]
Integrated with overall CMake build, moved spine-c to spine-c/spine-c and adjusted README.mds as well as project files.

**Comment by jpoag** [comment]
Awesome.  Should be...

add_subdirectory(spine-c)
add_subdirectory(spine-c/spine-c-unit-tests)

**Comment by jpoag** [comment]
nevermind, I see what you did
