### ISSUE TITLE
Unused variable warning

### ISSUE THREAD

**Issue by NeatWolf** [EsotericSoftware/spine-runtimes#782]
Unity v5.4.2f2

Assets/Spine/spine-unity/SkeletonUtility/Editor/SkeletonUtilityBoneInspector.cs(52,24): warning CS0414: The private field `Spine.Unity.Editor.SkeletonUtilityBoneInspector.currentSkinName' is assigned but its value is never used

**Comment by pharan** [comment]
I think you have a slightly outdated version of spine-unity.
That field is commented out.

**Comment by NeatWolf** [comment]
Oh. I wasn't expecting the runtimes getting updated so fast. I'll check them.

I believe this one has been solved as well?

Assets/Spine/spine-unity/SkeletonUtility/SkeletonUtility.cs(50,29): warning CS0219: The variable `slotIndex' is assigned but its value is never used
