### ISSUE TITLE
[spine-unity]right click on _SkeletonData.asset, can't find "Spine" menu

### ISSUE THREAD

**Issue by sjzlei1989** [EsotericSoftware/spine-runtimes#783]
I upgrade spine runtime to the latest version. But I can't find "Spine" menu when right click on _SkeletonData.asset file. Is this feature removed? When i right click on the blank of Hierarchy window, i find there are SkeletonRenderer, SkeletonAnimation, SkeletonGraphic, but no SkeletonAnimator. I want to know how to create SkeletonAnimator? Or is SkeletonAnimator is been removed?

**Comment by pharan** [comment]
This was removed in the 3.5 update.
This is how you instantiate now.

http://esotericsoftware.com/forum/New-Feature-Drag-and-Drop-to-instantiate-6789

**Comment by sjzlei1989** [comment]
@pharan  Thanks! Just find how to create animator. Thanks any way.
