### ISSUE TITLE
[ts] Multi-file atlas loading trouble

### ISSUE THREAD

**Issue by rpurushotma** [EsotericSoftware/spine-runtimes#786]
Things work fine for me when using an atlas/json that only point to one png, but when I try and run a project that has enough assets it breaks it up into multiple png sheets, I'm only able to load the first sheet but no subsequent ones (see screenshot -- Timey2.png and Timey3.png are in the same directory as Timey.png). Is there anything I need to do to add the additional files to the manager? AssetManager retrieves Timey.png in the network log, but no attempt for Timey2.png appears. In general, any console logs for errors and exceptions on asset loading would be great

![spine_console](https://cloud.githubusercontent.com/assets/4826791/20725864/25bc43e6-b628-11e6-9deb-526c9e3b535c.png)

http://esotericsoftware.com/forum/Multi-file-atlas-loading-trouble-7477

**Comment by rpurushotma** [comment]
These are the assets I was using incase they're relevant

[spine_multi_file.zip](https://github.com/EsotericSoftware/spine-runtimes/files/620031/spine_multi_file.zip)

**Comment by badlogic** [comment]
Widgets currently don't support multi-page atlases. I'm working on a fix.

**Comment by badlogic** [comment]
I've added a new `WidgetConfiguration` field called `atlasPages`. It allows you to specify all the images needed for the atlas, e.g.

```
new spine.SpineWidget("somediv", {
   json: "assets/spine/Timey.json",
   atlas: "assets/spine/Timey.atlas",
   atlasPages: [ "assets/spine/Timey.png", "assets/spine/Timey1.png", "assets/spine/Timey2.png" ],
   ...
```

Since all assets are loaded asynchronously, we can not know how  many images an atlas is composed of during load time. I'm afraid this is the only way to get multi-page atlases working.

**Comment by rpurushotma** [comment]
Sounds good. Right now the messages you get if you, say, don't leave a trailing slash on your imagesPath url are hard to debug. Please consider changing Widget.ts:132 from:

```
let atlas = new spine.TextureAtlas(this.assetManager.get(this.config.atlas) as string, (path: string) => {
      let texture = assetManager.get(imagesPath + path) as spine.webgl.GLTexture;
      return texture;
   });
```

to

```
let atlas = new spine.TextureAtlas(this.assetManager.get(this.config.atlas) as string, (path: string) => {
      let texture = assetManager.get(imagesPath + path) as spine.webgl.GLTexture;
      if (!texture) {
         console.log(`Texture from path ${imagesPath + path} failed to load, please check the file path. If you are loading multiple images from the same atlas, please see https://github.com/EsotericSoftware/spine-runtimes/issues/786`);
      }
      return texture;
   });
```
