### ISSUE TITLE
[as3] missing new in Atlas.as?

### ISSUE THREAD

**Issue by romamik** [EsotericSoftware/spine-runtimes#787]
spine-runtimes/spine-as3/spine-as3/src/spine/atlas/Atlas.as:

     region.pads = Vector.<int>(parseInt(tuple[0]), parseInt(tuple[1]), parseInt(tuple[2]), parseInt(tuple[3]));

should be 

     region.pads = new Vector.<int>(parseInt(tuple[0]), parseInt(tuple[1]), parseInt(tuple[2]), parseInt(tuple[3]));

??

**Comment by badlogic** [comment]
Thanks!
