### ISSUE TITLE
Animation not playing correctly with latest runtime version

### ISSUE THREAD

**Issue by romamik** [EsotericSoftware/spine-runtimes#790]
Not sure when did it happen, but with version 3.4 runtime animation was playing correctly and with latest runtime it stretches. I've tested js and starling version, they both have the same problem. 
Here is example animation: [Girl_export.zip](https://github.com/EsotericSoftware/spine-runtimes/files/627161/Girl_export.zip)
And screenshots:
![spine35](https://cloud.githubusercontent.com/assets/3735734/20834621/658c37fc-b8a7-11e6-84a8-1f4914bd3d34.png) ![spine34](https://cloud.githubusercontent.com/assets/3735734/20834622/658fafae-b8a7-11e6-836f-83b99a690f67.png)

**Comment by NathanSweet** [comment]
"stretches"?

**Comment by romamik** [comment]
Sorry for my english :-) It gets skew applied.

**Comment by NathanSweet** [comment]
It's hard to tell if anything is wrong. Can you reproduce the problem in the Skeleton Viewer?
http://esotericsoftware.com/spine-skeleton-viewer

**Comment by romamik** [comment]
Yes, in latest Skeleton Viewer animation also looks incorrect, just the same as with latest js and starling runtime.
Do not have Java development environment set to run previous versions...

**Comment by NathanSweet** [comment]
Checking the latest is sufficient, thanks.

The current problem is I can't tell by looking at your skeleton in Skeleton Viewer if it looks wrong, or if it is correct. It might help if you can email the images. contact@esotericsoftware.com We will keep the confidential.

**Comment by romamik** [comment]
Emailed you.

**Comment by romamik** [comment]
[swf.zip](https://github.com/EsotericSoftware/spine-runtimes/files/627210/swf.zip)
Also here are two swfs compiled with 3.4 and 3.5 runtimes to see the difference.

**Comment by badlogic** [comment]
Could you send us the .spine project instead of the exports? E-mail does fine if you don't to share here.

The behaviour of inherit scale/rotation changed between 3.4 and 3.5. Your skeleton's head bone seems to expect the old behaviour. If you open it in 3.5 and disable scale inheritance on the head bone, the behaviour is as it should be from what I can tell.

**Comment by romamik** [comment]
Thank you, sounds like this should solve the issue!
I currently do not have access to spine project, but we will try to do this, and I will report the result. However it will be possible only next week...

**Comment by badlogic** [comment]
@romamik i'm closing this out now. Please get back to me if modifying disable scale/rotation in your Spine project doesn't work out for you.
