### ISSUE TITLE
[spine-c] binary skeletons + constraints + (un)signed char... again

### ISSUE THREAD

**Issue by jphw** [EsotericSoftware/spine-runtimes#794]
related to https://github.com/EsotericSoftware/spine-runtimes/issues/709

The thing is that there are probably more places in the c-spine binary loader code, which work incorrectly if -funsigned-char (or /J) compiler flags are set.

Again, as with previous issue - constrains work well in case if a skeleton loaded from a json, or if char type is signed by default (no compiler flags set). But otherwise I still get broken animations, i.e:
json: http://imgur.com/UVrwF1f
binary + cflags: http://imgur.com/MCxbwyu

I haven't found the exact place in the code that causes this yet though.

**Comment by badlogic** [comment]
Can you send me the .spine file to contact@esotericsoftware.com? Or is it the same as before?

**Comment by badlogic** [comment]
I went through the binary loader to see if there are any implicit signed chars still being used but couldn't find anything. I'll need a repro case to see what's up.

**Comment by jphw** [comment]
I've sent you the animation;

**Comment by badlogic** [comment]
The IK bend direction was read in as signed, but assigned to a `char`, then converted to a `int`. Used `-Wconversion` to identify the issue in `SkeletonBinary.c`. No other such issues found.

Thanks for reporting!
