### ISSUE TITLE
[monogame] Fix VS/XS solutions

### ISSUE THREAD

**Issue by chanliu1983** [EsotericSoftware/spine-runtimes#802]
1>D:\spine-runtimes-master\spine-csharp\src\Attachments\AttachmentLoader.cs(45,3,45,17): error CS0246: The type or namespace name 'PathAttachment' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Attachments\BoundingBoxAttachment.cs(35,39,35,55): error CS0246: The type or namespace name 'VertexAttachment' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Attachments\MeshAttachment.cs(35,32,35,48): error CS0246: The type or namespace name 'VertexAttachment' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Attachments\MeshAttachment.cs(115,37,115,53): error CS0246: The type or namespace name 'VertexAttachment' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Attachments\MeshAttachment.cs(115,24,115,35): error CS0115: 'MeshAttachment.ApplyDeform(VertexAttachment)': no suitable method found to override
1>D:\spine-runtimes-master\spine-csharp\src\Attachments\AtlasAttachmentLoader.cs(80,10,80,24): error CS0246: The type or namespace name 'PathAttachment' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Skeleton.cs(57,22,57,36): error CS0246: The type or namespace name 'PathConstraint' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Skeleton.cs(181,36,181,50): error CS0246: The type or namespace name 'PathConstraint' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Skeleton.cs(464,10,464,24): error CS0246: The type or namespace name 'PathConstraint' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Skeleton.cs(42,24,42,38): error CS0246: The type or namespace name 'PathConstraint' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Animation.cs(612,10,612,26): error CS0246: The type or namespace name 'VertexAttachment' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\Animation.cs(607,12,607,28): error CS0246: The type or namespace name 'VertexAttachment' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\TransformConstraint.cs(34,37,34,48): error CS0246: The type or namespace name 'IConstraint' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\TransformConstraint.cs(136,26,136,34): error CS0115: 'TransformConstraint.ToString()': no suitable method found to override
1>D:\spine-runtimes-master\spine-csharp\src\IkConstraint.cs(34,30,34,41): error CS0246: The type or namespace name 'IConstraint' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\IkConstraint.cs(78,26,78,34): error CS0115: 'IkConstraint.ToString()': no suitable method found to override
1>D:\spine-runtimes-master\spine-csharp\src\SkeletonData.cs(62,22,62,40): error CS0246: The type or namespace name 'PathConstraintData' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\SkeletonData.cs(178,10,178,28): error CS0246: The type or namespace name 'PathConstraintData' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\SkeletonData.cs(44,24,44,42): error CS0246: The type or namespace name 'PathConstraintData' could not be found (are you missing a using directive or an assembly reference?)
1>D:\spine-runtimes-master\spine-csharp\src\SkeletonJson.cs(401,62,401,78): error CS0246: The type or namespace name 'VertexAttachment' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by badlogic** [comment]
You will need the sources from `spine-csharp` besides `spine-xna`.

**Comment by chanliu1983** [comment]
When I open it in VS2015 it I can see spine-csharp and spine-xna properly imported.

Also it is missing one file:

1>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets(63,5): warning VSX1000: The project spinemonogamexamarinstudioios was built while disconnected from a Mac agent, so only the main assembly was compiled. Connect to a Xamarin Mac build agent to build the full application.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "MonoGame.Framework". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>CSC : error CS2001: Source file 'D:\spine-runtimes-master\spine-monogame\xamarinstudio-ios\src\..\..\..\spine-csharp\src\Attachments\WeightedMeshAttachment.cs' could not be found.

**Comment by badlogic** [comment]
The Xamarin Studio project will not work in VS2015. You'll have to create a Windows desktop project for MonoGame in VS2015.

**Comment by chanliu1983** [comment]
You provided this file, spine-monogame-xamarinstudio-ios.csproj is it for VS?

**Comment by badlogic** [comment]
As its name says, the file is meant to be used with XamarinStudio for running on iOS. We do not provide desktop project files for the MonoGame example at the moment.

I propose you create a new MonoGame project yourself, then dump the sources from spine-csharp and spine-xna into your project.

**Comment by chanliu1983** [comment]
So spine-csharp\Attachments\WeightedMeshAttachment.cs is missing would not be a problem if I use xamarinStudio.

**Comment by badlogic** [comment]
As I said, at the moment, your best bet is to create a new MonoGame project and copy the sources from spine-csharp and spine-xna. The XamarinStudio solution may have errors, `WeightedMeshAttachment` has long been removed from the runtime.

**Comment by chanliu1983** [comment]
So I can not rely on the example now, right?

**Comment by badlogic** [comment]
Not using the XamarinStudio solution.

**Comment by dcaudill724** [comment]
spine-runtimes\spine-monogame\windows8-store\src\..\..\..\spine-csharp\src\Attachments\SkinnedMeshAttachment.cs' could not be found.

Everything seems to be working fine except this file seems to be missing and I believe it is causing a bunch of errors in the rest of the code because they are trying to reference it.

**Comment by badlogic** [comment]
I've replaced the old two Monogame solutions with a new, cross-platform, desktop project that works out of the box in both Visual Studio and Xamarin Studio, provided Monogame is installed on the system. See https://github.com/EsotericSoftware/spine-runtimes/commit/ee64dd98eb5ab2301a378d5ce6c0092ca51f0ca8
