### ISSUE TITLE
[cocos2d-x] BlendFunc not working

### ISSUE THREAD

**Issue by chriship** [EsotericSoftware/spine-runtimes#803]
The SkeletonAnimation class seems to be ignoring BlendFunc. If I set both a Sprite and a SkeletonAnimation with the same BlendFunc, it works on the Sprite but not on the SkeletonAnimation.

Any ideas why/how to achieve this?

```
testAnimation = SkeletonAnimation::createWithJsonFile("test.json", "test.atlas", 1);
testSprite = Sprite::create("test.png");

BlendFunc bf;
bf.src = GL_DST_COLOR;
bf.dst = GL_ONE_MINUS_SRC_ALPHA;

testAnimation->setBlendFunc(bf);
testSprite->setBlendFunc(bf);
```

**Comment by badlogic** [comment]
Slots of Spine skeletons have their own blend modes (normal, additive, multiply, screen). You can set these in the Spine editor on the slots of your skeleton. The blend function you provide via `setBlendFunc` is ignored in `SkeletonRenderer.cpp`. If you require to overwrite this behaviour, simply modify your copy of `SkeletonRenderer.cpp`.

**Comment by chriship** [comment]
Thanks for the speedy reply!
