### ISSUE TITLE
[unity] SkeletonRenderer does not update materials properly

### ISSUE THREAD

**Issue by Ran-QUAN** [EsotericSoftware/spine-runtimes#804]
There's a check in `LateUpdate` method for material changes, but when changes are detected, the material cache won't update.

code:
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-unity/Assets/spine-unity/SkeletonRenderer.cs#L537-L553

`workingSubmeshInstructions`'s materials should be copied to `submeshMaterials` when instance id mismatched.

**Comment by pharan** [comment]
Hmm.. I think you're right. We'll do a review of this part and push a fix.

**Comment by pharan** [comment]
Can you share your case where this doesn't work correctly?
