### ISSUE TITLE
[runtimes] Fix recursion in clearTracks

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#805]
See https://github.com/EsotericSoftware/spine-runtimes/commit/f6cf88103c861f4312d7c33c56ae81eae289bc59 and https://github.com/EsotericSoftware/spine-runtimes/commit/7dbf7c5268beccbaaf083f4933f5ea4c0d8ef42c

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling 

---
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

**Comment by badlogic** [comment]
Also close https://github.com/EsotericSoftware/spine-runtimes/issues/797 once done.

**Comment by Fraggle** [comment]
Thanks :)
