### ISSUE TITLE
[AnimationState] Track entries don't get cleared when TrackEntry timeScale is 0 even if mixDuration is 0.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#806]
http://esotericsoftware.com/forum/SkeletonAnimation-Update-Using-97-of-frame-time-7611

Track entries don't get cleared when a TrackEntry's timeScale is 0 even if mixDuration is 0.
The use case above seems to be when a TrackEntry whose animation you like to freeze in a pose is involved in mixing (ie, has a mixingFrom of its own).
This results is a crazy long mixingFrom linked list over time.

Relevant lines: 
mixTime needs to be > 0 to be cleared automatically.
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/AnimationState.java#L134

sideeffect of the larger intention: "Only remove mixingFrom entries from the end of the list."
https://github.com/EsotericSoftware/spine-runtimes/commit/99ca32dabbb15ad5f7d07816b868830e572489e0

mixTime is incremented according to the timeScale of its next node
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/AnimationState.java#L143

**Comment by NathanSweet** [comment]
The `mixTime > 0` requirement ensures the mixingFrom entry is applied at least once. I've added a comment to make this clear (and next time I won't have to figure out why the heck I had it in there).

It seems an explicit check for this case is the only fix.
