### ISSUE TITLE
[cocos2dx] No setEmptyAnimation and addEmptyAnimation in SkeletonAnimation class

### ISSUE THREAD

**Issue by chriship** [EsotericSoftware/spine-runtimes#807]
The documentation for the runtimes states that there is a setEmptyAnimation method and a addEmptyAnimation method for use with clearing the animations. The cocos2d-x runtime doesn't seem to have these methods.

**Comment by pharan** [comment]
That was added in the new Spine AnimationState in 3.5.
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-c/spine-c/src/spine/AnimationState.c#L668

You may be using an older runtime.
You can read the instructions here on how to update to the new one: https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-cocos2dx/README.md

**Comment by chriship** [comment]
Ah ok, yes looks like I am using an older runtime.

**Comment by chriship** [comment]
Just looked into this a bit more - it looks like those methods were added to AnimationState.c but the SkeletonAnimation.cpp has no reference to them.

**Comment by pharan** [comment]
Ah, you're right.
