### ISSUE TITLE
[c] improve json skip calls in parse

### ISSUE THREAD

**Issue by huangwei1024** [EsotericSoftware/spine-runtimes#810]
`value = parse_value(c, skip(value));`

under VS profile, I see `skip` be called too much times, it can not be inline function.
I thought the value string could be trim before parse, so `skip` not needed in parsing. 
And if the json output in compact mode, the trim function could be return fast by predict fixed length.
Because in my project, the spine json is too big, I have to think about this problem.

![image](https://cloud.githubusercontent.com/assets/667876/21524069/5460e2fa-cd4e-11e6-836b-8b318bcf2edd.png)

**Comment by badlogic** [comment]
We use a third party library for parsing JSON. We'd rather not diverge from upstream. Do you have any reason not to use the binary format? That is smaller on average and faster to load.
