### ISSUE TITLE
mixing/blending not working as expected 

### ISSUE THREAD

**Issue by SeminYun** [EsotericSoftware/spine-runtimes#811]
https://github.com/pixijs/pixi-spine/issues/131

captured

Hi,

absolutely possible, that I misunderstanding how this is supposed to work, but here it comes:

I have skeleton with one object and two animation anim1 and anim2. Both animations move the object by 100 units to the right. They both have the same length of 30 frames. I do:

skel.state.setAnimation(0, 'anim1', true).alpha=0.5;
skel.state.setAnimation(1, 'anim2', true).alpha=0.5;

I would expect the object to be at x=100 after thirty frames, but it is not, it is at x=50. Setting alpha to (1,0) works as expected, setting alpha to (0,1) also works as expected. Both animation curves are linear.

Any help or clarification would be appreciated.

thx...

**Comment by badlogic** [comment]
Mixing two animations on two separate tracks is not additive, which is why you see the result you see.
