### ISSUE TITLE
The behavior when animations are done is different between 3.1.08 and 3.5.46 at runtime

### ISSUE THREAD

**Issue by taigacon** [EsotericSoftware/spine-runtimes#812]
I have a project built in editor 3.1.08 and simply upgraded it to 3.5.46, then found something behave different. ( I am using spine-c runtime )
It seems that it will keep the state of last frame when an animation is done in 3.1.08, when in 3.5.46 it will restore to the SETUP state.
I find nothing helpful in the Changelog or something else, so what should I do next?

Thank you!

**Comment by badlogic** [comment]
You are right, the Changelog doesn't keep track of runtime changes. I'll add a changelog going forward in this repository specifically for changes in the runtime.

We've updated our documentation on animations here http://esotericsoftware.com/spine-applying-animations. By  default, the runtimes now mix back to the setup pose as you discovered. See specifically the section on empty animations http://esotericsoftware.com/spine-applying-animations#Empty-animations. You can prevent the mix back to the setup pose by setting `TrackEntry#trackEnd` to a really high value.
