### ISSUE TITLE
[Spine-ts]: Events not firing reliably on iOS devices

### ISSUE THREAD

**Issue by Nahikariii** [EsotericSoftware/spine-runtimes#816]
We have a spine object with two bones and one of them has 4 different events. We run two animations in different tracks at the same time, each animating a different bone.

This works fine on these browsers that we have tested:

- ie11
- chrome
- firefox
- android chrome. 

However, we have an issue on safari (both desktop and iOS) where some of the events are not triggered. We have tried to debug this but it doesn't happen when we have the developer tools opened, which makes it hard to debug. 

We have noticed that this does never happen the first time we run a spine animation, which makes us think it may be some pooling issue or something not being cleaned up properly. The problem is we can't confirm this without a debugger plus it happens "apparently" randomly. We are able to replicate it if we use safari (without the developer tools open) but there is no simple way of replicating it following some steps, it just happens at some point after X ( x > 1) amount of animations run.

I'm sorry, I know this is not very useful but I cannot provide a simple example with it (we will try to simplify our case and update this issue).

I'm opening this issue to get some feedback, is this something expected or it could be a bug? We have tried researching this but we couldn't find anything similar regarding spine-ts. 

Thanks in advance.

**Comment by badlogic** [comment]
I've tested spine-ts on all the browsers you mentioned, including iOS and macOS Safari. I did not run into any such Heisenbug.

The code paths dealing with events are deterministic and will work the exact same in all browsers, baring any JS VM bugs (which happen). There is a pooled structure `EventQueue` responsible for storing and firing events reported by `AnimationState`. But as I said, this queue is deterministic.

I'm afraid I can't do much without a reproduction case :/

**Comment by Nahikariii** [comment]
Thanks for answering. Yeah, we have looked at the code and we can see it's a deterministic queue that's why we are at a loss. We've been trying to simplify our case (it's a big project) today in order to provide an example but failed to do so. 

We are hoping we can provide something next week. 👼

**Comment by Nahikariii** [comment]
We just found out while trying to create the simple example that the issue is fixed on the latest release. We were using an older version of the runtime, we just updated it and we are not able to reproduce it anymore. 

Sorry for the inconvenience. 👼

**Comment by badlogic** [comment]
Not an inconvenience! Happy the latest version fixed it for you!
