### ISSUE TITLE
spine-ts: Triangles of the mesh still visible when playing

### ISSUE THREAD

**Issue by appsolutegeek** [EsotericSoftware/spine-runtimes#817]
Hi,

I have been testing a mesh we have but you can see the outline of triangle (although faint) - kind of like a wireframe, is there a way to hide this ? or is there a setting inside of spine when exporting to hide the wireframe/mesh or at least make it transparent ?

Thanks in advance

**Comment by badlogic** [comment]
Are you using the WebGL or the Canvas backend? 

For WebGL, you want to use pre-multiplied alpha for your atlases. Export your atlases from Spine checking the pre-multiplied checkbox, then set `SkeletonRenderer.premultipliedAlpha` to `true`.

The mesh rendering in the Canvas backend is marked as experimental and uses an affine transform to simulate rendering triangles with quads. Filtering artefacts in the Canvas implementation of some browsers (Safari, some Firefox versions) result in the outlines you see. There is no solution to this I'm afraid.

**Comment by appsolutegeek** [comment]
Yep, I was using canvas :-)

Now to try with webgl

**Comment by huangyiming9228** [comment]
Hi @badlogic , i'm using spine-canvas@3.8, because webgl context has limits of max number, I can only use canvas backend to render animation, but the triangles still visible, is there any way to hide the triangles today ?
![image](https://user-images.githubusercontent.com/34177347/154927337-aea4c60e-86dc-458f-9917-215fcaa0d6af.png)

**Comment by badlogic** [comment]
I'm afraid there is no solution for this with the Canvas API. It's what I explained in the reply above.

**Comment by chr15m** [comment]
@badlogic I have a client using Spine and the project has multiple sprites being rendered on a web page. Can I confirm the following so I can communicate it back to them:

- The `spine-player` depends on WebGL.
- WebGL on Chrome has a restriction on the number of contexts on the page at once.
- This puts a hard limit on the number of sprites on a page being drawn with `spine-player`.
- An alternative is using the low level `spine-canvas`.
- However `spine-canvas` has rendering artifacts (visible triangles) as shown above.

Is this correct? Are there any other options for rendering multiple Spine animations into a web page? I guess if it's the case I'll need to look at other solutions outside Spine.

**Comment by badlogic** [comment]
Your summary is correct, but is missing one thing you can't know about yet. @davidetan is working on a solution that lets you put as many skeletons on a page with a single WebGL enabled, transparent overlay canvas. We are seeing excellent results with that both on desktop and mobile in our testing. You can already play around with it on this branch:

https://github.com/EsotericSoftware/spine-runtimes/blob/ts-webgl-overlay/spine-ts/spine-webgl/src/SpineWebComponentWidget.ts

You can see usage here:
https://github.com/EsotericSoftware/spine-runtimes/blob/ts-webgl-overlay/spine-ts/spine-webgl/example/webcomponent-tutorial.html

Here's a live version for you to check out:
https://esotericsoftware.com/files/spine-widget/webcomponent-tutorial.html

The whole thing is based on web components, which makes integration pretty simple. Can't give you an ETA, but will likely be completed this year.

**Comment by chr15m** [comment]
Ok sounds good, thank you. For now I will see if I can do some scaling and blurring to get the canvas renderer working without artifacts. I'll keep an eye out for the update.
