### ISSUE TITLE
[cocos2d-x] Shear not working for nesting bones

### ISSUE THREAD

**Issue by dualface** [EsotericSoftware/spine-runtimes#818]
My animation have a bone named as "archer_root", like below picture:

![my_skel](https://cloud.githubusercontent.com/assets/62318/22022168/c53fe2d4-dcfb-11e6-9a8e-51182f91b8dd.png)

Like as you see, "archer_root" have three child-bones: archer, left_foot and right_foot.

But my codes not working expected, "archer_root" is not flipped, but can do it for "archer".

```cpp
auto scene = Scene::create();

auto skel1 = spine::SkeletonAnimation::createWithJsonFile("tower_arrow.json", "tower_arrow.atlas", 2.0f);
skel1->setAnimation(0, "shot_middle", true);
skel1->findBone("archer_root")->shearY = -180; // not working
skel1->setPosition(Vec2(200, 200));
scene->addChild(skel1);

auto skel2 = spine::SkeletonAnimation::createWithJsonFile("tower_arrow.json", "tower_arrow.atlas", 2.0f);
skel2->setAnimation(0, "shot_middle", true);
skel2->findBone("archer")->shearY = -180; // bone "archer" is flipped
skel2->setPosition(Vec2(200, 400));
scene->addChild(skel2);

Director::getInstance()->runWithScene(scene);

```

Resources download:

[tower_arrow.zip](https://github.com/EsotericSoftware/spine-runtimes/files/711135/tower_arrow.zip)

**My question**: This is a bug or a feature ?

**Comment by dualface** [comment]
I use latest runtime for cocos2d-x.

**Comment by badlogic** [comment]
I'd suggest to negate the scaleY of the bone not the shearY. I'll investigate if there's an issue with shear, thanks for reporting!

**Comment by dualface** [comment]
Thanks you replay.

I have try scaleY, it's not working:

```cpp
skel1->findBone("archer_root")->scaleY = -1;
```

**Comment by badlogic** [comment]
Ah, you are applying an animation. This will overwrite whatever values you assign to the bones during setup. You can fix this in two ways:

1. Do not key the bones you want to modify in code, e.g. "archer_root" in your animations.
2. Modify the bones **after** the animation is applied and before `spSkeleton_updateWorldTransform` is called, in every frame.

**Comment by dualface** [comment]
Great, I will try it. thanks !

**Comment by dualface** [comment]
![1](https://cloud.githubusercontent.com/assets/62318/22024382/cfb37e0c-dd04-11e6-98d5-ace44f7e10c0.png)

It's working. 

```cpp
skel->findBone("archer_wrap")->scaleY = -1;
```

**Comment by badlogic** [comment]
Great! Happy it worked out :)
