### ISSUE TITLE
[c] spSkeletonBinary does not use custom allocators 

### ISSUE THREAD

**Issue by Rattenhirn** [EsotericSoftware/spine-runtimes#821]
In kvec.h allocations are done with realloc and free. This is doubly annoying, because the pointers created with realloc are then handed out and deleted with FREE, causing problems when using a custom allocator.

For you convenience I have attached a patched version of kvec.h that uses Spines's custom allocators.

[kvec.zip](https://github.com/EsotericSoftware/spine-runtimes/files/714145/kvec.zip)

**Comment by badlogic** [comment]
Wonderful! I've had this on my todo for a while, thanks for the fixed up kvec, I'll integrate it sometime this week.

**Comment by badlogic** [comment]
I've applied and tested your fix, works as intended. Merged with master. Thanks!
