### ISSUE TITLE
[Unity] Spine.Animation vs string

### ISSUE THREAD

**Issue by Rennan24** [EsotericSoftware/spine-runtimes#824]
I was wondering if there is a way for us to serialize the Spine.Animation instead of serializing it to a string since you get access to the duration, name, and timelines of the animation. 

example
```CSharp

[ SpineAnimation ]
public Spine.Animation shootingAnim1;

[ SpineAnimation ]
public string shootingAnim2;

private void Start ( )
{
    // Possible with Spine.Animation
    Debug.Log ( shootingAnim1.duration );
    Debug.Log ( shootingAnim1.name );

    // Not possible with string
    Debug.Log ( shootingAnim2.duration );
    Debug.Log ( shootingAnim2.name );
}

```

The only way I know how to make it less annoying is to have a private Spine.Animation field and initialize it at startup and then use it later. Am I just approaching this the wrong way?

**Comment by pharan** [comment]
Unfortunately, no.

Spine.Animations aren't serializable UnityEngine.Objects. They're plain C# objects shared across all all spine-csharp runtimes (including XNA/Monogame).

They come from the Skeleton json/binary file, which you could update at any time. I suppose there could be an intermediate format can converts the skeleton data into a serializable UnityEngine.Object. It would be a complicated implementation though, exactly because it would need to know how to sync between any skeleton data entities that get renamed or rearranged.

One option is to have a custom class/struct that has and serializes as a string but is easy to load in code, so you don't need two or more object fields per animation. Either way, it costs a bit of indirection.

**Comment by Rennan24** [comment]
I see, thanks for the quick response though. Also thanks for the potential solution! 😄

**Comment by pharan** [comment]
Just a sample. It might make it into the official runtime someday.

```csharp
using UnityEngine;
using System.Collections.Generic;

namespace Spine.Unity {
	
	[System.Serializable]
	public class SerializedAnimation {
		[SpineAnimation][SerializeField]
		protected string name;
		protected Animation animation;

		public string Name { get { return name; } }
		public Animation Animation { get { return animation; } }

		#region Initializers
		public void Initialize (SkeletonData data) {
			animation = data.FindAnimation(name);
		}

		public void Initialize (Skeleton skeleton) {
			this.Initialize(skeleton.data);
		}

		public static void Intialize (SkeletonData data, params SerializedAnimation[] items) {
			foreach (var a in items)
				a.animation = data.FindAnimation(a.name);
		}

		public static void Initialize (SkeletonData data, List<SerializedAnimation> items) {
			foreach (var a in items)
				a.animation = data.FindAnimation(a.name);
		}
		#endregion

		#region Casting
		public static implicit operator Animation (SerializedAnimation sa) {
			return sa.animation;
		}

		public static implicit operator string (SerializedAnimation sa) {
			return sa.name;
		}

		public override string ToString () {
			return name;
		}
		#endregion
	}

}

// Editor part to simplify the struct in the inspector.
// Ideally on a separate .cs file stored in an Editor folder for Editor assembly compilation.
#if UNITY_EDITOR
namespace Spine.Unity.Editor {
	using UnityEditor;

	[CustomPropertyDrawer(typeof(SerializedAnimation))]
	public class SerializedAnimationEditor : PropertyDrawer {

		public override void OnGUI (Rect position, SerializedProperty property, GUIContent label) {
			position.height = EditorGUIUtility.singleLineHeight;
			EditorGUI.PropertyField(position, property.FindPropertyRelative("name"), label);
		}

		public override float GetPropertyHeight (SerializedProperty property, GUIContent label) {
			return EditorGUIUtility.singleLineHeight;
		}
	}
}
#endif
```

**Comment by Rennan24** [comment]
Oh dang! This looks sweet, I was trying to put together what you said by myself but this is awesome! Hopefully something like this makes it into the runtimes because it would be pretty useful. 👍

**Comment by pharan** [comment]
Had a minor update. Better copy the latest if you want to use it.
Any suggestions for a better name?

**Comment by Rennan24** [comment]
Oh thanks for the heads up. I don't really have a better name though, SerializedAnimation describes it pretty well, unless someone else has any other suggestions.
