### ISSUE TITLE
[runtimes] Mixing with setup pose

### ISSUE THREAD

**Issue by imyourm8** [EsotericSoftware/spine-runtimes#827]
Example based on Spine-csharp port
AnimationState.cs

Method **ApplyMixingFrom**
225th line code
i think idea is to mix with setup pose when previous entry has timeline which current doesn't has. But it turns out that on this line

`bool setupPose = timelinesFirstItems[i];`

It always uses setup pose mixing and produce strange mixing especially when setup pose is very different from animation.

**Comment by pharan** [comment]
Hello! This is an existing issue: https://github.com/EsotericSoftware/spine-runtimes/issues/815

If you're using a C# runtime, can you try this experimental version?
https://gist.github.com/pharan/cffdc3b2aee9288c9ca8b4ab94ee97d2
