### ISSUE TITLE
how to get run with cocos2d-x?

### ISSUE THREAD

**Issue by ArkMike** [EsotericSoftware/spine-runtimes#830]
I according to the setup of the readme, the second step, and the third is to do what?
The third step is to delete which path of files?
And download the Spine Runtimes source inside "Place cocos2dx here. TXT" do?
i rearlly need some help

**Comment by badlogic** [comment]
Step 2. and 3. instruct you do delete the Spine runtime that comes with cocos2d-x. It tells you exactly what folder in your cocos2d-x copy to delete from disk and delete from the corresponding IDE project.

You can find an example project you can look at for reference here https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-cocos2dx/example

**Comment by ArkMike** [comment]
I just can't see how these two steps of operation,

**Comment by badlogic** [comment]
Step 2 involves deleting the folder `cocos2d/cocos/editor-support/spine` via Finder on macOS or the file explorer on Windows. I'm not sure how else I can describe it.

Step 3 requires you do delete the source references to the files from the `cocos2d/cocos/editor-support/spine` in the IDE you use. E.g. in Xcode there would be a folder `spine` under `editor-support` (which is already deleted in the image below).

![](https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-02-23%20at%2011.29.07%20AM-qdGa5ccDgR.png)

**Comment by ArkMike** [comment]
Ok, still failed   =_=|||

**Comment by badlogic** [comment]
Please post the error you get.
