### ISSUE TITLE
[ue4] crashed when import animation

### ISSUE THREAD

**Issue by w2moon** [EsotericSoftware/spine-runtimes#837]
When i try to import an animation which has larger than 2048 width on a single image( not the atlas width ), the UE4 crashed.

Access violation - code c0000005 (first/second chance not available)

UE4Editor_SpinePlugin!USpineAtlasAsset::GetAtlas() [e:\project\spine-runtimes\spine-ue4\plugins\spineplugin\source\spineplugin\private\spineatlasasset.cpp:102]
UE4Editor_SpineEditorPlugin!USpineAtlasAssetFactory::LoadAtlas() [e:\project\spine-runtimes\spine-ue4\plugins\spineplugin\source\spineeditorplugin\private\spineatlasimportfactory.cpp:132]
UE4Editor_SpineEditorPlugin!USpineAtlasAssetFactory::FactoryCreateFile() [e:\project\spine-runtimes\spine-ue4\plugins\spineplugin\source\spineeditorplugin\private\spineatlasimportfactory.cpp:79]
UE4Editor_UnrealEd
UE4Editor_AssetTools
UE4Editor_AssetTools
UE4Editor_SpineEditorPlugin!LoadAtlas() [e:\project\spine-runtimes\spine-ue4\plugins\spineplugin\source\spineeditorplugin\private\spineskeletonimportfactory.cpp:73]
UE4Editor_SpineEditorPlugin!USpineSkeletonAssetFactory::FactoryCreateFile() [e:\project\spine-runtimes\spine-ue4\plugins\spineplugin\source\spineeditorplugin\private\spineskeletonimportfactory.cpp:88]

**Comment by badlogic** [comment]
Hm, that means atlas creation failed. Could you send me the assets you used (Spine project, export)? You can send them to contact@esotericsoftware.com.

**Comment by badlogic** [comment]
@w2moon I've tried to reproduce this with a big atlas and regions but didn't see a crash. Please provide your Spine project as requested in my last comment here. I'll reopen once I can repro it with your assets.
