### ISSUE TITLE
[skeletonviewer] Play sounds on events

### ISSUE THREAD

**Issue by Hinidu** [EsotericSoftware/spine-runtimes#840]
Hi!
We want to bind sound playing to spine events and we need to give some tool for our musician that he can use to see how animations and sounds fit together. We think that extending of skeletonviewer to allow to map sound files to events is a viable idea (maybe you have other suggestions?).
I have two questions:
1) Are you interested in something like this? (I will try to implement in any case but if you are not interested I will do it in my fork).
2) I have very small experience with Java and I don't understand how do you manage your dependencies - I've imported your projects to Eclipse but I don't know where I should put gdx-related dependencies and from where I should take them.
Thank you in advance!

**Comment by NathanSweet** [comment]
We have plans to support audio in Spine. Until we get to that, you can try this:
http://esotericsoftware.com/forum/Spine-Plugin-in-Support-5859?sid=374be67386fc7f43e3b3e1e0e72a2773&p=27032#p27032
This syncs a single WAV file with Spine editor playback, which can be used to synchronize animation to music or dialog. When the editor supports audio, we'll also have sounds that can be triggered by events.

Note you can use events and have them trigger sounds at runtime. This doesn't help preview in the editor though.

libgdx setup questions are best asked on the libgdx forums or IRC. spine-libgdx doesn't use Gradle yet. I set up libgdx by using Ant, run `ant -f fetch.xml` in libgdx so the libgdx binary dependencies are downloaded, then you can import the libgdx projects into Eclipse and spine-libgdx will just work. You don't need all libgdx projects, but it may be hard to see which you need. Try: gdx, gdx-backend-lwjgl, gdx-box2d, gdx-jnigen.

**Comment by Hinidu** [comment]
We don't need the support for audio in Spine itself because we want to have quite complex audio system in our game: different types of audio, choosing the random audio file from the list, etc. Though I think we will not modify skeletonviewer but write something ourselves with WPF or QT because we already did some instruments using spine-runtimes with these technologies.
