### ISSUE TITLE
[ts] support passing json and atlas contents

### ISSUE THREAD

**Issue by geddski** [EsotericSoftware/spine-runtimes#844]
I'm using the Widget runtime which currently makes its own `XHR` to fetch the `.json` and `.atlas` files. I'd prefer to inline these assets into my build with [webpack](https://webpack.github.io/). Would this be possible to add support for passing these to the HTML5 runtimes?

**Comment by badlogic** [comment]
How'd you inject them into the widget? JS or data URL in tag?

**Comment by geddski** [comment]
for the JSON file we could pass either a parsed JSON object. Data Uri is a good idea because it would work for the tag syntax as well.

**Comment by badlogic** [comment]
Passing a JSON object via JS (or the text of an .atlas file) should be
easy, I can add that to the configuration object.

**Comment by geddski** [comment]
That would be perfect, thank you!

**Comment by badlogic** [comment]
This is in master now. Two new fields were added to `WidgetConfiguration`:

* `atlasContent`: string holding the contents of an `.atlas` file. If given overrides `atlas` field, so the resource isn't fetched from the web.
* `jsonContent`: string or parsed JSON object holding the contents of a `.json` skeleton file. If give, overrides `json` field, so the resource isn't fetched from the web.

Hth!

**Comment by geddski** [comment]
@badlogic cheers! Thank you so much!

**Comment by badlogic** [comment]
@geddski quick update. I added support for inlining images as well. See https://github.com/EsotericSoftware/spine-runtimes/blob/3.6-beta/spine-ts/widget/example/index.html#L32 and the README.md for details.

**Comment by geddski** [comment]
@badlogic oh awesome! Perfect timing, I was just today going to try to figure out a way to preload/cache the images to prevent a flash when changing widgets. This is great. Thank you!

**Comment by geddski** [comment]
@badlogic I'm not sure how to use it, don't see anything in the README for it.

**Comment by geddski** [comment]
@badlogic trying to follow the example you posted, but spine-widget still makes an http request for the .png file...

**Comment by damy90** [comment]
@badlogic Hi, Is it still possible to pass content instead of url?
I can't find the readme file with the example mentioned above or the SpineWidget class anywhere in the project. As for the fields `atlasContent`, `atlasPagesContent`, and `jsonContent`, I only see these in old changelog entries when I search the source code.

**Comment by damy90** [comment]
@geddski I think you should have used atlasPagesContent as well
