### ISSUE TITLE
[ue4] Spine atlas causes engine crash 

### ISSUE THREAD

**Issue by Khannarc** [EsotericSoftware/spine-runtimes#845]
Hello,

  I'm currently working on a 2D game project in UE4 and my team got really excited with the release of a spine runtime plugin for the engine. I spent yesterday installing the different tools I needed to integrate the plugin and setting up the project for it. 

  My issue is the following. When I tried to import a .skel file with atlas and such it went perfectly well. But as soon as I tried to assign it to a skeleton animation within an actor it crashed the engine as soon as I plugged the .atlas into the component.

Here's the crash log that appears aftermath :

  Access violation - code c0000005 (first/second chance not available)

UE4Editor_SpinePlugin!readString() [d:\arashi_project_buildversion06 4.15\plugins\spineplugin\source\spineplugin\public\spine-c\src\spine\skeletonbinary.c:155]
UE4Editor_SpinePlugin!spSkeletonBinary_readSkeletonData() [d:\arashi_project_buildversion06 4.15\plugins\spineplugin\source\spineplugin\public\spine-c\src\spine\skeletonbinary.c:893]
UE4Editor_SpinePlugin!USpineSkeletonDataAsset::GetSkeletonData() [d:\arashi_project_buildversion06 4.15\plugins\spineplugin\source\spineplugin\private\spineskeletondataasset.cpp:107]
UE4Editor_SpinePlugin!USpineSkeletonAnimationComponent::CheckState() [d:\arashi_project_buildversion06 4.15\plugins\spineplugin\source\spineplugin\private\spineskeletonanimationcomponent.cpp:110]
UE4Editor_SpinePlugin!USpineSkeletonAnimationComponent::InternalTick() [d:\arashi_project_buildversion06 4.15\plugins\spineplugin\source\spineplugin\private\spineskeletonanimationcomponent.cpp:96]
UE4Editor_SpinePlugin!USpineSkeletonAnimationComponent::TickComponent() [d:\arashi_project_buildversion06 4.15\plugins\spineplugin\source\spineplugin\private\spineskeletonanimationcomponent.cpp:91]
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Core
UE4Editor_Core
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Kismet
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

  I hope you will be able to provide me with help as soon as you can. I'm pretty new to this and I'm just the "engine guy" on this project so I'm not in charge of our Spine works and might ignore some basics. 

Please receive the expression of my best regards.

**Comment by badlogic** [comment]
Are you working off of the master branch or the 3.6-beta branch? Can you provide me with steps to reproduce the issue?

**Comment by Khannarc** [comment]
The plugin we are using comes from the master branch I picked up on github. 

  As for reproducing the bug here's how it happened : 
  -We exported our spine animation, using binary with a .skel extension including nonessential datas and atlas files. As for the settings of the atlas we went with the default ones, so maybe there is something we did wrong here.
  -Then I imported the .skel in UE4 using the Import tool (No grab and slide here)
  -After that I created an empty actor blueprint in my main BP folder.
  -I opened the actor BP, went to the viewport tab, added a "spine skeleton animation component" then proceeded to successfuly plug in the .skel in "Skeleton Data".
  -the second I click the corresponding .atlas in the drop down menu for assigning the component the engine crashes.

  I hope this will be sufficient for you to reproduce the bug. In case you shall require additional information please let me know as soon as you can.

  Please receive the renewed expression of my best regards. Thanks for your quick answer and amazing work.

**Comment by badlogic** [comment]
What version of the Spine editor was the data exported from? Could you try using a JSON export instead of a binary export and check if that works?

**Comment by Khannarc** [comment]
We are currently using Spine version 3.6.06.

Exporting as .json fixed the crash issue. Yet the skeleton is now super blurry and upscaled many times when rendered in the editor. We will rummage through the whole integration process hoping for the best now.

  Thanks a lot for your fast response. I wish you a wonderful day.

**Comment by NathanSweet** [comment]
Note if you are using 3.6.06-beta you'll need to use the beta runtimes, which can be found in the `3.6` branch:
https://github.com/EsotericSoftware/spine-runtimes/tree/3.6-beta

**Comment by Khannarc** [comment]
I had no idea about that... Thanks for the intel, gonna try.

**Comment by badlogic** [comment]
For the blur and upscaling, you'll have to modify the UE4 scene lighting, e.g. disable screen space blur, temporal aliasing etc. Please google for UE4 renderer settings usually used for 2D.

**Comment by NathanSweet** [comment]
No problem! More info on versioning is [here](http://esotericsoftware.com/spine-settings#Version). If you wish to switch to non-beta, you can export to JSON and try importing into the latest 3.5 version. You may need to edit the JSON if you've used beta-only features.

**Comment by badlogic** [comment]
@Khannarc I'm closing this out now. Let us know if you run into other UE4 issues!
