### ISSUE TITLE
[ts] spine-widget.js animation loop is loaded anyway

### ISSUE THREAD

**Issue by BlytzStyle** [EsotericSoftware/spine-runtimes#853]
fix it Line 7571:

animationState.setAnimation(0, config.animation, true);

I think it is fair so:

animationState.setAnimation(0, config.animation, config.loop);

_sample html_

new spine.SpineWidget("spine-widget" + index, {
				json: "spine/sensore.json",
				atlas: "spine/sensore.atlas",
				**loop:false**,
......

thank you

**Comment by badlogic** [comment]
Thanks for reporting. Fixed in master!
