### ISSUE TITLE
[csharp][unity] "Error reading animation"

### ISSUE THREAD

**Issue by TicTocGarth** [EsotericSoftware/spine-runtimes#856]
Hello!

I'm not  sure what an artist did to cause this, but we were getting an error, `Error reading skeleton JSON file for SkeletonData asset: <SkeletonData asset name> / Error reading animation: <Animation name>` when copying over files from Spine into Unity.

I tracked it down to `spine-csharp/SkeletonJson.cs` in the `ReadAnimation` method. In the `Deform timelines` section, there is this line where the `deform` array is not large enough to fit`verticesValue`.

```
... else {
    deform = new float[deformLength];
    int start = GetInt(valueMap, "offset", 0);
    float[] verticesValue = GetFloatArray(valueMap, "vertices", 1);

    // Exception here! If start is greater than 0 then deform is too small!
    Array.Copy(verticesValue, 0, deform, start, verticesValue.Length);

    if (scale != 1) {
        for (int i = start, n = i + verticesValue.Length; i < n; i++)
        deform[i] *= scale;
    }

    if (!weighted) {
        for (int i = 0; i < deformLength; i++)
            deform[i] += vertices[i];
    }
}
```
Forcing `start = 0` caused a glitch in the mouth shape of one of our animations. I increased the Length of the `deform` array by `start` so that it would be able to fit the `verticesValue` array. Our animations seem to run in Unity now.

This is the edit that allowed me to load the animation in Unity.
```
int start = GetInt(valueMap, "offset", 0);
deform = new float[deformLength + start]; // Adding start to the Length of deform
```
**_I'm not sure what consequences this will have!_** However, at least now we can work with the animations in Unity. I'll update if I find any other bugs that come from this.

**Comment by badlogic** [comment]
What version of the Spine Editor did your artist export from? What version of the Spine Unity Runtime are you using?

**Comment by badlogic** [comment]
@TicTocGarth I'll reopen once you provide me with the information I requested. My guess is that the Spine Editor version your artist exported from does not match the Spine Unity Runtime version you are using.
