### ISSUE TITLE
[spine-unity][editor] Import Json file

### ISSUE THREAD

**Issue by ManakaMi** [EsotericSoftware/spine-runtimes#858]
Hello!

Will not the process of SpineEditorUtilities.cs now assume that all Json files are for Spine?

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs#L1228

Is there a way to exclude the specified json processing?

Thank you

**Comment by pharan** [comment]
Thanks for reporting. This issue existed in an older version but it was supposed to be fixed.
The current check actually checks for a "skeleton" node right under the root node.

Is it that you have large json files that aren't Spine and it's trying to check them?

**Comment by ManakaMi** [comment]
thank you for reply to me.

Yes, it is.
We have a lot of Json files in "Dictionary <string, object>" format.
(Not Spine Meta Json)

Currently, ReImport gives a lot of warning messages.
https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-unity/Assets/spine-unity/Editor/SpineEditorUtilities.cs#L1228

It is not fatal in our current project, so I am waiting for correction.

**Comment by pharan** [comment]
Ah, there's a small flaw in the checking logic. Thanks for reporting again. This should be fixed soon.
