### ISSUE TITLE
[unity] Keyed constraints on multiple tracks

### ISSUE THREAD

**Issue by GisleSolv** [EsotericSoftware/spine-runtimes#860]
We have one animation called Climb_Ladder playing on track 1, at the same time we have an animation called Eat_Blueberries playing on track 2. 
Eat_Bluberries is 100 frames long and keys the arm constraints 100%, but on frame 30 they are keyed to 0% to make them mix over to whatever animation is playing. 
Climb_Ladder loops and continually keys the arm constraints 100%. 
However, after playing Eat_Blueberries one time, the arm constraint will never let itself be keyed by the Climb_Ladder animation, even though Eat_Blueberries is stopped at the last frame, and that frame has no constraint keys.

This seems like a bug to me, but I'm not sure if this is intended behaviour?

**Comment by pharan** [comment]
It does seem like a bug. Likely exists in the other runtimes too.

We're in the process of reworking AnimationState and mixing behaviors.
Can you replace your AnimationState code with this and see if that fixes it?
https://gist.githubusercontent.com/pharan/cffdc3b2aee9288c9ca8b4ab94ee97d2/raw/a9d167770cb3cb8cce5e07d54bb0895b40d060e0/AnimationState.cs

**Comment by GisleSolv** [comment]
Changing out the animation state code caused the animations to persist on the track even though they finished playing. 
Uncommenting this line took care of that.. I'm guessing this is work in progress. 
entry.trackEnd = float.MaxValue; // loop ? float.MaxValue : animation.Duration;

With or without the comment, it didn't seem to fix my original issue I'm afraid.

**Comment by pharan** [comment]
There were some fixes to AnimationState recently.
Please reopen the issue if the problem still exists.

Note that the line you mentioned.
```
entry.trackEnd = float.MaxValue; // loop ? float.MaxValue : animation.Duration;
```
refers to the preferred default behavior of non-looping animations.
If you want non-looping animations to continue to be applied with their final pose long after its last key, you should use the current code.
If you want non-looping animations to end immediately after their last key, use `loop ? float.MaxFalue : animation.Duration`
