### ISSUE TITLE
[libgdx] Paths not working on old devices 

### ISSUE THREAD

**Issue by zepplondon** [EsotericSoftware/spine-runtimes#861]
Hi.
I've described my issue on the official page, but didn't get any feedback yet.
Hope to catch some attention here.
http://esotericsoftware.com/forum/Paths-not-working-on-old-devices-8070

**Comment by badlogic** [comment]
I replied an hour ago :)

**Comment by badlogic** [comment]
Let's continue on the forum, closing this out for now. Please provide the info I asked for on the forum as well.

**Comment by zepplondon** [comment]
Sure. Thanks. I'll test and reply on the forum asap.
