### ISSUE TITLE
[unity] Review SkeletonAnimator blending

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#864]
Introduce calculation of "accumulated weight".
http://esotericsoftware.com/forum/Incorrect-blending-when-using-SkeletonAnimator-Unity-8083

**Comment by pharan** [comment]
Pseudocode:
```
float runningTotal = 1.0 - trackAlpha; // apply alpha to total
foreach (trackEntry in track) {
     float phase = track.mixPhase;
     runningtotal += mixPhase;
     float appliedAlpha = phase / runningTotal;
     trackEntry.Apply(..., appliedAlpha);
}
```

Theoretically, it looks like this:
```
mix phase		| ++runningTotal 		| applied alpha
0.5			| 0.5				| 1
0.5			| 1				| 0.5
0.5			| 1.5				| 0.3333~

mix phase		| ++runningTotal 		| applied alpha
0.3			| 1				| 1
0.			| 2				| 0.5
1			| 3				| 0.3333~

mix phase  	 	| ++runningTotal 		| applied alpha
0.2			| 0.2				| 1
0.6			| 0.8				| 0.75
0.4			| 1.2				| 0.3333~
```

**Comment by NathanSweet** [comment]
From @Pharan on the [forum post](http://esotericsoftware.com/forum/Incorrect-blending-when-using-SkeletonAnimator-Unity-8083?p=37638#p37638):
> The problem with this seems to be that it cannot mix/fade back to setup pose as needed, especially parts-wise, since animation property sets are not guaranteed to perfectly intersect. This seems fine as a behavior for SkeletonAnimator as long as it's consistent with Mecanim.

We've got a fix for the "dipping", discussed here:
http://esotericsoftware.com/forum/Blend-Weirdness-in-Unity-3-5-7263?p=37700#p37700

**Comment by pharan** [comment]
@NathanSweet This is unrelated to SkeletonAnimator. SkeletonAnimator doesn't use Spine.AnimationState.

**Comment by pharan** [comment]
This will have a pass with the work on the Playable translator.
