### ISSUE TITLE
[runtimes] Port dipping problem fix

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#867]
See https://github.com/EsotericSoftware/spine-runtimes/commit/13c34e8751aedd48d7914c0e0ff58a322424c18e

- [x] spine-libgdx

---
- [x] spine-csharp
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas (not supported)
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

**Comment by pharan** [comment]
I have a correction for this. See: https://github.com/EsotericSoftware/spine-runtimes/commit/13c34e8751aedd48d7914c0e0ff58a322424c18e#diff-2e690293d0fea3104ddda07be1d1e5c9R223

**Comment by badlogic** [comment]
Reply here once ported to spine-c http://esotericsoftware.com/forum/Mixing-fail-in-cocos2d-x-8200

**Comment by pharan** [comment]
There's one very common source of dipping (interrupted mixing) that could be removed.
https://github.com/EsotericSoftware/spine-runtimes/pull/871

**Comment by badlogic** [comment]
Also need to port https://github.com/EsotericSoftware/spine-runtimes/commit/f8ea8e99ca3e822f9647ededbc5fdde5966e90aa

**Comment by badlogic** [comment]
Everything ported. Could try to add interrupted mixing dipping problem fix mentioned by @pharan
