### ISSUE TITLE
[unity] NullReferenceException when clone MeshAttachment

### ISSUE THREAD

**Issue by Ran-QUAN** [EsotericSoftware/spine-runtimes#869]
Position:
https://github.com/EsotericSoftware/spine-runtimes/blob/0afe70ee9d4a742c54459b23b0990fa05b3f520e/spine-unity/Assets/spine-unity/Modules/AttachmentTools/AttachmentTools.cs#L672

`o.Edges` could possibly be null, should add a check before calling `Clone()`

**Comment by pharan** [comment]
Thanks for reporting!
