### ISSUE TITLE
The issue in C runtime.

### ISSUE THREAD

**Issue by kundelstein** [EsotericSoftware/spine-runtimes#870]
Hi, guys! I think there might be an issue with your C runtime, I guess you should get a closer look at this. I didn't follow all of your code, so there is a slight chance I'm barking at the wrong tree. PS. I don't have any Spline licenses, I just got a look at your software this weekend.

File: SkeletonJson.c 
Line: 351

Current code is:
			} else if (strcmp(timelineName, "mix")) {
Should be:
			} else if (strcmp(timelineName, "mix") == 0) {

**Comment by badlogic** [comment]
Good find! Thanks, fixed.
