### ISSUE TITLE
The issue in C runtime (animation.c, line821).

### ISSUE THREAD

**Issue by kundelstein** [EsotericSoftware/spine-runtimes#875]
Hi again. Check if you are sure about this code:

File: Animation.c
Line: 821

Current code is:
	CONST_CAST(float**, self->frameVertices) = CALLOC(float*, framesCount);
Should be:
	CONST_CAST(float**, self->frameVertices) = CALLOC(float*, frameVerticesCount);

**Comment by badlogic** [comment]
Thanks, definitely a bug!

**Comment by kundelstein** [comment]
I have analyzed the code. I'm terribly sorry, but I think I have misled you. This is the array of arrays, where one is using frames and the second is having the vertices. So the code was correct, it is setting the number of frames here and somewhere further it was setting the sub-array of vertices.

**Comment by badlogic** [comment]
I ran our leak test and it appears the allocations are all correct. Had the same thought as you initially, should have had my coffee :)
