### ISSUE TITLE
[unity] Cloned attachment not returned

### ISSUE THREAD

**Issue by Ran-QUAN** [EsotericSoftware/spine-runtimes#878]
Position:
 - [Clone bounding box](https://github.com/EsotericSoftware/spine-runtimes/blob/bcffbcb725a8f6796524933da04f7a358e0e15f7/spine-unity/Assets/spine-unity/Modules/AttachmentTools/AttachmentTools.cs#L672)
 - [Clone mesh](https://github.com/EsotericSoftware/spine-runtimes/blob/bcffbcb725a8f6796524933da04f7a358e0e15f7/spine-unity/Assets/spine-unity/Modules/AttachmentTools/AttachmentTools.cs#L723)

Wrong return value, original attachments are returned by clone methods.

Hunted for a week :sob:

**Comment by pharan** [comment]
Oh crud. Thanks for reporting! Sorry for the trouble!
Will fix it right away.

Obviously, nobody clones BoundingBoxes. Certainly not in Spine-Unity. : p

**Comment by pharan** [comment]
https://github.com/EsotericSoftware/spine-runtimes/commit/e4f4e61dad085cfc62664517b9a3ddf9dae2a55b
