### ISSUE TITLE
[ts][webgl][widget] Retina drawingBuffer size

### ISSUE THREAD

**Issue by geddski** [EsotericSoftware/spine-runtimes#881]
@badlogic in my tests the canvas' drawingBuffer (width and height properties) needs to match the dimensions of the skeleton or it doesn't look sharp. 

Here's an example skeleton exported from Spine where `skeleton.width` is `810` and `skeleton.height` is `954`.

With the latest retina support in Widget, scaled to .4, the model looks like this:

![image](https://cloud.githubusercontent.com/assets/515722/25153479/e9e82e80-2449-11e7-9dc4-f0788a411ab2.png)

If instead I change spine-widget to set the canvas' width and height to match the skeleton, change the scale back to 1, then the end result looks much sharper:

![image](https://cloud.githubusercontent.com/assets/515722/25153447/c845cba2-2449-11e7-8dc0-927c39cc5c8c.png)

Here is my change to Widget.ts that makes this possible: https://github.com/geddski/spine-runtimes/commit/f9a07aa2d240641c80564b8bcbe7ee99ba32d926

 If I'm doing something wrong I'd love to be corrected! Or if this is right and you want the change I can submit a PR.

**Comment by badlogic** [comment]
Hrm, I was testing it with Spineboy at scale 1. For sharp rendering you need pixel perfect rendering, which you won't get at a scale != 1. I'll check it again tomorrow. Maybe you could share this asset via email (contact@esotericsoftware.com), so we both work with the same baseline.

**Comment by geddski** [comment]
@badlogic sent!

**Comment by badlogic** [comment]
I've created a little test runner to help me see the issue. I'm testing on a MacBook Pro with retina display. Here's the code:

```
<html>
<script src="../../build/spine-widget.js"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<body>
<center>
<div id="spine-widget" style="margin-bottom: 20px; width: 640px; height: 480px;"></div>
</center>
</body>

<script>
spineWidget = new spine.SpineWidget("spine-widget", {
	json: "assets/east-hoodie.json",
	atlas: "assets/east-hoodie.atlas",
	animation: "animation",
	backgroundColor: "#222222ff",
	debug: false,
	scale: 1,
	alpha: false,
	success: function (widget) {
		var animIndex = 0;
		widget.canvas.onclick = function () {
			animIndex++;
			var animations = widget.skeleton.data.animations;
			if (animIndex >= animations.length) animIndex = 0;
			widget.setAnimation(animations[animIndex].name);
		}
	}
});
</script>
</body>
</html>
```

I'm using the latest sources from the `3.6-beta` branch. I'm using the assets you sent via e-mail. I exported them using scale `1` for the texture packer settings.

I then played around with various widget settings, e.g. scale, fitToCanvas etc. None of my tests showed any blurriness. Here's the skeleton at 0.5 scale and 1.0 scale (using the `scale` parameter of the widget configuration).

![https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-05-10%20at%202.49.46%20PM-S4h382ttIb.png](https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-05-10%20at%202.49.46%20PM-S4h382ttIb.png)

As expected, the images are 100% identical, as the underlying texture is at full resolution.

Could you modify the above example so I can see the problem on my end?

**Comment by geddski** [comment]
Yeah it must have been something else I was doing in my app. No worries.
