### ISSUE TITLE
[starling] Add filter support

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#883]
See http://esotericsoftware.com/forum/Starling-Filters-support-8331

See https://forum.starling-framework.org/topic/apply-starling-filters-to-spine-display-object

**Comment by jimmymjing** [comment]
Is the filter getting supported? I see the ready tag but it has been there a while ago. Thanks.

**Comment by jimmymjing** [comment]
Oh...Is this feature's implementation getting delayed?

**Comment by jimmymjing** [comment]
will this feature getting implemented in the near future? Thanks.

**Comment by badlogic** [comment]
I'm sorry, we have discontinued spine-starling and are therefore closing this issue.
