### ISSUE TITLE
[UE4] Spine runtime prevents packaging and crashes project

### ISSUE THREAD

**Issue by Khannarc** [EsotericSoftware/spine-runtimes#884]
Hello Esoteric team !

  Few weeks ago I started implementing some animations in my project with the spine-runtime plugin for Unreal Engine 4. It works very nicely for what I intended and the result is very promising. 

  However, due to milestone imperatives I had to package my project in order to make a Beta presentation. That's when bad stuff happened. After cleaning the whole project to prepare it for packing I had an error remaining, and so I coudn't pack the project. After some tracking I found out that the plugin was preventing the from packing. I happened to find this ticket : http://esotericsoftware.com/forum/UE4-is-such-a-good-toolkit-its-amazeballz-7975  in which the error lines were very similar to mines.

  As indicated in the ticket I proceeded to update the runtime plugin I had installed in my project. So I did exactly as told in your documentation, removed the plugins folder's content and replacing it with files from the new beta-branch (Yes, I use beta-branch). And then, horror came. I couldn't open the project anymore. It asked me to rebuild the "SpinePlugin" and "SpineEditorPlugin" dlls so I clicked "rebuild" and after a few seconds "[Project] could not be compiled. Try rebuilding from source manually. 

  So I directly my VS project file and started the rebuild solution tool. And it came up with two errors. 
"D:\Unreal Projects\ARASHI_PROJECT_BuildVersion06.8_PAck\Plugins\SpinePlugin\Source\SpinePlugin\Public\spine-c\src\spine\PathConstraint.c(202): error C2124: division ou modulo par zéro"
Which basically means there is a divide by zero happening somewhere in the plugin files
AND
 "UBT error : Failed to produce item: D:\Unreal Projects\ARASHI_PROJECT_BuildVersion06.8_PAck\Plugins\SpinePlugin\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-SpinePlugin.lib"
Which I don't understand at all.

Right now I'm stuck with an unusable project and am forced to rollback three weeks of work with your plugin in order to get a buildable version. Yet, please understand I'm not mad at you or anything, just a bit lost since I'm not a programmer and have to rely on trial and error to get things to work when it involves code and stuff.

  I hope you will be able to give me a solution for this problem soon. Please don't hesitate to contact me if you need any additional informations.

  Best regards, Thomas.

**Comment by badlogic** [comment]
Sorry for the inconvenience. I'ved fixed this in the 3.6-beta branch via this commit 69711476fc457ffb31765870d01bb1470e44ac59

Please get the latest code for spine-c from the 3.6-beta branch and copy it to your UE4 project. Let me know if this doesn't resolve the error for you.

**Comment by Khannarc** [comment]
"BUILD SUCCESSFULL"

Praise Badlogic.

**Comment by badlogic** [comment]
Thank you, thank you, I'll be here all week. Thanks for reporting!
