### ISSUE TITLE
spine runtime for cocos2dx

### ISSUE THREAD

**Issue by nanmuyao** [EsotericSoftware/spine-runtimes#887]
In spine-runtimes/spine-cocos2dx/src/spine/Cocos2dAttachmentLoader.h this header, line 34:#include <spine/AtlasAttachmentLoader.h>   @Fraggle  
    There is no AtlasAttachmentLoader.h in spine folder, please, i need this,thanks alot.

**Comment by badlogic** [comment]
Hi! How did you setup your project? The file you need is in spine-c/. See the cocos2dx example in this repository on how a project using Spine is setup.
