### ISSUE TITLE
[runtime-c] move a bone position to a world space coordinate

### ISSUE THREAD

**Issue by mkdotcom** [EsotericSoftware/spine-runtimes#888]
Hello

In runtime-c :
How can I move a bone position to a world space coordinate ?

I tried to do this:

spBone_worldToLocal(bone, worldX, worldY , &bone->x, &bone->y);

but result is not good :)

thanks a lot

**Comment by badlogic** [comment]
You can directly set `bone->worldX/worldY` on a bone. However, if you then call `spSkeleton_updateWorldTransform`, or `spAnimationState_apply`, those positions will be overwritten again.

For scaling, shear and rotation, you need to modify `bone->a/b/c/d`.

**Comment by mkdotcom** [comment]
bone->worldX and bone->worldY are const, they can't be modified

**Comment by badlogic** [comment]
You can use the `CONST_CAST` macro, e.g. `CONST_CAST(float, bone->worldX) = myValue;`, or simply remove the const modifier on the field in the struct in your local copy of the runtime.

**Comment by mkdotcom** [comment]
i tried, it doesn't do anything, and i guess it make sense as the skeleton can't be applied using the new worldpos of the bones, because i guess the runtime uses the bone->x and bone->y to transform the skeleton

**Comment by badlogic** [comment]
As I said, the order of setting the worldX/worldY fields and calling spSkeleton_updateWorldTransform/spAnimationState_apply is important.

If you set the fields before calling these two methods, the values will be ignored and recomputed.

If you set the fields after calling these two methods, the values will stay and be used for rendering. Note however, that the new values will only affect the bone you set them on, not the children (that's computed in the two methods mentioned, which would overwrite your values).

You can also set x/y  of the bone by transforming your world position to a bone's local position. For that, call `spBone_worldToLocal(bone->parent, worldX, worldY, &localX, &localY)`. Then set the localX/localY on the bone's fields. Then call spSkeleton_updateWorldTransform.

**Comment by mkdotcom** [comment]
thanks you for you answer
that's my issue, i don't manage to make spBone_worldToLocal() to works correctly

**Comment by badlogic** [comment]
Remember that you need to calculate world to local in the bone's parent
space (pass bone->parent, not bone).

**Comment by mkdotcom** [comment]
actually i didn't know that... that fixed it! 👍 
thanks you so much 🥇 
I guess it's on the doc somewhere but I didn't seen it, sorry :/

**Comment by badlogic** [comment]
No problem! May I suggest that you sign up on our forums at https://esotericsoftware.com/forum for future questions? That way more people see the questions and answers!
