### ISSUE TITLE
[corona] Provide physics integration example

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#892]
See http://esotericsoftware.com/forum/Corona-Help-to-position-bounding-box-on-a-bone-1855?p=38645#p38645

**Comment by kadlugan** [comment]
Howdy badlogic, its kadlugan from the esoteric forums here. I hope things are going well. 

I noticed a change of status for this issue to 'ready'.  Does this mean that you have a working example up and running?  Fingers crossed. :)

**Comment by badlogic** [comment]
I've looked into it already. It's a mess because the physics API of Corona is pretty terrible. Any bounding shapes we submit will be centered automatically (!!!) and there's no obvious way how to compensate for this. I'll keep trying to make something sane.

**Comment by kadlugan** [comment]
Thanks badlogic,  

Yeah, it does seem to be a recurring issue of getting deep enough access via the API to do what you need in a simple way.  I appreciate your continued persistence.     The following are a couple of suggestions  - you may have already considered as you know more about the challenges than i do. 

Have you tried using an outline body or chain body?
https://docs.coronalabs.com/guide/physics/physicsBodies/index.html#outline-bodies
Some suggestions point to compensating for centering using this approach 
https://forums.coronalabs.com/topic/41422-problem-with-polygon-based-physic-body-position/page-2
https://stackoverflow.com/questions/5271583/center-of-gravity-of-a-polygon
https://stackoverflow.com/a/30874002/6652017

There are quite a lot of changes going on at the corona service that includes opening up the code base to allow more to be done (as i understand). They have recently opened up the corona enterprise native API which might give you more access. 
https://docs.coronalabs.com/native/C/index.html

You might be able to create a plugin to do what you need using spine-c features.
https://docs.coronalabs.com/native/plugin/index.html
https://docs.coronalabs.com/native/plugin/luaplugin.html

If there are particular issues that you can describe, its not a bad idea to repost your problems back to the corona forums and let some of the gurus there have a crack.   (eg Brent Sorrentino, Rob Miracle, roaminggamer, starcrunch)   

Im happy to help where i can

**Comment by badlogic** [comment]
Posted a possible solution here https://forums.coronalabs.com/topic/69888-is-it-possible-in-corona-walking-simulation-with-physics-and-smooth-movement/?p=364581

Many limitations!
