### ISSUE TITLE
[lua] BUG - Linked meshes and skins

### ISSUE THREAD

**Issue by torbenratzlaff** [EsotericSoftware/spine-runtimes#893]
In SkeletonJson.lua line 249 a function call needs to be changed.

The current version
`skeletonData.findSkin(linkedMesh.skin)`
produces an error, as the function needs to be called with a colon character instead
`skeletonData:findSkin(linkedMesh.skin)`
this is because the corresponding function in SkeletonData.lua is defined with a colon character too.

**Comment by badlogic** [comment]
Thanks for reporting! Fixed in master and 3.6-beta branch.
