### ISSUE TITLE
[Unity] Import skeletondata.asset files error in Unity Editor for OSX

### ISSUE THREAD

**Issue by tuzihao** [EsotericSoftware/spine-runtimes#894]
Unity(Latest version 5.6.0f3 - iOS platform) would freeze when import SkeletonData.asset file generated by spine

**Comment by pharan** [comment]
Are you saying the Unity Editor freezes? Or it freezes when testing on the device?

Were there any errors logged?

**Comment by tuzihao** [comment]
**Unity** freezes when I **open project**. There is Unity crashlog in the **/Library/CrashedAssetImports.txt**. It freezes when import **skeletondata.asset**. But import this data after project opened, it would succeed.

**Comment by pharan** [comment]
So Unity editor freezes.
Are you using Unity for macOS/OS X?
We have not seen this problem yet but thanks for reporting. We still need to investigate the cause on a test machine.

**Comment by tuzihao** [comment]
Yes MacOS Sierra Unity 5.6.0

**Comment by ownself** [comment]
I met same issue here, with Mac Unity, 5.6.1f1, editor freezes when "importing small assets". after open log, it stops at importing SkeletonData.asset

**Comment by pharan** [comment]
Thanks for sharing, @ownself!

**Comment by pharan** [comment]
I wasn't able to reproduce this crash.
Unity 5.6.1 in OSX, I had Metal enabled and tried to import a raw set of json, atlas.txt and png. I separately tested importing a set with SkeletonDataAsset and AtlasAsset. No crashes.
So this might may not be happening to all setups.

In any case, disabling "Metal API in Editor" seems to have helped people who have run into this problem.

**Comment by ownself** [comment]
I disabled "Metal API" and the problem's gone. Thx mate!

**Comment by remmarcoux** [comment]
Having the same issue when I checkout my project on a Mac. According to this issue ([link](https://issuetracker.unity3d.com/issues/macos-metal-unable-to-open-project-after-enabling-metal-editor-support-star-experimental-and-deleting-library-folder)) it would start after deleting your Library Folder. In my case, the workstation never had a Library folder to begin with, so it was never populated beforehand, therefore the issue might be related in this fashion...

**Comment by MrMengis** [comment]
We are experiencing this problem on macOS 10.12.6 with Unity 5.6.3p1. Can someone explain how to disable the "Metal API in Editor" please?

*Update: for anyone curious the answer is to change {project root folder}/ProjectSettings/ProjectSettings.asset
from:
  metalEditorSupport: 1 
to:
  metalEditorSupport: 0

**Comment by pharan** [comment]
You could have also accessed it in one of the preferences menu inspectors. I forget which one, I'm currently not on a mac.

**Comment by MrMengis** [comment]
> You could have also accessed it in one of the preferences menu inspectors. I forget which one, I'm currently not on a mac.

Unfortunately, using the editor was not an option as the project could not be opened using the metal API without significant changes to the Assets/ data. A 1 character change in a single text file seemed the less invasive workaround.

**Comment by chaixl** [comment]
Having the same issue

**Comment by homes815** [comment]
try this.

spine-unity/Asset Types/Editor/SkeletonDataAssetInspector.cs

 #if UNITY_EDITOR_WIN
[CustomEditor(typeof(SkeletonDataAsset)), CanEditMultipleObjects]
#endif
public class SkeletonDataAssetInspector : UnityEditor.Editor

**Comment by pharan** [comment]
If someone is still having this issue in the latest versions of Unity, please post a comment.

**Comment by fightingplane** [comment]
I'm still suffering this bug in Unity 5.6.0f1
