### ISSUE TITLE
[Unity]Import Error

### ISSUE THREAD

**Issue by fangzhou111** [EsotericSoftware/spine-runtimes#896]
![image](https://cloud.githubusercontent.com/assets/28536341/25808468/c2cdfa66-343c-11e7-89dd-20a8cf92255c.png)
there is no class textureloader and some more

**Comment by pharan** [comment]
Are you adding spine-unity from github?
We recommend using the spine-unity.unitypackage download page instead. http://esotericsoftware.com/spine-unity-download/

But if you need to use github, make sure you import both `spine-unity` and `spine-csharp`.

**Comment by fangzhou111** [comment]
i got it,thank you
