### ISSUE TITLE
API for renderer manipulation of world vertices

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#898]
This is an API to specify a function the renderer applies to world vertices just before rendering. This enables vertex shader-like effects: sine wave distortion, swirl, etc. We could provide some effects out of the box and users can develop their own.

See https://github.com/EsotericSoftware/spine-runtimes/commit/42fa637508745bcb593830ec47b42e2ce500f62a

- [x] spine-libgdx

---
- [x] spine-csharp (API is not part of core as it won't be shared between XNA & Unity)
- [x] spine-xna
- [x] spine-monogame
- [x] spine-unity
- [x] spine-tk2d

---
- [x] spine-c
- [x] spine-sfml
- [x] spine-cocos2d-objc
- [x] spine-cocos2dx
- [x] spine-ue4 (not available, use custom materials instead, more efficient and easier to author!)

---
- [x] spine-ts core
- [x] spine-ts webgl
- [x] spine-ts canvas (not supported)
- [x] spine-ts threejs

---
- [x] spine-as3
- [x] spine-starling

---
- [x] spine-lua
- [x] spine-love
- [x] spine-corona

**Comment by badlogic** [comment]
See https://github.com/EsotericSoftware/spine-runtimes/commit/42fa637508745bcb593830ec47b42e2ce500f62a

- [x] spine-libgdx

---
- [ ] spine-csharp
- [ ] spine-xna
- [ ] spine-monogame
- [ ] spine-unity
- [ ] spine-tk2d

---
- [ ] spine-c
- [ ] spine-sfml
- [ ] spine-cocos2d-objc
- [ ] spine-cocos2dx
- [ ] spine-ue4

---
- [ ] spine-ts core
- [ ] spine-ts webgl
- [ ] spine-ts canvas
- [ ] spine-ts threejs

---
- [ ] spine-as3
- [ ] spine-starling

---
- [ ] spine-lua
- [ ] spine-love
- [ ] spine-corona
