### ISSUE TITLE
[ue4] Can't compile with UE 4.16

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#910]
Build tool is broken again. Sent PR, see https://github.com/EpicGames/UnrealEngine/pull/3621

**Comment by Bloodwork** [comment]
The link is not public. Leads to 404. I guess only the creator of the ticket can view it? 

I guess I'll stick with 4.15 for now.

**Comment by badlogic** [comment]
The link is to the PR on Epic's Unreal repository. You should have access to that if you use UE. The PR has been merged. You'll need to recompile the Unreal Build Tool project and replace the .exe in your local installation of UE 4.16 until Epic releases the next update.

**Comment by Bloodwork** [comment]
I've not tried compiling yet but this seems to be fixed in 4.16.1?

> Fixed!	UE-45455	GitHub 3621 : Fix regression in compiling plain .c files with MSVC++

https://forums.unrealengine.com/showthread.php?146431-4-16-1-Hotfix-Released

**Comment by badlogic** [comment]
Wonderful! Thanks for notifying me.
