### ISSUE TITLE
[libgdx]getAttachment in Skin Multithreaded error

### ISSUE THREAD

**Issue by StoneChiu** [EsotericSoftware/spine-runtimes#911]
I think the Key lookup in Skin should not be static, it may cause some problem in multithreaded, or make the getAttachment method synchronized.

**Comment by NathanSweet** [comment]
I don't mind it being non-static, it's safer as you mentioned. After `lookup` is non-static, then multiple threads can concurrently call `getAttachment` only if other threads are not calling `addAttachment` or `clear`. Other Skin methods must not be used by multiple threads concurrently (well, `getName` and `toString` are safe).

Note that modifying a skin (or any skeleton data object in general) which is in use by another thread is unsafe unless both threads are synchronized.
