### ISSUE TITLE
[spine-c] Calling spBone_worldToLocal for the first time before calling spSkeleton_updateWorldTransform returns NaN

### ISSUE THREAD

**Issue by snake5** [EsotericSoftware/spine-runtimes#924]
I'm setting IK bone location to a world position. For this purpose I used spBone_worldToLocal to convert world position to a local position that I could give to the bone.

When I called `spBone_worldToLocal` before ever calling `spSkeleton_updateWorldTransform` on the skeleton, I received NaN local X and Y values, which in a typical plague-like fashion wrecked all further computation. Traced the issue down to `float invDet = 1 / (a * d - b * c);`, that sometimes was a division by zero, which in practice only seems to happen with freshly initialized bone data.

So I'd like to propose this change to initialize the matrix and fix the issue:

```
Index: Bone.c
===================================================================
--- Bone.c	(revision 1251)
+++ Bone.c	(working copy)
@@ -47,6 +47,8 @@
 	CONST_CAST(spSkeleton*, self->skeleton) = skeleton;
 	CONST_CAST(spBone*, self->parent) = parent;
 	spBone_setToSetupPose(self);
+	CONST_CAST(float, self->a) = 1.0f;
+	CONST_CAST(float, self->d) = 1.0f;
 	return self;
 }
```

The data `spBone_worldToLocal` returns will be wrong either way for the first frame (which can be easily discarded), I'd just prefer that it didn't mess everything else up further down the road.

**Comment by pharan** [comment]
So why not call updateWorldTransform before doing your first operation? Or make sure your operation is always done after the updateWorldTransform of every frame?

**Comment by snake5** [comment]
What's the point of that when it's both faster and less confusing to just initialize the matrix properly? There are lots of ways to solve the problem, I'm sure. I just don't want to pick the one that's going to make me look for the same bug more than once.

**Comment by badlogic** [comment]
I think initializing the transform matrix to identity on creation of a bone is a good idea. Nothing is more annoying than tracing NaNs.

**Comment by pharan** [comment]
True that you'd get rid of NaNs. (Not saying having the identity matrix is a bad idea).

But it would still be wrong for every frame, not just the first one, since every frame, you'd be getting the value from the previous pose/frame.

**Comment by archo5** [comment]
Well, there doesn't seem to be a way to give IK targets absolute position, so it's a choice between "last frame world-to-local transform" and "last frame IK results", of which I prefer the first option. Absolute-position IK targets is another feature to consider, by the way.

**Comment by badlogic** [comment]
If your IK target isn't 1) constraint and 2) directly attached to the root bone, you may get away with directly setting its position. It's an ill-defined problem though in a hierarchical system like a skeleton. Since bone positions are given in local space, there's no way around calculating the local transforms (and thus coordinate spaces) before being able to convert a world position to a local coordinate system. Still nice to initialize bone transforms to identity, pushed a fix.
