### ISSUE TITLE
[csharp/unity] Clipping has extra triangles sometimes.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#937]
http://esotericsoftware.com/forum/Clipping-Bug-8966

SkeletonViewer
![nvidia share_2017-07-11_07-22-57](https://user-images.githubusercontent.com/1911082/28044403-c99c3c6e-6609-11e7-856f-8ae641052ac8.png)

Spine-Unity
![nvidia share_2017-07-11_07-12-45](https://user-images.githubusercontent.com/1911082/28044373-9f4a3132-6609-11e7-8d76-827b6ceb4330.png)

**Comment by pharan** [comment]
@badlogic 
Looks like XNA/MXA for Visual Studio 2017 is broken.
Do you have a working setup you can test the repro export with?

**Comment by badlogic** [comment]
Tested in XNA (VS15), no extra triangles as far as I can see. Clipping looks correct.

**Comment by pharan** [comment]
Ok, that helps narrow it down.
Should be on spine-unity's renderer side.

**Comment by pharan** [comment]
Note the same number of verts and tris.

No bug when flipped.
![image](https://user-images.githubusercontent.com/1911082/28145840-00044806-67a8-11e7-9e27-9dfeedc6acad.png)

Bug state. It's fanning the wrong way? Is this the triangulator?
![image](https://user-images.githubusercontent.com/1911082/28145844-0f20b5ae-67a8-11e7-833b-70288391b556.png)

Extra triangles aren't at the start or end of the buffers so it's likely not a count issue.

**Comment by pharan** [comment]
[simpler clipping bug repro.zip](https://github.com/EsotericSoftware/spine-runtimes/files/1149968/simpler.clipping.bug.repro.zip)

input into SkeletonClipper
```
vertices  {7.762, -4.199, -7.575, -4.167, -7.553, 6.138, 7.784, 6.105}
triangles  {0, 1, 2, 2, 3, 0}
uvs  {0.758, 0.488, 0.008, 0.488, 0.008, 0.992, 0.758, 0.992}
```

output from SkeletonClipper
```
vertices  {0.487, 0.434, 0.626, 0.618, 2.569, -0.694, -4.367, -1.603, -4.377, -0.104, -0.419, 0.334, 0.751, -1.61, 2.569, -0.694, 0.626, 0.618, 0.744, 0.773, 4.492, 1.847, 4.268, -1.614}
triangles  {0, 1, 2, 3, 4, 5, 3, 5, 6, 7, 8, 9, 7, 9, 10, 7, 10, 11}
uvs  {0.402, 0.714, 0.408, 0.723, 0.503, 0.659, 0.164, 0.614, 0.164, 0.687, 0.357, 0.709, 0.415, 0.614, 0.503, 0.659, 0.408, 0.723, 0.414, 0.731, 0.597, 0.784, 0.587, 0.614}
```

UnityEngine Mesh Data
```
vertices  {(0.487, 0.434, 0), (0.626, 0.618, 0), (2.569, -0.694, 0), (-4.367, -1.603, 0), (-4.377, -0.104, 0), (-0.419, 0.334, 0), (0.751, -1.61, 0), (2.569, -0.694, 0), (0.626, 0.618, 0), (0.744, 0.773, 0), (4.492, 1.847, 0), (4.268, -1.614, 0)}
triangles  {0, 1, 2, 3, 4, 5, 3, 5, 6, 7, 8, 9, 7, 9, 10, 7, 10, 11}
uvs  {(0.402, 0.714), (0.408, 0.723), (0.503, 0.659), (0.164, 0.614), (0.164, 0.687), (0.357, 0.709), (0.415, 0.614), (0.503, 0.659), (0.408, 0.723), (0.414, 0.731), (0.597, 0.784), (0.587, 0.614)}
```

**Comment by badlogic** [comment]
Taking this on. I'll try to repro in XNA again, need to write a debug renderer first. My guess is that the translation of some of the labeled gotos is still borked.

**Comment by badlogic** [comment]
Bug was in Triangulator, mistranslated `break outer`
