### ISSUE TITLE
[unity] Unity 2017.x Sprite Atlas Support

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#940]
Unity 2017.1 introduces SpriteAtlas, which is a new asset type that has a collection of Sprites for Unity to pack. It gives control over output texture and packing settings.

This may remove the need for the (re)packing step or Spine-Unity's reliance on the Spine/libGDX atlas format. But it likely won't be able to handle all cases. This includes:
- images with subfolder paths ("goblingirl/forearm")

Current issues:
- subfolder paths won't be supported.
- Unity 2017.1 seems to pack square POT textures when Tight Packing is disabled. Is this a bug?

https://docs.unity3d.com/2017.1/Documentation/ScriptReference/U2D.SpriteAtlas.html
UnityEngine.U2D.SpriteAtlas Inspector
![image](https://user-images.githubusercontent.com/1911082/28099847-70d966fe-66f1-11e7-8594-490c42e9e956.png)

**Comment by HDANILO** [comment]
Do we have an ETA on this? It would be awesome.

**Comment by pharan** [comment]
I wouldn't count on it on 2017.1.
There seems to be problems with how Unity Sprite Atlas assets work that we can't use it as a suitable/reliable replacement yet.
We'll see what changes in future Unity versions.

**Comment by vzlomvl** [comment]
Hello. Any news on this topic? I am using Unity 2017.2.1f1 and seems "Unity 2017.1 pack square POT textures when Tight Packing is disabled" problem is gone. It would be great use Sprite Atlas with Spine.
![image](https://user-images.githubusercontent.com/17579325/34263229-71a4906c-e677-11e7-92ab-97352a5a0511.png)

**Comment by AdrianRamis** [comment]
Any news on this?

**Comment by pharan** [comment]
No news currently, though it's good that the POT packing thing was fixed.
We'll probably shoot for Spine 3.7.

Subfolder paths on the editor side still presents a problem.

**Comment by pharan** [comment]
Revisiting this for 3.7
The runtime implementation is working. But there's a lot of editor weirdness that needs to be fixed.

The current implementation has the user populating a List<Sprite> in the inspector.
UnityEngine.U2D.SpriteAtlas 's API for retrieving Sprite data returns clones of Sprites, and appends "(Clone)" to the end of their names, which makes the initial setup suboptimal and quite stupid, tbh, though the workaround is not impossible.

The shaders in 3.7-beta branch also now has a "Straight Alpha Texture" checkbox which allows the user to use non-PMA textures like ones packed by Unity's Sprite packer. The new SpriteAtlasAsset type comes with a template material that has this enabled.

Editor stuff still to be implemented/fixed:
- [x] Menu for generating a SpriteAtlasAsset from a SpriteAtlas.
- [x] User notes for how the template material works
- [ ] Detect tight packing on the SpriteAtlasAsset, and warn the user accordingly.
- [ ] Detect disabled atlas packing in Unity Editor settings (is this possible?) and warn the user accordingly.
- [x] for some reason, the SkeletonDataAsset inspector breaks when it's using a SpriteAtlasAsset.
- [x] Detect the transition from play mode to edit mode despite not being selected, then force reload if non-existent materials or textures are detected. Otherwise, pink boxes everywhere.
- [ ] SkeletonGraphic doesn't preview correctly in edit mode because Unity atlases are not packed in edit mode. It's only able to use the first texture, so all attachments look like they use the first sprite in the SpriteAtlas.

**Comment by pharan** [comment]
@vzlomvl It looks like it's still packing as square POT in 2018.1
![image](https://user-images.githubusercontent.com/1911082/41385490-95f72554-6fae-11e8-8fd8-8e4db76e3ca0.png)

**Comment by vzlomvl** [comment]
@pharan No. For example if you set the padding equal 2 you get this(in Unity 2018.1.4f1):
![image](https://user-images.githubusercontent.com/17579325/41393911-9d155656-6fb0-11e8-82b5-8ff856395a3d.png)

**Comment by pharan** [comment]
@vzlomvl Strange. So it's a bug. If your padding is 4 or 8, it'll pack square POT. If you set it to 2, it will work correctly.

4 seems to be the default so we need to warn people.

**Comment by vzlomvl** [comment]
@pharan Seems like when the padding is 4 the textures doesn't fit in 1024x2048 and Unity pack it in 2048x2048(next POT size). I set the padding equal 4 and removed the head texture. After that Unity packed non square texture(1024x2048).
![image](https://user-images.githubusercontent.com/17579325/41434235-bad1076c-7023-11e8-992d-8c0030667a98.png)

**Comment by vzlomvl** [comment]
@pharan  In Unity 2018.2, UnityEditor.U2D namespace was added. https://docs.unity3d.com/2018.2/Documentation/ScriptReference/U2D.SpriteAtlasExtensions.html

**Comment by pharan** [comment]
I think it was already in the U2D namespace in 2017.something.
I did get a bit lost trying to find it at first. Thanks for the info.

**Comment by pharan** [comment]
Oh you meant UnityEditor.U2D.
Might be useful.

**Comment by vzlomvl** [comment]
Hi @pharan. Any news on this feature?

**Comment by HaraldCsaszar** [comment]
As described on the forum posting here:
http://esotericsoftware.com/forum/Unity-Sprite-Atlas-Support-11538

**Comment by ledvinam** [comment]
This is really exciting. ;-) though SpriteAtlas absolutely sucks. Particularly the atlas sizes and atlas max size.

**Comment by vzlomvl** [comment]
Amazing 😍 Thanks.
