### ISSUE TITLE
[cocos2d-x] SpineSkeleton keeps rendering if the opacity of a parent node is zero

### ISSUE THREAD

**Issue by ForestRingGames** [EsotericSoftware/spine-runtimes#942]
So we've got this node hierarchy:

SomeCCNode (Opacity 0)
----SkeletonAnimation

In this case the SkeletonAnimation is still producing renderer commands that cause OpenGl draw calls - even though nothing is visible. We've debugged this with the Xcode OpenGL Frame tool. We see the geometry, but nothing is visible and OpenGL calls get "wasted".

**Comment by badlogic** [comment]
Ah, good catch! We can make it so that nothing is rendered when the node's (inherited) opacity is 0!

**Comment by pharan** [comment]
Is it standard in cocos2dx to not issue draw calls when the node opacity is zero?

**Comment by badlogic** [comment]
@pharan It's up to the Node implementation. Not submitting draw calls when opacity is zero is a good default.

**Comment by badlogic** [comment]
Fixed, but per attachment.
