### ISSUE TITLE
[unity] Unity 2017 Timeline/Playables support

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#943]
"Timeline is a powerful new visual tool that allows you to create cinematic content such as cutscenes and trailers, gameplay sequences, and much more."

It's basically an animation sequencer built into Unity Editor and the Unity engine. It's not only for cutscenes. It's for any, moderately complex, sequence of animations that can play even while the player is running around in-game.

Unity designed their Timeline/Playables API and systems to be extensible. We've been anticipating its release for a while now and while the APIs are still in flux, now seems to be a good time to start with basic support.

Talks
https://www.youtube.com/watch?v=oZRp8c1Wv-o
https://www.youtube.com/watch?v=uBPRfcox5hE

Overviews
https://www.youtube.com/watch?v=yr6ki_aicnM

**Comment by gamedevcouple** [comment]
this would be the single most useful addition in ages to the program.

the ability to sequence animations with gameplay and audio and scrub through would  reduce code-bloat in animation state machine scripts and AI scripts, and open up a world of development to designers and artists.

**Comment by pharan** [comment]
There's no argument there. And we have been anticipating this API release for more than a year.

But the Playables API currently seems to be more indirect and convoluted and anticipated. (some measures they took to improve performance)
And they've already said it's going to change very soon.

We've already got the most basic thing working, no problem. But a lot of the multi-track, mixing and edge cases and also-programmatic-control are not handled yet.

**Comment by bosnian** [comment]
@pharan When can we expect the release with Timeline support(roughly)?

**Comment by pharan** [comment]
VERY ROUGHLY, likely before the year ends.
Can't give a more specific estimate currently.

**Comment by kcapelli-assf** [comment]
Hey Pharan!

My team is loving Spine: we've never gotten up to speed so quickly with a tool. Thanks for such an intuitive interface!

I wanted to follow up on this topic: we're in prototype right now (writing tools and defining pipelines) and planning to go into production early next year. Timeline is a necessary part of our pipeline, and Spine almost perfectly solves our particular animation needs, so Spine-Timeline support is of great interest but the end-of-year estimate/ fog of war will make us **sweat** as we pass through our prototyping period. Do you have an update, or is there anything I can help ping Unity about? (We have a longtime and good developer relationship with them plus I have colleagues on the inside I can ping/ prod).

**Comment by pharan** [comment]
We can release a unitypackage of the work-in-progress version so you can prototype with it and give us feedback. In its current form, it should be usable enough for prototypes. Though this has the risk of breaking all your stuff in the future IF we do a major refactor.

I'll probably also put it in a separate repo somewhere before it becomes officially part of the spine-unity runtime.

The big known issues are really where mixing is involved. Multi-track mixing is not handled. Single-track mixing may not behave as expected. And not all the track options are recognized

Thanks for the offer of knowledge! I'll think of something to ask if it happens.

**Comment by pharan** [comment]
spine-unity-experimental
Spine Timeline for spine-unity 3.6
2017-09-15
http://esotericsoftware.com/files/runtimes/unity/spine-unity-experimental-spine-timeline-3_6-2017-09-15.unitypackage

**Comment by ledvinam** [comment]
Hi Pharan, is there official github for spine timeline features? M.

**Comment by kcapelli-assf** [comment]
Pharan, thanks so much! Sorry for the tardy reply, I've been out sick and then catching up. My engineers are approaching this soon and I'm directing them to this thread and the package plus the SPINE documentation.

**Comment by pharan** [comment]
We've made some progress on this. Expect a new unitypackage in the next 2 or 3 days.
In this form, it's about ready to be included in the official git repo, but still marked experimental.
The basic mixing cases should already be handled.

There are still some lingering questions regarding more complex cases (multiple tracks, with AnimationState animation being applied at the same time, and in what order). Will be posting on it soon.

**Comment by pharan** [comment]
Currently, some order of execution stuff requires an extra `UpdateWorldTransform` call to the skeleton being animated, which is really not cool. The alternative may have to be disabling the SkeletonAnimation or attaching an additional new component to the Spine GameObject that handles all the quirks.

There may also just be an alternate non-editor-scrubbable clip type which just issues "commands" to SkeletonAnimation's AnimationState.

**Comment by pharan** [comment]
There are some quirks about how Timeline assets and the Playables API are actually separate things that make the editor/inspector not as friendly as it could be. Cleaning up is taking a while.

**Comment by unix2dos** [comment]
How do I get the latest code, even if it's unstable?

**Comment by pdyxs** [comment]
Any updates on this?

**Comment by pharan** [comment]
We're currently adapting it for 2017.2. Some changes seem to have made our mixing handling less reliable.

I'm adding a Spine AnimationState Timeline Track type to handle basic stuff. It just makes method (SetAnimation) calls to SkeletonAnimation's AnimationState object. This means you won't be able to scrub it in edit mode. Timeline's editor APIs currently don't have a distinction between edit mode and play mode so it can possibly mess things up if we support scrubbing naively. We can probably create dummy scrubbing behavior eventually.

Our targeted Timeline Track type is called a "Spine Animation Track". It's scrubbable and mixable and uses an extra component on the GameObject to handle the cases. And that's what we're currently having trouble with regarding mixing and fading-in-and-out taking and releasing animation control from the SkeletonAnimation/SkeletonAnimator.

Anyway, we'll have a new beta and the experimental code included in the runtime before December.

**Comment by ledvinam** [comment]
Wov, that is great news. We are waiting for this feature in order to make animated short stories in Unity. :-) Please do it "right" :-)

**Comment by pdyxs** [comment]
Thanks, looking forward to it!

**Comment by pharan** [comment]
Haha! We'll do it as "right" as Unity will allow... which is honestly looking a bit messy.

**Comment by pharan** [comment]
https://forum.unity.com/threads/default-playables-text-switcher-track-error.502903/
Also weirdly getting this error. Currently no way to get rid of it, and it seems to be a persisting bug even in 2017.3 beta.

**Comment by pharan** [comment]
For now, the experimental code and docs will be tracked here: https://github.com/pharan/spine-unity-experimental/tree/spine-timeline

I'm currently writing the how-to-use docs.
For now, the main Spine Animation Track type is quite unusable if you have mixing.

Spine AnimationState Track should be safer for now, since all it does is make SetAnimation calls for the SkeletonAnimation's AnimationState.
Normally, you can't preview animations in edit mode with it. But I've just added a preview with slightly inaccurate mixing. It's slightly inaccurate because the mixing in edit mode may not reflect exactly what mixing looks like in actual play mode.

More docs to follow. I'll link them here when available.

**Comment by pharan** [comment]
Documentation is included with the experimental Spine Timeline folder.
https://github.com/pharan/spine-unity-experimental/tree/spine-timeline/Assets/spine-unity-experimental/Spine%20Timeline/Documentation

You can find the latest unitypackage here: http://esotericsoftware.com/files/runtimes/unity/spine-unity-experimental-spine-timeline-3_6-2017-11-25.unitypackage

**Comment by MichalBerlinger** [comment]
Hi, I want to ask about a roadmap for this Timeline support.
Is it safe to use it in the current project or are you planning to change API (and so braking references etc.)?
If just features will be added, it is safe to use it even when it might be a little buggy, but it is important, that future updates will not break all prepared timelines.

**Comment by pharan** [comment]
It's safe to use Spine AnimationState Track. How it interfaces with Spine is simple (just makes SetAnimation calls according to the track arrangement) and is pretty much going to be as is. Confidently use that one, though at the moment, I wouldn't use it for any timelines that need to playback backwards.

Our current problems for the Spine timeline tracks in general is the lack of Unity's editor-side exposed references in so getting a list of animation names from the skeleton data is less convenient than we'd like it to be.

Flip timeline is fine to use too.

Everything else is up in the air.

**Comment by pharan** [comment]
It's safe to use Spine AnimationState Track. How it interfaces with Spine is simple (just makes SetAnimation calls according to the track arrangement) and is pretty much going to be as is. Confidently use that one, though at the moment, I wouldn't use it for any timelines that need to playback backwards.

Our current problems for the Spine timeline tracks in general is the lack of Unity's editor-side exposed references in so getting a list of animation names from the skeleton data is less convenient than we'd like it to be.

Flip timeline is fine to use too.

Everything else is up in the air.

**Comment by pharan** [comment]
@Abuki
With the introduction of [Animation Reference Assets](http://esotericsoftware.com/forum/PSA-Spine-Animations-as-Unity-asset-references-10201), we may switch AnimationState Tracks over to using these instead of using the SkeletonDataAsset/string pair right on the clips.

Is this change workable for you? It involves having to reassign all your existing clips using the references.

**Comment by MichalBerlinger** [comment]
I am not currently using the Timeline so from my point of view it is ok. And I guess, there could be an editor script written to replace strings with assets.

The funny thing is that I implemented something like these reference assets myself a month or two ago for my project :D

**Comment by Antemation** [comment]
Does this work for Spine UI animations as well? (Tried but didnt get it to work)
And if not, any plans on implement it for Spine UI animations as well?

**Comment by pharan** [comment]
@Antemation Currently, no. I guess we can add one just for SkeletonGraphic. Or have a separate adapter class.
Look forward to this this week. We will update this soon.

The problem is really that Unity's inspector out of the box has no support components that implement interfaces, and SkeletonGraphic uses Unity's MaskableGraphic as the class it derives from. So it can't use the same classes right now, and until Unity does implement interface fields.
