### ISSUE TITLE
[obj-c] Render Spine on custom UIView

### ISSUE THREAD

**Issue by freeubi** [EsotericSoftware/spine-runtimes#944]
Hello,

i checked the demo and it seems that the animation is drawn on a rootView. 
Instead of that, can i render it to a uiview of my choice?

**Comment by badlogic** [comment]
Hi!

The spine-cocos2d-objc runtime is for [Cocos2d-ObjC](http://www.cocos2d-iphone.org/). I'm afraid I'm not intimately familiar with Cocos2d-ObjC and can't answer your question. I suggest you consult their documentation on whether this is possible, and also ask on [their forum](http://forum.cocos2d-objc.org/).

Cheers,
Mario
