### ISSUE TITLE
[cocos2d-x] getCurrent(trackIndex) does not return nullptr even though the animation has finished playing

### ISSUE THREAD

**Issue by ForestRingGames** [EsotericSoftware/spine-runtimes#945]
Is it intended behaviour that `getCurrent(trackIndex)` returns a pointer to the last spTrackEntry, even though it has already finished playing? The track time is just ticking up to infinity, even though the end time was reached already.

I've read in several forum posts that it should return nullptr in case there is no animation playing currently.

**Comment by badlogic** [comment]
The track end time is set to a really high value by default, so the last track entry will usually linger around. However, you said the end time has already been passed, so this sounds like a bug. I'm investigating.

**Comment by ForestRingGames** [comment]
@badlogic Sorry, I was wrong. The track end has not passed, but the animationEnd of the last animation had long passt. I mixed them up. So might it even be normal behaviour that the last spTrackEntry is then staying alive?

**Comment by badlogic** [comment]
Ah, yes. That is "normal" indeed then :(
