### ISSUE TITLE
[unity]need add UNITY_2017 check

### ISSUE THREAD

**Issue by littlesome** [EsotericSoftware/spine-runtimes#950]
hi, 

unity2017 does not define UNITY_5, so some code need changes, eg:

https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-csharp/src/Atlas.cs#L47

https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-csharp/src/SkeletonBinary.cs#L31

and this way maybe better:

```
UNITY_5 || UNITY_5_3_OR_NEWER
```

https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-csharp/src/SkeletonJson.cs#L31

**Comment by pharan** [comment]
Thanks for reporting! I was so sure that was fixed.
