### ISSUE TITLE
[Unity] Manual is unclear

### ISSUE THREAD

**Issue by subzero911** [EsotericSoftware/spine-runtimes#954]
1. Add a documentation for Mecanim SkeletonAnimator API.
I don't understand how to catch custom events via SkeletonAnimator instead of SkeletonAnimation.
2. Add all possible attributes (like [SpineEvent]) documentation and usecases.
3. Some manual pages are available only through cross-links in the text. And not presents in a table of contents. Like this: http://ru.esotericsoftware.com/spine-unity-events

**Comment by pharan** [comment]
The docs are currently in flux, as is the implementation of SkeletonAnimator with some adaptations with the new 2017.1 API.

SkeletonAnimator tries to do things the way Unity does, and uses Unity Animation Events on the dummy AnimationClips. https://docs.unity3d.com/Manual/animeditor-AnimationEvents.html
ie. You need to write a method on the script with the same name as the event defined in Spine.

If you find some specific things that are unclear or missing, feel free to open an issue here: https://github.com/pharan/spine-unity-docs
