### ISSUE TITLE
[csharp] entry.trackEnd set to float.MaxValue prevents trigger of AnimationState.End

### ISSUE THREAD

**Issue by hardsetting** [EsotericSoftware/spine-runtimes#965]
I updated spine runtimes of my project to the latest version (git cloned yesterday) and I noticed that the animation callbacks I was using started behaving weirdly.

Namely, the AnimationState.End of the last animation in the track is never triggered. I noticed instead that the AnimationState.Completed is called as expected (according to [this](http://esotericsoftware.com/spine-unity-events)).

After trying different versions of the runtimes and digging a little into the code, I found out that this piece of code (taken from AnimationState.cs[AnimationState.Update] at rows 110-117):

```csharp
} else if (current.trackLast >= current.trackEnd && current.mixingFrom == null) {
	// Clear the track when there is no next entry, the track end time is reached, and there is no mixingFrom.
	tracksItems[i] = null;

	queue.End(current);
	DisposeNext(current);
	continue;
}
```

is never actually reached, even if It should be (I think), because `current.trackEnd` is always set to `float.MaxValue` when not mixing to another animation (e.g. the last animation).

Interestingly, in AnimationState.cs at row 594:
```csharp
entry.trackEnd = float.MaxValue; // loop ? float.MaxValue : animation.Duration;
```

I think that the commented code would work as expected, but obviously I am missing the big picture.

**Comment by hardsetting** [comment]
Actually using the commented line I suggested yields yet stranger results.

In my case I got the expected behavior back by changing
```csharp
} else if (current.trackLast >= current.trackEnd && current.mixingFrom == null) {
```
to
```csharp
} else if (current.trackLast >= current.animationEnd && current.mixingFrom == null) {
```

that works for me because I always have a single non-looped animation in the track.

**Comment by pharan** [comment]
This was a change in 3.4, I think.
Currently, animations(in a TrackEntry) in AnimationState don't get cleared until you clear it manually (`ClearTrack(x)`) or you specify TrackEnd. This applies to all runtimes.

Could you say in what way the commented code "yields yet stranger results"?

"track time" and "animation time" are technically on two different scales so you may get unexpected results if you compare `animationEnd` (animation data time) and `trackLast` (stateful track time).

**Comment by NathanSweet** [comment]
Sorry you hit this gotcha. We didn't like the looping vs non-looping animations having different behavior when reaching the `trackEnd`. If you want the old behavior you can set `trackEnd` to `animation.duration`. See docs here:
http://esotericsoftware.com/spine-api-reference#TrackEntry-trackEnd
