### ISSUE TITLE
[ue4] Updated to UE 4.17

### ISSUE THREAD

**Issue by badlogic** [EsotericSoftware/spine-runtimes#968]
Switch to new build system.

**Comment by badlogic** [comment]
Closed via https://github.com/EsotericSoftware/spine-runtimes/commit/e02f8b7a1cdb4634d13859e7b00037b5230311a4

**Comment by Bloodwork** [comment]
Is this already available publicly via cloning the runtimes?

**Comment by badlogic** [comment]
Yes, in both the 3.6 and 3.7-beta branches!

**Comment by Bloodwork** [comment]
Then I'm confused. I'm using the latest UE4 4.17.1 and I get this error: http://take.ms/ap1ER

**Comment by badlogic** [comment]
Could you try opening the example project in this runtime repo? I'm running that without problems in 4.17.1. If you only copied the SpinePlugin and SpineEditorPlugin, please also make sure to copy our fork of RuntimeMeshComponent to your project.
