### ISSUE TITLE
[AnimationState] Some problem with mixing out not in order.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#970]
This totalAlpha condition seems to be preventing an ended TrackEntry (mixTime > mixDuration) from actually being ended.
https://github.com/EsotericSoftware/spine-runtimes/blob/34086c1f41415309b2ecce86055f6656fcba2950/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/AnimationState.java#L147-L151
With this condition in place, it seems to present the problem linked below. Commenting it out removes it.
http://esotericsoftware.com/forum/Wrong-animation-mix-9188

The bug may also be related to this:
https://github.com/EsotericSoftware/spine-runtimes/blob/34086c1f41415309b2ecce86055f6656fcba2950/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/AnimationState.java#L222-L223

As the code passes through this branch several times instead of only once, because the TrackEntry doesn't end.

**Comment by NathanSweet** [comment]
@pharan How can I see this with the ref impl? I tried:
```
state.getData().setMix("stand", "move", 0.3f);
state.setAnimation(0, "move", true);
state.addAnimation(0, "stand", true, 2);
state.addAnimation(0, "attack_1", false, 2);
state.addAnimation(0, "move", true, 2);
state.addAnimation(0, "stand", true, 0.81f);
state.addAnimation(0, "attack_1", false, 0.2f);
```
I don't see meshes that aren't reset to the setup pose, though I don't really know what I'm looking for. I also tried using `setAnimation` with sleeps between them.

**Comment by pharan** [comment]
@NathanSweet  I actually ran into the same problem.

vzlomvl mistyped.
```
state.getData().setMix("move", "stand", 0.3f); // should be move-stand. not stand-move as vzlomvl posted.
state.setAnimation(0, "move", true);
state.addAnimation(0, "stand", true, 0.81f);
state.addAnimation(0, "attack_1", false, 0.2f); // look at her left pant leg.
```

That should repro it.
The first three animations just demonstrate a case where it isn't broken.

**Comment by NathanSweet** [comment]
Ah, thanks @pharan! I think I have a good fix.
