### ISSUE TITLE
spine-webGl how can I totally remove my obj

### ISSUE THREAD

**Issue by supermrji** [EsotericSoftware/spine-runtimes#972]
I use `spine-webGl` runtime .
I want to remove played animation spine item ,
And I set a empty frame `animationState.update(undefined);`

It seems disable but memory are still taken .
Can someone tell me how to remove spine-webGL item ?

**Comment by badlogic** [comment]
Passing undefined to the `update` method is not the solution you are looking for. With the spine-webgl runtime, you are in full control of when to render what. Simply don't render the skeleton via `SkeletonRenderer` if you don't want it to show up in your canvas, and make sure to clear the canvas via WebGL (`glClear`), to override the last rendered canvas content.

Please post questions regarding the runtimes to the forum at https://esotericsoftware.com/forum

**Comment by supermrji** [comment]
Thanks a lot . 
I will try it .
