### ISSUE TITLE
[js] Clean up

### ISSUE THREAD

**Issue by gregmax17** [EsotericSoftware/spine-runtimes#982]
Is there was to destroy/set all references to null once the mesh is removed from the scene?

**Comment by badlogic** [comment]
Could you elaborate? spine-ts doesn't have the concept of scene, but instead is an immediate mode renderer, where you issue drawing commands every frame.

**Comment by badlogic** [comment]
Closing this out, will reply to you here if you get back to me. Going forward, please use the forums at https://esotericsoftware.com/forum for questions. The issue tracker here on GitHub is meant to report bugs in one of the Spine runtimes.
