### ISSUE TITLE
[corona] Shearing + disabled scaling inheritance leads to wild flickering

### ISSUE THREAD

**Issue by torbenratzlaff** [EsotericSoftware/spine-runtimes#983]
If you create a bone for which you disable the scaling inherintance and apply an animation that uses shearing, the attached graphics will flicker wildly when used in the Corona SDK example.

**Steps to reproduce:**
1. Create a new bone
2. Attach a graphic to the bone
3. Disable the "inherit scale" checkbox for the bone
4. Create a new animation in which you use the shearing transformation (two keyframes with diffrent values)
5. Export and test with the Corona example project
6. Attached graphic flickers wildly

If "inherit scale" is active, everyhting works fine.

**Comment by badlogic** [comment]
Thanks for reporting, fixed in 3.6 and 3.7-beta branch!
