### ISSUE TITLE
[corona / lua] skeletons are updated even if there is no animation/effect playing

### ISSUE THREAD

**Issue by torbenratzlaff** [EsotericSoftware/spine-runtimes#987]
In the current version skeletons are completly updated every time you call the update functions like in the example:
`state:update(delta)
state:apply(skeleton)
skeleton:updateWorldTransform()`

Even if there is no animation playing (skeleton has been set to setup pose or last animation is not looped) the skeleton is updated as if changes had happend. This is a big performance issue.

**Here are some ideas how that could work:**
1. `state:update()`, `state:apply()` and `skeleton:updateWorldTransform()` check if something could have changed and only execute if that's the case.

2. `state:update()`, `state:apply()` check if something has changed which they return as a return value. By doing so, developers can decide to stop the update process or continue updating anyways.

3. Provide an event which indicates that a skeleton is in a waiting state so developers can stop the updates manually.

**Comment by NathanSweet** [comment]
We normally assume a skeleton has been updated every frame. It's unusual to not play any animation, usually there is idle. It's too hard to know if a skeleton was changed, but it could be reasonable to provide a property which disables updates. If you know your skeleton is dormant, you can set the property and clear it when you want updates again.

**Comment by badlogic** [comment]
The problem with tracking whether there were state changes or not is that they usually are quite expensive themselves. We've previously considered exactly that, but ultimately decided against automatic state change tracking for the reason just outlined.

You can register listeners with `AnimationState` and `TrackEntry` to get an event when animation(s) are complete. The Corona Skeleton "class" does not automatically update world transforms, you are responsible for calling that method in e.g. `enterFrame`, so you can decide if and when to call it.
