### ISSUE TITLE
bad outer

### ISSUE THREAD

**Issue by sorthoth** [EsotericSoftware/spine-runtimes#999]
https://github.com/EsotericSoftware/spine-runtimes/blob/9e97eb2bfae379a3eea41e50301b7c896dc93413/spine-c/spine-c/src/spine/AnimationState.c#L929

**Comment by badlogic** [comment]
No, this is a correct translation of the reference implementation https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/AnimationState.java#L729
